### ISSUE TITLE
⚡ [CoE Starter Kit - AUGUST UPGRADE HOWTO] Dependencies exist which make August upgrade need special steps

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#1005]
### Describe the issue

In the August release, we have removed an old dependency that is no longer used, the CoE Settings table. Upgrade from July (or previous) bits will need to proceed differently than normal as a result. 

You have two options to successfully upgrade as a result. 

**Option 1: Changing the order of upgrade.**
You will need to upgrade the dependent solutions before you upgrade Core. If possible, this is the preferred path.
Please upgrade in the following order:
1. Upgrade Nurture
2. Upgrade Gov
3. Update Audit Logs
4. Then upgrade Core

**Option 2: Chose Update rather than Upgrade.**
If you have dependencies from Core for these (aka if you are upgrading from older bits). You may need to chose update instead. This will leave the CoE Settings in place, when you upgrade the other solutions, the dependency will remove, and your later upgrade (ex in September) will remove CoE Settings. 
1. Instead of upgrade, use update to install Core August bits.

As always, be sure to remove unmanaged layers in order to see our changes. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

CoE Settings Table

**Comment by ATJSM** [comment]
I used the Update option after the Upgrade failed. Now I see 2 Core component solutions with the same version. Is this expected? I thought the previous one should have been removed.

![image](https://user-images.githubusercontent.com/13952319/129087061-44f0aa4b-0db5-4fe7-81b0-ef3a8e03289e.png)

**Comment by JeneferM-MSFT** [comment]
That is not expected. The new version is 2.75, so it looks like perhaps you used the old solution file to update?

**Comment by ATJSM** [comment]
That's weird, because I downloaded it using the link in our documentation this morning. Maybe the link was not updated with the new version?

**Comment by manuelap-msft** [comment]
@ATJSM I've checked and aka.ms/coestarterkitdownload downloads the latest version.

**Comment by jorgemorenog** [comment]
Hi,

Same as @ATJSM , the "Update" option fails. We only use the CoreComponents and the last version is from July.

The error is related to a missing dependency with the Connection Reference admin_CoECoreHTTPAZUREAD. Does it make sense?

> Failed to find connection references with logical name(s) 'admin_CoECoreHTTPAZUREAD'. Please check if connection references exists.

In our case, there is no solution duplication. Moreover, we do not have our own customizations on the components.

Thanks a lot!

**Comment by ATJSM** [comment]
> @ATJSM I've checked and aka.ms/coestarterkitdownload downloads the latest version.

Thanks, Manuela, I checked again yesterday night and the version of the download link was pointing to 2.75 version. But yesterday morning it was not pointing to that version. It might have been that the redirection was not yet updated to point to the newer version.

My main issue right now is what to do next. Do I need to delete both solutions and deploy CoE again. Just delete 1 solution?

**Comment by JeneferM-MSFT** [comment]
@ATJSM , you should be able to delete the one just installed without impacting your data. It should be just an upgrade layer. 
![image](https://user-images.githubusercontent.com/62659043/129238022-e4ec0859-16f1-407c-ac68-8e3f6bf101f3.png)

**Comment by manuelap-msft** [comment]
@jorgemorenog can you confirm if you have just the Core solution already installed in the environment, or if you have both Core and Core for Teams installed in this environment?

**Comment by jorgemorenog** [comment]
@JeneferM-MSFT @manuelap-msft thanks for the feedback. I can confirm:
- We have **only** the Core solution (not the Core for Teams)
- We also have the CoE HTTP Azure AD connection reference (as the image shows. Checked schema name too)

![image](https://user-images.githubusercontent.com/10724478/129332416-e586364c-4503-4aa8-bbe1-7896eb1f8983.png)

That's why it is weird this issue :|

**Comment by manuelap-msft** [comment]
If you select the ... next to the CoE Core - HTTP AZURE AD connection and select show dependencies, can you share what dependencies it shows there? Thank you!

**Comment by jorgemorenog** [comment]
My mistake, @manuelap-msft ! Here is the image with the dependencies:

![image](https://user-images.githubusercontent.com/10724478/129346110-37278168-8d5c-4ff9-a655-3479b767ed9a.png)

![image](https://user-images.githubusercontent.com/10724478/129346143-a251076a-a229-4394-82a1-6f456d34370f.png)

**Comment by mduqueBasf** [comment]
Hi @manuelap-msft  and @JeneferM-MSFT . The same here in BASF. Update does not work for CoreComponents The rest of the solutions are OK . Latest Core was June. 

My Core Http Azure AD Dependencies are:

![image](https://user-images.githubusercontent.com/64835119/130574682-18423b63-c1c3-474c-be92-0f9ff727d995.png)

**Comment by JeneferM-MSFT** [comment]
Can you please try with this version of Core? 
[CenterofExcellenceCoreComponents_2_77_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7039490/CenterofExcellenceCoreComponents_2_77_managed.zip)

**Comment by JeneferM-MSFT** [comment]
And please try to install [the version above, 2.77](https://github.com/microsoft/coe-starter-kit/files/7039490/CenterofExcellenceCoreComponents_2_77_managed.zip) via overwrite upgrade in the classic UX  

Solution > Switch to Classic (note this can take some time, may have to try twice)  
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png) 

Click Import (fourth from the left)  
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png) 

Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import  
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png) 
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by mduqueBasf** [comment]
Hi @JeneferM-MSFT  and @manuelap-msft 2.77 Installation Upgrade from Classic was just fine! Thanks!

**Comment by GarryPope** [comment]
Hello @JeneferM-MSFT,

I hope you are well. I'm sorry to bother you, but I need some help please. I'm trying to follow the above, but I think I must be doing something wrong. Okay, here goes at explaining it. Sorry it's so long. 

We only have the "Center of Excellence - Core Components" solution installed, 
schema name "CenterofExcellenceCoreComponents".
We were on version 2.1.6.

Last Friday I tried to install the same solution but with version 2.77. This failed. 

Today I started reading the above and switched over to the classic UI to try and import again. 
In the import options I used: 
"Solution Action" = "Upgrade (recommended)"
"Previous customizations on components included in this solution" = "Override customizations (not recommended).

This installed version 2.77 but left the _Upgrade solution behind. 
So now, when I look in Solutions in my environment I still see my "Center of Excellence - Core Components" version 2.1.6 with schema name "CenterofExcellenceCoreComponents", 
but also the "Center of Excellence - Core Components" with schema name "CenterofExcellenceCoreComponents_Upgrade"

![image](https://user-images.githubusercontent.com/68440710/132241312-e9eb48be-ad34-40d9-8963-2f833d4b7927.png)

In Solution History it also confirms that the Upgrade has failed. 

![image](https://user-images.githubusercontent.com/68440710/132241421-fd9c3e91-0f3b-438b-aa72-3aae39da6c6c.png)

I also checked the "CoE Core - HTTP Azure AD" as @manuelap-msft suggested above to someone and it too is showing the dependencies. 

![image](https://user-images.githubusercontent.com/68440710/132241697-557794f9-7756-4d73-830b-b5036709cecb.png)

Any ideas what I'm doing wrong here please? Thanks very much.

**Comment by manuelap-msft** [comment]
Hey Garry! Don't apologize - this is exactly what we're here for :) 

Could you try Importing the solution again and instead of **Upgrade** pick **Update** when you get to that step and then **Overwrite customizations** on the next step? 

With one of the last versions we had introduced some a dependency issue on the HTTP Azure AD connection reference, that we wanted to remedy and clean up with this release but it requires you to use **Update** (which is not the default) during the import to update the solution and replace all components in the solution with the new ones. 

You will know this has worked if the CenterofExcellenceCoreComponents solution (the one without the _Upgrade) changes to 2.77! Once that is done, you can safely remove/delete the _Upgrade layer that you see in the first row now. 

Let me know how you get on!

**Comment by GarryPope** [comment]
Hello @manuelap-msft,

Thanks for the reply, and nice to hear from you. 

That worked perfectly, just as you explained. If anyone is reading this with the same issue, just an FYI as I was deleting the _Upgrade solution I initially received a failure message, see below, but I did nothing and a couple of minutes later the _Upgrade solution disappeared. So ignore the failure message.

![image](https://user-images.githubusercontent.com/68440710/132280288-aac3bda8-b8d3-4c94-a7b6-de482aebcf98.png)

Thanks for all your help and have a good day,
Garry

**Comment by manuelap-msft** [comment]
Hello! Awesome, thanks for confirming - glad to hear it worked now!! :)

**Comment by paulculmsee** [comment]
I have the same issue as Garry upgrading from 2.2.20210707.3 to 2.75 and in my case I am stuck and unable to delete the upgrade. Error is "Failed to find connection references with logical name(s) 'admin_CoECoreHTTPAZUREAD'. Please check if connection references exists.” but when I look in the solution I see "admin_CoECoreHTTPAzureAD".

Is the case mismatch a packaging thing or a display/logic bug?

I cannot apply 2.77 because it tells me there is already a patch so stuck at present.

**Comment by paulculmsee** [comment]
Okay so I solved my issue with invaluable help from @JeneferM-MSFT 

1. I was sent an unmanaged version of CoE solution and installed onto a fresh tenant so that I could then use the same publisher CoE team uses
2. I deleted the old connection reference from the environment
3. I made a new solution and added a new connection reference with the admin_CoECoreHTTPAZUREAD logical name and used the same publisher as CoE so I got admin_ prefix
4. I exported this solution as unmanaged
5. I imported this solution to my problematic site. It did not make a duplicate connection ref... instead it applied an unmanaged layer to the existing admin_CoECoreHTTPAzureAD connection ref so now it had the logical name admin_CoECoreHTTPAZUREAD
6. I deleted the 2,7 patch that had previously refused to work and this time it worked!

Conclusion: There is a big in patch rollback code for solutions. It is not detecting connection references in the same way that installs do.
