### ISSUE TITLE
[CoE Starter Kit - QUESTION] Use Remove Flow as Admin in Governance flows

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1010]
### Describe the issue

Copying in from customer email: 

Here is the screenshot for the section of the flow in Governance Component of CoE Starter Kit where it deletes a Flow that is approved by owner.
Flow name - Admin | Archive and Clean Up v2 (Clean Up and Delete)

 
![image](https://user-images.githubusercontent.com/55705669/129061855-c65d9e03-8b4f-4ce8-9ecf-77198c1361b6.png)

I wanted to understand if we can replace it with single action – ‘Remove Flow as Admin’ available under  ‘Power Automate for Admins’ connector (snapshot below). This also helps avoid the notification that goes to existing owner that a new owner has been added to the flow when ‘Modify Flow Owners as Admin’ action executes.

![image](https://user-images.githubusercontent.com/55705669/129061868-83fd18e9-f93d-4e2a-a12a-bfd278b92ed7.png)

 

### Expected Behavior

Reduce API calls and actions to use Remove Flow as Admin

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

latest

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Clean Up and Delete)

**Comment by JeneferM-MSFT** [comment]
Investigating for Sept

**Comment by Jenefer-Monroe** [comment]
fixed for Sept

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
