### ISSUE TITLE
[CoE Starter Kit - BUG] upgrade issue when upgrading the Governance Components in Dataverse for Teams

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#1012]
### Describe the issue

When applying the upgrade of Governance Solution from 1.70.20210708.1 to 2.0, I get the following error message:  Upgrading solution failed. Cannot delete attribute: utcconversiontimezonecode from Entity: admin_ArchiveApproval since the attribute is not a custom field.

### Expected Behavior

I expected the upgrade to complete successfully.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.0

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1) Have existing environment with Governance components installed from July release.
2) Attempt upgrade to August release

(in my case, this was in a Dataverse for Teams environment, but didn't think that mattered with the Governance solution)

**Comment by JeneferM-MSFT** [comment]
I am not familiar with that attribute. Please try update instead.

**Comment by JeneferM-MSFT** [comment]
Also wondering, did you follow the steps in this noted bug? https://github.com/microsoft/coe-starter-kit/issues/1005

**Comment by bartsneary** [comment]
Unfortunately, I didn't notice the bug until I had already gone through the normal update steps doing core, then governance, then the others.  It all worked fine in my DV4T environment with core, but hit this issue with governance.  In a DV4T environment, I'm not sure how to use update instead of upgrade.  I'll try that if you can give me steps.

**Comment by MartinWhiteDAZN** [comment]
I am getting the exact same error for the same versions.
I am using the Teams version.
I am not offered the option to Update or Upgrade. It implies an Update is happening.
I have not installed the Nuture solution - would this be a problem? I only have Core and Governance installed and I have started the update using Governance as per the instructions.

![image](https://user-images.githubusercontent.com/57627519/129175916-9465550d-e2fc-4049-bd5d-ce50d1bc6c0d.png)

![image](https://user-images.githubusercontent.com/57627519/129176438-ebdd1f68-9a7d-4af5-807c-83322ebc50de.png)

**Comment by manuelap-msft** [comment]
Hello,

I'm looking into this! We used to be able to use the same Governance components solution in Production and Dataverse for Teams environments, as the solution only used things that were supported in Dataverse for Teams. Maybe a recent product change caused this issue. The field it is failing for is not one I'm familiar with, so it may be specific to Dataverse for Teams configuration.

Thank you for your patience as we investigate this,
Manuela

**Comment by manuelap-msft** [comment]
1. It looks like that experience is different in Teams, and you can't choose between Upgrade and Update
2. We have to prepare a different "Core for Teams" base solution for Teams, and it looks like we missed some dependencies here for this release that the Governance solution, which is why the import is failing. Can you try upgrading the Core for Teams solution to the one attached here, and then upgrading the Governance solution.
[CenterofExcellenceCoreComponentsTeams_2_3_managed.zip](https://github.com/microsoft/coe-starter-kit/files/6975348/CenterofExcellenceCoreComponentsTeams_2_3_managed.zip)

This worked for me when I just tested it. Once one of you can confirm this works for you also, I will change this in our released version!

Thank you
Manuela

**Comment by bartsneary** [comment]
Same experience.  Thanks for the quick fix!

**Comment by manuelap-msft** [comment]
I updated the downloadable release now - thanks for the quick testing and feedback!
