### ISSUE TITLE
[CoE Starter Kit - Documentation request] add picture showing what is needed for Flow Approvals URL 

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#1038]
### Describe the issue

At this spot:
![image](https://user-images.githubusercontent.com/62659043/129596909-4ac4234c-02b6-47fe-bd39-a1fc0d7d7e04.png)

Add a picture like this:
![image](https://user-images.githubusercontent.com/62659043/129597053-5d68d184-9ff5-442f-8da2-432497599473.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.0

### What app or flow are you having the issue with?

documentation

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
