### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture Components failed to import

### ISSUE THREAD

**Issue by silvafr1** [microsoft/coe-starter-kit#1041]
### Describe the issue

Hello,
I´m trying to set up nurture components for the first time this environment and I´m getting the error: 
Solution "Center of Excellence - Nurture Components" failed to import

### Expected Behavior

Installation successfully done

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.1

### What app or flow are you having the issue with?

Installation it-self

### Anything else?

[Center of Excellence - Nurture Components_import.xlsx](https://github.com/microsoft/coe-starter-kit/files/6999070/Center.of.Excellence.-.Nurture.Components_import.xlsx)

**Comment by JeneferM-MSFT** [comment]
I'm afraid all your file shows me is that install was cancelled. Can you tell me, are you GCC or GCC-High (aka a gov tenet)? If so, then this would be a known issue. 

If not, we have had troubles with upgrade lately do to changing the way we ship. Please try and update instead of upgrade, and if that fails do an overwrite via the classic ux. 

How to do that:
Solution > Switch to Classic (note this can take some time, may have to try twice)  
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png) 

Click Import (fourth from the left)  
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png) 

Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import  
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png) 
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by silvafr1** [comment]
Hello,

Regarding your question, no I´m not "gov tenent",

Meanwhile, I´ve followed your suggestion:  "switch to classic" and import solution, apart of  "overwrite customizations" because is new installation and got the same error:

![NurtureSolution_Import01](https://user-images.githubusercontent.com/49397248/129740113-571ba9c1-0990-4c74-8510-0af80c78ae52.PNG)

Thank you.

**Comment by JeneferM-MSFT** [comment]
Oh this is not an upgrade, this is a new install. I'm afraid I've never seen this happen then. 
- Do you have permission to import other solutions in this environment? 
- Did you install Core here? 
- It looks like you have installed it in the past as you have a security role there from Nurture. Can you comment on that?

**Comment by silvafr1** [comment]
Hello,

We have imported other solution without any problem (Core, Audit logs, Governance).

Yes we had a few months ago the Nurture version from February (I think!) and we removed it then.
Do you think there is something blocking, from the old removal?
Thank you.

**Comment by JeneferM-MSFT** [comment]
OK thank you. Yes I'm afraid you will need to contact support. It sounds like you are in some strange state but that install mostly worked. 
Sorry we cannot assist here further.
