### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor V2 - Environment disappears on Remove from Policy

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#1043]
### Describe the issue

When I choose to remove an environment from the policy the environment disappears from the app and is no longer available to select again

### Expected Behavior

I should be able to move environments between the Available and Added to Policy buckets in the DLP Editor V2 app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

1. Update an existing DLP policy with scope = Exclude certain environments
![image](https://user-images.githubusercontent.com/41050216/129792762-12260cc9-04c8-4dca-ade9-c302906ab322.png)
2. Remove an environment from the policy
![image](https://user-images.githubusercontent.com/41050216/129793013-84d5f09e-734c-4b39-b578-2e4f3a90d181.png)
3. The environment disappears and is not showing in the Available bucket
![image](https://user-images.githubusercontent.com/41050216/129793102-67a7049c-c31e-48a7-bad6-fec96f3d6593.png)

### Anything else?

This scenario is particularly important when trying to see the Impact Analysis of policies where Scope = Exclude certain environments and

**Comment by manuelap-msft** [comment]
Hello,

thanks for the very detailed error analysis, this is super helpful! I was able to repo this in my environment - it looks like when the environment is removed from the policy, we're adding it back to the wrong collection. I'm working on fixing that!

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Fixed for September release (expected to come out next week)

**Comment by mikefactorial** [comment]
@HamishSheild This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by HamishSheild** [comment]
Hi @manuelap-msft , unfortunately I don't think this is fixed in the September release (Core version 3.12).  If you have only 1 environment in **Added to policy** in a "Exclude Certain Environments" policy and remove the environment from the policy, then the result is that environment is then missing from the **Available** tab.  If there is more than 1 policy in **Added to Policy** then this doesn't happen.  Do you want me to raise another Issue to track this or will you re-open this one?

![image](https://user-images.githubusercontent.com/41050216/133704758-a2b33169-4dbe-45d1-a20b-9a07a31d79e7.png)

**Comment by manuelap-msft** [comment]
I'll reopen this one! Can you confirm you don't have any unmanaged layers on the DLP Editor app?

**Comment by HamishSheild** [comment]
Thanks.  No unmanaged layers
![image](https://user-images.githubusercontent.com/41050216/133846885-1030979b-1361-4316-92b4-da98c8fae7ff.png)

**Comment by mikefactorial** [comment]
@HamishSheild This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
