### ISSUE TITLE
[CoE Starter Kit - PRODUCT BUG] Maker Assessment Starter Dataflow - not supported in DfT

### ISSUE THREAD

**Issue by tmycgn** [microsoft/coe-starter-kit#1057]
### Describe the issue

The installation was done exactly according to the instructions (Team Environment):
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#import-starter-data-set-for-the-maker-assessment-app

However, the initial start of the dataflow does not work. Also the hint with the refresh does not work. The Excel file has been uploaded and included. The data could also be imported.

![image](https://user-images.githubusercontent.com/82310796/130240395-4d39f788-5bdd-4c45-8b10-ebe786352b59.png)

![image](https://user-images.githubusercontent.com/82310796/130240953-f58bf223-76e7-4421-8377-8fa83bd20ddd.png)

![image](https://user-images.githubusercontent.com/82310796/130241044-3c65620a-b309-4a08-92b6-725fb708adac.png)

![image](https://user-images.githubusercontent.com/82310796/130240145-17ab5661-12b9-4a79-b4d3-8c0b5b8d82b0.png)

![image](https://user-images.githubusercontent.com/82310796/130240193-f3face1a-0a91-4531-a5c0-99e0c52a3733.png)

### Expected Behavior

The dataflow should start according to the guide.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Maker Assessment Starter Dataflow 3

### Steps To Reproduce

Doing https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#import-starter-data-set-for-the-maker-assessment-app in Team environment.

### Anything else?

Could the bug be due to the beta status of the Dataflow integration in Teams?

**Comment by JeneferM-MSFT** [comment]
reached out to product team

**Comment by JeneferM-MSFT** [comment]
It appears dataflows are not yet supported in the desktop version of DfT. You can enter the starter data manually, or you will have to wait for this feature to be supported to use the dataflow to load. 
Sorry for the inconvenience.

**Comment by tmycgn** [comment]
Ok thanks @JeneferM-MSFT, maybe it makes sense that this will be added to the existing MS Docs documentation.

**Comment by JeneferM-MSFT** [comment]
Agreed. I am checking to see when this will be resolved, and if its a while yet, I will both add a note and provide a workaround.

**Comment by Jenefer-Monroe** [comment]
Looks like it will be a while, we've actually gone backwards and install does not work with a dataflow anymore into teams. 
Here is a version of Sept without the dataflow so that you can proceed: [CenterofExcellenceNurtureComponents_3_0_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7138428/CenterofExcellenceNurtureComponents_3_0_managed.zip)

I'm afraid the only workaround to get the data into the DfT that exists are to either manually enter the data using the admin app provided with the solution, or to use the Excel Add in if you have access to it. This is because there is no bulk import available in teams and we cannot force a GUID in the row entry form in.

### Get the sample data
Download these 3 files locally for your reference
[answeroptions.xlsx](https://github.com/microsoft/coe-starter-kit/files/7139420/answeroptions.xlsx)
[assessments.xlsx](https://github.com/microsoft/coe-starter-kit/files/7139423/assessments.xlsx)
[assessmentcategories.xlsx](https://github.com/microsoft/coe-starter-kit/files/7139424/assessmentcategories.xlsx)

### Excel Add In
1) Browse to flow.microsoft.com > select your DfT CoE environment > Data > Tables > **Assessment Category**
![image](https://user-images.githubusercontent.com/89584709/132754072-090224f3-a729-4bf3-b40b-55af0974c864.png)
2) Relationships > Data > Edit Data in Excel 
![image](https://user-images.githubusercontent.com/89584709/132754245-43abcc18-4039-4316-9cad-63a027e29f12.png)
3) Open the file from your download > Enable Editing > and ensure you are signed in as the correct user for DfT environment
4) Open **assessmentcategories.xlsx**
5) Copy in the following columns from the assessmentcategories.xlsx to **admin_MakerAssessmentCategory** which is the file with the addin. Then hit publish

| From          | To            |
| ------------- |:-------------:|
| admin_makerassessmentcategoryid     | Assessment Category |
| admin_categoryname     | Category Name  |
| admin_sortorder | Sort Order |

![image](https://user-images.githubusercontent.com/89584709/132755687-f43255e1-cff6-4a8d-be7b-fdffd80545c6.png)

6) Do the same thing for the **_Assessment Questions_** table, use **_assessments.xlsx_** and map as follows

| From          | To            |
| ------------- |:-------------:|
| admin_assessmentid  | Assessment |
| admin_importantthingstokeepinmind     | Important things to keep in mind  |
| admin_questionformat | Question Format  |
| admin_questionname | Question Name |
| admin_makerassessmentcategory | Assessment Category |

7) Do the same thing for the **_Assessment Questions_** table, use **_answeroptions.xlsx_** and map as follows

| From          | To            |
| ------------- |:-------------:|
| admin_answeroption | Answer Option |
| admin_answeroptionsid | Answer Option**s**  |
| admin_consideration | Consideration  |
| admin_isdefault | Is Default  |
| admin_requiresadditionalstorage | Requires Additional Storage  |
| admin_requiresaibuilder | Requires AI Builder  |
| admin_requiresportals | Requires Portals  |
| admin_requirespremium | Requires Premium  |
| admin_requiressupport | Requires Support  |
| admin_question | Question  |

### Admin App
If that doesnt work you will either need to wait for the DfT to work again, or input manually. I suggest via the admin app
![image](https://user-images.githubusercontent.com/89584709/132757632-1b90eee6-7619-4a31-8724-eccfd13a4da7.png)
![image](https://user-images.githubusercontent.com/89584709/132757700-7000572c-dc26-4ea8-be5c-367c6580ae1d.png)

**Comment by Jenefer-Monroe** [comment]
As of today, you can now use the Dataflow in a Teams install, but you have to go through teams in the browser in order to do so. 
You will see the dataflows as an element next to installed apps. 
![image](https://user-images.githubusercontent.com/89584709/145602925-9213b081-6286-4155-98b1-eb461857f1ba.png)

We will update the documentation to include this note.
