### ISSUE TITLE
[CoE Starter Kit - BUG] Flows in solutions cannot be deleted by Archival flows - should warn user

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#1062]
### Describe the issue

Today we allow people to approval deletion of flows that are part of a solution, but the product cannot actually delete such flows. And we never tell the user

### Expected Behavior

Add communication to the end user that they will need to do the deletion manually.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.0

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Clean Up and Delete)

**Comment by JeneferM-MSFT** [comment]
Fixed for September

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
