### ISSUE TITLE
[CoE Starter Kit - BUG] If user manually deletes an app/flow, the table doesnt update deleted field

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#1073]
### Describe the issue

causes some edge cases where they will always be reminded

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.0

### What app or flow are you having the issue with?

Clean Up and Delete

**Comment by JeneferM-MSFT** [comment]
fixed for September

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
