### ISSUE TITLE
[CoE Starter Kit - BUG] Set Flow Permissions app does not work for flows that are in a solution

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#1081]
### Describe the issue

If a flow is in a solution, cannot add new owner via Set Flow Permissions

### Expected Behavior

Allow new derived owner to be added via helper flow

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Set Flow Permissions

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
