### ISSUE TITLE
[CoE Starter Kit - BUG] can not turn on BPF for approving Teams environments

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#1082]
### Describe the issue

Hey, 
i am not able to activate the Business Process Flows.
If I try this there is an Error message:
![image](https://user-images.githubusercontent.com/62603605/130987286-7611eff2-2588-4421-a601-aa591fb543d1.png)

I can activate the flow from the developer mode, but the BPF still not showing in der Power Platform Admin View-app.

It would be great to get help with this! 

### Expected Behavior

Turning on the BPF like described here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

App: Power Platform Admin View / BPF

**Comment by Cathi029** [comment]
Hey, are there any news on this problem? I tried to install the kit in a new environment, but the same problem occured.
Might this problem be solved in the new september version?

Thanks a lot for you work and support!

**Comment by mikefactorial** [comment]
@Cathi029 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
