### ISSUE TITLE
[CoE Starter Kit] Hide Content Conversion and Logic Flows from DLP Editor

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1087]
During investigation we noticed that the DLP Editor in the CoE solution shows 2 additional connectors which are hidden by design on the PPAC portal.

The 2 connections are:
Logic Flows
Content Conversion

The CoE Starter Kit uses the Get Connectors action of the Power Apps for Makers connector (Power Apps for Makers - Connectors | Microsoft Docs) to list available pre-built connectors in the DLP Editor. This action returns both Logic Flows and Content Conversion as connectors so that's why they are being shown in the DLP Editor. 

Looks like there is special logic in PPAC to hide those two connectors. We will replicate that and also hide them in the DLP Editor.

**Comment by manuelap-msft** [comment]
fixed for September

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
