### ISSUE TITLE
[ALM Accelerator - BUG]: Issue while importing managed solution as update 

### ISSUE THREAD

**Issue by KarthikRao-HM** [microsoft/coe-starter-kit#1092]
### Describe the issue

Message: CanvasApp import: FAILURE: A managed solution cannot overwrite the CanvasApp component '' with Id= which has an unmanaged base instance.  The most likely scenario for this error is that an unmanaged solution has installed a new unmanaged CanvasApp component on the target system, and now a managed solution from the same publisher is trying to install that same CanvasApp component as managed.  This will cause an invalid layering of solutions on the target system and is not allowed.

Description: Trying to import a canvas app with custom and OOTB connectors (Azure blob storage).
The connection references are added to a JSON file and a folder called config is created and the JSON file is placed under a sub directory for Validate environment. 

Above error message occurs in Import solution as update step and upon verification there are no unmanaged layers of the solution or the power app in the environment and all are deleted. 

Could you please help debug the issue?

### Expected Behavior

The connection references created in the validation environment and mentioned in the customDeploymentSettings.json file must be accepted and a deployment to validation must occur when the pipeline is running.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.202

**Comment by jenschristianschroder** [comment]
Hi @KarthikRao-HM,

From the error message it seems to that your issue is not related to the custom connector you are deploying. Rather it is a result of having an unmanaged customization layer on the Canvas App component in the target environment. This can happen if someone edits the Canvas App in target environment and saves. The changes will be saved to an unmanaged layer on top of the managed solution you imported. 
Result it that future updates to the managed component can not be imported unless the unmanaged layer is removed.

To work around this in scenarios where unmanaged customizations are required it is recommended to create the unmanaged changes in a separate solution so that it can be export and reinstalled once the managed component has been updated.

To delete the unmanaged layer you should:
1. Go to the target environment
2. Open the solution containing the Canvas App
3. Select the Canvas App
4. Click the context menu (...) and select See solution layers
5. Select the unmanaged layer
6. Click remove unmanaged layer

Documentation on Managed vs. Unmanaged solutions https://docs.microsoft.com/en-us/power-platform/alm/solution-concepts-alm#managed-and-unmanaged-solutions

**Comment by KarthikRao-HM** [comment]
Hi @jenschristianschroder  - the solution is deleted. There is no reference of managed or unmanaged version of that solution in that environment. Is it retaining the reference of the power app only in some place in the environment even though the solution is deleted? I donot see it under the apps section as well.

**Comment by jenschristianschroder** [comment]
When deleting a managed solution all components in will also be deleted. So if you have deleted the managed solution from the target environment you should not face this issue.

Can you try the following query in your target environment to see if you can find the CanvasApp is still there somehow.

https://[target environment url]/api/data/v9.1/canvasapps?$filter=(displayname eq '[Canvas App Displayname]')

Or list all records in canvasapp table and verify if the Canvas App is still there:

https://[target environment url]/api/data/v9.1/canvasapps

**Comment by KarthikRao-HM** [comment]
I tried running this on Postman or browser as a Get request with basic auth. It give me 401 unauthorized exception. Could you please share any article on how to authenticate and run the queries.

Below headers were added -
GET [Organization URI]/api/data/v9.1/accounts?$select=name
&$top=3 HTTP/1.1  
Accept: application/json  
OData-MaxVersion: 4.0  
OData-Version: 4.0

**Comment by devkeydet** [comment]
Since it is a GET, you could just use the browser.  If you want to use postman, see these instructions.
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/setup-postman-environment
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/use-postman-perform-operations

**Comment by mikefactorial** [comment]
Closing this since there's nothing more to be done for this issue. Feel free to open a new issue if you need further assistance.
