### ISSUE TITLE
[CoE Start Kit] Environmental request app - links to understand form options.

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#1093]
**Is your feature request related to a problem? Please describe.**
Users (makers) of Environment Request app are expected to understand what Environment Type, Region etc. is. This is not necessarily common knowledge for new makers.

**Describe the solution you'd like**
Links (Learn more) for each property that can be configure to point to internal wiki, sharepoint other resource that can explain the specific concept

**Comment by denisem-msft** [comment]
This has been added to the Maker - Environment Request app and the message can be modified by providing a current value to the new 'Wiki - Environment Type' environment variable
![image](https://user-images.githubusercontent.com/43950360/147563251-e6078754-b529-425c-bac4-690b01d36c39.png)

**Comment by mikefactorial** [comment]
@jenschristianschroder This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
