### ISSUE TITLE
[CoE Starter Kit - BUG] Not all portals are recorded into the table by the flow

### ISSUE THREAD

**Issue by dudelis** [microsoft/coe-starter-kit#1096]
### Describe the issue

I have multiple Starter portals in my tenant. They are all active, however, after the **Admin | Sync Template v3 (Portals)** runs not all portals are visible in the Power Platform Admin View.

### Expected Behavior

The expected behavior is that all the Portals are visible in the Power Platfrom Admin View tab.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.77

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Portals)

### Steps To Reproduce

1. Create 2 Trial environments.
2. On each environment create 1 Starter Portal.
3. Run the Admin | Sync Template v3 flow.
4. Check the table in the Power Platform Admin View - only 1 of the portals is logged (if no other Starter portals exist)

### Anything else?

I debugged the flow myself and noticed, that the Admin | Sync Template v3 (Portals) has List ADX Websites step. The step returns JSON, from which the ItemInternalId is taken and considedred to be the Portal unique ID, but it is not. Here is the screenshot of this step from 2 different flows for 2 different environments (you can see this from input parameters of the step), however the ItemInternalId is the same:
![image](https://user-images.githubusercontent.com/7166141/131690584-1dbb21c8-c42f-44c7-b7e6-e44b21bacaf3.png)

It seems to me that this is the ID of the Portal Template. I noticed at one of the customers, that they have only 1 portal of each kind, however, they have more than 15 portals in total.
Maybe you should use a compound ID, e.g. EnvironmentID + TemplateID? If any questions, I am ready to help.

**Comment by Jenefer-Monroe** [comment]
Thank you for reporting with such great steps. I notified the Portals folks.

**Comment by Jenefer-Monroe** [comment]
Can you please test something for me? We may have used the wrong field for the GUID, and so I wonder if this would fix it. There are six places you will need to make this change to **_Admin | Sync Template v3 (Portals)_**.
For the three shown below, you would change **_Row ID_** to be **_@{body('Parse_Portals_JSON')?['adx_websiteid']} (_**instead of ItemInternalID)
![image](https://user-images.githubusercontent.com/89584709/134706321-deafe933-439a-4747-88a5-bdcc99f859ea.png)
![image](https://user-images.githubusercontent.com/89584709/134706152-4834edd4-3223-42a3-a032-07ed36ae809e.png)

And for the three below here, you will change **_Power Apps Portal_** to be that value
![image](https://user-images.githubusercontent.com/89584709/134706513-a5326a50-5f62-4203-84bd-8636f0a597fa.png)

![image](https://user-images.githubusercontent.com/89584709/134706425-dea146f9-590d-40a5-b8c1-4ce82873cafd.png)

**Comment by dudelis** [comment]
I will test it, but I am sure this will not fix it. In my screenshot above you can see, that **adx_websiteid** is also seen and it is also the same for 2 different portals.

**Comment by dudelis** [comment]
I tested and it is not working. As I already mentioned, the **adx_websiteid** property is the same for Portals on different environments.

**Comment by dudelis** [comment]
I managed to obtain all the Power Portals in the CoE by not setting the admin_portalid, and let it be generated automatically, since we do not get any unique value from any of the calls.

And then I am checking if an item exists in Power Portal Table with the same environmentid and websiteID:
![image](https://user-images.githubusercontent.com/7166141/134933317-0b9c9319-37ea-4cbe-859f-478e98a100a7.png)

If 1 item exists, the Portal has been already created in CoE before:
![image](https://user-images.githubusercontent.com/7166141/134933784-d3b74c51-a3b1-4d95-9ffc-f37973f1747e.png)

And then I am using the admin_portalid of the first element, where I need to update the portal attributes:
![image](https://user-images.githubusercontent.com/7166141/134934168-bfe2197a-babb-4277-8fd7-cb4e4abda9af.png)

And if I need to create a new item in the CoE Portal table, I am not setting the admin_portalid:
![image](https://user-images.githubusercontent.com/7166141/134934397-93b50f5c-eaa7-4ddd-8c81-ae810888a9a6.png)

I am not sure, if this is a viable approach, but since I do not know, where I can get the Portal Instance Unique ID, I am kind of using the concept of a compound key (EnvironmentID + WebsiteID) without changing the Table structure.

**Comment by Jenefer-Monroe** [comment]
thanks for your research. We are reaching out to the dev team to see if they can point us to a unique id. Appreciate your efforts!

**Comment by Jenefer-Monroe** [comment]
Local fixed for Oct. We now use a combination of the envt and website guid to determine uniqueness and auto-generate a GUID. 
We have also added a clean up routine at the top so you dont need to worry about these appearing twice now either.

**Comment by mikefactorial** [comment]
@dudelis This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
