### ISSUE TITLE
[CoE Starter Kit] All sync flows enabled by default except Sync Template (Flows) 

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#1100]
### Describe the issue

Not a major issue but noticed that in current version of core component all the other sync template flows except Flows are enabled by default after solution import. 

![image](https://user-images.githubusercontent.com/8307644/131817566-d946d126-9eab-4a10-babb-ec88460d981c.png)

### Expected Behavior

All sync flows disabled by default

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.77

### What app or flow are you having the issue with?

Sync Flows

**Comment by Jenefer-Monroe** [comment]
Thank you for the heads up. We shipped 2.77 manually and not with our tools, so this should be a one off. Will hold to verify though with the Sept release.

**Comment by mikefactorial** [comment]
@petepuu This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
