### ISSUE TITLE
[CoE Starter Kit] Sync Flow (Apps) - store version number of app

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1104]
On the Power Apps table, also store the app version for reporting.

**Comment by Jenefer-Monroe** [comment]
Power Apps Release version now stored in the PowerApps Apps table for September
![image](https://user-images.githubusercontent.com/89584709/132020043-a595f3a5-8d05-41ed-a7da-06d906728a1b.png)

**Comment by Jenefer-Monroe** [comment]
Will require [full inventory run](https://docs.microsoft.com/power-platform/guidance/coe/limitations#incomplete-inventory) to get the value for all apps in the tenant.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
