### ISSUE TITLE
[CoE Starter Kit] Power BI report page for Environment Capacity 

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1105]
Show Capacity and Top 10 Capacity of Environments in the Power BI

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
