### ISSUE TITLE
[CoE Starter Kit] Environment Request App - Improve filter on my pending requests view

### ISSUE THREAD

**Issue by chrispiasecki** [microsoft/coe-starter-kit#1110]
**Is your feature request related to a problem? Please describe.**
The status filter for the Environment requests currently does not allow you to view all, only one status at a time. 

**Describe the solution you'd like**

- Add a selection of 'All' or unselect the status filter. 
- Sort the statuses in alphabetical order for better user experience.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by manuelap-msft** [comment]
Re-opening so it can be included in our release notes for November.

**Comment by mikefactorial** [comment]
@chrispiasecki This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
