### ISSUE TITLE
[CoE Starter Kit - BUG] (Power Apps User Shared With) failing for user with Viral-GUID in role assignment return 

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1111]
### Describe the issue

We have a single failure in our test tenant caused by the product returning an unexpected value. 

Get App Role Assignment as Admin in one case returned only email and not id. 

![image](https://user-images.githubusercontent.com/89584709/132000477-5ad7e37c-833e-4dc1-8755-1c80967ec1d7.png)

The issue also surfaces in Get App Permissions. 

The user does appear to be normal and functioning, but the way it was added to the app perhaps to get that Viral-GUID is the issue. 

I think the fix would be easy (catch and lookup in O365users via email) but does not seem urgent for Sept and want to understand better so targeting Oct.

### Expected Behavior

able to handle this case.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.77

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

**Comment by Jenefer-Monroe** [comment]
turns out this case was due to incorrectly attempting to add user programmatically. and the user wasnt actually added.
so the fix is to just check that ID is not null before proceeding. 
local fixed for Sept and running through testing.

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
