### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot import September 2021 Nurture components to Teams environment

### ISSUE THREAD

**Issue by jukkan** [microsoft/coe-starter-kit#1131]
### Describe the issue

I have installed the latest version of the Core components for Dataverse for Teams : CenterofExcellenceCoreComponentsTeams_2_5_managed.zip

Upon trying to import the Nurture components 2.2, I get an error for missing dependencies for the "Maker - Command Center" Canvas app:

![image](https://user-images.githubusercontent.com/10254155/132561929-8b247e2e-0e7d-4bbd-bc67-51e05cf2fdc7.png)

This is the first time installing the Nurture solution into a Dataverse for Teams environment that already had the August release for Core and Governance solutions.

### Expected Behavior

I should be able to install the latest September release of Nurture components into a Dataverse for Teams environment

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Solution

**Comment by bartsneary** [comment]
I got the same error.  Don't see where I can upvote something, so just added the comment.  It installs fine in a regular Dataverse environment.

**Comment by Jenefer-Monroe** [comment]
thank you, we found a repro and are investigating.

**Comment by manuelap-msft** [comment]
Hello,

we repo this in our tenant, but after resolving the missing dependency issue we are still seeing issues importing the solution into Teams - at the moment looks like that may be related to the Dataflow. We're still investigating and will keep this thread updated!

Thank you for your patience,
Manuela

**Comment by manuelap-msft** [comment]
Hello,

1. We have just updated the Core for Teams version so it contains the Maker - Command Center, which was causing dependency issues. You can get that from our release: https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2021/CenterofExcellenceCoreComponentsTeams_2_9_managed.zip
2. The Nurture solution contains a dataflow, and it looks like there's a product issue where this can no longer be imported into Teams but is fine being imported into Prod. We prepared a one-off solution that does not contain the dataflow that can be imported into Teams. It has the same unique name and publisher as the regular Nurture solution so that once dataflows can be imported into Teams again, you will have no problem upgrading it. To avoid confusion, we're not including this special Nurture solution in the Release but only sharing it one off with customers who experience issues. I've attached it here for you to use.
[CenterofExcellenceNurtureComponents_3_0_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7138428/CenterofExcellenceNurtureComponents_3_0_managed.zip)

@Jenefer-Monroe will share instructions on how to manually add [Maker Assessment Starter Data](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#import-starter-data-set-for-the-maker-assessment-app) which is what the dataflow currently does and is now missing from the Teams version.

Let us know if you have any additional questions - appreciate it's a bit confusing :) 
Manuela

**Comment by jukkan** [comment]
Thanks, @manuelap-msft ! Now the import worked for Dataverse for Teams environment, too.

**Comment by Jenefer-Monroe** [comment]
I'm afraid the only workaround to get the data into the DfT that exists are to either manually enter the data using the admin app provided with the solution, or to use the Excel Add in if you have access to it. This is because there is no bulk import available in teams and we cannot force a GUID in the row entry form in.

### Get the sample data
Download these 3 files locally for your reference
[answeroptions.xlsx](https://github.com/microsoft/coe-starter-kit/files/7139420/answeroptions.xlsx)
[assessments.xlsx](https://github.com/microsoft/coe-starter-kit/files/7139423/assessments.xlsx)
[assessmentcategories.xlsx](https://github.com/microsoft/coe-starter-kit/files/7139424/assessmentcategories.xlsx)

### Excel Add In
1) Browse to flow.microsoft.com > select your DfT CoE environment > Data > Tables > **Assessment Category**
![image](https://user-images.githubusercontent.com/89584709/132754072-090224f3-a729-4bf3-b40b-55af0974c864.png)
2) Relationships > Data > Edit Data in Excel 
![image](https://user-images.githubusercontent.com/89584709/132754245-43abcc18-4039-4316-9cad-63a027e29f12.png)
3) Open the file from your download > Enable Editing > and ensure you are signed in as the correct user for DfT environment
4) Open **assessmentcategories.xlsx**
5) Copy in the following columns from the assessmentcategories.xlsx to **admin_MakerAssessmentCategory** which is the file with the addin. Then hit publish

| From          | To            |
| ------------- |:-------------:|
| admin_makerassessmentcategoryid     | Assessment Category |
| admin_categoryname     | Category Name  |
| admin_sortorder | Sort Order |

![image](https://user-images.githubusercontent.com/89584709/132755687-f43255e1-cff6-4a8d-be7b-fdffd80545c6.png)

6) Do the same thing for the **_Assessment Questions_** table, use **_assessments.xlsx_** and map as follows

| From          | To            |
| ------------- |:-------------:|
| admin_assessmentid  | Assessment |
| admin_importantthingstokeepinmind     | Important things to keep in mind  |
| admin_questionformat | Question Format  |
| admin_questionname | Question Name |
| admin_makerassessmentcategory | Assessment Category |

7) Do the same thing for the **_Assessment Questions_** table, use **_answeroptions.xlsx_** and map as follows

| From          | To            |
| ------------- |:-------------:|
| admin_answeroption | Answer Option |
| admin_answeroptionsid | Answer Option**s**  |
| admin_consideration | Consideration  |
| admin_isdefault | Is Default  |
| admin_requiresadditionalstorage | Requires Additional Storage  |
| admin_requiresaibuilder | Requires AI Builder  |
| admin_requiresportals | Requires Portals  |
| admin_requirespremium | Requires Premium  |
| admin_requiressupport | Requires Support  |
| admin_question | Question  |

### Admin App
If that doesnt work you will either need to wait for the DfT to work again, or input manually. I suggest via the admin app
![image](https://user-images.githubusercontent.com/89584709/132757632-1b90eee6-7619-4a31-8724-eccfd13a4da7.png)
![image](https://user-images.githubusercontent.com/89584709/132757700-7000572c-dc26-4ea8-be5c-367c6580ae1d.png)

**Comment by bartsneary** [comment]
I'm happy to try the workaround, but couldn't we use the new Preview feature of Dataflows in Dataverse for Teams to see if that works?

[Graphical user interface, application, Teams  Description automatically generated]

***@***.***
Bart Sneary (he/him)
Architect & Technology Ethicist | 952-837-4560 W or 507-403-3088 M ***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
***@***.***

**Comment by bartsneary** [comment]
The v3 version appears to have worked:

[Graphical user interface, application, Teams  Description automatically generated]

[Graphical user interface, application, email  Description automatically generated]

***@***.***
Bart Sneary (he/him)
Architect & Technology Ethicist | 952-837-4560 W or 507-403-3088 M ***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
***@***.***


From: Bart Sneary
Sent: Thursday, September 9, 2021 3:37 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Manual ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Cannot import September 2021 Nurture components to Teams environment (#1131)

I'm happy to try the workaround, but couldn't we use the new Preview feature of Dataflows in Dataverse for Teams to see if that works?

[Graphical user interface, application, Teams  Description automatically generated]

***@***.***
Bart Sneary (he/him)
Architect & Technology Ethicist | 952-837-4560 W or 507-403-3088 M ***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
***@***.***

**Comment by manuelap-msft** [comment]
Hey Bart,

screenshots are not coming through when you reply via email, you will have to directly go to the issue in GitHub (https://github.com/microsoft/coe-starter-kit/issues/1131) and paste the screenshots there for us to see them.

I'm curious how you got the Dataflow into Teams, did you create a new one from the Dataflow (preview) tab in Teams? We tried adding the dataflow to the solution which resulted in the solution import failing so if there's a way you got it to work we'd love to know how you did it!

Thank you
Manuela
