### ISSUE TITLE
[ALM Accelerator - BUG]: Deploymentconfigguide outdated

### ISSUE THREAD

**Issue by mdpc-nnit** [microsoft/coe-starter-kit#1137]
### Describe the issue

The [deploymentconfigguide](https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorForAdvancedMakers/DEPLOYMENTCONFIGGUIDE.md) seems out of sync with the latest pipelines

In the deploymentSettings.json file, when I use the format
```
{
  "ConnectionReferences": [
    [ "cat_CDS_Current", "#{connection.cat_CDS_Current}#" ]
  ]
}
```
I get the following error during the "Import managed solution as update":
```
2021-09-09T09:35:37.5890578Z ##[error]Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Microsoft.Xrm.WebApi.Models.ConnectionReferenceSettings' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'ConnectionReferences[0]', line 3, position 9.
```
It works when I used the format suggested [here](https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools), i.e.:
```
  "ConnectionReferences": [
    {
      "LogicalName": "tst_sharedtst5fcreateuserandjob5ffeb85c4c63870282_b4cc7",
      "ConnectionId": "4445162937b84457a3465d2f0c2cab7e",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_tst-5fcreateuserandjob-5ff805fab2693f57dc"
    }
]
```
It also reactivates flows, so this fixes the issue.

### Expected Behavior

I would like to be able to use the simpler format
```
{
  "ConnectionReferences": [
    [ "cat_CDS_Current", "#{connection.cat_CDS_Current}#" ]
  ]
}
```
In the deploymentsettings.json and still update connection refs

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

097ea80e8648c829d3ba3aeaa991e6fabe594ce0

### Anything else?

I expect there is a similar issue with environment variables, but I did not test this.

**Comment by mikefactorial** [comment]
Hey @mdpc-nnit,
Thanks for bringing this to our attention. A little bit of background may be required as well as a sneak peek into what is coming.
1. The deploymentconfigguide will be updated in the coming release.
2. The reason we've changed the format is to align with new features in PAC CLI and in the Azure DevOps tasks that eliminate the use of third party tasks for setting environment variables and our powershell that was used for updating connection references. These functions are now native in the tooling so the next release will make use of them. The schema in the deploymentSettings.json required for these new functions differed slightly from our custom deployment json which required us to make an update to align. https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools
3. The next update will automatically generate a deploymentSettings.json and customDeploymentSettings.json for you on export of the solution that will align with the new formats and we'll include guidance on how to migrate to the new format.
4. Additionally, we are adding capabilities to the AA4AM app that will allow you to set the values of all of the deployment configuration settings with a simple UI rather than having to gather all of the details and fill in them in, in the json.

As we progress through preview we are trying to incorporate native platform capabilities and remove the workarounds we have in the pipelines currently which is why occasional breaking changes are still necessary. The next release will move toward the native connection reference and environment variable settings and remove backward compatibility with our workarounds, but should be a reasonably smooth transition since the system will handle generating the json and creating pipeline variables for you.

New deployment configuration experience. Sneak Peek :)
![image](https://user-images.githubusercontent.com/42348035/132711938-1b27ed97-dcf0-4bca-81a5-54fa7d16849d.png)

**Comment by mdpc-nnit** [comment]
Wow, that is great @mikefactorial ! The reason I updated the pipelines in the first place was because I knew about the official build tools' new capabilities.

Being able to do the configs from a canvas app will be great! I don't assume that you will be able to create connections in downstream environments directly from the app? And will I be able to assign connections from another account than my own (e.g. a service account)?

Do you want me to close this issue?

**Comment by mikefactorial** [comment]
@mdpc-nnit the goal is to provide makers who do have permissions to create connections in downstream environments the ability to do so with the ability to request connections from other users to create the connections, but because of the way permissions work the logged in user (whoever that is) will only be able to see their connections. 

In the case of a service account someone would still have to login as that service account and either create the connection from the accelerator or create the connection and then update the connection id in the pipeline variable manually, since we can't currently work around that limitation in the platform.

**Comment by mikefactorial** [comment]
Feel free to close this unless you have more questions.

**Comment by mdpc-nnit** [comment]
Your solution sounds great! If you can log in as the service account and create connections directly from the app, then it is still totally fine.

When is this feature planned? I know some powerplatform admins that will be clapping their small hands :)

**Comment by mikefactorial** [comment]
Should be in the next couple of weeks. Have some docs to update but the feature is mostly complete.
