### ISSUE TITLE
[CoE Starter Kit - REQUEST] - Additional Documentation Needed for Core Solution

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#1139]
### Describe the issue

I am unable to find any documentation on regarding the new flow "CLEANUP - Admin | Sync Template v3 (Delete Bad Data)".

https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#flows
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2021

### Expected Behavior

Documentation available for review.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.7

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Delete Bad Data)

### Steps To Reproduce

Review these links:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#flows
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2021

**Comment by manuelap-msft** [comment]
Hello,

our release and docs update are not always in sync, because of different approval processes. We have made the changes required to docs already, but they're still being reviewed which is taking a bit longer this time due to some people being on leave. We'll ping you here when the changes are live.

Thank you for your patience,
Manuela

**Comment by manuelap-msft** [comment]
Docs are now live: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows
