### ISSUE TITLE
[CoE Starter Kit - Enhancement] Developer Compliance Center - make filter based on Power Platform User Role so you can get editors too

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1143]
### Describe the issue

Today we filter on the powerapps table but that only lets you get apps the person owns
    ClearCollect(
        myApps,
        Filter(
            'PowerApps Apps',
            'App Owner'.admin_makerid = myMakerProfile.admin_makerid && 'App Deleted' = 'App Deleted (PowerApps Apps)'.No
        )

### Expected Behavior

if we fillter instead on Power Platform User Role we can show ones they own or hve edit perms too
will have to also do addcolumns to powerapps table to get the data needed

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
