### ISSUE TITLE
[CoE Starter Kit - Documentation] - Upgrading Audit Log Solution - [Child] Admin | Sync Logs

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#1146]
### Describe the issue

Facing some on-going difficulties with the audit log solution, custom connector, connection objects, and the flow [Child] Admin | Sync Logs, etc. We've only been able to get this all to work by modifying the Child flow, which of course creates an unmanaged layer.  The last couple of upgrades have been this way. Even when I remove the unmanaged layer on the flow I still have to go through the process of re-establishing the custom connector details, the connection object, update the flow. The upgrade process is not smooth at all.  

### Expected Behavior

Ideally the upgrade process is easier with fare less touch points. 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.3

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

**Solution layer prior to upgrading. I do remove this prior to upgrading...**
![2021-09-09_14-31-23](https://user-images.githubusercontent.com/1613085/132750839-be7e43d2-9a9a-48c4-909b-80bf5a3c9d59.png)

**Post upgrade it is actually creating connection object to a completely different solution in the CoE environment. Why is it grabbing these? I have no idea.**
![2021-09-09_9-58-10](https://user-images.githubusercontent.com/1613085/132748891-9eab8cb0-6ca9-483d-a6c1-2fc2ac293dd3.png)

**To fix it I have to remove the connections and re-establish everything.**
![2021-09-09_10-16-28](https://user-images.githubusercontent.com/1613085/132748995-1ca0c04d-8ae1-4c4b-b34b-ecbf29bc3103.png)

![2021-09-09_10-23-18](https://user-images.githubusercontent.com/1613085/132749024-3101bf50-a15e-4f28-a0a2-326ed815728e.png)

![2021-09-09_10-35-09](https://user-images.githubusercontent.com/1613085/132749043-295dd5f6-a30d-4fef-9fce-2cbd25a7437b.png)

**Editing flow allows me to fix the connection objects. But then I have to save it, which again puts me back into unmanaged layer territory.**
![2021-09-09_10-36-11](https://user-images.githubusercontent.com/1613085/132749067-9f4b508c-1baa-4713-8b8b-a536c02c5074.png)

### Anything else?

Would it make sense to completely remove the Audit Log solution and start over with this solution from scratch?  I am not sure how to correct this issue.

**Comment by Jenefer-Monroe** [comment]
Hello this is a product issue, and not an issue with the toolkit. That said I believe the following way of fixing it is simpler and does not require you edit the flow. We will add this to the limitations documentation

**Custom Connector lost on upgrade**
Your audit log flows may fail after an upgrade due to the connection being broken. 
You will know its broken because you will see requests to fix like the below, and your flow will be failing with an Auth error.
![image](https://user-images.githubusercontent.com/89584709/132772867-b9d8f74c-33fa-45c5-8d2c-1948a717b081.png)

If you go to your connectors you will see your broken connector, clicking fix connection will not fix it:
![image](https://user-images.githubusercontent.com/89584709/132773412-f0948b08-015c-414b-bd2c-6dd154564a22.png)


The easiest way to fix this is to reset the custom connector and then fix the connection. This will allow you to fix the situation without editing the flow

**Fix it without editing your flow**
1) Open the custom connector for edit
![image](https://user-images.githubusercontent.com/89584709/132773567-29ff5b59-3d3f-4aad-83d1-98c93a786170.png)

1) Go to 2. Security, and chose to Edit under the Authentication type
![image](https://user-images.githubusercontent.com/89584709/132773648-60fd808f-b64c-4d06-b59b-1f34f75b3023.png)

1) Add the client id, secret and resource url that you used when you first set up the custom connector, and hit update connector
![image](https://user-images.githubusercontent.com/89584709/132773823-4237baab-1f3a-45d7-b85e-ebc0ebfec8de.png)

1) Go back to the connection and hit **_Fix connection_**
![image](https://user-images.githubusercontent.com/89584709/132773964-7c3ecb7e-4b8c-40ff-a5a9-6a6b321fe3a4.png)

**Comment by robertcaretta** [comment]
Ok, thank you. I will try this on the next upgrade. I will remove the managed layer first on that Child flow. 

This doesn't explain why the upgrade process is attempting to use connection objects found in a completely different solution.  That's the second screenshot I provided. You will notice there are 2 connections prefixed with "UC".

**Comment by Jenefer-Monroe** [comment]
We dont have any connection references with that name. And as far as I know we never have. So perhaps you have another solution in your environment with them and when you editted you selected them.

**Comment by patrickpooon02** [comment]
The "reset the custom connector" that @Jenefer-Monroe provided is useful. I have encountered this for months and every update will need me doing the same.

**Comment by robertcaretta** [comment]
@Jenefer-Monroe - We updated the Audit solution using the process you outlined, and it does help speed things up. However I found some additional blockers, and ended up with another unmanaged layer of that flow. Here is what we did.

1. Removed the unmanaged layer of that child flow.

2. Upgraded the solution to the Sept release. That worked fine.

3. Re-validated the credential information in the custom connector, per your guidance.

4. Attempted to re-start the child flow. That failed. _Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"FlowMissingConnection","message":"The flow is missing a connection for api 'shared_admin-5foffice-20365-20management-20api-5f8e72098c633fab51'. Reauthenticate the connection or remove from the flow and re-save."}}"._

5. I noticed that the custom connection object date did not update after updating the custom connector. So I went back into the custom connector and ran a new test. I used one of the "List" options, which returned a 200 message.

6. After running that test the connection object date updated. 

![2021-09-17_16-38-23](https://user-images.githubusercontent.com/1613085/133856336-8ae59198-d863-4f33-88a2-5a0cf98328af.png) 

7. I attempted to start the child flow again. Same error, would not start.

8. Then I went to the flow and checked the run only users section. This was not correct. So I updated it to point to the correct connection objects. I was then able to start the flow. 
![2021-09-17_11-47-34](https://user-images.githubusercontent.com/1613085/133856683-c4f14187-d805-4f49-83c2-a4029aee5f97.png)

9. However, this again creates a new unmanaged layer on the child flow.
![2021-09-17_11-49-51](https://user-images.githubusercontent.com/1613085/133856721-bc4dd57b-d0c9-4c16-a786-2248f16ee013.png)

**Comment by Jenefer-Monroe** [comment]
Hello. Can you help explain how you are blocked? Is it just that you did not expect updating the run-only to create an unmanaged layer?

**Comment by robertcaretta** [comment]
The blockers are the additional steps I outlined. It does work, I just want to make sure I know if we are doing the right thing and if that experience is what we should expect every time. 

Is the expectation that the child flow will always have an unmanaged layer after each upgrade?  If so, all of those steps should probably be outlined in the instructions for upgrading the audit log solution, including removing the unmanaged layer.

**Comment by Jenefer-Monroe** [comment]
Got it, thank you. Just making sure you are working. 

We can add to the Note in [Installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) that all child flows will need the unmanaged layer removed in order to receive updates, and that the run-only will need reset after update.

**Comment by mikefactorial** [comment]
@robertcaretta This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
