### ISSUE TITLE
Add app ownership change request to  Developer Compliance Center

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1153]
From Champions Community: Mohammed Alkuhlani

Expanding on our conversation about patterns in the last call. I want to share this pattern for automating an admin task with the community hopefully someone finds it useful.

We receive requests from our Citizen Developers for ownership change of their apps. While this is a simple change, it is just one more little thing that can be automated. We added the pattern below as an extension to the compliance center functionality.
- The pattern below is triggered by simply clicking on a "Ownership Change" option
- The user then selects the new owner from a combo box searching Office 365 Users.
- Once the request is submitted (saved to SharePoint) a flow is triggered under a service account context.

![image](https://user-images.githubusercontent.com/89584709/132859211-6a1621df-cb41-4547-89b4-2c1a4f664c03.png)

**Comment by Jenefer-Monroe** [comment]
Question: With the Approval - does that go to the new app owner, or to the admin?

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
