### ISSUE TITLE
[CoE Starter Kit - BUG] Getting an error when trying to upload the latest version 

### ISSUE THREAD

**Issue by mehakvij** [microsoft/coe-starter-kit#1165]
### Describe the issue

Hi! I'm trying to follow the upgrade guidelines on the docs, but when trying to upload the first (nurture component), I get the error below. I know the guide said to do it in the nurture, audit log, gov, then core order. 

![image](https://user-images.githubusercontent.com/73190679/133264472-44dadee3-6ca8-4cf6-920f-05f892dcd7cf.png)

Should I just upload core first according to this?

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Nurture Components

**Comment by manuelap-msft** [comment]
We believe we have the issue fixed by adding the table we removed back in, which will fix this dependency issue:
Please upgrade Core using this solution attached here.
 
And then upgrade the rest of the solutions as typical.

[CenterofExcellenceCoreComponents_3_12_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7162422/CenterofExcellenceCoreComponents_3_12_managed.zip)

Let us know if that works for you - if it does, we'll update the Core solution in the main release as well so other customers can benefit from that!

**Comment by fz8975** [comment]
This worked for me

**Comment by Jenefer-Monroe** [comment]
wonderful. thank you for confirming

**Comment by mehakvij** [comment]
Hi @Jenefer-Monroe and @manuelap-msft, thanks! I tried it and got this error though:

![image](https://user-images.githubusercontent.com/73190679/134014738-f3556992-7eb6-44d0-8a78-0504282f5ab0.png)

**Comment by manuelap-msft** [comment]
Hello @mehakvij,

can you share a few more details please - there should be a Log that you an download or if you click on Solution History, you can see the failure with an error message there? We need to work out why it's failing!

Thank you
Manuela

**Comment by mehakvij** [comment]
@manuelap-msft I actually tried it again today and it imported successfully (not sure why - I did the same thing yesterday!)

I've attached a screenshot of the error here though:

![image](https://user-images.githubusercontent.com/73190679/134180209-790b6fdd-a8c7-4680-af9b-630222537112.png)


Thank you! I think we can mark as closed now :) Appreciate the help

**Comment by manuelap-msft** [comment]
Interesting, thanks for confirming! We sometimes see Internal Server Errors when there's timeouts or intermittent service issues. Glad to hear it worked now!
