### ISSUE TITLE
[CoE Starter Kit - BUG] [Child] Admin | Sync Logs - CoE Audit Logs require smaller chunks

### ISSUE THREAD

**Issue by patrickpooon02** [microsoft/coe-starter-kit#1178]
### Describe the issue

We have already amend the Admin | Sync Logs flow to run every hour with each interval (Chunking size) as 1 minute. However we still got the "CoE Audit Logs require smaller chunks" alert... Is there anyway to improve, or let the flow run until there is no more logs within that period of time?

![image](https://user-images.githubusercontent.com/82566841/133539900-15f3659a-e8d2-4ea5-9313-35a2d3a48d10.png)

![image](https://user-images.githubusercontent.com/82566841/133540010-56206047-d116-4094-9afd-3f09ff4ce734.png)

### Expected Behavior

The flow should have ability of Pagination, so all logs can be retrieved.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.3

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by manuelap-msft** [comment]
Hello,

thanks for this suggestion - we are using the Office 365 Management API to connect to the Audit Log (https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference?view=o365-worldwide#working-with-the-office-365-management-activity-api).

Do you have a sample implementation where you are using pagination? That would help us see how we can change the connector.

Thank you
Manuela

**Comment by patrickpooon02** [comment]
Hi I am just referring to some other connectors in Power Automate, for example Sharepoint Online. There is still a limit on the max number of items captured with the action, but still it is useful.

![image](https://user-images.githubusercontent.com/82566841/133718678-125afff1-fe2f-4b28-93ff-45fbd5a5b72a.png)

Another thought is can there be a loop wrapping the getNextPageURI and getContentDetails steps, to let the flow loop through all "Next Page" and get the log entries?

**Comment by Jenefer-Monroe** [comment]
Pagination doesnt work for this connector. It fails the flow when you try to use it. As far as I know, we cannot support pagination for this backend programmatically either. 

Your eventual solution will be to use the [Bring your own Datalake](https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate) solution which we will incorporate with the CoE.

**Comment by patrickpooon02** [comment]
Yes agreed it is connector issue...

How about the loop logic thing? Can that be done to wrap the actions? As we have been saving the logs to Dataverse we don't want to move to other solution.

**Comment by manuelap-msft** [comment]
For large customers, the existing solution of using a cloud flow against the Office 365 API doesn't scale well - both on the API side (e.g. there's no category to retrieve just Power Platform Audit Logs, so a lot of noise to filter out) and not on the flow side either where you soon hit throttling limits. 

Once the Bring your own Datalake solution is GA, we will add dataflows to the CoE Starter Kit that use the data from the Datalake to update Dataverse tables - so where the data is doesn't change for you, just the way of getting it there will change from using the API to Dataflows. 

Because of the development effort on our side for this, and limited resources we have available, we are focusing our effort on the BYO Datalake approach. If you do want to try and get the looping logic to work and share that back here, we'd appreciate that and can incorporate it back into the CoE Kit too! 

Thank you!
