### ISSUE TITLE
Cleanup Power Apps User Shared with takes 4 days to run

### ISSUE THREAD

**Issue by philipbullard** [microsoft/coe-starter-kit#1185]
### Describe the issue

Just noticed this, I think the reason it takes so long to run is that some share to dynamic groups that include all employees.  Just giving a heads up.  It does look like it completes.  May be a good option to be able to disabled some groups from being analyzed from the sharing state?  Not sure… 

### Expected Behavior

Not sure of the impact and inventory results.  It does run successfully, so there is no issue besides it taking so long to complete and possible impact that could have with governance.
![4days2run](https://user-images.githubusercontent.com/17128707/133627323-677d3cf4-7b91-4cdb-b4a7-982a13461db7.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

**Comment by manuelap-msft** [comment]
Thanks for the heads up!

In the Power Platform Admin View (model driven app) we show a list of all the users and groups the app is shared with including the group size - this is to give admins a better understanding of how many users an app is shared with in total
![image](https://user-images.githubusercontent.com/55705669/133635997-789f28db-0508-499f-b28e-9f973ec951a5.png)

I think that would the only place where a slow or unsuccessful run would have an impact. We'll have a look at the flow and see if there's any performance improvements we can make - I'm wondering if instead of running this as one big flow, we could run it as a child flow. We have seen massive performance improvements in other areas by using child flows!

Thanks for highlighting this,
Manuela

**Comment by Jenefer-Monroe** [comment]
working on switching to using child flows for Oct

**Comment by mikefactorial** [comment]
@philipbullard This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
