### ISSUE TITLE
[CoE Starter Kit] Explain how the Archive Score is calculated in the dashboard

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1187]
The Archive Score consists of multiple factors, e.g. when the app was last modified, if it uses words like sample or demo in the name etc. It is often unclear how we came to the conclusion of the score, so enhance the pop up card in Power BI to clearly call out the calculation.

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/134356786-1af6a3d2-3264-4d9f-bd8b-9e897012239f.png)

Added the calculation to the pop up for Apps, Cloud flows and Desktop flows.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
