### ISSUE TITLE
[CoE Starter Kit - BUG] Set App Permissions (and flow) - filter on Environment page doesnt work on load

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1194]
### Describe the issue

we were referring to a control on another page accidently in the filter so it basically got blocked and no-oped until you browsed to that page and returned.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Set Flow Permissions

**Comment by Jenefer-Monroe** [comment]
fixed

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
