### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Resources RMS - does not add expiration date when requested

### ISSUE THREAD

**Issue by thsisonCoe** [microsoft/coe-starter-kit#1197]
### Describe the issue

"Core Components -> Power Platform Resources RMS - Power Apps":
 When admin approved the request for Environment with expiration date, the created environment don't have expiration even though a request specified an expiration of 30 days. Therefore the clean up will not fetch the environment that supposedly expired.

### Expected Behavior

An expiration was set based on the duration

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Env Request | Create approved environment

**Comment by denisem-msft** [comment]
There was an update to the "Env Request | Create approved environment" flow that will be available in the 3.19 release. You may test out the changes in this version: 
[CenterofExcellenceCoreComponents_3_19_2_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7749468/CenterofExcellenceCoreComponents_3_19_2_managed.zip)

**Comment by mikefactorial** [comment]
@thsisonCoe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
