### ISSUE TITLE
[CoE Starter Kit - BUG] Set App Permissions (and flow) - launch button on orphans page doesnt work

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1203]
### Describe the issue

we had an extra slash. env var is expected to contain the slash everywhere else. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Set Flow Permissions

**Comment by Jenefer-Monroe** [comment]
fixed for Oct

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
