### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Compliance detail request v3 - most conditions have one side missing

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1209]
### Describe the issue

A bunch of spots in this flow seemed to have suffered that same data loss bug we saw in the past and have their conditions stripped out on save
Example location:
![image](https://user-images.githubusercontent.com/89584709/134228543-1c318fde-2e27-4713-8d3c-4778a9de383d.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Compliance detail request v3

**Comment by Jenefer-Monroe** [comment]
local fixed for Oct.

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by alangausebeck** [comment]
Condition operands disappear when you rename an enclosing apply.
