### ISSUE TITLE
[CoE Starter Kit - DOCUMENTATION] Env Request - Notify Admin flow needs an env variable set before turning on

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1212]
### Describe the issue

and this is not in the documentation.  so turning it on fails but it doesnt telly ou how to fix. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Env Request - Notify Admin flow

**Comment by manuelap-msft** [comment]
Added this for October release.

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
