### ISSUE TITLE
[CoE Starter Kit in Teams] Environment Capacity management capability

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1217]
The Production version of the CoE Starter Kit supports managing environment capacity in the model driven app. 

Similar capabilities need to be added to the admin view canvas app in Teams.

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/134356231-38511977-0fa5-4b08-8423-5be4be1d6c9f.png)

Done for next release

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
