### ISSUE TITLE
[CoE Starter Kit - BUG] Deleted Custom Connectors not included in CLEANUP - Admin | Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by xmihux** [microsoft/coe-starter-kit#1218]
### Describe the issue

When a Custom Connector is removed, it's not deleted from admin_connector table (or marked as deleted, depending on Env Variable value).

admin_connector table has the 'admin_connectordeleted' column, but all values are false, even if the Connector doesn't exist anymore. 

Custom Connectors are not listed in 'Deletes old items from CoE inventory' Scope of the CLEANUP flow. 
There is also no HELPER flow for it, as there are for Canvas/MDA/Flows/PVAs

### Expected Behavior

Deleted Custom Connectors are included in the CLEANUP - Admin | Sync Template v3 (Check Deleted) flow.

1. In the 'Deletes old items from CoE inventory' Scope, to delete the ones marked as deleted if Env Variable changes
2. In the later part of the Flow, to delete recently removed ones [or create a child Flow as done with other components] 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

1. Create custom connector
2. Run Sync flows
3. Remove a custom connector
4. Run Cleanup flows

**Comment by Jenefer-Monroe** [comment]
I've added this for Oct.

**Comment by mikefactorial** [comment]
@xmihux This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
