### ISSUE TITLE
[CoE Starter Kit - BUG] Add Manager and M2 Manager to Maker form in Model Driven App

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1219]
### Describe the issue

We added a set of flows to ping former managers to deal with objects left behind by people that left the company, and we have a flow which fills this value automatically for people still at the company. 
But we did not offer an easy way for admins to go manually update this value for people that have already left.

### Expected Behavior

added these fields to the form form Makers in the MDA

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
fixed for Oct

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
