### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned Object Reassigment flows - return values coming as string not int

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1220]
### Describe the issue

this is causing it to always look like it failed

### Expected Behavior

correct the return value behavior. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Orphaned Object Reassigment flows

**Comment by Jenefer-Monroe** [comment]
just going to use strings for return values from all child flows for now while the product issues get sorted.

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
