### ISSUE TITLE
[CoE Starter Kit - PRODUCT BUG] The response is not in a JSON format. - fail to find app after returned from get apps

### ISSUE THREAD

**Issue by Lumpybd** [microsoft/coe-starter-kit#1221]
### Describe the issue

We are getting a consistent failure in "Admin | Sync Template v3 (Apps)" flow, on the "Insert New Apps" step. This is only happening when the flow is querying the Default environment, all other environments are processed fine.

The error is "Action 'Get_the_App' failed". If I look at the step in question, it is getting a 404 error back from the request. We have a significant number of apps in the Default tenant, over 400. The step runs for 6-7 minutes before failing.

Raw input:
![image](https://user-images.githubusercontent.com/16439408/134498674-d54d59a6-34f9-45e6-80a5-3046ffdaae13.png)

Raw output:
![image](https://user-images.githubusercontent.com/16439408/134499285-e3db263a-a56c-4bdb-9577-33a4799eb3bb.png)

### Expected Behavior

The step should complete successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

### Steps To Reproduce

1. Execute Admin | Sync Template v3 flow either manually or on the default schedule, wait for it to finish
2. The above flow will then start the "Admin | Sync Template v3 (Apps)" flow once the relevant Environment records have been updated.
3. Wait 6 - 8 minutes - the instance of the "Admin | Sync Template v3 (Apps)" flow that is processing the Default environment will fail.

### Anything else?

All other flows within the Core solution appear to be working without issue.

**Comment by Jenefer-Monroe** [comment]
I believe you may have hit a product bug around caching of deleted PowerApps.   

Can you please try to following to see if this repros outside of the toolkit? 


To use: Import the flow, open, select the environment which repros for you.  

It loops the apps, will hit the same failure and the you can go to support with this flow instead of the toolkit, for faster iteration to fix. 

  

[ProductBug-GetAppfails-TheresponseisnotinaJSONformat_20210418134636.zip](https://github.com/microsoft/coe-starter-kit/files/6671168/ProductBug-GetAppfails-TheresponseisnotinaJSONformat_20210418134636.zip) 

  

![image](https://user-images.githubusercontent.com/62659043/122421743-d4854c80-cf49-11eb-80c6-d3f27474c665.png)

**Comment by Lumpybd** [comment]
I can confirm that this flow fails too in the same environment. Error is "The response is not in a JSON format."

**Comment by Jenefer-Monroe** [comment]
Yes, you will need to contact support then, show them this simpler flow so that they dont get distracted by CoE. There is a caching bug and sometimes **_Get Apps as Admin_** returns deleted apps. They (support) can clear that for you.

**Comment by manuelap-msft** [comment]
Closing as no further action on the CoE Starter Kit needed.
