### ISSUE TITLE
[CoE Starter Kit - BUG] Sync flow errors mail coming in malformatted

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1223]
### Describe the issue

![image](https://user-images.githubusercontent.com/89584709/134546801-7787d901-3528-422e-b349-79d67752a932.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Sync Template v3 (Sync Flow Errors)

**Comment by Jenefer-Monroe** [comment]
local fixed for Oct
![image](https://user-images.githubusercontent.com/89584709/134551239-d3325b9a-a52d-43c9-b66e-f2370a56a8d9.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
