### ISSUE TITLE
[CoE Starter Kit - BUG] Welcome Mail: Make mail go to admin when isProd = false

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1225]
### Describe the issue

When we introduced the isProd env var, we didnt extend it to all the flows. This is confusing to organizations.
Will first get it to apply across Core, only focused on mails sent to end users automatically (aka with inventory data)
- Admin | Compliance detail request v3
- Admin | Welcome Email v3

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin | Welcome Email v3

**Comment by Jenefer-Monroe** [comment]
local fixed for Oct

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
