### ISSUE TITLE
[CoE Starter Kit - BUG] PBIT failing to identify the org url in the tenant

### ISSUE THREAD

**Issue by AlainCote** [microsoft/coe-starter-kit#1228]
### Describe the issue

- [ ] 
<img width="364" alt="Erreur" src="https://user-images.githubusercontent.com/83082048/134917096-29b233d4-8448-4a47-b10a-f840a0dc5edf.png">

We cannot connect to the Power BI report inside that zip package "center of excellence audit logs 2.4 managed". it is always giving us the attach error. The application has been install by the owner of the environment. We tried 4 times so far. 

### Expected Behavior

Be able to connect to the report ans see the visual. 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.4

### What app or flow are you having the issue with?

center of excellence audit logs 2.4 managed

### Steps To Reproduce

1 connect to the environment with Global admin creds.

**Comment by Jenefer-Monroe** [comment]
you may have entered the org url incorrectly. Depending on which pbit you used it either needs to be like this (to include the trailing slash)
**_http://orge.....dynamics.com/_**

or this with no prefix or slashes at all
**_orge.....dynamics.com_**

**Comment by AlainCote** [comment]
We are using the second way with no prefix and we still have the same error message.

**Comment by Jenefer-Monroe** [comment]
and that is the correct tenant id?

**Comment by AlainCote** [comment]
I will have to validate with the Azure admin. Is this a private channel or public ? i just realize there is some sensitive info in the error message.

**Comment by Jenefer-Monroe** [comment]
This is a public channel. Here you can see all the issues for CoE toolkit https://github.com/microsoft/coe-starter-kit/issues?q=is%3Aissue+label%3Acoe-starter-kit+

**Comment by AlainCote** [comment]
So after verification yes it is the same tenant ID.

**Comment by AlainCote** [comment]
Trade id and correlation id, what are they use for ?

**Comment by Jenefer-Monroe** [comment]
Can you restore the picture so that we can better understand the error you are seeing? You can just obscure the private data.

**Comment by AlainCote** [comment]
Voila.

**Comment by Jenefer-Monroe** [comment]
Thank you! You have a nice weekend too! 
Please note that the picture didn't come through though, you will need to update from within GitHub for me to see pictures. I wont see them if you put them in email.

**Comment by AlainCote** [comment]
Did it again.

**Comment by manuelap-msft** [comment]
Hello,

I just want to verify a few things:

- You are saying the Power BI File inside the ""center of excellence audit logs 2.4 managed" solution - there is no Power BI file inside this file, and you have to upload the entire .zip file as a solution - see this step here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow
- If you are using the Power BI file that you downloaded via aka.ms/coestarterkitdownload (it will be named CDSLegacy_CoeDashboard_... or Dataverse_CoEDashboard then you do not enter a Tenant ID or App Registration ID when it asks you for the Org URL - you enter the URL of the Environment where you've installed the CoE Starter Kit - here are the steps on how to get the URL: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#get-the-environment-url

Because you talked about the Power BI file in the Audit Log solution zip folder I just wanted to make sure we're talking about the same things and are on the same page.

**Comment by AlainCote** [comment]
Hi Manuela,

Thank you, I will verify this but unfortunately i don't have access to the tenant today, i will get back to you tomorrow.

**Comment by renaudarmstrongvictrix** [comment]
Hi Manuela,

Im teaming with AlainCote for this project. 

Thanks for the follow-up.

We are having trouble with the CDSLegacy_CoeDashboard and I have followed step by step the instructions provided.


I still get the following error :  

![CoE_Error_Dashboard](https://user-images.githubusercontent.com/91679305/135469741-c80fe96e-9c36-486b-bf5c-2e3dec509671.png)

**Comment by manuelap-msft** [comment]
You're missing an s - the URL has to start with http**s**://
