### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Audit Logs

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#1229]
### Describe the issue

Configure :: Time Interval action failed due to template language expression. 

![image](https://user-images.githubusercontent.com/75992078/134693350-497530f2-253e-440d-8fd0-8b0a88b041d2.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.4

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

**Comment by Jenefer-Monroe** [comment]
Hello as stated in the error message you have updated the env variable **_TimeInterval-Unit_** to a string it does not recognize. I believe they have to be singular (Minute not Minutes). 

Note also that we have offered these env variables for your convenience, in the event you are able to get them to work for you in a better way so that you dont have to worry about keeping the change up to date month over month. 

However we are not able to scale to supporting the exploration there.

**Comment by manuelap-msft** [comment]
Closing as no further action on the CoE Starter Kit needed.
