### ISSUE TITLE
[CoE Starter Kit - BUG] Reset solutions to repair the problems with upgrades

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1235]
### Describe the issue

Since moving to multiple environments, cleaning up connection references, and removing CoE Settings table, we have had nothing but a nightmare of upgrade challanges. 
We have gone and added old items back into the solutions to make upgrades seemless again. These are set to not be used, and we will validate this to be the case each month, and then in ~6 months we will delete them and have an interim solution for folks to use between old and new worlds at that point.  

### Expected Behavior

Regular upgrade through the UX in the normal order (Core, then things like audit etc)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

everything - upgrade

**Comment by Jenefer-Monroe** [comment]
Tested to clean against June 2021 bits starting Oct release.

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
