### ISSUE TITLE
[CoE Starter Kit] Exclude environment from Compliance flow should also exclude it from Developer Compliance Center

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1238]
With #714 we are introducing flags to exclude environments from archive and compliance processes - excluded environments should also be filtered out in the Developer Compliance Center so makers are not prompted to provide further details there.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
