### ISSUE TITLE
[CoE Starter Kit] Developer Compliance Center enhancements

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1239]
The current traffic light symbol does not communicate well enough to makers what next steps there are - we should re-think that flow and discuss various steps / status involved here

- Awaiting information?
- Need to migrate to prod environment? 
- Will be deleted? 
- Ready for archive? 
- Compliant (with an option to filter those out) 

So makers can better see what tasks they have to complete. 

Do we need to write a status from the archive / compliance flow back to the resource table that can flag up in this app etc. 
Do admins configure the traffic light / status information
...

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
