### ISSUE TITLE
[CoE Starter Kit - BUG] Add Company to Makers table and flows

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1240]
### Describe the issue

Some companies/organizations use "Company" field in Azure instead of, or in addition to, "Department" and they need that info in the Makers table in order to track usage. 
Since we want to have the sync flows not very edited, we will add that for them. 

### Expected Behavior

Add to table and flows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Makers

**Comment by Jenefer-Monroe** [comment]
fix in testing for Oct

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
