### ISSUE TITLE
[CoE Starter Kit - BUG] Add Company and Department to Power Platform Users table

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1241]
### Describe the issue

Today we store Department (and soon company) for Makers, but we do not store it for Power Platform Users, though we did add the field

### Expected Behavior

Add this to the flow.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Power Platform Users

**Comment by Jenefer-Monroe** [comment]
fix in testing for Oct

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
