### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor V2 didn't show the list of Analyzed apps and flows

### ISSUE THREAD

**Issue by nowttttt** [microsoft/coe-starter-kit#1249]
### Describe the issue

We have found an issue in the DLP Editor V2 app.
- On the Impact Analysis tab, it didn't show the list of Analyzed Apps and flows. So we can see the list of Apps and flows are impacted.
![DLPEditor](https://user-images.githubusercontent.com/32125374/135040540-12ad68ec-b451-4e80-9f6f-395718ce8aae.png)

- The email icon is displayed overlap with Owner Name
![image](https://user-images.githubusercontent.com/32125374/135042007-bf6a5c33-025f-4494-a7a2-b82bd0db2ba4.png)

### Expected Behavior

- Analysis Tab: It should show the list of Analyzed Apps and flows. And can select to see details.
- Email icon: not display overlap the filed.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

DLP EditorV2

### Steps To Reproduce

1. Input all information in DLP Editor V2 app.
2. Next to Impact Analysis Tab

![DLPEditor](https://user-images.githubusercontent.com/32125374/135040540-12ad68ec-b451-4e80-9f6f-395718ce8aae.png)

**Comment by HamishSheild** [comment]
Hi @nowttttt , I was just about to add a very similar issue.  The reason that the list is blank is because there are no apps or flows that are impacted by the DLP.

However, this page is not very clear...  if there are no impacted apps or flows then...

- I think it would be better to have a message telling the user that there are no impacted apps or flows
- The app details should not show on the right hand side

![image](https://user-images.githubusercontent.com/41050216/135046560-099a33f7-d1f8-491b-a3b0-7b7a28ba6df8.png)

**Comment by manuelap-msft** [comment]
Hello,

that's correct - due to the functions CountRows / Count not being delegable, we can no longer show the number of impacted apps and flows (only analysed ones). But I agree that this screen is confusing in that it doesn't clearly state that you do not have an impact. We'll look into improving the experience, thanks for the feedback!

Manuela

**Comment by mikefactorial** [comment]
@nowttttt This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
