### ISSUE TITLE
[CoE Starter Kit - REQUEST] Add 'When a HTTP request is received' to the DLP Impact Analysis

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#1250]
Similar to [Issue 846](https://github.com/microsoft/coe-starter-kit/issues/846 ), it would be great to have the **When a HTTP request is received** connector added as part of the impact analysis in the **DLP Editor** app.

This is dependent on [Issue 1237](https://github.com/microsoft/coe-starter-kit/issues/1237), to have the **When a HTTP request is received** connector included as part of the Connectors dataset for the CoE

**Comment by manuelap-msft** [comment]
@Jenefer-Monroe was just working on adding the When a HTTP request is received connection. We may find that once that work is done, the DLP Editor will automatically work with this connector as well but need to test!

**Comment by manuelap-msft** [comment]
Fixed for October
![image](https://user-images.githubusercontent.com/55705669/135149318-29ba25cc-a8f1-492f-b3c6-be914a77f820.png)

**Comment by HamishSheild** [comment]
Thanks!

**Comment by mikefactorial** [comment]
@HamishSheild This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
