### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Resource RMS - haven't shown the icon of connectors are not restricted.

### ISSUE THREAD

**Issue by nowttttt** [microsoft/coe-starter-kit#1251]
### Describe the issue

We're trying to request an environment from "Power Platform Request Center" app and then using "Power Platform Resource RMS" app for approval by Admin. 

In the Connector section, it shows the icon and list of connectors.
- the icon for the connectors are blocked is show correct.
- but the icon for the connectors are not restricted is missing. (Admin might confused)

![image](https://user-images.githubusercontent.com/32125374/135044482-37a362f2-216a-46b2-9663-7184d38dd0ff.png)

### Expected Behavior

Show the correct icon for "the connectors are not restricted"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin - Power Platform Resource RMS

### Steps To Reproduce

1. Set DLP Policy for the environment (Block connector)
2. Maker request environment via app "Power Platform Request Center"
3. Admin check the detail of request environment via app Admin - Power Platform Resource RMS.
4. In the section connector- the icon was missing.

**Comment by mikefactorial** [comment]
@nowttttt This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
