### ISSUE TITLE
Enable multi-select of environments and connectors in DLP Editor

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#1253]
**Is your feature request related to a problem? Please describe.**
I recently implemented DLP policies for a client who has over 250 environments.  I created a 'Exclude certain environments' policy in the Power Platform admin centre and excluded all environments except for one, so I could test the impact with the DLP Editor without actually applying the DLP.  In the DLP Editor I had to manually, one by one, assign the environments to the policy which was extremely tedious.

**Describe the solution you'd like**
I would like the ability to select multiple environments and then choose to add or remove them from the policy in bulk.  Similar to how it works when editing DLP policies in the Power Platform admin centre

**Describe alternatives you've considered**
I've considered building this myself :)

**Additional context**
I think the same functionality should be applied to selecting Connectors and assigning them to groups

**Comment by manuelap-msft** [comment]
Hello,

we do have an open but unscheduled backlog item for this (#602), which means it's on our backlog but we haven't funded implementing it. Our current recommendation is to create the DLP Policy in the Power Platform Admin Center, don't assign it to any environments so that at least the connector selection is taken care of. 

I'll close this item as a duplicate. If you do end up building this yourself, let us know and we're happy incorporating your changes back into the CoE Kit :)

Thank you
Manuela

**Comment by HamishSheild** [comment]
Thanks @manuelap-msft , if I need to do a DLP rollout for another customer with a large number of environments I will look at implementing this.
