### ISSUE TITLE
[CoE Starter Kit] Review flows to ensure derived owner trumps owner

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1256]
Review all archive / compliance flows to ensure the derived owner trumps the owner everywhere.

- [x] Archive flows
- [x] Compliance flows
- [x] Orphan flows
- [x] Set Flow permissions app
- [x] Compliance center app

**Comment by Jenefer-Monroe** [comment]
compliance flow does not do flows today so no work there. And compliance center app does not support it yet but is going through a big re-do, the work will happen with that.

**Comment by Jenefer-Monroe** [comment]
We were showing flows owned by people but with a different derived owner in Set Flow Permissions. 
Fixed for Oct.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
