### ISSUE TITLE
[CoE Starter Kit - BUG] HTTP type connectors do not get connected to apps/flows for some reports (ex MDA)

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1265]
### Describe the issue

The HTTP connectors are built in and so they dont show up as connectors by default. 
We did the work to work around this for the DLP Editor but we did not finish the work to make it show up in the Model Driven App and things like this. 
Will investigate to see how easy it would be to fix. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
