### ISSUE TITLE
[CoE Starter Kit] DLP Editor - search environments added to / excluded from a policy

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1271]
### Describe the issue

The user experience for editing DLP policies where the scope is 'Exclude certain environments' could be improved

1. Enable search for the Environments **Added to policy**
2. Rename the **Added to policy** tab to **Excluded from policy** to match the Power Platform admin center wording - this can be confusing and easy to get the DLP configuration wrong.

### Expected Behavior

1. When I search environments while viewing the Added to policy tab of the Environments step in the DLP Editor I expect the list of environments shown to filter based on what I have searched (like it does for the Available tab)

![image](https://user-images.githubusercontent.com/41050216/135048740-3eb55c29-66b5-4152-aa39-9a1e7833eebe.png)

**Comment by manuelap-msft** [comment]
Opened from #1252 to track the search capability, which we are not able to complete in the October sprint.

**Comment by manuelap-msft** [comment]
One might say finally but this is now solved in our dev environment and will be published with our January release:
![image](https://user-images.githubusercontent.com/55705669/146379895-3914a97b-cfac-4f42-998e-af35a42b8668.png)

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
