### ISSUE TITLE
[CoE Starter Kit] Re-design Set New App permissions

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1285]
With the Command Centers and Environment Request Management app, we introduced a great look and feel to our CoE Starter Kit apps. For consistency, we should update the Set New App permissions app with the same look and feel.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
