### ISSUE TITLE
[CoE Starter Kit] Audit Log flow does not update last launch date

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1288]
The Update App Last Launch Date action in the Audit Log flow does not trigger due to incorrectly configured run after statement. This means that the Audit Log itself is updated, but the Last Launch Date field in the Power Apps App table is not updated.

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/135465856-8570a32f-a2d0-40c7-95b2-5883130d3d45.png)

tested and fixed

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
