### ISSUE TITLE
[CoE Starter Kit - BUG] COE Filter Issue on New Dashboard

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#1290]
### Describe the issue

We installed the Dataverse_CoEDashboard_202109.pbit and see that there are many errors in the filter, screenshot attached
<img width="479" alt="COE_filter_error" src="https://user-images.githubusercontent.com/45642255/135485483-3c5367cb-231e-4f35-b084-46c2e96f72ac.PNG">
.

### Expected Behavior

All the filters in the reports should be working

.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2_9

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. Download and open Dataverse_CoEDashboard_202109.pbit
2. Apply associated environment URL
3. Review reports

### Anything else?

No

**Comment by Jodarcy1** [comment]
That version works great, thanks.

**Comment by mikefactorial** [comment]
@Jodarcy1 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
