### ISSUE TITLE
[CoE Starter Kit] Template catalog - use File type in Dataverse

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1302]
The Template Catalog currently uses a SharePoint list where templates are stored. We can replace this with the File/Image datatype in Dataverse which should also work in Dataverse for Teams and reduce the overhead of what needs to get created before this can be used. 

To Do:

- [x] - Create a template catalog table with the necessary fields + file field to store the template 
- [x] - Update Template Catalog app to use the table instead of a SharePoint list
- [x] - Update setup instructions to remove the need for creating a SharePoint list

**Comment by manuelap-msft** [comment]
Done for January release.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
