### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Center don't use the Browser Window Space correct

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#1321]
### Describe the issue

The layout of Developer Compliance Center don't align correct in App Detail Screen:
![image](https://user-images.githubusercontent.com/15800069/136157040-44e2e795-14ea-4e72-9407-bb39f2e5f1c6.png)

The browser window have a size of: 2048x1191
Browser Zoom is 100%
Browser: Google Chrome Version 94.0.4606.61 (Official Build) (64-bit)

### Expected Behavior

Correct Layout

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Developer Compliance Center

### Steps To Reproduce

1. Open Developer Compliance Center in Browser Window (**not full screen**) e.g. 2048x1191
2. Navigate to App Details

**Comment by Jenefer-Monroe** [comment]
I believe Manuela has fixed this now with her re-design of teh compliance center for Jan.

**Comment by mikefactorial** [comment]
@megel This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
