### ISSUE TITLE
[CoE Starter Kit - BUG] Unneeded tab on Portal form

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#1329]
### Describe the issue

Hello Coe Team,

Just a simple one, nothing important. In the "Power Platform Admin View" model-driven app, on the Power Apps Portal form, there is an empty tab called "New Tab".

Don't think that's needed.

![image](https://user-images.githubusercontent.com/68440710/136330249-c91e6e59-d845-49dd-89fd-8256fbb56410.png)

Thanks very much,

Garry

### Expected Behavior

"New Tab" not showing on the Power Apps Portal form.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

Open Power Platform Admin View
Click Portals
Open a portal record
See the empty tab called "New Tab"

**Comment by mikefactorial** [comment]
@GarryPope This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
