### ISSUE TITLE
[CoE Starter Kit - BUG] Model Driven Apps sync flow not writing App Environment ID string

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1332]
### Describe the issue

We forgot to add this to MDA sync when we added to canvas

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Model Driven Apps)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
