### ISSUE TITLE
[CoE Starter Kit - BUG] Set App Permissions (Dataverse for teams) User photo error. 

### ISSUE THREAD

**Issue by J04nn4** [microsoft/coe-starter-kit#1336]
### Describe the issue

When in the app, owner tab, looking for people get following error. (freshly deployed COE core for D4T on 10/05) 
![image](https://user-images.githubusercontent.com/35706419/136453308-10ee65d4-c3a0-440c-9886-6650f9ece395.png)

### Expected Behavior

no error when filtering owners.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.2 (Core for Teams)

### What app or flow are you having the issue with?

Set App Permissions 

### Steps To Reproduce

Open Set App Permission install in D4T. 
go to owner tab
type user name

**Comment by Jenefer-Monroe** [comment]
validated for Nov release

**Comment by mikefactorial** [comment]
@J04nn4 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
