### ISSUE TITLE
[CoE Starter Kit - BUG] "CLEANUP HELPER - Power Apps User Shared With" flow does not save App info

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#1369]
### Describe the issue

"CLEANUP HELPER - Power Apps User Shared With" flow does not save App, so for example the "App shared with" table in Power Platform Admin view. See more details in this closed issue #569 

After defining App in the Flow then started to see users in App shared with list

![image](https://user-images.githubusercontent.com/8307644/137309999-a3ae31c3-5bd4-4f69-b865-89be3e152ef8.png)

![image](https://user-images.githubusercontent.com/8307644/137310607-f83e015d-5b6d-493d-9b94-2a4816c2162e.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

**Comment by Jenefer-Monroe** [comment]
Thank you for posting, working on a fix for Nov.

**Comment by Jenefer-Monroe** [comment]
local fixed for November

**Comment by mikefactorial** [comment]
@petepuu This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
