### ISSUE TITLE
[CoE Starter Kit] Include Power Platform release wave notes in Command Centers

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1375]
The Release Wave notes have an RSS feed https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave2/power-apps/ and it would be useful to include this information in the Command Center as well, so that admins can be prepared for what new is coming when.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
