### ISSUE TITLE
[CoE Starter Kit - BUG] App Settings button doesn't work for teams environments

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1383]
### Describe the issue

Use one of our apps with these buttons
![image](https://user-images.githubusercontent.com/89584709/138136658-c143835e-4fda-466e-80f4-6c55845a9629.png)
![image](https://user-images.githubusercontent.com/89584709/138136693-499e17ef-9eb7-43b2-84e2-daab7e576da0.png)

Try to use the button to get to apps/flows in teams environments, it doesn't work. 

Set App Permissions, Compliance Center, ...

### Expected Behavior

Either make this work or (more likely) make it obvious that the button wont work in that case. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Set App Permissions

**Comment by Jenefer-Monroe** [comment]
apps only, this works for flows.

**Comment by Jenefer-Monroe** [comment]
local fixed Jan for Set App Permissions

**Comment by Jenefer-Monroe** [comment]
local fixed Compliance Center for Jan

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
