### ISSUE TITLE
[CoE Starter Kit - enhancement] add role setting to CanvasAppOperations helper flows

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1384]
### Describe the issue

we create new owners with this helper but did not update the user role table. 
this was needed for the work in Developer Compliance Center.

### Expected Behavior

fixed to both Core and Gov

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

CanvasAppOperations

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
