### ISSUE TITLE
[CoE Starter Kit] App Catalog - update with feedback option and other enhancements

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1391]
We refreshed the **App Catalog** with a few updates:

- Updated the UI to look like the Admin - Command Center app
- Update the App Detail screen to include
  - list of connectors this app uses
  - list of feedback & ratings
  - ability to leave star ratings and feedback
  - ability to email the maker
  - ability to request access which works via a Teams card + then grants access
- added new table called App Catalog Feedback with fields rating, feedback & lookup to App
- added a new field to the PowerApps App table which will be a rollup of all ratings to calculate the average

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/138311520-c1fce9b4-25e9-4e47-9ff7-88c21902a96b.png)

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by jukkan** [comment]
Did this version of the App Catalog actually ship in some release? I haven't seen the new UI or ratings features in either of the Core packages that I've installed.

**Comment by manuelap-msft** [comment]
Interesting! Yes, shipped in November - are you looking at Core in Production or Core for Teams?

**Comment by jukkan** [comment]
I installed both of them this week. It turns out actually both environments had an unmanaged layer for this app, which was a surprise to me. I didn't think of checking it since I hadn't consciously touched the Canvas app, but perhaps there has been something about the previous setup process that had led to the layer being created in both scenarios. Anyway, all good now & the new version is a clear improvement over the old one!
