### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by RimpalAgarwal** [microsoft/coe-starter-kit#1399]
### Describe the issue

Here are the details of error

1.	Flow Name :  Admin | Sync Template v3 (Apps)

Error
Action 'Get_Apps_as_Admin' failed

Error Details
The request failed with client error: 'The environment '<null>' could not be found in the tenant 'e0793d39-0939-496d-b129-198edd916feb'.'. The correlation Id is '86978df5-2023-4c07-8e0d-b1a67e081c9a'.

2.	Flow Name : Admin | Sync Template v3 (Flows)

Error
Action 'List_Flows_as_Admin' failed

Error Details
You are not permitted to make flows in this 'c6cbd56a-115a-4b06-bdc1-82f4111edcac'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions.

### Expected Behavior

Flow should end without any error 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps) , 2.	Flow Name : Admin | Sync Template v3 (Flows)

### Steps To Reproduce

check error in Run history

**Comment by Jenefer-Monroe** [comment]
You failures for the Apps do indeed look to be due to the product caching issue we discussed. 
We installed the flow together and had it running to loop all apps in the default and then get, once that fails you can go to product support and they can fix your cache. Here is that flow again, in case you need it. 

**Deleted Apps Product Bug** 
I believe you have hit a known product bug around caching of deleted PowerApps. If so, you will need to contact support to have them clean this up in order to have this flow start passing.   
Our recommendation is to first get a repro outside of the toolkit before contacting support. You can use the below flow to get this repro.   

To use: Import the flow, open, select the environment which repros for you.   
It loops the apps, will hit the same failure and the you can go to support with this flow instead of the toolkit, for faster iteration to fix.  
[ProductBugDemo-getappaftergetappsfails_20211108125525.zip](https://github.com/microsoft/coe-starter-kit/files/7497063/ProductBugDemo-getappaftergetappsfails_20211108125525.zip) 
![image](https://user-images.githubusercontent.com/62659043/122421743-d4854c80-cf49-11eb-80c6-d3f27474c665.png)

**Comment by Jenefer-Monroe** [comment]
The flow error sounds like it could also be the same caching bug from what you have shared, here is the flow version of the above to test with:

**Deleted Flows Product Bug** 
I believe you have hit a known product bug around caching of deleted flows. If so, you will need to contact support to have them clean this up in order to have this flow start passing.   
Our recommendation is to first get a repro outside of the toolkit before contacting support. You can use the below flow to get this repro.   
To use: Import the flow, open, select the environment which repros for you.   
It loops the flows, will hit the same failure and the you can go to support with this flow instead of the toolkit, for faster iteration to fix.  

[ProductBugDemo-getappaftergetappsfails_20211108125525.zip](https://github.com/microsoft/coe-starter-kit/files/7497087/ProductBugDemo-getappaftergetappsfails_20211108125525.zip) 
![image](https://user-images.githubusercontent.com/62659043/124291999-64162800-db12-11eb-92a6-55b4ffe1ecee.png)

**Comment by Jenefer-Monroe** [comment]
Looks like I pasted the wrong link for the flow one, here that is fixed

To use: Import the flow, open, select the environment which repros for you.   
It loops the flows, will hit the same failure and the you can go to support with this flow instead of the toolkit, for faster iteration to fix.  
[ProductBugDemo-getflowaftergetflowsfails_20211116133300.zip](https://github.com/microsoft/coe-starter-kit/files/7546680/ProductBugDemo-getflowaftergetflowsfails_20211116133300.zip)
![image](https://user-images.githubusercontent.com/62659043/124291999-64162800-db12-11eb-92a6-55b4ffe1ecee.png)

**Comment by Jenefer-Monroe** [comment]
Have you folks been able to test this?

**Comment by RimpalAgarwal** [comment]
Hi @Jenefer ***@***.***>

I was able to recreate the failure scenario for APP , but not for flow. I have re-executed the flow for another environment to check if I can recreate the failure scenario for Flow also.

Here are the details for APP failure. Please let us know what is the next step .. on how to fix this caching issue



Thanks and Regards,
Rimpal Agarwal

    COVID SUPPORT – WE ARE IN THIS TOGETHER!
[A red heart image placed on open hands]
I A red heart image placed on open hands
24/7 doctor’s tele-consultation <https://people.accenture.com/stream/eventid/39674987> (Audio/Video service) Call or WhatsApp to 9111891118 with the text "Hi I am from Accenture"
COVID-19 handy emergency guide<https://in.accenture.com/india/?site=1&blog=548&p=50997&referrer=mailer>  | RT-PCR testing<https://in.accenture.com/india/?site=1&blog=548&p=64930&referrer=mailer> (with home sample collection) | Reimbursement for RT-PCR testing | Accenture in India<https://in.accenture.com/india/?site=1&blog=548&p=64930&referrer=mailer>
Vaccination reimbursement benefit<https://in.accenture.com/india/?site=1&blog=548&p=63804&referrer=mailer> (for all people who are eligible as on date) | India Covid vaccination update | Accenture in India<https://in.accenture.com/india/?site=1&blog=548&p=63804&referrer=mailer>
ASOC 24/7 Emergency Helpline number +91-80-4106 2762  |  Ask DiPA for HR Queries<https://teams.microsoft.com/l/app/023730bf-64a7-4455-8298-c260e938640e>


From: Jenefer Monroe ***@***.***>
Sent: Wednesday, November 24, 2021 6:29 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Agarwal, Rimpal ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] your issue (Issue #1399)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


Have you folks been able to test this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dstarter-2Dkit_issues_1399-23issuecomment-2D977334441&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=jRz1Ov-ZInftgYmPO6bHyNNio5obnKHQBE0oCRcm-_M&m=x6SjifV3s2VKkPu8Wu1kotFuUpKtd59REmTMtCpUxG8&s=J8HcU0vtnQ85F6245xjN4ehydZYA0ib6yFDLao8JTMM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AWGOKPDIWWZKAIKBVG32I7TUNQ2DVANCNFSM5GUTCJLQ&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=jRz1Ov-ZInftgYmPO6bHyNNio5obnKHQBE0oCRcm-_M&m=x6SjifV3s2VKkPu8Wu1kotFuUpKtd59REmTMtCpUxG8&s=NTTVp2WueIT_XWGOYL1VnAI0JOcguG11LssO6JjJFHk&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=jRz1Ov-ZInftgYmPO6bHyNNio5obnKHQBE0oCRcm-_M&m=x6SjifV3s2VKkPu8Wu1kotFuUpKtd59REmTMtCpUxG8&s=A2z2qQwJMsovGcJxsyMz-RCFQzvQB8uqF98jEQszD38&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=jRz1Ov-ZInftgYmPO6bHyNNio5obnKHQBE0oCRcm-_M&m=x6SjifV3s2VKkPu8Wu1kotFuUpKtd59REmTMtCpUxG8&s=zSFPmeASGQ_lh8BVKOTnUOlcmQ4Zcht2TW_sY2WHoOU&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by Jenefer-Monroe** [comment]
Being tracked in email. Please work with Vasavi to schedule if you still need help here. 
Thank you
