### ISSUE TITLE
Command Center - Environment Variable Section

### ISSUE THREAD

**Issue by missbets** [microsoft/coe-starter-kit#1403]
Error: Field 'schemaname is required'
Issue: When using environment variable section in command center power, the above error pops up. 
Resolved: Default Sol > environment variables > create a current value for specific environment variable
Once creating a current value, user will be able to edit environment variables using the command center app

**Comment by Jenefer-Monroe** [comment]
local fixed for Dec.

**Comment by mikefactorial** [comment]
@missbets This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
