### ISSUE TITLE
[CoE Starter kit] Add field for environment purpose to enviornment table

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1406]
Add field to document environment purpose (such as used for Production, Development, Test, Training) to Environment table.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
