### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Connection Status) - fails when you run in to deleted apps and flows

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1417]
### Describe the issue

We get the list of apps/flows from the inventory and then get details from the product. if its been deleted (and check deleted hasnt run yet) it fails. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Connection Status)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
