### ISSUE TITLE
[CoE Starter Kit - BUG] Check Deleted - PVA and MDA helpers timing out now for Teams sku 

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1418]
### Describe the issue

Due to recent product changes, we now retry a bunch and the time out in the helpers for PVA / MDA for Teams envt. 
We cant inventory from those envts anyway. So the fix is to check and not send to the helper for these cases.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
