### ISSUE TITLE
[CoE Starter Kit] Configurable text for emails

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1420]
Currently users have to edit flows to make the email and adaptive card text their own which leads to unmanaged layers and update issues, it also is difficult to review the email text or even know which flow sends what. 

- have an email configuration table that we preload with data (maybe not with a dataflow though)

- all flows pull info from that table

- where we dynamically have text we could use placeholders that we then match (e.g. something like {AppName} that we would replace with the actual app name) OR keep dynamic parts hardcoded at the bottom or start of the email 
- fail flows if text is not configured

**Comment by HamishSheild** [comment]
This would be awesome! 

I've done something similar for a client recently (nothing to do with COE) using a custom table for email/letter templates. It works well. 

Inserting dynamic data is a pain with Power Automate as you end up with a huge set of nested Replace statements. Quite nasty. I am interested to see how you would handle this.

Happy to help out and share learnings if your are interested.

**Comment by modery** [comment]
We've just had this done for us as part of a bigger CoE setup engagement, and it works as you described it. Think it would definitely be worthwhile to introduce this generally.

**Comment by Jenefer-Monroe** [comment]
**Here is my current plan of action:** 
-	We will have a table that stores the current values for emails and their subject lines
-	One table for CoE or a Table per solution TBD. (worried about creating new dependencies to Core)
-	There will be a sync flow which runs monthly (to get monthly CoE upgrades) which updates the subject and body columns, if their associated “Default” is still set to true
-	This is because sometimes we update the text in a flow based on feedback (typos, product changes, etc)
-	The flow will work similarly to how we used to do starter data for things like Innovation Backlog
-	The app we create to update these values will set these “Default” fields to false if they are edited by the CoE Admins, and then they will not be overwritten in the future if we change the values
-	We may add to the Admin – Command Center app for this
-	We will ship with only the En-US values for all the mails, but will look for language from O365 Users connector and allow admins to map this to other languages, and add rows for those.

**Column Descriptions**
-	Solution – If we have a single table, this will specify which solution the flow is in
-	Flow Name – the name of the flow being configured
-	Action Name – the name of the action being configured
-	Target Audience – the persona for which the mail is intended, this is to help organizations review the list
-	Default Subject – true = the subject is as written by MSFT CoE team, ok to overwrite on next flow run. False = the subject has been edited, do not overwrite.
-	Subject – Subject to use in the flow
-	Default Body –true = the body is as written by MSFT CoE team, ok to overwrite on next flow run. False = the body has been edited, do not overwrite.
-	Body – Body to use in the flow 
-	CC – if there is an identity to put on the CC line. This is added as there are often sub-categories of admin-email to be used, can now be put in CC
-	Language – allows admin to enter new rows for different languages. We ship only en-US. If the call to O365 users returns a preferred language that is blank or not in the table, defaults to en-US.

**Example row in the table**
![image](https://user-images.githubusercontent.com/89584709/139732830-7e9896d3-43c6-4fff-9170-08c6714cd4cc.png)

**Comment by Jenefer-Monroe** [comment]
For variables, we are just going to have that embedded in the text as shown here from the example above.
 ```
 <li><a href="@{parameters('Community URL')}">Our Power Platform Community</a></li>
```

This allows the flow to remain simple, and just re-uses the products concept of dynamic data embedded in the text.

**Comment by andrewgaskins** [comment]
Yes this would be a big deal. I was just updating our Compliance Detail flow and thinking about managing those layers on updates. It would also be nice to have a chance to decide if you want this to be an email or post a card for the user in Teams.

**Comment by Jenefer-Monroe** [comment]
As a stretch goal, I am considering having all the emails sent to a helper flow which will send the email. It could then be augmented to be teams in a single location. But I am not certain if we can do that as part of this ask. If not, you can add it as a separate ask once we release.

**Comment by andrewgaskins** [comment]
@Jenefer-Monroe I was thinking the same thing when updating the emails about the helper flow. Looking forward to seeing what you do.

**Comment by Jenefer-Monroe** [comment]
Considering also adding a Sent-On-Behalf of column. Though would need to make it clear how to configure this to folks so its not a big ticket generator.
Would this be of interest for folks?

**Comment by bigpix2000** [comment]
So far so good on the plan.  Everything making sense so far.  A couple of observations:

- Sent on Behalf is a tough one ... the case of underscoring that the sender is not the one you should "reply to" (noreply@tenant.ext)  it takes up space and might be more confusing than perhaps letting the admin handle the "replies" to the service account via the same tools we are managing (cough cough Flow cough)  and not sure if it merits extra help in the "starter kit" but, well, why not ...  :-)   Short answer is it is interesting but I don't know if it is a priority.  Oh wait, so if you do that there, you mean to do it all across the kit?  
- For the updates ... wondering if there can be a "use default" flag so that after the folks update the text variables, they can decide that after an update that they may PREFER the default just like with our phones in setting up the voice mail answering .. we can always let the system do it but we can choose to go custom to the last custom one we did?  That way no issue on overwrite but rather a case of "get from here instead of there" situation.  It allows also to potentially use the default to for the non-english version translation or to vary it by region.  Just a thought there.  
- Last thought was I liked the way you are handling the variables! (hearted!)  Thanks again!!

**Comment by Jenefer-Monroe** [comment]
Unfortunately the technique for variables described above does not seem to work. 

As an example, this stored in a multi-line text field in Dataverse:

> Some of the Sync Flows in the CoE Starter Kit have failed. See below and navigate to the Flow Instance URL to find out more details:
> @{outputs('Compose_HTML_Table')}
> 

Then pulled in to body of the email does not evaluate the variable into the html table, it just writes out as text
![image](https://user-images.githubusercontent.com/89584709/140506228-c4cf3f06-8f91-4a3b-b59d-6d5bb34ff4e3.png)

If anyone here knows how to force Power Automate to evaluate variable again, please let me know. I have a few things to try yet, otherwise I'll just restructure all the emails to have the variables present at the end.

**Comment by bigpix2000** [comment]
This appears to be the case of the Flow evaluating the variable before it is even ready and you are trying to "ignore" things until there is a value (or a true error) yes?  Confirming that the source of the data is dataverse or a passed in parameter or environment variable or something else?

**Comment by Jenefer-Monroe** [comment]
Correct, the data is stored in Dataverse and passed in to flow through the Dataverse connector.
I think you are also correct that this it is flow itself doing the evaluation early, as I have tried multiple actions/connectors to try and get around this.
I find no settings to change when this occurs. It also will not treat html tags correctly, just places them in as strings.

**Comment by bigpix2000** [comment]
Ah ha!  so another thought.   It is email after all (cough cough "outlook") .... Last I saw a flow have to to Rich text manipulation (and I was so hoping that HTML tags worked) had them calling Word and doing the "automation" there and then sending the body in the email.  Trying to find the sample but the idea came up awhile back because at least back in 2019 or so it was definitely not possible to use HTML strings in.  Quick question is even if it is a "string" for the body, is there not an option for the mail connector for Rich text?

**Comment by hernan-ramirez** [comment]
Hi everyone! Jenefer, would it be possible to use Word Templates with properties to generate the text content? And then we can use the Document Converter to get both, HTML or Markdown? I know that we would have to have a document library with the templates, and it would be a template by notification. 

How do you see this idea?

In the table row, it would be the same as Jenefer described, but in the body value it would be the URL of the Word template. I really like that there is also a column for "Send as".

Regards!

**Comment by Jenefer-Monroe** [comment]
Hello, word templates would be a good idea to explore. Unfortunately they are not ISV friendly. 

In other words, we cannot rely on any of the office actions (Excel, Word, ...) in the toolkit as when you import them into your own tenant, you have to redo the actions, which in the case here would be substantial work each month. 

Thanks for helping think outside the box!

**Comment by bigpix2000** [comment]
It makes sense ... I explained exactly this as to why it was GitHub and Not ADO out of the box for the ALM Piece and also why Excel Reporting was left to the Power BI OOB experience. We don't want to create a custom API that needs Azure for example although on the edge there as we rely on tools like AAD for registrations etc.  Logic apps are pay as you go and add an extra burden to the concept of the starter kit which is to be "free" at least for the first 30 days  ...  hmmmm. Unless we say just like you can get a trial for Power apps you can get one so you can do a Logic app?  hmmmmmm .... Just a thought.  

So the clue feels like it is in how anyone would use Power Automate to send a Rich Text email at all ...  Test that and at least we have something that might be modifiable ?

**Comment by bigpix2000** [comment]
The case of if we can format it it via a variable that is ... we know there is formatting because we see it now ...  right?

**Comment by hernan-ramirez** [comment]
I have had the experience of working with word templates and ALM and it was not too hard. The templates are distributed as the CoE Started Kit does with the Dashboard in Power BI. The word template activities can be completed with environment variables to fill the site and library, and then the file name is the column "URL body" of the table designed for Dataverse. There is no need to redo the flows in that case.

However, if we have the original idea of using the text value of a column and record without token to replace, and then we put the dynamic contents at the end concatenated, it would be perfect for the first version!!

**Comment by hernan-ramirez** [comment]
mmm... "tokens to replace" ?? If the value of body field in dataverse is: "My message [[MyVariableToReplace]] and more message" and replace [[MyVariableToReplace]] with my dynamic conten by automate expression ??

**Comment by Jenefer-Monroe** [comment]
I don't think we can scale to having custom code at each mail to fill in the variables. If we cannot get the product to interpret them as is, brought in, then I think we will need to just have the variables at the end of each mail. 

For now, I am going to go forward with this plan (variables at the end) and cross my fingers that we don't run in to more issues. 

If anyone here has a sample solution I can use to test word templates working across tenants, please share. As we have an awesome solution for the CoE we never shipped as we couldn't get this to work

Thanks for the feedback!

**Comment by bigpix2000** [comment]
time to hunt for that, team!  checking the MVP's and the sample repositories to see if there is anything sitting in plain site ... probably need to dig a bit since that very specific action is not in the title of the sample.

**Comment by Jenefer-Monroe** [comment]
local fixed for Dec. Finishing testing. 
Dec will have only the cloud flows in Core complete. And in future months, with feedback, we will extend into Gov and Nurture

**Comment by bigpix2000** [comment]
Good start .... anticipating documentation or guidance updates to coincide or should we keep note until then?

**Comment by Jenefer-Monroe** [comment]
Yes the how-to for this will be in the documentation when we release Dec!

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
