### ISSUE TITLE
[ALM Accelerator - BUG]: issue title

### ISSUE THREAD

**Issue by mehakvij** [microsoft/coe-starter-kit#1425]
### Describe the issue

Getting the below error on load of the app. 

![image](https://user-images.githubusercontent.com/73190679/139692418-802de825-257d-4720-bc3c-1faf693bd137.png)

If I try to import, I only see this, even though I do have a build from Nov 1.

![image](https://user-images.githubusercontent.com/73190679/139692786-43e502c3-a3cb-4652-b8de-0ced1f7ebb11.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

July 2021

**Comment by mikefactorial** [comment]
@mehakvij can you verify that the build in question from November 1 has an id of 327738 as the error message states? There was a bug in the previous releases related to builds getting deleted from Azure DevOps but being referenced in the App User Settings that causes the error you are seeing. It should be fixed in the latest version. You can see the buildId in the url for the build run instance (e.g. https://dev.azure.com/org/coe-starter-kit-azdo/_build/results?buildId=**6306**&view=results

**Comment by mehakvij** [comment]
Hi @mikefactorial checked and from Nov 1, the id is 370884.

Mehak

Will just updating the PowerApp for now fix this? Or should I be updating the pipelines too

**Comment by mikefactorial** [comment]
@mehakvij seems like the thing the app is complaining about is a build number that was stored in the user settings and no longer exists in Azure DevOps which was the issue we had previously that was fixed in the update. Would definitely recommend upgrading to the latest version. There's a lot of enhancements available in that release.

You'll need to update both the pipelines and the solution. There are upgrade instructions in the release notes to help with the process. https://github.com/microsoft/coe-starter-kit/releases/tag/ALMAcceleratorForAdvancedMakers-September2021a.

**Comment by mikefactorial** [comment]
Closing this for now. Feel free to open another issue and reference this if need be.
