### ISSUE TITLE
[CoE Starter Kit - BUG] CDSLegacy_CoEDashboard_202110 + Portals Table

### ISSUE THREAD

**Issue by missbets** [microsoft/coe-starter-kit#1442]
### Describe the issue

When setting up the Power BI Dashboard, the below error is shown: 

OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Portals Column 'admin_portalenvironment' in Table 'Portals' contains a duplicate value '4b086820-7b50-47be-8a8a-9f08d04d515c' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.

### Expected Behavior

No errors occur in queries

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CDSLegacy_CoEDashboard_202110.pbit

### What app or flow are you having the issue with?

Power BI Legacy Dashboard

### Steps To Reproduce

1. Open power bi dashboard Legacy template
2. enter org url with https:// prefix
3. Sign in
4. Error occurs

### Anything else?

Workaround - In PowerBI Dashboard > Transform Data > "Portal" Table > delete Column 'admin_portalenvironment' in Table 'Portals'. After doing this, all errors were gone.

Seems like this error occurs when there are multiple power app portals created in the same environment, which is a new feature (https://powerapps.microsoft.com/en-us/blog/power-apps-portals-create-multiple-portals-in-your-dataverse-environment/)

**Comment by Jenefer-Monroe** [comment]
Can you please let me know what version of the toolkit (Core solution) you are using? 
In the Nov build released yesterday (3.18) we believe we have worked around this new feature in Portals and that the inventory will no longer have duplicates after the inventory runs.

**Comment by missbets** [comment]
Hi Jenefer! 
I was helping another M36 admin set it up. We attempted both builds (November + October) and got similar error messages.

**Comment by Jenefer-Monroe** [comment]
I'm afraid we dont repro this. Will hold for a bit for others to see the workaround, and hope that it works itself out.

**Comment by manuelap-msft** [comment]
Hello,

I was able to repo this and it is due to an incorrect relationship between the Portals and Environment table in Power BI. We will fix this for December. 

You can fix it yourself by choosing Manage Relationships in Power BI desktop:
![image](https://user-images.githubusercontent.com/55705669/142418330-5ea9fd28-b31d-43d5-83a3-90be559bbb48.png)

and changing the relationship between Portals and Environment to many to one:
![image](https://user-images.githubusercontent.com/55705669/142418396-b8679a85-24c7-4e32-b317-e73e59e9b26b.png)

It is one to one at the moment which is causing this issue.

Thank you
Manuela

**Comment by mikefactorial** [comment]
@missbets This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
