### ISSUE TITLE
[ALM Accelerator - BUG]: export-to-git pipeline failing

### ISSUE THREAD

**Issue by ServiceAdmin365** [microsoft/coe-starter-kit#1448]
### Describe the issue

Export-to-git pipeline failing with error : No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request.
Requested the access from the MS Form request but still not received the access or am I missing anything

### Expected Behavior

Export the solution to Git

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20211001.1

### Steps To Reproduce

Tried to click on button from Canvas App "Push changes to GIT"

**Comment by mikefactorial** [comment]
@ServiceAdmin365 the request for pipelines in the free version of Azure Devops can take a few days. May just need to be patient. Unfortunately, we don't have any line of sight into those requests ATM.

**Comment by glemis** [comment]
So is it to be understood that parallelism is required to make use of the COE ALM.
Usually, in pipelines I have developed pipelines would be queued if triggered while the free agent is in use. 

Hoping there is some way to run without enabling paying for parallel jobs. 
I see in regards to enabling many makers to author and maintain apps parallelism  is pretty important.

But I would really like to use the COE for a small controlled group of makers where conflicting demand for the pipelines is less of a concern.

**Comment by mikefactorial** [comment]
@glemis the issue here is that running pipelines, in general, aren't allowed for newly created free AzDO accounts. The history is that people were misusing the compute time in AzDO's free tier so it had to be locked down and enabled via a specific request to Microsoft. The error that is thrown talks about parallelism, but that's a bit of a red herring. Assuming you are able to run pipelines in your organization, whether it's the free version or paid version will allow you to use the ALM Accelerator. I'm going to close this issue out since it's stale but feel free to open a new issue if you have further questions.
