### ISSUE TITLE
[CoE Starter Kit - BUG] Pagination policy set to 100000 by default while 5000 is max allowed 

### ISSUE THREAD

**Issue by pallvip** [microsoft/coe-starter-kit#1450]
### Describe the issue

The pagination policy on the flows are set to 10000 by default while 5000 is max allowed and hence causing flows to fail.
Can you please fix the package as we cant possibly update all flows.
![image](https://user-images.githubusercontent.com/40602120/140898587-0126bf84-00dc-4d2e-aa2a-16a3a3f58697.png)
![image](https://user-images.githubusercontent.com/40602120/140899521-15aa764f-3c01-4c07-903d-7b46a9c8fb5e.png)

### Expected Behavior

The Pagination policy should be in allowed limit, and we should be able to save connection references.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Canvas Apps)

**Comment by pallvip** [comment]
![image](https://user-images.githubusercontent.com/40602120/140900237-abf65d2a-5014-4b1a-8e36-9fe91c127da3.png)

**Comment by manuelap-msft** [comment]
Hello,

this is due to you having an insufficient license to run the flows. 

Please see:
Power Automate performance profiles https://docs.microsoft.com/en-us/power-automate/limits-and-config#performance-profiles
Pagination limits per profile https://docs.microsoft.com/en-us/power-automate/limits-and-config#concurrency-looping-and-debatching-limits
And hence our limitation https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#trial-licenses
