### ISSUE TITLE
[CoE Starter Kit - BUG] Add storage limitation line to the table on choosing between D4T and Prod

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1459]
### Describe the issue

From this user: 
https://github.com/microsoft/coe-starter-kit/discussions/1457

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
fixed as part of documentation rewrite

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
