### ISSUE TITLE
[CoE Starter Kit - BUG] Cleanup Old Objects App - when person not a manager has bad screen

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1465]
### Describe the issue

![image](https://user-images.githubusercontent.com/89584709/141197533-1918cfc4-46d5-4142-871b-5741b221d83d.png)

### Expected Behavior

hide it when no users

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.8

### What app or flow are you having the issue with?

Cleanup Old Objects App

**Comment by Jenefer-Monroe** [comment]
local fixed for Dec

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
