### ISSUE TITLE
[CoE Starter Kit - BUG] Security Role for Makers on Archive Approvals table missing Append To

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1474]
### Describe the issue

![image](https://user-images.githubusercontent.com/89584709/141308243-6c2a7599-a1b2-4339-8fa2-0158721a5dec.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.8

### What app or flow are you having the issue with?

Cleanup Old Objects App

**Comment by Jenefer-Monroe** [comment]
local fixed for Dec
![image](https://user-images.githubusercontent.com/89584709/141308366-f8194412-d9b0-4a45-bf09-595f12519035.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
