### ISSUE TITLE
[CoE Starter Kit - BUG] Check Deleted - Failure Array not included for first round (newly deleted environments)

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1479]
### Describe the issue

Missed doing this step
![image](https://user-images.githubusercontent.com/89584709/141841469-60e76fed-9792-4880-9e91-a7574dfd662e.png)

for newly deleted environments

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment]
local fixed December

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
