### ISSUE TITLE
[CoE Starter Kit - BUG] Add Env Vars for command center application to get m365 messages

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1486]
### Describe the issue

today they have to edit the flow and hence get an unmanaged layer that will prevent updates/
![image](https://user-images.githubusercontent.com/89584709/142000601-e641f600-18cd-460a-aa72-d6eff622bee9.png)

### Expected Behavior

env vars instead

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Command Center App > Get M365 Service Messages

**Comment by Jenefer-Monroe** [comment]
![image](https://user-images.githubusercontent.com/89584709/142002148-9365c9d4-49c4-4710-9dbb-6bce884d78d2.png)

local fixed for Dec

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
