### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Command Center - remove delegation errors

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1487]
### Describe the issue

Delegation Errors in the app due to CountRows 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment]
Fixed with this basic pattern, where I make a collection just for countrows for 3 different counts: 
```
ClearCollect(JustForCount_SyncFlowErros, Filter('Sync Flow Errors','Sync Flow Errors (Views)'.'Active Sync Flow Errors'));
Patch(
    col_nav,
    LookUp(
        col_nav,
        Label = "Service Health"
    ),
    {Notifications: CountRows(JustForCount_SyncFlowErros)}
)
```

**Comment by Jenefer-Monroe** [comment]
there is one spot left here that this doesnt work which is in the onstartscreen pattern. need to investigate that separately. But the rest are fixed

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
