### ISSUE TITLE
[CoE Starter Kit - BUG] remove nagivation from onstart in Set App/Flow Permissions app

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1489]
### Describe the issue

Navigate(HomeScreen); in onstart caused it to not load data when booted in maker. would eventually cause it to not load data in player too, so fixed.  

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Set Flow Permissions

**Comment by Jenefer-Monroe** [comment]
local fixed Dec

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
