### ISSUE TITLE
[CoE Starter Kit - BUG] Product Caching issue causing failures in Command Center App > Initially Populate Bookmarks

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1490]
### Describe the issue

some apps get deleted but still returned in Get Apps as Admin. This was returning apps without logical names and causing this flow to fail here
![image](https://user-images.githubusercontent.com/89584709/142020387-38229b96-8161-432a-9a09-3a07d739d30e.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Command Center App > Initially Populate Bookmarks

**Comment by Jenefer-Monroe** [comment]
local fixed for December
![image](https://user-images.githubusercontent.com/89584709/142020555-d1af19bc-72d2-4da5-84b9-567243925a03.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
