### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - Command Center: cannot set current value for env vars that dont have one already

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1492]
### Describe the issue

If an env var has never had a current value, you cannot add one with the app. 

![image](https://user-images.githubusercontent.com/89584709/142031853-ee0e61d9-12c8-4cd1-87db-7bd4f372235a.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment]
fixed for Dec

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
