### ISSUE TITLE
[CoE Starter Kit] Add Tenant ID as a column to inventory tables

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1496]
### Describe the issue

Feature ask for customers that have multiple tenants they want to support - add Tenant ID to inventory tables (perhaps only environment is needed?), customers can then bring together tables from different tenants in one Power BI Dashboard (out of scope for CoE) and display info by tenant. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Power BI

### What app or flow are you having the issue with?

Power BI

**Comment by manuelap-msft** [comment]
@Jenefer-Monroe I spoke to Ravi and Phil internally and we discussed adding a tenant ID to the inventory to support customers with multi-tenant scenarios. Effort on our side should be just adding the tenant ID in - I'm not sure if this is info we get currently from the Admin connectors to populate? If not, we can leave it blank for now - it is available through BYO Datalake and we can populate it there and this can then be a pre-req for those scenarios. But if actions like List Environmemts somehow return the Tenant ID we can add it as well!

**Comment by Jenefer-Monroe** [comment]
local fixed for December

**Comment by Jenefer-Monroe** [comment]
1. added a TenantID field to Envt table 
1. fill this field from the main sync flow **_Admin | Sync Template v3_**

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
