### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Command Center - add search bar to env var page

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1509]
### Describe the issue

Hard to find the env variable you want to edit

### Expected Behavior

able to search them by name

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment]
local fixed for Dec

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
