### ISSUE TITLE
[ALM Accelerator - BUG]: “GetAppsAndFlows” is currently configured with Run-Only user 

### ISSUE THREAD

**Issue by MrHueb** [microsoft/coe-starter-kit#1512]
### Describe the issue

In the setup guide section Update the Webhook URL Value (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator#update-the-webhook-url-value), you should copy the URL from the WorkflowCompleteNotification Flow.
Issue: The instruction most likely refers to the **trigger** of the flow. Additionally, the flow does not show a URL as it can not be turned on / saved.
![Screenshot 2021-11-19 145214](https://user-images.githubusercontent.com/56923538/142633891-0296951a-8f44-4a95-a62e-789916e1a3bc.png)
![Screenshot 2021-11-19 145307](https://user-images.githubusercontent.com/56923538/142633895-a2eb23ec-8571-45f1-aaea-6b654d862ba2.png)
 

### Expected Behavior

The trigger should show a URL that can be used to update the admin app.
The user should be able to save the flow and create an URL.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20210521.1

### Steps To Reproduce

Import solution and follow setup guide https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator

Issue appears here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator#update-the-webhook-url-value

**Comment by mikefactorial** [comment]
Hi @MrHueb, thanks for reporting this. We're aware of the issue and actively working on a fix. I've notified the team member working on this to provide an update here.

**Comment by fooshen** [comment]
Thanks @MrHueb - we are working on this fix. For now, you can unblock this by changing the run-only permission for its child flow, GetAppsAndFlows. Change the connection for Power Apps for Makers from "Provided by run-only user" to "Use this connection (<your connection>)". You will then be able to get the URL generated for the webhook.

![image](https://user-images.githubusercontent.com/23041800/142781139-c9f724e5-0f37-4356-a7d7-3b03df14ee81.png)

**Comment by DanishIslam07** [comment]
I am still facing this issue. Please help.

**Comment by fooshen** [comment]
Hi @DanishIslam07 - once you have updated the Child Flow's (GetAppsAndFlows) Run-Only Permissions as described above - turn if off and then turn it back on again. Then head back to its parent flow "WorkflowCompleteNotification" and try to turn it on. Do update back if this works for you?

**Comment by DanishIslam07** [comment]
Thanks for your response.

First of all flow is already turned off. When I tried to turn it on after updating the run only permissions, i got below error-

<img width="1323" alt="Screenshot 2022-06-10 at 12 19 37 PM" src="https://user-images.githubusercontent.com/39618236/173034660-4e069fe7-ce0a-416e-93ae-d93b7870293e.png">

**Comment by fooshen** [comment]
Thank you for the update @DanishIslam07 - from the error provided, it might be due to other child flows that are used by "GetAppsAndFlows". Can you confirm if the following two flows are turned on - "ReadEnvironmentVariable" and "FetchLocalizedText"?

**Comment by DanishIslam07** [comment]
Thank you so much for your guidance. It worked.

Just want to add that like other components setup documentation, for ALM it is not mentioned which flows to be enabled first or in which order flows needs to be enabled.

**Comment by Bosch-PW** [comment]
Hi, I have turned on (GetAppsAndFlows , FetchLocalizedText , ReadEnvironmentVariable) yet I get similar error when I turn on WorkflowCompleteNotification flow. please see error below.

"Flow client error returned with status code "BadRequest" and details "{"error":{"code":"MultipleErrorsOccurred","message":"Multiple errors occurred: 'BadRequest,BadRequest,BadRequest'. Please see details.","details":[{"code":"ChildFlowNeverPublished","message":"The workflow with id '05dc414d-78eb-ea11-a817-000d3a56b702' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."},{"code":"ChildFlowNeverPublished","message":"The workflow with id '4528dfaf-782e-eb11-a813-000d3a33febe' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."},{"code":"ChildFlowNeverPublished","message":"The workflow with id 'b4ea7f57-d0ee-ea11-a817-000d3a1abe26' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}]}}". "

Thanks

**Comment by fooshen** [comment]
Hi @Bosch-PW, there are several other child flows that are used by WorkflowCompleteNotification flow.  Can you check and see which Child Flow(s) in your imported solution that is not turned on? You should expect all Cloud Flows to be turned on. Specifically for WorkflowCompleteNotification flow, you will also need: GetSolution, SendEmailNotification and LogTelemetry in addition to GetAppsAndFlows, FetchLocalizedText and ReadEnvironmentVariable.

Let us know how it goes.

**Comment by Bosch-PW** [comment]
Thanks for your support, it worked.

**Comment by mikefactorial** [comment]
Awesome! Closing this out. Thnks @fooshen! for supporting this and thanks @Bosch-PW for following up!
