### ISSUE TITLE
[CoE Starter Kit - BUG] Objects made by Service Principles show as Orphaned (except canvas apps/cloud flows)

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1515]
### Describe the issue

Previously we were only checking for maker type Service Principle for 2 object types (Canvas Apps and Cloud Flows)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

sync flows

**Comment by Jenefer-Monroe** [comment]
Local fixed in Dec to have a helper flow for orphan check, this allowed us to scale to this work being applied to all object types now.

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by Jenefer-Monroe** [comment]
Hello, no Service Principles should not show up as orphaned. 

Please be sure you are running the **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** in Core
And old objects, owned by Service Principle will only be fixed up if they go through inventory so you will need to do a [Full Inventory](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory)
