### ISSUE TITLE
[CoE Starter Kit - BUG] No easy way to delete an approval to delete flow/app

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1517]
### Describe the issue

some gets the archival approval mail
they approve the delete
they change their mind.

--> No easy way for admin to remove this approval, they have to go into the table itself

### Expected Behavior

Added this button to the admin app for this. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.8

### What app or flow are you having the issue with?

App and Flow Archive and Clean Up

**Comment by Jenefer-Monroe** [comment]
local fixed Dec

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
