### ISSUE TITLE
[CoE Starter Kit] 12/17 - Test App Registration scope for Audit Log custom connector

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1519]
a communication has been published recently about the Office management service health API deprecation on 17 December and being replaced by Graph API 
https://m365log.com/apps-365/service-communications-api-retirement/

This API is added into the permissions scope in App registration while configuring the custom connector according to the starter kit documentation.

I'm not sure if the scope is really needed to get the audit logs activity, but let's run a test to see what the impact is.

**Comment by Jenefer-Monroe** [comment]
It does work with this permission removed. YEAH!

Manuela to update the documentation. 
Jenefer to test and make sure existing installs still work after the product change on 12/17

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
