### ISSUE TITLE
[ALM Accelerator - BUG]: Deploy project to test step attempts to create a new environment

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1521]
### Describe the issue

When the user selects Deploy to test in the ALM for makers application, the Cloud flows attempt to create a new environment yet part of the ALM setup is to define the Test and Production environments in the ALM Accelerator Admin Configuration

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

**Comment by mikefactorial** [comment]
@medicineshow looks like this got lost in the shuffle during the holidays last year. The reason behind this is that the app creates a temporary build environment to validate the solution prior to pushing to test. This is similar to the validation environment that the ALM Accelerator for Power Platform uses except it's provisioned just in time and is used as a check to ensure the solution can be packaged and deployed successfully.

You can see the steps in the Deploy to Stage flow under "Check if Deploying to Test" 
![image](https://user-images.githubusercontent.com/42348035/153431070-b71d0e64-bad6-4154-b1dc-cc6950b6d12d.png)

Closing this out for now since there's no more action to be taken and there hasn't been any updates in a while. Feel free to open a new issue if you have any additional questions.
