### ISSUE TITLE
[BUG]: "All Environments" not available in Cloud Flows Page of the PowerBI Report

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#1529]
**Describe the bug**
The option to select "all environments" in the Cloud Flows Report

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 3.18
 - App or Flow None - teh data is there - I have checked

**To Reproduce**
1. Load PowerBi Report
2. Select Cloud Flows
3. Look at Environment filter

**Expected behavior**
A clear and concise description of what you expected to happen**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

I don't think your screenshots have come through. I'm not sure I understand - all environments are selected by Default, e.g. the page/report shows all environments to begin with and you can drill down into a single environment with the filter? Can you help me understand what the issue is?

Thank you
Manuela

**Comment by NPrice99** [comment]
![CoELAckofenvironments](https://user-images.githubusercontent.com/8484048/143086117-e4a73508-6dbb-4b43-9ad7-2527a4ea2f46.PNG)


See "Environment" filter does not have "All Environments" as a option

**Comment by manuelap-msft** [comment]
That's expected behaviour. It will only list available environments, and unselecting them all will show all environments.

If you select one:
![image](https://user-images.githubusercontent.com/55705669/143087454-ec7f4768-f239-4105-8fdc-e7d66b915e22.png)

If you unselect all:
![image](https://user-images.githubusercontent.com/55705669/143087481-548d4d6d-64e2-4ed3-b6c8-b47370378dd3.png)

If you don't see the all option, you may have a filter set at page level through Power BI Desktop, through Filters on this page
![image](https://user-images.githubusercontent.com/55705669/143087552-74538f0c-ee49-4ff8-9b03-899948735412.png)
