### ISSUE TITLE
[CoE Starter Kit - BUG] Parse JSON OrphanedFlows step fails for flows that were never inventoried

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1535]
### Describe the issue

if a flow shows up in this flow that was never inventoried, it has some nulls that the current parse cannot hanlde. 

### Expected Behavior

change EnvtDisplayName type from String to String or Null

            "EnvtDisplayName": {
                "type": [
                    "string",
                    "null"
                ]

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.8

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

**Comment by Jenefer-Monroe** [comment]
local fixed Dec

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
