### ISSUE TITLE
[CoE Starter Kit - BUG] Portals Inventory - please show some details about permissions

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1545]
### Describe the issue

Table permissions enabled in entity lists, basic forms, and advanced form steps
Authentication types for the basic auth types.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Portals)

**Comment by Jenefer-Monroe** [comment]
local fixed for January.
![image](https://user-images.githubusercontent.com/89584709/143947827-b7640edd-896f-46aa-a0fb-a6bcc4193468.png)
![image](https://user-images.githubusercontent.com/89584709/143947892-2ab30aff-2dfe-4261-8c45-28f11d4a3c6f.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
