### ISSUE TITLE
On more of the BI report pages a filter by Environment and env Type.

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#1546]
There are lots of pages that filter by environment, but some that do not,  I know I could easily add them, and again on the next upgrade.

Take the flow licence Assessment page,  and app,  There are dynamics envs that consist of dynamics licence users, so are covered under that licence,  Filtering by env allows me to narrow down the premium licences.

There are differences between Citizen Dev envs and Pro Dev by environment, I need to analyse differently.  So especially on these pages a few more filters would be good.

**Comment by manuelap-msft** [comment]
Hello! Thanks for the feedback - added this to our backlog, and I'm hopeful we'll be able to fit this into our January release!

**Comment by manuelap-msft** [comment]
Hello,

I just went through all the pages of the BI and added the environment filter to all pages that were missing it. This will go live with the January release now!
![image](https://user-images.githubusercontent.com/55705669/146547749-8f331d85-1b8b-4662-bdbd-d55219bf11ac.png)

**Comment by mikefactorial** [comment]
@binaryjam This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
