### ISSUE TITLE
[CoE Starter Kit - Question] Archive and Clean Up v2 - Why only canvas apps

### ISSUE THREAD

**Issue by renaudarmstrongvictrix** [microsoft/coe-starter-kit#1560]
### Describe the issue

Hi,

We are implementing the Archive and Clean Up Process and all the components related to it. 

I was curious to know why the _Archive and Clean Up v2 (Start Approval for Apps)_ filters out the Model Driven Apps and SharepointForm Apps. 

Would it cause any problem if we would change the filter in the initial List.. (Dataverse) to include all app types ?

![image](https://user-images.githubusercontent.com/91679305/144315253-123d9344-83f8-47ca-b5dd-2ac310e9e942.png)

Thanks 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Apps)

### Steps To Reproduce

-

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for reaching out with such a well researched question. 
We exclude SP and MDA because we cannot do the same management activities to them. If you allow them to be included the risk would be that they would fail later to be deleted. I know for sure this will fail for MDAs. 
Although I havent tested this in a while. If you end up testing this and find that it works for you, please let us know.

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for toolkit team
