### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View - Environments resources show discrepancy

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1576]
### Describe the issue

In the Power Platform Admin View, the calculated field for number of apps / flows does not match the number of apps / flows brought in via the table. Possibly an issue with different filters on these numbers.

![image](https://user-images.githubusercontent.com/55705669/145081859-b090e4d9-2058-4e06-a749-4db1cca4dbbb.png)

### Expected Behavior

Numbers match

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/146795588-90593e55-954b-42bb-9802-d5be3e21c128.png)

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
