### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 is running since 3 hours

### ISSUE THREAD

**Issue by UrvishGT** [microsoft/coe-starter-kit#1578]
### Describe the issue

Hi,

I am trying to setup the CoE core component and looks like the Admin Sync flow is stuck since 3 hours.
Please find below screenshot for that.
![image](https://user-images.githubusercontent.com/94638525/145097393-283b70d0-ae0e-490b-8d0d-8eb6b48d04e2.png)

Is this the expected behaviour or something else?

I am using CenterofExcellenceCoreComponents_3_19_managed.zip.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by UrvishGT** [comment]
I found something with the issue.

Its causing this delay because of the Environment variable "DelayInventory".

Core components internally set this variable and its default value is Yes.

While installing it does not give option to change the value of it.

Any one faced this issue?

**Comment by manuelap-msft** [comment]
Hello,

this is expected behaviour. We have multiple thousand customers using the CoE Starter Kit and running the Admin | Sync Template flow on a schedule at the same time for all customers caused a high load on Dataverse. Unfortunately the schedule trigger in flow doesn't support using dynamic values, e.g. setting the scheduled time to a value within the timezone of the customer. We therefore introduced a random delay so the flow starts at the same time for all customers and then waits a random time between 0-12 hrs before starting the action. This is to balance out the load on our service.

Thank you
Manuela

**Comment by UrvishGT** [comment]
Thanks for the update Manuela.

I started that flow to run again and will see after 12 hours what it does.

One thing I do not get it though is, when you say all the customer's flow schedule on the same time and that is causing high load on Dataverse.
could you please tell me more about it? As it sounds like this flow is talking to some remote thing on your side or something else?

**Comment by manuelap-msft** [comment]
Well, Dataverse is a cloud service hosted in Microsoft data centers, so it's a service we maintain. It's not something that is run on your server or your infrastructure, but on Microsofts data centers.
