### ISSUE TITLE
[ALM Accelerator - BUG]: Doesn't support connection references and environment variables

### ISSUE THREAD

**Issue by diego-coke** [microsoft/coe-starter-kit#1579]
### Describe the issue

Using the ALM Accelerator for Makers once I request to move the solution from dev to test on the UI everything looks good they are no errors, but when you play the app on the new environment it sends errors, and looks like the connection are not being migrated correctly in my case for a Power automate flow that uses outlook connector.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

 1.0.20210521.1

**Comment by devkeydet** [comment]
GitHub actions for Power Platform do not yet offer the ability to set connection references and environment variables.  The Azure DevOps tasks (aka Power Platform Build Tools) do:
https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools
When GitHub Actions for Power Platform have equivalent capability, you can use the same approach to update your yml files to use this capability.

**Comment by diego-coke** [comment]
Just to see if I'm understanding right, we can't move the connections inside apps or flows with the current release of ALM Accelerator for Makers. Am I right?

**Comment by devkeydet** [comment]
Once GitHub Action for solution import supports connection references and environment variables, you could follow similar instructions in the link above, modify your yml in the repo, and add the capability to set connection references and environment variables to the starter yml files the accelerator deploys.  We will not be releasing updated the starter yml files in the Accelerator for Makers because we are working to consolidate the two accelerators into one.  When we do that, the yml files in the unified accelerator will have this capability built in.  The current ALM Accelerator for Makers is being de-invested in favor of a unified accelerator that attempts to bring the experiences and capabilities of both into one.  We will continue to fix bugs for the ALM Accelerator for Makers, but we will not be enhancing it.  We are planning to update our documentation to reflect this soon.  I don't have exact dates because the docs are going through editorial review.

**Comment by devkeydet** [comment]
The 0.5.0 release of GitHub Actions for Power Platform now exposes the deployment-settings-file input in the import-solution action:
https://github.com/microsoft/powerplatform-actions/blob/0.5.0/import-solution/action.yml

As of writing this post, docs have not yet been updated, but you can use either of these tags to reference the latest release: 
![image](https://user-images.githubusercontent.com/4499296/146273095-642a158c-b20b-49b1-ac14-3970d3608b4c.png)

They are all aliases for https://github.com/microsoft/powerplatform-actions/releases/tag/0.5.0

**Comment by devkeydet** [comment]
@diego-coke - I wanted to provide some further explanation.  I had to go back and review the code of the ALM Accelerator for Makers (AA4M) and now realize my point about updating the yml files might be confusing.  Every time AA4M provisions a new repo, it does so using what GitHub calls a template repository.
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

When you install AA4AM, the template repo used is configurable through an Environment Variable.
![image](https://user-images.githubusercontent.com/4499296/146459218-0d447e6b-ac08-46f9-a010-4592949b18de.png)

By default, the Environment Variable is set to point to this publicly available template repo.
https://github.com/poweralm/repotemplate

What you would need to do is:
1. Create a new repo of your own using the template repo above.
2. Update the yml files in the template repo to conditionally use the new **deployment-settings-file** input that's now part of the **import-solution** action.  You would write conditional logic that would use a deploymentSettings.json file for an environment if one existed (not every solution needs one).
3. Convert the new repo into a template repo.
4. Update the Environment Variable to point to **your** template repo.
5. Now, every new repo that gets created will have support for using a deploymentSettings.json file based on your enhancements to the yml files.

For existing repos, you **would** need to update all the yml files.  At the time of building AA4M, GitHub did not have a way to reuse workflows.  Therefore, template repos were the only option.

To generate deploymentSettings.json files specific to your test and production environments, you would need to follow these instructions (minus the Azure DevOps part [Step 4] since you are using GitHub Actions).
https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools

**Comment by mikefactorial** [comment]
@diego-coke and @devkeydet Closing this since there's nothing more to be done for this issue. Feel free to open a new issue if you need further assistance.
