### ISSUE TITLE
[CoE Starter Kit] Maker Command Center - add filter and search capability to Learn and Blog page

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1583]
- On Learn page, add filter by certification / learning path / documentation / other
- On Blog page, add filter by product

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/146384555-a8c5edd1-7e49-4a77-a9ab-56d75305a7c7.png)

Blog page filter by product and search added

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
