### ISSUE TITLE
[CoE Starter Kit] Admin Command Center - add filter and search capability to Learn, Blog, Message Center and Release Notes page

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1584]
On Learn page, add filter by certification / learning path / documentation / other and/or search bar
On Blog page, add filter by product and/or search bar
On Message Center page, add filter by product and/or search bar
On Release Notes page, add filter by product and/or search bar

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/146387688-d66b8c56-e098-419c-87da-eea30cfbbf59.png)
 Learn page done

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/146387906-9abd4540-4231-4c44-9eeb-077560e49d14.png)

Blog page done

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/146389148-426a5bcc-648f-4e5c-bf53-3a80dd36812c.png)

Release Wave notes done

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/146391081-b0c36b5f-240d-42b3-87be-c68a96c240e5.png)

Message Center done

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
