### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Check Deleted) can't assign per flow passes

### ISSUE THREAD

**Issue by pallvip** [microsoft/coe-starter-kit#1586]
### Describe the issue

I am installing the COE starter kit and it won't let me assign the flow pass. and comes up with error -  "Cannot set plan for unpublished solution flow". I have not made any changes to flow, and have already done "Publish all customisations" from Solutions page 
![image](https://user-images.githubusercontent.com/40602120/145245715-24e4f92a-21ae-4787-8681-ad36ef30ee7d.png)
![image](https://user-images.githubusercontent.com/40602120/145245765-b5d56442-f73e-45e7-8d0e-efa824471ed4.png)
![image](https://user-images.githubusercontent.com/40602120/145249088-7fa850e3-292e-42a0-8c47-07492e729f6c.png)

The only thing which I havent filled is these 3 environment variables -
![image](https://user-images.githubusercontent.com/40602120/145249186-6ca5e0e4-5da8-405b-9d7e-c9326fc204b9.png)

### Expected Behavior

I would expect to be able to assign flow pass to the flow so it can just run 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment]
I think you need the flow to be turned on in order to assign a license to it, but I'm not certain.

And from the first error message, it seems you don't have the correct user license type in order to turn on that flow. 
You will need to have a non-trial per-user flow license to turn on the flow 

Below is our general note on pagination:

**_Pagination_**
Hello. All the flows have this pagination policy. It indicates that you are using an insufficient or trial license. 
Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes. 

See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles) 
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits) 
And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).

**Comment by pallvip** [comment]
I have 5 per flow passes assigned to the environment and when I try to assign a per flow pass to the flow I get this error 
![image](https://user-images.githubusercontent.com/40602120/145370926-64cd3ec4-e423-4c01-a924-3c8c1159c241.png)

**Comment by Jenefer-Monroe** [comment]
There seems to be a chicken and egg situation here and we have given that feedback to the product team.
You need to have the flow turned on in order to assign the flow. Please turn on the flow. 
In order to turn on the flow you need a per-user license that is not a trial.

**Comment by manuelap-msft** [comment]
Closing out as no further action required from the CoE Starter Kit team. If we hear back from the Product Team on this feedback, we'll update you here.
