### ISSUE TITLE
[CoE Starter Kit] Year on Year growth data on creation date

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1590]
I've been asked to provide year over year growth percentage for creation of apps, flows, environments, chatbots, also no. of makers, etc. Is this something that COE can provide?

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/146562934-b53a7c18-2c67-4683-afe2-f2cb7c8167ed.png)

Done for January

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
