### ISSUE TITLE
[CoE Starter Kit] Add a reminder in weekly clean-up flows before delete the Teams Environment

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1593]
Add a reminder in weekly clean-up flows before delete the Teams Environment

**Comment by Jenefer-Monroe** [comment]
tracking for Jan

**Comment by Jenefer-Monroe** [comment]
![image](https://user-images.githubusercontent.com/89584709/147570959-50cb142e-4de9-4f9a-833b-e0f24bfaa8c6.png)

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
