### ISSUE TITLE
[CoE Starter Kit] Add information about CoE Starter Kit release to Command Center

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1595]
Add a reminder to upgrade / prompt to upgrade to the command center showing current version vs what they are on

**Comment by manuelap-msft** [comment]
We will use this GitHub feed https://github.com/microsoft/coe-starter-kit/releases.atom to bring information about the latest release to the Command Center.

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/146801607-bfa7524e-8512-40c4-8f13-2518faf7d44c.png)

**Comment by manuelap-msft** [comment]
The app will check what version you are on at the moment and compare it to the latest release. If your install is more than 3 months old, you will receive a prompt to upgrade.

![image](https://user-images.githubusercontent.com/55705669/146808334-1925db85-343a-4b01-bc85-3521765eb28b.png)

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
