### ISSUE TITLE
[CoE Starter Kit - BUG] Governance - add flow to auto-excuse Support type environments from Governance flows

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1598]
### Describe the issue

Support environments are copies of environments. We do not want to have the governance flows run on them lest people get pinged about copies of their work, rather than their actual work. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Governance flows

**Comment by Jenefer-Monroe** [comment]
local fixed for January
![image](https://user-images.githubusercontent.com/89584709/145627218-30eed741-ce50-4d79-8d64-f297dd37df04.png)
![image](https://user-images.githubusercontent.com/89584709/145627280-aa767ed7-c77e-4806-ace5-ed32d4290f18.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
