### ISSUE TITLE
[CoE Starter Kit - Idea] Derive concept of complete inventory

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#1602]
Hi, 
do you see feasible that when the set of "Admin | Sync Template flows" had finished in their daily execution exists other flow to refresh the Power BI CoE Dashboard?
Thanks.

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately, we do not have a way to know when all the flows for all the environments have finished. This is due to the way we set up the triggers and the lack of access to flow run telemetry from within the kit. 
As a result we have no "inventory is complete" concept. 
Please let me know if that is what you were asking. 
Thanks

**Comment by albertocaa1317** [comment]
It would possible that each flow necessary to have the complete refreshed data in de pbi dashboard enable a flag when finished, for example, change a Boolean field to True in a Control Table in Dataverse and when all flows had enabled their flags a flow automated runs to refresh the dataset?
Yes, I know it, maybe it's a crazy idea 😜

**Comment by Jenefer-Monroe** [comment]
I suppose that would be somewhat possible. We can put this on our backlog but I don't expect it to pop to high priority soon as today our reports arent intended to be real time. Please let us know if you figure something out though to share!

**Comment by albertocaa1317** [comment]
Sure! I go to try it in a lab environment. I hope to get this crazy idea in a real idea :)

**Comment by manuelap-msft** [comment]
Closing out as we are not able to invest in this.
