### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by xavieralonso** [microsoft/coe-starter-kit#1605]
### Describe the issue

I'm only see 9 environments and we have 27 environments created.

### Expected Behavior

To See in the BI dashboard the information related to the hided environments. Apps, connectors and so on.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.8

### What app or flow are you having the issue with?

Power Bi associated to CoE.

### Steps To Reproduce

1. Open Environments report of CenterOfExcellenceBi.pbix

**Comment by Jenefer-Monroe** [comment]
Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role? You need this role in order to see all objects in the tenant. Without it you only see the environments and objects to which you have access. 

Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf) 

Please see our [pre-reqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites) for this and the other requirements needed to successfully run the starter kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
