### ISSUE TITLE
[CoE Starter Kit - BUG] Button "Launch Maker Portal" in app "Access this flows" launches incorrect url

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#1620]
### Describe the issue

Hi,
in the app "Admin - Access this flows" of Core solution, the button "Launch Maker Portal" launch a incorrect url:
_https://emea.flow.microsoft.com/manage/environments/manage/environments/XXX/flows/XXX/details_

This ocurrs because the environment variable "Power Automate environment variable" already contains "manage/environments/"

![image](https://user-images.githubusercontent.com/57954993/145980028-f088d081-3ac0-49b4-98cd-7fc590e22bb4.png)
![image](https://user-images.githubusercontent.com/57954993/145980036-7276ccda-0439-49f7-99d3-7a401e10c431.png)

### Expected Behavior

This the correct url:
https://emea.flow.microsoft.com/manage/environments/XXX/flows/XXX/details

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin - Access this flow

**Comment by Jenefer-Monroe** [comment]
Thanks for posting! Local fixed for January.

**Comment by mikefactorial** [comment]
@albertocaa1317 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
