### ISSUE TITLE
[CoE Starter Kit] Modify Developer Compliance Center to new look and feel (of Environment Request app)

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1623]
Update Developer Compliance Center app to have the same look and feel as our newer apps like the Admin Command Center and Environment Request app.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
