### ISSUE TITLE
[CoE Starter Kit - BUG] PVA failures in Check Deleted

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1633]
### Describe the issue

This conditional was somehow were removed from this action. 
![image](https://user-images.githubusercontent.com/89584709/146203435-7bdc229a-9bd2-4a8a-9cdd-eb046efd4e08.png)

### Expected Behavior

Conditionals in place

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment]
local fixed Jan

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
