### ISSUE TITLE
[CoE Starter Kit - BUG] Remove error from Command Center when M365 app registration not created

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1635]
### Describe the issue

Today if the person does not (or cannot) set up the app registration for the M36 messages, they will get an error every time they use the command center. 

### Expected Behavior

Update the flow and app to not throw that error if the person doesn’t (or can't) set up app registration. 

If we add a catch on the List and then returned “404 – not setup up” or something for that case
 
![image](https://user-images.githubusercontent.com/89584709/146216551-1df5b9d9-f831-4797-9639-115f537c65d8.png)

Then in the app when they browse to this page, we could show something like “not configured” or something. 
 
![image](https://user-images.githubusercontent.com/89584709/146216597-45506d00-9270-492e-a1bf-3236d9c9bd62.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment]
Local fixed Jan. Actual fix ended up being:

![image](https://user-images.githubusercontent.com/89584709/146235806-049c54cc-d259-418f-9549-00f61f1fc966.png)

![image](https://user-images.githubusercontent.com/89584709/146235875-d4b1d4e5-fa9f-4195-9606-d6aa86b24a16.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
