### ISSUE TITLE
Power Platform Admin View app missing 'Admin Requirement - Reviewed Flow' field

### ISSUE THREAD

**Issue by WilliamJYoung** [microsoft/coe-starter-kit#1638]
The field 'Admin Requirement - Reviewed Flow' has been removed from the Flows Audit page
Can this be restored, so that we can amend the record values?

**Comment by manuelap-msft** [comment]
Hello,

thank you for letting us know - you're right, that field dropped of the form when we shuffled some fields around. 

I have restored it now in our dev version and it would roll out with the January release in a few weeks, is that okay or do you need it sooner? If so, I can talk you through how to change the form to add it yourself! 
![image](https://user-images.githubusercontent.com/55705669/146375142-b7cc408f-5419-4b50-9ad6-b76ea89bc79b.png)

**Comment by WilliamJYoung** [comment]
Thanks again for the quick reply Manuela
I think this can likely wait as we have a workaround
Thanks and have a great Christmas!

**Comment by mikefactorial** [comment]
@WilliamJYoung This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by WilliamJYoung** [comment]
@mikefactorial that's great. Thanks again for the quick response!
