### ISSUE TITLE
[CoE Starter Kit - BUG] Various Cloud Flows with Pagination Threshold SET TO HIGH

### ISSUE THREAD

**Issue by Rene-** [microsoft/coe-starter-kit#1642]
### Describe the issue

I am in the middle of turning on the cloud flows from the core package, but I am running into issues with actions having their pagination threshold set to 10,000 versus the allowed limit of 5000. 

### Expected Behavior

Flows turning on

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin - Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Hello. All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).

**Comment by Rene-** [comment]
I mistakenly thought my test tenant user account had the pro plan 2 license - it was set to free. 

I have gone through all the flows and reduced the pagination threshold to test the core components. Will I run into any other issues using the free version of the license?

**Comment by Jenefer-Monroe** [comment]
If you have a larger tenant, you may not fetch all of the data (as it may be on later pages). 
And of course you will not be able to upgrade without removing all these unmanaged layers and re-changing. 
So we do not recommend this path.
