### ISSUE TITLE
[ALM Accelerator - BUG]: ALM Accelerator Admin Configuration Canvas App Update Button

### ISSUE THREAD

**Issue by alzia-msft** [microsoft/coe-starter-kit#1646]
### Describe the issue

Whenever I select the "Update" button I notice I get an "Unexpected Error". It appears this happens when I select the Client ID and GITHUB ORG NAME button the first time.

### Expected Behavior

There should be no error when selecting the update button, maybe a notification that tells the user that his/her actions were successfully updated would be a nice to have? 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

### Steps To Reproduce

1. Open ALM Accelerator Admin Configuration App
2. Update Client ID or GITHUB ORG NAME selection first time makes you see an unknown error

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/92477952/146589355-ef208318-175a-4633-a616-54e705dc997b.png">

**Comment by mikefactorial** [comment]
@alzia-msf can you verify if the changes are saved by closing and reopening the app? I'll add this to the backlog to investigate, but the error message should be innocuous as long as the values are saved.

**Comment by mikefactorial** [comment]
@alzia-msf Just a heads up the ALM Accelerator for Makers isn't going to be getting a lot of support going forward. You may have noticed that it hasn't been updated in almost a year. The reason is that we're focusing on the ALM Accelerator for Power Platform (formerly the ALM Accelerator for Advanced Makers). The ALM Accelerator for Power Platform will unify the experiences and support for Azure DevOps and GitHub and include more robust functionality than the ALM Accelerator for Makers does in its current state. Would like to get your feedback on the project / client you're planning to use AA4M with and see if AA4PP would be a better fit.

A couple of things to consider: 
1. Is the client / project tied specifically to GitHub or is using Azure DevOps an option? If so, AA4PP is a better choice. GitHub support is in the works for AA4PP as well.
2. Currently, AA4M doesn't support connection connection references, setting environment variables among other things in downstream environments which is a big limitation. AA4PP does handle these more complex Power Platform scenarios.

**Comment by mikefactorial** [comment]
That being said AA4M will remain as a reference or sample app in the CoE Starter Kit we're just not investing development efforts in AA4M in favor of the unified Accelerator. The unmanaged solution is shipped with the CoE Starter Kit and can be extended and the source code is available as well.

**Comment by mikefactorial** [comment]
Closing this since there's nothing more to be done for this issue. Feel free to open a new issue if you need further assistance.
