### ISSUE TITLE
[CoE Starter Kit] Power BI for Dataverse for Teams - Add Environment Capacity

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1651]
Add Environment Capacity page to Dataverse for Teams Power BI Dashboard

![image](https://user-images.githubusercontent.com/55705669/146768823-31f3fbba-df17-411f-987e-72929138070d.png)

**Comment by manuelap-msft** [comment]
New dashboards uploaded and will be shipped with January release:
You can try this one: https://github.com/microsoft/coe-starter-kit/raw/coe-january/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
