### ISSUE TITLE
[CoE Starter Kit] Update Power BI - 1. dedicated to Production envs | 2. dedicated to Dataverse for Teams environments

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1652]
We currently ship two Power BI dashboards:
- one using the Common Data Service (Legacy) connector in Power BI 
- one using the Dataverse connector in Power BI 

These have different limitations: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use

Due to inherent differences between Production and Dataverse for Teams environments (system columns being different etc), we are now changing the Power BI Dashboards that we offer:

1) Power BI dashboard for use with Production environments (if your CoE is installed in a Prod environment) - called Production_CoEdashboard_MMMYY.pbit (release month/year)
2) Power BI Dashboard for use with Dataverse for Teams environments (if your CoE is installed in a Teams environment) - - called Teams_CoEdashboard_MMMYY.pbit (release month/year)

**Comment by manuelap-msft** [comment]
New dashboards uploaded and will be shipped with January release:
You can try this one: https://github.com/microsoft/coe-starter-kit/raw/coe-january/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
