### ISSUE TITLE
[CoE Starter Kit - DOCUMENTATION] rewrite setup docs for core and gov to be area oriented

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1656]
### Describe the issue

We are up to ~45 flows in Core and its overwhelming. Need a way to have setup focus on areas. 

### Expected Behavior

Have (as examples) setup inventory, setup compliance, setup env requests, etc. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

documentation

**Comment by Jenefer-Monroe** [comment]
local fixed Jan

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
