### ISSUE TITLE
[CoE Starter Kit - BUG] D4T: Need way to exempt apps and flows from archival flows

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1657]
### Describe the issue

We have a way to exempt Apps and Flows from Archival in the Model Driven App for regular Core but forgot to add to the canvas version in Core for Teams

### Expected Behavior

A way to do this exemption in the canvas version of Power Platform Admin View

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
![image](https://user-images.githubusercontent.com/89584709/146840518-5fdf9e35-3843-4b3a-90e8-5a0de55bf0d2.png)

local fixed Jan

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
