### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned Environment Display Name being set incorrectly

### ISSUE THREAD

**Issue by A-Demir-ilx** [microsoft/coe-starter-kit#1658]
### Describe the issue

Hello,

In some of our environment in the Admin view app we are missing the display name. The URL and the other details are updated correctly, we are only missing the display names for some specific Dynamics 365 environments. 
![image](https://user-images.githubusercontent.com/96475793/146923067-73248df9-501c-4f23-a818-ecb598fd765e.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.60

### What app or flow are you having the issue with?

Admin - Sync template v3

**Comment by Jenefer-Monroe** [comment]
Hello, I've never seen this happen before. 
Note that we expose what we get back from the connector. 

Can you please browse to the [PP Admin pages](https://admin.powerplatform.microsoft.com/environments) and see of they show with a display name there?

**Comment by A-Demir-ilx** [comment]
Hi @Jenefer-Monroe , Yes, I can see the environment names in the admin center and also in the output from the Admin Sync template v3 flow. However in the Admin view app I can't see some of the display names.

**Comment by Jenefer-Monroe** [comment]
Can you clarify what you mean here: _and also in the output from the Admin Sync template v3 flow_

Can you please open the **_Admin | Sync Template v3_** flow and go to the latest run. 
You can find your repro environments by looking for them in the output in some json parser which will tell you which value they are in, then go to that iteration in the apply to each environment
![image](https://user-images.githubusercontent.com/89584709/146936905-a6cb3ddf-ee4d-4744-bc34-65b7193ffd73.png)

Please let me know what path they went down in this part of the flow, so that I know if the value got written correctly

**Comment by A-Demir-ilx** [comment]
Hi Jenefer, See image below. I can see in the output of the 'Get environment' the right display names, however in the update step I can't see the name.

![image](https://user-images.githubusercontent.com/96475793/146942830-4086dd2c-5c3f-4a64-b885-1448e334f75f.png)

**Comment by Jenefer-Monroe** [comment]
Can you please hit Edit on this flow, and let me know what you see there? I think this may be a bug that I noticed and fixed separately already this month, so you will likely see something else here

![image](https://user-images.githubusercontent.com/89584709/146943628-cc5610dc-d0f7-406a-b0dd-a9c9f35e584e.png)

**Comment by A-Demir-ilx** [comment]
Hi @Jenefer-Monroe ,
See attached screenshot. I have also tried to map again the column and update the flow.
@{items('Apply_to_each_Environment')?['properties/displayName']}

![image](https://user-images.githubusercontent.com/96475793/146945438-f94b1ddb-a14e-4d5e-b6c6-69e4dbc889f2.png)

**Comment by Jenefer-Monroe** [comment]
thats a different action. See the titles? The bug was only in the update side
![image](https://user-images.githubusercontent.com/89584709/146945798-5f5b0888-3ff9-4a7e-af23-7da086899038.png)

**Comment by A-Demir-ilx** [comment]
@Jenefer-Monroe , See attached. If I remap this to the right value then it should fixed?

![image](https://user-images.githubusercontent.com/96475793/146946028-56f91ef8-e620-41ca-ade1-83c1adb88b02.png)

**Comment by Jenefer-Monroe** [comment]
thanks for confirming and being so helpful in debug! This is local fixed then already for January.

**Comment by Jenefer-Monroe** [comment]
and correct, if you paste that in you will be good. But then you will have created an unmanaged layer that will need removed when you upgrade

**Comment by A-Demir-ilx** [comment]
Thanks, I have temporary changed the mapping and before the January update I will remove the unmanaged layers.

**Comment by Jenefer-Monroe** [comment]
So glad you are unblocked. I will re-open so that we can track the fix for January.

**Comment by mikefactorial** [comment]
@A-Demir-ilx This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
