### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Flow Errors - include the CoE envt name

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1661]
### Describe the issue

Because people can have multiple CoEs installed (ex Dev, Test, Prod), and yet they need sync flow errors in each of these as they are deving and testing, it becomes difficult to know which envt is sending the failures. 

### Expected Behavior

Show the CoE envt in the email name

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Sync Flow Errors)

**Comment by Jenefer-Monroe** [comment]
Local fixed Jan
![image](https://user-images.githubusercontent.com/89584709/146972086-ec269f79-7d82-4a8a-983d-1eae2149f896.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
