### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by Nrabadia** [microsoft/coe-starter-kit#1669]
### Describe the issue

Trying to Install the CoE toolkit, got the step Activate the flows step 4, and it wont turn on the flow. error is "Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Connectors' of type 'OpenApiConnection' at line '1' and column '6339' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

### Expected Behavior

Should be able to turn on flow and move to the next one

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin Sync Template v3

### Steps To Reproduce

1. Create an environment
2. Import the CoE components
3. configure the variables
4. configure the helper and clean up components
5. turn these on

### Anything else?

same issue trying to do the same with-in MS Teams

**Comment by Jenefer-Monroe** [comment]
Hello. All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by JadhavKalpana** [comment]
While setting up the configuration of CoE Strater Kit Core component.
I'm getting below error-
Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Connectors' of type 'OpenApiConnection' at line '1' and column '6382' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".
 Kindly Help or suggest
<img width="733" alt="issue" src="https://user-images.githubusercontent.com/97939667/149898575-17faa6c3-8f06-4061-a42e-edd87eb11029.PNG">
