### ISSUE TITLE
[CoE Starter Kit] Add a forms.office.com template to copy from vs asking customers to create their own

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1670]
For the Power Platform Training Feedback, create a forms.office.com form and share the link to duplicate the form so customers don't have to create their own from scratch.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
