### ISSUE TITLE
[CoE Starter Kit - BUG] Perf Improvement - add concurrency to the loop in CLEANUP - Admin | Sync Template v3 (Delete Bad Data)

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1672]
### Describe the issue

Forgot to add concurrency here

### Expected Behavior

In particular, we do leave behind connection references so this one will get called periodically and might be large. 
Dont expect this to be super impactful but might as well fix it up while we are doing this scrub looking for spots we missed wrt concurrency. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Delete Bad Data)

**Comment by Jenefer-Monroe** [comment]
local fixed Jan

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
