### ISSUE TITLE
[CoE Starter Kit - BUG] Perf Improvement - add concurrency to the loop in CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1673]
### Describe the issue

Had it for the main loop (looping makers) but not for the objects when a new orphan is found

### Expected Behavior

add to the loops marking objects too.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

**Comment by Jenefer-Monroe** [comment]
don't expect this to be a big perf improvement but might as well fix while we are walking everything for a concurrency scrub.
local fixed Jan

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
