### ISSUE TITLE
[CoE Starter Kit] Setup instructions for commercial and US Gov Clouds

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1674]
For these URLS
![image](https://user-images.githubusercontent.com/55705669/147137658-f1dbd5d8-aa20-4044-bf79-974b0730ef66.png)

For all commercial tenants the URLs are the same, they are different for Gov clouds only. We should investigate if  it would make the  install easier by defaulting these variables it to commercial cloud values and advising how to update for Gov clouds only.

**Comment by Jenefer-Monroe** [comment]
We have decided just to update the env variable description instead so that its easy to copy/paste. 
This will make the issue easier to deduce when done incorrectly
New descrition: 
Environment, including geographic location, for Power Automate - Ex for commercial: https://flow.microsoft.com/manage/environments/

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
