### ISSUE TITLE
[CoE Starter Kit - BUG] D4T - missing Portals table and flow

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1679]
### Describe the issue

Missing the Portals table and flow for inventory. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.10

### What app or flow are you having the issue with?

Core for Teams

**Comment by Jenefer-Monroe** [comment]
local fixed Jan
![image](https://user-images.githubusercontent.com/89584709/147495570-0c9fe57d-0255-4193-a639-f26b632c5bba.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
