### ISSUE TITLE
[CoE Starter Kit - BUG] Request Orphaned Objects Reassigned (Child) fails when too many objects

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1688]
### Describe the issue

When a user with lots of objects leave the org, there objects cannot be sent via teams due to adaptive card size limit
![image](https://user-images.githubusercontent.com/89584709/147694295-cf9708d0-5745-40d9-9890-f9b2eb1731bd.png)

### Expected Behavior

Send on email format in this case and send to admin persona as well so that they can assist as we will not be able to use the adaptive card until this is resolved.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

**Comment by Jenefer-Monroe** [comment]
local fixed Jan

![image](https://user-images.githubusercontent.com/89584709/147695865-49d4e0b3-bf70-4e48-9cce-80ed5ee94afb.png)
![image](https://user-images.githubusercontent.com/89584709/147695906-ee2aaa4f-4de5-49ac-a32d-4954ef84373c.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
