### ISSUE TITLE
[CoE Starter Kit - BUG] Set Flow Permissions - couple ownership bugs

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1689]
### Describe the issue

1 - On the orphans and owner pages, the on select shows
//navigate
Navigate(FlowDetailsScreen)

2 - not marking orphan

### Expected Behavior

1) this instead as with the environments page.
//navigate
If(IsBlankOrError(ThisItem.WorkflowEntityId), Navigate(FlowDetailsScreen), Navigate(FlowDetailsScreen_Solutions))

2) Remove the if statement, for some reason that didnt work even though it was true
UpdateIf(Flows, Flow=SelectedFlow.Flow, {'Flow is Orphaned': "No"});

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Set Flow Permissions

**Comment by Jenefer-Monroe** [comment]
local fixed January.

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
