### ISSUE TITLE
[CoE Starter Kit - BUG] Store HTTP - flow connections in table so they appear in the PBI / MDA

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1691]
### Describe the issue

Today since HTTP isn't a regular connector its not showing up in Power BI and the Model Driven App. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by Jenefer-Monroe** [comment]
local fixed for jan. http, http webhook, http trigger

![image](https://user-images.githubusercontent.com/89584709/147787586-b425c13a-9d57-4638-ac00-6d05791c909e.png)
![image](https://user-images.githubusercontent.com/89584709/147787688-57f0b6f5-d6af-453b-a898-fab1b9d264ac.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
