### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Archive and Clean Up v2 (Start Approval for Flows) Just a question

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#1736]
### Describe the issue

I just have a question about the **Admin | Archive and Clean Up v2 (Start Approval for Flows)** flow. Is this flow able to see if there were any recent runs on a flow? The reason I am asking is that multiple flow owners are complaining about receiving the archival request emails for flows that are actively kicking off every day. Sometimes multiple times in a day. Their main complaint is that there has not been any modifications on the flow because it is working as it should, So there is no need to modify it to prevent them from receiving the emails. We have been marking their flows as excused from archival, but I was wondering if it is able to see recent flow runs, so it can be a condition on whether the email is sent out.

I totally understand if it can't. 

### Expected Behavior

Flow checks to see if there are any active flow runs. If there is, then no action taken.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows)

### Steps To Reproduce

No steps to reproduce. Just have a question.

**Comment by Jenefer-Monroe** [comment]
Hello, no we cannot detect flow usage in the toolkit, further its our assertion that even if you could, that would not mean that the flow was still serving business value due to the verbose triggers options. 

You can, however, excuse the flow from these processes if the reasons stated by the makers is one you agree should allow the flow to stay in play. 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#app-and-flow-archive-and-clean-up-view

And you can excuse entire environments if you believe they are being actively monitored and kept clean already
![image](https://user-images.githubusercontent.com/89584709/148967446-da1d9c18-c773-4c65-9d33-56934236290d.png)

**Comment by AUTigers16** [comment]
I didn't think it was possible. Thanks for the confirmation.
