### ISSUE TITLE
Import solution fails

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#174]
**Describe the bug**
Importing a solution into environment fails as the import-unmanaged-to-dev-environment tries to consume a non-existing artifact from a deployment pipeline

**To Reproduce**
1. Click IMPORT SOLUTION
2. Select Solution
3. Select build number
4. Click IMPORT
5. Go to Azure DevOps
6. import-unmanaged-to-dev-environment has failed with the following error: ##[error]Artifact drop was not found for build 10.

**Expected behavior**
Expect the selected build of the selected solution to be imported into selected environment.

**Screenshots**
Import dialog
![image](https://user-images.githubusercontent.com/24893229/115201288-78db4600-a0f5-11eb-9a60-fd146b7551e3.png)

Import-unmanaged-to-dev-environment failed run
![image](https://user-images.githubusercontent.com/24893229/115201341-8690cb80-a0f5-11eb-91f7-f5244763b43d.png)

Referenced pipeline is deployment pipeline with no produced artifacts
![image](https://user-images.githubusercontent.com/24893229/115201621-d40d3880-a0f5-11eb-8bd8-41c6052f04f3.png)

**Additional context**
Seems the build numbers shown in drop down on Import dialog are runs of the deploy-validation pipeline. This pipeline does not produce any artificats.
Should the drop down instead show builds of the build-solution build pipeline that produce the solution artificats?

**Comment by devkeydet** [comment]
On the surface, this looks to be a regression because of our refactoring.  I will let @mikefactorial review and confirm.  

@jenschristianschroder - per our discussion this morning, this opens a broader discussion about how this experience should work in the canvas app UX.  The general scenario we are trying to address is the traditional code first workflow:

_- Get latest code changes from a specific branch into my dev environment
- Do my work
- Commit changes in my working branch
- Push changes to remote repo
- Submit PR_ 

So, I am thinking fix this bug first to get things back to the state it was in before the pipeline refactoring, but also review this work issue/enhancement:
https://github.com/microsoft/coe-starter-kit/issues/122

But we probably need to rationalize whether we repurpose #122 to be more "from branch" focused ux instead of "pick a build"

**Comment by jenschristianschroder** [comment]
Just tried to verify this using the latest pipeline templates. Everything works as expected so closing this issue.
