### ISSUE TITLE
[CoE Starter Kit - BUG] Export impacted apps/flows to CSV doesn't work

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#1760]
### Describe the issue

I don't receive the mail with the apps and flows impacted by a DLP.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

DLP Editor

### Anything else?

![image](https://user-images.githubusercontent.com/57954993/149618241-7261c104-d1be-4aac-a7bd-2efb46f1b62d.png)

![image](https://user-images.githubusercontent.com/57954993/149618245-64fc2349-5d00-4507-934e-de56f91fcb38.png)

**Comment by Jenefer-Monroe** [comment]
Hello. This app is considered part of the "inventory" setup. Each time to upgrade you need to ensure you have all the flows setup. This function uses the following flow which is considered part of the [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-setup-flows) set.

**_DLP Editor > Parse impacted resources into CSV_**

Please go make sure you have all these flows turned on in order to use the Inventory features of the starter kit. 
Thanks for using CoE!

**Comment by albertocaa1317** [comment]
I got it! Sorry, I have not seen in the documentation.

**Comment by Jenefer-Monroe** [comment]
No worries, thanks for using CoE!
