### ISSUE TITLE
Installing Coe InvalidPaginationPolicy (CoE Core)

### ISSUE THREAD

**Issue by Kaikapitaen** [microsoft/coe-starter-kit#1852]
current state: 
Dataabse 9.2.21122.00151
Updates	2021 release wave 2
CoE/ Core: 3.20.6

Activate Admin | Sync v3 monitoring 
"{"error":{"code":"InvalidOpenApiFlow","message":"
 Code: InvalidPaginationPolicy, Meldung: \" \"Get_Environments\"  Typ \"OpenApiConnection\" in 1 und 34474 . "minimumItemsCount\" 

Thanks for help.

**Comment by manuelap-msft** [comment]
Hello. All the flows have a pagination policy requiring a medium or high performance profile. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).

**Comment by Kaikapitaen** [comment]
Ahoi Manuela,
thx for writing me, thats mean a lot for me.
My view ist about 40times Environment and circa 10-200 Apps per Environment.
Will a need necessarily "Power Automate Pro Flow-Plan" License oder will a "Microsoft Power Apps for Developer”  License feed my need? 
Best regards, Kai

**Comment by Kaikapitaen** [comment]
Let me add my question:
If i need "Power Automate Pro Flow-Plan" how much License i will for COE/Core-Components witch include 53 Cloud-Flows?

**Comment by manuelap-msft** [comment]
Unforutnately we're not licensing experts and can't help with the detailed license setup required.

Any of these licenses will be sufficient
![image](https://user-images.githubusercontent.com/55705669/151333077-d3b98f72-b00e-4508-8ec2-3c0478b7e171.png)

We typically recommend a Power Automate Per User license that covers one user (the admin) running all the flows in the CoE kit, however some very large tenants may need increased API limits and will require a Power Automate Per Flow license for some of our long running flows.

I would recommend getting started with a Power Automate Per User license and checking if any flows are getting throttled (e.g. run for multiple days) and identifying those flows to assign them a Per Flow license. Based on the tenant size you've described above, I think it's unlikely you will hit throttling limits and the Per User license for all flows should be sufficient.
