### ISSUE TITLE
[CoE Starter Kit - BUG] Need help understanding if / how inventory collected

### ISSUE THREAD

**Issue by mjohnston1986** [microsoft/coe-starter-kit#1862]
### Describe the issue

Hi There,

We installed the CoE dashboard early last year. We've recently noticed that the report is only showing data for Power Apps until the end of June last year.

Around this time, we moved from Per User to Per App licensing. Would this have anything to do with the issue?

I noticed the dataset refresh had stopped working at the end of August, which I have now fixed.

### Expected Behavior

When selecting a certain date range, I would expect to see the data, however the dashboard is blank.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2021 Release Wave 2

### What app or flow are you having the issue with?

CoE - App Usage

**Comment by manuelap-msft** [comment]
Hello,

the CoE Starter Kit uses cloud flows to collect inventory and telemetry information (so info about your apps, your flows, your enviornments) into Dataverse tables in the environment you have the CoE kit installed. Everything in the CoE kit is then based on the data in this table - including the Power BI dashboard. 

There's a few reasons this data could be out of date:
1. The inventory sync flows are not running anymore https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows - this is the most likely cause. You will need to check the Center of Excellence - Core components solution to see if the flows have stopped and find the error - they could be suspended due to insufficient licenses, due to DLP policies, due to connection authorization issues etc. Once you know why they have stopped we may be able to help you further. 
2. The Power BI dashboard is using Import so a scheduled refresh needs to be set up to refresh the data regularly.
3. You're on an old version of our Core components solution that is now out of date. We relese the CoE kit monthly, and recommend upgrading at least every 3 months - learn more: https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup

**Comment by mjohnston1986** [comment]
Thanks Manuela, how do I check if the flows have stopped working?

**Comment by manuelap-msft** [comment]
1. Navigate to make.powerapps.com
2. Select the environment you have installed the CoE in
3. Select Solutions
4. Select Center of Excellence - Core components solution
5. Check the flows listed here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows - check they are on, and click on them to go to the Flow Details page and see if the runs are failing

**Comment by mjohnston1986** [comment]
Thank You, I've checked and the flows all appear to be switched on.

We ran a manual refresh this morning, would you expect data to show up after that?

We are currently running on version 1.78 of the app.

**Comment by manuelap-msft** [comment]
Please also check if the flows are successfully running - do so by selecting a flow, e.g. Admin | Sync Template v3 (Apps) and navigating to the Details page. You will see the run history there. Check that the flow ran recently (in the past two days) and the status of the runs succeeded
![image](https://user-images.githubusercontent.com/55705669/151396959-b42f225d-9692-45d1-9a2e-266fb732610f.png)

After a manual refresh, we would expect data to show up immediately if the refresh succeeds.

Our current version is 3.20 so you're quite a few versions behind (likely over a year).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
