### ISSUE TITLE
[ALM Accelerator - BUG]:  how can I get the ALM Accelerator for Power Platform App solution file? 

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#1900]
### Describe the issue

Hello,

 I am looking to set up the app mentioned here - https://docs.microsoft.com/en-in/power-platform/guidance/coe/almacceleratorpowerplatform-components

However the latest CoE starter kit does not include this app, and github file has a code files. 

Can you please suggest how can I get the ALM Accelerator for Power Platform App solution file? 

Looking forward!

Thanks,
T

### Expected Behavior

ALMAccelerator App should be available in the latest CoE Starter Kit mentioned here - https://docs.microsoft.com/en-in/power-platform/guidance/coe/setup

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

3.20.6

**Comment by mikefactorial** [comment]
Hey @tomsinsight, the Accelerator will be shipping with the CoE Starter Kit in the February release. As of right now we have a separate release. The latest is here (https://github.com/microsoft/coe-starter-kit/releases/tag/CenterofExcellenceALMAccelerator-January2022). However, to install the ALM Accelerator you'll want to follow the instructions found here since there are a number of steps involved in the setup process. We've create a Command Line Interface to automate the install process.

https://docs.microsoft.com/en-in/power-platform/guidance/coe/setup-almacceleratorpowerplatform-cli

If you want to look at all of the steps involved in manually setting up the ALM Accelerator without the CLI. See the following doc.

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform

We recommend using the cli to make setup easier since there are a lot of steps involved in the manual setup process

**Comment by tomsinsight** [comment]
Hello Mike,

Thank you so much for your time, Much appreciated!

I have installed through CLI, however the app does not show the experience dropdown as indicated as follows, would you please help what am I missing there?
![image](https://user-images.githubusercontent.com/98403757/152179557-39869af4-6d1a-4c7e-b915-7a94cb517ef1.png)

Thank you so much for your time in advance!

Best Regards,
Tom

**Comment by mikefactorial** [comment]
@tomsinsight see this #1850. For a similar discussion.

**Comment by mikefactorial** [comment]
Closing for now. @tomsinsight Feel free to open another issue or start a discussion if you have any other questions.
