### ISSUE TITLE
[CoE Starter Kit - BUG] Link in email is incorrect

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1918]
### Describe the issue

In the starter Kit release email for February, the link to issues and features takes you to June 2021
![image](https://user-images.githubusercontent.com/17124284/152337502-fd85e249-0872-4ab7-8557-f6f7f18d4559.png)

https://github.com/microsoft/coe-starter-kit/milestone/7

![image](https://user-images.githubusercontent.com/17124284/152337432-cedaa214-9020-4a03-9a6c-d1381f95087e.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2022

### What app or flow are you having the issue with?

Its the email sent

**Comment by manuelap-msft** [comment]
Hello,

the email is sent automatically when we publish a release (https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-February2022) and uses the text of the release. Yesterday we forgot to update the link to the correct milestone before we published the release which is why the email used the wrong link. We updated the Release itself since and will be more careful before publishing in the future!

Thank you
Manuela
