### ISSUE TITLE
[ALM Accelerator - BUG]: Questions related to App Configuration

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#1922]
### Describe the issue

Hello Team,

I have succesfully deploy the ALM through CLI, however as a next step, I require to configure the solution where I am stuck with the following questions - would you please help?

1. What is Team Maker experience?
2. Are target environments like dev-test-prod are used for "ALM Accelerator" solution management??? Does it mean that all solutions developed in MPP tenant - must go through these environments? Or Makers can use their own environments to deploy their solution?
3. Are these variables of "Maker's solution" variable? Or ALM's solution variable? Why they require to be configured?
![image](https://user-images.githubusercontent.com/98403757/152367261-40ffbab7-2da3-47bc-a03d-803694c5563f.png)
4. What are the component ownership? How does that relate to maker's solution or ALM's solution?
![image](https://user-images.githubusercontent.com/98403757/152367362-8c04d080-50e1-4435-ad9a-2d52bd2d300f.png)

Thank you very much for your time in advance!

Best,

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

latest

**Comment by mikefactorial** [comment]
@tomsinsight I'll do my best to explain based on my understanding of the questions.

1. Not totally sure what you're referring to, but users can have User Settings assigned to them (these are different experiences) in the app where certain features can be toggled on / off and some of the names of things like Commit, Deploy etc. can be changed. We have examples of two types of experiences in the docs that are driven off of the User Settings records in the Admin app. These are just examples of possible configurations but it's up to you how you want to configure them for your users (https://docs.microsoft.com/en-us/power-platform/guidance/coe/almacceleratorpowerplatform-advancedmaker, https://docs.microsoft.com/en-us/power-platform/guidance/coe/almacceleratorpowerplatform-newmaker).
2. The default pipeline configuration and profiles in the app assume that all solutions move 
 a. From dev to validation as a result of a Pull Request when the user chooses to Deploy from their personal branch to the solution branch
 b. from validation to test when the PR created above is approved.
 c. from test to production when a PR is created / approved from the solution branch to the main branch or when a user explicitly selects to deploy to prod.
The environments in question are configured on the profile associated with the solution. It's possible to customize these stages but requires updates to both the Profile and the pipelines to accommodate your scenario. NOTE: We don't have guidance in our docs currently on how to do this, but I'll add a backlog item to explain this further in a future release with some common scenarios.
3. The variables in question are based on the components in the solution you are working with. They are required in order to deploy a solution into another environment in a working state (e.g. you can't deploy a Flow that has a connection reference without supplying a connection in the target environment because the flow won't be able to be enabled in the target environment until the connection is supplied for the connection reference.)

**Comment by mikefactorial** [comment]
Moving to discussion #1952
