### ISSUE TITLE
[ALM Accelerator - BUG]: Why do we specify the three different environments in CLI installation process?

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#1943]
### Describe the issue

Hello,

As per my current understanding, the ALM Accelerator will be deployed in the single environment - which is basically a prod environment? If so, why do we specify three different MPP environments? Would you please help clarify? what is the purpose of having three different environments for ALM accelerator if ALM solution is not being deployed in other two environments?

![image](https://user-images.githubusercontent.com/98403757/152546880-20a3396f-f5b0-4868-8cb9-39d4e54a3b62.png)

Thanks,

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

latest

**Comment by mikefactorial** [comment]
@tomsinsight the three environments in question are related to the pipeline execution not to where the ALM Accelerator solution installed. There's an explanation of this here (basic) https://docs.microsoft.com/en-us/power-platform/guidance/coe/almacceleratorpowerplatform-components and here (advanced) https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/branching-and-merging. Ultimately, the default configuration of your pipeleines and the ALM Accelerator rely on 4 environments. 
1. The environment where the Accelerator is installed
2. The environment where you will deploy to when creating a Pull Request in the Solution Branch (Validation)
3. The environment where you will test the deployed solution after the Pull Request into the Solution Branch is approved and merged (Test)
4. The environment where your app will be used / share with others after a Pull Request to main from your Solution Branch is accepted and merged.

**Comment by mikefactorial** [comment]
Moving to discussion #1952

**Comment by mikefactorial** [comment]
#1943 
Q:
[](https://user-images.githubusercontent.com/98403757/152546880-20a3396f-f5b0-4868-8cb9-39d4e54a3b62.png)Hello,

As per my current understanding, the ALM Accelerator will be deployed in the single environment - which is basically a prod environment? If so, why do we specify three different MPP environments? Would you please help clarify? what is the purpose of having three different environments for ALM accelerator if ALM solution is not being deployed in other two environments?

image

Thanks,

Expected Behavior
No response

What component are you experiencing the issue with?
ALM Accelerator Canvas App

What solution version are you using?
latest

Steps To Reproduce
No response

Anything else?
No response
A: 
@tomsinsight the three environments in question are related to the pipeline execution not to where the ALM Accelerator solution installed. There's an explanation of this here (basic) https://docs.microsoft.com/en-us/power-platform/guidance/coe/almacceleratorpowerplatform-components and here (advanced) https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/branching-and-merging. Ultimately, the default configuration of your pipeleines and the ALM Accelerator rely on 4 environments.

The environment where the Accelerator is installed
The environment where you will deploy to when creating a Pull Request in the Solution Branch (Validation)
The environment where you will test the deployed solution after the Pull Request into the Solution Branch is approved and merged (Test)
The environment where your app will be used / share with others after a Pull Request to main from your Solution Branch is accepted and merged (Prod).

**Comment by tomsinsight** [comment]
Thanks Mike for clarifying, so I understand as below:

1. ALM Accelerator will be installed only in the single environments.
2. Maker who develops their app - "Maker App 1" is in his/her own development environment lets say - Dev Environment 1.
3. When Makers come to the ALM App, they will further deploy "Maker App 1"  from dev environment to validation environment ( Val Environment 1) to validate the solution.
4. Once validation is succeed, they will then move and deploy "Maker App 1"  from validation to Test environment (Test Environment 1) via ALM App.
5. And finally they make "Maker App 1"  live from test to prod (Prod Environment 1) via ALM App.

Is above process correct?

Thanks,
