### ISSUE TITLE
[CoE Starter Kit - BUG] Field is of type string but DateTime was specified

### ISSUE THREAD

**Issue by JQEP** [microsoft/coe-starter-kit#1968]
### Describe the issue

Upgrading / updating the CoE starter kit is not working. Getting the following error: Attribute admin_rpamodifiedon is a String, but a DateTime type was specified. with Code 80041A06. Cannot change or remove this field. I have tried importing from the classic view. But nothing seems to solve this issue. I am aware I am upgrading from quite an older version.

### Expected Behavior

That the solution successfully imports and that the Core solution is upgraded.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.44

### What app or flow are you having the issue with?

Core Solution

### Steps To Reproduce

1. Import solution
2. Select CenterofExcellenceCoreComponents_3_31_managed
3. Fill information
4. Error occurs: Attribute admin_rpamodifiedon is a String, but a DateTime type was specified.

**Comment by manuelap-msft** [comment]
Hello,

are you upgrading from 1.44?

Thank you
Manuela

**Comment by JQEP** [comment]
> Hello,
> 
> are you upgrading from 1.44?
> 
> Thank you Manuela

Yes, I am.

**Comment by manuelap-msft** [comment]
Unfortunately we are only able to help with Upgrades for versions 3 month back, I believe 1.14 may be over a year old - check here for how to get notifications when a release comes out: https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup#installing-upgrades

Since 1.14 the solution experience in the product has changed so much, introducing things like environment variables and connection references, that the version you are on right now will not be compatible with the new version. I believe you will have to start with a clean install from scratch. 

Here are some ideas for how you can migrate data if needed https://github.com/microsoft/coe-starter-kit/issues/1507 - this may be relevant if you've collected additional meta-data or audit log events that you want to keep.

**Comment by JQEP** [comment]
Alright, thank you.
