### ISSUE TITLE
[CoE Starter Kit - BUG] Admin|Archive and Clean Up v2(Start Approval for Apps)の利用について

### ISSUE THREAD

**Issue by TakatoNagano** [microsoft/coe-starter-kit#2000]
### Describe the issue

Admin|Archive and Clean Up v2(Start Approval for Apps)を有効化し、実行しましたが対象アプリの所有者へメールを飛ばすことができませんでした。
原因を調査したところ、以下アクションにて値が取得できていませんでした。
”List apps not launched or marked modified since Past Time”
取得できるようにするために対応についてご教授頂きたいです。

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.12

### What app or flow are you having the issue with?

Admin|Archive and Clean Up v2(Start Approval for Apps)

### Steps To Reproduce

１．Admin|Archive and Clean Up v2(Start Approval for Apps)を有効化し、”実行”をクリック
２．エラーは無く、処理完了

**Comment by Jenefer-Monroe** [comment]
I'm afraid I cannot help without more context. Are you saying that you expected an individual app to be returned from **_List apps not launched or marked modified since Past Time_** that was not returned? Or that no apps were returned. 

Please read about the [archival process here](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#archive-processes)

In particular the flow charts help you understand what apps would be chosen and what would happen to them through the archival flows
![image](https://user-images.githubusercontent.com/89584709/153199755-b8efae7e-70dd-469f-996c-a4287e1623c4.png)


Please share screenshots as well, those are helpful, note that you need to be logged in to GitHub to share images.

**Comment by TakatoNagano** [comment]
The result of executing Admin | Archive and Clean Up v2 (Start Approval for Apps) is linked.
I confirmed Create Archival Request for Each in this flow result, but it was white out.
When I contacted Microsoft support, Create Archival Request for Each was a "List apps not launched or marked modified since Past Time" action.
It seemed to perform loop processing based on the acquired record information.

As a result of downloading the data acquired by "List apps not launched or marked modified since Past Time", the second image was displayed.
Please let me know if there is a cause that has not been acquired or if there is a necessary setting .
![image](https://user-images.githubusercontent.com/95905410/153782710-055d7687-ed48-4ea9-9c2f-5477308682cf.png)

![image](https://user-images.githubusercontent.com/95905410/153782750-54e4bc65-ae5b-4caa-87d9-81d5d6ce8e59.png)

**Comment by TakatoNagano** [comment]
I explain the background in this question.
We would like to take an inventory of apps using the CoE Starter Kit to prevent the app from becoming overwhelmed.
Microsoft Support told me that Admin | Archive and Clean Up v2 (Start Approval for Apps) in CoE is an inventory of apps.
After importing CoE, activation of this flow is completed after the initial setting is completed.
At that time, the problem I asked above occurred.
A similar event has occurred with Admin | Archive and Clean Up v2 (Start Approval for Flow), so please resolve it.

**Comment by Jenefer-Monroe** [comment]
That is not the purpose of these flows. Inventory is set up with a different set of flows. 
Please see [setup inventory](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components)

**Comment by Jenefer-Monroe** [comment]
closing out but please return if you hit issues installing the inventory.
