### ISSUE TITLE
[ALM Accelerator - BUG]: Pipelines with incorrect triggers

### ISSUE THREAD

**Issue by andrewgaskins** [microsoft/coe-starter-kit#2032]
### Describe the issue

Investigating the triggers on pipelines deployed using the newest COE CLI there is an error with the applied triggering build.

### Expected Behavior

Would expect Test pipelines to have the deploy validation settings for that branch and not another. This appears to be different from the previous issue of the YAML build pipeline defaulting to the first branch.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20210922.2

### Steps To Reproduce

1. Run coe alm branch with correct inputs. 
2. Review created pipelines an everything looks correct
3. Review triggers for deploy-test* and it is referencing another triggering build in another branch
4. Manually make the changes pipeline triggers as expected. 

### Anything else?

![Screenshot 2022-02-10 143546](https://user-images.githubusercontent.com/11320569/153500640-0cd8b58b-9dd8-49f3-b7ab-c34f24804246.png)

**Comment by mikefactorial** [comment]
@andrewgaskins interesting...will need to look into this. Thanks for reporting.

**Comment by mikefactorial** [comment]
@andrewgaskins I think this issue is resolved in the March release and was a side effect of copying existing pipelines indiscriminately when running the branch command. We've removed this functionality unless the branch command is specifically called with a source pipeline to clone. Please retest with the latest version of the coe-cli. Here's the PR for the fix https://github.com/microsoft/coe-starter-kit/pull/1904
