### ISSUE TITLE
[ALM Accelerator - BUG]: RESOURCE NOT FOUND ERROR

### ISSUE THREAD

**Issue by GaborVig** [microsoft/coe-starter-kit#2048]
### Describe the issue

No action after pressing the "DEPLOY SOLUTION" button following the Title update and production environment target selection. The pipelines got triggered during the validation and test deployment phases.

Error:
POST https://europe-002.azure-apim.net/invoke 404 (Resource Not Found)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220114.1

### Steps To Reproduce

Validation Deployment Settings: 
Deployable: Allowed, Approval Type: Pull Request, Source Branch: ---, Target Branch: refs/heads/SolutionName

Test Deployment Settings: 
Deployable: Allowed, Approval Type: ---, Source Branch: ---, Target Branch: ---

Prod Deployment Settings: 
Deployable: Allowed, Approval Type: ---, Source Branch: ---, Target Branch: ---

**Comment by mikefactorial** [comment]
Hey @GaborVig, thanks for reporting this and for the details. It does look like the steps are misconfigured. I assume you created these manually or modified them from the default. By default they should be setup as follows.

![image](https://user-images.githubusercontent.com/42348035/153915269-f4765786-621c-4992-af2a-230dcf48db7b.png)

**Comment by mikefactorial** [comment]
If you use the AA4PP app to setup the profiles they should default to this configuration.

**Comment by GaborVig** [comment]
Hi @mikefactorial, I used the AA4PP to setup the profiles as you suggested, but the deployment settings that automatically configured is different for me. I also tried to update the target branch value manually to [Use Solution Branch], but it doesn't work. I'm getting the error below.

![image](https://user-images.githubusercontent.com/78961804/154078363-68e14491-966b-4521-bade-2b557720c7c9.png)
![image](https://user-images.githubusercontent.com/78961804/154078389-e7fa99a2-ffcb-4d2e-85f1-07c71b72a2a1.png)
![image](https://user-images.githubusercontent.com/78961804/154078414-eb5f3b32-2138-432f-99d6-21c79c36995a.png)
![image](https://user-images.githubusercontent.com/78961804/154078436-0005236e-7ad1-4df6-9873-6661da3bdc40.png)
![image](https://user-images.githubusercontent.com/78961804/154080715-764657be-1c16-4a9c-8789-70bf9daecb5c.png)

**Comment by mikefactorial** [comment]
@GaborVig this is where things get tricky. The default configuration would use the [USE SOLUTION BRANCH] in the deployment profiles. If you create a new profile with [USE SOLUTION BRANCH] you should see Deployment Steps that mimic what I showed in the previous screenshot. From there you'd commit your solution and then run through the process of deployment.

If you aren't planning to use the default setup you'll need to understand the pipelines a bit more in depth and update them appropriately.

The default triggers in the pipelines assume using the Solution Branch. However, we don't use solution branches internally and create our feature branches off of main as you show above. Here's a sample of what that might look like. 

![image](https://user-images.githubusercontent.com/42348035/154145999-39697d3a-1a14-4ca3-a437-28ea4120ba3a.png)

One thing to note here is that we are using an environment approval instead of a Pull Request approval for production. An environment approval will execute the associated pipeline directly (e.g. in this case deploy-prod-SolutionName). The expectation is that you have configured the production environment in Azure DevOps to require approval. https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass

Additionally, you'll need to update your pipelines to reflect the use of the main branch as the source for your feature branches whereby default they will assume you are using the Solution branching strategy. 

At some point we'll document all of this, but for now it's a bit esoteric and probably best to stick with the default setup of using the solution branching strategy until we have better coverage of the alternate scenarios in our docs and the tooling is better at handling the various scenarios automatically.

**Comment by GaborVig** [comment]
Thank you @mikefactorial
