### ISSUE TITLE
[CoE Starter Kit - Feature]: Need to fetch information for Power Virtual Agent for Teams 

### ISSUE THREAD

**Issue by IdrisHAli** [microsoft/coe-starter-kit#2055]
### Is your feature request related to a problem? Please describe.

Currently the COE toolkit doesn't support extracting PVA for Teams information. This is important as we cannot see who are the users building PVA for enterprise and we cannot reach out to them. 

### Describe the solution you'd like

We want the PVA for Team information made available in COE Tables (and Apps like Power Platform Admin view, Developer Compliance Center)

### Describe alternatives you've considered

No Alterative

**Comment by manuelap-msft** [comment]
Hello,

this is not possible in the product today.

The way the CoE Starter Kit works is it's installed in one environment, and uses the Dataverse (Legacy) connector to get information of all bots in environments across the tenant. The nature of the Dataverse (Legacy) connector is that it can't connect to Dataverse for Teams environments (authentication failure). And the "new" Dataverse connector only supports connecting to the current environment.

So unfortunately we can not meet this requirement due to product limitations. If something changes in the future, we will consider this for implementation.

Thanks for the feedback
Manuela
