### ISSUE TITLE
[CoE Starter Kit - Feature]: Record app quarantine status as part of sync flow

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2127]
### Is your feature request related to a problem? Please describe.

The app quarantine status is now returned as part of Get Apps as Admin, and should be recorded as part of the sync flow.
![image](https://user-images.githubusercontent.com/55705669/155739615-a772793e-c795-46a4-8db4-ca41902e6947.png)

### Describe the solution you'd like

If admins use power shell / their own logic to quarantine apps, make sure this is reflected in our meta-data by recording this as part of sync flows.

**Comment by Jenefer-Monroe** [comment]
Equation would look like this (with variety depending on where in the flow you are)
`if(equals(items('Apply_to_each_editted')?['properties/executionRestrictions/appQuarantineState/quarantineStatus'], 'Quarantined'), true, false)`

Unfortunately having it built in to the sync flow regular update spot here will cause the **_Admin | Set app quarantine status_** flow to run every time. Evidently that column filter will consider the field modified even if the value doesnt change.
![image](https://user-images.githubusercontent.com/89584709/158902760-ee3eccf1-2aac-438d-9578-2bc5f51c1366.png)

So we will need to decide if we want to allow for that (will be a lot of runs for full inventories) or add a little more complexity to the flow with a manual check if the value has changed.

**Comment by Jenefer-Monroe** [comment]
Plan instead is to add a new cleanup flow which will keep this up to date. 
The flow will cover both the DLP And Quarantine parts of execution Restriction
![image](https://user-images.githubusercontent.com/89584709/159012260-7ea88cc0-e4c4-4b9a-b848-8729fc9d28dc.png)

In order to avoid touching every single object in the tenant during the cleanup flow, they will run like this

loop 1
- get apps marked quarentined in the CoE
- see if they are still marked as such in the tenant
- if not update to false

loop 2
- get apps in the envt
- filter to quarentined apps
- mark all those apps as quarentined in the CoE if not already marked as such
