### ISSUE TITLE
Parse JSON Fails in [Child] Admin | Sync Logs Flow

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#2132]
Hi

I have a failure in Parse JSON in [Child] | Admin Sync Logs Flow.
[
  {
    "message": "Invalid type. Expected Integer but got String.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[177].RecordType",
    "value": "83",
    "schemaId": "#/items/properties/RecordType",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected Integer but got String.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[177].UserType",
    "value": "0",
    "schemaId": "#/items/properties/UserType",
    "errorType": "type",
    "childErrors": []
  }
]

I have no control of the Logs so I think this could do with try Catch Block around the Parse JSON.

Do you want me to do this for you ?

REgards

Nigel

**Comment by manuelap-msft** [comment]
Hello,

thank you! Are you on the latest version of the Audit Log solution? We saw some issues like this in August last year where the Audit Log event schema had changed in the product and we had to adjust how we parse the events, but have not seen this since.

This comment here  https://github.com/microsoft/coe-starter-kit/issues/959#issuecomment-893450646 shows what the latest schema should look like - if yours looks like this, but you're still seeing the error then we may need to do some more investigation on exactly what element it's failing at! I don't think anything in our current schema expects an Integer.

Thank you
Manuela
