### ISSUE TITLE
[CoE Starter Kit - BUG] How to confirm Active Apps and Flows in the Power BI Dashboard?

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2134]
### Describe the issue

Hi,

I require to know how to confirm active apps and flows in CoE Table vs Power BI Dashboard ( Version 2.1.7) - to ensure that statistics are correct.

For Apps,  I see that in Power BI dashboard - the number of Apps where app_deleted=False == 1832 and in CoE table "PowerApps App" where app_deleted=False == 1812 - Can you please share - why there could be the difference of **20 apps** in CoE Table vs Power BI Dashboard Report?

Similarly, for the Flows,  I see that in Power BI dashboard - the number of Flows where flow_deleted=False == 4603 and in CoE table "admin_flows" where flow_deleted=False == 5350 - Can you please share - why there could be the difference of **747 flows** in CoE Table vs Power BI Dashboard Report?

**Note:** The Power BI Dashboard Report - Environment Deleted == 30 in both apps and flows ( These statistics are in the Production environment, which can not be upgraded at the moment due to policy constraints)

Looking forward to hearing from you!

Thanks,

### Expected Behavior

Both Power BI Dashboard statistics and CoE Tables should have the same statistics as per my understanding. However, I am not 100% sure.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.7

### What app or flow are you having the issue with?

Power BI Dashboards - Apps and Flows Report

**Comment by Jenefer-Monroe** [comment]
Hello, there are many reasons people see differences between the different places to look at the app/flow count. 

Please see our [limitations page](https://docs.microsoft.com/power-platform/guidance/coe/limitations#inventory-differences-between-powershell-power-platform-admin-center-and-coe-starter-kit)

Since your discrepancy is with the PBI, you also might not have set up the report's data set to refresh. Please see this Power BI article on [configuring scheduled refresh](https://docs.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh)

Hope that helps

**Comment by Jenefer-Monroe** [comment]
You are welcome. Thanks for using CoE
