### ISSUE TITLE
[CoE Starter Kit - BUG] Problem with Flow - ForceRecheckOrphan

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2153]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/2150

<div type='discussions-op-text'>

<sup>Originally posted by **Nevinia210** March  2, 2022</sup>
Hello everyone,
does anyone experienced problem with flow HELPER - Maker Check?
Currently we have there one action
![image](https://user-images.githubusercontent.com/42325625/156345186-a1f73c01-5a33-4ed4-8b89-ceaffe64c2a5.png)
that is causing the problem:
![image](https://user-images.githubusercontent.com/42325625/156343621-41167777-ab4d-4959-ac92-d524ee870e08.png)
After February update(3.31) action is still there</div>

**Comment by Jenefer-Monroe** [comment]
Please open the flow in edit mode and expand the trigger, do you have all three input variables? 
![image](https://user-images.githubusercontent.com/89584709/156453552-10fc467e-ee9d-434b-8d55-d866be2d20a8.png)


If not, do you have an unmanaged layer on the flow?

**Comment by Nevinia210** [comment]
i have same trigger as you
![image](https://user-images.githubusercontent.com/42325625/156538938-cbc99f96-b30f-40b2-8b47-e9bfdaade306.png)
for unmanaged layer i have 2 layers in my current solution
![image](https://user-images.githubusercontent.com/42325625/156539722-8ad70fc3-5de4-4181-85c4-0b614e4f29aa.png)

**Comment by Jenefer-Monroe** [comment]
I'm not sure why you have that layer, maybe you edited the flow intentionally? You will need to remove it before you upgrade. 
But regardless, that wont be the cause of your failure here since you have the parameter. 

My next guess is that the flow calling here didnt pass in the parameter, which would mean that it has an unmanaged layer as we did validate that we are correctly passing for all the calls. 

Please find which parent flow is calling this child and failing. If you click show dependencies
![image](https://user-images.githubusercontent.com/89584709/156589401-340db822-befb-40cc-b917-9e24567efc93.png)

you can see all the flows that call it
![image](https://user-images.githubusercontent.com/89584709/156589499-e6b629ab-2b39-47ba-b944-bbfb849ca5bd.png)

See which of these are failing from the call to this child. And then see if that failing flow has an unmananged layer.

**Comment by Nevinia210** [comment]
Hello,
i removed all unmanaged layers from all our flows in CoE - that didnt removed the action above
then i upgraded solution to version 3.34 - that didnt removed the action neither
is there some way how to downgrade solution to previous version so during import i can select update which should replace our solution (that could maybe help for removing problematic action)

**Comment by Jenefer-Monroe** [comment]
We dont expect that action to be removed, we expect it to be filled. This helper doesnt run on its own, it is called by other flows. Can you please find which flow is failing as a result of calling that child flow?

**Comment by Nevinia210** [comment]
First flow that i found is "Admin | Sync Template v3 (Apps)"
i expected that at least name of that action will be renamed from "Initialize Variable" to something meaningful after removing unmanaged layer/upgrade, but its still same, is that correct behavior?

**Comment by Jenefer-Monroe** [comment]
We had not renamed that action for the March release. 

Is the (Apps) sync flow failing? If so, please get to that point of failure. If not, please find a flow calling this helper that is failing.

**Comment by Nevinia210** [comment]
I checked again all flows after one day (there is delay action in Admin | Sync Template v3) and flow ended up successfully, also Helper - Marker Check succeeded its runs yesterday, so march update actually helped to fix the issue,

Thanks for help

PS: previously i mismatch "Admin | Sync Template v3" with "Admin | Sync Template v3 (Apps)", (apps) flow is turned off anyway
