### ISSUE TITLE
AA4AM: Solution not imported to test, prod and solution imported to validation but all changes not reflecting

### ISSUE THREAD

**Issue by KarthikRao-HM** [microsoft/coe-starter-kit#221]
I am able to build the solution and push it to a dev repo and successfully do pull request validation as well. 
The main branch after pull request is setup (branch policy) to start the deployment to rest of the environments (validation, test and prod) wherein I am getting certain errors.

Few queries and issues that were encountered –
•	The solution was moved to validation environment but the changes are not seen, last modified of the flow that was modified is updated.
•	The solution was imported to validation as managed solution, is it the only option or can it be unmanaged as well without tweaking the underlying YAML files.
•	The solution was not imported to other 2 environments, test and production.
 
Below are certain screenshots that might help, 
 
Status as seen in Power app - Attachment 1
 ![Attachment 1](https://user-images.githubusercontent.com/82882835/116595019-7d4afe80-a940-11eb-9221-ee5fe5b5c0b9.png)
On clicking the error - Attachment 2
![Attachment 2](https://user-images.githubusercontent.com/82882835/116595014-7b813b00-a940-11eb-99d9-3bdd47528391.jpg)

**Comment by mikefactorial** [comment]
@KarthikRao-HM inline below
• The solution was moved to validation environment but the changes are not seen, last modified of the flow that was modified is updated. - First thing to check to see if this is a pipeline issue or a platform issue or something related to the solution not containing the expected changes is to go to the validation pipeline and download the managed solution artifact. Import it manually and verify if you get the expected results. Additionally you should be able to manually inspect your flow changes in source control by going to the branch / folder you committed your changes in and looking under SolutionPackage/Workflows similar to the screenshot below.
![image](https://user-images.githubusercontent.com/42348035/116605336-47385b00-a8fd-11eb-8420-177664c5601b.png)

• The solution was imported to validation as managed solution, is it the only option or can it be unmanaged as well without tweaking the underlying YAML files. - Solutions will always be imported as managed unless you change the underlying YAML. However, it would be good to know what the scenario you have is that brings up this question? 

• The solution was not imported to other 2 environments, test and production. - Based on the screenshot of the error can you verify that your Repo is called MyNewSolution and additionally that you've set the permissions for the build service per this step in the setup doc https://github.com/microsoft/coe-starter-kit/blob/main/PowerPlatformDevOpsALM/GETTINGSTARTED.md#update-permissions-for-the-project-build-service?

Below are certain screenshots that might help,

**Comment by KarthikRao-HM** [comment]
Hey Mike,

Thank you!
PFB details on progress and some questions on issues.

The first issue (**The solution was moved to validation environment but few of the changes are not seen**) was due to a change that was made in the target environment to the component in question - deleting the unmanaged layer of that component helped resolve the issue, now all changes are merged.

Regarding the second question (**The solution was imported to validation as managed solution, is it the only option**)- There might be certain scenarios where importing as a unmanaged solution may be required like tweaking certain actions or values during testing. There maybe different settings for target applications during testing or scenarios where very a small change maybe required to retest the entire process hence complete re-dployment from dev to test each time may prove counter productive. This is not a show stopper at the moment and can be managed by using a layering approach for unmanaged solutions and testing. 

Regarding the third issue (**solution was not imported to other 2 environments, test and production**) - The name of repo was wrong as you suggested after providing the right name everything described below was accomplished based on which I had few questions -

1. After push changes to git from power app below 2 pipelines are triggered from the cascade -
	A. Export-solutionname-to-git-branch
	B. Build-solutionname
are these the proper pipelines that should run?
2. After creating pull request from the ALM power app below 3 pipelines are triggered each time -
	A. Build-solutionname
	B. Deploy-validation-solutionname
	C. Deploy-test-solutionname
Is this approach, sequence correct? 
3. How can we stop it from directly deploying to test in this step and deploy it after merging with main branch? 
4. Is it supposed to deploy to prod at the same step or after approval/completion of PR as it did not happen after completion too. **_Basically deploy-prod-solutionname was never triggered._**

The scenario I am trying to work with here is -
If I have 3 environment only dev, test and production which are constants (they are sandboxes and production instances not trial), all the development will be done on dev and pushed to a dev branch in devops (using the first button in the app, the ALM app will be deployed in dev branch), using the second button the pull request is to be initiated and this validates and deploys in test, the testing of components will be done in test environment then the approver can approve, complete the merge between dev and main branch which will trigger deployment to (3rd) prod environment.

Also the cloud flows were in turned off state in the target, do they need to be turned on manually or do we have a feature to set them to start the flows. The scenario here is to remove any type of manual handling of solutions components by users.

**Comment by mikefactorial** [comment]
@KarthikRao-HM thanks for the detailed feedback and questions. 
Your configuration / setup is different than what is laid out in the setup documentation. As background and something that we will likely document in more detail. 

We have 4 environments including a validation environment that is used to deploy the solution when a PR is created in order to validate that the solution can be deployed before pushing it to test. 

Additionally, we have what we call a v-next branch that is branched from main and all in progress work is merged into prior to merging with main when we are ready to release.

With that background because your setup doesn't follow this pattern you're going to need to adjust the triggers for your builds and likely eliminate or repurpose the validation build for your scheme.

Another option is to setup your pipelines and branching similar to ours and use the pipelines as is. You could always make Validation and Test point to the same environment.

1. The build should not trigger on export unless you are pushing to a git branch that is configured as a trigger for the build pipeline. Normally, you would create a personal dev branch off of main or off of what you are calling the dev branch in your scenario (which would not be configured as a trigger in any of the pipelines). You'd keep pushing changes to your personal dev branch until you're ready to push to the main dev branch that all of the other developers would create their personal branch from.
2. After creating a PR the build should kick off and deploy to validation. The deployment to test should only happen after the PR is approved and merged.
3. You will need to modify your branch triggers. Difficult to say what to change and where without seeing your current pipelines.
4. The deploy to production should happen based on successful merge to the main branch or whatever branch is configured in your triggers for your production pipeline.

Cloud flows are turned on by the pipeline one of two ways. Assuming the flow is associated with a connection reference then when you setup the connection reference pipeline variable the pipeline will use the user who created the connection for the connection reference to enable the flow. In the case where your flow doesn't have a connection reference then the pipelines will revert to using the component owner pipeline variable to determine what user should be impersonated to enable the flow.
