### ISSUE TITLE
[CoE Starter Kit - Authentication issue - expired tokens

### ISSUE THREAD

**Issue by jainmilan002** [microsoft/coe-starter-kit#2226]
### Describe the issue

I have installed CoE starter last year. Till last month everything was working fine but then I am getting authentication error as below:- 
"Error from token exchange: Bad Key authorization token. Token must be a valid JWT signed with HS256
Failed to validate token: IDX10223: Lifetime validation failed. The token is expired."

I have installed version: 1.78

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.78

### What app or flow are you having the issue with?

on all the flow

**Comment by Jenefer-Monroe** [comment]
Hello, the platform does expire tokens. To see if that is something that you can repair, you would need to reach out to product support.

I'm afraid we cannot assist with an install this old. The CoE has gone through a few restructuring since then and so upgrade will likely not work. We recommend upgrading at least every 3 months to avoid getting into this state.

If all you are using us for is inventory then starting with a clean envt will not be difficult and is likely your best path forward. 

Please see [Before setting up the CoE Starter Kit](https://docs.microsoft.com/power-platform/guidance/coe/setup)
See #1507 if you have audit log data you need to migrate.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
