### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to turn on flow

### ISSUE THREAD

**Issue by scberr** [microsoft/coe-starter-kit#2234]
### Describe the issue

During installation of the starter kit, when I try to turn on the Cloud Flow "Admin | Sync Template v3 (Connectors)"

Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Connectors' of type 'OpenApiConnection' at line '1' and column '5514' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}". Code: 0x80060467 InnerError: '.

This seems to be because the paging threshold is set too high

### Expected Behavior

I would expect it to turn on successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_3_34_managed

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

### Steps To Reproduce

1. Install solution
2. Turn on Flow

### Anything else?

no

**Comment by scberr** [comment]
Same issue with these actions:

- List_initial_Connector_records

Same issue with these flows
- Admin | Sync Template v3 (Apps)

Looks like this is a duplicate of this issue
https://github.com/microsoft/powerapps-tools/issues/725

**Comment by manuelap-msft** [comment]
Hello. All the flows have a pagination policy requiring a medium or high performance profile. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites) and troubleshooting described in our [setup instructions(https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows)

**Comment by manuelap-msft** [comment]
Closing as this is a known and documented limitation.
