### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Center - Submit button does not move BPF forward

### ISSUE THREAD

**Issue by yodelmas** [microsoft/coe-starter-kit#2303]
### Describe the issue

Hello,

On Developer Compliance Center App, submit button is not updating "Admin Requirement - Rish Assessment State" to submitted.

So it breaks all the logic of validation BPF because wa can't go to the next phase.

Thanks for your help

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.12

### What app or flow are you having the issue with?

Developer Compliance Center

### Steps To Reproduce

1. Open App
2. Select an app
3. Filling information
4. Submit information

**Comment by Jenefer-Monroe** [comment]
We used to require that everything be filled in, including description, before moving the the risk assessment state along. 
As of March update we now do not do any checking to see what has been updated, we just move the state along if they hit submit, putting the requirement on the admin to manually push back if they dont have what they need. 
We do have on the backlog making this nicer but for now, if you upgrade you should not see this occur any longer.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by BhargavPrasadGorakanti** [comment]
Hi,

Our team is currently on 2.13v of Governance module and plans to upgrade soon. We find the App description check useful as the app would go back to "Requested" state immediately when Admin | Compliance Detail Request flow runs again anyway. 

Before considering any custom implementations, I wanted to check if there are any plans for potential future enhancements to the compliance form submission logic where app description becomes mandatory (again) in order to move to "Submitted" status. 

Also, would you consider adding a feature to let Makers update app description directly from Dev Compliance Center app?

![NonCompliant](https://user-images.githubusercontent.com/43746286/167884247-3b60b48b-1ddc-4476-b21a-d8933d103f64.PNG)

Thank you,
Bhargav

**Comment by Jenefer-Monroe** [comment]
Can you please post this as a new item? We dont track closed bugs closely. 
Thank you
