### ISSUE TITLE
[CoE Starter Kit - BUG] How can I create DLP poly into CoE?

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2308]
### Describe the issue

Hi, within the Micorsoft documentation I found that I can create a DLP policy within the DLP Editor V2 application. How can I do it? I don't see any buttons...
Thanks

https://powerapps.microsoft.com/en-us/blog/new-in-the-coe-starter-kit-review-the-impact-of-dlp-policy-changes/

![dlp](https://user-images.githubusercontent.com/101250592/160068194-ce65b135-e348-4520-b360-68dde22c676b.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

1. Run application DLP Editor V2

**Comment by manuelap-msft** [comment]
Hello,

our most up to date documentation on all the apps and components of the CoE starter kit is here: https://aka.ms/coestarterkit - blog posts easily get out of date, and won't reflect changes made to apps!

Here's the documentation for the DLP Editor
https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#dlp-editor-v2

Due to some limitations with the API used to create DLP policies, we had to remove the ability to create policies from this app. It can now only be used to change existing policies. Our recommendation is to create a policy in the Power Platform Admin Center with the connector configuration that you want, don't assign it to any environments (thus not causing an impact), then opening the DLP editor to modify the policy, assign it to the environments you want and performing an impact analysis there.

Hope that helps
Manuela
