### ISSUE TITLE
[CoE Starter Kit - QUESTION] Sync Flows performance

### ISSUE THREAD

**Issue by raphaeltremblay1966** [microsoft/coe-starter-kit#2327]
### What is your question?

Hello - We are running Core 3.34. For one particular environment, we have a difference of 1000 flows between the tenant (6589) and the CoE (5434). We have instructed to run a Full Inventory in order to see if it would complete the difference. 

The Sync Flow have been running for 12 hours, and never seem to finish. (I also notice that there is a big % number of "Failed" in the "Apply to Each Flow", any reason for this behavior ?).

![image](https://user-images.githubusercontent.com/99994964/160626265-87918048-b17e-400c-87cf-92f0646bf00e.png)

![image](https://user-images.githubusercontent.com/99994964/160628474-9e83e6a8-08de-4623-889f-a9383d4f28e3.png)

![image](https://user-images.githubusercontent.com/99994964/160626398-c1a71903-9def-4b4a-b670-da1cdf45401b.png)

Another example of never ending flow, that we endup cancelling :

![image](https://user-images.githubusercontent.com/99994964/160627445-71818478-f281-429c-9442-fd8820c4b27f.png)

The first inventory was done with an old version (1.71) and since then, there is no way to get the difference in number of Flows.
Is there something we can do to resolve this issue.

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34 (March 2022)

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid I'm having some trouble following your exact question here. 

Full inventories are slow for medium and large tenants because the flow is doing a bunch of work on lots of objects. 6500 flows in this one environment and this object type alone for you. 

It sounds like you may be hitting throttling limits as a result of the run, this would cause it to slow down even further. 
If this is the case, please see https://github.com/microsoft/coe-starter-kit/issues/917 for how to resolve in the short term, and [Power Platform admin center telemetry data export to Microsoft Azure Data Lake](https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate) for the long term solution explanation.

For the failures, I'm afraid you would need to have the flow complete so you can get information on them individually. We cannot assist with specific details. 

For now I would assume you've hit throttling limits and need to get the exemptions via support as described in #917 above.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
