### ISSUE TITLE
[CoE Starter Kit - QUESTION] ability to target test people before tenant with coe features

### ISSUE THREAD

**Issue by Dominic-Victrix** [microsoft/coe-starter-kit#2340]
### What is your question?

Is there a way to test all features included in Core and Governance Components without deploying it tenant wide? I would like to have a group of beta tester with makers and managers. 
From now, i'm used to customize each Flows to specify users or objects to test without spamming whole tenant with emails.

Can i turn off all sync flows and manage manually core tables (Makers, PowerApps app, Flows, etc.)?

Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2022

**Comment by Dominic-Victrix** [comment]
Thanks for your quick anwser.

First process we need to test is archival process. 

**What we did** : 
In "Admin | Archive and Clean Up v2 (Start Approval for Apps)" flow, we edited "List apps not launched or marked modified since Past Time " action to filter apps from a specific maker. 

Is there a better way to test the process? 

Our first goal is to review all emails before going in production.
Second goal is to translate emails.

Thanks again!

**Comment by Jenefer-Monroe** [comment]
Gotcha. Here are a few things that will help. 

1) There is an environment variable called **_ProductionEnvironment_** 
This is set to Yes by default but you can set it to No in your test environment and the mails from Archival will go to the Admin Email instead of the end user. Please remember that flows cache env vars and so will need to be turned off and back on in order to get the new value

2) Exempt environments from the process
We allow you to excuse environments from the processes see [here](https://docs.microsoft.com/power-platform/guidance/coe/setup-archive-components#exempt-environments-from-the-archive-process) for more details. You could have a test environment where you run this stuff

I hope that helps!

**Comment by Jenefer-Monroe** [comment]
Glad to help. Thanks for using CoE!
