### ISSUE TITLE
[CoE Starter Kit - BUG] no Audit Log for CoE Starter Kit

### ISSUE THREAD

**Issue by tinghu2000** [microsoft/coe-starter-kit#2356]
### Describe the issue

There is no Audit Log  for CoE Starter Kit

### Expected Behavior

![Capture](https://user-images.githubusercontent.com/102851701/161374400-84bce06f-4242-4590-bfa9-e85b57aedd83.PNG)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

power apps dashboard

**Comment by Jenefer-Monroe** [comment]
Please validate that you have installed and setup the [audit log solution](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog).

If so, please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

And a picture like this showing the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
