### ISSUE TITLE
[CoE Starter Kit - BUG] Action 'Get_Maker' failed

### ISSUE THREAD

**Issue by GoerdesM** [microsoft/coe-starter-kit#2421]
### Describe the issue

During execution of flow "Admin |  Sync Template v3", I get the following error during the "Get Maker" action within the "Check if Legacy Environment" step. Message is "The server did not receive a response from an upstream server. Request tracking id '08585520780531798873254887936CU01'". I recently upgraded to the April version.

![image](https://user-images.githubusercontent.com/103028386/162678566-5d44e49a-0d00-4c38-ae3b-fa075d6d9c54.png)

### Expected Behavior

Flow should work without error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.17 for Teams

### What app or flow are you having the issue with?

Admin - Sync Template v3

### Steps To Reproduce

Using Core Components for Teams 3.17
Executing Admin - Sync Template v3

**Comment by txh57** [comment]
Same here. It happens for all environments of _EnvironmentType_ Default and Developer.

There are no unmanaged layers in solution Center of Excellence - Core Components and we are on CoE version Apeil 2022.


`get-adminpowerappenvironment | select EnvironmentName, DisplayName, CreatedBy, CreationType, EnvironmentType | where EnvironmentType -like 'De*'`
![image](https://user-images.githubusercontent.com/25150539/162710328-99b4c691-372f-48e1-a910-fb49856d060c.png)
All of these environments have a _CreatedBy/id_ of SYSTEM instead of a GUID.

`pac org query -s "select TOP(10) admin_displayname, admin_makerid from admin_maker"`
![image](https://user-images.githubusercontent.com/25150539/162710515-0176d776-6226-430a-ad37-c56790cbf019.png)

### **Flow Admin | Sync Template v3**
Scope: Store Environments in the CoE CDS Entity
Condition: Check if Legacy Environment
False
Get Maker
![image](https://user-images.githubusercontent.com/25150539/162710753-053c311f-a796-4a6a-9d48-8c95881f12dd.png)

### **Flow HELPER - Maker Check**
![image](https://user-images.githubusercontent.com/25150539/162710829-f5f258a6-3e34-4ea8-a99f-322a6f7a770e.png)
The calling flow passes SYSTEM to flow HELPER - Maker Check which fails because it expects a GUID.

**Comment by manuelap-msft** [comment]
Hello,

@txh57 I see you are on 3.36 - we unfortunately had a bug in this version, and released a hotfix the day after the release went out - version 3.37 (https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-April2022/CenterofExcellenceCoreComponents_3_37_managed.zip). You'll have to upgrade to fix this!

@GoerdesM I don't think we had this error in the Teams version, can you confirm all the child flows are on? https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows

Thank you
Manuela

**Comment by GoerdesM** [comment]
Yes, all Flows are ON like documented. In addition to the error on the Admin | Sync Template v3 Error I just see another failed run within the Admin | Sync Template v3 (Model Driven Apps) flow. However, following runs of this flow were successful again. Error there is in step "Get Model Driven Apps and store in CoE CDS Entity > Apply to each Model Driven App > Get Owner and first orphan check > Get MDD App Creator". Error 404: No Organization is matching the given dataset. Don't know if this is related to the other issue, but potentially a hint.

![image](https://user-images.githubusercontent.com/103028386/162727642-7b5d0996-a9a4-4164-8b96-fa631d91baab.png)

![image](https://user-images.githubusercontent.com/103028386/162727723-6408523e-2f28-4efe-9f3e-f33e698d716b.png)

**Comment by GoerdesM** [comment]
Just see your comment about the new version. I will try to download and update and let you know

**Comment by txh57** [comment]
> Hello,
> 
> @txh57 I see you are on 3.36 - we unfortunately had a bug in this version, and released a hotfix the day after the release went out - version 3.37 (https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-April2022/CenterofExcellenceCoreComponents_3_37_managed.zip). You'll have to upgrade to fix this!
> 

Thanks for the hint about the hotfix for the core components.
Updating from version 3.36 to version 3.37 solved the issue.

Thank you Thomas

**Comment by manuelap-msft** [comment]
@txh57 Super, thanks for confirming so quicky and really sorry for the inconvenience!

**Comment by GoerdesM** [comment]
Hi @manuelap-msft, installing the newest version 3.18 also worked for us. Problem is solved. Thanks

**Comment by manuelap-msft** [comment]
Amazing, thanks for confirming so quickly and sorry again for the inconvenience!
