### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to create a new DLP policy with DLP Editor V2

### ISSUE THREAD

**Issue by jsbernier-Victrix** [microsoft/coe-starter-kit#2427]
### What is your question?

The CoE Starter Kit documentation says that you can create new policies from the DLP Editor V2 application. But I don't see a "New" button to create a policy. I am only able to edit an existing policy. How can a new policy be created from the DLP Editor V2 application.

![image](https://user-images.githubusercontent.com/103434468/162755404-175ec396-2900-4adb-85f2-4f2c3ce26a15.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

DLP Editor V2

**Comment by manuelap-msft** [comment]
Hello,

the DLP Editor only supports editing DLP policies, could you let me know where in the documentation you found a note that creating policies is supported? I just checked our docs (https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#dlp-editor-v2) and the don't mention it, so please let me know where you found a reference to creating so I can get that updated 

![image](https://user-images.githubusercontent.com/55705669/162756241-a10dc6ba-0e6c-4864-856b-d441787fc966.png)

Due to some limitations with the API used to create DLP policies, we had to remove the ability to create policies from this app. It can now only be used to change existing policies. Our recommendation is to create a policy in the Power Platform Admin Center with the connector configuration that you want, don't assign it to any environments (thus not causing an impact), then opening the DLP editor to modify the policy, assign it to the environments you want and performing an impact analysis there.

**Comment by Jenefer-Monroe** [comment]
Note also, that the text string at the top of the app has one more sentence making this clear.
You state you are on 3.37 so perhaps you have an unmanaged layer on the app and are not seeing all the changes. 
![image](https://user-images.githubusercontent.com/89584709/162758239-a94dab6a-b029-4bb5-af96-bf59235355e9.png)
