### ISSUE TITLE
[CoE Starter Kit - No Edit Button]

### ISSUE THREAD

**Issue by LilianThomsen** [microsoft/coe-starter-kit#2444]
### What is your question?

Somehow the edit and bulk edit buttons as well as the activate + deactivate buttons are gone when opening the Power Platform Admin View CoE app.

![image](https://user-images.githubusercontent.com/103517574/162988505-15b784a0-de15-4b9b-84a6-fb3df2bc7720.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Hello. I dont think we ever had those in the ribbon, and if we did, they were not intentional. 

At a high level:
- the ribbon here in particular comes from the Dataverse and its contents are dependent upon your security role for that table. We would hide it entirely if we could, as it causes confusion. 
- things like "assign" "delete" here only act upon the record, not the object (app in this case). So deleting here only deletes the record, it would come back on the next inventory run. 

Specifically:
- to edit a record if you want to augment the data (ex excuse app from archival), you click on the app name. 
- we also don't utilize active / de-active state for anything

Hope that helps.

**Comment by LilianThomsen** [comment]
It does. Thank you for clarifying :-)
