### ISSUE TITLE
[CoE Starter Kit - QUESTION] multiple versions in same environment, unable to uninstall any of them

### ISSUE THREAD

**Issue by eoszak** [microsoft/coe-starter-kit#2457]
### What is your question?

Somehow I have both v1.98 and v2.75 of the core components in the same environment (default environment), I'm trying to remove them both and install the latest in a separate environment all its own, but I'm unable to uninstall either one.  The v2.75 says there's a dependency on Admin | Sync Template v3 (Connectors), and the v1.98 says it is the base for an upgrade solution. Please delete CenterofExcellenceCoreComponents_upgrade first.  Any suggestions?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.98

**Comment by Jenefer-Monroe** [comment]
Hi there. Sorry I'm afraid we cant drive too deeply into issues this specific to your tenant. 

However, generally speaking, since all you are trying to do is delete, I think if you can get the list of dependencies you can delete them individually and then delete the solution once they are gone. 

If you switch to classic mode from the solution page
![image](https://user-images.githubusercontent.com/89584709/163214135-d3c93957-b535-4b05-b31c-a795a0c45ac6.png)

You can delete from there and you will likely get more detailed dependencies issues listed
![image](https://user-images.githubusercontent.com/89584709/163214607-10723229-319c-4786-b55f-948a9aabf4ea.png)

And delete them one by one. 
I hope that helps

**Comment by eoszak** [comment]
Thank Jenefer, but in Classic view mode the same error message persists.  
![image](https://user-images.githubusercontent.com/49961711/163248240-3d99a636-1580-4e93-a8e9-3f6ef338161b.png)
I was able to drill into the solution layers for the first one and remove the Active layer, but the others remain, and the context menu doesn't open with any options.
![image](https://user-images.githubusercontent.com/49961711/163249209-1d749f0c-25e9-4bfa-afed-6ad296b3b1c7.png)
Normally I'd just delete the environment, but it's the default environment.  I've already stood up a separate environment just for CoE to ensure this doesn't happen again, but trying to make sure there won't be any interference with the two installations once I do that.  I turned off all of the flows in the current solutions, maybe that's all that's needed?

**Comment by Jenefer-Monroe** [comment]
My suggestion was just to use classic to see if it gave you better error messages on the dependencies. 
I'm afraid the only thing I can suggest is deleting the objects in Default 1 by 1, that will likely need to be iterative as you slowly remove dependencies since you cannot find the dependencies list.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
