### ISSUE TITLE
[ALM Accelerator - QUESTION] Patches & Solution Clone for new minor/major

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#2460]
### What is your question?

**A couple of questions:**
Is there a concept / documentation, how I should use the AA4PP, when my team want to work with creating Solution Patches & creating Solution Clones (next minor/major)?
Which branching model should I use?
How do I deploy solution patches with AA4PP?
Does AA4PP pipelines use the new the Minor/Major version?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 2022

**Comment by mikefactorial** [comment]
@megel great questions. 
1. We haven't handled patching in the ALM Accelerator, mostly because we don't see patching as a long term solution in the solution framework. The goal would be for the solution framework to better understand changes in a solution and upgrade / update appropriately. 
2. As far as branching strategies. Right now we only support 1 and that's the default strategy of solution branches / maker branches and then ultimately pushing to the main branch. We have plans to support other strategies but there are any number of strategies that the accelerator can support we just need to have the time to provide guidance on these. This could be opened as a seperate issue and upvoted by the community to give up some guidance on where to focus our efforts.
3. Solution versioning happens on export currently and still uses a workaround to version the solution. You can see this here https://github.com/microsoft/coe-alm-accelerator-templates/blob/05ad5e278cffd00beec71189506e38ac5bee2b01/Pipelines/Templates/export-Solution.yml#L114. There have been improvements in PAC CLI since we implemented this functionality that we've yet to incorporate into our pipelines.https://www.powercommunity.com/power-platform-cli-january-update/

**Comment by megel** [comment]
@mikefactorial:

1. I agree. We have tested patching because of the possibility to a rollout minor solution parts much faster. It's similar to a hotfix branch & cherry-picking the commit into solution-branch / main-branch. And yes, patching does not fit into current branching concept.
2. The standard branching strategy works well and is easy to understand.
   - PR to `main` branch trigger import in PROD environment
   - Commit to `<solution>` branch trigger import in TEST environment
   - PR to `<solution>` branch is validated (policy) in VAL environment
3. I guess it make sense to overrule major and minor version during solution-build. The value should be based on the current major/minor from development during solution export. Both values can be transferred into pipeline similar to values from `CONFIGURE DEPLOYMENT SETTINGS`. What do you think?

**Comment by mikefactorial** [comment]
@megel  Closing this out. Feel free to open an enhancement request that we can [rioritize based on our converations.

**Comment by mikefactorial** [comment]
We'll be releasing some features in the september release to address this.

**Comment by SBichler** [comment]
Hi @mikefactorial,

I was searching for AA4PP support for patches and found this issue. My question is if patches are still not on the roadmap for the ALM Accelerator.

Why am I asking?
In our work as MS partner, it is a very important use case to deliver fast hotfixes right to production. Currently, the easiest way to do so is by using patches. By that, I can change only the problematic artifact and deliver solely that. The alternative if we want to use the ALM Accelerator is to deliver the whole solution. This is problematic because in the middle of a sprint, there might be unfinished artifacts in the solution or the solution is already on the test environment but not fully tested, therefore we can't merge the solution branch into main until all components are finished and tested.

**Comment by Cliveo** [comment]
> We'll be releasing some features in the september release to address this.

Has this happened? I'm trying to deploy a patch at the moment & the way the build versioning is done the patches version is below the base solutions version.
