### ISSUE TITLE
[ALM Accelerator - QUESTION] plans to have that solution work with "least privileged" environments

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2464]
### What is your question?

Piggybacking on the ALM question, are there plans to have that solution work with "least privileged" environments? As in, I'm not a GA and will never have the ability to create AAD groups so installing that ALM accelerator will be difficult. There was a discussion post on this, too.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

n/a

**Comment by mikefactorial** [comment]
Unfortunately, the complexity of the app require advanced permissions to install, but not necessarily to use the app. One way to work around this would be to break out some of the install actions in the CLI in order to be run by other people with the correct permissions in the organization. Would be good to get others thoughts and experiences on this to better understand and address the need.

**Comment by mikefactorial** [comment]
Closing this out as it's no longer relevant with the updates to use the Project Setup Wizard
