### ISSUE TITLE
[ALM ACCELERATOR - QUESTION] CoE Cli download

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2468]
### What is your question?

From @megel: When is the CoE CLI available as download / installable package like the Power Platform CLI?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

n/a

**Comment by mikefactorial** [comment]
@megel another great question. Thank you for being so involved with the Accelerator and the Starter Kit.

 The coe-cli and our templates are not necessarily packaged for download. We've been discussing this internally. One benefit of not packaging the CLI and the templates is our ability to be agile and make updates on the fly, but I think we've landed on that's not maintainable and we need to get more regimented now that we are part of a regular release cadence with the Starter Kit. Leaving this open because I don't think we have a backlog item for it.

**Comment by mikefactorial** [comment]
Related to #2505
