### ISSUE TITLE
[CoE Starter Kit - QUESTION] How can I get the App Last Launced column to display a result?

### ISSUE THREAD

**Issue by nilliers** [microsoft/coe-starter-kit#2508]
### What is your question?

Power Platform events are not being logged properly in the M365 Audit log.  Inside the CoE All Apps audit logs displays the following results under All Apps, App Display Name; App Environment; App Owner; App Created date; App Modified date; and App Type all with results.  The App Last Launched column does not have a result.  How can I get the App Last Launced column to display a result?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Feb 2022

### What app or flow are you having the issue with?

 App Last Launched

**Comment by Jenefer-Monroe** [comment]
Please also validate that you have installed and setup the [audit log solution](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog).

If so, please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

And a picture like this showing the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png)

**Comment by EricTingler** [comment]
Hello, I am having the same issue. 

I have checked the items you have above and the API is set up correctly, and the Flow has been running successfully. 

It has been about a week since we have set up the CoE. 

Any idea on how to fix this issue?

**Comment by Jenefer-Monroe** [comment]
Note that the audit log solution begins gathering launches at the time you enable. So you will not expect to see those that occurred before you turned on the logs. 
I suggest launching a few apps, waiting a few days, and seeing if those flags get their last launched date udpated. 

If not, and if you'd like to have me make sure they look correct. Please share the images I have requested above to show completed setup.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
