### ISSUE TITLE
DLV Editor V2 - Not all impacted Apps/Flow listed

### ISSUE THREAD

**Issue by Sulomania** [microsoft/coe-starter-kit#2521]
### Describe the issue

We created a new DLP Policy and wanted to see the impact for existing Apps/Flows in an environment. Within the DLP Policy the SQL connector is blocked. The DLP Editor was showing us less impacted apps/flows than we expected. We checked the amount of apps/flows using the SQL connector in the COE Dashboard. Here is the amount much higher. Is there any inconsistency why the DLP Editor V2 is showing less impacted apps/flows?  

### Expected Behavior

Same results in DLP Editor V2 and COE Dashboard

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April 2022

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

1. Run DLP Editor for a DLP Policy where SQL is blocked
2. Receive CSV Document with impacted apps/flows
3. Compared the apps/flows with the results on the COE Dashboard and some Apps/flows which are using SQL are not detected by the DLP Editor

**Comment by Jenefer-Monroe** [comment]
Your DLP policy may be targeting particular environments, or excluding some. Can you check on that?

**Comment by Sulomania** [comment]
The DLP Policy is targeting the default environment and it is analyzing the amount of apps (1532)/flows(3262) which are available in the default environment.

**Comment by Jenefer-Monroe** [comment]
Here is the DLP Editor for my case, it analyzed 35 total apps (in that environment) and found 23 that would be broken 
![image](https://user-images.githubusercontent.com/89584709/164245976-2b8c7075-6dab-4468-a191-ad593b3739be.png)

**Comment by Sulomania** [comment]
Hi Jenefer,
I have following information for the specific App

App Connection
![image](https://user-images.githubusercontent.com/103515392/164683381-375b4f4e-9554-404b-a00d-5ef1fc15ec4f.png)

App Modified on:
![image](https://user-images.githubusercontent.com/103515392/164683731-7b09c751-9b84-4956-a722-7237c93ee367.png)

Admin_Apppublished:
![image](https://user-images.githubusercontent.com/103515392/164683835-e291c785-f53f-4a5d-bad6-fdbec70caab3.png)

App Type:
![image](https://user-images.githubusercontent.com/103515392/164684030-d0182bbb-65c0-46ab-9a51-c3d1a526cf82.png)

Is it helpful?

Thanks a lot for your amazing support!

**Comment by Jenefer-Monroe** [comment]
Thanks for following my steps! So I see the SQL Server in the list. 
Two more things to check in that Excel export please.

**Comment by Sulomania** [comment]
Here are the next requested information:

App Environment:
It is the default environment

DLP Evaluation Status:
![image](https://user-images.githubusercontent.com/103515392/164710860-137096a4-12b2-4ad3-b223-ee68e002608d.png)

App Deleted:
![image](https://user-images.githubusercontent.com/103515392/164710968-b9fac450-346e-4d98-9872-e2e8051ef1c7.png)

I can confirm that I see some but not all of expected apps/flows that use SQL

**Comment by Jenefer-Monroe** [comment]
Thank you for confirming. It looks like an issue specific to the app then, I'll assign to the app owner now that we've got this info.

**Comment by manuelap-msft** [comment]
Hello,

The Power BI gets the information through a relation between the **PowerApps App** and the **App Connection References** table. Due to [delegation limits](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/delegation-overview) in canvas apps, the DLP Editor can't make use of that relation but instead gets connections used in the app from the **App Connections** field in the  **PowerApps App** - this is a text field that contains the connections in a comma seperated way (e.g. SharePoint,SQL Server,)

Can you confirm that this field is populated for the app you're missing? 

You may have to use Data > Edit data in excel on the PowerApps App table to review this information.
![image](https://user-images.githubusercontent.com/55705669/165253620-a22fd4b9-43fd-43e3-b47a-d54e95261dfe.png)

If this information is not there for the app you're missing, please run a full inventory: https://docs.microsoft.com/en-us/power-platform/guidance/coe/faq#running-a-full-inventory
