### ISSUE TITLE
Admin Sync Template v3 (Flows) failing on Get_flow_from_CoE action

### ISSUE THREAD

**Issue by raphaeltremblay1966** [microsoft/coe-starter-kit#2531]
Hello - we have the Admin Sync Template v3 (Flows) failing with the error 'Action Get_flow_from_CoE' failed. It happens for a number of environments, where for other environments, it works fine. Any ideas what could cause this ?

![image](https://user-images.githubusercontent.com/99994964/164309472-baadc2b3-8eb8-479a-bde0-13e9de396184.png)

**Comment by raphaeltremblay1966** [comment]
Some more info : we are running CoE Core components 3.37 (April 2022).

The Flow seems to stop at a particular flow with the Forbidden error

![image](https://user-images.githubusercontent.com/99994964/164315395-eaff98ac-c3b0-4e25-86d7-b4db3bfb3eeb.png)

![image](https://user-images.githubusercontent.com/99994964/164316053-db015276-6b35-4ab6-a927-30bd61a7d845.png)

The user used for the Coe Flows is System Administrator.

Thanks

**Comment by raphaeltremblay1966** [comment]
If I try to run a Full Inventory, just as a test, it will fail also.

![image](https://user-images.githubusercontent.com/99994964/164325958-65a812ab-c90e-4ac6-9f0f-ea26bf1d782e.png)

Would it be possible, if an error comes with the Get Flow as Admin, to just skip it, and not abort, because we never have a fully synched inventory.

**Comment by Jenefer-Monroe** [comment]
This was posted in a way that it did not get into our list. Getting it into our lists

**Comment by Jenefer-Monroe** [comment]
I believe you have hit a known product bug around caching of deleted flows. If so, you will need to contact support to have them clean this up in order to have this flow start passing.  
 
Our recommendation is to first get a repro outside of the toolkit before contacting support. You can use the below flow to get this repro.  
 
To use: Import the flow, open, select the environment which repros for you.   
It loops the flows, will hit the same failure and the you can go to support with this flow instead of the toolkit, for faster iteration to fix.  
[ProductBugDemo-getflowaftergetflowsfails_20211116133300.zip](https://github.com/microsoft/coe-starter-kit/files/7546680/ProductBugDemo-getflowaftergetflowsfails_20211116133300.zip)
![image](https://user-images.githubusercontent.com/62659043/124291999-64162800-db12-11eb-92a6-55b4ffe1ecee.png)

**Comment by YvoValcon** [comment]
Hi Jenefer,

I received the same error message, what are the steps to be undertaken?
