### ISSUE TITLE
[CoE Starter Kit - BUG] Apps created with only Last Launched On information

### ISSUE THREAD

**Issue by LukasKo999** [microsoft/coe-starter-kit#2586]
### Describe the issue

We are currently having 700+ Apps that has only Last Launched On information filled out. This is probably causing 
[Child] Admin | Sync Logs flow, in action Update App Last Launch Date. 
![image](https://user-images.githubusercontent.com/93936147/165728281-7d20723c-71cb-4165-901e-c26d3d047dbc.png)

### Expected Behavior

Those App should be updated as deleted or data populated if existing.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Steps To Reproduce

Let's assume the scenario App is created and deleted straightaway. 
1. Create canvas app and run it at least once.
2. Delete the app
3. Run Audit Log flow
4. Check if there is a blank app
5. Run Sync flow Canvas app
6. Check if this did anything

**Comment by Jenefer-Monroe** [comment]
Hello, I dont quite follow you. 

The audit logs only track last launched. They are not used for tracking delete. I know its in there but its just legacy, the API changed, and we now catch deletes via the clean up flows.

And for launches, the audit logs can only catch and update apps that have already made it to inventory. 

Please let me know what you are trying to accomplish.

**Comment by LukasKo999** [comment]
Hi Jenefer, I just found out that we are not running CLEANUP - Admin | Sync Template v3 (Delete Bad Data), because we were not sure if we want to delete data. But this one is inevitable seems like. Sorry for false alarm.

Just add here. Child Audit Log is upserting the App record, if App has been launched, but not yet synchronized with Admin | Sync Template v3 (Apps).

**Comment by Jenefer-Monroe** [comment]
We have divided up the flows by function, and so all flows in this page are required to know that the inventory is running correctly. 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components

We cannot add the app inline here as there is just too much complexity (I know it seems like it should be easy) for adding new apps. You can see how long the list of actions is in the (Apps) sync flow to understand what I mean. 

This should not happen frequently though, due to all the delays in the system. 

Please me know if there is anything else we can do to assist here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by LukasKo999** [comment]
Hi Jenefer,

That Update Launch Date action in Audit Log is doing Upsert. If App does not exist, it’ll create a new App row with launch date only.

LK
________________________________
