### ISSUE TITLE
[CoE Starter Kit - BUG] Before writing Flow Instance URL for Sync Flow Errors, check format of Power Automate environment variable and add / if it doesn't exist

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#2602]
### Describe the issue

The Column 'Flow Instance URL' has an invalid URL in it -
![image](https://user-images.githubusercontent.com/8484048/165936226-3c8381a6-2946-4dcd-9a11-f93d004e3cd2.png)

There is a missing "/" after the word 'environments'.

So that when you click on the icon to show the error, you get the default environment and not the run error.

### Expected Behavior

I expect the column 'Flow instance URL' to have a valid URL in it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Sync Flow Errors)

### Steps To Reproduce

Show the Dataverse table "Sync Flow Errors".

se the invalid url in the column 'Flow Instance URL'

**Comment by manuelap-msft** [comment]
Hello,

this is retrieved from the Power Automate Environment variable and we expect the format to be put it as in our docs with the trailing / 
![image](https://user-images.githubusercontent.com/55705669/165944909-41f5a1be-0815-4a13-8371-9a8eaaab7d21.png)

The reason we can't auto-determine this is because government clouds have largely different URLs. Unfortunately environment variables don't support input validation, however I think we can do better here on our end and when we write this value check if the / exists or not and if not add it in. I'll add this to our backlog!

You'll have to update the environment variable to enter the / and then re-start all the sync flows as environment variables are cached and new values are only picked up if you toggle the flow off / back on. 

Thank you
Manuela

**Comment by manuelap-msft** [comment]
We will validate this in the Setup Wizard #3476 vs directly in the flow to ensure it's written correctly in the first place.
