### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unable to see permissions for SharePoint integrated power app (Access this App / Access this Flow)

### ISSUE THREAD

**Issue by powersd01** [microsoft/coe-starter-kit#2605]
### What is your question?

Hello,
In the CoE Power BI, for example, I notice in Apps, when I "Drill through - App Detail" a SharePoint Integrated PowerApp, unable to see Permissions. 
![SharePointIntegratedPowerAppsIssue](https://user-images.githubusercontent.com/47794763/165949341-7940a074-5a84-46a7-8f1f-5db53aed6d64.PNG)

### What solution version are you using?

Power BI version: 2.102.683.0 32-bit (February 2022)

**Comment by manuelap-msft** [comment]
Hello,

for SharePoint custom forms this is expected behaviour - they are automatically shared through SharePoint list permissions, see: https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/customize-list-form#administer-your-custom-form
![image](https://user-images.githubusercontent.com/55705669/165950900-90749227-ecad-4e6f-8594-578c309c54f5.png)

I'm not sure if Power BI supports hiding visuals based on a condition but we can look into that.

Manuela

**Comment by Jenefer-Monroe** [comment]
My recommendation would be to just add a flag on the top like we do in Set Permissions apps (ex not supported for Teams)
Tp explore with #2338

**Comment by Jenefer-Monroe** [comment]
Sorry I didnt mean you, I meant us. For our fix add a flag (a banner at the top of the page) when an app type we cant adjust is present.

**Comment by powersd01** [comment]
Thank you both Jenefer and Manuela!
