### ISSUE TITLE
[ALM Accelerator - BUG]: Failing while committing the Solution

### ISSUE THREAD

**Issue by NagulapallyLaxmanGoud** [microsoft/coe-starter-kit#2624]
### Describe the issue

Following the Bug Id : 2325 I have made the small change as suggested.

Changed
git clone -b "main" "https://github.com/microsoft/coe-starter-kit.git"
to
git clone -b "mochs-coe-cli-debugging" "https://github.com/microsoft/coe-starter-kit.git"
in the update-deployment-settings.ps1

Till yesterday (02-May-2022) I am able to deploy the solution to test after completing the pull request automatically, but it's not triggering solution to deploy into prod.

But today (03-May-2022) when I am trying to commit the solution from AA4PP app its failing. 

![ALM-CommitError](https://user-images.githubusercontent.com/99319322/166485185-28cf2988-ae79-49fb-86d2-015b013614a0.png)

So now I changed it back to

git clone -b "mochs-coe-cli-debugging" "https://github.com/microsoft/coe-starter-kit.git"
to
git clone -b "main" "https://github.com/microsoft/coe-starter-kit.git"
in the update-deployment-settings.ps1

Now commit is succeded.
Now I am also able to deploy the solution to test after completing the pull request automatically, but it's not triggering solution to deploy into prod.

I have changed the CI as enabled by editing the pipeline trigger (deploy-prod-SolutionName) before I merge the pull request, then I am now able to trigger both test and prod pipelines.

So, Is this the workaround I should follow or is there any new update that is coming in the new release to run (deploy-test-SolutionName) and (deploy-prod-SolutionName) pipelines automatically after pull request as approved and merged.

### Expected Behavior

deploy-prod-SolutionName pipelineshould trigger automatically without any manual configuration

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April 2022

### Steps To Reproduce

Click on the "Commit Solution" Button in AA4pp App,
Click on Processing icon --> Navigates to Azure Devops, 
See the error in the export-solution-to-git pipeline.

**Comment by mikefactorial** [comment]
@NagulapallyLaxmanGoud the branch in question mochs-coe-cli-debugging has already been merged to main in this PR (https://github.com/microsoft/coe-starter-kit/pull/2492) so the branch no longer exists and the workaround we were using in #2325 was only meant to be temporary while we were validating the fix. You should revert the change you made to use the latest from the main branch. 

For any pipelines that were generated automatically previously before the bug was fixed you have two options.

1. Delete the faulty pipelines and export your solution again to generate new pipelines in a working state
2. You can manually fix your deployment pipelines by updating the settings on the pipeline mentioned here https://github.com/microsoft/coe-starter-kit/issues/2548. These settings are under Triggers on the pipeline 
![image](https://user-images.githubusercontent.com/42348035/166503105-d30b24fb-dc1a-422b-a988-039ac7be131e.png)
