### ISSUE TITLE
Flow to delete an app

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#2702]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/2700

<div type='discussions-op-text'>

<sup>Originally posted by **ClaudiuVio** May 12, 2022</sup>
Hello,

I have 2 flows created to notify the users who have created a new app to fill out some data. After 2 weeks if the data is still not filled out the application should be deleted automatically

There is a way to achieve such a thing?</div>

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid we aren't staffed to assist with customizations of the kit. But what you are describing sounds a lot like the compliance flows we have made. The criteria is just different.
You may benefit from just hijacking that process and applying it to all apps instead of just ones identified as heavily used. 
Please see our documentation for more ideas:

- [Sample audit process](https://docs.microsoft.com/power-platform/guidance/coe/example-processes)
- [Component descriptions](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#compliance-processes)
- [Setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components)

I hope that helps
