### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Connection Reference not register the connection creator

### ISSUE THREAD

**Issue by rfolgadoal** [microsoft/coe-starter-kit#2707]
### Describe the issue

The flow Admin | Sync Template v3 (Apps) not registering the App connection creator. Is the maker that creates the app?

<img width="524" alt="FlowError-ConnectorReference-Apps(1)" src="https://user-images.githubusercontent.com/93584307/168099916-abfff9dd-2934-4ba7-964b-a72bdcefaf60.png">

In the flows the connection references are not registering either.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

**Comment by Jenefer-Monroe** [comment]
This information isnt available to us for individual objects. I think we thought it was at one point and started the work, which is why that is there. 
Note it has just become available at the envt level though (for the xtenant isolation work) and so we are working on that for June https://github.com/microsoft/coe-starter-kit/issues/2620

**Comment by rfolgadoal** [comment]
Thanks! I will track that question 👍
