### ISSUE TITLE
[CoE Starter Kit - QUESTION] Condition checks before updating risk assessment status in Developer Compliance Center

### ISSUE THREAD

**Issue by BhargavPrasadGorakanti** [microsoft/coe-starter-kit#2710]
### What is your question?

Hi,

Our team is currently on 2.13v of Governance module and plans to upgrade soon. We find the App description check useful as the app would go back to "Requested" state immediately when Admin | Compliance Detail Request flow runs again anyway.

Before considering any custom implementations, I wanted to check if there are any plans for potential future enhancements to the compliance form submission logic where app description becomes mandatory (again) in order to move to "Submitted" status. Posting as a follow-up question from this thread - https://github.com/microsoft/coe-starter-kit/issues/2303 

Also, would you consider adding a feature to let Makers update app description directly from Dev Compliance Center app?

![NonCompliant](https://user-images.githubusercontent.com/43746286/168115624-3b2932c0-c233-4355-ad03-56c0e754ef39.PNG)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.13

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by Jenefer-Monroe** [comment]
We had overwhelming feedback to remove all the requirements so we wont be going back on that part of the behavior. 
For augmenting it, I would recommend adding a separate flow rather than tweaking the existing ones, which detects the unfill fields when in this state and resets state (and mails users perhaps)

Please post the request for the ability to update description. We can consider it. I remember trying to make that work in the past and couldnt, but fresh eyes are always useful, and the product adds features all the time!

**Comment by Jenefer-Monroe** [comment]
[CoE Starter Kit - QUESTION] Update email content and recipients · Issue #2721 · microsoft_coe-starter-kit
