### ISSUE TITLE
[CoE Starter Kit - QUESTION] Update email content and recipients

### ISSUE THREAD

**Issue by anut12** [microsoft/coe-starter-kit#2721]
### What is your question?

I've set up COE in a DEV environment and updated production environment variable to 'No'. I also updated Admin eMail environment variable to Power Platform Admins group object ID. 

However, the emails are being sent to the app makers. How can I change the emails to be sent to Power Platform Admins group instead of the app makers. Is there a way to also update the email content?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.15

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Apps)

**Comment by Jenefer-Monroe** [comment]
Did you reset the flows after you updated the environment variable? 
Note that Power Automate caches values for environment variables and so you need to turn the flow off and back on in order to see the new value. 

Please see the note in our FAQ documentation:
https://docs.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
