### ISSUE TITLE
CoE Starter Kit version Core 2.1

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#2737]
### What is your question?

Where can I find the CoE Starter Kit that contains the Core components version 2.1?
Could you please tell me which month was it released in and is it possible to share with me the folder that contains the solutions from that version?

Thank you in advance!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1

### What app or flow are you having the issue with?

N/A

**Comment by Jenefer-Monroe** [comment]
If you go to [releases](https://github.com/microsoft/coe-starter-kit/releases) for the kit you can go and expand the "Assets" node to see what version shipped with that release
![image](https://user-images.githubusercontent.com/89584709/168639505-f02da9bc-da47-4b73-a6c6-c7d5b5d0d75d.png)

It appears that Core 2.1 is too old to even track though, must have been from before we switched our repository, which means its older than May 2021.

**Comment by LizethRegules** [comment]
Yes, I went through the Assests and only got till May 21 which has 2.1.6. So, do you think it is possible to get version 2.1?

**Comment by Jenefer-Monroe** [comment]
I don't think we have a copy of that anymore. Can I ask why you need it? Perhaps there is some other way to address your needs.

**Comment by LizethRegules** [comment]
I'm upgrading to latest version of the kit and wanted to try in a test environment what could happen during the upgrade before actually upgrading in my coe production environment. But if you do not have it, that is fine. I guess I'll just have to be more careful while doing it.

**Comment by Jenefer-Monroe** [comment]
Upgrade from that age is almost certain to not work. What aspects of the kit are you using? Your best bet is likely a new environment entirely so asking to make sure I can give you good advice.

**Comment by LizethRegules** [comment]
Mainly using core and governance components. 
Could you tell me what are the reasons of the upgrade most likely not working if being upgraded 1 year after?

**Comment by Jenefer-Monroe** [comment]
Approximately June of last year there was a product change that required we reset a bunch of environment variables and it led to lots of upgrade issues. We spent a bunch of time when this occurred walking people through how to fix this up, but are no longer able to go back and do that due to funding. 

We recommend you upgrade at least every 3 months in order for us to be able to assist. Please see [installing upgrades](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

Note that if you want to try upgrade you should be able to create a backup which you could install on a new environment, and then try upgrade there. 
![image](https://user-images.githubusercontent.com/89584709/168656466-a1aa7b53-4ce6-4b6e-baca-44d21f69496b.png)

I hope that helps

**Comment by LizethRegules** [comment]
Thank you, this is really helpful! Closing this now. :)
