### ISSUE TITLE
[ALM Accelerator - BUG]: Issue importing the CenterofExcellenceALMAccelerator solution

### ISSUE THREAD

**Issue by ChrisS-nova** [microsoft/coe-starter-kit#2739]
### Describe the issue

Whenever me or any of my team tries to import any of the releases for the CenterofExcellenceALMAccelerator solution they are given this message, "The dependent component Workflow (Id=9f6a2a7b-4e00-ec11-94ef-000d3a199bfb) does not exist. Failure trying to associate it with CanvasApp (Id=4af7a6a0-bfb9-4903-ab2a-008dcb522b62) as a dependency. Missing dependency lookup type = PrimaryKeyLookup."
We were able to import the solution with no issues as of Wednesday May 11th. I have tried to do a solution upgrade but that still doesn't seem to solve the problem.

A screenshot of the solution import history will also be attached to this issue as well as the solution zip file that successfully deployed to a power automate environment on the 11th
![SolutionHistoryScreenshot](https://user-images.githubusercontent.com/100228148/168692329-0a0e760c-9741-474d-9bcf-eb0e5b721f41.png)
[CenterofExcellenceALMAccelerator_1.0.20220511.1_managedSuc.zip](https://github.com/microsoft/coe-starter-kit/files/8703781/CenterofExcellenceALMAccelerator_1.0.20220511.1_managedSuc.zip)

### Expected Behavior

That it successfully imports to our environment

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220503.1

### Steps To Reproduce

1. Download the attached zip file
2. Go into any environment where the solution does not exist
3. Import the solution zip file
4. Wait for the deployment to fail and return the specified error

**Comment by mikefactorial** [comment]
Hey @ChrisS-nova, this just cropped up recently due to a change in the platform. We're aware of the issue and have a fix for it in the June release, but unfortunately, there's no work around at the moment. The specific issue is that we had a deleted flow in our canvas app for a while that the import process just ignored previously, but there was an update recently (since the may release) that exposed this issue. Will discuss internally how we might be able to work around this in the short term but you may have to wait for the June release. Tagging a couple of people @jenschristianschroder @rsantos00 @devkeydet

**Comment by mikefactorial** [comment]
@ChrisS-nova this is resolved in the May Hotfix release here https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2022-HF1. Thanks for the feedback. This ultimately was a platform change that exposed an issue in some of our apps.
