### ISSUE TITLE
[CoE Starter Kit - BUG]: 'App Deleted field' Shows 'No' where as we have data for 'App Deleted On' field

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#2775]
Hi Team,

We are using CoE Starter kit in our tenant and using the 'Power Platform Admin View' Model Driven App we monitor the Apps and Environments.

We could see that for the apps that are deleted, the field 'App Deleted' shows the value 'No' where as the field 'App Deleted On' have the deleted timestamp.

Attaching a sample screenshot below.

![image](https://user-images.githubusercontent.com/33513504/169270840-9dcb108c-843c-4ac3-94d4-0105fa7f4227.png)

Could you please help here.

Thanks,
Tom

**Comment by Jenefer-Monroe** [comment]
We do clear the deleted on Date when we note an object is re-instantiated. So we'll need more information to investigate.
![image](https://user-images.githubusercontent.com/89584709/169307898-744a1b3c-f0cc-4e49-8752-97899ce92936.png)

1. Is the object actually deleted? In other words is the "No" incorrect? Or the date stamp? 
2. How many objects are in this state? And what type? (ex just a few canvas apps?)
3. What version of Core are you running? 
4. Do you know the history of the object? Was it deleted in the past?

**Comment by Jenefer-Monroe** [comment]
Gotcha. Your version is about a year old, and we have done a ton of work in the meantime on this area, including work to unmark areas that were incorrectly marked deleted in the past. 

You will need to be on current builds in order to have this work, and in order to receive assistance here. 

Unfortunately upgrade from that old a build is not likely to work, and a clean environment is likely necessary. Note that we recommend upgrade at least every 3 months as that is how far back we test. 

Can you please tell me what you use the kit for? What solutions? 
Do you just use us for inventory? And do you use the Audit Logs solution? 
That will help me advise you on how to get into a good state.

**Comment by AUTigers16** [comment]
I have an issue that is related to the App deleted field showing no and the App Deleted on field does have a date, but I don't want to derail this reported bug. Should I create my own bug?

**Comment by Jenefer-Monroe** [comment]
Assuming you are on a more current build then its most certainly something different, so please do post separately.

**Comment by marioalecosta** [comment]
We use it for governance, following the growth in usage of our power platform features in the tenant. And with the information from apps and flows, we added DLPs and requested training from the makers, and we use audit Logs solution.

![image](https://user-images.githubusercontent.com/13107941/170071047-a1c323ff-cb37-486f-b511-3cde31fe13d0.png)

**Comment by Jenefer-Monroe** [comment]
ok unfortunately migration to a new environment will not be easy then. 

People have succeeded at cleaning this situation up but it requires you manually go and find each problem and fix it manually, for example if it says some connection reference is missing in the new version of core, you go find that in your current solution and remove it. 

I'm afraid this is not something we are staffed to assist with. 

Once you get it fixed up though, upgrade at least quarterly and you can then come here for assistance.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
