### ISSUE TITLE
Request Orphaned Objects Reassigned (Child) Flow Customization

### ISSUE THREAD

**Issue by mrramosjr21** [microsoft/coe-starter-kit#2832]
### What is your question?

I'm trying to copy and create a new file for the **Request Orphaned Objects Reassigned (Child) flow** for our changes in email. I noticed in the switch case  > Case See Each > "If app not timed out" = Yes > Switch app submitActionId > AssignItIDone > Switch on ToWhom lookup - app > 200 Success.

I can't add an action in the Condition for "Let them know if it succeeded - assign app toWhom"
![image](https://user-images.githubusercontent.com/20808214/170239782-a31008c6-1ee1-4efb-9f03-14cbee998b6e.png)

This is the Actual flow
![image](https://user-images.githubusercontent.com/20808214/170239959-9df2847a-89d0-4818-8e36-15999a77b3ea.png)

I'm just creating a new flow same as the original Request Orphaned Objects Reassigned (Child).
I think the problems only appears in the **200 Success Switch case**

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.15

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child) Customized

**Comment by Jenefer-Monroe** [comment]
I'm afraid I cannot help you here as we are not staffed to assist with customizations. I have a few ideas I can offer but otherwise I'm afraid I can't help as you seem to have run into some issue with the flow product's editor specific to your case. 

- I know there is some limit on the number of nests you can do, so if you added conditions above you may have hit it. Though I thought there would be an error not a no op. 
- You may have hit some bug in the editor that can be fixed by refreshing. (just save close reload)
- You may have hit some intermittent service issue and just waiting would help. 

Sorry that I cannot more clearly advice here. 

Might I ask, why are you rewriting this? What feature are you wanting that isnt there in our shipping version?

**Comment by mrramosjr21** [comment]
I see, but in you original flow "**Request Orphaned Objects Reassigned (Child)**" there an action button there? How come when I tried to re-create and did the same nest. I countered this error?

Another thing before I did this re-creation of the flow. I tried copying the flow via clipboard. But after updating the connections I have encountered a problem in the conditions and switch objects.
![image](https://user-images.githubusercontent.com/20808214/170629579-91e2416a-77e4-4856-bfec-e1748fb10bba.png)

This didn't appear when I manually create it. but encountered the nested error there.

**Comment by Jenefer-Monroe** [comment]
Sorry I don't know why you are hitting those errors with the editor, again we are not staffed to help with customizations of the kit. 

If you let me know why you are re-creating the flow, if there is some small change you are hoping for, we might be able to incorporate is so that you and others benefit. And then you would not need to go through this work.

**Comment by mrramosjr21** [comment]
I already found a solution on this error.
I just created an Object below the Condition.
![image](https://user-images.githubusercontent.com/20808214/170934585-a581870b-ce55-48ac-b633-b1d9b2e099e1.png)

after the creation. I dragged it to the YES/NO condition.
