### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Variables Description is blank during import

### ISSUE THREAD

**Issue by NikoAppSphere** [microsoft/coe-starter-kit#2834]
### Describe the issue

When we import the core components the descriptions field are blank. Tried on two different computers and chrome&edge.

![image](https://user-images.githubusercontent.com/98519819/170272398-f9d29e11-49d6-4489-8add-520c947ef397.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Import

### Steps To Reproduce

Import the core solution into enviroment

**Comment by Jenefer-Monroe** [comment]
We dont repro this so there is likely some service issue impacting your tenant or data center. 
![image](https://user-images.githubusercontent.com/89584709/170276056-b56ca955-8da9-452a-a9f8-7aacffa6a60e.png)

If it continues to repro please test with some non-CoE related solution so that product support can assist.

**Comment by NikoAppSphere** [comment]
We imported now without filling in the environment variables. We now have set them using the command center app.

No problem, right?

**Comment by Jenefer-Monroe** [comment]
You may have to turn flows that were on when you imported off and back on to get the values, but otherwise you should be fine.

**Comment by NikoAppSphere** [comment]
Ok thats what i already had in mind! Thank you.
Closed!

**Comment by Jenefer-Monroe** [comment]
Glad you are covered, thanks for using CoE
