### ISSUE TITLE
[CoE Starter Kit - QUESTION] PBI : We cannot convert value null to type Text

### ISSUE THREAD

**Issue by kbirstein** [microsoft/coe-starter-kit#2845]
### What is your question?

My client can't access data in the Power BI report. We have installed the Production version, his generic service account has all rights to the Dataverse database in the COE environment we created (System Admin and System Customizer) and we have ascertained in the Solution that there is data in the "PowerApps App" table and the Sync Template v3 flow is running but when we try to apply changes in the Power BI Desktop template we get the following errors and the data will not load. I've installed the COE for about 7 clients now and I've never seen this issue.
![PowerBI_Screenshot2](https://user-images.githubusercontent.com/13750516/170491993-672a55e6-1fbb-4f44-9be8-98b212ab7e26.jpg)
![PowerBIError_Screenshot1](https://user-images.githubusercontent.com/13750516/170492001-b2af40cd-1a9f-4138-bba7-fc2b88937826.jpg)
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2022

### What app or flow are you having the issue with?

Power BI Template

**Comment by manuelap-msft** [comment]
Oh wow, that's a first for me as well! Not seen this issue before. Are they on the latest version of Power BI Desktop?

**Comment by Jenefer-Monroe** [comment]
Can you also please clarify what you mean mean by this? 
` but when we try to apply changes in the Power BI Desktop template`

**Comment by BreakPointAtLine0** [comment]
Hello Everyone...

Seeing the **exact same issue** when connecting Power BI Desktop using the **Template "Production_CoEDashboard_May2022.pbit"**.  Saw that it has been just raised few days ago. So, just adding a comment rather than raising a new one.

**Power BI Desktop version installed.**
~~~~~~~~~~~~~~~~~~~~~~
Release: May 2022
Product Version: 2.105.664.0 (22.05) (x64)
~~~~~~~~~~~~~~~~~~~~~~

**Attached Files:**
1)- The extracted contents of the COE Starter Kit Zip. (So that the version is known)
![COE Kit Contents](https://user-images.githubusercontent.com/31046558/170944806-85a7c9bf-1114-4cd8-8a47-35d614eed927.JPG)
2)- Screenshot of the issue that comes up initially: Please see the messages. They are all same, except for one.
![Current Issue 01](https://user-images.githubusercontent.com/31046558/170946183-2b2ad05f-8f90-4090-82cf-d30ff4e01493.JPG)
3)- Screenshot of the issue that comes up after trying to "Apply Changes": (The button that comes up along with "Discard Changes" within that Yellow band on top. Please see screenshot.
![Current Issue 02](https://user-images.githubusercontent.com/31046558/170946270-7644f414-fc55-4575-a01c-33b13d95101c.JPG)

Thanks for help!

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of the solutions in your environment so that we can validate the CoE solution installed?
And plase also validate you are on the latest version of Power BI Desktop.

**Comment by BreakPointAtLine0** [comment]
> 
Hello Jenefer,
Thanks for response.
Below is the Screenshot of the **Solutions listed in the same Environment where we have installed the COE Starter Kit** in our Tenant.
We have installed the below Power BI Desktop version:
Release: **May 2022**
Product Version: **2.105.664.0 (22.05) (x64)**
Thank you for your help.
![COEStarterKit-Solutions](https://user-images.githubusercontent.com/31046558/171185179-451bd85c-58e1-4543-93c1-2da9c59e8efd.JPG)

**Comment by Jenefer-Monroe** [comment]
Unfortunately we still don't repro. Will leave open for a bit to see if others in the community have ideas.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
