### ISSUE TITLE
[ALM Accelerator - QUESTION] How to create profile when you import solution from other place

### ISSUE THREAD

**Issue by last72** [microsoft/coe-starter-kit#2856]
### What is your question?

I was able to import solution from DevOps Repo (that I created and exported). Now I am trying to import solution from Powerapps creator kit. It asks me to select a profile but the profile is blank. Do I need to use profile from other solution or do I need to create from admin app (model driven app)?

Creator kit: https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/overview
![image](https://user-images.githubusercontent.com/30095306/170859781-4757e558-a4d5-4851-80db-c8d9a872101e.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220517.1

**Comment by jenschristianschroder** [comment]
Hi @last72,

The ALM Accelerator Import feature can only be used to import solutions from Azure DevOps Git source control.

In order to import the Creator Kit, you should follow the instructions here: https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/setup#install-the-solution 

The instructions mentioned in link are high level. Here a bit more detailed steps to import the Creator Kit

1. You need to download the Creator Kit solution zip file to your hard drive
2. Got to make.powerapps.com and select the environment in which you want to import the Creator Kit 
3. Click Solutions in the left hand navigation menu.
4. Click import solution in the main ribbon
5. Select the solution zip file you downloaded in 1

**Comment by last72** [comment]
Hi @jenschristianschroder. Thanks for the comment. I am able to import the Creator Kit to my environment without any issue.

I am trying to contribute to the Creator Kit repo. To do that, I need to import the solution unmanaged but the file from your link is managed solution.

See screenshot below
![image](https://user-images.githubusercontent.com/30095306/171199783-0d8e15f4-98cf-4c88-aa62-c90ab9e12cec.png)
![image](https://user-images.githubusercontent.com/30095306/171199879-9cf49e82-40e2-43d4-ae5e-d48648a6313b.png)

**Comment by mikefactorial** [comment]
@last72 the unmanaged solution is shipped with the release along with the managed solution

https://github.com/microsoft/powercat-creator-kit/releases/download/CreatorKit-May2022/CreatorKit-Unmanaged.zip

![image](https://user-images.githubusercontent.com/42348035/171642901-af72c607-471a-4c68-b4fb-556513b51aa9.png)

**Comment by last72** [comment]
@mikefactorial Thanks, I didn't saw the release included unmanaged solution file.
