### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Audit Log solution only reflects the operation 'LaunchPowerApp' in Audit Logs

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/coe-starter-kit#2857]
### Describe the issue

Audit Log solution only reflects the operation 'LaunchPowerApp' in Audit Logs in the Power Platform Admin View App

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by manuelap-msft** [comment]
That's expected behaviour. We do not store other Audit events. We only store LaunchPowerApp to provide insights into unique users and sessions over time in the Power BI dashboard, and the Last Launched Date in the Power Apps app table.

What other events were you expecting to see there and how would you expect to use them in the CoE?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
