### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flow Action Details) errors

### ISSUE THREAD

**Issue by cr0max** [microsoft/coe-starter-kit#2872]
### Describe the issue

Several errors with the flow - Admin | Sync Template v3 (Flow Action Details) 

The error WorkflowOperationParametersRuntimeMissingValue appears on all those failed flows and this happens every day.

![image](https://user-images.githubusercontent.com/97740538/171169390-0ebd341a-95a7-42a9-b587-c6bd337d4b0d.png)

Do you know what this is and how to correct it?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2022 v3.38

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

**Comment by Jenefer-Monroe** [comment]
In your failing flow, please open the trigger and look for the flow environment value. Is there one present? 
![image](https://user-images.githubusercontent.com/89584709/171194563-9ea27f51-215f-419e-8990-67729fad528b.png)

**Comment by cr0max** [comment]
No there is no environment value.
But it has a deleted value and date, so I guess thats why it is failing. It does not exist anymore.
![image](https://user-images.githubusercontent.com/97740538/171207385-25873cec-1941-4d1d-b789-7ecd309e06ce.png)

**Comment by Jenefer-Monroe** [comment]
Aw ok, thanks for investigating! 
In the June release we have changed the trigger so that it will only trigger when a particular field is modified. So I believe that will resolve for your case as well. 
https://github.com/microsoft/coe-starter-kit/issues/2749
![image](https://user-images.githubusercontent.com/89584709/168852369-382b60af-196d-4777-937b-7e34a4eac58c.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
