### ISSUE TITLE
[ALM Accelerator - Feature]: Ability to select different repository when import

### ISSUE THREAD

**Issue by last72** [microsoft/coe-starter-kit#2877]
### Is your feature request related to a problem? Please describe.

Currently you cannot import solution from other DevOps repo than you initially selected.

Under Solution Source (which shows branch), it only shows branch for the initially selected repo. 

### Describe the solution you'd like

Can we change the repo to be imported at this stage?

![image](https://user-images.githubusercontent.com/30095306/171206931-286bec69-9de9-4ddb-a17f-e14f66204478.png)

### Describe alternatives you've considered

Another dropdown to complete the hierarchy [DevOps Org - DevOps Project - Git Repo - Branches - Solution (folder)]

![image](https://user-images.githubusercontent.com/30095306/171207384-413f5056-9daa-4e09-a90a-c4bf7021328b.png)

### Additional context?

contribute to the creator kit repo

**Comment by mikefactorial** [comment]
@last72 this has been open for a while. Currently, the solution to this issue is to create a deployment profile to select from in the first drop down which has the project and repo already specified. Assuming that's a workable solution . The ask here may be to show the details of profile e.g. Project, Repo correct or am I missing something? Thanks!

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here for now.
