### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Request app does not work

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2891]
### Describe the issue

Hi Team,

As I review the environment request app (Core 3.38) - after creating the request by submitting the form, It does appear in the pending view. Would you please share where the request is being stored and what is the process flow? to whom it gets notified? 

I see under connection there is no Microsoft data verse connection is missing:
![image](https://user-images.githubusercontent.com/98403757/171402861-7318f437-d9e4-4f14-bddd-3a2f93156d08.png)

Thanks,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

environment request app

**Comment by denisem-msft** [comment]
Hi @tomsinsight 

The Environment Creation Request is a record in the Dataverse table that is installed in the Core components. The related connectors for the request are stored in a Many to many relationships between the Environment Creation Request record and the PowerApps Connectors records. 

The screenshot you shared appears to be the 'Maker - Environment Request' canvas app's details list, on the connectors tab that the app itself uses. You should be able to open the 'Admin - Environment Request' canvas app and view the details of the Environment Creation Request and see the requested connectors in the cards on the right side of the screen. That is displaying the records in the many to many relationships easily.

Since this was more of a question and not necessarily a bug, I will close this for now. Please feel free to reopen if I didn't sufficiently answer your question!
