### ISSUE TITLE
[CoE Starter Kit - BUG] App Description missing from Cleanup Old Objects App and typo for Maker - Command Center

### ISSUE THREAD

**Issue by diego-coke** [microsoft/coe-starter-kit#2914]
### Describe the issue

We can't see CoE Starter Kit Apps description in the App Catalog

### Expected Behavior

We should see the app description in the App Catalog:

![image](https://user-images.githubusercontent.com/83843163/171738721-80aeaa13-fcaf-4870-b024-184e51343ef5.png)

We can see it for custom apps but not for the CoE Starter Kit Apps, we already checked and the description is visible if we try to edit the CoE Starter Kit Apps

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

N/A

**Comment by Jenefer-Monroe** [comment]
I don't repro this, and it looks like you are on an old version of the app. Perhaps you forked a copy of it or have unmanaged layers on the app. Here is what the app looks like in 3.39

![image](https://user-images.githubusercontent.com/89584709/171861514-f1f188a0-e2dc-4925-84ef-4b3471ce1a32.png)

If you need help understanding unmanaged layers please see [Remove unmanaged layers from inventory flows](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) section of the [Updating the Center of Excellence (CoE) Starter Kit](https://docs.microsoft.com/power-platform/guidance/coe/after-setup) documentation.

**Comment by diego-coke** [comment]
Hi Jenefer,

You were right there was an unmanaged layer but I already delete it and it's the same, the app is looking like yours but it's not pulling the descriptions:

![image](https://user-images.githubusercontent.com/83843163/172191528-2f0e48a3-3774-422d-83f1-3f5623b27a26.png)

We are running version 3.39 of the core components:

![image](https://user-images.githubusercontent.com/83843163/172191660-520791ad-93e7-47a8-9db8-38d52719cf63.png)

**Comment by Jenefer-Monroe** [comment]
I wonder if its because we added the description after you install the kit, and since you dont edit these apps the new values for the description doesnt get added. Lets try with one of these. 

### Make a change
1. Go to CoE envt > Apps > Maker - Command Center (as an example) > Edit
![image](https://user-images.githubusercontent.com/89584709/172225202-faf623d8-a2f7-4615-bfed-b6e7d400d6fe.png)

1. File > Settings > Is there a description present? 
![image](https://user-images.githubusercontent.com/89584709/172225621-29184639-3305-4522-8f02-cf56b701f98e.png)

1. If so, then its the inventory not being updated. Insert a new blank screen (just to make a change that wont disturb users)
![image](https://user-images.githubusercontent.com/89584709/172225911-639127c2-bbec-43ee-85ee-c0c2a374ed2d.png)

1. Save, Publish, and Close 

### See if fixed
1. Wait for the inventory to run tomorrow and see if this is resolved in the App Catalog
1. If so, you'll need to do this for the other apps too in order to re-inventory them. 

### Cleanup
Once done, you'll need to cleanup the app so that its back to managed and we can update going forward
1. For each of the apps you do this with, go to its solution > apps > See solution layers
![image](https://user-images.githubusercontent.com/89584709/172226718-1815436c-4e02-4b8e-a192-7cc0d06d993c.png)
1. Remove the unmanaged layer
![image](https://user-images.githubusercontent.com/89584709/172227268-c535f607-4d97-46c0-ab8c-903a19111cdc.png)

**Comment by diego-coke** [comment]
That worked :)

Just FYI the Maker Command Center app has the wrong description:

"Command and Setup Center for **Admins** to navigate to other CoE Starter Kit resources" should say Makers, right?

**Comment by diego-coke** [comment]
And the Cleanup Old Objects App doesn't have a description :)

**Comment by Jenefer-Monroe** [comment]
Thanks for the catch on typos and missing description! Will shift this bug to track updating those two for July.

**Comment by Jenefer-Monroe** [comment]
- [ ] Update **_Maker - Command Center_**
- [ ] Add **_Cleanup Old Objects App_**

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
