### ISSUE TITLE
[CoE Starter Kit - BUG] Where can I find the quick view of every feature/fixes being released with each version?

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2966]
### Describe the issue

Hi Team,

As I look up the release notes, it shows all the list of bug fixes which are done, however I was looking for the quick summary view about new features/fixes - is there any document link for the same that you can refer?

Looking forward to hearing from you!

Thanks,

### Expected Behavior

quick summary view about the latest release

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

documentation

**Comment by manuelap-msft** [comment]
Hello,

you can see all the bugs and features addressed with a release here: https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-June2022 but we don't have a quick version of them and it's not part of our documentation. 

We are looking to structure the change log better instead of it being long list, have it structured in this way:

# CoE Starter Kit
## Bug fixes
- bug 1
- bug 2
## Features
- feature 1
- feature 2
# ALM Accelerator
## Bug fixes
- bug 1
- bug 2
## Features
- feature 1
- feature 2

That is currently on our backog here https://github.com/microsoft/coe-starter-kit/issues/2170 and should make the release notes more readable. 

Thank you
Manuela
