### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to connect to Org URL in PowerPlatformGovernance_CoEDashboard_202206.pbit

### ISSUE THREAD

**Issue by HMJ-Somerset** [microsoft/coe-starter-kit#2988]
### Describe the issue

June 2022 release installed in D4T environment
Opened **PowerPlatformGovernance_CoEDashboard_202206.pbit** and entered org URL when prompted.
(This is the same Org URL successfully used to connect to data in the Teams_CoEDashboard-May2022.pbit Power BI template.)
The connection defaults to http:// which causes the error message invalid_resource|AADSTS500011: The resource principal named http://... was not found in the tenant named <Directory ID>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Previous .pbit files have defaulted to https://

When prefixed by https:// you are prompted to sign in.  When you then click connect, the wheel spins and you go back to "you are not signed in".  This results in a never ending loop of signing in, connect, sign in, connect etc.

I can make a manual connection to the Dataverse tables with no error
Does this report only work with a production environment?
I first logged as a Power BI issue but after screen share session with Microsoft support was advised to raise this as a bug here

### Expected Behavior

I expected to connect to the data source and the data loaded into the desktop file

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard_202206.pbit

### Steps To Reproduce

1. Open PowerPlatformGovernance_CoEDashboard_202206.pbit
2. enter org URL
3. sign in
4. error

**Comment by HMJ-Somerset** [comment]
Read further into documentation and found that only works in production environment
[https://docs.microsoft.com/en-gb/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use]

**Comment by kashanico** [comment]
@Jenefer-Monroe I am facing the same issues. Using a production environment. This issue looks to have started with the May Power Bi Dashboard release.
![image](https://user-images.githubusercontent.com/64927104/176017790-9feee681-8a68-4081-8a83-2004faeee758.png)


As referenced by another user here: https://github.com/microsoft/coe-starter-kit/issues/2617
The instructions are to enter the URL without https:// or http://, then Power BI Desktop will default to http. But now this fails which complains about it not being found in the tenant. Perhaps because http access has been disabled recently?

If I follow the suggestion in the other thread and force https:// I still get errors
![image](https://user-images.githubusercontent.com/64927104/176017355-0613ec30-fc7c-421b-88d4-bb513bb4acef.png)

If I follow the official instructions and enter without any https/http I get the following error.
![image](https://user-images.githubusercontent.com/64927104/176017875-f8454c98-10bf-4707-85d2-ae7cf9ab8459.png)


This looks to be an issue with how this is authenticated via http. Please advise.
