### ISSUE TITLE
[ALM Accelerator - BUG]: Activate Flows For Component Owners

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/coe-starter-kit#2991]
### Describe the issue

When deploying the step Activate Flows for Component Ownership is failing with the error message:

The user details for tenant id 'TENANTID' and principal id 
'PrincipalId' doesn't exist

### Expected Behavior

I'm not exactly sure what this is doing anyway as my flows are activated in the previous step (Activate Flows for Connection References).  

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Latest

### Steps To Reproduce

I don't think we have anything special in our environment as this is an OOB deployment.  

The only way to work around the error is to deploy the flows with activate = false

### Anything else?

![image](https://user-images.githubusercontent.com/1624416/173442746-bfc20b84-b987-4d8f-bb03-892a38626ed0.png)

**Comment by jenschristianschroder** [comment]
Hi @rfarris2000,

Is the user configured for activating flows synchronized to the target Dataverse environment? You can check that from https://aka.ms/ppac by navigating to the target environment and selecting users on the right hand side

**Comment by rfarris2000** [comment]
@jenschristianschroder The user is an application user that is synced to the target environment and is listed as a System Admin.

**Comment by jenschristianschroder** [comment]
Hi @rfarris2000,

I have tested this and can reproduce the behavior you describe.

The issue seems to be the result of trying to activate flow with an Application User.

Can I ask why you want to activate with the flow with an Application User rather than a normal user?

Have you also set the Application User as the owner of the flow and does the Application User also own the connections in the flow?

**Comment by rfarris2000** [comment]
@jenschristianschroder 

1) The owner is correctly is set to the Application User but the activation fails as you mentioned.
2) I guess why wouldn't I want the owner to be an Application User?  Is there a downside to it?
3) The application User owns the flow but does not own the connection or have it shared with them.

I'm happy to discuss further offline if you need screenshots in case there is any sensitive data.

**Comment by devkeydet** [comment]
The whole workaround that exists in the Accelerator is because flows cannot be activated by App Users today when using connections the Application User doesn't have permission to.  That's because App Users do not have permissions to connections today.  Therefore, when a Flow owned by an App User is turned on in this scenario, it will not succeed.  There is ongoing work in the platform to enable this scenario.  This is not a bug in the Accelerator.  It is how the service works today.  You can only turn the Flow on as regular user in this scenario.  So, the user you use for impersonation cannot be an App User today. 
 Not for this particular scenario.  Once the platform improvements materialize, we will remove the workaround.  Until then, you must impersonate a regular user to turn on the flow, not an App User.

**Comment by rfarris2000** [comment]
@devkeydet I can share the connection with the app user.  Would that be a workaround?

**Comment by devkeydet** [comment]
Not today.  There is ongoing work in the platform to enable this.

**Comment by devkeydet** [comment]
See: https://github.com/microsoft/coe-starter-kit/issues/3014
