### ISSUE TITLE
[CoE Starter Kit - QUESTION] Help with upgrade

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#2998]
### What is your question?

Hello.  I am trying to uninstall an old version of the COE, version 1.0.0.61, where all of the components are in one solution.  It is showing a dependency on the Apps table required by 'My Flow'.  I cannot identify this flow and therefore cannot delete.  Can you assist please?  Thanks.
<img width="853" alt="COE_dep_error" src="https://user-images.githubusercontent.com/45642255/173900036-f7a0f50c-f00c-4551-8fd5-8dd6424ff0e9.PNG">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.0.61

### What app or flow are you having the issue with?

N/A

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are not staffed to assist with upgrades this old. However, hopefully if this is the only issue, you can just delete the flow and be good. 

I believe the flow will be in the CoE environment since its using the table, but you can confirm if you use the Power Platform Admin View app:
![image](https://user-images.githubusercontent.com/89584709/173935087-3d83f223-d876-4600-8d15-fbb8de44c7be.png)

And while you are there you can get the flow GUID (name)
![image](https://user-images.githubusercontent.com/89584709/173935870-19a0a1b8-4a42-4bc5-9f4e-a25e9481897b.png)

And then you can delete it using the **_Remove Flow as Admin_** action

To get the envt (GUID) name
![image](https://user-images.githubusercontent.com/89584709/173935600-d6b67c51-a126-4e2c-b716-526e34d375e2.png)

Then to delete
![image](https://user-images.githubusercontent.com/89584709/173935316-8340932f-f1f4-47d9-aa03-9944902a2c99.png)
![image](https://user-images.githubusercontent.com/89584709/173936283-434d5c59-ecfb-445e-82ed-c3b02ef259c2.png)

I hope that helps!
