### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template V3 error

### ISSUE THREAD

**Issue by eddwr1** [microsoft/coe-starter-kit#3002]
### Describe the issue

We are experiencing a recurring issue with the cloud flow "Admin | Sync Template V3" that causes it to fail.

![image](https://user-images.githubusercontent.com/97225231/174044865-db3de814-5806-49c4-968f-d34cc0809e4a.png)

The error occurs at the following step in the flow:

![image](https://user-images.githubusercontent.com/97225231/174043937-4c013061-2671-4308-8cce-c5e2dc014fa8.png)

![image](https://user-images.githubusercontent.com/97225231/174044093-db7945ac-87a2-4a92-b28b-4c3af77b78ad.png)

![image](https://user-images.githubusercontent.com/97225231/174044207-7639bd82-2096-421d-9f0d-9ca1171b5086.png)

When searching the environment's ID (170ed0cd-e8b4-48bd-a82c-4c0f0e0cf84a) in Power Platform Admin Center it returns no result, so it may be an environment that was created and removed without cleanup.

### Expected Behavior

Flow should run successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

 Admin | Sync Template v3

### Steps To Reproduce

1. Visit https://make.powerapps.com/
2. Select correct environment
3. Open Center of Excellence - Core Components solution
4. Select Cloud Flows and open "Admin | Sync Template V3"
5. View flow history

**Comment by Jenefer-Monroe** [comment]
The failure you have highlighted is caught. Its there to indicate if the envt is already inventoried or not. The flow is failing lower down where you see the second red failure indicator. 

However, since you already did the investigation to look into this envt id, we dont need to do that now. 
It sounds like you have hit a product bug. Can you please import and run this flow to see if it repros for you?
[Getenvtfailuresforenvtreturnedfromgetenvts_20220616130525.zip](https://github.com/microsoft/coe-starter-kit/files/8919046/Getenvtfailuresforenvtreturnedfromgetenvts_20220616130525.zip)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
