### ISSUE TITLE
[ALM Accelerator - BUG]: Run Solution Checker getting failed

### ISSUE THREAD

**Issue by shree2905** [microsoft/coe-starter-kit#3063]
### Describe the issue

Running the "Build Deploy Validation" pipeline when the "Run Solution Checker" step crashes.

![image](https://user-images.githubusercontent.com/79618656/175915751-d2152c42-bea1-43ad-b4da-6e5c7199b422.png)

The validation pipeline is getting failed due to "##[error]Exceeded the max wait. Try running again with an increased SecondsBetweenChecks and MaxStatusChecks." this reason. 

This solution consist of below objects. Can't really figure out what's wrong with my solution. 

![image](https://user-images.githubusercontent.com/79618656/175916268-68c63788-2836-4477-aac7-038c016a1f36.png)

I downloaded the SolutionPackage file from the Azure Repo branch and then used Power Platform CLI to package the solution and run solution checker on both managed and unmanaged solution. It worked without the error.

![image](https://user-images.githubusercontent.com/79618656/175916889-4b7771e0-09c4-4a79-b84c-3c2b0ac83eff.png)

How can I increase the timeout limit for SecondsBetweenChecks and MaxStatusChecks variable. Is there other way to solve this issue?

_Thank you in anticipation_ 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April 2022

**Comment by mikefactorial** [comment]
Hey @shree2905, thanks for reporting this. The solution checker task is something that we don't have any control over in the Accelerator. This question would be better addressed to the product team via a support request perhaps. That being said you can disable this check in the pipelines by setting DisableSolutionChecker variable, either in a global variable or at the pipeline level by setting the value to 'true'. The fact that you can run the solution checker through the CLI without a problem would be good to bring up to support since we are using the same APIs to run the checks in the pipelines.

**Comment by mikefactorial** [comment]
We were seeing some slowness in the Solution Checker in our July testing several days ago so this may have been a service issue at the time. We have created a backlog item to make the specified parameters configurable in a future release #3087. Closing this out for now as there's nothing more we can do on this issue.
