### ISSUE TITLE
[CoE Starter Kit - BUG] Error 500011, authentication with Power BI Dashboard 

### ISSUE THREAD

**Issue by TetefBubu** [microsoft/coe-starter-kit#3080]
### Describe the issue

Hi,

Using Production_CoEDashboard_May2022.pbit file, after authentication step, we have this error: 

invalid_resource : AADSTS500011: The resource principal named http://orgbf7d2e88.crm12.dynamics.com was not found in the tenant named GRTgaz. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: a26cc920-6cdf-4149-9a1c-1cbce51f3600
Correlation ID: 94198436-4dbf-4182-9813-00ded323f802
Timestamp: 2022-06-29 09:31:36Z.

Thanks in advance for help.

Best regards

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Production_CoEDashboard_May2022.pbit

### Steps To Reproduce

Setup CoE Starter kit until reaching to PowerBI Dashboard setup step.

**Comment by TetefBubu** [comment]
For earch data source, at the end, we have this error  (sorry in French).

Environment
Les informations d'identification sont requises pour la connexion à la source Cds. Vous devez actualiser et fournir les informations d'identification pour continuer. (Source à http://orgbf7d2e88.crm12.dynamics.com/.)

App, Flow, Maker, Connector, App Connection Reference, Flow Connection Reference, Audit Log, Flow Action Details, NonProdWords, Virtual Agent, Virtual Agent Component, Virtual Agent Flows, RPA, RPA Sessions, Power Platform User, Portals, Environment Capacity,

**Comment by Jenefer-Monroe** [comment]
Hello, this issue is with PBI itself, and not our template file. 

My guess from the error is that you have multiple users/tenants that you use for testing and you are logged in as the wrong one, or that there is a cache in the permissions. 

If that's the case you can try to log in as the correct user, and clear the connections via File > Options and settings > Data source settings > Clear permissions for both local and global
![image](https://user-images.githubusercontent.com/89584709/176451864-9e1754b3-e07b-496c-ac9a-27f41304858b.png)


If that's not the case, my recommendation is to get a repro outside of the CoE and approach a PBI expert in your org, or support. 

To get a repro:
- Boot PBI
- Home > Data > Dataverse
![image](https://user-images.githubusercontent.com/89584709/176449586-ab2e0b9d-9262-4f6e-b601-3cd352d7659d.png)
- Click the carrot next to your CoE environment in the Navigator > select some table > Load
![image](https://user-images.githubusercontent.com/89584709/176450736-936e5f0e-b5b8-4bec-b55c-eb35ad2847cb.png)
-

**Comment by TetefBubu** [comment]
Thanks Jenefer,

You should be right, because when I tried to remove all credentials, I found an old CoE setup (we did a few month ago) :may be we didn't remove correctly all parts.

![image](https://user-images.githubusercontent.com/108397783/176457340-b3fa5398-4eb6-447b-9727-4cb30271a92a.png)

I Tried to clear the permission cash, without any success : but I'm going to ask te our Power BI Teams for some Help.

Best Regards

**Comment by Jenefer-Monroe** [comment]
Thanks for keeping me in the loop, please let me know what you find so I can help others in the future!

**Comment by manuelap-msft** [comment]
Hello,

from the initial error message you shared it looks like you're missing just an "s". It says The resource principal named http://orgbf7d2e88.crm12.dynamics.com/ - the URL should be The resource principal named http**s**://orgbf7d2e88.crm12.dynamics.com/ - so starting with https. Missing the https can lead to auth issues!

Manuela

**Comment by TetefBubu** [comment]
Hi Manuela,

Yep It worked :-), adding the https prefix.

I also tried to access to dataverse as explained by jenefer, and it worked too.

But unfortunatly, now I have a new issue : blocked buy other requests..

I guess it's another issue not linked to the first authentication Issue ?

![image](https://user-images.githubusercontent.com/108397783/177562627-784f8612-5d55-4553-8c44-ea67b91e3f99.png)
