### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs even at 1 minute still not small enough chunks

### ISSUE THREAD

**Issue by DieterVCV** [microsoft/coe-starter-kit#3090]
### Describe the issue

Set up the CEO kit together with Microsoft, we went down to chuncking size: 1 minute but it still didn't work.
Error:Your audit logs were collected but some were missed due to truncated results in [this run ]
You will need to use a smaller interval to gather all logs. 
Current chunking size: 1 Minute

We have a big organisation but not a lot of people are using PowerApps/PowerAutomate

### Expected Behavior

It should get all information without error

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

Used settings: 
StartTime-Unit: Day
StartTime-Interval: 1
Timeinterval-Interval: 1
TimeInterval-Unit:Minute
StartTime-Interval:1500

**Comment by Jenefer-Monroe** [comment]
I'm afraid there is nothing we can do about this until we re-plat to the BYOD (Self Service analytics) where the logs will be more natively gathered rather than via this custom connector

You can explore this ahead of time if you would like
https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
