### ISSUE TITLE
[CoE Starter Kit - QUESTION] the Apps BPF in "Power Platform Admin View" doesn't work well.

### ISSUE THREAD

**Issue by hammhamm** [microsoft/coe-starter-kit#3102]
### What is your question?

I'm testing the Apps BPF in Power Platform Admin View, but it doesn't work well. 

In the "Validate Maker Business Requirements" stage, the status of "Check if Maker Provided Business Requirements" can only be selected as "No".

<img width="960" alt="image" src="https://user-images.githubusercontent.com/71855867/176851936-2f78bef0-82c0-408c-b11b-243cc97bdac8.png">

Then, when I click Next Stage, I get the following error and cannot proceed.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/71855867/176852064-c854e5b1-6ee4-4780-b12d-bf7432a10259.png">

Am I missing some information?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
That value (Check if Maker Provided Business Requirements) is not editable by you, there is a little lock symbol to suggest this. 
It is a calculated column based off a different field
![image](https://user-images.githubusercontent.com/89584709/176908705-63c60e13-b0b4-4058-aa88-46d28f18c5e8.png)

This all gets updated for you by the apps that take in the information from the maker. 
If you want to manually set it, you can do so using this field, and setting to Submitted
![image](https://user-images.githubusercontent.com/89584709/176906359-c0d407a8-dfee-4fdd-8009-1abd2735e829.png)

Note though, that since its a calc column you may not see the value switch to yes right away, calc coumns can take quite a while to update.

**Comment by hammhamm** [comment]
@Jenefer-Monroe 
I appreciate your quick response.

>This all gets updated for you by the apps that take in the information from the maker.

OK,I will try it

Thanks

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
