### ISSUE TITLE
[CoE Starter Kit - BUG] Pagination Limit Exceeded Admin | Sync Template v3 CoE Solution Metadata

### ISSUE THREAD

**Issue by matthewdevaney** [microsoft/coe-starter-kit#3108]
### Describe the issue

When I Turn On This Flow:
Admin | Sync Template v3 CoE Solution Metadata

I Get The Error Message 
Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Apps_as_Admin' of type 'OpenApiConnection' at line '1' and column '2218' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}". Code: 0x80060467 InnerError: '.

![image](https://user-images.githubusercontent.com/34290969/177051750-5f0af4d8-5e2a-46a6-ac06-b74a9a129d56.png)

### Expected Behavior

The flow should turn on with no errors.  To remove the error set pagination to 5,000 records (the max. allowed).

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### Steps To Reproduce

Turn on the flow in the CoE Starter Kit enviroment.  An error message will appear.

**Comment by Jenefer-Monroe** [comment]
Hello. All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
