### ISSUE TITLE
[CoE Starter Kit - BUG] Want CoE for Desktop Flows

### ISSUE THREAD

**Issue by Dhruv28112000** [microsoft/coe-starter-kit#3125]
### Describe the issue

I have gone through the CoE starter kit. In which I have to build Bi Dashboard for my flows of Power Automate. I want to know which file I use which gives only the monitor option for my power automate flows only.

Regards 
Dhruv Dalsania

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.2

### What app or flow are you having the issue with?

Power Automate

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid we are not setup to assist with customizations and so I cannot ensure that any advice I give will be correct as what we test is all the flows in the [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on and running.  

Can you comment on why this is as requirement for you? That might assist me with any advice. 

If what you are worried about is API calls, then I think you could skip these particular flows and be ok
![image](https://user-images.githubusercontent.com/89584709/177564342-59062e1d-319d-4467-a64c-bf269ba51930.png)

**Comment by Dhruv28112000** [comment]
I want only my desktop flow runs data and analyze in BI

**Comment by Jenefer-Monroe** [comment]
Gotcha. Thanks for clarifying. The desktop flow work in the CoE Starter Kit currently has several limitations that make it insufficient for organizations exclusively focused on that tech. This is due to the way that we gather the data and is not something we can fix without a product change (which is supposed to be coming live in a few months)

That said, there is a dedicated set of folks who work on "Automation CoE". My recommendation is that you focus in that direction instead. Here are some starter links to get you going:
- [Automation Center of Excellence Webinar](https://info.microsoft.com/ww-thankyou-businesscenterexcellencerpa.html?LCID=EN-US&ocid=eml_pg332504_gdc_comm_ba)
- [Microsoft Power Platform Automation CoE starter kit (preview)](https://docs.microsoft.com/power-platform/guidance/automation-coe/automation-coe-starter-kit)
- [RPA CLI](https://github.com/rpapostolis/rpa-cli)

**Comment by Dhruv28112000** [comment]
Thank you,  Jenefer for clearing all the things
