### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - Environment Request Connector Color Indicator Issue

### ISSUE THREAD

**Issue by KishoreJagan83** [microsoft/coe-starter-kit#3142]
### Describe the issue

When Maker select's  any of the  Business connector, then the color indicator shows Yellow but it should be Green.
![image](https://user-images.githubusercontent.com/43986892/177728804-ea1349c9-7f34-4b13-860e-15237b2103f6.png)

### Expected Behavior

If Maker pick's any of the connector's which belongs to Business connector category , color indicator should show in Green instead it shows Yellow.

Based on Default DLP Policy,
Business connector's should be Green
Non Business connector's should be Yellow
Blocked connector's should be Red(Do not Disturb symbol)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Admin - Environment Request

### Steps To Reproduce

After Maker Raises the Environment creation request using Maker - Environment Request App
Approver will view the Connectors selected by the maker in Admin - Environment Request App

**Comment by KishoreJagan83** [comment]
Any Updates ?

**Comment by denisem-msft** [comment]
@KishoreJagan83 the colors next to the connectors indicate that the connectors will be restricted if used together. If the connector is blocked outright, it will be red. Sorry that wasn't clear in the documentation or the interface.

Is there a better way we can communicate that some connectors will be restricted from being used together, rather than putting a warning sign between them? Perhaps we should just show the grouping in each group instead of a status?

**Comment by manuelap-msft** [comment]
Closing out as no further action required from CoE kit team / no response received on the issue. Please let us know if you continue to face issues.
