### ISSUE TITLE
[CoE Starter Kit - QUESTION] List RPA Flow Sessions error handling

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#3199]
### What is your question?

Hi Team, 

Have you encountered the following error in the desktop flow cloud runs?
![image](https://user-images.githubusercontent.com/95443860/179086032-b6d8daa8-bc23-4c17-9c23-797c1ab3c226.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Desktop Cloud Runs Flow

**Comment by nasilvae** [comment]
Hi Manuela, sorry attaching the new info below. 

We have 3 RPA environments. It seems to be breaking when it hits the environment that has most of our resources. 
![image](https://user-images.githubusercontent.com/95443860/179274959-d425be9c-5238-4a3a-8da0-1cbd5047085c.png)
![image](https://user-images.githubusercontent.com/95443860/179274977-b6edb31d-b686-4a15-a713-5fa77050d01c.png)

 
 

We were also experiencing the issue with the old CoE – 3.34 which prompted us to upgrade. 
![image](https://user-images.githubusercontent.com/95443860/179274991-beb45de1-19e4-4101-8555-6960777c6a22.png)
![image](https://user-images.githubusercontent.com/95443860/179275002-5e322a64-0c3f-4df6-811c-e0257307cd45.png)

**Comment by Jenefer-Monroe** [comment]
Regarding the apply-to-each failure

I'm afraid you may just be too large for the kit as it exists. You may be better suited to an automation focused CoE.
The desktop flow work in the CoE Starter Kit currently has several limitations that make it insufficient for organizations exclusively focused on that tech. This is due to the way that we gather the data and is not something we can fix without a product change (which is supposed to be coming live in a few months)

There is a dedicated set of folks who work on "Automation CoE". My recommendation is that you focus in that direction instead. Here are some starter links to get you going:
- [Automation Center of Excellence Webinar](https://info.microsoft.com/ww-thankyou-businesscenterexcellencerpa.html?LCID=EN-US&ocid=eml_pg332504_gdc_comm_ba)
- [Microsoft Power Platform Automation CoE starter kit (preview)](https://docs.microsoft.com/power-platform/guidance/automation-coe/automation-coe-starter-kit)
- [RPA CLI](https://github.com/rpapostolis/rpa-cli)

**Small tweak you could do**
We get two days backwards by default to help with redundancy (in case there is a failure one day or something). You could change this to -1 instead of -2 and that should work for you. However you will then have an unmanaged layer and you will need to remove that with each upgrade and reapply the change, please see [upgrading the kit](https://docs.microsoft.com/power-platform/guidance/coe/after-setup)
![image](https://user-images.githubusercontent.com/89584709/180825869-c5985043-5e58-4829-9622-b9ed23dfbfa1.png)

**Comment by Jenefer-Monroe** [comment]
Regarding your other bug, it looks like you were missing some changes to the flow, below is what it looks like now, please be sure you remove unmanaged layers so you see these changes
![image](https://user-images.githubusercontent.com/89584709/180826490-8e4be725-552b-48ef-81c8-0aee204bde82.png)
