### ISSUE TITLE
[CoE Starter Kit - BUG] Welcome to Power Apps and Power Automate

### ISSUE THREAD

**Issue by MarcosCostarella** [microsoft/coe-starter-kit#3210]
### Describe the issue

I keep getting the welcome email almost on daily basis. I can also get more than one email the same day
![Welcome to Power Apps and Power Automate](https://user-images.githubusercontent.com/106347491/179286588-a1852e86-a6eb-4b5e-86e9-e466fc050915.jpg)
.

### Expected Behavior

MS CoE workshop said to me the welcome email only fires the first time you create an app or a flow
![Admin Welcome Email v3](https://user-images.githubusercontent.com/106347491/179287376-741963a3-1d0d-4273-ae4e-84cdbd969ddc.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin | Welcome Email v3

### Anything else?

If I take a look at flow, last step send the welcome email to the admin email instead of the maker
![Send welcome email](https://user-images.githubusercontent.com/106347491/179288479-abb8d505-3ec4-4b00-8d0d-11c7ce84fd0a.jpg)

**Comment by Jenefer-Monroe** [comment]
This is what happens when you have the environment set as a non-production envt. In other words an environment for testing the CoE. 
You can see that in the equation
`if(equals(variables('isProductionEnvt'), true), triggerOutputs()?['body/admin_userprincipalname'], variables('adminEmail'))`

You can turn this flow off in your test envt if you'd like. 
And if this is your production environment, you should fix that env var
![image](https://user-images.githubusercontent.com/89584709/179315614-ac1b572a-aaed-4d35-97f1-d8d286e3bea3.png)

**Comment by MarcosCostarella** [comment]
so the value had been set to yes but the flow was working with the previous value. Why the reset flows is hidden from my side?
![command and setup center](https://user-images.githubusercontent.com/106347491/179624956-fc812ad8-69e7-4009-b39d-ec286e782697.jpg)

**Comment by manuelap-msft** [comment]
Here's what the **ProductionEnvironment** variable means:

1. If set to "no", we assume you're in a test environment and all emails will be redirected to the Admin email address you configured in a separate environment variable. Nothing will be sent to a maker/end user.
2. If set to "yes", we assume you're in a production environment and want to send all emails to the actual recipient - the maker/end user. 

From the description of your problem it sounds like the flow was not working as expected in that it was sending emails to you, rather than the new makers. So that's why you had to change it. 

The reset flow button was introduced in a more recent version of the Core components solution. You're currently on version 3.38, and we introduced this capability more recently - our current version is 3.40 and you'll have to upgrade to get that capability. Or, you can manually turn off and back on the Welcome email to force a reset.

Hope that helps,
Manuela

**Comment by MarcosCostarella** [comment]
Hi Manuela,

Yes, I manually turn off and back on this case. But I was thinking that there might be more flows in place using this variable and it would worth reseting all them. I will push the update and see if button is available

THanks,

**Comment by MarcosCostarella** [comment]
We are safe to close this thread. I pushed v3.40 and now reset button is visible. In any case, I have found new issues towards power bi Production_CoEDashboard_July2022. I am posting error here https://github.com/microsoft/coe-starter-kit/issues/3251
