### ISSUE TITLE
[CoE Starter Kit - QUESTION] Managed Environments vs CoE Starter Kit

### ISSUE THREAD

**Issue by bronsonacoutts** [microsoft/coe-starter-kit#3259]
### What is your question?

This is more of a documentation enhancement request, although I am sure there are already plans for this.

Now with the release of "Managed Environments"  some clearer documentation/guidance for when to use which and maybe some example use cases would be good.  

Also, if you choose to use Managed Environments (Which I am), how the CoE Starter Kit best compliments this and best practice (or what the intentions were/are) for how these should work in tandem.

I am figuring this out as I go for now.  Glad to be in the position of still gradually launching a PP program and therefore have the luxury of being able to do a bit of trial and error in prod (really? in prod? who me? no never :-))

### What solution version are you using?

July 2022

**Comment by manuelap-msft** [comment]
Hello,

great point, we're working on adding documentation for this but it's still in progress! In the meantime, a brief comparison of features:

**[Weekly digest](https://docs.microsoft.com/en-us/power-platform/admin/managed-environment-weekly-digests)** The CoE Starter Kit doesn't have a weekly digest for admins; instead admins self-serve information through the [Power BI dashboard](https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi). One part of the Weekly Digest is highlighting inactive apps to admins - in the CoE, a similar goal is achieved via the [Inactivity Notification process](https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#inactivity-notifications-processes) which notifies makers of their inactive resources and asks for approval to delete them. If approved, they are deleted from the tenant. So in Managed Environments this is an "insight" only, whereas in the CoE Starter Kit it drives action - the CoE kit also reduces burden on the admin to deal with inactive resources, as it puts it on the maker to decide what to do with that resource. 

**[Sharing limits](https://docs.microsoft.com/en-us/power-platform/admin/managed-environment-sharing-limits)** The CoE Starter Kit can't limit sharing on resources, so this can only be done via Managed Environments. The CoE Kit has a [Compliance process](https://docs.microsoft.com/en-us/power-platform/guidance/coe/example-processes) which identifies highly shared resources and asks makers to provide additional information, so that admins can better support those solutions (e.g. move them to a dedicated environment, implement ALM, have the helpdesk educated on that solution) and  through the [Power BI dashboard](https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi) admins can identify highly shared resources. But limiting sharing can only be done via Managed Environments.

**[Data policies](https://docs.microsoft.com/en-us/power-platform/admin/managed-environment-data-policies)** - seeing what DLP policies are applied to an environment can be done using the [DLP Editor](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#dlp-editor-v2) in the CoE Starter Kit. Additionally, the main purpose of the DLP Editor is to perform impact analysis on DLP policies you are planning to apply - so before applying a policy to an environment you can see what apps/flows that are already in those environments would be impacted. So Managed Environments gives you the visibility of what DLP policies area already applied to an environment, but the CoE Kit can additionally give you visibility into what impact those policies have on existing apps/flows.

This is a comparison of the specific features available in Managed Environments, the CoE kit has a wide range of admin, governance and nurture features beyond that - such as bulk updating permissions, environment and DLP request management, clean up of orphaned/abandoned resources, Pulse survey, Maker assessments etc. 

Overall it will depend on your use cases and needs for governance - I would say it's good to start with what's out of the box available in the product, as that's less maintenance and configuration effort on your side. And if you then discover you need additional features, see if the CoE kit can help with those. 

We'll make sure to write this up properly to add to our docs as well!

**Comment by bronsonacoutts** [comment]
Thanks Manuela!  That is actually quite fantastic, I think perhaps you might do your technical writers out of a job if you keep that up!

**Comment by manuelap-msft** [comment]
This has been added to our docs yesterday - it's pretty similar to what I shared earlier with you, just pasting the link here for completeness:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/overview#how-to-use-the-coe-starter-kit-alongside-power-platform-admin-center

Any further questions, please do let us know!

**Comment by bronsonacoutts** [comment]
Thanks Manuela!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
28/07/22,
22:30:43
