### ISSUE TITLE
[CoE Starter Kit - QUESTION] About the "Logic flows" connector

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3295]
### What is your question?

When I was checking the apps that violated the DLP policy, I found an app that violated the DLP policy because one app uses the "Logic Flows" connector.

When I checked this connector in "Power Platform Admin View", it was displayed that it was used in the "Admin --Command Center" app of the core component.
![image](https://user-images.githubusercontent.com/70095092/181440740-c2bb41e7-99b2-4695-ad86-05306f3800f9.png)

However, when I looked at the connections in the "Admin --Command Center" app, I couldn't find the "Logic Flows" connector.
![image](https://user-images.githubusercontent.com/70095092/181440981-108d72fb-9632-46f5-8043-a332bceb0c75.png)

Does the "Logic Flows" connector represent any other connector?
What is this connector?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2022

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by manuelap-msft** [comment]
The Logic Flows connector is when an app calls a Power Automate flow - you won't see this listed as a connection in the app, it's treated as a child flow in the app.

If you block the HTTP Request connector via data loss prevention (DLP), child flows are also blocked because child flows are implemented using the HTTP connector. 
https://docs.microsoft.com/en-us/power-automate/create-child-flows#known-issues

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
