### ISSUE TITLE
Getting number of PVAs in teams environment

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/coe-starter-kit#3296]
### Describe the issue

We are building lifecycle management for teams environments in our tenant and we want to see if there are any PVAs created in each environment. Could you please let us know where we can get this data on number of PVAs created in each teams environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin - Sync template V3

**Comment by manuelap-msft** [comment]
Information about PVAs are stored in the Dataverse tables of the environment - we use the Dataverse (Legacy) connector in the CoE environment to query the "bot" Dataverse table of all other environments in your tenant to get information on PVAs. Due to some authentication restrictions in the product, this method doesn't work for Dataverse for Teams environments so in the CoE kit we don't have the ability to get PVAs created in Teams environments.

Here's the table you're looking for - you may be successful using other mechanisms, such as calling the Dataverse API, to get this information and can build your own extension to the CoE kit for this:
https://docs.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/bot
