### ISSUE TITLE
Setup automation based on the GETTINGSTARTED.md procedure · Issue #26 · microsoft/coe-starter-kit-preview (github.com)

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#33]
Instead of requiring users to manually deploy the pipeline templates, create service principals, and ado service connections, provide a way to automate this from the canvas app.

Service Principal: https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools#configure-service-connections-using-a-service-principal
ADO Service Connections: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints

**Comment by rpothin** [comment]
I am working on something similar in another repository (https://github.com/Power-Platform-DevOps/Power-Platform-ALM-Starter-Kit/milestone/1), so I would be happy to help on this part.

I still need to push my work to the dedicated branch in the Power-Platform-DevOps/Power-Platform-ALM-Starter-Kit.

**Comment by rpothin** [comment]
Also, I am not sure what would be the best practice for service principals (see my comment [here](https://github.com/Power-Platform-DevOps/Power-Platform-ALM-Starter-Kit/issues/8#issuecomment-693748246)).

**Comment by devkeydet** [comment]
I'll take a look, but generally would love to incorporate your work here once reviewed.

**Comment by rpothin** [comment]
@devkeydet we are currently reviewing a [pull request](https://github.com/Power-Platform-DevOps/Power-Platform-ALM-Starter-Kit/pull/13) in our repository (Power-Platform-DevOps/Power-Platform-ALM-Starter-Kit) for the provisioning and decommissioning of an environment with service connection management in Azure DevOps.

Do not hesitate to take a look and even let comments in the pull request if you want.

I think I will try to take a look to the creation of a service principal because I am interested by this point too.

**Comment by rpothin** [comment]
Thank you for the assignment @mikefactorial 😊

I was working on this task since few weeks now in a private GitHub repository.
I pushed all my work progress in a fork of this public GitHub repository: [**rpothin/coe-starter-kit**](https://github.com/rpothin/coe-starter-kit)

Most precisely, my work is located in the [**PowerPlatformDevOpsALM/SetupAutomation**](https://github.com/rpothin/coe-starter-kit/tree/main/PowerPlatformDevOpsALM/SetupAutomation) folder.

Finally, you can follow my work on this task in a [project](https://github.com/rpothin/coe-starter-kit/projects/1) created in my fork of this GitHub repository.

**Comment by mikefactorial** [comment]
Initial release of CoE CLI will be part of the July release.

**Comment by mikefactorial** [comment]
@devkeydet This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.
