### ISSUE TITLE
Unable to upgrade CoE Starter Kit from 2.0.10

### ISSUE THREAD

**Issue by LakshmanChand** [microsoft/coe-starter-kit#3321]
We created a separate environment for CoE starter kit and installed CoE kit Core components version 1.39 initially on 28th March 2020. And then we have upgraded CoE kit core components from version 1.39 to 2.0.10 on 23rd March 2021. Now, we are unable to upgrade CoE Starter kit core components from version 2.0.10. to latest version. We are getting an error as below. When we use the backup of the same environment and restore on sandbox environment, we are able to upgrade the CoE kit core components from 2.0.10 to version 3.37. Please share the link to download the exactly next version of CoE kit core components version 2.0.10. I have created couple of tickets on the same issue.

As we have production data with the current version, we cannot delete the existing version of solution to install the latest version.

**Error Details**
**_Connector import: FAILURE: {"error":{"code":"ApiNotFoundForPatch","message":"The custom connector could not be found for the update operation."}}_**

**Comment by Jenefer-Monroe** [comment]
I'm afraid our guidance capabilities have not changed since the last time you asked. 

We cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help with how to migrate the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment.

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Sorry we cannot be of more assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
