### ISSUE TITLE
[ALM Accelerator - QUESTION] Connection is not configured for this resource

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#3336]
### What is your question?

Hello , I am hoping you can help - I have an Issue I need some support  with 

I have installed the ALM accelerator solution  into its own environment. As I proceed to establish the deployment profile after selecting prepare I receive the error, <SharePointSites.Runfailed:the connection is not configured for this resource> except all applicable environments have an established SharePoint connection

![Issue 1](https://user-images.githubusercontent.com/99030907/182369680-90ebcf36-9b56-4fa8-a879-55cb02e7034a.PNG)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

August 2022

**Comment by mikefactorial** [comment]
Disregard. The last message. Can you ensure that your user has the following role or is part of a team with this role in the ALM Accelerator environment? 

![image](https://user-images.githubusercontent.com/42348035/182396951-6b2063c0-fcd7-457f-b287-d599158344c4.png)

**Comment by crowdedLeopard** [comment]
Hi @mikefactorial they do -also the dropdown is empty when they try to select the SharePoint site when setting environment variables

![Issue 2](https://user-images.githubusercontent.com/99030907/182419581-b3f12ee9-0d7d-497b-97ad-3265385c1e6d.PNG)
s

**Comment by mikefactorial** [comment]
I would expect the drop down to be empty since the flow responsible for retrieving the sites failed. The specific issue here is with the connection. However, the message is indicative of the process record in dataverse not being shared with the user. The role I mentioned makes the process table readable at the org level which is why my first inclination was to check that role. A couple of things to try
1. Delete / Recreate the Sharepoint connection in the ALM Acccelerator environment.
2. Manually share the process record associated with the flow with your user. The process record will have the same name as the flow e.g. 
![image](https://user-images.githubusercontent.com/42348035/182425310-ff7298a8-4c59-4aad-b0ee-67ee5f803353.png)

**Comment by mikefactorial** [comment]
Also, assume that the user in question does in fact have permissions to read sites in Sharepoint.

**Comment by mikefactorial** [comment]
One more thing to check is if the Flow actually runs and fails or if it is never run at all. If it is running but failing during the run then it would be helpful to see where it's failing.

**Comment by crowdedLeopard** [comment]
Hi @mikefactorial , the flow wasnt enabled - I turned it on and as you said , it works !

My last issue is below - Ive checked the service connections exist in devops  and in the  corresponding PP environment and all pipelines can share service connections. 

Im sure im missing something basic here 

![ADO - ALM Accelerator Issues](https://user-images.githubusercontent.com/99030907/182900381-3e2a2511-6f36-4e80-9b8f-d406ea4b2847.png)

**Comment by mikefactorial** [comment]
@crowdedLeopard make sure the name of the service connection is identical to the value passed into the pipeline. A common issue is that the trailing slash is left off it was created manually. Other than that make sure the check box at the bottom of the service connection config that says "Grant access permission to all pipelines"

**Comment by crowdedLeopard** [comment]
many thanks for your help @mikefactorial  - almost working.
