### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template v3 (Desktop Flows) issue

### ISSUE THREAD

**Issue by annaserbenko** [microsoft/coe-starter-kit#3337]
### Describe the issue

Admin Sync Template v3 (Desktop Flows) flow failed with error message "Cannot write more bytes to the buffer then the configured maximum buffer size" in the action "List desktop flows" which gets the information from the system table called Process (workflow).
We checked this table and it's empty for one of the environment and the flow is failing only while trying to connect to the table from this one environment.
So our questions are: why is this table empty on this environment? How is this table populated? How can we make this table to be populated? Which flows need to added to this table: all or only solution flows?
Because of this emptiness and error in the flow we cannot receive the information about the desktop flows from this particular environment.

![image](https://user-images.githubusercontent.com/102215719/182394172-4a1280c5-3752-4b4b-8e67-e88bf36f55e5.png)

### Expected Behavior

The Process (workflow) table has items and CoE flow is working correctly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Admin Sync Template v3 (Desktop Flows)

**Comment by Jenefer-Monroe** [comment]
Unfortunately you have hit a [known limitation with Desktop Flows in the CoE](https://docs.microsoft.com/power-platform/guidance/coe/limitations#large-desktop-flows)

The desktop flow work in the CoE Starter Kit currently has several limitations that make it insufficient for organizations focused on that tech. This is due to the way that we gather the data and is not something we can fix without a product change (which is supposed to be coming live in a few months)

That said, there is a dedicated set of folks who work on "Automation CoE". My recommendation is that you focus in that direction instead. Here are some starter links to get you going:
- [Automation Center of Excellence Webinar](https://info.microsoft.com/ww-thankyou-businesscenterexcellencerpa.html?LCID=EN-US&ocid=eml_pg332504_gdc_comm_ba)
- [Microsoft Power Platform Automation CoE starter kit (preview)](https://docs.microsoft.com/power-platform/guidance/automation-coe/automation-coe-starter-kit)
- [RPA CLI](https://github.com/rpapostolis/rpa-cli)

**Comment by annaserbenko** [comment]
@Jenefer-Monroe Thank you for your response.
My question was about how to make the table Process (workflow) to be populated. Because we have more than 20 environments and this table is populated at all environment except one. With this one environment it's empty and filling doesn't work.
So we're trying to understand why this table isn't populated only at one particular environment

**Comment by Jenefer-Monroe** [comment]
Its not populating because the returned value from the call is too large for the connector. This is a product limitation of the old Dataverse connector that you cannot select which columns to retrieve. And we are awaiting a product fix to the new Dataverse connector before we can use it. 
In short, the kit cannot assist with collecting inventory for your large Desktop Flow environments but you can use those other resources I shared as they use a different tech for gathering data which is not bound to the connectors.

**Comment by annaserbenko** [comment]
@Jenefer-Monroe Thank you for your response. I understood the logic of this table in terms of desktop flows. But why is this table empty at all? Why there are no information about the cloud flows at least?

**Comment by Jenefer-Monroe** [comment]
We do not populate the process (workflow) table. That is a product table. We do not populate it, the product does. We read that table and write to the tables in the Core Solution. The desktop flows in that table are too large to read in that environment. 

We do not use this technique to gather cloud flows as that product has a proper connector. There is a separate flow Admin Sync Template v3 (Flows) that gathers cloud flows and puts those in its table.

**Comment by annaserbenko** [comment]
@Jenefer-Monroe  thank you for your answers!
Just to confirm that this error "Cannot write more bytes to the buffer then the configured maximum buffer size" is a limitation and for now we're not able to receive the information from this table with the CoE flow, right?
Appreciate your help
![image](https://user-images.githubusercontent.com/102215719/182829941-1b696784-450d-4cef-bf3c-b8c2d9dd78af.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
