### ISSUE TITLE
CoE Starter Kit - Prerequisite

### ISSUE THREAD

**Issue by HCLAshwaniB** [microsoft/coe-starter-kit#3355]
### Describe the issue

need assistance to CoE Starter Kit - Prerequisite and configuration guide.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

NA

### What app or flow are you having the issue with?

Na

**Comment by manuelap-msft** [comment]
Hello,

you can find all of our documentation here: https://aka.ms/coestarterkit

Specifically, our pre-requisites are here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup and our set up instructions start here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components

You've mentioned the Governance components in your post so for that the pre-requisites are here https://docs.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov and the setup instructions start here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components. There's multiple parts to the Governance components solution and the setup has been split up by feature rather than by solution so you'll find all the setup instructions in those pages:
![image](https://user-images.githubusercontent.com/55705669/182788962-483ddec1-f1f7-44b9-84af-5c9cc6636214.png)

**Comment by HCLAshwaniB** [comment]
Thank you for the information. This really help full to understand the basics. However can you please guide me how I can get help to end to end configuration of  'core and governance solution' and suggestions for our environment custom requirement as a 'free or paid partner support'?

**Comment by manuelap-msft** [comment]
Hello,

our team does not offer a service like that, we make the COE Starter kit available as an open-sourced and unsupported set of components, shared via GitHub using a [MIT license]([https://github.com/microsoft/coe-starter-kit/blob/main/LICENSE)

However, we have many partners that offer CoE install and configuration services - you can find them via AppSource: 
https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
