### ISSUE TITLE
How to resolve CoE Audit Logs require smaller chunks

### ISSUE THREAD

**Issue by shanemeisnerdhg** [microsoft/coe-starter-kit#3390]
### What is your question?

Trying to get past the "CoE Audit Logs - Missing some logs - require smaller chunks" emails:
_CoE Audit Logs - Missing some logs - require smaller chunks
Your audit logs were collected but some were missed due to truncated results in [this run ]
You will need to use a smaller interval to gather all logs. 
**Current chunking size: 5 minute**_

It doesn't seem our Tenant is that large, but maybe it is for this process??

Our Tenant is currently at 17GB used with our largest environment having 849 Apps. 
We believe over 50% of those unused, thus the need to audit so we can start cleaning house.

We've set our TimeSegments-CountLimit to 300
TimeInterval-Unit - Minute
TimeInterval-Interval - 5

Does that look correct? 
Any recommendation settings for trying to get past this?

The Child flow runs always show NextPageURl as True with the Input value matching the Output for all runs.

Input:  https://manage.office.com/api/v1.0/a311fc62-83f4-45f0-9502-1bb2247d4c8d/activity/feed/subscriptions/content?contenttype=Audit.General&endtime=2022-08-08T08:43:09.7619862Z&starttime=2022-08-08T08:38:09.7619862Z&nextpage=20220808084114338136279$20220808083809761000000$na0030

Output: https://manage.office.com/api/v1.0/a311fc62-83f4-45f0-9502-1bb2247d4c8d/activity/feed/subscriptions/content?contenttype=Audit.General&endtime=2022-08-08T08:43:09.7619862Z&starttime=2022-08-08T08:38:09.7619862Z&nextpage=20220808084114338136279$20220808083809761000000$na0030

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

August 2022

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
Because of the way the backend we are using works, we also have to see other office operations (ex boot excel) so the number of records here balloons quickly. You could try 1 minute chunks

- TimeSegments-CountLimit: 1500
- TimeInterval-Unit - Minute
- TimeInterval-Interval - 1

But if that does not work then I'm afraid there is nothing we can do about this until we re-plat to the BYODL (Self Service analytics) where the logs will be more natively gathered rather than via this custom connector

You can explore this ahead of time if you would like
- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

We are currently working on integrating this with the CoE hoping to release sometime in the fall.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
