### ISSUE TITLE
Seeing two appid columns in PowerApps app table

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/coe-starter-kit#3395]
We are seeing two columns AppID and APPStringID in PowerApps apps admin table in COE. Could you please let us know what is the difference between both and which one is the correct appid for different kind of apps (model-driven, canvas and sharepoint form app). For model driven apps we see that both ids are different.

**Comment by Jenefer-Monroe** [comment]
Unfortunately the answer is not simple because the different app types use GUIDs differently. Ex Model Driven Apps reuse GUIDs across environments for starter apps. 

The intention of the APPStringID is to be a GUID you can lookup from the product to find an app in inventory
The intention of the AppID is to be a unique GUID for the record. 
As of August there is a third option RecordGuidAsString which is a string version of AppID (for Dataflow usage)

I hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
