### ISSUE TITLE
[CoE Starter Kit - BUG] Coe Audit Logs - Chunking Size Issue - Sending a ton of emails daily. 

### ISSUE THREAD

**Issue by joebeyer75** [microsoft/coe-starter-kit#3422]
### Describe the issue

Every since we installed the COE toolkit, we are getting 50+ emails everyday all at the same time that are:

Subject: CoE Audit Logs - Missing some logs - require smaller chunks. 

Body: Your audit logs were collected but some were missing due to truncated results in this run. You will need to use a smaller interval to gather logs. **Current chunking size**: 15 Minute. See the optional Step 11 of our Audit Log flow setup documentation for more details. 

Upon initial rollout, the chunking size was set to 1 hour. We then lowered it to 30 minutes. Now we have it at 15 minutes, but still getting these email. 

### Expected Behavior

Not sure what emails/information we are supposed to be getting in place of these, so not really sure what expected behavior should be since this has been happening every since we installed it. 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

Flow runs every day and sends out the 50+ emails. 

### Anything else?

Your audit logs were collected but some were missed due to truncated results in [this run ](https://flow.microsoft.com/manage/environments/e6fd2b46-aa5b-e35a-b778-fbd88afca814/flows/47e636c7-327b-e585-f7ae-c0276fea3d17/runs/08585414491356724711412659914CU75). 
You will need to use a smaller interval to gather all logs. 
Current chunking size: 15 Minute 
See the optional Step 11 of our [Audt Log flow setup documentation ](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)for more details.

**Comment by Jenefer-Monroe** [comment]
This mail is intended to let you know that you need to continue making these chunks smaller to hopefully be able to cover your tenant usage. You can try down to 1 minute (see below for help with that), then if you still get the error you may just be too large to work with the existing custom connector solution. 

Because of the way the backend we are using works, we also have to see other office operations (ex boot excel) so the number of records here balloons quickly. You could try 1 minute chunks

- TimeSegments-CountLimit: 1500
- TimeInterval-Unit: Minute
- TimeInterval-Interval: 1

But if that does not work then I'm afraid there is nothing we can do about this until we re-plat to the BYODL (Self Service analytics) where the logs will be more natively gathered rather than via this custom connector

You can explore this ahead of time if you would like
- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

We are currently working on integrating this with the CoE hoping to release sometime in the fall.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
