### ISSUE TITLE
Use and deploy without Environment Maker permissions

### ISSUE THREAD

**Issue by bbenouarets** [microsoft/coe-starter-kit#3424]
### Is your feature request related to a problem? Please describe.

Currently, the developer must obtain Environment Maker rights in each environment where the Accelerator is to deploy.

### Describe the solution you'd like

We would like to have a role or feature that allows the maker itself to not need special permissions on the environments.

**Comment by mikefactorial** [comment]
@bbenouarets thanks for this feedback. We've heard this from other users as well. We're currently investigating the minimum priveleges required with the platform team and there is on-going work to get to a place where makers don't need to have permissions in downstream environments. However, in the short term there will always need to be some permissions in downstream environments if a user is expected to configure deployment profiles and / or configure deployment settings. This is a platform limitation at the moment that we as the CoE Starter Kit team are subject to since we can only work within the confines of the platform's capabilities. Closing this as a duplicate for now https://github.com/microsoft/coe-starter-kit/issues/3302 https://github.com/microsoft/coe-starter-kit/issues/2829
