### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inactivity Notifications - can base on usage rather than modified? 

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#3440]
### What is your question?

For the Inactivity notification flow under the Governance Component, is it in the product roadmap to remove the "Last Modified" date as our triggered command? Users run the app and flow regularly; however, does not modify often and we don't want an approval process to be sent out to almost all users who have not modified the app/flow within the 6 months. Thanks! :) 

### What solution are you experiencing the issue with?

Governance

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2

**Comment by Jenefer-Monroe** [comment]
For apps, you can enable the [audit logs solution](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog) and that will let the inactivity for apps be based on being launched recently instead of edited. 

For flows, we dont currently have access to when they run and so cannot create a similar condition. 

In either case, you can excuse apps, flows and entire environments from the process in the [Power Platform Admin View](https://docs.microsoft.com/power-platform/guidance/coe/core-components#power-platform-admin-view) and the [Cleanup Old Objects App](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#cleanup-old-objects-app)

Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
