### ISSUE TITLE
[CoE Starter Kit - QUESTION] Error when Connecting Environment to Power BI Dashboard

### ISSUE THREAD

**Issue by ddomboy** [microsoft/coe-starter-kit#3456]
### What is your question?

Hey together,

I am currently installing the CoEStarterKit. When configuring my PowerBI dashboard I want to connect my environment to Power BI with the zip file  "Production_CoEDashboard"

After login I receive the following errors:

OrgUrl:
Load operation was aborted due to an error loading a previous table

Environment:
OLE DB- or ODBC-Error: Exception of HRESULT: 0x80040E4E

The same error occurs for the others as well.

What can I do here? Thanks in advance!

**Comment by manuelap-msft** [comment]
Here are some typical troubleshooting tips when connecting to the Power BI dashboard: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting

Make sure that you put the Org URL in in this format https://myorg.crm.dynamics.com - the leading http**s**: is important for a successful connection to be established. We sometimes see this error when customers use http instead of https! 

If this doesn't help could you please paste in the full error message so everything you see in the load error as the actual failure might be a little further down?

**Comment by ddomboy** [comment]
![Fehler neu](https://user-images.githubusercontent.com/110176702/184624672-3ae7ba72-18a2-40d4-afeb-aa1bb73a89d6.PNG)

**Comment by manuelap-msft** [comment]
If you scroll down there, is there one table that gives a different error message?

**Comment by ddomboy** [comment]
![fehler 2](https://user-images.githubusercontent.com/110176702/184628619-e5ef8280-622f-430b-9090-08d1f24923c3.PNG)

This occurs one time as well

**Comment by manuelap-msft** [comment]
Perfect, thank you - I think that's the real issue! We had a bug here due to a new column we introduced on all tables in the data model, and released a hotfix to the dashboard last week. You can download the latest version here 
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Production_CoEDashboard_August2022.pbit

Please let us know if that works or if you see the same error still, as we may have missed a table!

**Comment by ddomboy** [comment]
works, thanks a lot!

**Comment by manuelap-msft** [comment]
Amazing, thanks for letting us know! I'll close this issue now but please do let us know if there's anything else we can help with!

Thanks for using the CoE,
Manuela
