### ISSUE TITLE
[ALM Accelerator - BUG]: ISSUE TITLE

### ISSUE THREAD

**Issue by esosa61** [microsoft/coe-starter-kit#3489]
### Describe the issue

In a build and deploy job to validation environment the pipeline stops at Set TriggerSolutionUpgrade Variable

Starting: Set TriggerSolutionUpgrade Variable
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\4aaa4686-43c3-4bb7-9c39-82de1f256823.ps1'"
TriggerSolutionUpgrade : The term 'TriggerSolutionUpgrade' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\a\_temp\4aaa4686-43c3-4bb7-9c39-82de1f256823.ps1:4 char:7
+ if("$(TriggerSolutionUpgrade)".Contains("TriggerSolutionUpgrade"))
+       ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (TriggerSolutionUpgrade:String) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : CommandNotFoundException
##[error]PowerShell exited with code '1'.
Finishing: Set TriggerSolutionUpgrade Variable

It was a CLI installed, any ideas or workaround

### Expected Behavior

Solution is deployed to validation environment as managed

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

august 

### Steps To Reproduce

Deploy solution form the ALM Accelerator

**Comment by mikefactorial** [comment]
@esosa61 thanks for reporting this. Looks like you have a more recent version of the pipelines post August release. 

This is a known issue with our documentation on the manual setup of the pipelines which instructs you to import our pipeline repository. The side effect of this is you will get changes made since the previous release in your pipelines. 

To remedy this please get the latest pipelines from the release here https://github.com/microsoft/coe-alm-accelerator-templates/archive/refs/tags/CenterofExcellenceALMAccelerator-August2022-HF1.zip or the tag here https://github.com/microsoft/coe-alm-accelerator-templates/tree/CenterofExcellenceALMAccelerator-August2022-HF1

We have an issue open to fix the instructions in the docs in the upcoming release.

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here.
