### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION with the Audit log flows and the time intervals

### ISSUE THREAD

**Issue by johnravas** [microsoft/coe-starter-kit#3566]
### What is your question?

I have recently installed the August 2022 edition of the CoE Starter kit with the audit logs component.  With the [Child] Admin | Sync Logs flow I continue to receive daily notifications that Your audit logs were collected but some were missed due to truncated results in this run.  You will need to use a smaller interval to gather all logs.

Per the documentation I have been tweaking the intervals in hopes of stopping this error message.  I started with the defaults (1 hour).  I tweaked them down to 30 minutes, then up to 4, 6, then 8 hours.  I don't seem to be making progress in getting this dialed in correctly.  We have a tenant of about 1,700 users and I didn't think we did that much with Power Platform - yet! I was hoping that my original tweak, 30 minutes would solve it.  For today's run, I set it to 15 minutes - which generated 96 child flow runs.  In my email, I received 22 error messages - in theory a win, in that I didn't receive one for each flow run like my other days.  I would have thought 15 minute intervals would have been more than sufficient.

I tried looking at the flows to see if I could get an idea of how to best guess my settings.  Any advice?  Thanks in advance

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
This mail is intended to let you know that you need to continue making these chunks smaller to hopefully be able to cover your tenant usage. You can try down to 1 minute (see below for help with that), then if you still get the error you may just be too large to work with the existing custom connector solution. 

Because of the way the backend we are using works, we also have to see other office operations (ex boot excel) so the number of records here balloons quickly. You could try 1 minute chunks

- TimeSegments-CountLimit: 1500
- TimeInterval-Unit: Minute
- TimeInterval-Interval: 1

But if that does not work then I'm afraid there is nothing we can do about this until we re-plat to the BYODL (Self Service analytics) where the logs will be more natively gathered rather than via this custom connector

You can explore this ahead of time if you would like
- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

We are currently working on integrating this with the CoE hoping to release sometime in the fall.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
