### ISSUE TITLE
[ALM Accelerator - Feature]: Import to Dev as Managed

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/coe-starter-kit#3569]
### Is your feature request related to a problem? Please describe.

We have a situation where we have a CORE solution that includes many references tables that will be used for multiple applications.  When we fire up a developer instance and use the AA4AM to import the CORE solution into the developer environment it goes in as managed.  This causes an issue when say you are working on a new APP and need to add a lookup on a table that references a table in CORE.  The entire CORE table is then added to the new APP solution.

Example:

I have two solutions: CORE and APP1

CORE has references to tables that all solutions will need, like CORETABLE1.

APP1 has the references to tables for that app, named APP1Table.  One of those tables needs data from CORETABLE1 as a lookup.

When I add a field to APP1Table the entire table CORETABLE1 is added to the solution.  I really only need the reference to that field from APP1Table.  

### Describe the solution you'd like

Add an option to import a solution from source as managed so that when the reference is added, the CORE table is not added to the APP solution.

This will element the cross-solution dependency and APP1 will only contain the components it owns entirely plus the delta customization.

### Describe alternatives you've considered

We can manually import the managed solution but we have other config data that goes with that we would have to import manually which runs the risk of it being done automatically.

**Comment by mikefactorial** [comment]
@rfarris2000 thanks for submitting this. We have a similar request here https://github.com/microsoft/coe-starter-kit/issues/2185. Except in that request it's to deploy as unmanaged to downstream environments. The concern with adding this functionality in both cases is that a user can potentially shoot themselves in the foot. However, similar to the warnings we have in the UX for the Delete Solution functionality I think we can warn users that choosing these options could have unintended consequences and also provide admins with a way to turn this functionality off for certain groups of users or altogether. Will discuss internally about the best solution to this request. Adding to December backlog for now along with  https://github.com/microsoft/coe-starter-kit/issues/2185.

In the meantime, you may be able to accomplish this pretty easily using the hooks in the pipelines (i.e. Hooks\deploy-solution-import-pre-hook.yml) to add some logic to decide what else needs to be deployed along with a certain solution.

A lot to think about here...will update with some of our internal brainstorming on the overall request and potential solutions.

**Comment by rfarris2000** [comment]
@mikefactorial It's a little different than that.  I only want the ability to import a solution as managed in my developer environment.  My case requires that the base solution (similar to default) be installed in all developer environments but only as managed.  

All other solutions they work on can be unmanaged except this base solution.

**Comment by mikefactorial** [comment]
@rfarris2000 it is different. I get the ask but brought up the the other issue because we have segregated import from deploy specifically because the former is import as unmanned and the latter is deploy as managed. So maybe the ask isn't correct. Rather than importing a managed solution it would be better to deploy a managed solution based on some trigger. This way we don't have to change our pipelines in either situation we just need a new trigger off either the import or the deploy pipelines. Both of those pipelines use the same templates to do the same thing. The only difference is if the solution ends up as managed or unmanaged. If we start thinking of import and deploy as just deploy as unmanaged or deploy as managed then we can kill two birds with one stone rather than killing one bird which is why I brought up the other issue, but like I said there's potential side effects to this solution where a user could break their environment.
