### ISSUE TITLE
[CoE Starter Kit - BUG] Not saving all flows in CoE flow Table

### ISSUE THREAD

**Issue by MarinaHadzi** [microsoft/coe-starter-kit#3572]
### Describe the issue

When we run Admin | Sync Template v3 (Flows) flow it collects some flows and does not write them in Flow table. They are visible in List flows as admin action but we can't see what happened in Apply to each then.
![image](https://user-images.githubusercontent.com/71693895/187928461-2a96871c-31de-4a39-9c51-5a11fe6afee2.png)

We are missing around 10 flows from Default environment, a regual user account is the owner of a flow and flows are not in a solution. Do you have some recommendations on hot to fix this?

Thank you, kind regards

### Expected Behavior

collect all flows from environments 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3,41

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by Jenefer-Monroe** [comment]
There are a few reasons you may be missing flows including:
- they are owned by a service principle
- they are unpublished (imported as a solution but never turned on)
- they were missed in the past and a full inventory will fix it. 

You should try a [full inventory](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory) run to see if that fixes it. Note that in order to make the API calls in these flows manageable, we filter to objects added/edited in the last week for processing. This prevents us from having to determine if every flow in the envt has been changed by looking at its modified date.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
