### ISSUE TITLE
[ALM Accelerator - BUG]: Import managed solution fails 

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#3587]
### Describe the issue

We when try to import a MANAGED solution, which contains elements that  already exist in the TARGET environment as unmanaged then ALM accelerator fails . However we are able to import the same solution by using CRM import functionality .

The below  link says similar issue . Since we are using ALM accelerator we can not implement the same solution which mentioned in below link .
https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/DevOps-CI-CD-Cannot-Convert-Unmanaged-Components-to-Managed/td-p/850080

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Apr 2022

**Comment by mikefactorial** [comment]
@linujohn22 you're correct that the current implementation doesn't support this scenario. However, there is a facility in the import solution task that would allow you to do this specifically the ConvertToManaged parameter seen below. It's debatable whether we should support this option since it may have unintended consequences and having unmanaged solution components in a downstream environment isn't the ideal ALM practice.
![image](https://user-images.githubusercontent.com/42348035/188861465-e0302f05-1da1-46b9-88da-a155ab615570.png)

However, if you want to override the default solution import in the ALM Accelerator you could update the deploy-solution-import-pre-hook.yml (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorforpowerplatform-hook-extensions) to call the task with the ConvertToManaged flag set. This would ultimately result in the solution being imported twice but you could work around that by updating the variables used in the conditions in the main pipelines.

Obviously, this is a bit of a hack but it does provide a solution in your unique case.

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do on this issue.
