### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE DelayInventory + Schedule Daily + absence of Concurrency Control + big tenant

### ISSUE THREAD

**Issue by miroslav-harlas** [microsoft/coe-starter-kit#3600]
### Describe the issue

Hello,
first of all, I do not really understand the purpose of **DelayInventory** variable and related logic in **Admin | Sync Template v3** cloud flow. How the _random delaying_ can be a way how to achieve _load balancing_? That sounds like an IT _magic_ approach ✨🔮. Please, could you elaborate more and update official documentation of real purpose of this? Thank you very much, I'm really curious about knowing this and potentially learning something new 😉
![image](https://user-images.githubusercontent.com/16306406/188888911-3817a22a-7a7b-49f8-9f4e-35a136b4077b.png)
![image](https://user-images.githubusercontent.com/16306406/188890838-7bf7d6b0-93fe-49dc-af19-e9f76be07594.png)

Anyway, this feature **DelayInventory** is causing issues to us. I'm going to ignore the situation with full inventory - we have pretty big tenant and full inventory is taking about 9 days in our tenant and we handle this by modifying schedule of Admin | Sync Template v3.

What I would like to complain about is impact of **DelayInventory** feature to incremental inventory runs as well. By default these are set to be running on daily basis, and actually we also would love to have those to be running daily, but due to big amount of environments - more than 1500 - the cloud flow **Admin | Sync Template v3** is usually running for very long time. We have set DelayInventory to "No" and after that action, the single run of **Admin | Sync Template v3**  in our tenant is taking between 7-16hours. OF course, the follo-up flows Admin | Sync Template v3 (xxx) need additional time to be completed, therefore the single incremental inventory is usually taking  between 10-22 hours in our tenant. However we learned hard to identify this environment variable exists and that the related process caused a mess and malfunction of CoE starter Kit.

Real life story:
Imagine that we had DelayInvenotry set to "Yes". One run **Admin | Sync Template v3** randomly decided to delay for more than 14 hours, and with the inventory itself, it was running for more than 30 hours. Unfortunately, next run of **Admin | Sync Template v3** was triggered in the meantime and "random" feature decided to delay for less than 60 minutes. Then we had two parallel runs of **Admin | Sync Template v3** which were updating CoE environment records twice at the same time and triggering the inventory of apps, flows and other things twice at the same time. The second run of **Admin | Sync Template v3** took then more than 40 hours, and in the meantime the third run of  **Admin | Sync Template v3** was triggered in parallel with second one, but then it was even worse and finally after couple of days we had about 3-4 runs of incremental inventory running in parallel at the same time and everything starter to time out as well as getting messy little bit. It was pretty complicated and time consuming to get everything back under the control. That's it. Thank you for reading our whole story about this issue :)

### Expected Behavior

1. DelayInvenotry variable is set to "No" by default.
2. **Concurrency** control is turned **On** on a schedule trigger of **Admin | Sync Template v3** and **Degree of Parallelism** is set to **1** >> to avoid multiple runs of this flow in parallel. You can also consider this setting as a standard for all other scheduled flows, which do not expect to be running twice in parallel, e.g. clean-up flows, etc.
3. Because inventory itself may take longer time, than run of the flow **Admin | Sync Template v3**, please, implement a logic, which can check that previous inventory run was completed/finished and do not start a new one (or delay it) if the previous inventory run is already in progress. This can be achieved by adding additional data -> store the history of runs of **Admin | Sync Template v3* and make unique identifier of each run (e.g. incrementally autogenerated incremental number), and then have a table, in which every flow **Admin | Sync Template v3 (xxxx)** will confirm that it is completed for each environment. Not sure if my proposal is clear and achievable. Please, let me know.

![image](https://user-images.githubusercontent.com/16306406/188898419-efda7343-1658-44a2-969e-bf5712c1abbd.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Admin -Sync Template v3

### Anything else?

I'm aware about BYODL and plans to connect CoE Starter Kit to that, but I believe that fixing the issues described above, and especially setup of Concurrency control, which is very simple and fast task to do, that will improve stability of CoE Starter Kit even with combination with BYODL.

**Comment by manuelap-msft** [comment]
Hello,

thanks for the feedback!

The **DelayInventory** setting is used to protect the Dataverse service on the Microsoft side - the CoE Starter Kit is installed in thousands of tenants, and as you can image performs quite a lot of Dataverse read/write actions during an inventory run. The way scheduled flows work, unfortunately, is that when they are shipped in a managed solution they run at the very same time independent of the customer timezone - so they may run at 7am PST, 3pm GMT etc etc. This meant that we saw millions of Dataverse calls at the very same time each day, which meant that with an increase in installations of the CoE kit it may have caused a service disruption. That's the last thing we want! In order to balance out these Dataverse calls we had to make sure customers run the inventory at different times during the day - our _ideal_ solution would have been to provide a parameter to the Schedule trigger, unfortunately that's not possible in Power Automate today (the Schedule trigger doesn't work with Environment Variables etc) so the only solution we could think of is introducing a random delay after the flow kicks off. 

Hopefully that explains the purpose of this setting - it's not to load balance queries on your (customer) side, but to spread them out on our (Microsoft) side.

Great suggestions regarding the **Concurrency** setting - we'll test that on our side and if it all works we can add that to a future release.

At the moment, with all the various flows kicking off after the main **Admin | Sync Template v3** flow - so the flows for Apps, Flows, Desktop Flows, etc we currently do not have logic to know when the last flow is done running and the inventory is thus complete. I like your suggestion of storing the flow runs - that's a great idea! We'll have to evaluate the impact on API calls, performance etc here but we'll add that also to our backlog for investigation!

Thank you for the fantastic write up and suggestions - really appreciate the effort you put into writing this up and providing the feedback to make the CoE better! And thanks for using the CoE!

**Comment by miroslav-harlas** [comment]
Thank you VERY much for explaining the reasons for having DelayInventory in place. That is something I was not aware/not thinking about, I have learned something new today. Thank you for this clear and understandable explanation. 😊

Please, try to consider at least the use of Concurrency Control option for some of the key flows with schedule trigger.
Thank you.

**Comment by manuelap-msft** [comment]
To be very honest, we've been intentionally a little bit vague about the reason for DelayInventory as it's a bit of a clunky solution to the problem we had. Glad to hear the full explanation made sense! 

Yes, my colleague and I just had a call on the Concurrency Control and we too learned something new today - we should be able to add this for the October release, if our testing goes well!

**Comment by Jenefer-Monroe** [comment]
We cannot do this after all as the setting makes manual runs of the scheduled flow no longer work which breaks things like full inventory runs. 
![image](https://user-images.githubusercontent.com/89584709/189931130-e511bfda-8bbd-4b45-b27c-f2c9d57fc88d.png)

Further the setting cannot be undone so its not something that users could just undo on their own when they want to manually trigger. 
![image](https://user-images.githubusercontent.com/89584709/189931530-5b7ac46b-aedd-4301-a20b-ed8bd5812ab8.png)

**Comment by Jenefer-Monroe** [comment]
Hopefully the work for https://github.com/microsoft/coe-starter-kit/issues/3604 and the upcoming BYODL will be sufficient. 
Thank you for the suggestions.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
