### ISSUE TITLE
[CoE Starter Kit - QUESTION] Shared Groups are coming back as 0 or empty

### ISSUE THREAD

**Issue by Nass92700** [microsoft/coe-starter-kit#3631]
### What is your question?

why the total group shares are empty or "0"? i have some apps shared with power platform users of type "group" and are counted in the total shared

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

admin view

**Comment by manuelap-msft** [comment]
Is this flow running **CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)** and can you check it has any failed runs?

**Comment by Nass92700** [comment]
Yes it's running well

![Capture d’écran 2022-09-13 191011](https://user-images.githubusercontent.com/113169835/189964508-1f6fbb5c-e94e-4209-9189-6839eefce88a.jpg)

**Comment by Jenefer-Monroe** [comment]
Since we dont repro I'm afraid you will have to find a repro in there to show us. 
Find a repro app where you expect a number other than zero due to a group, and note its Envt ID
Go to **_CLEANUP HELPER - Power Apps User Shared With_** flow and run in, entering the Envt ID
![image](https://user-images.githubusercontent.com/89584709/191082908-ad417fe0-6220-4196-a99e-3e4bef89dc84.png)

When the run completes, find your repro app in the list returned from Get Apps as Admin, get its index and find it in the loop, We will need to see what happens in the loop
![image](https://user-images.githubusercontent.com/89584709/191083245-74122f81-dc12-4b22-a242-6a2cd1b53a5f.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
