### ISSUE TITLE
[CoE Starter Kit - BUG] Apps shared groups = 0 for Teams apps

### ISSUE THREAD

**Issue by Nass92700** [microsoft/coe-starter-kit#3692]
### Describe the issue

I runned the cloud "Admin | Sync Template v3" with childs flow, the environment variable fullinventory = true.

These are Teams applications created with the Teams environment by an owner and shared with a Teams group that I find well in the power platform user of the group type with and a group size.

The Apps shared groups = 0 for the Teams apps

I shared CoE apps with a groups and run again the flow and the apps shared groups is correct.

it looks like flow is not working properly for teams apps

Sincerly

![shared](https://user-images.githubusercontent.com/113169835/190636103-87217c29-bd72-4873-8d3e-7561956252f7.jpg)
![sahred7](https://user-images.githubusercontent.com/113169835/190636240-2fbb2a56-e6bc-45b1-ae59-d8b97acf837f.jpg)
![sahred6](https://user-images.githubusercontent.com/113169835/190636250-fa2a3f1d-1fe2-49e6-8d62-588d19a66805.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

I runned the cloud "Admin | Sync Template v3" with childs flow, the environment variable fullinventory = true and delay = false

**Comment by Jenefer-Monroe** [comment]
Hello I do not repro this. Can you please show me how you shared the app?

**Comment by Nass92700** [comment]
Hi Jenefer,

I juste shared the app in make.power apps with users

![Capture d’écran 2022-09-26 165943](https://user-images.githubusercontent.com/113169835/192311398-6aaeb98c-4781-4215-bfa3-491df96bf4b7.jpg)

**Comment by Jenefer-Monroe** [comment]
The flow that collects this information is **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With_**. I assume you have that on and running. If so, you will need to test your case since I dont repro. 

Run its helper by clicking run and then plop the envt url of your repro app 
![image](https://user-images.githubusercontent.com/89584709/192360472-6bbaa941-44c8-4cd4-ab4e-9d062ec4d909.png)

Open the resulting run, find your app in the apply-to-each shown here and then we will walk it together
![image](https://user-images.githubusercontent.com/89584709/192360680-1b9901ae-dd1c-4df7-bd8b-2ee60913a802.png)

**Comment by Jenefer-Monroe** [comment]
Looks like we have this posted twice. Duping this to https://github.com/microsoft/coe-starter-kit/issues/3631
Plese track there
