### ISSUE TITLE
[ALM Accelerator - QUESTION] Deploy Solution with ALM using Environment Maker Security Role to application user

### ISSUE THREAD

**Issue by shree2905** [microsoft/coe-starter-kit#3708]
### What is your question?

We have a environment where we can not assign "System Administrator" security role to the Application User due to the policy. To commit the solutions in this environment using ALM I've assigned the "Environment Maker" security role instead of system administrator. 

Once I run the "export-solution-to-git" pipeline, It throws error for Publish Customization and Export Unmanaged tasks. I've added the snap of the errors below respectively. 

![image](https://user-images.githubusercontent.com/79618656/191081643-e9be612f-09ac-4cb9-8aba-b9bdd4ba31d0.png)

![image](https://user-images.githubusercontent.com/79618656/191082318-c11013a4-000c-4b1d-8503-ba85d3ac6748.png)

When I checked the privileges of the Environment Maker security role, It has access to Publish Customization, Export Customization and Import Customization over the Organization. The user with the same security role can perform Import, Export and Publish operation in the Environment. Where if I used the same security role to the application user, I'm getting errors.

![image](https://user-images.githubusercontent.com/79618656/191083109-ec1a806c-8038-488a-ac39-ad3415d26761.png)

Que. 1: Why ALM is not able to perform operation using Environment Maker security role where a normal user can perform the same operation with the same role. 

Que. 2: How to perform ALM operation using Environment Maker Security Role to application user? what extra access/privileges it needs to make it work seamlessly. 
 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

May 2022

**Comment by mikefactorial** [comment]
@shree2905 unfortunately, we haven't investigated app user permissions required if system admin is not allowed. The specific error in the second error message appears to be that the user doesn't have read permissions to the 'process' table. I'd recommend creating a new role based on environment maker and adding read/write to that table, based on my investigation. You can also try adding System Customizer to the app user's roles and see if that works. If it does you may want to inspect the specific permissions available to System Customizer and add those to your custom role. Note that based on what components are included in a solution your custom role may need to be updated over time. In particular if you are importing data as part of the pipelines since the app user will need the appropriate permissions to the tables to write / read data or there additional components included in a solution that require specific priveleges. If you are able to find a solution it would be helpful for us if you could let us know as others may have similar requirements.

**Comment by shree2905** [comment]
@mikefactorial Thanks

**Comment by mikefactorial** [comment]
Closing this out for now as this is a paltform issue and not specifically related to the ALM Accelerator
