### ISSUE TITLE
[CoE Starter Kit - QUESTION] Help with custom flows

### ISSUE THREAD

**Issue by gargkr** [microsoft/coe-starter-kit#3711]
### CoE - Possibility to automate reporting and send notification

Hello everyone, 

 

We are in the stage of adopting CoE in our company and we wanted to automate administrative tasks so we could get report notification whenever - 

A new PowerApp/Power Automate/Virtual Agent is created in default environment
Whenever a new Environment is created (manully or even from Teams)
Report with maker/owner for App/flow in each environments
Report with all flows/apps which are not in used since last 1 month for example. 
We know that CoE is dashboard where we can find all this information manually but we wanted if this could be automated and responsible person can recieve this information or reporting via email or any notification without logging into CoE dashboard environment. 

 

Thank you in advance. 

 

Regards

Krishn

### What solution version are you using?

3.19

**Comment by Jenefer-Monroe** [comment]
These would all be possible and pretty easy. We are not staffed to assist with such customizations, but I can give you an idea with one to get you started

EX: Send mail to admin when a new PowerApp is created in default environment
You would create another solution in your CoE Environment called something like "CoE Extentions"
In there you would add a  flow called something like "Admin Extended: Send mail for new App in Default" 
Start with the same trigger as **_Admin | Sync Template v3 (Apps)_** but change it to Added only instead of Added or Modified
![image](https://user-images.githubusercontent.com/89584709/191261969-432b9ac7-d75b-4231-b021-1b4d126472b9.png)

Then do a comparison to see if its default environment
![image](https://user-images.githubusercontent.com/89584709/191262783-774a08dc-ce4e-4dfa-bef1-0ee71d31b1ae.png)

And if so send the mail to the admin. 
I hope that helps!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
