### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Command Center - Reset Flows Fails

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3722]
### Describe the issue

In the Command and Setup Center | Admin when selecting Reset Flows for any of the Environment variables, The following error message is presented at the top of the screen:

CommandCenterApp>GetCoEFlows.Run failed: { "error": { "code": "WorkflowTriggerIsNotEnabled", "message": "Could not execute workflow 'e7c3857b-3cc2-0093-0ca2-af2ead3b182b' trigger 'manual' with state 'Deleted': trigger is not enabled." } }

![image](https://user-images.githubusercontent.com/17124284/191285232-cd8153e9-d2ca-47e0-9064-2c2eb452f604.png)

All of the Command Center flows are turned on.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Command and Setup Center | Admin

**Comment by Jenefer-Monroe** [comment]
Is this flow present in your Core solution? 
![image](https://user-images.githubusercontent.com/89584709/191288102-f9c2c1e6-971d-4bcc-bdfd-d2c4ffc8c929.png)

Note it was missing when we shipped 3.44 and so we hot fixed with Core 3.45. We also hotfixed Gov for another bug. 
Please download and install the latest package. You should see the following solutions
Core 3.45
Gov 2.21

**Comment by medicineshow** [comment]
yes that's our issue, thanks

**Comment by Jenefer-Monroe** [comment]
Good to hear. Please be sure to upgrade both Core and Gov. I'll go ahead and close this but please let us know if you have other issues!
