### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unknown & termed makers with model-driven apps & custom forms

### ISSUE THREAD

**Issue by alisoncyeh** [microsoft/coe-starter-kit#3760]
### What is your question?

What does **Unknown** in the App Maker table mean? Are these orphaned apps?

Also have a termed user who is still showing up in the App Maker table after using the Set App Permissions app to change ownership to a current user. All the termed user's canvas apps were properly transferred but their model-driven apps & custom forms still have the termed user listed as the owner.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Power BI Dashboard & Set App Permissions

**Comment by Jenefer-Monroe** [comment]
Hello we cannot programmatically change ownership for Model Driven Apps nor for SP Canvas Forms. You will need to go and migrate those manually to the new owner. 

Yes Unknown is orphaned, but so is blank. I believe there was a change and we used to put Unknown there and now we put blank.

**Comment by alisoncyeh** [comment]
Thanks Jenefer!

Follow up question: does a termed user not change the ownership for model-driven apps & custom forms to then orphaned? I'm unclear how the user is still showing up in the App Maker table if they don't exist in AAD anymore

**Comment by Jenefer-Monroe** [comment]
We keep these users in the Maker table even after they are removed from AD. This is so that we can keep that information as its helpful. For example it should show things like their former Manager and their department if it was available and collected before they were removed from the AD

The apps, the maker themselves, and all their objects, will show as orphaned once they are removed from AD if you are running the **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** flow.

We cannot programmatically change ownership for all those objects though, only for some.

**Comment by alisoncyeh** [comment]
Thanks! Is there a reason the Set App Permissions app only works for canvas apps?

**Comment by Jenefer-Monroe** [comment]
You bet! 

So unfortunately we can only do what the product exposes to us, and the permissions for those app types are not offered to us programmatically.

**Comment by alisoncyeh** [comment]
Got it, thank you!
