### ISSUE TITLE
[ALM Accelerator - BUG]: GetPowerPagesSites.Run failed

### ISSUE THREAD

**Issue by esosa61** [microsoft/coe-starter-kit#3764]
### Describe the issue

Every time I've made a commit i have an error displayed in red at the top saying

GetPowerPagesSites.Run failed: Connection not configured for this service.

### Expected Behavior

Not to see the error message

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

September 2002

**Comment by mikefactorial** [comment]
@esosa61 can you provide any error messages you see in the GetPowerPagesSites Flow or is it not running at all? If the latter can you verify that the user in question / the team the user is a member of has these roles?

![image](https://user-images.githubusercontent.com/42348035/192360065-a6477c3d-bdce-4421-aaa6-0ff4d1bb4ae1.png)

**Comment by esosa61** [comment]
Yes the user has the ALM Power App Access, the error display in any commit the solution has no PowerPages components

![image](https://user-images.githubusercontent.com/61057922/192401376-ade9c31a-7ff7-4455-b16a-e7632a7364f1.png)

**Comment by mikefactorial** [comment]
@esosa61 can you verify that all of the flows in the solution are turned on?

**Comment by bronsonacoutts** [comment]
I have the identical issue after upgrading from August to October.

Sure enough the Get Power Pages flow in the Solution was disabled.  

When I tried to enable, I received the error:  

`Turn on failed. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '91ba0602-96b2-4851-989a-b1008d01ee9a'. Connection '/providers/Microsoft.PowerApps/apis/shared_commondataservice/connections/shared-commondataser-eb01f1a5-4b55-454f-9def-7024-ac86173d' to 'shared_commondataservice' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".`

The account that installed the solution upgrade was different to the original user who installed the solution.  

 By getting the user who originally installed the solution to activate the flow, it activated fine.

That's as far as I was able to get without getting distracted, not sure if it has solved my problem yet or not, but I will check later.

**Comment by mikefactorial** [comment]
@bronsonacoutts thanks for sharing your findings, this doesn't seem like an issue with the accelerator. Possibly a platform issue.

@esosa61 were you able to resolve this issue?

**Comment by esosa61** [comment]
> @esosa61 can you verify that all of the flows in the solution are turned on?

The cloud flow GetPowerPagesSites was off, I turned on and there is no error.

**Comment by esosa61** [comment]
The cloud flow GetPowerPagesSites was off, I turned on and there is no error.
