### ISSUE TITLE
ALM Accelerator : Using Service Account as Flow Owners in downstream environments

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#3793]
Hi Team,

Could you please help us with the below problem.

We have to use service accounts as Flow Owners in downstream environments (UAT & PROD). We are able to do it using the Deployment Settings where we can specify the owner.

But, when it comes to connection references used by the flow, the connections created by the service account can't be used as the ALM Accelerator display the connections I own only.

So, if we need to have the service account as the owner of a flow and use its connection, what would be the best solution?

Thanks in advance !

**Comment by mikefactorial** [comment]
@tomjosbin for now someone would need to create the connections as the service account using the deployment settings in the app or if you are able to get the connection ids you could plug them into the pipelines directly. We have a backlog item to use the new capabilities available in the platform to share a connection with a service principal (https://github.com/microsoft/coe-starter-kit/issues/3307) which would allow the creator of a connection to share the connection directly with the SP that runs the pipelines, but there would still be a need for the service account to set the correct connections on the deployment configuration initially.

NOTE: Once a connection is created and set in the deployment configuration. If any other user doesn't have access to that connection it will show in the UX as an "Existing Unshared Connection". Unfortunately, this is limitation in the platform today. That we have no way to workaround in the accelerator due to how oAuth connections work.

**Comment by rfarris2000** [comment]
What I am seeing when this happens is the user and connection value are being blanked out:

	{
		"Data": "/providers/Microsoft.PowerApps/apis/shared_approvals",
		"Name": "connectionreference.approvals",
		"Value": ""
	},
	{
		"Name": "connectionreference.user.approvals",
		"Value": ""
	}

This causes the pipeline to fail.  Right now I'm going into each environment as the service account and setting the connection manually for each deployment.  Approvals is a weird one because you can't switch the user when the connection is created.

**Comment by rfarris2000** [comment]
@mikefactorial Have you seen this at all?

**Comment by mikefactorial** [comment]
@rfarris2000 pardon the delay. I can't say that I have. I'll need to try to replicate it and get back to you.
