### ISSUE TITLE
[CoE Starter Kit - Feature]: Environment Variables Required for Inactivity notifications Flow

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3795]
### Is your feature request related to a problem? Please describe.

The Admin | Inactivity notifications v2 (Clean Up and Delete) flow says has configurable time for the Get past time for archivals ready to delete step, however this is not an environment variable and so would create solution layering.

### Describe the solution you'd like

An environment variable for the following steps in the flow:
Recurrance
Get past time for old archival requests
Get past time for archivals ready to delete

**Comment by medicineshow** [comment]
sorry just realised wrong subject. I will close and change to CoE

**Comment by mikefactorial** [comment]
@manuela-msft this may have gotten lost due to it being assigned to the wrong project.

**Comment by Jenefer-Monroe** [comment]
Hello. Yes this got lost, thank you for moving over for us. 

Since this is so old, please let us know if its still relevant or if we have resolved with [these environment variables](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components#all-environment-variables)

![image](https://user-images.githubusercontent.com/89584709/215216201-91433144-53bb-4ffa-a5fd-4ab2ced80065.png)
