### ISSUE TITLE
Flows pending suspension empty

### ISSUE THREAD

**Issue by raphaeltremblay1966** [microsoft/coe-starter-kit#3811]
We have received Microsoft notice MC428527 · Published Sep 9, 2022, in the Message Center regarding flows not being compliant. 

In the notice, we have instructions to look after the Flows Pending Suspension tile in the Governance Power BI dashboard, but that is empty. The field is also empty in the CoE Admin View. Is there something we are missing ? 

We are running CoE 3.45 September 2022

![image](https://user-images.githubusercontent.com/99994964/193079249-c3e74607-bcf7-4029-91a4-f44f6dae1257.png)

![image](https://user-images.githubusercontent.com/99994964/193079436-ccd1fa04-ee93-4aea-86e6-f6632c480652.png)

![image](https://user-images.githubusercontent.com/99994964/193078441-4b8e5e53-188e-47ee-8d44-bdc88959ca04.png)

**Comment by Jenefer-Monroe** [comment]
This will only be filled if you have some flows that are pending suspension and if the jobs the product runs to detect these have run in your tenant. 

Do you have cases you expect to show up here that are not? 

And then we do have a bug (https://github.com/microsoft/coe-starter-kit/issues/3713) local fixed for Oct release in which flows that were not previously inventoried (missed in the past and never added) get added incorrectly. 

If you filter the Flows to Abandoned Flows. do you see the rows with flow suspension filled out? If so you you have been touched by that bug, please follow the notes in #3713 to fixed up or install Oct release next week to get that fix.

**Comment by millsmi** [comment]
Hi Jenefer,

We received Message ID: MC428527 from Microsoft.

"Our internal monitoring detected issues in your Power Automate instance that we need your attention to resolve. 
 How Does this affect me?Our internal monitoring has detected that some flows in your Power Automate instance fall into the following non-compliant categories: 

Premium flows without premium licenses: 

Flows are using premium features (premium connectors/custom connectors/HTTP connectors/On premise gateway/Business process flows) without a premium Power Automate license (Power Automate per user/Power Automate per flow license). This can happen because of the following reasons: 

Flows created by users who previously had trials/premium licenses that expired. 

Flows created by users who left the organization. "

This email then goes on to day

"What action do I need to take? 

In the latest version of Center of Excellence (CoE) Starter Kit (https://docs.microsoft.com/en-us/power-platform/guidance/coe/starter-kit), you can see a section for flows pending suspension due to non-compliance by performing the following steps: 

Select Flows Pending Suspension tile from the Power Platform Governing and Compliance dashboard. 

A dashboard will be displayed showing information about the flow, including the reason for suspension. 

Please assign a per flow license (https://docs.microsoft.com/power-platform/admin/power-automate-"

However, we do not see anything relating to pending suspension or suspended. I did open an MS case, and I was supplied a CSV file of ~90 flows with a pending suspension state, but cross checking them with the CoE, the CoE shows nothing.

**Comment by Jenefer-Monroe** [comment]
I'm glad you got the csv! Do you see those 90 flows if you filter the Flows to Abandoned Flows? 
If so you are hit by #3713 fixed in Oct release which we are preparing to ship.

**Comment by Jenefer-Monroe** [comment]
Can you please find a few of the flows in the list and let me know what you see? Are they inventoried at all?

**Comment by millsmi** [comment]
Using the default Flows view, I see 'Display Name', 'Flow Environment', 'Maker', 'Derived Owner'. 'Created On', 'Modified On', 'Flow State'.  When I open the records, they do seem to be inventoried correctly,

**Comment by Jenefer-Monroe** [comment]
Are the 90 flows all in your default environment? Or are they in other environments as well?

**Comment by Jenefer-Monroe** [comment]
And then for a sample flow that is in the list, can you please go to this flow's runs list, add the evnt column and then open the latest run for that environment. 
![image](https://user-images.githubusercontent.com/89584709/193833997-8d13b18a-43e9-4b55-ad19-0d30c9aa529c.png)

In that flow run instance, go to the **_Filter to tenant flows with estimated suspension data_** action. What is returned there? 
![image](https://user-images.githubusercontent.com/89584709/193834219-e3e0a87e-40e0-4ddd-a6dc-111756a7ef40.png)

**Comment by raphaeltremblay1966** [comment]
Hello - sorry for the delay. We don't see the Edit Column option, nor the estimated suspension data. 

Should we be running at some point Admin | Sync Template v3 (Flow Action Details) also ?
Thanks

![image](https://user-images.githubusercontent.com/99994964/195667046-c3b2651b-eefb-4d1a-a335-99e5de34bcda.png)
![image](https://user-images.githubusercontent.com/99994964/195666818-57aa857f-96f1-4e6b-b07f-1141845b8ee5.png)

**Comment by Jenefer-Monroe** [comment]
OK we can trigger it manually instead then. 

1. Find an environment in your tenant where you expect to see the a flow pending suspension but the report does not show one. 

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find **_Admin | Sync Template v3 (Flows)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. Note the picture here is for an Apps run but it will look the same otherwise
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. Scroll down to the **_Filter to tenant flows with estimated suspension data_** action. What is returned there? 
![image](https://user-images.githubusercontent.com/89584709/193834219-e3e0a87e-40e0-4ddd-a6dc-111756a7ef40.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team

**Comment by Jenefer-Monroe** [comment]
You likely have unmanaged layers blocking you from seeing our changes. Please see [Remove unmanaged layers from inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows)

**Comment by Jenefer-Monroe** [comment]
If after removing unmanaged layers you still see the issues, please post a new bug and reference this one, as that helps us more accurately track issues rather than re-opening old ones.
