### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Set Flow Permission 「Type NotSpecified: Cannot change permissions for this type in the app, please go to App Setting and change there」

### ISSUE THREAD

**Issue by jbst2018** [microsoft/coe-starter-kit#3840]
### What is your question?

Hi team.

I have a question about 「Set Flow Permissions」App.
I tried setting owner to orphaned flow using app.

Then, as in the capture, Type NotSpecified: Cannot change permissions for this type in the app, please go to App Setting and change there is displayed, and owner setting was not possible.

What does this display mean?

![image](https://user-images.githubusercontent.com/109139057/193761070-df045014-c4ae-44c9-aabc-ad4b7360bd31.png)

I checked same flow in the capture from the Power platform admin center.
The flow have a shared Microsoft 365 group.
Given this, does that mean Microsoft 365 Groups can't set owners from Set Flow Permission?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Set Flow Permission

**Comment by Jenefer-Monroe** [comment]
Hello it looks like the user type is not coming through which is why nothing else is coming through either. The types here are usually Group/User. I dont know what type it is but that seems to be the problem. Can you please click the Flow Settings button there (you may need to add yourself first if you dont have permissions already)
![image](https://user-images.githubusercontent.com/89584709/193860261-48e7b043-5043-4219-b93b-2e5ba0c7c7d3.png)


And then in the flow details screen that opens hit Share
![image](https://user-images.githubusercontent.com/89584709/193860540-bee8be34-458f-4450-814b-42ca4e63cf3e.png)

What shows up?

**Comment by jbst2018** [comment]
I checked and it looks like below
The blue frame was the user and the red frame was the Microsoft 365 group.
Given this, does that mean Microsoft 365 Groups can't set owners from Set Flow Permission?

![image](https://user-images.githubusercontent.com/109139057/194040050-fe7a4232-3f2f-4c88-ac57-702c7e9decb7.png)

**Comment by Jenefer-Monroe** [comment]
No we do support that group type. I wonder if its a language thing and the user type is being localized for you. 
Please note that the [CoE Starter Kit solutions are not localized](https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages)
You need to add the English language pack to your environment to make sure all apps and flows work.
[Regional and language options for your environment](https://learn.microsoft.com/power-platform/admin/enable-languages)

Can you please try that and let me know what you see?

**Comment by jbst2018** [comment]
sorry.
The English language pack cannot be applied because it is being introduced to customers.

Let me close this question.
