### ISSUE TITLE
Developer Compliance Center, when showing custom connector icon: The environment 'Default-' could not be found in the tenant 'xxxx'." 

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#3916]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/3874

<div type='discussions-op-text'>

<sup>Originally posted by **myatix** October  6, 2022</sup>
Can someone tell me why I am getting the following error in our Starter Kit Test Environment when accessing the Developer Compliance Center?

PowerAppsforAppMakers.GetConnectors failed: { "error": { "code": "ServiceToServiceEnvironmentNotFound", "message": "The environment 'Default-' could not be found in the tenant 'xxxx'." } }</div>

**Comment by akimble15962** [comment]
I am also receiving this error in the App Catalog as well as the Developer Compliance Center apps. I originally thought it was due to changing the default environment name to "Personal Productivity" as that's Microsoft's best practice, but I then I started receiving the error with the new environment name instead of Default.

**Comment by manuelap-msft** [comment]
Accidentally left open, fixed in some of the recent releases.
