### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin Planning Report - TDS endpoint

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#3942]
### Describe the issue

When opening the Admin Planning Report, on load it reports the following error. Not sure what SQL instance it's looking for...
![image](https://user-images.githubusercontent.com/93291159/195444877-8f4e89db-067a-4e58-bbfc-8990a1d42b67.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Power Platform Admin Planning Report

**Comment by manuelap-msft** [comment]
How have you entered the URL when connecting to Power BI?

This dashboard uses the TDS endpoint to connect to Dataverse and the URL has to be entered like this: org123.crm.dynamics.com - without the https in the beginning and trailing ? at the end. The SQL error message isn't related to a SQL instance, but to Dataverse and the TDS endpoint being used. We are using the Tabular Data Stream (TDS) endpoint that emulates a SQL data to connect to Microsoft Dataverse. You can learn more about the TDS endpoint here https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query

This error typically occurs if you have entered the URL including the https and trailing slash, see our Troubleshooting guidance here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting

If this doesn't help, there's some additional troubleshooting steps available on the Power BI site - if the URL has been entered correctly, errors can also be due to network configuration:
https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query#blocked-ports

**Comment by manuelap-msft** [comment]
Closing out as no further action required from CoE kit team. Please let us know if you continue to face issues.
