### ISSUE TITLE
[CoE Starter Kit - QUESTION] Incomplete Inventory

### ISSUE THREAD

**Issue by PowerVis** [microsoft/coe-starter-kit#3956]
### What is your question?

We noticed the sync templates are not pulling the records from the default environment whether its a new app or flow created. We found only a handful of apps got synced.  This issue seems happening since June. To test, we created 3 apps by3 different users, gave more than 5 days of time, and still, no data was found in Dataverse regarding the new apps created.  

Our normal monthly new power app creation will be between 1500-2500 apps, until the month of May we see this trend, and afterward, there seems a cliff fall in numbers.

Any thoughts on what could be the issue here?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin Sync template v3 | apps

**Comment by Jenefer-Monroe** [comment]
Are all the [inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) still on and running? 
Are there recent failures in the apps sync flow runs? 
Are the connections for the sync flows still owned by an identity that has PPAdmin? [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by PowerVis** [comment]
yes, they are running with issues, We get sync flow errors which list apps and flows has the issue to fetch information on them
There were failures in the past due to some connection references, but it is rectified 

The connections used in sync flow is an admin account.

How can we pull some of the lost records?

**Comment by Jenefer-Monroe** [comment]
Before figuring out how to fetch the lost records, lets see why you arent getting the new ones you added. 
Were their failures in the **_Admin | Sync Template v3 (Apps)_** flow for the environment you tested?

**Comment by PowerVis** [comment]
sorry for coming back late, as we were testing and looking for failures, but there are no failures and NO inventory as well.

**Comment by Jenefer-Monroe** [comment]
If it were because you had too many objects I would have expected a failure. 

Please get an example of an app you added that is not in the inventory. Note its app id, and it'senvironment 

Go to **_Admin | Sync Template v3_**, are the runs completing? If so please open the most recent run and look at the output of the Get Environments action. Do you see the environment of your target app? 
![image](https://user-images.githubusercontent.com/89584709/197193297-ec85d32b-a0d5-43bd-835c-fb6500bfd456.png)

If so, browse to the CoE environment > Core solution via https://flow.microsoft.com/ (this will let you add columns to the run)
Go to the **_Admin | Sync Template v3 (Apps)_** runs, add the environmentid column and find your target envts run. Open it
![image](https://user-images.githubusercontent.com/89584709/197194213-82c71c0c-7ccb-4127-8a57-f40f5eb1e873.png)

Go to Load Arrays > Get Apps as Admin. Do you see your app in the output? 
![image](https://user-images.githubusercontent.com/89584709/197194866-86b79b32-b002-4d7a-9835-3727909b89ea.png)

If so, go to Filter apps just below. Do you see your app in the output? 
![image](https://user-images.githubusercontent.com/89584709/197195583-6c6d033c-ae60-40d7-a100-92f705802f37.png)

If so, note its index in the output array. Find it in the Apply to each App and then we will continue on.
![image](https://user-images.githubusercontent.com/89584709/197195843-5fae94a1-da99-43a2-ac2e-1de6dd8b0c0f.png)

**Comment by PowerVis** [comment]
@Jenefer-Monroe   while we test found it is failing for the default environment with page buffer size. Even it is failing on maximum buffer.  This is same as the issue ##3957

![image](https://user-images.githubusercontent.com/25033013/198015074-892f66bb-a52d-4a6b-bb17-943d58c1fe82.png)

**Comment by Jenefer-Monroe** [comment]
It looks like they've hit a platform limitation due to the size of your tenant - the **_Get Apps as Admin_** action of the **_Power Apps for Admin_** connector can't return the page size of apps in your this environment. 

There's nothing we can do from a CoE Starter Kit perspective to overcome this in the sync flows. This is a limitation of the connector. The only option will be to onboard to the upcoming BYODL preview. Please see https://docs.microsoft.com/power-platform/admin/self-service-analytics

I have made your CAT team member aware of your situation so please work with him to get onboarded!
Thank you

**Comment by PowerVis** [comment]
We do have BYODL and established the pipeline and do have the past few months of data.  

So is it safe to say we have reached the limit on COE side and lookup DL  for future data?

**Comment by PowerVis** [comment]
@Jenefer-Monroe   thank you,  will check on the dataflow part and private preview with my CAT contact and take it from there.

So we can close this case?

**Comment by Jenefer-Monroe** [comment]
Yes nothing else to do with this bug then, I'll go ahead and close. 
Thank you!
