### ISSUE TITLE
[CoE Starter Kit - QUESTION] Sync Flow (Flows) errors with admin_flow with ID does not exist

### ISSUE THREAD

**Issue by PowerVis** [microsoft/coe-starter-kit#3957]
### What is your question?

Notice lots of sync flow errors, particularly on  sync flows | flows

and most of the issues on the flow template are related to the below error

![image](https://user-images.githubusercontent.com/25033013/195706491-40ed553c-857c-4cfc-80f7-a2dd01b6e0f1.png)

any thoughts on how to resolve this?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin Sync template v3 | Flows

**Comment by Jenefer-Monroe** [comment]
Hello, that is an error from this action which is used to determine if a flow is already in the inventory or not. It it errors, that means its not in the inventory yet and so that error is caught and the variable isNewToCoE to true. 
![image](https://user-images.githubusercontent.com/89584709/196049140-d33ef8f5-d434-4634-8f0f-26ad96d01ee7.png)


Unfortunately flow will cache the first failue to show for the flow even if its a caught failure. 
If the flow as a whole fails, it will fail somewhere below and the failure will not be a caught failure, you will need to find where it fails and is not caught.

**Comment by PowerVis** [comment]
Sorry for coming late,  we are still checking on our previous issue #3956   will update once we have checked and amended the changes.
