### ISSUE TITLE
[CoE Starter Kit - QUESTION] update full inventory write up to include note about restored objects

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#3970]
### What is your question?

Ever since we updated our COE Starter Kit for the current month, I have noticed that flows that we have restored in our tenant are not appearing in the Dataverse table or in the COE Start Kit apps. Example. the Power Platform Admin view or Set Flow Permissions. We can access the restored flows and are able to pull them up using PowerShell. Is there a specific flow that I need to make sure is running in the starter kit to make sure that it is updating the Dataverse table? I checked all the sync flows and do not see where any of them failed. 

Need some guidance on what I need to specifically look at to troubleshoot why these flows are not appearing in the dataverse table and in return appearing in the apps. I have more data where I have researched but do not want to put it on here.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2022

### What app or flow are you having the issue with?

All sync flows

**Comment by Jenefer-Monroe** [comment]
Do you have all the [inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on and running? And do they have any unmanaged layers on them? 
In particular, the **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** flow, and its child flows, are the ones that re-add objects if they were restored in the even that you are tracking deleted objects.

**Comment by Jenefer-Monroe** [comment]
Worked offline to figure this one out. 
Turns out when objects are restored from delete, their last modified date is not changed. For canvas apps and cloud flows we did an API saving feature to first filter all objects by modidifed date so these are not getting re-added. 
Solutions are
1) Full inventory run
2) Change date for that filter back
3) Save the objects when restored

This customer is doing the third option here and I will add to documentation.
