### ISSUE TITLE
[CoE Starter Kit - QUESTION] App usage reports

### ISSUE THREAD

**Issue by IonB1977** [microsoft/coe-starter-kit#3974]
### What is your question?

Hi there,
We installed the CoE Starter Kit and Power Bi dashboard for our Organization. 
I have a few questions related to CoE reposts.

For couple of the pages we do not get any reports: 

1. App usage does not show info at all. Can't select any range.
![image](https://user-images.githubusercontent.com/110121301/196195909-79721557-5540-4cf4-ad21-53a24f0950f0.png)

2. Info for flows is delayed up to 5 days. 
For example, we deleted couple of flows from one environment on Monday. We still see them in the Power Bi dashboard for few days. Only on Friday are gone from the reports.

3. 5.	Range selection does not work on any page. 
![image](https://user-images.githubusercontent.com/110121301/196196282-35661a5e-07df-428e-a9fc-06b4f2c55782.png)

Please let me know if any more info is need it as this is my first bug report.
Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Power BI dashboard reports

**Comment by Jenefer-Monroe** [comment]
Hello. The usage information is filled by the [Audit Logs](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog) solution which is a separate setup and requires you configure usage of a custom connector. 

And yes there are delays in the inventory. In particular we look for objects which have been deleted by this flow, **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_**, which is run every other week due to the number of API calls involved.
