### ISSUE TITLE
[BUG]: Power Automate Users of Flows

### ISSUE THREAD

**Issue by DarthVador** [microsoft/coe-starter-kit#398]
**Describe the bug**
The CoE is supposed to help admins make correct decisions when it comes to licensing.  Power Automate licensing has two main ones: per user plan and per flow plan.  For me to understand if I should license a flow, I need to know how many users are using it.  I can't find it in the "admin_powerplatformuserroles" table.  I only see App stuff.

**To Reproduce**
Import in the table, admin_powerplatformuserroles, but no flow user info

**Expected behavior**
I would expect to see user information for those using each flow.

**Additional context**
Example of a licensing scenario.  If I have one user licensed for a flow and there are five users accessing it, then we should have 6 licenses.  But if I have one flow and it is accessed by 200 users, it might be better to license that via per flow plan.

**Comment by JeneferM-MSFT** [comment]
Hello. Thanks for using CoE. 

Licensing information is a common ask but unfortunately its not something that we have access to programmatically in order to help admins monitor and control it. It is in our backlog to continue trying to get the information to add to the toolkit though.  ​

Closing  out since there is no action for the tool kit today.
