### ISSUE TITLE
[ALM Accelerator - QUESTION] Least privilege role for App Registration Azure

### ISSUE THREAD

**Issue by conawpa** [microsoft/coe-starter-kit#4022]
### What is your question?

Hi Team,

our Azure Global Admins are reticent to provide a high level of access to the App Registration to run the ALM Accelerator installation process.  Can we apply Contributor and be able to run the script to configure all the access points to DevOps and Power Platform, etc or can someone explain an approach we can take to start off with a higher level, then backoff to Contributor?

Help

Paul Conaway
paul.conaway@lamresearch.com

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.00.72

**Comment by mikefactorial** [comment]
@conawpa thanks for the question. The install does require a user with elevated access to Power Platform and Azure in order to create app registrations (Service Principals) in Azure and App Users in Power Platform. As well as the ability to import the solution and configure the solution.

The service principal created to run the pipelines requires elevated permissions in order to deploy solutions into power platform environments. 

Normal users of the app require only a Basic User license and contributor permissions to the projects in Azure DevOps and Environment Maker permissions in the Power Platform environments they are building or deploying to. The latter is to allow makers to configure connections in downstream environments prior to deployment.

Hope this helps. Feel free to follow up if there are more questions.

**Comment by conawpa** [comment]
Thanks Mike, after the install script is run, can we drop the permission to contributor?

**Comment by mikefactorial** [comment]
@conawpa looks like your last question was missed. There's no reason you can't remove permissions after the script runs. However, the user may see some errors show up in the ALM Accelerator App if they aren't able to at least read the status of pipelines since the app will attempt to poll for pipeline runs to check their status. Closing this issue out for now. Feel free to open a new issue with any other questions.
