### ISSUE TITLE
Developer isolation vs Shared environment 

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/coe-starter-kit#4030]
### What is your question?

We are currently working on an HR onboarding solution with two developers. As it exists right now each developer has their own environment and each developer is working on different pieces. 

However, we are soon getting to the point where there will be overlap. What is the recommendation for a multiple developer per solution scenario?  Should we abandon the multiple developer environment and move to a shared environment scenario?

Will this be addressed in the platform and by extension the accelerator?  I’m beginning to rethink the developer isolation scenario. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

October 2022

**Comment by sdhsynsci** [comment]
@rfarris2000  We have tried both approaches, shared dev environments and dev specific environments. Both have problems and we have lots of trouble merging after devs have had a branch out for too long.  And in a shared dev environment half done work gets committed frequently. We just implemented AA4PP before we built our own AzDo ALM setup.  And that has been a journey in and of itself.  But now that we have it setup and almost working, we see the opportunity to support both approaches the way the AA4PP creates dev branches even if you are working in the same environment.  Our current thinking is we can support both, we will keep a shared dev for each layer of our solutions (Platform, Product, Client Project).  However, if a Dev is going to do something brand new non-connected and or unknown, they can check out the unmanaged solution to a separate dev environment and work on it and check it in when done.  We would love to know how others are approaching this topic and what is the advice from AA4PP team.

**Comment by Ballzer0** [comment]
We have done complete developer isolation. We usually try to decouple our solutions so that we can work on different solutions in paralelle.  

We have also devided our solutions into 3 parts. 

- **QuantusDoc** only contains table information, (columns, relations and keys)

- **QuantusDocPA** only contains power automates associated to the Doc solution. We did this because we always use **solution-upgrades** when we update power automates

- **QuantusDocUI** contains all views, forms and apps associated with the solution. This is so that we can easily update the UI eliments without being afraid that we accidentally update the data model and delete a field etc.

its a bit much, but we divide tasks based on who is good. For example we have a dedicated UI guy that focuses on the UI solution. 

example:
![image](https://user-images.githubusercontent.com/28560729/197825671-96ab8a07-5e15-49f6-9873-2df22d4491e5.png)


- We always end our work days by deploying to the test environment
- We always start our work days by pulling from the test branch 

this way we stay in sync. And we use a lot of communication to make sure 2 people arnt working on the same solution.

im interested to hear how others have been using the tooling

**Comment by Ballzer0** [comment]
> We have done complete developer isolation. We usually try to de-couple our solutions so that we can work on different solutions in parallel.
> 
> We have divided our solutions into 3 parts.
> 
> Example
> 
> * **QuantusDoc** only contains table information, (tables, columns, relations and keys, security roles, and column security profiles)
> * **QuantusDocPA** only contains power automates associated to the Doc solution. We did this because we always use **solution-upgrades** when we update power automates
> * **QuantusDocUI** contains all views, forms and apps associated with the solution. This is so that we can easily update the UI eliments without being afraid that we accidentally update the data model and delete a field etc.
> 
> its a bit much, but we divide tasks based on who is available or skilled at a certain topic. For example we have a dedicated UI guy that focuses on the UI solution.
> 
> example: ![image](https://user-images.githubusercontent.com/28560729/197825671-96ab8a07-5e15-49f6-9873-2df22d4491e5.png)
> 
> * We always end our work days by deploying to the test environment
> * We always start our work days by pulling from the test branch
> 
> this way we stay in sync. And we use a lot of communication to make sure 2 people arnt working on the same solution.
> 
> im interested to hear how others have been using the tooling

**Comment by rfarris2000** [comment]
Up until this point we have been doing developer isolation.  However, we are trying to bring developers up to see with the tooling and processes, it's required us to start using "pair programming".  With developer isolation and in particular how the platform works with unmanaged solutions this isn't really a long-term solution.  We are now going to a shared environment approach which I'm foreseeing will bring other issues.

**Comment by Ballzer0** [comment]
> Up until this point we have been doing developer isolation. However, we are trying to bring developers up to see with the tooling and processes, it's required us to start using "pair programming". With developer isolation and in particular how the platform works with unmanaged solutions this isn't really a long-term solution. We are now going to a shared environment approach which I'm foreseeing will bring other issues.

yeah, its actually quite a challange seeing how solutions just "merge together" if they are all unmanaged. 

For us, we have to install the "core solution" as managed on our development environment before we can start working on the UI solution.. This is a lot of extra hassel

**Comment by mikefactorial** [comment]
Closing this thread as there hasn't been any activity in several months
