### ISSUE TITLE
[CoE Starter Kit - BUG] Approvals | Power Automate Notifications not going to Owner of the flow 

### ISSUE THREAD

**Issue by declawson** [microsoft/coe-starter-kit#4047]
### Describe the issue

From COE-Core > Power Platform Admin View > Flows -  I can view the actual 'Maker' & 'Derived Owner' for flows in each environment.  I can also see that I am listed as the Owner for ALL flows. I am the Power Platform Admin for the tenant.

The issue is Approvals | Power Automate notification emails 'This flow appears to be unused; can we delete? <Flow Name> are all coming to me and not the 'Maker' or 'Derived Owner'.    

The emails also state 'OWNER DOES NOT EXIST. APPROVAL SENT TO ADMIN.'  even though I can see that 'Maker', "Derived Owner' and 'Owner' are all populated from the Power Platform Admin View'.

In addition, I 'Reassigned' many of these to the 'Maker/Derived Owner' and the maker of the flow approved deletion but I am now getting notification emails 'Reminder to back up your Flow: <flow name>. 

### Expected Behavior

I expect all notification emails to be sent to the 'Derived Owner' to Approve/Reject deletion. As well as the reminder to back up the flow prior to deletion.

Obviously, the purpose of the governance module is to cleanup unwanted/unused flows by the flow owners themselves not the Admin.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.20

### What app or flow are you having the issue with?

App and Flow Inactivity Notifications Clean Up View

**Comment by Jenefer-Monroe** [comment]
We do not use the Owner column, thats filled in as you because its your identity running the inventory flows, it just means taht you "own" the line in inventory. We dont use it in this flow, we rely on derived owner column if it contains data, else Maker column.

This can happen on purpose for a few reasons
1. You have the ProductionEnvironment env variable as false
You can check this one by looking at a recent run, what value is shown for isProd
![image](https://user-images.githubusercontent.com/89584709/198143932-9194a2dd-9024-4221-82b9-cc7323832cd5.png)

2. The flows are flagged as orphaned
3. The flow owner is a service principle. 


You will need to open the recent run and find a case in the the flow and walk it with me otherwise to see what happened, since we do not repro. 
Hope that helps

**Comment by declawson** [comment]
Thanks, that fixed it. 

FYI, the admin_Production env var in the def solution was 'Default = Yes' but 'Current = No' in the Managed Solution. I reset the env var.

**Comment by Jenefer-Monroe** [comment]
Wonderful, thank you for letting me know!
