### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by BillatClearBank** [microsoft/coe-starter-kit#4073]
### What is your question?

I am seeking clarification of the limitations, which say that "The Admin | Sync Template v3 (Flows) flow will fail to collect inventory information for flows that were imported or are owned by a service principal." 
We have a number of such Flows that do appear in the CoE tables. Thus:
a/ is this limitation still current?
b/ are there perhaps other permission settings, other than the connections account, that affect the discovery of flows (e.g. environment roles)?
c/ How might we ensure that we don't Block an already used connector via DLP?
Thanks

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
a/ is this limitation still current?
Will investigate and return here with answer

b/ are there perhaps other permission settings, other than the connections account, that affect the discovery of flows (e.g. environment roles)?
You need to have the [Power Platform Admin role](https://learn.microsoft.com/power-platform/admin/use-service-admin-role-manage-tenant#power-platform-administrator) in order to see all flows form all environments. 
See also: [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

c/ How might we ensure that we don't Block an already used connector via DLP?
You can use the [DLP Editor app](https://learn.microsoft.com/power-platform/guidance/coe/core-components#dlp-editor-v2), it has an impact analysis tool in it.

**Comment by BillatClearBank** [comment]
Hi Jenefer
That's great and thanks for the response and information.
Supplementary question: 
I've used the DLP Editor App (great, BTW) but doesn't it just use the same collected metadata? My problem is that I think the CoE Flows aren't picking up some of our Flows, so suspect that this app won't either
Thanks

**Comment by Jenefer-Monroe** [comment]
It looks like the service principle limitation has been fixed by the product. YAH! Thank you for that information, we will update our documentation for the November release. 

You are correct, the DLP Editor reads off the inventory. So if an app or flow is missing from the inventory then it will not appear in the impact analysis search. 

Do you have examples of flows you think are missing?

**Comment by Jenefer-Monroe** [comment]
You can do a [full inventory](https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory) run as well. If your tenant isnt too large this is an option to "reset" the inventory if you think something may have gone wrong.

**Comment by BillatClearBank** [comment]
Hi Jenefer
As far as I can tell, Flows which sit within a Solution are found only if they are turned ON. Whilst we also have some Flows which show in BOTH the Solution and the CoE but are turned OFF, I suspect that these were previously ON.

Is this a likely possible explanation of my CoE data?
Thanks again for your help

**Comment by BillatClearBank** [comment]
Hi Jenefer
I had a further look at my Flows and the notes and I realised that I misunderstood this particular limitation:
_Flows that have never been turned on
The Admin | Sync Template v3 (Flows) flow will fail to collect flows that have never been turned on. For example, if you import a solution with flows that are off, these will not be collected to inventory as they are not returned by the connector._
...from [https://learn.microsoft.com/en-us/power-platform/guidance/coe/limitations](https://learn.microsoft.com/en-us/power-platform/guidance/coe/limitations)

It gives me a question as to how the system interprets "flows that have never been turned on" when the CoE is first installed. Does it really mean "never"  or is it just since the installation, i.e. does the Flow itself somehow flag that it has been ON previously or is it that the CoE picks it up if it's ON and subsequently updates even if it is subsequently set to OFF? I hope this makes sense but if not, let me know

Thanks again for your help with this

**Comment by Jenefer-Monroe** [comment]
yes it does make sense. It means literally never turned on. The product connector doesnt return them if they've never been registered as active. 
Hope that helps!

**Comment by BillatClearBank** [comment]
Sorry to query again, but I just want to be clear: 
You're saying that if a solution based Flow has at any time been ON but is OFF at the time of a first time install of the CoE, it should be picked up by the Flows and logged in the COE?

**Comment by Jenefer-Monroe** [comment]
It should yes. And that comes down to, is it returned by the **_Get Flows as Admin_** action.

**Comment by BillatClearBank** [comment]
That's great. Thanks again
