### ISSUE TITLE
[ALM Accelerator - BUG]: Export Solution Pipeline Error

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#4091]
### Describe the issue

Hi Team,

Could you please help us with the below error.

Error running pipeline: CustomAzureDevOps.RunPipeline failed: {"$id":"1","innerException":null,"message":"See https://aka.ms/AzPipelines/SettingVariablesAtQueueTime - You can't set the following variables (Branch,BranchToCreate,BuildDefinitionId,CommitMessage,Data,Email,EnvironmentName,ImportUnmanaged,PipelineId,Project,Repo,ServiceConnection,SolutionName,UserName). If you want to be able to set these variables, then edit the pipeline and select Settable at queue time on the variables tab.

The commit solution step is failing with this error.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

 1.0.20220517.1

**Comment by mikefactorial** [comment]
@tomjosbin this is due to a security update in Azure DevOps. We've moved away from using variables in our pipelines due to this change and are using parameters instead. I'd recommend upgrading to the latest version of our pipelines and the ALM Accelerator app. You may still be able to disable this setting in your Azure DevOps project settings.

![image](https://user-images.githubusercontent.com/42348035/199258924-71cf69c3-1145-41ea-b522-803b83c1c7cb.png)
