### ISSUE TITLE
[CoE Starter Kit - BUG] PowerApp Maker Environment variable populated without the '/' 

### ISSUE THREAD

**Issue by shriyamal** [microsoft/coe-starter-kit#4136]
### Describe the issue

The URL when clicking on the app settings button in the Set App Permissions app is missing the / in the URL as it tries to launch 
https://make.powerapps.comenvironments/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/details

A / is needed between "com" and "environments"

### Expected Behavior

To launch the App Settings of the app selected correctly 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

NA

**Comment by manuelap-msft** [comment]
This URL is compiled with the value from the **PowerApp Maker environment variable** which we have in place as different clouds have different URLs. We ask that the URL is entered with the trailing slash - likely you have entered it without the / in your environment and that's why the link doesn't open correctly:
![image](https://user-images.githubusercontent.com/55705669/200547754-6a378a83-a4a5-4fa9-bd6c-87705f481a29.png)
