### ISSUE TITLE
The size of the request is too long

### ISSUE THREAD

**Issue by rsantos00** [microsoft/coe-starter-kit#4138]
### Describe the issue

When I'm defining deployment settings for my solution I get an error with GetSolutionConnectionReferences.Run failed.
Looking at the flow error I can see there is a huge number of objectids being passed in the headers:

![image](https://user-images.githubusercontent.com/3724826/200544571-6bd5a17f-21a0-4374-ba1c-5e3130813ea9.png) 

![image](https://user-images.githubusercontent.com/3724826/200544751-73a52ab4-5335-45e9-8e99-da61a68215fd.png)

which leads to the error in the "Get Solution Components" DV connector:

![image](https://user-images.githubusercontent.com/3724826/200544682-62abe5ef-31cb-4127-bc2d-f3d66edd99e7.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

November release

**Comment by mikefactorial** [comment]
There are two options to move forward with this issue. This is related to limitations in the legacy Dataverse connector that we can't currently work around. Once the current Dataverse connector has support for cross environment queries we should be able to resolve this.

1. Move some of the unmanaged solutions out of the same dev environment since there are so many connection references in one environment.
2. Update the flow to query solution components before querying connection references. We could make this update if we think that the number of connection references in an environment would for the most part be greater than the number of solution components in a solution. We could also remove the filter from the solution component query and compare ids after we get the complete list of components and connection references.

**Comment by rsantos00** [comment]
Currently, in the dev environment, there are 281 connections and 149 connections in production. The number of environments is a lot lower than that.

**Comment by rsantos00** [comment]
@mikefactorial: This solution fixed the problem
