### ISSUE TITLE
[CoE Starter Kit - BUG] Error message when importing Core components solution

### ISSUE THREAD

**Issue by RahulBLK** [microsoft/coe-starter-kit#4165]
### Describe the issue

The environment is created using the service account but while uploading the Core components zip, we get a generic error regarding missing the necessary privileges.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Core Components Solution import

**Comment by RahulBLK** [comment]
We can connect on Teams for further troubleshooting.

**Comment by Jenefer-Monroe** [comment]
Hello, sorry we are not staffed to meet with our GitHub users. Debugging will need to done here. You will need to share the error message and some screenshots please. 

Please also note that you are trying to install the Sept 2022 version while the [Nov 2022 version](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2022) is available. 

These are the permissions needed in order to install and run Core: [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by RahulBLK** [comment]
I am not able to upload error screenshot, but while importing solution via a service account (also the creator of environment) we are getting a generic error of "You are missing the necessary privilege to import solutions in this environment.".

Following the suggestion, we did try with November (latest) code as well but no luck.

**Comment by RahulBLK** [comment]
Kindly let me know how to troubleshoot ?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
