### ISSUE TITLE
Powerapps not showing in the dashboard

### ISSUE THREAD

**Issue by Salampop** [microsoft/coe-starter-kit#4192]
### Describe the issue

the powerapps applications list is empty in the dashboard (powerbi) template

### Expected Behavior

to see the list of all the applications within the environment 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2022

### What app or flow are you having the issue with?

V3

### Steps To Reproduce

Bo Error message

### Anything else?

Nope

**Comment by manuelap-msft** [comment]
Let's check a couple of details first

- Are all your Admin - Sync flows running without failure? You can check in the Admin - Command Center to see if there are any failures
- When you open the Power Platform Admin View, do you see your apps and flows inventory there?

**Comment by Salampop** [comment]
and yes, all admin flows are working without any issue.

**Comment by manuelap-msft** [comment]
If you can see the Apps in the Power Platform Admin View but not in the Power BI dashboard, you may have not configured scheduled refresh on the Power BI dashboard so it's not up to date with the data in the Dataverse tables.

Also note that in the October release we had some hardcoded filters shipped with the dashboard that you may have to remove manually if you're on that version (this was fixed in the November release). Here's the issue https://github.com/microsoft/coe-starter-kit/issues/3877 that contains some info on what was hardcoded.

**Comment by Salampop** [comment]
thanks, waited 24 hours and they are showing now.

**Comment by manuelap-msft** [comment]
Great, thanks for confirming!
