### ISSUE TITLE
[Power Platform communication site template] File Not Found errors in Deploy-PowerPlatformHub script

### ISSUE THREAD

**Issue by expiscornovus** [microsoft/coe-starter-kit#4206]
### Describe your bug, question or feature ask.

When running the Deploy-PowerPlatformHub.ps PowerShell script I am getting some errors for a bunch of the SiteAssets image files:
https://learn.microsoft.com/en-gb/power-platform/guidance/adoption/wiki-community#run-the-powershell-scripts

I am also seeing warnings: _skip adding/updating custom actions because the site has "noscript" enabled_

![sitesassets_images](https://user-images.githubusercontent.com/22542376/202252566-d1aa96b5-15bb-4ff6-ab5c-261070e6e491.png)

I will try and reproduce this also on another demo tenant.

**Comment by Laskewitz** [comment]
Hey Dennis - 

No worries. This is perfectly normal. We don't do anything with custom actions and the file not found errors are because the PnP Provisioning Engine we are using checks first if the file is already there and if not (file not found) it creates the file for you. It should have deployed all the files. Sorry for the worrying output, but it's nothing to worry about. 😁

Does the site look alright? Or do you have a broken site?

Thanks,
Daniel

**Comment by expiscornovus** [comment]
Hi Daniel,

Yes, the site looks perfectly normal. Thanks for the clarification. 

In that case I will close my comment, thanks for your help :)
