### ISSUE TITLE
[CoE Starter Kit - QUESTION] Change cleanup flows from six months not modified , to just six months not launched

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4210]
### What is your question?

Having an issue with following flows -

Admin | Inactivity notifications v2 (Start Approval for Apps)
Admin | Inactivity notifications v2 (Start Approval for Flows)

May be other governance flows like these, but these are the two main culprits, especially the flows.

When these flows are ran, a few thousand emails are sent out, sometimes 2-300 to a single user.
The problem is, they're nagging my users to delete flows / apps that have been ran in the past six months, but not modified.  If it isn't broke, don't fix it applies here.  There are some flows / apps that do not need to be modified because they work well, it doesn't mean they should be marked for a deletion request.  I see the logic in this, but it does not apply to our environment.

Is it possible to just take the "modified" part out of these otherwise helpful cleanup flows and just leave the launched.  If it wasn't launched for six months, then yes I understand, there probably isn't a need for it.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Oct 2022

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

**Comment by manuelap-msft** [comment]
Hello,

1. For apps, we do have launch information available if you use the Audit Log solution
2. For flows, we do not have launch information available as there's no way for us to fetch this data

There's a reason it's called a *starter* kit, and that's because there's no one size fits all when it comes to Power Platform governance - the kit just aims to provide a starting point for things you should consider as you manage and govern Power Platform, but some of the components in the kit will just serve as inspiration vs being an exact fit for your company. Here's our guidance for extending and customizing the kit, which should help you in modifying these processes to suit your needs: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

**Comment by manuelap-msft** [comment]
Thanks for the feedback! Just wanted to clarify a few things

1 The CoE Starter Kit is meant to be just that - a _starting_ point to help a customer establish automation and tooling for Power Platform administration and governance. It's not a "product" but meant to be seen as a set of templates and you can decide what you want to use as is, what you want to customize/extend, and what you don't need at all - there's no one size fits all when it comes to Power Platform governance and any approach hugely depends on the strategy, vision and delivery model for Power Platform in the customers organization. Many of our customers work with partners to extend/customize the kit to make it fit to their organisations needs.
1. The CoE Starter Kit is built 100% on top of the Power Platform, as such we
a. depend on data that the platform makes available to the kit programmatically 
b. are subject to any limitations that the platform has 
1. Model Driven app and Cloud flow usage is not available via the [Office 365 Audit Log](https://learn.microsoft.com/en-us/power-platform/admin/logging-powerapps) which we today use to retrieve launch/run information so that's why the CoE kit doesn't display it (related to 2a). However, this data is available via the [self-serve analytics (bring your own datalake)](https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics) feature that's available as public preview from the Power Platform Admin Center. You can sign up for this feature from the Power Platform Admin Center, and if this information is critical to your governance workflows start implementing your own solution on top of it. Yes, the CoE kit is also working on re-platforming to use the data from self-serve analytics as a foundation for inventory and telemetry but this is an ongoing development effort - we have found some issues during testing, and likely this version won't be available until the new year now. 
2. If you find issues with any of the CoE kit flows, we are committed to fixing them if you raise an issue here on GitHub. Same with any feature ideas - we prioritize our work based on customer feedback. However, we do not have an SLA for fixing bugs and implementing new features as we're a very small team and the CoE kit is an unsupported set of templates.

**Comment by JayCecchine** [comment]
> @JayCecchine I totally agree with you on the above there are definitely some major challenges implementing the Governance flows within the CoE solution. We have had huge issues with the governance part of the starter kit and have finally decided to deactivate it as we found so many issues with this part of the solution.
> 
> @manuelap-msft The last thing we hear was that there was a new release coming in December that would allow you to check for last launched?

yes, getting to that point as well that I may just disable it entirely.  Its causing more harm than good at this point.

**Comment by Jenefer-Monroe** [comment]
sorry to hear you've been struggling with the kit. ill close this bug out since there is no further action for starter kit team, but please let us know if you have other issues pop up
