### ISSUE TITLE
[ALM Accelerator - BUG]: AzureDevops page not available in admin app

### ISSUE THREAD

**Issue by GAVCY** [microsoft/coe-starter-kit#4218]
Hello,

When I launch the admin app, the sections are not named and I don't have access to the azure devops page in the app.
I have tried removing the solution, removing the creator kit, and reinstalling but I have the same issue.
Screenshots below : 
![image](https://user-images.githubusercontent.com/118366885/202393961-330a461f-49d2-4b56-b83d-5d715e05fa7b.png)
![image](https://user-images.githubusercontent.com/118366885/202394052-cff99fcd-ea33-4032-9856-17c0326695de.png)

### Expected Behavior

I expected to have access to the azure devops page

### What component are you experiencing the issue with?

ALM Accelerator Admin Model driven app

### What solution version are you using?

1.0.20221101.1

### Steps To Reproduce

Launch the ALM Accelerator for Power Platform Administration app

### Anything else?

N/A

**Comment by jenschristianschroder** [comment]
Hi @GAVCY,

Thanks for reporting this. 

What security role do you have in the environment in which the ALM Acc. solution is installed in?

**Comment by GAVCY** [comment]
Hello,

I have admin system security role and I think i tried some others but it didnt change the outcome

**Comment by mikefactorial** [comment]
I'm at a bit of a loss to explain this. Tried switching language from English to French to see if that was the issue but don't see the same behavior. What's strange is that in your screenshot I see generic New Group and New Area labels where in my environment in French langugage I see the english labels. I suppose this is possibly because the base language installed is English but it's odd that we are seeing two different screens.

@GAVCY if not installed can you try installing the English langugage pack in this environment to see if you get similar results?

![image](https://user-images.githubusercontent.com/42348035/204331992-773cc846-396d-4593-9d6f-c3c87d15312b.png)

**Comment by mikefactorial** [comment]
Closing this issue as there hasn't been any activity. Feel free to open a new issue if this persists.

**Comment by ahmedsassi2024** [comment]
it woks for me, i installed english on the environment then
* alm accelerator admin personalisation settings / languages : select english and it is done , thank you
![2023-12-13 18_14_59-Window](https://github.com/microsoft/coe-starter-kit/assets/64517936/370e40d8-28b7-4d5a-bdbe-8727811cb420)
