### ISSUE TITLE
[Core Components] Maker - Command Center

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#425]
The CoE Starter Kit and our guidance contains many different apps a maker or end user may be wanting access to - e.g. the template catalog, app catalog, learning resources, SharePoint/Wiki site, developer compliance center. 

We would like to create a "Power Home" as a one-stop-app that brings the CoE efforts together. This will be used to provide a starting point for makers and end users to explore their internal governance and community, and for makers and end users to more effectively communicate and interact with their CoEs.

**Comment by manuelap-msft** [comment]
v1 will be part of the September release, showing CoE app bookmarks, MS learn links and an RSS feed to Power Platform bog posts.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
