### ISSUE TITLE
[Core Components] Setup documentation

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#426]
Better “get started” documentation – what to do first, what are the pre-requisites, what do you have to set up, what do you run (& what does it do when you run it).

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by tchagan** [comment]
> 

the installing updates link goes nowhere, it's now missing from the updated documenation.

**Comment by manuelap-msft** [comment]
https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup
