### ISSUE TITLE
[CoE Starter Kit - BUG] Microsoft Teams Environment Creation and Deletion review Emails Reoccuring

### ISSUE THREAD

**Issue by tkudya** [microsoft/coe-starter-kit#4260]
### Describe the issue

The emails sent by Microsoft Teams Environment Creation and Deletion review, i keep getting a repeat of the same emails with the same Teams, Although they have been approved with the Admin View.  It's always the same 4 Teams and any recent ones that i have approved keep appearing each week. 

![tempsnip](https://user-images.githubusercontent.com/78653328/203552362-0c8f4f8f-a756-4a6a-951c-e0165b10fe68.png)

### Expected Behavior

I would except to not keep receiving this email once I have approved Teams Justification within

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.19

### What app or flow are you having the issue with?

Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments

**Comment by Jenefer-Monroe** [comment]
We made some changes to this flow since the August release that I believe resolve this with this filter 
`admin_environmentsku eq 'Teams' and admin_environmentdeleted eq false and  admin_environmentcreatedon gt @{body('Get_7_days_in_the_past')} and admin_makerrequirementbusinessjustification ne null`

![image](https://user-images.githubusercontent.com/89584709/203554208-3c2949b6-61d6-4e58-9c5f-5b620b1f09b5.png)


Can you try that out? And if so, update to November release (or December which will be out soon)

**Comment by tkudya** [comment]
I will update the Starter kit Thank you
