### ISSUE TITLE
[CoE Starter Kit - QUESTION] Which flow is this originating from

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4264]
### What is your question?

I have to create managed layers for the following emails users are receiving.  I need to change the text of the email that is being sent out.  I've found the following flow that sends out team cards, but not emails.

Flow - Request Orphaned Objects Reassigned (Parent)

Speaking of which, when I create a managed layer, and eventually have to update the CoE kit, is there a way to save that managed layer to re-apply it to theupated kit?

<img width="396" alt="image" src="https://user-images.githubusercontent.com/24686498/203659900-19574269-532f-4085-bc9b-18bc3614553d.png">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Oct 2022

### What app or flow are you having the issue with?

Flow - Request Orphaned Objects Reassigned (Parent)

**Comment by manuelap-msft** [comment]
Hello,

this email is sent in the **Request Orphaned Objects Reassigned (Child)** branch if the response to the Teams adaptive card has timed out - you'll have to look at the "If not timed out" branch to find it.
![image](https://user-images.githubusercontent.com/55705669/203816576-78861a8f-abcf-4b65-8df3-2e1763a46760.png)

PS: In January or February we'll likely have a version of the CoE kit ready through which these email texts can be customized without editing the flow and creating unmanaged layers so that will help then as well!

**Comment by JayCecchine** [comment]
Thanks for the response. I'm a bit new to creating managed layers, is it simple to just modify the template text for both the teams card and email?

**Comment by JayCecchine** [comment]
Any guidance on making this change would be appreciated, thanks.

**Comment by Jenefer-Monroe** [comment]
Editing the mail is easy, you can do it right there in line in the picture Manuela shared. But as she said it will create unmanaged layers that will need [removed on upgrade](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows)
Hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
