### ISSUE TITLE
[Governance Components] Orphaned Resources and Archive Requests

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#432]
Improvements to address orphaned resources. Better process for archive requests – what happens when end users ignore the request? Bulk action for makers? 

- [x] Ability for makers and managers to view orphaned resources and archive requests
- [x] As a maker I can open the highlighted app
- [ ] As a maker, I can delete the app or flow
- [x] As a maker, I can submit approval for the app or flow to be archived
- [x] As a maker, I can reject for the app or flow to be archived
- [x] As a maker, I can request for the app or flow to be exempt from the entire process and provide a business justificationo
- [ ] As a maker, I can bulk delete / approve / reject apps and flows 
- [x] As a manager, I can see which of my team have outstanding archive requests and nudge them
- [ ] As a manager, I can ask for admins to archive / delete apps or flows
- [ ] As a manager, I can bulk perform above actions

**Comment by manuelap-msft** [comment]
Some of these items have been addressed in the June release. Working on bulk update for July release.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
