### ISSUE TITLE
[CoE Starter Kit - BUG] November UPDATE

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#4332]
### Describe the issue

Hello,

Last week I updated to the latest version November package.

And today we cannot find any Model Driven app in the dataverse of COE env.

![image](https://user-images.githubusercontent.com/7468628/205230647-29f7144c-f293-4748-930d-6b3616978c97.png)

What should we check?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin - Sync Template v3

**Comment by ClaudiuVio** [comment]
No unmanaged layers on the solution CORE installed.

**Comment by ClaudiuVio** [comment]
After the run of Admin - Sync Template v3, the Model Driven app are back.

What could cause this?

No unmanaged layers on the CORE solution. And the flow ran 2 times before, and the Model Driven apps were not added to Dataverse.

**Comment by Jenefer-Monroe** [comment]
Hello, I'm really not sure what you were seeing. I looked back and it seemed like you had problems with Model Driven Apps in the past too that we were unable to narrow down. 
Sometimes people see inconsistencies like this if the identity they are using has their licenses or roles assigned via PIM, which we cannot support due to the long running nature of our flows. You might want to check on that.

Can you confirm, you are seeing your Model Driven Apps now?

**Comment by ClaudiuVio** [comment]
Model Driven apps appeared back after the sync flows rerun. I don't understand why they are deleted and then the Model Driven type apps are added back.

**Comment by Jenefer-Monroe** [comment]
I'm not sure either, seems like a long running problem you had. Please return and let us know if you experience more problems here in the future.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
