### ISSUE TITLE
[CoE Starter Kit - BUG] Action 'Get_Environment' failed - "admin_environment With Id = xxx Does Not Exist"

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#4334]
### Describe the issue

We have decided to install the CoE Starter Kit in a new environment after failing to upgrade the old CoE Starter Kit in another environment. However we have run into a problem when running **Admin | Sync Template v3** for the first time.

Store environments in the CoE CDS Identity  > Check if Legacy Environment > Get Environment

![image](https://user-images.githubusercontent.com/119695189/205356391-0432f39e-ffff-4003-ad6c-f37819945098.png)

### Expected Behavior

**Admin | Sync Template v3** completed without any errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

1. Run **Admin | Sync Template v3** for the first time.

**Comment by Jenefer-Monroe** [comment]
Hello, that is a caught failure. That action is seeing if the environment is already in inventory. If its not then this call fails, is caught by the next action, and sets the variable to show the environment is new to the CoE inventory
![image](https://user-images.githubusercontent.com/89584709/205371889-09454d0d-25b5-4420-b9ad-ad57c8b12622.png)

If your flow failed it will be due to something further down in the flows. 
Most of the time people fail on the call the "Get Maker" because they have not turned on the helper flows. 
Please make sure you have all the flows in the [inventory setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on. 

If they were all on then please go down further in the flow to find where it fails and halts.

**Comment by Jenefer-Monroe** [comment]
What is returned from the call to **_Get Maker_** above for the **_userisorphan_** value? 
![image](https://user-images.githubusercontent.com/89584709/205646834-508ad26e-753e-4edd-afbe-0d6d433ecf59.png)

**Comment by Jenefer-Monroe** [comment]
Please go to the Maker table and see of this maker is present. 
![image](https://user-images.githubusercontent.com/89584709/205732754-7b77218b-d821-4c44-9a16-b42a5a1e6905.png)

**Comment by Jenefer-Monroe** [comment]
The **_HELPER - Maker Check_** flow fills this table. In your case that call to Get Maker should have ensured that value was in the table. 

Can you please take the values from here, 
![image](https://user-images.githubusercontent.com/89584709/205966959-36f3ba9e-d3c6-435f-a017-a218c07e04cc.png)

And run the flow with those values? 
![image](https://user-images.githubusercontent.com/89584709/205967413-65c837f8-965c-4c69-9985-a4d8b8acbcab.png)

Then click on the time stamp of the run that was triggered to open it
![image](https://user-images.githubusercontent.com/89584709/205967582-58d99a4d-b70b-47d0-9948-4e24d756d938.png)

It should get down to this section of the flow during its run
![image](https://user-images.githubusercontent.com/89584709/205967741-fdc90e3d-9a88-4e9f-869a-d1cab4b9871f.png)

Then it should go down to Add Maker. 
![image](https://user-images.githubusercontent.com/89584709/205968015-9f2e8989-32d8-4fb9-ac27-742e91286d4d.png)

Please share screenshots of what you see.

**Comment by Jenefer-Monroe** [comment]
so above when you thought the table was empty, it wasnt?

**Comment by Jenefer-Monroe** [comment]
oh wonderful news. thank you!
