### ISSUE TITLE
[Core Components] Cloud Flow owners

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#434]
Explore if Custom Connectors / APIs can be used to change flow ownership (add additional owners).

**Comment by chrispiasecki** [comment]
Any update or progress on this?

**Comment by manuelap-msft** [comment]
Hello,

this is an unfunded item in our backlog, not currently assigned to a sprint. There will not be any update or progress until this item can be assigned to a sprint.

Thank you
Manuela

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
