### ISSUE TITLE
[CoE Starter Kit - BUG] | All environments are not showing for 2 different global admin / Power Platform Admin users

### ISSUE THREAD

**Issue by rob-amason** [microsoft/coe-starter-kit#4340]
### Describe the issue

I had two Global Admin accounts that are not seeing the same environments across https://make.powerapps.com/ & https://us.flow.microsoft.com/. When I share the direct URL between the two accounts, they can both access everything; however, when creating connections with one account they appear to run into a temporary error and then create the connections but are never visible to the other account views. The environment is visible from both accounts within admin.powerplatform.microsoft.com.

Account #1
![image](https://user-images.githubusercontent.com/119354363/205556954-1a16296a-8cd1-4df2-a321-19f5b0f5af66.png)

Account #2
![image](https://user-images.githubusercontent.com/119354363/205557006-4cba995a-73cb-4f30-bf2f-cfeea5a1e1fa.png)

Account #1
![image](https://user-images.githubusercontent.com/119354363/205557276-a40f32ac-aac7-4328-8e1f-e9f1b5f460e4.png)

Account #2
![image](https://user-images.githubusercontent.com/119354363/205557370-86297816-0357-4a5e-a288-fe31a0df1425.png)

Errors seen when creating connections under account #2
![image](https://user-images.githubusercontent.com/119354363/205557469-fdb3cb1b-1518-41a4-a65a-8124312201e6.png)

![image](https://user-images.githubusercontent.com/119354363/205559625-cf6ccfbb-d49b-4037-ae7b-6e66ce6d9d5b.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

CoE

### Steps To Reproduce

Steps recorder file is attached.
[ConnectorCreationError.zip](https://github.com/microsoft/coe-starter-kit/files/10151001/ConnectorCreationError.zip)

**Comment by manuelap-msft** [comment]
Hello,

from your description, it looks like your issue is not with a feature of the CoE Starter Kit but with the Power Platform product itself? If that's the case, please raise a support ticket with Microsoft https://learn.microsoft.com/en-us/power-platform/admin/get-help-support. If I misunderstood, please clarify where in the CoE kit you are seeing the issue.

Note that the CoE Starter Kit is a solution built on top of Power Platform, and in this GitHub page we are only able to offer support for questions or issues related to the CoE Starter Kit but can't help with issues related to Power Platform itself. For that, you'll have to go through official support channels with Microsoft support.

Manuela

**Comment by rob-amason** [comment]
> Hello,
> 
> from your description, it looks like your issue is not with a feature of the CoE Starter Kit but with the Power Platform product itself? If that's the case, please raise a support ticket with Microsoft https://learn.microsoft.com/en-us/power-platform/admin/get-help-support. If I misunderstood, please clarify where in the CoE kit you are seeing the issue.
> 
> Note that the CoE Starter Kit is a solution built on top of Power Platform, and in this GitHub page we are only able to offer support for questions or issues related to the CoE Starter Kit but can't help with issues related to Power Platform itself. For that, you'll have to go through official support channels with Microsoft support.
> 
> Manuela

Hi Manuela - 
This is occurring within a Power Platform CoE environment.

**Comment by manuelap-msft** [comment]
If you are having issues with the core features in Microsoft Power Platform: Use your standard channel to contact Microsoft Support. This includes if you have issues authenticating to environments, using connectors, importing solutions, setting up data policies etc.

If you are having issues using the features of the CoE kit itself, report your issue here. This includes if flows of the kit are not running, if an app in the kit has a bug etc.

**Comment by rob-amason** [comment]
> If you are having issues with the core features in Microsoft Power Platform: Use your standard channel to contact Microsoft Support. This includes if you have issues authenticating to environments, using connectors, importing solutions, setting up data policies etc.
> 
> If you are having issues using the features of the CoE kit itself, report your issue here. This includes if flows of the kit are not running, if an app in the kit has a bug etc.

I've opened a ticket with the Power Platform support team as well. Thank you for your responses.

**Comment by Jenefer-Monroe** [comment]
What did you hear back from support? We've had a few issues recently with access, wanting to understand if there is a generalized issue that we can understand for others.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
