### ISSUE TITLE
[CoE Starter Kit - BUG] Get New Flow as Admin failing

### ISSUE THREAD

**Issue by Rose-Lynch** [microsoft/coe-starter-kit#4341]
### Describe the issue

4 Daily Failures on Admin | Sync Template v3 (Flows) on 4 different environments (one on each), same every day with Error: Action 'Get_Flow_from_CoE' failed, Error Details: admin_flow With Id, Does Not Exist.  Same ID on all of them. Been happening since importing CoE (about a month).  

![Admin sync Template v3 (flows)error](https://user-images.githubusercontent.com/119854376/205620714-d85f5643-85e4-45e6-9a81-ca0d9cdda7ac.jpg)

### Expected Behavior

Not the same one failing each day with same ID and error, would expect error cleared after a day or so.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### Anything else?

Read this one and seemed like the same issue, they were advised to contact support https://github.com/microsoft/coe-starter-kit/issues/2531

**Comment by Jenefer-Monroe** [comment]
Hello you have hit a product bug here in which the list flows function is returning a flow that the get flow will not return. 

You will need to [contact support](https://learn.microsoft.com/en-us/power-platform/admin/get-help-support) to have them clean this up in order to have this flow start passing.  
 
Our recommendation is to first get a repro outside of the toolkit before contacting support. You can use the below flow to get a simple repro.  
 
To use: Import the flow, open, select the environment which repros for you.   
It loops the flows, will hit the same failure and then you can go to support with this flow instead of the toolkit, for faster iteration to fix.  
[ProductBugDemo-getflowaftergetflowsfails_20211116133300.zip](https://github.com/microsoft/coe-starter-kit/files/7546680/ProductBugDemo-getflowaftergetflowsfails_20211116133300.zip)
![image](https://user-images.githubusercontent.com/62659043/124291999-64162800-db12-11eb-92a6-55b4ffe1ecee.png)

**Comment by Rose-Lynch** [comment]
Have done this thank you.
