### ISSUE TITLE
[Core Components] Environment Request Management

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#438]
Automating environment management is top of mind, and we want to provide a template solution for how makers can request new environments, access to existing environments and changes to available connectors.

**Comment by manuelap-msft** [comment]
This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
