### ISSUE TITLE
[ALM Accelerator - Feature]: Icon for running test/prod pipeline in ALM app 

### ISSUE THREAD

**Issue by thetla** [microsoft/coe-starter-kit#4396]
### Describe the solution you'd like

Hi,

I have a big team that's using the ALM accelerator (70). All of them are missing an icon like on the "export solution to git" that is running and showing completed after the commit. They like that you can see a green icon after completing the pull request but would really like an icon to describe the prod/test runs like the icon/circle for export solution to git. This would help all the makers that don't want to spend so much time going in to Azure DevOps etc but just be in Power Platform Environments/ALM App. 

Br Terje Hetland 
PowerPlatform Center For Enablement Team

**Comment by mikefactorial** [comment]
@thetla can you share some details about your setup? Specifically, do you have the export pipeline running in the same project as the deployment pipelines (e.g. the project specified in the profile or is the export pipeline in a different project? I believe I've seen this behavior when the latter is the case. Will do some investigation into making this experience better for all scenarios.

**Comment by thetla** [comment]
Hi,

We have one "main template" project where we do all the updates. Other than that, we have different projects in Azure DevOps with repos/standard pipelines. We do have the export pipeline running in the same project as the deployment profiles.

Br Terje Hetland

**Comment by mikefactorial** [comment]
@thetla after rereading the feature request I understand a little better what the ask is. Assume this is to add a status indicator to the main screen. Originally, this was a feature in the Accelerator. However, since we've moved toward allowing more than 3 environments for deployment we moved this information from the main screen to the deployment request screen via the chevron next to the PR status icon.
![image](https://user-images.githubusercontent.com/42348035/211607400-fc99a11a-983a-4500-937d-85c2c1504411.png)
from here you can see the status of the deployments as well as the destination environment and other details
![image](https://user-images.githubusercontent.com/42348035/211610462-7995fe0c-d94f-4db7-be9f-86b47d0662c9.png)

**Comment by mikefactorial** [comment]
Closing this out for now. As we move toward reimagining parts of the ALM Accelerator UX to align with in-product ALM we will likely address this request, but don't have plans to invest in this in the legacy experience since this capability is already available via the solution deployment request details screen.
