### ISSUE TITLE
[CoE Starter Kit - Feature]: Last Launched date (app last launched on) is not returning any information

### ISSUE THREAD

**Issue by OlaAwo** [microsoft/coe-starter-kit#4399]
### Is your feature request related to a problem? Please describe.

Power Platform COE Power BI report  - App Risk Assessment : Last Launched date (app last launched on) is not returning any information

### Describe the solution you'd like

I expect to see date of when an App was last launched so that it can help me decide which App to delete if they are not in use

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. Here are a few things to note. 

Audit logs are collected by a solution separate from Core as the setup for them requires additional permissions. Please see [Set up the audit log connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)

Audit logs begin to collect data from when they are turned on, they do not go back and get historical data.
They are based on a custom connector, and these have issues with upgrade and need to be fixed periodically as described here: https://github.com/microsoft/coe-starter-kit/issues/1424

Please validate that you have installed and setup the [audit log solution](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog) 

Then, share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

A picture like this showing if the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png) 

And a picture like this showing if the data is populating
![image](https://user-images.githubusercontent.com/89584709/164469099-1cb27bec-a1b8-4a22-8b2c-c9bdb50d7d33.png)
