### ISSUE TITLE
Observations and questions while setting up CoE

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#4412]
### What is your question?

1. Can we have filter 'Shared with user' on flow risk assessment tab on Power BI dashboard?
2. Auto Delete On Archive environment variable - The Admin command center shows deprecated. But 'CleanUp and Delete' flow is using that variable. 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/112712553/207059582-f897cce1-1b52-4586-b2d1-cd687a4f6a75.png">

3.  Is it possible to keep the consistency across the dashboard with filter field Name ' Owner' , as some places it is read as 'Display name' 
4. From 'Developer Compliance Center App' can we include a tab for 'Environments' so that can get justification for Teams environment creation, as could see Power Platform Admin View App does have 'Environment blade' with business justification field. 
5. Is it possible to create a functionality to delete the Maker from the maker group automatically if any resources created by them in the tenant got deleted , this is in reference to flow ' Add maker to group'
6. Is it possible to add a functionality to not show the extra environment variables once CoE is setup, for example, there are two environment variables to setup the client secret- using Text secret and using Azure key vault. Once the user have decided to use either one , the other one should not get displayed for them anymore
7. Admin - command center App - There is NO reset flow button, in case the secret is changed but can see a delete button
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/112712553/207063985-25484bc7-2165-4943-a996-7d2b0f2cd488.png">
8.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November

**Comment by Jenefer-Monroe** [comment]
Here are some answers, hope it helps

### 1. Can we have filter 'Shared with user' on flow risk assessment tab on Power BI dashboard?
We do not currently store this information. We have a backlog item to do this work here: https://github.com/microsoft/coe-starter-kit/issues/1083

### 2. Auto Delete On Archive environment variable - The Admin command center shows deprecated. But 'CleanUp and Delete' flow is using that variable. 
It is deprecated in that we have replaced it and will eventually remove it. In the meantime we need to keep it in the kit so that we do not break installs.

### 3.  Is it possible to keep the consistency across the dashboard with filter field Name ' Owner' , as some places it is read as 'Display name' 
Please post as a separate issue and I can place on the backlog. 

### 4. From 'Developer Compliance Center App' can we include a tab for 'Environments' so that can get justification for Teams environment creation, as could see Power Platform Admin View App does have 'Environment blade' with business justification field. 
We have a backlog item tracking this work: https://github.com/microsoft/coe-starter-kit/issues/4290

### 6. Is it possible to create a functionality to delete the Maker from the maker group automatically if any resources created by them in the tenant got deleted , this is in reference to flow ' Add maker to group'
Please post as a separate issue and I can place on the backlog. 

### 7. Is it possible to add a functionality to not show the extra environment variables once CoE is setup, for example, there are two environment variables to setup the client secret- using Text secret and using Azure key vault. Once the user have decided to use either one , the other one should not get displayed for them anymore
That is product behavior, not something we can impact. We did, however, just release the preview of a setup wizard that should make that a better experience. Please try it out and let us know what you think. https://github.com/microsoft/coe-starter-kit/issues/3476

### 9. Admin - command center App - There is NO reset flow button, in case the secret is changed but can see a delete button
We only track a few env vars there for objects that impacted many flows as upkeep of this feature is expensive. The product team is now making these resets no longer required so we will be removing this all together soon as no longer needed. 
You can see what flows need reset in the meantime manually by looking at the object's dependencies.
![image](https://user-images.githubusercontent.com/89584709/207068115-d220e8bc-30cf-4fbf-8a99-727aa58df219.png)

**Comment by PPMini** [comment]
Many thanks for all the information and direction. Will raise separate ticket for required issues.

Have another question with respect to RSS connector in Center of Excellence, I understand it is fetching the latest news and blog post with respect to power platform to get  in Admin - command center App. My question here is: are these URLs whitelisted or what are the bases to select the URLs for this connector

**Comment by Jenefer-Monroe** [comment]
I'm afraid I don't follow your question. Can you provide a little more detail, what are you trying to accomplish here?

**Comment by PPMini** [comment]
Hi Jenefer, 
 Apologies, please ignore that question. Closing the thread as nothing to follow up on this. Many thanks for all the support

**Comment by Jenefer-Monroe** [comment]
you are welcome, thank you for using CoE
