### ISSUE TITLE
[ALM Accelerator - BUG]: Commit Solution - export-solution-to-git - Saving Export Pipeline Parameters

### ISSUE THREAD

**Issue by daniel-klesc-lego** [microsoft/coe-starter-kit#4448]
### Describe the issue

Hi there,
  in my solution I have added a power automate flow with following name: **PackingBI-DataPlatform-App-Workers-Sharepoint-File-Configuration-Get**. Afterwards I have tried to commit a solution and I got an error in step Saving Export Pipeline Parameters. See the attached image.
![image](https://user-images.githubusercontent.com/109669159/207829481-3c65c620-14e7-49e0-9094-920c7a520103.png)

If I remove the last part of the flow name (-Get). So the name is: PackingBI-DataPlatform-App-Workers-Sharepoint-File-Configuration the error disappears.

### Expected Behavior

I expect that the name of the flow won't have any impact on the functionality of the app.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

The one from November 2022

### Steps To Reproduce

- Put into any solution a power automate flow with a name **PackingBI-DataPlatform-App-Workers-Sharepoint-File-Configuration-Get**
- Press the commit solution button on that solution

**Comment by mikefactorial** [comment]
@daniel-klesc-lego thanks for reporting this will look into what's going on here.

**Comment by mikefactorial** [comment]
@RajeevPentyala this is generally caused by missing quotes around a variable or parameter name or possibly has to do with string encoding.

**Comment by RajeevPentyala** [comment]
@daniel-klesc-lego I could not reproduce the issue. I could commit a solution with a flow by name "_PackingBI-DataPlatform-App-Workers-Sharepoint-File-Configuration-Get_".
![image](https://user-images.githubusercontent.com/104883923/208869681-6d1e5237-138c-4791-99f7-b59573996da1.png)

I suspect the issue could be due to the Unicode characters in pipeline parameters. To troubleshoot the issue better, can you share the Logs.
- Open the failed pipeline run.
- From menu, click on 'Download Logs' and share the .zip folder.
![image](https://user-images.githubusercontent.com/104883923/208870497-824e89bc-50c1-46b3-9bbe-e4a35f2674f0.png)

Please let me know if any queries. FYI @mikefactorial

**Comment by daniel-klesc-lego** [comment]
@RajeevPentyala I have attached the log ;-)
[logs_795.zip](https://github.com/microsoft/coe-starter-kit/files/10277194/logs_795.zip)

**Comment by RajeevPentyala** [comment]
@daniel-klesc-lego Thanks for the quick response. Issue has been identified and its due to the usage of double quotes (i.e., "dot") in your commit message.  _"Correction of name of flow. By mistake a _**"dot"**_ was used in a name."_

Issue has been fixed and will be available in upcoming release.

Meanwhile please refrain the usage of double quotes in commit message. FYI @mikefactorial
