### ISSUE TITLE
[ALM Accelerator - QUESTION] Get Connection References Flow - On DeploymentSettingsScreen

### ISSUE THREAD

**Issue by suryakiran255** [microsoft/coe-starter-kit#4454]
### What is your question?

We have been observing a few performance issues on the deployment settings screen which fetches connection references. Upon checking the get connection references flows, we have noted that we are fetching all the connection references from the source environment. We were wondering if we can filter out connection references based on the solution id field available in the connection reference table. Also, what is the need to query the solution component table if we are able to fetch the solution-specific connection references from the connection references table? Below is the screenshot for the existing action

![image](https://user-images.githubusercontent.com/20218503/207955324-d8a7f942-2c92-4aea-96c8-1bd8fff58585.png)

Looking at the connection references table screenshot, we could leverage the solution column from the connection references table.
![image](https://user-images.githubusercontent.com/20218503/207955595-8f462ee2-5632-4dff-853c-0c36f88b6628.png)

Later in the flow, we also query the solution components table, is that really required?
![image](https://user-images.githubusercontent.com/20218503/207955880-aacb7444-36bd-47f3-abb0-62e8e4fb0d74.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

November

**Comment by mikefactorial** [comment]
Hey @suryakiran255 thanks for the question. Unfortunately, the solutionid field on the connectionreference table doesn't actually map to the solutionid on the solution table as you would expect it to which is why we had to jump through all the hoops we are in that particular flow. It's also in part due to the limitations in the Legacy Datavese connector. That being said we did reorganize this flow to be slightly more performant in the December release and instead are querying solution components before connection references. You may want to take a look at the December release to see if that update fixes the potential performance problems you're seeing.

**Comment by mikefactorial** [comment]
Closing out this issue as there's no more work on our part until we can refactor using the capabilities in the new Dataverse connector.
