### ISSUE TITLE
[Nurture Components] Training in a day - add calendar item to email

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#447]
Add calendar item to registration email.
Allow events to be marked as virtual, and create Teams invite.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
