### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard - Failed to turn on Admin | Sync Template flows

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#4473]
### Describe the issue

I have started the set up for the COE starter kit Wizard set up process.
 
It seems to be good until it reaches the Run Setup flows. Here my initial configuration of the Wizard got stuck and am unable to go further.
![image](https://user-images.githubusercontent.com/111575586/208649252-c1338d02-d35a-4d33-878a-09ac6407124b.png)

![image](https://user-images.githubusercontent.com/111575586/208649280-8796316c-6b85-4d42-8df6-badc5f4a653a.png)

Kindly help

 

### Expected Behavior

The setup should get in smoothly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Set Up Wizard app

### Steps To Reproduce

I have started the set up for the COE starter kit Wizard set up process.
 
It seems to be good until it reaches the Run Setup flows. Here my initial configuration of the Wizard got stuck and am unable to go further.
![image](https://user-images.githubusercontent.com/111575586/208649252-c1338d02-d35a-4d33-878a-09ac6407124b.png)

![image](https://user-images.githubusercontent.com/111575586/208649280-8796316c-6b85-4d42-8df6-badc5f4a653a.png)

Tried to check with the other flows working are on or not all seems to be good.

**Comment by Jenefer-Monroe** [comment]
Did you try to turn on manually?

**Comment by Neel1KNK** [comment]
Manually like,

I went to solution and play the setup wizard and start the process and when I come to this step, it fails.

Previously I was getting the error saying to turn on the sync flows and later I was able to turn on the sync flow, and later am getting this error.

**Comment by Jenefer-Monroe** [comment]
Given this is the second one you've hit, you should probably try to turn on the flows manually so that they are debuggable. 
Note that we are making this error more granular next release. 

Go to your CoE Environment > Core Components > Flows 
![image](https://user-images.githubusercontent.com/89584709/208796961-5c5e168e-2c3e-4c76-9985-52776730927c.png)

And then either make sure all these are on, or turn them on, in the order shown

1. All [child flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows) are turned on
1. All [setup flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-setup-flows) are turned on
1. All [inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows) are turned on

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
