### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Model Driven Apps) doesn't return all apps

### ISSUE THREAD

**Issue by marekbuban** [microsoft/coe-starter-kit#4509]
### Describe the issue

The flow doesn't return all model driven apps we have in environments. As model driven apps are visible to everyone, I can see many model driven apps in maker portal that are not present in CoE.
I've also checked the flow history run for default environment. In the default env I see like 100 of model-driven apps, but in the flow run history for the same environment, action List Model Driven Apps only returns like 80 of them.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Model Driven Apps)

**Comment by Jenefer-Monroe** [comment]
There are some limitations on what we can inventory based on what is programmatically provided by the product itself. For example, [unpublished model-driven apps](https://learn.microsoft.com/power-platform/guidance/coe/limitations#unpublished-model-driven-apps) cannot be inventoried. 

In order to debug here you will need to find a case with which to debug. Find a published model driven app that is not appearing in your inventory and then do the following so that we can have a repro in hand

### How to find a repro 
You will need to find a repro of this in your tenant to see what is going wrong. 
1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from starter kit team.
