### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard error loading control

### ISSUE THREAD

**Issue by Pavan12Verma** [microsoft/coe-starter-kit#4513]
### Describe the issue

Setup Wizard pre-requisite step is showing "Error loading control"
![CoE setup wizard error](https://user-images.githubusercontent.com/101834540/210391647-0b4b2b68-edab-4be8-b11d-6aa2003a34c2.png)

### Expected Behavior

Show control instead of error message

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Setup Wizard

### Steps To Reproduce

In Core Components solution open Setup Wizard app

**Comment by Jenefer-Monroe** [comment]
Thank you for posting, not sure if this is known or not but putting on the list for investigation for next release.

**Comment by manuelap-msft** [comment]
This usually happens when some flows failed to activate in the background. Can you open the solution and try to turn on the SetupWizard>GetUserDetails, GetCurrentEnvironment, GetTenantDetails flows manually and restart the setup wizard? If any of the flows fail to turn on, the SetupWizard won't work so make sure they're on before proceeding.

**Comment by Pavan12Verma** [comment]
ok, can't find GetTenantDetails in core solution but I see GetTenantID flow should I turn that on?

**Comment by manuelap-msft** [comment]
Yep, I had a copy and paste issue in the above comment - it's these three flows:
![image](https://user-images.githubusercontent.com/55705669/210398847-2ca5954d-57c5-4883-8700-012a9d7b20d7.png)
