### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#4535]
### Describe the issue

Power Platform User Microsoft 365 Group (and possibly the Maker Group) search/select doesn't display all known M365 Groups.

### Expected Behavior

All groups are available to select.

Also, it would be good to be able to simply add the Object ID, as a fail safe.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Setup Wizard

**Comment by manuelap-msft** [comment]
This is a known and tracked issue #4494 targeted to be fixed in February. Please update these environment variables manually and then return to the wizard to complete the setup:
![image](https://user-images.githubusercontent.com/55705669/211021554-a74e782e-d9d6-4f0b-afe4-846f3120f3d9.png)

![image](https://user-images.githubusercontent.com/55705669/211021570-b7d29179-5752-42ee-9079-67d844b05644.png)

Environment variable documentation:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-manually
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables

Closing as duplicate.
