### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Desktop flows) - max buffer size

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#4557]
### Describe the issue

For some environments that contains bigger amount of workflows the flow doesn't work. The error for List Desktop Flows action says "Http request failed as there is an error: 'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'." 

![image](https://user-images.githubusercontent.com/54030753/211518595-460a2e31-0cc2-495f-a1ae-06054158576b.png)

Was this bug resolved in the December release or will it be resolved in the January release? If the bug is not resolved, is there any ready work around?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

**Comment by Jenefer-Monroe** [comment]
The desktop flow work in the CoE Starter Kit currently has several limitations that make it insufficient for organizations heavily focused on that tech. This is due to the way that we gather the data and is not something we can fix without a product change (which is supposed to be coming live in a few quarters)

That said, there is a dedicated set of folks who work on "Automation CoE". My recommendation is that you focus in that direction instead. Here are some starter links to get you going:
- [Automation Center of Excellence Webinar](https://info.microsoft.com/ww-thankyou-businesscenterexcellencerpa.html?LCID=EN-US&ocid=eml_pg332504_gdc_comm_ba)
- [Microsoft Power Platform Automation CoE starter kit (preview)](https://docs.microsoft.com/power-platform/guidance/automation-coe/automation-coe-starter-kit)
- [RPA CLI](https://github.com/rpapostolis/rpa-cli)

Sorry for the inconvenience

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team

**Comment by ghaughey** [comment]
Has anyone found a workaround for this?
