### ISSUE TITLE
Sync flows failing for "List flow as Admin" - byte limit

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#4572]
The sync flows are failing for "List flows as Admin" as well as "List connections as Admin"
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/106515181/212007441-d8b182bf-49f4-45b4-be88-55b729f3f6ad.png)
<img width="858" alt="MicrosoftTeams-image (5)" src="https://user-images.githubusercontent.com/106515181/212007452-c5d2395a-fd25-4ba2-b1f8-feea2c52d047.png">

**Comment by Jenefer-Monroe** [comment]
The CoE kit is built on top of the product, and as such bound to platform limitations. 
This failure is due to a limitation on the amount of data connectors can bring back, which unfortunately, you have exceeded. 

We are working on a new CoE kit architecture with the product which will not require we use this action any longer, it should be available later this year.  You may benefit from exploring it now: 

https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

In the meantime, in order to proceed with using the kit, you would need to reduce the number of flows and connections in the environment by delete old unused ones or moving logical groups of them to their own environments. 

Alternatively, if you would like to maintain the flow inventory yourself, you could do this using other tools which do not suffer this connector limit like PowerShell. 
Unfortunately we are not staffed to assist with this, but here are some ideas to get you started:

Instead of deleting your Flows you could also consider using logic apps or a PowerShell command to export all Flows.
Get-AdminFlow | Export-Csv -Path '.\FlowExport.csv'
From there, you have the option to push the data into the CoE kits Dataverse table using PowerShell / LogicApps as well.

**Comment by Jenefer-Monroe** [comment]
closing out as unfortunately there is nothing else the starter kit can do here to assist.
