### ISSUE TITLE
[ALM Accelerator - Question] Preview status

### ISSUE THREAD

**Issue by powerplatformjustin** [microsoft/coe-starter-kit#4582]
Just wondering if there is any clarity on when this will be out of preview being in preview now for way past a year.

Sadly I want to use this on a project but can't due to it saying "preview" on MS docs any timelines on this? 

Is there an ability to get Support / raise a support request for this officially?

**Comment by manuelap-msft** [comment]
What do you mean by "this"?

**Comment by powerplatformjustin** [comment]
just wondering what the timeline is on the ALM accelerator being moved out of preview on the MS docs

**Comment by mikefactorial** [comment]
@powerplatformjustin appreciate the question. This is something we are discussing internally. 

The primary reason for the ALM Accelerator being in preview is that we are relying on the canvas unpack and pack functionality which is also in public preview (https://github.com/microsoft/PowerApps-Language-Tooling/blob/master/README.md). 

Other tools that leverage the Power Apps Source File Pack and Unpack Utility including the Power Platform CLI also include the preview moniker in the functions that utilize this preview feature since it's not recommended for production use at this time (https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/canvas). 

Power Apps Source File Pack and Unpack Utility is being developed by another team within Microsoft. So, we don't dictate timelines for GA. Will follow up with their team and the rest of our team to provide more specifics.
