### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Audit Logs Refinement

### ISSUE THREAD

**Issue by DK-SPPP** [microsoft/coe-starter-kit#4593]
### CoE Audit Logs - Missing some logs - require smaller chunks.
Current Chunking Size: 15 minutes and we are still receiving emails sayings smaller chunks are required.

**Are there any solution existed to retrieve all logs without any miss?
Is there any road map to improve this challenge from your end?**

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child Admin] | Sync Logs

**Comment by Jenefer-Monroe** [comment]
This mail is intended to let you know that you need to continue making these chunks smaller to hopefully be able to cover your tenant usage. You can try down to 1 minute (see below for help with that), then if you still get the error you may just be too large to work with the existing custom connector solution. 

Because of the way the backend we are using works, we see other office operations (ex boot excel) so the number of records here balloons quickly. You could try 1 minute chunks

- TimeSegments-CountLimit: 1500
- TimeInterval-Unit: Minute
- TimeInterval-Interval: 1

But if that does not work then I'm afraid there is nothing we can do about this until we re-plat to the BYODL (Self Service analytics) where the logs will be more natively gathered rather than via this custom connector

You can explore this ahead of time if you would like
- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

We are currently working on integrating this with the CoE hoping to release sometime in the next few quarters.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
