### ISSUE TITLE
[CoE Starter Kit - QUESTION] FinOps Capacity not longer available

### ISSUE THREAD

**Issue by cr0max** [microsoft/coe-starter-kit#4660]
### What is your question?

Hi,
Has there been a change in the flows for environment capacity inventory for FinOps database/file?
Before our upgrade (pre december 2022), FinOps database and file was visible in the Environment Capacity.

After the upgrade those entries are now gone. Has there been a change. Because we have some FinOps databases that no longer are visible in CoE.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Environment Properties)

**Comment by manuelap-msft** [comment]
We had some questions and asks on removing this capacity (e.g. #2918) as it's not related to Power Platform, but instead to Dynamics F&O and we have therefore removed it.

**Comment by cr0max** [comment]
Thank you for the explanation, my search for previous tickets might have been for open only...
We did run the august/september 2022 update previous to december, so thats why it got removed.

However, our FinOps db/file inventory for CoE did work fine and since MS has had this on preview for a long time. I assume that this will be GA sometime in the future and this was great for our reports and also for the capacity alerts.

 From PPAC:
 
![image](https://user-images.githubusercontent.com/97740538/214569590-52e22577-1e92-47ef-9758-476793e6d8b7.png)

https://learn.microsoft.com/en-us/power-platform/admin/finance-operations-storage-capacity?WT.mc_id=ppac_inproduct_resources

**Comment by manuelap-msft** [comment]
For the CoE Kit, many of our users were confused with FinOps capacity showing as that's a Dynamics concept and they're mainly Power Platform Admins. So we'll continue to filter this out in order to avoid confusion.

If you do want to manage and see FinOps capacity in the CoE kit, you can modify the Environment Properties sync flow to remove this filter:
![image](https://user-images.githubusercontent.com/55705669/215534927-08038177-bb56-4d5b-9e55-a418b4baf5de.png)

Note that modifying this flow will introduce an unmanaged layer and mean you won't get any updates to this flow during future upgrades.
