### ISSUE TITLE
[CoE Starter Kit - BUG] Last Launched information is outdated.

### ISSUE THREAD

**Issue by Funterrain** [microsoft/coe-starter-kit#4676]
### Describe the issue

we have installed the latest CoE incl. Dashboard.
But unfortunately (as in the older versions) the information (Last Launched) is completely outdated.
We are sure that the flowers are running correctly.
Could someone please help us with this issue?

### Expected Behavior

Show c up to date information

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

AuditLogs Flow

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. Here are a few things to note. 

Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

Then a picture like this showing if the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png)

**Comment by Funterrain** [comment]
Hello, thanks for helping!
Here is the screen. We have no data here...
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/91595579/215420377-968d0fa0-10a3-4a85-81a3-b3571b001aaa.png">

The other screen shows that the child flows are failing.
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/91595579/215421529-cfb97d6c-4f98-4155-a1dd-2b5c0555482c.png">

Can you please help troubleshooting this?

Kind regards
Frank

**Comment by Funterrain** [comment]
Hi, I was able to fix the custom connection and the Admin Flows:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/91595579/215462417-3694a3b7-9f6f-4f0a-a8a2-d4b088ad8ed1.png">


But the Dashboard still is not showing correct "last launched" date in Power BI dashboard is not correct.

**Comment by Jenefer-Monroe** [comment]
Well done fixing that up. Connections to custom connectors often get broken on solution upgrade that may be what happened here. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve that in the future.

Audit logs begin to collect data from when they are turned on, they do not go back and get historical data as the api we use does not support that. So once you have some data in play these will begin to show up. 

Note also that you will need to be sure you have [Configured Scheduled Refresh](https://learn.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh) for your PBI so that it picks up the latest data for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
