### ISSUE TITLE
[CoE Starter Kit - BUG] Connection Identities aggregated page results size exceeds maximum

### ISSUE THREAD

**Issue by alisoncyeh** [microsoft/coe-starter-kit#4726]
### Describe the issue

The Admin | Sync Template v3 (Connection Identities) fails with: "The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '210250653' bytes. This exceeded the maximum size '209715200' bytes allowed."

Previous [response/guidance](https://github.com/microsoft/coe-starter-kit/issues/3761) from the CoE team was:

"This failure is in an out of the box connector’s action, which we're just using. Unfortunately, it has a size limitation that you have exceeded.

We cannot fix this, but you can manually clean up some of the old connections via Power Shell and then be under the size limit. We have documented this limitation here along with a starter solution to address via PowerShell: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#set-up-connection-cleanup-broken-connections"

However, there was a **major issue** where the cmdlets deleted live connections & it broke over 30 flows for my customer that took two months to resolve. This error has continued to persist & the customer needs a solution other than running broken cmdlets. What is the recommendation now?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

**Comment by Jenefer-Monroe** [comment]
Hello. What happened in this case was that the behavior of the product changed after we released the cmdlet. 

When we shipped the cmdlet, logicflow connections always returned type error (which is incorrect) but explicitly blocked delete, with its own error message even, to protect customers from the situation you faced. 
So when the cmdlet deleted all errored connections it did not delete these as the product protected them. 

Some time after we shipped the cmdlet the product changed that behavior and started to allow delete of these connection types without fixing the fact that they always show as type errored. 

A chunk of tenants were hit by the behavior you described as a result of this change. The product reverted the change, and these cannot be deleted again. But we have not re-introduced any scripts as they are, as you state, just too risky. 

In order to proceed I'm afraid you will need to go about creating your own scripts to delete these with your own testing, or contact product support.

**Comment by alisoncyeh** [comment]
Thanks for the thorough explanation. Are there no plans to address this behaviour? Unfortunately, this is a **huge** blocker for my customer -- installing the CoE is already a very manual process & now customers need to write their own scripts in order for the full solution to work? The [BYODL solution](https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics) won't work either as it's yet another item to set up that comes with additional costs.

Admin | Sync Template v3 (Business Process Flows) & Admin | Sync Template v3 (Apps) also fail because this flow fails to run successfully & provide actual data to subsequent flows. My customer has lost trust in the CoE due to this whole experience.

**Comment by Jenefer-Monroe** [comment]
There is nothing we as a starter kit can do here, however as a partner being paid to do this for customers (which is sounds like is your position?), this is a great place for you to shine and advertise as someone that can learn how to clean these up manually.

In your situation you can run a query cmd, test it to be sure its sound (that you aren't deleting real connections) then delete. Whereas for us, we would be delivering a script that would need to work safely over time regardless of current product behavior, product changes, or tenant state. Per the above, this is not something we can feel safe in doing. 

If that isn't something you can offer, then you can just have your customers skip gathering connection identities.

**Comment by alisoncyeh** [comment]
It doesn't make sense that a starter kit doesn't fully work OOTB with zero customisations. I am a full-time Microsoft resource for this customer, not a partner. It's hard to sell them on a tool they have to install themselves & can't even open a traditional support ticket on.

What you outlined is exactly what we tried the first time & the only reason they ran the cmdlets in production was because the tests seemingly went fine. This customer does not want to run any more scripts considering they can't even trust the cmdlets to run properly.

Is the rest of the CoE intended to work without gathering connection identities? Connections are a key aspect of Power Platform & the customer needs that data in order to adequately mange their organisation.

**Comment by manuelap-msft** [comment]
1. The CoE kit is built on top of the product, and as such bound to platform limitations. This failure is due to a limitation on the amount of data a connectors can bring back, which unfortunately, you have exceeded. The CoE Kit can't change the behaviour of Power Automate
2. The CoE kit is a reference implementation (hence the name starter kit), not an end to end / out of the box solution. There's no one size fits all when it comes to Power Platform administration and governance, and the kit only aims to inspire and provide a sample implementation of how to handle certain scenarios. To get the most out of the kit, many customers extend and customize it to fit their needs so the opposite of what you said is true. We do fully expect customers to make customizations to the kit. 
3. Equally, the CoE kit is not a fit for every customer - the scenario your customer encountered was very unfortunate and happened due to a product behaviour change that we weren't aware of. Hopefully you can restore their faith in the CoE kit but if not, you may want to consider doing an analysis with them on what features of the kit they need for their governance approach and see how they can be fulfilled with out of the box capabilities and where they'd need to write their own implementation instead.

**Comment by alisoncyeh** [comment]
Thanks for the thorough explanations! To help me understand what customisations they'll need, is the rest of the CoE intended to work without gathering connection identities? What other data will they lose out on by removing this flow?

**Comment by alisoncyeh** [comment]
Checking in on the above. Any insights?

**Comment by alisoncyeh** [comment]
Is the customer safe to run the same cleanup script as before with no issues now?

**Comment by Jenefer-Monroe** [comment]
We cannot advice on how to do this cleanup. The only safe path as far as I can tell, will be for someone to clean up connection areas case by case. 

So query for broken sharepoint connectors, make sure they all look like ones that can be deleted, delete them. 
Query for broken dataverse connectors,  make sure they all look like ones that can be deleted, delete them. 
etc...

You should give feedback to the product team that this is not an easy task, we are bound by their capabilities.

**Comment by alisoncyeh** [comment]
Understood, my customer has opened a ticket on this issue. In the mean time, is the rest of the CoE intended to work without gathering connection identities? What other data will they lose out on by removing this flow?

**Comment by Jenefer-Monroe** [comment]
They will not be able to identify cross tenant connections (ex someones gmail account)

**Comment by alisoncyeh** [comment]
Got it, thanks! Could you confirm if this flow would have any affect on Admin | Sync Template v3 (Business Process Flows) & Admin | Sync Template v3 (Apps)? Both of those flows are also failing with null values, the assumption being the Connection Identities flow is failing to fully populate the tables on which these two flows are running

**Comment by alisoncyeh** [comment]
Thank you for confirming! In that case, I'll open new separate issues for those two flows
