### ISSUE TITLE
[CoE Starter Kit - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by fbellavf** [microsoft/coe-starter-kit#4728]
### Is your feature request related to a problem? Please describe.

When I load the Power Platform Admin View app from CoE our default environment (USA Region - I am in Canada), it shows only one app which is incorrect, there are over a hundred. I wanted to run the App and Flow Inactivity Notification Clean Up View to do some house cleaning.

![image](https://user-images.githubusercontent.com/104634753/216470134-686051a5-fb34-4b8d-bf62-d67f18de65a4.png)

### Describe the solution you'd like

Is there something disabled/enabled that is not showing the app?

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for trying out the kit! 

When we see this happen, its typically because the identity running the kit does not have the Power Platform Admin Role permanently assigned. 

Please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

![image](https://user-images.githubusercontent.com/89584709/216485089-8f933a34-b8c2-41fb-a849-79449a932054.png)

**Comment by fbellavf** [comment]
Thank you Jenefer-Monroe for you quick response. I will check with my team to see if the identity that we are using has the right permission.

Fernand

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
