### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform CoE Dashboard - Apps - Missing App in App Drill Through

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#4732]
### Describe the issue

Power Platform CoE Dashboard - Apps - Missing App in App Drill Through

### Expected Behavior

The application is available in Power Platform CoE Dashboard - Apps - App Drill Through

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard_December2022.pbit

### Steps To Reproduce

1. Open **PowerPlatformGovernance_CoEDashboard_December2022.pbit**.
2. Go to **Apps** tab.
3.  Right click an App.
4. Select **Drill through**.
5.  Select **App Detail**.
6. In New Window, Application under **Manage App** is missing.

### Anything else?

Screenshots:
![Power BI CoE Version](https://user-images.githubusercontent.com/119695189/216597466-09d5bdb9-9fa2-4323-9cbd-591cb4f7da2f.png)

![Power BI CoE Steps](https://user-images.githubusercontent.com/119695189/216597475-465c0242-0b29-4fb1-af12-9e1bd949b110.png)

![Power BI CoE Steps 2](https://user-images.githubusercontent.com/119695189/216597471-a2febe03-e38d-4fcf-97c2-0cf483785646.png)

**Comment by Jenefer-Monroe** [comment]
Hello. You need to do these steps from the [Set up the Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi) documentation in order to use these apps: 

[(Optional) Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard)

**Comment by Jenefer-Monroe** [comment]
wonderful, thanks for letting us know!
