### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs Chunk Size Issue

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#4737]
### Describe the issue

We are receiving a chink size error with the CoE. We have changed the time interval unit to minutes and time interval interval to 1 minute. We have also modified the range of the timesegment-countlimit from 60 all the way to 2400. We are still having chunk size issues. Do you have recommendations?
![image](https://user-images.githubusercontent.com/95443860/216704188-1520a562-8968-4c07-9984-961b1c74ed94.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Audit Sync Logs

**Comment by Jenefer-Monroe** [comment]
I'm afraid your tenant is just to large for this system of collecting audit logs then. The back end does not allow us to filter there so we have to pull in all logs and filter in the flow client. 

I'm afraid there is nothing we can do about this until we re-plat to the BYODL (Self Service analytics) where the logs will be more natively gathered rather than via this custom connector

We are currently working on integrating this with the CoE hoping to release sometime in the next few quarters.
You can explore this ahead of time if you would like
- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

Sorry we cannot unblock you sooner.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
