### ISSUE TITLE
[CoE Starter Kit - QUESTION] Connection Reference Identity table growth

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#4749]
### What is your question?

Hi, is it normal that the Connection Reference Identity table is growing at the rate shown in the image below?

![image](https://user-images.githubusercontent.com/41050216/217145548-df021ad1-39a4-41cf-b7bb-23b077aad9e4.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

**Comment by Jenefer-Monroe** [comment]
It is normal for it to grow, yes. It stores every connection identity in the tenant and since today these are not purged by any processes in the product, and only if people manually delete them, then I would expect it to continuously grow. 

The feature is used only for detecting cross-tenant identities so if this size is too large for you, you can cut stop them and delete the contents of the table.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
