### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade failing V3.31 to V4.2

### ISSUE THREAD

**Issue by LanMorton** [microsoft/coe-starter-kit#4753]
### Describe the issue

We’ve followed the requirements in the page installing updates to ensure our CoE is clean, no unmanaged layers, no customised features. Most flows and apps still run well, except it’s running with the old Coe template.
Specifically, the Admin | Sync Template v3 run well, succeeded most times. However, importing the Core Components 4.2 failled anyway.
We couldn’t find any unmanaged flows or solution layers within our CoE, but still hit the same error as I sent you in my last email.
We are unable to install the Core Components Solution (7/12/2022). It failed every time we tried to update it for our CoE. Although we have tried various ways for many hours (investigated and learned other’s experiences through the Developer Community); it failed to import this solution anyway; the same error (see below) occurred every time we try to update it:
 
[CANNOT IMPORT OR UPDATE COE-2023.02.07.pdf](https://github.com/microsoft/coe-starter-kit/files/10677153/CANNOT.IMPORT.OR.UPDATE.COE-2023.02.07.pdf)

I believe the issue is related to two different versions of the core components are existing in our CoE (V3.39 and V3.31). We are expecting your advice and suggest us a relevant way for resolving our request/issue. Hope you can support us soon please.

We need to update or upgrade to the latest version of coe;
Presently, our coe runs well ; however we want to apply the latest coe template V4.2
Our existing versions are V3.31 and V3.39 for the Core Components
All other components have been updated, no error/issue (Nurture, Governance, backlogs components, etc.) are up to date.
Kind regards,
Lan 

### Expected Behavior

We need to update or upgrade to the latest version of coe;
Presently, our coe runs well ; however we want to apply the latest coe template V4.2
Our existing versions are V3.31 and V3.39 for the Core Components
All other components have been updated, no error/issue (Nurture, Governance, backlogs components, etc.) are up to date.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31 and 3.39 Core Components

### What app or flow are you having the issue with?

Command Center App > Get M365 Service Messages

### Steps To Reproduce

1. CoE upgrade for Core components, cannot import the latest solution
[CANNOT IMPORT OR UPDATE COE-2023.02.07.pdf](https://github.com/microsoft/coe-starter-kit/files/10677209/CANNOT.IMPORT.OR.UPDATE.COE-2023.02.07.pdf)

### Anything else?

no
[CANNOT IMPORT OR UPDATE COE-2023.02.07.pdf](https://github.com/microsoft/coe-starter-kit/files/10677215/CANNOT.IMPORT.OR.UPDATE.COE-2023.02.07.pdf)

**Comment by Jenefer-Monroe** [comment]
Hello, please note the CoE Starter Kit is an unsupported set of templates: https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support. 
We do not have a support team that can help resolve issues, and support is provided on best endevaours without SLA via GitHub. 

Debugging upgrade really requires knowledge about the old build and the new, which is why we require people to [upgrade at least every 3 months]((https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)) for us to assist. We simply do not have the knowledge to assist with upgrades of this age, nor the complexity of the issue you are facing. 

If all you are using us for is inventory, with or without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get started with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Others have overcome it with a classic overwrite upgrade, ill paste how to do those below. 

Sorry we cannot be of more assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
