### ISSUE TITLE
[CoE Starter Kit - BUG] Power Apps CoE Toolkit Admin flows are not getting triggered. 

### ISSUE THREAD

**Issue by Girijabaral** [microsoft/coe-starter-kit#4756]
### Describe the issue

Power Apps CoE Toolkit Admin flows are not getting triggered. "Admin | Sync Template v3" Flow is running fine, which should trigger other admin flow. But other admin flows are not getting triggered.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin - Sync Template v3

### Anything else?

Preferred way to communicate: Email to saurabh.chauhan@cummins.com and CC to solaikumaresan.sathasivam@cummins.com

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid we are not staffed to assist with issues outside of the context of GitHub so we will need to interact here. 
Note that in your responses, if you log in to GitHub to respond, then you can share images and things like that. So you should try to do that rather than respond in email. 

Please go to the Products admin page: https://admin.powerplatform.microsoft.com/ > Environments > Find your CoE environment > Click History from the ribbon
![image](https://user-images.githubusercontent.com/89584709/217530536-ff6a67a6-1af8-4092-8c98-eb2c2875041c.png)

Please share what you see in the history.
![image](https://user-images.githubusercontent.com/89584709/217530654-9c0e1d44-bc5f-4e29-a6fd-d9df515d8a7b.png)

**Comment by Jenefer-Monroe** [comment]
closing out due to inactivity, but please let me know if you still see this. I believe you've hit a product bug around triggers and resetting environments.

**Comment by Girijabaral** [comment]
[CoE Toolkit Error.docx](https://github.com/microsoft/coe-starter-kit/files/10823637/CoE.Toolkit.Error.docx)

**Comment by Jenefer-Monroe** [comment]
Re-opening the issue.

**Comment by Jenefer-Monroe** [comment]
Hello. Thank you for responding. I understand what you are seeing, your expected behavior is correctly. The run of **_Admin Sync Template V3_** should result in runs of flows like **_Admin Sync Template V3 (Flows)_**

I have a theory about the cause, but you will need to check for me. 
Please go to the Products admin page: https://admin.powerplatform.microsoft.com/ > Environments > Find your CoE environment > Click History from the ribbon
![image](https://user-images.githubusercontent.com/89584709/217530536-ff6a67a6-1af8-4092-8c98-eb2c2875041c.png)

Please share what you see in the history.
![image](https://user-images.githubusercontent.com/89584709/217530654-9c0e1d44-bc5f-4e29-a6fd-d9df515d8a7b.png)

**Comment by Jenefer-Monroe** [comment]
Hello just checking in to see if you need help finding this information. Without this investigation step we wont be able to assist. Please let me know.

**Comment by Jenefer-Monroe** [comment]
closing out due to inactivity,
