### ISSUE TITLE
[CoE Starter Kit - QUESTION] Number of model-driven app launches

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#4757]
### What is your question?

Is it a limitation of CoEStarterKit that the number of model-driven app launches is not captured when retrieving PowerApps launch counts? Or is it a limitation when retrieving audit logs?

Thanks.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.53

**Comment by Jenefer-Monroe** [comment]
Hello. Yes that is a limitation of the Office Audit Logs which is what we use today to gather launch information. Model Driven Apps do not write to that backend so we cannot fetch them. 

The good news is that we are iterating on a new architectural option for the CoE Starter Kit known as the BYODL (Bring your own datalake) (aka Self Service analytics) where the logs, including those of Model Driven app launches and flow runs, will be natively gathered rather than via this custom connector

You can explore this ahead of time if you would like
- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

We are currently working on integrating this with the CoE hoping to release sometime in the next few months.

**Comment by egym07** [comment]
Understood. Thank you.
Looking forward to your progress.

**Comment by vipulrai400074** [comment]
This feature is added in the new update? @Jenefer-Monroe 

We are facing an issue with the CoE (Center of Excellence) Power Bi Report. Can't able to see the model driven apps **"shared with user count"** and **"App launched count"** but for canvas app we can able to see the count in the power bi report.
 
We are using the CoE kit version January 2024.
