### ISSUE TITLE
[CoE Starter Kit - BUG]: BadRequest exceeds the maximum allowed

### ISSUE THREAD

**Issue by JimmyMoralesH** [microsoft/coe-starter-kit#476]
**Describe the bug**
I get an error _"exceeds the maximum allowed"_. by activating the flows associated with the Center of Excellence Starter Kit

**Component** (please tell us which flow or app you are experiencing issues with):

Solution : CenterofExcellenceCoreComponents_2_1_6_managed.zip
Version : 2.1.16
App or Flow: Flow CLEANUP - Admin | Sync Template v3 (Check Deleted)

Go to 'solutions --> Center of Excellence - Core Components --> Flow CLEANUP - Admin | Sync Template v3 (Check Deleted)'
Click on '....' --> click on 'Turn On'

**See error :** 
Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Error saving flow with code \"InvalidPaginationPolicy\" and message \"La directiva de paginación de la acción de ejecución de flujo de trabajo \"Get_Environments\" Type \"OpenApiConnection\" found on line \"1\" y column \"3071\" is not valid. El valor especificado de la propiedad \"minimumItemsCount\" supera el máximo permitido. Valor real: \"100000\"; máximo permitido: \"5000\".\"."}}".

**Screenshots**
![image](https://user-images.githubusercontent.com/84737793/119418358-d8fd7300-bcc5-11eb-9648-724a2830048f.png)

**Comment by manuelap-msft** [comment]
Hello, 

all the flows have this pagination policy. This error indicates that you are using an insufficient license.
Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes.

See here for the license types: https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles
And here for pagination limits: https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits

And hence our requirements for licenses. [What licenses do I need to run this solution?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-licenses-do-i-need-to-run-this-solution)

Thank you,
Manuela
