### ISSUE TITLE
[CoE Starter Kit - BUG] Recurring Office Hours invite not being sent

### ISSUE THREAD

**Issue by cwanja** [microsoft/coe-starter-kit#4815]
### Describe the issue

When registering for Office Hours and checking the box to get recurring meeting invites, I do not get a recurring meeting. I do get an invite, but only for the next month. That requires me to "register" for each month for office hours. 
![image](https://user-images.githubusercontent.com/54645561/219066455-d7a87393-e63e-4dd7-9b24-b63bb445f543.png)

### Expected Behavior

Invite sent to registered email address would include the recurring meeting going forward.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Teams Webinar

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. https://aka.ms/coeofficehours
2. Register and select "send me recurring invite"
3. Receive invite, but only for next month's meeting - not recurring

**Comment by manuelap-msft** [comment]
Hello,

I understand the question now - we host the office hours as Teams webinars, which do not support a recurring option. So we set the office hours up as a new webinar on a monthly basis and then send out the invite to previous attendees on a monthly basis. There's no recurring invite as that's not possible with webinars.

There's multiple reasons why we use Teams webinars vs regular teams calls, primarily because it allows us better control of what attendees can do in the call. 

Hope that clarifies it,
Manuela

**Comment by cwanja** [comment]
Thanks @manuelap-msft for the reply. However, I do not get the upcoming invites regardless of previous attendance or selecting that box. Happy to chat further on Teams (FTE Microsoft)

**Comment by manuelap-msft** [comment]
Can you confirm you received this email now?
![image](https://user-images.githubusercontent.com/55705669/219110546-1131ec23-602d-4809-9645-9488964d4bce.png)

**Comment by cwanja** [comment]
I did receive March's invite, but it is not recurring. Based on your previous comment, would I expect to automatically receive future invites when the Teams webinar is schedule?

**Comment by manuelap-msft** [comment]
Like I said, Teams webinars can't be recurring so we have to schedule them month on month. Yes, we have a flow that sends out those email reminders that had a bug which is why you haven't received the reminders previously. We fixed that bug now, so you should receive the reminders going forward. You can also always check https://aka.ms/coeofficehours and sign up from there.

**Comment by cwanja** [comment]
Thank you @manuelap-msft!
