### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Feb release update

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4817]
### What is your question?

my question is we have recently deployed December CoE kit in Prod 

Suddenly , there is  update on Feb release of CoE Kit 

we have not  any customization to the CoE Solutions , can we straight away upgrade our solutions to the latest version ?

Is there any major impact of apps in this release , all canvas apps are replaced with model driven app is it true ?

If yes what would the best approach  to continue with CoE.

Kindly please suggest

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
Hello. We release every month on the Wednesday of the first full week. We skipped the January release in order to have time for holidays, but generally speaking you can expect a monthly release. 
We recommend upgrading at least every 3 months in order for us to be able to assist you with your kit. Please see [Updating the Center of Excellence (CoE) Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/after-setup)

Your decision for which month to update, and if you want to have a staging environment for testing before updating Production, is up to you. It totally depends on how you are using us and for what. 
You can view descriptions of what changes were made here: https://github.com/microsoft/coe-starter-kit/releases/latest

It does include the introduction of some Model Driven Apps to replace canvas, but the canvas are still there while we get feedback. 

Overall Feb appears to be a very solid, high quality release based on the bugs posted. 

Hope that helps!

**Comment by pamatihyd** [comment]
thank you , for quick response ,you are great. 

my question is simple  If I decide to go,  if we did not apply customization , I  can simply upgrade without second thought ? why because there is nothing we have done in the solutions 

I could not find the details regarding which are all apps are replaced/replacing to  Model Driven Apps

Tried the above link you have shared but didnt get , Could you please help 
Is there any youtube link that you have talked about latest feb release with Model driven Apps ?

**Comment by manuelap-msft** [comment]
Here's the list of canvas apps that have been replaced:
![image](https://user-images.githubusercontent.com/55705669/219332111-37cbc0de-be17-479a-bebe-f4eb6c57e609.png)

We don't have recordings per release, but we do host monthly office hours to provide updates of what's part of a release and a place to answer questions - you can register for our next office hours at https://aka.ms/coeofficehours. We currently don't make the recordings of these office hours available publicly.

**Comment by pamatihyd** [comment]
Thanks alot , it has been a great help.
CoE tool kit is growing  with smooth automation.

**Comment by Jenefer-Monroe** [comment]
Wonderful to hear! I'll go ahead and close this out then but please let us know if you have more questions in the future!
