### ISSUE TITLE
[CoE Starter Kit - QUESTION] Last Launched Date

### ISSUE THREAD

**Issue by mbirge11** [microsoft/coe-starter-kit#4827]
### What is your question?

Hi, is it safe to say that if Last Launched Date is not populated for a record in Power Apps App, that app has never been launched?  Seems obvious, but I just want to confirm.

The earliest that records with a Last Launched Date value go back to is 12/7/2021, so I'm guessing this must be around the time we enabled our logs to track this information.  But if records have a blank Last Launched Date value, can I say they have never been launched any time between 12/7/2021 and now?

Thanks in advance.

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Happy to help. 

We introduced the idea of chunking warnings (saying you did not get all the logs) sometime early 2022. 

So as long as you have not been getting those chunking warnings, and you didnt have periods of time when the audit logs were not running, then yes you can assume you have gathered since early 2022

**Comment by mbirge11** [comment]
Great, thanks Jenefer.

**Comment by Jenefer-Monroe** [comment]
You bet, glad to help!
