### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log Connector (Office 365 Management API) - lost upon upgrade and won't save

### ISSUE THREAD

**Issue by DS2019** [microsoft/coe-starter-kit#4851]
### Describe the issue

I upgraded to Feb 2023 of the CoE Starter Kit. This is the first time I've upgraded with Audit Logs. The Audit Logs failed and the Custom Connector's connection could not be fixed. I deleted the connector and reimported the Core components. 
Under the new Office 365 Management API, I tried to go in and edit the custom connector to set it back. However, instead of a resource URL, I have a refresh URL (see screenshot). Plus, when I try to Update connector, it does not save at all. 
How can I get this upgrade back on track? Thanks!
![O365Mgmt](https://user-images.githubusercontent.com/44073678/220490395-fdc860ec-f9ab-4769-ac0e-0b156549c174.jpg)

### Expected Behavior

I have seen the other reports about bugs with upgrading the Audit Log. The fix seems to be to reset the custom connector up. However, it looks different from the screenshots in my case and it won't save. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb 2023

### What app or flow are you having the issue with?

Audit Log Custom Connector

**Comment by Jenefer-Monroe** [comment]
Hello. The default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2.
Please see https://github.com/microsoft/coe-starter-kit/issues/4808 for our work to update our documentation to reflect this. 

When editing the Security settings of the custom connector, in addition to [the steps described in our documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector) also set the identity provider to Azure Active Directory.

Thanks for posting.

**Comment by DS2019** [comment]
Hi,
Thanks for letting me know about the AAD change. When 
![AuditIssuesBlank](https://user-images.githubusercontent.com/44073678/220718420-0bff183b-a93d-4e74-a6f3-6b6a8ca4a94f.jpg)
I go to update the connector, it says it has successfully updated the connector, but everything under security returns to default. Do you know why this may be reverting?
Do I need to update the Azure Registration? I've been trying to get this to work for a couple days now. :(

**Comment by DS2019** [comment]
I tried anyway with the test subscription as I read in another bug report that the security info doesn't seem to save. I get a 401 - not sure why:
![AuthDenied](https://user-images.githubusercontent.com/44073678/220732351-1af16fc9-4d75-4246-a4a0-7d909ed0dee0.jpg)
One thing that is different in mine from the documentation is that what's called the login URL in the documentation it is called Authorization URL in mine and it defaults to: 
https://login.microsoftonline.com - as in the documentation I've changed it to: https://login.windows.net although I've tried it both ways with no success.

**Comment by apalfreyman** [comment]
I often have issues with the custom connector following CoE update.  The change to Generic OAuth 2 caught me out this time.  Changing to Azure Active Directory mostly resolved the problem, but I had to delete old instances of the connector from Connections.  Then in the "Test" section of the custom connector setup I created a brand new connection and used that to test and confirm a valid response.
![image](https://user-images.githubusercontent.com/97671589/220761021-fd16bc7d-0796-447a-8aab-2ca1ee1f345a.png)

(NB I believe that after pressing update on the "Security" config screen, everything there does return to blank/default values.  Authorization URL is defaulted to https://login.microsoftonline.com and I don't change it.)

I then re-linked that new connection to the two instances of the "Office 365 Management API CenterofExcellenceAuditLogs" connection references via the default solution and the audit log flows ran successfully again.  I'm not sure why there are two instances of the connection reference (CoE starter kit installed since ~January 2022), but it all seems to work fine now.
![image](https://user-images.githubusercontent.com/97671589/220761977-818b62cd-a7ef-42e3-962d-5233335a644b.png)

**Comment by DS2019** [comment]
Thank you, @apalfreyman - I've followed your steps exactly, from deleting out the old connection and creating a new one in test. That enabled me to get the 400 response:
![OperationFailedwith400](https://user-images.githubusercontent.com/44073678/220795008-8db69c2b-d27d-4d36-98e5-37a23c7afbfc.jpg)
I then went and found the 2 instances of the connection refs in the default solution and created the connection within to our service account on both. Will report back on if any success. 
Much thanks!

**Comment by Jenefer-Monroe** [comment]
This error here is expected if you have already enabled the subscription in the past. 
You can test here instead with a list subscriptions instead.

**Comment by DS2019** [comment]
All seems to be working. Thanks for your help and also a big thanks to @apalfreyman - your steps finally got the audit logs working again after upgrade!

**Comment by Jenefer-Monroe** [comment]
Thanks indeed @apalfreyman !!! 
I'll go ahead and close out.
