### ISSUE TITLE
[ALM Accelerator - QUESTION] Converted Solution in the developer Environment to Managed

### ISSUE THREAD

**Issue by ShinraTenseiii** [microsoft/coe-starter-kit#4864]
### What is your question?

Hi,

I successfully deployed My solution to Validation, Test and Production.

After successfully deploying the solution, I was in the Developer environment from where I was moving the solution.

It converted the solution in the developer environment to Managed.

I am confused about how will I make bug fixes or any other changes in my solution that is in the developer environment?

Please help me with a use case.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

 1.0.20230206.1

**Comment by mikefactorial** [comment]
@ShinraTenseiii the only way a solution could be converted from unmanaged to managed using the ALM Accelerator is if you ran the Delete solution pipeline against your solution. Other than that the pipelines will never convert an unmanaged solution to managed. Even if you accidentally tried to import into your dev environment as managed or had configured your deployment to deploy to your dev environment by accident the pipelines would fail because the unmanaged solution already exists. This was done on purpose to prevent this sort of situation. Are you sure that where you saw the managed solution was in the dev environment? I'm not entirely sure how this is possible. If there's any other details you can share about this experience or if you've been able to reproduce it would be good to understand what the specific steps were that lead to this.

**Comment by ShinraTenseiii** [comment]
Hi Mike,

I did check and I did run the Delete Solution pipeline once. It only removed the solution from the canvas app.

I am confused why would it convert the solution to managed after I run the Delete Solution Pipeline. I Assumed the delete Pipeline is to remove the solution from the Development Enviroment but it changed the solution to Managed.

I am sorry :( I forgot to mention I did run the delete pipeline on the solution in the dev environment.

**Comment by mikefactorial** [comment]
@ShinraTenseiii sounds like the delete pipeline failed at some point. This can happen if there was an app open in the maker portal or there was a dependency related issue. The delete pipeline runs in two stages. 

Stage 1: It will export the unmanaged solution and delete the unmanaged solution container.
Stage 2: It will import the solution as managed and delete the solution.

The effectively deletes all of the components associated with the unmanaged solution as deleting an unmanaged solution only deletes the container and the not the associated components.

You should be able to see the failure in Azure DevOps by looking at the pipeline run. If a failure occurs in the second stage you can rerun the stage. 
![image](https://user-images.githubusercontent.com/42348035/221968215-a02de970-be31-4341-ade9-2ad1d9d70814.png)

The idea behind deleting an unmanaged solution is to clear out any unmanaged components and then import the solution back from source control using the import functionality in the ALM Accelerator.

**Comment by ShinraTenseiii** [comment]
Hi Mike,

The pipeline failed due to dependencies.

I am unable to delete the Managed solution now.

I even reran the failed jobs but it is still failing because dependencies exist.

I removed the dependency from the environment itself and it still shows me there are missing dependencies but I have already deleted it from the environment.
