### ISSUE TITLE
[CoE Starter Kit - BUG] Reminders keep being sent although user already took action by rejecting

### ISSUE THREAD

**Issue by MartijnSmeitinkJDE** [microsoft/coe-starter-kit#4880]
**Describe the issue**
Although action is already taken (rejected) person is reminded every week. 
Perhaps I misconfigured something, but according to the explanation a reject or accept of the e-mail should stop the call to action for at least a month?

**What solution are you experiencing the issue with?**
Core

**What solution version are you using?**
Feb release

**What app or flow are you having the issue with?**
CLEANUP 

**Steps To Reproduce**
For us this happens every week

**Anything else?**
I have example e-mails I can share that prove the point.

**Comment by Jenefer-Monroe** [comment]
There was a bug a few months ago which caused this behaivor but it no longer repros in the latest builds. 
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by MartijnSmeitinkJDE** [comment]
Sure, I think this is what you mean:

![image](https://user-images.githubusercontent.com/125970351/221681118-829812ad-4c29-4970-b483-c54d82badea3.png)

**Comment by Jenefer-Monroe** [comment]
Yes I believe you have hit the bug in which, when we moved shipping tenants, some operands in flows got lost.
This is fixed in the Feb release so please [update to Feb](https://review.learn.microsoft.com/power-platform/guidance/coe/after-setup?branch=coe-march2023) to see that fix.

**Comment by MartijnSmeitinkJDE** [comment]
I will upgrade, and let you know on Monday!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
