### ISSUE TITLE
Can't set communication methods in CoE Setup Wizard (bug fixed in February, duplicate)

### ISSUE THREAD

**Issue by ManuelVermeyen** [microsoft/coe-starter-kit#4898]
### Describe the issue

In COE upgrade wizard we want to configure communication methods.
-admin persona
-maker persona
-user persona

We have created M365 groups for this in Azure AD the way it is described.  Then we waited for synchronization.
When we want to configure these groups in COE upgrade wizard, the groups are not shown in the dropdownmenu where you can select a group for de persona.  There are groups shown there but none of them has anything to do with COE.

### Expected Behavior

I want to see the created groups in that list that were created for the COE.  How can we see those groups?

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

CoE Upgrade wizard - configure communication methods

**Comment by manuelap-msft** [comment]
This is related to pagination limits on the Office 365 Groups connector and was fixed in the February release, where you're now able to put in the email/ID of the group in a text field rather than using the drop down:
https://github.com/microsoft/coe-starter-kit/issues/4494#issuecomment-1384129326

February has proven to be a really stable release, so I do recommend you upgrade. If for some reason you can't upgrade, you can update the communication methods manually by updating the environment variables as mentioned here:
https://github.com/microsoft/coe-starter-kit/issues/4632#issuecomment-1397198142

**Comment by manuelap-msft** [comment]
closing out some old issues that we missed to close
