### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by michael-wright-pwc** [microsoft/coe-starter-kit#4901]
### Describe the issue

The "Admin | Sync Template v3 (Ai Models)" cloud flow is throwing errors when trying to execute on environments located in regions that do not support AI Builder (i.e. environment hosted in South Africa).

Here is what the error message says (usually thrown in the action "Get AiModel Template"):
{
  "status": 400,
  "message": "{\"operationStatus\":\"Invalid\",\"error\":{\"type\":\"Error\",\"code\":\"RegionNotSupported\",\"message\":\"AI Builder is not enabled for this region\"}}",
  "error": {
    "message": "{\"operationStatus\":\"Invalid\",\"error\":{\"type\":\"Error\",\"code\":\"RegionNotSupported\",\"message\":\"AI Builder is not enabled for this region\"}}"
  },
  "source": "[redacted]",
  "errors": [],
  "debugInfo": "clientRequestId: [redacted]"
}

For some reason I cannot upload screenshots to this ticket - if you need them (or the IDs redacted in the error message above) send me an email: michael.v.wright@pwc.com.

### Expected Behavior

Expect this flow not to run for environments located in regions not supported by AI Builder.

Please add a check at the beginning of this flow to terminate the flow if the environment's region does not support AI Builder to prevent unnecessary sync flow errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Ai Models)

### Steps To Reproduce

1. In a tenant with environments located in regions unsupported by AI Builder
2. Open a "Admin | Sync Template v3 (Ai Models)" flow run triggered by an environment in a region unsupported by AI Builder (i.e. South Africa)
3. Drill down through these actions: Put Ai Models in CoE -> Apply to each Ai Model -> Get Related Objects -> Get AiModel Template
4. Get AiModel Template is always the action that throws the error. (see error details above)

**Comment by manuelap-msft** [comment]
Thanks for raising this! We're already tracking this as an enhancement here #4699 - we don't think there's an automated way for us to see in which region AI Builder is available, and we're a little hesitant hard-coding region names into the flow (as if AI Builder becomes available, we'd have to update the flow and customers on a previous version of the kit would not receive the latest inventory). We're investigating if there's an automated way to check if AI Builder is available. 

To set expectations, this is not a high priority on our backlog right now due to other feature asks that have a higher priority.

**Comment by manuelap-msft** [comment]
I'm closing this duplicate as we're already tracking this.
