### ISSUE TITLE
[CoE Starter Kit - QUESTION] I've noticed some apps have been marked as deprecated with the February release, what do I need to do with them?

### ISSUE THREAD

**Issue by EnsilaC** [microsoft/coe-starter-kit#4906]
### Describe the issue

hi Team, 

We upgrade the COE kit to the latest version, and now we have several apps [deprecated]. I have understood that these apps are replaced with other ones, but i want to keep this environment tidy, so to remove these apps. 
While i tried to delete a message pop up which basically confirms that i cant delete them as are part of a solution. 
Can you please let me know what should be done in this case?
![image](https://user-images.githubusercontent.com/123632961/222692332-d8912687-5278-4c4a-9c91-1e833ca321db.png)

### Expected Behavior

After the upgrade, all deprecated apps should have been automatically removed

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power platform training management

### Anything else?

there are several apps marked as deprecated. PLease see the screenshot above

**Comment by manuelap-msft** [comment]
Hello,

that's correct, we deprecated some canvas apps and replaced them with model driven apps that use custom pages, as that allowed us to use Creator Kit components for a Fluent UI look and feel and made collaboration on development easier for us. 

**Here's what you need to do:**
If you are currently using one of the apps that's been marked as deprecated, unshare the deprecated version and re-share the new app with your colleagues.

**Here's what we will do:**
The deprecated apps were left in the solution so that customers who are using them have time to unshare them and re-share the new version, get familiar with the new version or take a copy of the old version if they want to stick with it.
There's no need for you to delete the app, we will delete it from the solution in about 3 months but we needed to give customers some time to migrate to the new apps - hence why we didn't just delete them.

Hope that helps,
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
