### ISSUE TITLE
[CoE Starter Kit - Feature]: Allow Audit Log operation filtering using Environment variables

### ISSUE THREAD

**Issue by alinefmr** [microsoft/coe-starter-kit#4910]
### Is your feature request related to a problem? Please describe.

Power Automate flow "**[Child] Admin | Sync Logs**" filters audit log results based on the "Operations" field: **LaunchPowerApp**, **DeletePowerApp**, **DeleteFlow**, and **PowerAppPermissionEdited** are the only filtered and persisted categories. 
It would be helpful allowing a dynamic selection that doesn't require editing the flow itself.

### Describe the solution you'd like

Please leverage environment variables to allow custom entries. Instead of adding filter values directly as

_@or(equals(item()?['Operation'], 'LaunchPowerApp'), equals(item()?['Operation'], 'DeletePowerApp'), equals(item()?['Operation'], 'DeleteFlow'), equals(item()?['Operation'], 'PowerAppPermissionEdited'))_

Consider using ennvironment variables to allow custom entries at the "Filter array" action (within "Apply to each cluster"):
![childlogs](https://user-images.githubusercontent.com/40579000/222863658-640fb971-6c6f-4d22-a6d8-b571f7a37486.jpg)

### Describe alternatives you've considered

Alternatives include editing the flow, generating unmanaged layers, and are not ideal.

**Comment by Jenefer-Monroe** [comment]
This format for gathering usage has been riddled with issues due to the limitations of the backend. Luckily we are able to start gathering usage information using native product features with the upcoming Bring your own Datalake / Self Service Analytics features. 

We will be shipping public preview of that integration with CoE in a few weeks. You can explore this ahead of time if you would like:
- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

We will not continue to iterate on this technique of gathering usage as a result, though it will stay available in the kit for those that are just exploring the kit or cannot get access to the DL features.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
