### ISSUE TITLE
[CoE Starter Kit - QUESTION] PBI issue: Data source error: The 'admin_userprinciplenamewithoutspecialchars' column does not exist in the rowset. Table: Maker.

### ISSUE THREAD

**Issue by EnsilaC** [microsoft/coe-starter-kit#4918]
### What is your question?

hi Team, 

From the last upgrade of the COE ( feb Fix) the Power BI dataset cant be refreshed with the message : 
Data source error: The 'admin_userprinciplenamewithoutspecialchars' column does not exist in the rowset. Table: Maker.
Cluster URI: WABI-NORTH-EUROPE-D-PRIMARY-redirect.analysis.windows.net
Activity ID: d49a5915-9d10-43f8-9302-68445e7b3ab9
Request ID: dea9a5c6-34b9-4e42-9306-9cf1f8588251
Time: 2023-03-05 23:04:22Z

Can you please let us know how to fix this ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power BI Report

**Comment by Jenefer-Monroe** [comment]
We did remove that column but I dont see it being referenced in our PBI anywhere, so I dont repro. Did you use the latest PBI from the folder as well?

**Comment by EnsilaC** [comment]
hi Jenefer, 

these are the latest POwer BI files installed 
![MicrosoftTeams-image (35)](https://user-images.githubusercontent.com/123632961/224274039-e4d9c300-da77-47d6-a2c5-f58ad6335b6a.png)

**Comment by Jenefer-Monroe** [comment]
Sorry I meant did you use the PBI from the Feb release folder when you downloaded the CoE?

**Comment by EnsilaC** [comment]
hi Jenefer,

We used the latest release of FEB for the COE Kit.
Inside the folder we couldn’t see a PBI component, but if you have the appropriate one we can try again to upload

Best regards,

Ensila Cuku
Application Consultant

[Fagron]

**Comment by Jenefer-Monroe** [comment]
Inside the [feb release download](https://aka.ms/coestarterkitdownload) you will see pbit files, a power bi template
![image](https://user-images.githubusercontent.com/89584709/224691006-7cb77c78-f3dc-4212-8f83-bee8dcc244c5.png)

We have to use a pbi template file because that way it can take it your data and apply. 
You open the pbit and enter your org url, then hit load, and sign in several times :)
![image](https://user-images.githubusercontent.com/89584709/224691735-136835ed-504e-4cbc-b911-3b4e9978ae24.png)

Please see [setup powerbi](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi) for more details

**Comment by yhaugom** [comment]
We did experience the same issue using the Power BI template named **_PowerPlatformGovernance_DoEDashboard_February2023_**
![image](https://user-images.githubusercontent.com/1016457/226302627-ebd72ecd-81f7-4b43-86a7-2da56c3d8d59.png)

![image](https://user-images.githubusercontent.com/1016457/226301471-2497ea00-1dba-4f59-a934-762a63a40056.png)

However, I tried to open it again and republish, and now it seems to be working. The first time I published it, the newest version of the CoE Core Components solution was not done importing. Could this somehow be the reason?

**Comment by Jenefer-Monroe** [comment]
There may be some kind of delay between PBI and Dataverse, I'm not sure. But I'm glad this got resolved now! 
I'll keep an eye on this when I see it to see if I can find clarity on the issue. For now I'll go ahead and close since you are unblocked. But do open new issues for us if you need more help!

**Comment by Jenefer-Monroe** [comment]
Oh i didnt even notice that thank you. 
The last contact with them was a week ago, which is when we close for inactivity anyway, so I'll go ahead and leave it closed. 
Thanks for letting me know though!
