### ISSUE TITLE
[CoE Starter Kit - BUG] Setup wizard prompting for the email address rather than the Azure Group ID for CoE Makers

### ISSUE THREAD

**Issue by EnsilaC** [microsoft/coe-starter-kit#4919]
### Describe the issue

Admin | Add Maker to Group failing with the error message : The 'inputs.parameters' of workflow operation 'List_group_members' of type 'OpenApiConnection' is not valid. Error details: Input parameter 'groupId' is required to be of type 'String/uuid'. The runtime value '"PP_COE_Maker@fagron.onmicrosoft.com"' to be converted doesn't have the expected format 'String/uuid'.

We added the PP_COE_Maker@fagron.onmicrosoft.com in the COE Creator Kit wizzard, and this flow is picking up from there the group. 
Can you help why is showing this error message?

### Expected Behavior

Admin | Add Maker to Group to run successfully and the makers to be added in the group PP_COE_Maker@fagron.onmicrosoft.com automatically

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Add Maker to Group

**Comment by manuelap-msft** [comment]
Hello,

we made a mistake in the setup wizard prompting for the email address rather than the Azure Group ID for this environment variable. This will be fixed in the next upgrade.

In the meantime, find the Group ID for this email address and use the CoE Admin Command Center > Environment Variables page to update the **Power Platform Maker Microsoft 365 Group** environment variable.
