### ISSUE TITLE
Delete Resources from the Power Platform Admin View

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#4951]
As an admin, I'm in the process of cleaning up flows that are not needed. The flow owners have deleted their flows, but they are still showing up in the Power Platform Admin View app. What is the process to delete them from the Power Platform Admin View? In the Flows table, do I need to change the Flow deleted field to Yes then manually run the CLEANUP HELPER - Check Deleted (Cloud Flows)?

**Comment by manuelap-msft** [comment]
Hello,

you won't have to manually mark flows as deleted - the **CLEANUP - Admin | Sync Template v3 (Check Deleted)** runs on a schedule to check what's deleted from your tenant and marks things up as deleted accordingly. I believe this flow runs weekly or bi-weekly as it's high in API calls so what you see in the Power Platform Admin View might not be totally up to date because of that - you can kick off the CLEANUP - Admin | Sync Template v3 (Check Deleted) manually to get things up to date.

**Comment by dcurt1977** [comment]
Thank you very much, this is very helpful as I can confirmed that kicking off the CLEANUP - Admin | Sync Template v3 (Check Deleted) manually did get things up to date in the Power Platform Admin View.

**Comment by manuelap-msft** [comment]
That's great, thanks for confirming! I'll close this issue for now but please let us know if you have further questions.
