### ISSUE TITLE
[no project] Question related to Data Export feature, not related to CoE kit

### ISSUE THREAD

**Issue by SFDCMAN** [microsoft/coe-starter-kit#4956]
### Describe the issue

I am trying to implement BYODL feature in my tenant to get telemetry data.
I have already created my AZ DL and I am starting the creation of dataflow to get **application** files json data, I am facing a problem when loading data from json file error message "We found extra characters at the end of the JSON input." 
I have tested with "Environment" json files and it seems to be ok.
![we found an extra characters at the end of the JSON input](https://user-images.githubusercontent.com/936867/224300098-c4b944af-5d1a-4d7e-9da5-c5f121791443.png)
![Applications_DataLake_json_files](https://user-images.githubusercontent.com/936867/224300103-450e6be5-42a0-4e30-ad59-3e3c128c75a9.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

N/A

**Comment by manuelap-msft** [comment]
Hello,

It sounds like you're trying to connect to the files in the Storage Account provided by the [Data Export](https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics) feature by creating a dataflow yourself to transform the data, is that right? 

If so, the Data Export feature is part of the Power Platform Admin Center and not related to the CoE kit at all, so I'm afraid we can't help you there. I believe the reason you're getting this error is because the files are in json line format, not json format - see: https://learn.microsoft.com/en-us/power-query/connectors/json#troubleshooting so looking at the documentation there, that might unblock you.

We're also about to release the integration of the CoE kit with the Data Export feature next week and that will contain some dataflows that do this transformation, so you could wait until then and look at the dataflows in the CoE kit to copy from there if you still want to create your own.

Manuela
