### ISSUE TITLE
Child sync flows failing- Custom connector not working after upgrade

### ISSUE THREAD

**Issue by Natashamg** [microsoft/coe-starter-kit#4960]
### Describe the issue

I recently upgraded the CoE, the sync flows keep failing. The Office 365 api management custom connector isn't working.
The connection has been re-established, but when I test the connector, it fails with and error saying I'm not authorized. I've followed the setup of the connector according to the document and still doesn't work. Can you please help me figure out what is wrong?

### Expected Behavior

Sync flows run successfully

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
Hello. Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

If that does not resolve, then you likely ended up with a bad connection, perhaps due to the wrong identity provider being selected as in [issue 4808](https://github.com/microsoft/coe-starter-kit/issues/4808)

If that occurs please try the steps outlined in [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

Sorry for the complexity here!

**Comment by Jenefer-Monroe** [comment]
You are so welcome!
