### ISSUE TITLE
[CoE Starter Kit - QUESTION] Force the refresh of deleted apps

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#4978]
### What is your question?

Hi,

I've deleted an inactive app since 3 weeks now and it's still present in the Poduction report and power platform Admin view app.
I checked once again with the concerned user and the app is deleted. 

Am i missing something ?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Feb 2023

**Comment by manuelap-msft** [comment]
Hello,

can you check when the **CLEANUP - Admin | Sync Template v3 (Check Deleted)** flow has last run, and if it has run successfully? You may also want to manually run it and see if that resolves the issue. Due to the high number of API calls this flow consumes, it's set to run only every 2 weeks. 

Manuela

**Comment by tocri** [comment]
@manuelap-msft You rocks. I don't know why, the flow was off. Now all seems good. I'm happy

**Comment by manuelap-msft** [comment]
Amazing, so glad that worked for you! :)
