### ISSUE TITLE
[CoE Starter Kit - BUG] Flow whose owner is group instead of user is still considered orphan flow

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/coe-starter-kit#5015]
### Describe the issue

We have bunch of flows whose owner is my team's group instead of me so that anyone in the team can have access and modify the flow. It seems like CoE doesn't consider group address as owner and list it as orphaned flow.

### Expected Behavior

The flow shouldn't be listed under orphaned flow.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Set Flow Permissions

### Steps To Reproduce

1. Create and save flow 
2. Change the owner of your flow from you to one of the Azure AD group
3. Check the 'Set Flow Permissions' > 'Orphaned Flow', your flow should show up there. (might have to wait until the admin sync flow runs to pick up your new flow and owner information)

### Anything else?

![image](https://user-images.githubusercontent.com/3292092/225698079-0bb7fe72-4d21-4f41-93ac-a48b189a7469.png)

![image](https://user-images.githubusercontent.com/3292092/225697385-5c482545-73ff-452b-b044-b0456782db98.png)

**Comment by Jenefer-Monroe** [comment]
Unfortunately it looks like ownership assumes a person and not a group, and a pretty low level, in our kit. So we will need to put this on the backlog to investigate. 
In the meantime you can set the derived owner to a person and the kit will use that person for its processes without you losing the benefit of group ownership in the product. 
To do this you will need to edit in the grid view in Dataverse like this:
Go to the flow table, edit the columns so that you can see the needed columns to make the change and click edit for full screen
![image](https://user-images.githubusercontent.com/89584709/225874920-dfd997f7-5d92-47b5-92a7-15df39c208d3.png)

Filter to your cases and update the derived owner to be an individual
![image](https://user-images.githubusercontent.com/89584709/225875389-e02a1d00-cf4b-4756-83b7-6ca798824f8b.png)

**Comment by sanjeev40084** [comment]
@Jenefer-Monroe thank you for the info. i added myself as the DerviedOwner in the Flow table but i don't see any changes on the 'Admin - Flow Permission Center' > orphanced flow view. Since i am updating Dataverse table directly, i believe just refreshing the canvas app should pick up the change isn't it?

**Comment by Jenefer-Monroe** [comment]
No there are processes which woudl update the orphan status from here. You can short circuit this by manually updating the flow column to no as well, then you would see it in the apps immediately. 
![image](https://user-images.githubusercontent.com/89584709/226006510-efca6821-1bfc-4409-95d8-fe9536e9bb5c.png)

**Comment by sanjeev40084** [comment]
@Jenefer-Monroe updating 'Flow is Orphaned' column for one of the row made it not show up on under orphaned flow view. i will let the rest be updated through the scheduled cloud flow. thanks again 👍 p.s: i feel like there should be whole separate documentation where we could short circuit things to see the changes right away 😄

**Comment by Jenefer-Monroe** [comment]
Half my brain is filled with shortcuts for the CoE Starter Kit :)

**Comment by sanjeev40084** [comment]
definitely worth blog article 😎😎😎
