### ISSUE TITLE
[CoE Starter Kit - QUESTION] what are the sync flows that need to be turned on in BYOD version

### ISSUE THREAD

**Issue by ValentinMaz** [microsoft/coe-starter-kit#5032]
### What is your question?

When using the DataExport in the COE Starter Kit, what are all the sync flows that need to remain turned on? I couldn't find this in the documentation.
I understand that some tables (Apps, Flows, ...) are populated from the Data Export and dataflows but that other information is still gathered from the sync flows (AI Models, Connectors, ...). Would it be possible to confirm the full list of sync Flows that should remain turned on with the BYOD configuration?
Many thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

**Comment by Jenefer-Monroe** [comment]
Hello. Yes this information is stored in the CoE Solution Metadata table, which is where we get the information from in order to turn on / off the flows correctly. 

![image](https://user-images.githubusercontent.com/89584709/226203027-72a57ea6-c258-4ebc-9f03-d46c73fdf1fa.png)

Here are the ones used for inventory so you dont have to fetch yourself but just so you know where you can look at any time. 

- Admin | Add Maker to Group
- Admin | Excuse Non Inventoried Envts from Governance Flows
- Admin | Excuse Support Envts from Governance Flows
- Admin | Sync Template v3 (Ai Models)
- Admin | Sync Template v3 (App Properties)
- Admin | Sync Template v3 (Business Process Flows)
- Admin | Sync Template v3 (Call Updates)
- Admin | Sync Template v3 (Connection Identities)
- Admin | Sync Template v3 (Connectors)
- Admin | Sync Template v3 (Custom Connectors)
- Admin | Sync Template v3 (Desktop Flow - Runs)
- Admin | Sync Template v3 (Desktop flows)
- Admin | Sync Template v3 (Environment Properties)
- Admin | Sync Template v3 (Flow Action Details)
- Admin | Sync Template v3 (Portals)
- Admin | Sync Template v3 (PVA Usage)
- Admin | Sync Template v3 (PVA)
- Admin | Sync Template v3 (Solutions)
- Admin | Sync Template v3 (Sync Flow Errors)
- Admin | Sync Template v3 CoE Solution Metadata
- Admin | Sync Template v3 Configure Emails
- CLEANUP - Admin | Sync Template v3 (Check Deleted)
- CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
- CLEANUP - Admin | Sync Template v3 (PVA Usage)
- CLEANUP HELPER - Check Deleted (Ai Models)
- CLEANUP HELPER - Check Deleted (Business Process Flows)
- CLEANUP HELPER - Check Deleted (Custom Connectors)
- CLEANUP HELPER - Check Deleted (PVA)
- CLEANUP HELPER - Check Deleted (Solutions)
- CLEANUP HELPER - Power Apps User Shared With
- Command Center App >  Get M365 Service Messages
- Command Center App > Get CoE Flows
- Command Center App > Initially Populate Bookmarks
- Command Center App > Set CoE Flows State
- DLP Editor>Parse impacted resources into CSV
- HELPER - Add User to Security Role
- HELPER - CanvasAppOperations
- HELPER - CloudFlowOperations
- HELPER - Maker Check
- HELPER - ObjectOperations
- HELPER - Send Email
- SetupWizard>CallOrphanFlow
- SetupWizard>CreateGroup
- SetupWizard>GetCurrentEnvironment
- SetupWizard>GetTenantID
- SetupWizard>GetUserDetails
- SetupWizard>RunInitialFlows
- SetupWizard>ShareApps
- SetupWizard>UpdateInventoryTypeAppSetting
- SetupWizard>UpdateDataflowEnvironment
- CoE BYODL - When Maker dataflow refresh is complete
- CoE BYODL - When Environment dataflow refresh is complete
- CoE BYODL - When Model App dataflow refresh is complete
- CoE BYODL - When App dataflow refresh is complete
- CoE BYODL - When Flow dataflow refresh is complete

**Comment by ValentinMaz** [comment]
Thank you very much for this, this is exactly what we needed - this table is fantastic.

**Comment by Jenefer-Monroe** [comment]
You are most welcome! I'll go ahead and close but please return with any other questions.
