### ISSUE TITLE
[CoE Starter Kit - QUESTION]  Ensure the secret being sent in the request is the client secret value, not the client secret ID error when setting up audit log

### ISSUE THREAD

**Issue by tucoeadmin** [microsoft/coe-starter-kit#5034]
### Describe the issue

Can not Create Custom Connection Office 365 Management API for audit log

### Expected Behavior

I have successful setup COE starter kits recently. but one day I update core component to v.4.3 and I've check all features
such as audit log to ensure my COE can get update data but I found that my workflow has stopped.
I don't know when it stopped.
then I try to check custom

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.1

### What app or flow are you having the issue with?

Center of Excellence - Audit Logs

### Steps To Reproduce

1.Select Environment : COE-TU
2. Connections
3. New Connection
4. search for "Office 365 Management API"
5. click "Create" then "Create" button
6. provide user id "coea.....@xxxxx.com"
7. I get error message.
"OAuth2 authorization flow failed for service 'Azure Active Directory'. OAuth 2 sign in failed to exchange code for access token. Client ID and secret sent in form body.. Response status code=Unauthorized. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '7178754a-8f99-47c1-9c62-1bd076015c45'.\r\nTrace ID: 0222fad6-8122-4469-81bc-f772ec139500\r\nCorrelation ID: 734ec4db-379c-42dd-8406-10b252afc55e\r\nTimestamp: 2023-03-20 02:55:58Z","error_codes":[7000215],"timestamp":"2023-03-20 02:55:58Z","trace_id":"0222fad6-8122-4469-81bc-f772ec139500","correlation_id":"734ec4db-379c-42dd-8406-10b252afc55e","error_uri":"https://login.windows.net/error?code=7000215"} Client ID and secret sent in Basic authorization header.. Response status code=Unauthorized. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '7178754a-8f99-47c1-9c62-1bd076015c45'.\r\nTrace ID: 39052f72-3618-44bf-a610-5a67ef362500\r\nCorrelation ID: 2b2ebec0-1d79-4103-84b4-70785f85f6c1\r\nTimestamp: 2023-03-20 02:55:58Z","error_codes":[7000215],"timestamp":"2023-03-20 02:55:58Z","trace_id":"39052f72-3618-44bf-a610-5a67ef362500","correlation_id":"2b2ebec0-1d79-4103-84b4-70785f85f6c1","error_uri":"https://login.windows.net/error?code=7000215"}"
![image](https://user-images.githubusercontent.com/100560236/226236233-e2bc13ab-98ee-4c8a-8c76-c4ba331a2e35.png)

### Anything else?

what's wrong to my connection?

**Comment by manuelap-msft** [comment]
Hello,

here's a couple of troubleshooting tips for this:
- Recently the default identity provider for custom connector has changed, and needs to be updated to Azure Active Directory when you update the security details - see https://github.com/microsoft/coe-starter-kit/issues/4808
- Sometimes when a bad connection is created, it's hard to clean it up - here's a write up of what to try https://github.com/microsoft/coe-starter-kit/issues/4961
- From the error message in the red area it sounds like you might have copied the Secret ID rather than the Secret Value into that field, here's some screenshots on what value to copy https://github.com/microsoft/coe-starter-kit/issues/5027#issuecomment-1474191824

Hope these help you resolve the issue
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
