### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to update app status via Developer Compliance Center

### ISSUE THREAD

**Issue by ajeyng** [microsoft/coe-starter-kit#5055]
### Describe the issue

1. Encountering issue when updates records via Developer Compliance Center. 
2. Power Platform Maker SR has been shared with the App & the M365 user group is assigned the Maker SR.

### Expected Behavior

Maker should be able to submit Compliance updates which marks the Risk status of App as Submitted & Justification provided in the BPF updates as "Yes"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. Encountering issue when updates records via Developer Compliance Center. 
2. Power Platform Maker SR has been shared with the App & the M365 user group is assigned the Maker SR.

### Anything else?

![image](https://user-images.githubusercontent.com/107418214/226715013-f1d5b23c-548b-4e07-af26-818d49741604.png)

**Comment by Jenefer-Monroe** [comment]
I reprod this for a few apps and they turned out to be deleted (but the check deleted clean up flow had not yet run)
If you click App settings, does it bring you to an error page? 
![image](https://user-images.githubusercontent.com/89584709/227069728-ecc3d4a7-2056-4876-96a0-b4ee61d6480e.png)

Then if you run **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_**, do the app get removed from the UX?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
