### ISSUE TITLE
Action 'Get_Environment' failed[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by achaganti** [microsoft/coe-starter-kit#5068]
### Describe the issue

Core Component "Admin Sync Template V3" failing with error:
Action 'Get_Environment' failed

All helper flows are running fine. 

### Expected Behavior

FLow to be successfully and data to be generated. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin - Sync Template V3

### Steps To Reproduce

Error
Action 'Get_Environment' failed 

Error when the flow runs. 

### Anything else?

nothing

**Comment by Jenefer-Monroe** [comment]
Please note that failures like this are caught/expected failures. 

We use these calls to see if the object is new to the inventory, and if it is, this call to “get it” will fail. This failure is caught and the “isnew” variable is set to true. 
![image](https://user-images.githubusercontent.com/89584709/225679681-01467de5-1a1c-4c93-bf57-71296f5ea83b.png)

In order to debug you need to find the terminating failure in the flow. Here for example the call to “forced failure” failed, and was not caught, so the flow terminated here. That is the spot you need to find in your failure in order to debug. 
![image](https://user-images.githubusercontent.com/89584709/225681214-a5549790-32e9-482e-b427-0c346aa50684.png)

**Comment by achaganti** [comment]
I see its failing at this stage 
![image](https://user-images.githubusercontent.com/34516164/227205147-07a348f1-14f4-495a-a607-76f956166ecf.png)

**Comment by Jenefer-Monroe** [comment]
yes you have to dive in to the failure, here is an example from another flow to show you what I mean. You look below that condition to find where it terminates. 
![image](https://user-images.githubusercontent.com/89584709/227342293-88e1ccad-14c1-4338-b047-fdeb7c9278f5.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
