### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by jacobbrooks-scoular** [microsoft/coe-starter-kit#5075]
### Describe the issue

In the PowerPlatformGovernance_CoEDashboard_February2023 Power BI File the 'Audit Log' table has not updated data since 05/30/2022.  It seems like this source has not been updating and I cant figure out where this datasource is failing at.

![GitHub Ticket](https://user-images.githubusercontent.com/101224151/227234799-799f9a60-f9ee-414b-9e9e-1b75eb6075fa.png)

### Expected Behavior

Expected behavior is to have data current within this Audit Log table.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Unknown

### What app or flow are you having the issue with?

Unknown

**Comment by Jenefer-Monroe** [comment]
Hello. Connections to custom connectors get broken on solution upgrade, so likely that is what has occurred. 

Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

If that does not resolve, then you likely ended up with a bad connection, perhaps due to the wrong identity provider being selected as in [issue 4808](https://github.com/microsoft/coe-starter-kit/issues/4808)

If that occurs please try the steps outlined in [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

Sorry for the complexity here!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by jacobbrooks-scoular** [comment]
Sounds good thank you Jenefer
