### ISSUE TITLE
[CoE Starter Kit - BUG] Desktop Flows Report (Total)

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#5085]
### Describe the issue

Looking at the BI report for Desktop flows there is a total #flows that is the sum of rpa_id

Yet in the grid showing all the desktop flows is the column ID which is actually renamed admin_name field.

So the number of flows in the grid is significantly smaller than that of the total flows.

### Expected Behavior

Im not sure what rpa_ID is vs admin_name,   but if I show the rpaid in the grid I can see duplicate adminnames for lots of different rpaids,   so Im guessing that there are duplicate entries per desktop flow 

In which case the total should be against the adminname not the rpaid.   If its the other way round then what on earth is going on in the grid and the collection data ?

Thanks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb 2023

### What app or flow are you having the issue with?

PowerBI Report

### Steps To Reproduce

Have lots of desktop flows ad look at th report.

**Comment by binaryjam** [comment]
A similar problem I have is that the creation trend in my report has over 1k of desktop flows, when we havent enabled the client, except for some admins.

The total number of DFlows it says is 1207,  whereas the total distinct admin_names is 103 which matches the grid data and sounds reasonable for our env, 

That said I have one Test desktop flow but two show in the grid , so Im not sure of the collection data is 10% here either.
I'd triggered  full inventory yesterday so, this should be restingthe data.   Perhaps the report is fine and the collected data needs fixing?

**Comment by Jenefer-Monroe** [comment]
The reason we have name and rpa id as separate GUIDs is because the product re-uses GUIDs across envts for desktop flows installed there. So you have name (not unique) and RPA_ID (unique) 
We then have a third column "RPA Unique Name" that is a concatination of envt and name, so that we can do a lookup. 
Pretty convoluted and confusing, but thats what it is. 

As you can see here, this Desktop flow exists in multiple envts and so has the same "name". 
![image](https://user-images.githubusercontent.com/89584709/227996114-20313b26-528e-4fc2-9a25-7dc8b2637cae.png)

**Comment by Jenefer-Monroe** [comment]
I do see all the objects on that screen using RPA_ID for the count though not name. So I'm not sure what you are seeing. Can you share a screenshot so I can understand better?

**Comment by binaryjam** [comment]
I've checked the Table and the flow runs, there are only 3 env I have DTF in,  the flow run matches my expectations, of DTF 78, 16, 5.

In the RPA table If I filter by env ID, there are only 3 envs collected for, though the contents all messed up in dev and some in prod.

The flow runs seem to be ok, they are entering the correct flows into that table and have correctly combined unique names.

The common element in the bad entries 1100 approx of them, is that the env ID isnt concatenated, its missing from the unique name and contains only the rpa_id.  

To fix this, I think I need to delete anything whose unique ID doesnt begin with the 3 env ids I have, or possibly the length of the unique id is < len of a guid. (36/37) call it 40 and its still ok.    Im not sure if I should do this or reallly the best way.

But doesnt explain why this is happening, and it is happening in my prod data,   I dont have examples of failed flow runs to check , there are too many runs.  
_Is it possible to use trigger conditions to exclude the teams envs to reduce the number of runs ? Would that work, the first condition is using all trigger variables.  ? Would that be worse.  This is another topic though, so ignore this for the purpose of this ticket, my brains wandering._

**Comment by binaryjam** [comment]
Hi , Have you any thoughts on this topic ,   can I delete the bad data  I thought a flow like this seems to selectr the correct things.
![image](https://user-images.githubusercontent.com/7352864/229104666-9e9e4db6-065f-4dd2-8b71-c0bfed2cf65e.png)
As the field should contain a valid env and I got 3 with DTFs in this seemed like it would work and then delete the DV item.

But I have this in dev and prod, so something is failing on the sync to create these like this.  Was this a bug at some time in the past ?   If so there isnt a cleanup that catches this type of previous bug.

**Comment by Jenefer-Monroe** [comment]
I think the issue here is that we dont have a clean up flow for deleted desktop flows: https://github.com/microsoft/coe-starter-kit/issues/4133

We've not prioritized this since our entire Desktop Flow story is so flimsy due to https://github.com/microsoft/coe-starter-kit/issues/2102 until the new Dataverse connector comes out. 

I would expect that we can make the Desktop Flows story better end to end this fall when the new connector is done. 
Until then the Automation Kit is really the only way to get a reliable Desktop Flow inventory
- [Automation Center of Excellence Webinar](https://info.microsoft.com/ww-thankyou-businesscenterexcellencerpa.html?LCID=EN-US&ocid=eml_pg332504_gdc_comm_ba)
- [Microsoft Power Platform Automation CoE starter kit (preview)](https://docs.microsoft.com/power-platform/guidance/automation-coe/automation-coe-starter-kit)

Sorry about this complexity.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
