### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Admin Command Center

### ISSUE THREAD

**Issue by DHRUVSHAH1803** [microsoft/coe-starter-kit#5111]
### Describe the issue

"Message Center" Tab displays empty data. To Update "Command Center - Client Secret" environment variable it is not recommended as per MSDN documentation and to update "Command Center - Client Azure Secret" environment variable it is still in preview stage("https://learn.microsoft.com/en-us/power-apps/maker/data-platform/environmentvariables#use-azure-key-vault-secrets-preview"). Will you recommend to use "Command Center - Client Azure Secret" to update environment variable in "Production Environment" as the preview feature may subject to change in future as per MSDN documentation.
![coe admin command center](https://user-images.githubusercontent.com/85008479/228142598-0b30fd36-080e-459c-8d99-a579f5eefaee.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

CoE Admin Command Center

**Comment by Jenefer-Monroe** [comment]
Many people have used this so we do think its fine to use for the kit, but I do not understand what your hesitance is based on, perhaps some internal rules to you. So I cannot really comment on if you should do it or not since I dont understand your circumstance.

This feature just displays what you see by browsing to the product message center manually. So if you are hesitant to use preview features you wont miss much of anything by not using this particular feature of the command center. 

I hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
