### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power BI Report Issue after upgrade

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#5186]
### What is your question?

recently we have upgraded tool kit to latest version.

Since then our old December release Power BI Dashboard is not refreshing and throwing error.
![image](https://user-images.githubusercontent.com/29652263/229771469-408e5d81-8849-46de-a252-ce46479c7d77.png)

My  question is with every release of CoE ,do we need to configure new Power BI report or can continue to use the same report ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power BI Report

**Comment by Jenefer-Monroe** [comment]
Hello. It is best practice to upgrade to each month's PBI yes. Sometimes you will be able to get away with not doing it because the table structure used in the report didn't change or is only additive. 
In this case we removed a column no longer needed from the table, and then removed it from the Power Query transform as well. I know the April release will have something similar, we removed some stale and confusing columns from a table and the Power Query transform. 
You can save-as / publish on top of the same report though, so the report consumers will not be impacted by doing this. 
Hope that helps.
