### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Audit Logs: Error from token exchange: Permission denied due to missing connection ACL: Connection 

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#5191]
### Describe the issue

Hi,

I have upgraded Audit log component, Now when I turn on the flow and run. There is an error being throwed. 
Error: Error from token exchange: Permission denied due to missing connection ACL: Connection https://unitedstates-002.azure-apim.net/@unitedstates-002/logicflows/f968edef-c7ef-43ab-f5cd-a8985fcb1450 version -9223372036854775808, connection=unitedstates-002/commondataservice/shared-commondataser-872ccec3-0baf-4ee2-8c29-bfca1c1a89c0

"body": {
        "status": 403,
        "source": "https://unitedstates-002.token.azure-apim.net:443/tokens/unitedstates-002/commondataservice/shared-commondataser-872ccec3-0baf-4ee2-8c29-bfca1c1a89c0/exchange",
        "message": "Error from token exchange: Permission denied due to missing connection ACL: Connection https://unitedstates-002.azure-apim.net/@unitedstates-002/logicflows/f968edef-c7ef-43ab-f5cd-a8985fcb1450 version -9223372036854775808, connection=unitedstates-002/commondataservice/shared-commondataser-872ccec3-0baf-4ee2-8c29-bfca1c1a89c0"
    }
}

Can you please help me to resolve this.

### Expected Behavior

The flow should run successful and even the child flow should run successfully.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Steps To Reproduce

Post upgraded.
Turn on the Admin | Sync Audit Logs flow
Run the flow

**Comment by Jenefer-Monroe** [comment]
Hello. Connections to custom connectors get broken on solution upgrade. It sounds like you knew that and tried to fix though. 

If the normal fix up steps did not resolve, then you likely ended up with a bad connection, perhaps due to the wrong identity provider being selected as in [issue 4808](https://github.com/microsoft/coe-starter-kit/issues/4808)

If that occurs please try the steps outlined in [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

Sorry for the complexity here!

**Comment by ApoorvaKantale** [comment]
ListDefns-TenantIDEnvironmentVariable
ListDefns-TenantIDEnvironmentVariable

{
    "statusCode": 403,
    "headers": {
        "x-ms-failure-cause": "apihub-token-exchange",
        "x-ms-apihub-obo": "false",
        "x-ms-apihub-cached-response": "true",
        "Date": "Tue, 04 Apr 2023 17:45:08 GMT",
        "Content-Length": "523",
        "Content-Type": "application/json"
    },
    "body": {
        "status": 403,
        "source": "https://unitedstates-002.token.azure-apim.net:443/tokens/unitedstates-002/commondataservice/shared-commondataser-872ccec3-0baf-4ee2-8c29-bfca1c1a89c0/exchange",
        "message": "Error from token exchange: Permission denied due to missing connection ACL: Connection https://unitedstates-002.azure-apim.net/@unitedstates-002/logicflows/f968edef-c7ef-43ab-f5cd-a8985fcb1450 version -9223372036854775808, connection=unitedstates-002/commondataservice/shared-commondataser-872ccec3-0baf-4ee2-8c29-bfca1c1a89c0"
    }
}

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid you appear to be on a very old version of the audit log solution or you have unmanaged layers preventing you from seeing our changes. We no longer fetch env vars that way. 

Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by ApoorvaKantale** [comment]
![image](https://user-images.githubusercontent.com/78148795/230008213-9ba9cac2-7f39-4de5-b0a3-5f0e5d031449.png)

**Comment by Jenefer-Monroe** [comment]
Please remove the unmanaged layer manually instead of through our tooling for both this flow and the child (in case it has one too):
![image](https://user-images.githubusercontent.com/89584709/230085534-d6e06479-b3e7-4a6c-96f8-f6f763b7d1ef.png)
![image](https://user-images.githubusercontent.com/89584709/230086229-169d905b-890f-47b0-982a-9c5ee0bc3416.png)

**Comment by Jenefer-Monroe** [comment]
If you are on 3.3 and dont have unmanaged layers, then that call should not be present. It shoudl look like this
![image](https://user-images.githubusercontent.com/89584709/230086554-8a64b40f-97b2-4638-bbad-3c2a3a2f5764.png)

**Comment by ApoorvaKantale** [comment]
I have followed the same steps to remove unmanaged layer. Unmanaged layers are removed.
But still i see old model of flow 

![image](https://user-images.githubusercontent.com/78148795/230139459-93ca0941-ceb5-431d-9485-dbf83952e220.png)
![image](https://user-images.githubusercontent.com/78148795/230139505-6015f60e-65dd-42f9-b452-405365741cc6.png)
![image](https://user-images.githubusercontent.com/78148795/230139571-6ded1f23-0b93-4305-b657-8747421f41b2.png)

**Comment by ApoorvaKantale** [comment]
Please help me to resolve this, I need to fix this issue on priority

**Comment by Jenefer-Monroe** [comment]
I'm afraid I don't know how to assist as if you've really removed the unmanaged layer, and really have 3.3 installed, then you would not see the old bits.
Can you share this screenshot showing it not having unmanaged layers? 
![image](https://user-images.githubusercontent.com/89584709/230085534-d6e06479-b3e7-4a6c-96f8-f6f763b7d1ef.png)
![image](https://user-images.githubusercontent.com/89584709/230086229-169d905b-890f-47b0-982a-9c5ee0bc3416.png)

**Comment by ApoorvaKantale** [comment]
![image](https://user-images.githubusercontent.com/78148795/230144388-5613e672-a6f2-4d41-8412-56629c6e1f10.png)

**Comment by ApoorvaKantale** [comment]
![image](https://user-images.githubusercontent.com/78148795/230144460-e473a21b-9ee0-4e4f-9ee3-9397672a05d4.png)

**Comment by ApoorvaKantale** [comment]
![image](https://user-images.githubusercontent.com/78148795/230144877-ba36ee01-cd51-4a51-a143-1dbc5f29697a.png)

**Comment by Jenefer-Monroe** [comment]
ok I've never seen that, where the core components are a layer on the flow. So I have no idea how you got there. 
It should look like this
![image](https://user-images.githubusercontent.com/89584709/230145788-0ebac5bd-345f-4a03-9f62-b6d28207a8b9.png)

**Comment by Jenefer-Monroe** [comment]
oh i thikn you didnt select the flow. You need to select the flow
![image](https://user-images.githubusercontent.com/89584709/230146052-656cab40-a384-400e-914c-0ae3d672ee4c.png)

**Comment by Jenefer-Monroe** [comment]
ok from this, and the other bugs in your list, your environment is just in a broken and unknown state. I'm afraid we cannot help you get out of this. You should start from scratch in a clean environment.

**Comment by ApoorvaKantale** [comment]
All other flows in core are working fine.

Can help me to fix Audit component

**Comment by Jenefer-Monroe** [comment]
I'm afraid I cannot. From looking at this and through all your bugs you are just in a completely unknown state. You will need someone that can put their hands on it in order to resolve this, or you need to start from scratch. 

If you chose the former, there are partners that specialize specifically in CoE Starter Kit, so you could reach out to them for assistance. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

As a reminder, although the underlying features and components used to build the kit (such as Dataverse, admin APIs, and connectors) are fully supported, the kit itself represents sample implementations of these features. While we do our best to help people use them as is, they are not a supported feature.

**Comment by ApoorvaKantale** [comment]
Please let me know , if we have  any alternative

**Comment by Jenefer-Monroe** [comment]
Your options are to start from scratch in a new environment or find someone that can sit with you (internally or by hiring a partner)

**Comment by ApoorvaKantale** [comment]
Hi,

Can please suggest some other options.

**Comment by ApoorvaKantale** [comment]
I have to fix in this environment itself, We cannot create new environment

**Comment by Jenefer-Monroe** [comment]
You will need to hire someone that can sit with you to fix your situation then. Your environment is not in a state that I can assist in debugging remotely. 

There are partners that specialize specifically in CoE Starter Kit, so you could reach out to them for assistance. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

As a reminder, although the underlying features and components used to build the kit (such as Dataverse, admin APIs, and connectors) are fully supported, the kit itself represents sample implementations of these features. While we do our best to help people use them as is, they are not a supported feature.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
