### ISSUE TITLE
Flow "Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments" was automatically executed and delete Microsoft Teams Dataverse environments without justification or approval

### ISSUE THREAD

**Issue by Facun84** [microsoft/coe-starter-kit#52]
Good night,
 
We updated CoE to the latest version and when doing so, the Flow "Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments" was automatically executed. This resulted in the deletion of 3 Microsoft Teams Dataverse environments (created before the upgrade) without any mail coming in for justification or approval.

**Comment by devkeydet** [comment]
Sorry, this is a bit of a repo in transition, which has confused people.  We hit some snags in being able to move to using this repo, but didn't want to make it private.  If you haven't already, please file the issue here: https://github.com/microsoft/powerapps-tools/issues. We anticipate being active in this repo in early 2021.
