### ISSUE TITLE
[CoE Starter Kit -Helper - CloudFlow Operations flow fails when changing permissions on Power Platform Admin View Screen

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#5212]
### Describe the issue

When I manage permissions for Flows in the Power Platform Admin view screen the flow Helper - CloudFlowOperations fails as it is adding in the Username instead of the id of the user.

![image](https://user-images.githubusercontent.com/117682988/230451237-c8b78622-43cf-4a74-a4f1-62512cd76075.png)

But it does not do that when I do the change flow permissions in the Set Flow Permissions app as you can see the successful records there.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Helper - CloudFlowOperations

### Steps To Reproduce

Go to Power Platform Admin View > Go to Flows > Select Flow > Click the Manage Permissions and add someone to view or edit. Go to the flow Helper - CloudFlowOperations flow and see that it fails and added the username instead of the id.

**Comment by Jenefer-Monroe** [comment]
Thank you for posting, this was known and the fix is targetted for the May release. 
Note that it only repros if you change permission. If you remove the person and then add them with the new permissions it will work. So you can use that as a workaround in the meantime. 
https://github.com/microsoft/coe-starter-kit/issues/5149

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
