### ISSUE TITLE
[CoE Starter Kit - BUG] Inventory in BYODL CoE not accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5217]
### Describe the issue

Hi Team, 

In the spirit of testing, I have setup both BYODL CoE and Legacy CoE in the same tenant. I noticed that we have discrepancies on the data inventory. The storage account export has been setup for over multiple weeks now. 

Legacy CoE Overview Dashboard:
![image](https://user-images.githubusercontent.com/95443860/230617271-f3bfdf81-01b6-4038-b38d-3319fe74ae3b.png)

BYODL CoE Overview Dashboard:
![image](https://user-images.githubusercontent.com/95443860/230617567-7242d38f-4710-4091-8317-98f40b4f28fb.png)

Cloud Flows for Legacy CoE are running normally and Dataflows for BYODL CoE are running normally. They both have been refreshed as of this post. 

Inventory Discrepancies:

Solutions:
Legacy - 2134
BYODL - 2126

Business Process Flows:
Legacy - 2902
BYODL - 2875

AI Models: 
Legacy - 215
BYODL - 182

Flows: 
Legacy - 4314
BYODL - 4346

### Expected Behavior

Both dashboards should have the same information. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023 

### What app or flow are you having the issue with?

Admin View

### Steps To Reproduce

Open Admin View

**Comment by Jenefer-Monroe** [comment]
Hello. You can expect there to be small differences in the tallies between these architectures at any time as the delay is different. 

For sync flow architecture, the inventory will be from whenever the daily flows run. So if an environment was created at 8 AM and and the sync flows run at 8:01 AM, it will be present. 

For the BYODL, it must first be present in the Datalake via Data Export. So if an environment is created at 8 AM, it will be present either in the next data export or the one after that depending on product internal processes. In other words there can be a 2 day delay in seeing new objects in the Datalake. The same is true for object deletes. Their delete will not be represented in the Datalake until the processes recognize it and stop writing them via Data Export.

For these three objects, the process to gather the inventory is exactly the same across the architectures. The only difference is in how the environment update is triggered. For BYODL, its when the Envt is written to by the Dataflow (and hence the envt must be present there)
- Solutions
- Business Process Flows
- AI Models

And flow the flow object, its limited by the when the flow object is written to the Datalake by Data Export. 

Thats not all to say that you might not find bugs, but differences of this size hint to me, an issue with timing not an issue with the system (other than it having time delays :))

In order to be actionable as a result, we would need you to see a specific case where you expect it to be present or missing and its not. 

I hope that makes sense. 
Thank you for using us and giving us feedback!

**Comment by nasilvae** [comment]
> Hello. You can expect there to be small differences in the tallies between these architectures at any time as the delay is different.
> 
> For sync flow architecture, the inventory will be from whenever the daily flows run. So if an environment was created at 8 AM and and the sync flows run at 8:01 AM, it will be present.
> 
> For the BYODL, it must first be present in the Datalake via Data Export. So if an environment is created at 8 AM, it will be present either in the next data export or the one after that depending on product internal processes. In other words there can be a 2 day delay in seeing new objects in the Datalake. The same is true for object deletes. Their delete will not be represented in the Datalake until the processes recognize it and stop writing them via Data Export.
> 
> For these three objects, the process to gather the inventory is exactly the same across the architectures. The only difference is in how the environment update is triggered. For BYODL, its when the Envt is written to by the Dataflow (and hence the envt must be present there)
> 
> * Solutions
> * Business Process Flows
> * AI Models
> 
> And flow the flow object, its limited by the when the flow object is written to the Datalake by Data Export.
> 
> Thats not all to say that you might not find bugs, but differences of this size hint to me, an issue with timing not an issue with the system (other than it having time delays :))
> 
> In order to be actionable as a result, we would need you to see a specific case where you expect it to be present or missing and its not.
> 
> I hope that makes sense. Thank you for using us and giving us feedback!

I understand, I worry because BYODL CoE has been running since the 21st of March and Legacy CoE since yesterday. I was hoping to have the same information in both of them but I can give a few more days.

**Comment by Jenefer-Monroe** [comment]
Are you in a test tenant where objects are not being created/deleted? 
If so, then be sure to run the clean up processes, then if there are still differences, you will need to explore to find a single one for us to investigate.

If not, then you can always expect there to be small deltas.

**Comment by nasilvae** [comment]
> Are you in a test tenant where objects are not being created/deleted? If so, then be sure to run the clean up processes, then if there are still differences, you will need to explore to find a single one for us to investigate.
> 
> If not, then you can always expect there to be small deltas.

Yes, I am in a test tenant is shared with my team but we don't create items that often. For the clean up processes you mean the clean up flows I make sure they are running on both CoE instances?

**Comment by Jenefer-Monroe** [comment]
Correct, these cleanup flows
![image](https://user-images.githubusercontent.com/89584709/230632540-0d5c1b26-3ab5-480b-b155-2cde4186c090.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
