### ISSUE TITLE
[CoE Starter Kit - BUG] "Get Specialty Action Details" not removing system admin which is added by flow itself

### ISSUE THREAD

**Issue by umeshmurumkar** [microsoft/coe-starter-kit#5233]
### Describe the issue

Flow : Admin | Sync Template v3 (Flow Action Details) scope "Get Specialty Action Details" is adding CoE Flow Admin as owner with assign action by calling flow "HELPER - CloudFlowOperations" however we have seen many user complaining CoE Service account which runs starter kit is being added to their flows as co owner. We feel that remove action is not working or something is not working as expected. we are using November release.

### Expected Behavior

The Admin account should be removed from flow.
We also want to understand what is criteria for specialty action details as we unable to find root cause of this issues

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### Steps To Reproduce

We do not see any logs as failed hence we are unable to reproduce the issue.

### Anything else?

Please help us to understand what specialty actions is and in which scenarios it update the flow owner.
Will new release resolve this issue?

**Comment by Jenefer-Monroe** [comment]
Basically there is some information (ex HTTP connections and password checks) which is not exposed unless you are an owner of the flow. So in this flow we add the user running the flow, get the details needed, and then remove them. 
![image](https://user-images.githubusercontent.com/89584709/230923271-a79cf470-e866-4f2f-b4b9-2e0f585908e1.png)

We do see this working for ourselves and others, so in order to debug we would need a specific repro from you. 
Please find a flow where this is occurring, remove the running admin persona, run the flow action details flow for it, and then let me know what you see there.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
