### ISSUE TITLE
[CoE Starter Kit - BUG] Default environment data is missing from the dashboard

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#5250]
### Describe the issue

Default environment Apps, flows are missing from various section of the dashboard BYODL_CoEDashboard_April2023.pbit.

 I am using the dashboard from April version. 

Thanks,
Devendra

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

BYODL_CoEDashboard_April2023.pbit

**Comment by Jenefer-Monroe** [comment]
Can you please go see if your data is available in the Power Platform Admin View app? Filter to default and canvas apps.
![image](https://user-images.githubusercontent.com/89584709/231455361-e2091d1e-21a0-49ae-855a-d500355742a0.png)

**Comment by devvelegandla** [comment]
Thanks @Jenefer.

Yes i can see the Canvas apps from default environment in Admin app.

**Comment by Jenefer-Monroe** [comment]
Can you please let me know
1. Do you see data from other environments in the PBI? 
1. Browse to the Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)

**Comment by devvelegandla** [comment]
Thanks @Jenefer-Monroe 

Updated to No and will wait for next refresh.

**Comment by Jenefer-Monroe** [comment]
You will need to go to the Command Center > CoE Flows > Inventory > and make sure all the flows are on.

**Comment by devvelegandla** [comment]
If we use BYODL, we need to turn on only specific flows and not all inventory flows?

We turned On only flows based on CoE metadata. 

![image](https://user-images.githubusercontent.com/130560248/232366693-f901b322-b02d-4f75-b8d4-d2f25156127a.png)

**Comment by Jenefer-Monroe** [comment]
Yes all inventory flows listed there need to be turned on.

**Comment by devvelegandla** [comment]
@Jenefer-Monroe - Here in this thread it says WIZARD should take care of the flows that needed to run when we use BYODL
https://github.com/microsoft/coe-starter-kit/issues/5163
Could you please let me know if i run the V3 inventory flows then i shouldn't use the BYODL?

**Comment by devvelegandla** [comment]
@Jenefer-Monroe - I have Turned ON all flows except Admin | add makers to Group.

**Comment by devvelegandla** [comment]
> Can you please go see if your data is available in the Power Platform Admin View app? Filter to default and canvas apps. ![image](https://user-images.githubusercontent.com/89584709/231455361-e2091d1e-21a0-49ae-855a-d500355742a0.png)

As we are reviewing this again, I don't see canvas Apps in Admin app.

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry I'm a little lost. Here it sounds like you turned BYODL off
![image](https://user-images.githubusercontent.com/89584709/233989324-9eea5bfb-5519-43b6-b24b-4e64ebf8cc65.png)

Can you please review this and let me know which path you are trying to take?

**Comment by devvelegandla** [comment]
@Jenefer-Monroe - Apologies for confusion. We are using the BYODL and I updated the value to YES.
![image](https://user-images.githubusercontent.com/130560248/234431591-df87f787-35ec-47f5-b212-2098c71df27a.png)

We are seeing the data for other environments. The issues are with default environment. 

I will install the hotfix and update you.

**Comment by devvelegandla** [comment]
@Jenefer-Monroe 
- We have deployed the hotfix but no luck on Default environment.
We can only see custom pages and Model driven apps but no canvas Apps. 

Dashboard still got inconsistent details.

**Comment by manuelap-msft** [comment]
Hello,

thank you for your patience as we triage this!

If I do understand correctly, you are using the Data Export (BYODL) feature and in the Power BI dashboard you're not seeing all data. You are only seeing model and custom pages, but not canvas apps. 

I have a couple of questions then, if my understanding is correct

1. Can you navigate to the storage browser, and to the powerplatform>powerapps>Applications folder, and look at the two Default- .json files. Do you see a model.json and canvas.json for the Default environment? If you open them, do they show data? 
    ![image](https://user-images.githubusercontent.com/55705669/234555282-6dcdf928-abe7-4c2b-bcb2-16d142797f43.png)
1. If you open the canvas.json file contain some elements with ClassicCanvasApp as subType
    ![image](https://user-images.githubusercontent.com/55705669/234575686-a90a5548-af71-485d-b0c8-35e0ae2deb92.png)
1. If that's all correct, let's see if they're disappearing in the Dataflow somewhere. Navigate to app.powerbi.com > Edit the Dataflow > Select the Apps table
   ![image](https://user-images.githubusercontent.com/55705669/234556273-f8b35636-993e-40ed-b8ea-d33b9ca40e52.png)
1. Select the **Merge with environments** step in the Applied steps area
1. Select the EnvironmentNameFromTable column > deselect all > search for default and only select the default
   ![image](https://user-images.githubusercontent.com/55705669/234556554-8b5a6e5e-a65a-4eff-aa78-f8df6ee15e25.png)
1. We're adding a step to only filter to the default environment, we'll remove that again later once we know the data is correct. Confirm that you do want to insert the step here.
7. The Filtered rows step should show you two rows - one is the canvas file and one the model file
   ![image](https://user-images.githubusercontent.com/55705669/234556722-b3fcb9ef-de78-41a2-bc9d-2a0766824ef7.png)
8. Now click through all of the remaining steps - is there one specific point at which the apps are disappearing? Or are they never showing up in the first place?
   ![image](https://user-images.githubusercontent.com/55705669/234556907-0f6ed212-9181-411e-9702-a8bd53fef615.png)
1. Cancel / don't publish the changes as we've just added a filter to only do Default- so that would mess up your dashboard! 

Let me know if those instructions make sense or if you need some more step by step instructions to follow the above steps!

Thank you for helping us investigate this!
Manuela

**Comment by devvelegandla** [comment]
Thanks @manuelap-msft 

Until step 4 all good. I was able to find the json files and both of them got the data. 

On step 5, I wasn't able to find the default environment.

![image](https://user-images.githubusercontent.com/130560248/234586109-37bc2a91-3cf7-4f1d-bba6-6211876802ed.png)

I also tried to look for Default environment in the list of environments and wasn't able to find either.

![image](https://user-images.githubusercontent.com/130560248/234586835-fe446e0f-a25a-4749-903a-2312b9406b0c.png)

**Comment by manuelap-msft** [comment]
Hello,

great news that your source data is correct - that makes it easier for us! We've seen this issue before, and I thought we had fixed that. Let's check a few more things but I'm hopeful we can get to the bottom of this quickly.

Here's what the dataflow does:
- The environments.json file always contains a list of your current environments. The dataflow prepares a list of all environments in your tenant
- The canvas/model.json files contain a list of all your apps across all your environments - however, if an environment got deleted the file would still be in your storage account (the Data Export never deletes files, it only updates/creates them). The Dataflow therefore merges all the apps with the existing environments - this filters out apps where the environment no longer exists. 
- I think there's just an issue merging the Default- environment in so let's check for that. 

**Confirm environments**
Can you select the Environments table in the Queries view and check if one of the applied steps is called "lowercased environmentId"? If you look through the list of environments, are you able to find the default environment there and does the environmentId start with default- (instead of Default-)
![image](https://user-images.githubusercontent.com/55705669/234594413-cf9def6b-85f5-4b7f-a99b-72fc15761885.png)

**Confirm app files**
Can you select the Apps table in the Queries view and check the step before merge environments, do you see the default- environment in the EnvironmentNameFromTable? Does it appear in lowercase?
![image](https://user-images.githubusercontent.com/55705669/234595558-ce11542a-882f-4420-8a14-8fa4d9394c65.png)

Just from looking at your screenshots, it does look like you're missing the step to lowercase the environment which is something we fixed for the April release (and what caused this issue earlier) so you may be using an older / outdated version of our Dataflow. If that's true, you'll have to set up the Dataflow again from our latest version - download via [https://aka.ms/coestarterkitdownload](https://aka.ms/coestarterkitdownload). There's no upgrade path for Power BI Dataflows (that we know of), so you'll have to re-import and re-configure it following the steps here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#import-power-bi-dataflows

If you'd prefer to not do that and keep the current dataflow, I can also talk you through the changes you manually need to make.

**Comment by devvelegandla** [comment]
Thanks @manuelap-msft 

We have imported the updated Data flow and it seems an issue with the export of data to Azure datalake. We have raised a ticket with support team,

**Comment by manuelap-msft** [comment]
Thanks for confirming! I missed the line earlier in your response where you noted that the file was very small in size. Hopefully this will get resolved soon so you get all your data through the Data Export. Please let us know if you have any further questions, or run into further issues once the Data Export issue is resolved!
