### ISSUE TITLE
[CoE Starter Kit - QUESTION] Help with customizing email notifications in the CoE Admin Command Center

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5278]
### What is your question?

I upgraded from the Dec 2022 version of the COE kit to the April 2023 version.

I was hoping to be able to use the "CoE Admin Command Center" to customize the email notifications for these 2 flows:
Admin | Inactivity notifications v2 (Start Approval for Apps)
Admin | Inactivity notifications v2 (Start Approval for Flows)

But I only see 19 emails that I can customize. All of which are from the "Core" solution.

How do I fix this so that I can use the "CoE Admin Command Center" to modify the email notifications for these 2 flows?
![COE-customize-emails](https://user-images.githubusercontent.com/128085471/231581760-e4248c03-e5e6-4cb0-8c0f-abf5a38ec13e.PNG)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 2023

**Comment by Jenefer-Monroe** [comment]
Hello, if you use the setup wizard to upgrade in the future this will resolve for you. Basically you need to sync the new emails. This can be done manually by runnign the following flow, note that if you cannot turn it on or run it, its likely because its child flows are not turned on. Again the setup wizard woudl do this for you. 

Run: **_Admin | Sync Template v3 (Call Updates)_**

It requires these flows be turned on:
- Admin | Sync Template v3 CoE Solution Metadata
- Admin | Sync Template v3 (Connectors)
- Admin | Sync Template v3 Configure Emails

It will kick off this flow with the correct parameters, when it completes you will see those mails: **_Admin | Sync Template v3 Configure Emails_**

Hope this helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
