### ISSUE TITLE
Admin | Sync Template v3 Error  | Action 'Get_Maker' failed

### ISSUE THREAD

**Issue by achaganti** [microsoft/coe-starter-kit#5303]
Admin | Sync Template V3 Flow failing . Check Maker Flow is already ON and all child flows too.. Current version of COE is 4.3 
![image](https://user-images.githubusercontent.com/34516164/232334227-c6dd476a-01e4-41ed-b9fb-b44008014641.png)

**Comment by Jenefer-Monroe** [comment]
Please make sure that you dont have any unmanaged layers on the child flow: [Removing other customizations](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#removing-other-customizations)
And that you have the Run only users set properly: [Set flow run-only users properties](https://learn.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties)

**Comment by achaganti** [comment]
> e Run only users set properly: [Set flow run-only users properties](https://learn.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties)

I checked that the child flow doesn't have any unmanaged layers and the run only users are set properly.

**Comment by manuelap-msft** [comment]
Can you open the run history of Helper - Maker Check flow and check
- are all runs failing?
- if only some runs are failing, can you open a failed run and share the step at which it's failing?

**Comment by achaganti** [comment]
I checked the history already and do not see any failures for Helper-Maker at all.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by manuelap-msft** [comment]
The call should look like this for SYSTEM environments with both MakerID and Display Name set to SYSTEM. 
![image](https://user-images.githubusercontent.com/55705669/232463676-7da29cf1-d361-47a5-a38c-8381eecd537a.png)

I think it's failing because display name is a required property of the child flow, and it looks like that's not provided. We have to figure out why that's not coming through.

1. Can you go to the Get Environments scope and open the Get Environments action
   ![image](https://user-images.githubusercontent.com/55705669/232466797-8dc3a85b-e44f-4fad-a440-33fdf3bc3cdf.png)
2. Select Click to download and copy the output to your preferred JSON viewer
3. Find the environment that's failing there
4. What does the createdBy attribute look like? 
5. In my case, even for a SYSTEM created environment it shows ID/displayName as SYSTEM
   ![image](https://user-images.githubusercontent.com/55705669/232466985-97536cef-0fad-4acd-bbc8-40471c4372a1.png)
6. If it doesn't show SYSTEM for ID and displayName for you, can you let us know what type of environment it is and what region it is in so we can try and repo this on our end?

**Comment by achaganti** [comment]
It seems to have an ID and eastus region. Also the environment failing seems to be the one where the CoE was installed..

**Comment by manuelap-msft** [comment]
Hello,

The CoE Starter Kit is an unsupported set of templates; whilst we do try our best to triage issues raised with us in a timely manner, we aren't able to provide an SLA on when we'll be able to look at them. We don't have a dedicated support team triaging the issues. Thanks for your patience as we're still looking into this.

Manuela

**Comment by achaganti** [comment]
Totally understand. Will wait for your response.

**Comment by Jenefer-Monroe** [comment]
Yes it looks like our short circuit checks for SYSTEM display name instead of id
![image](https://user-images.githubusercontent.com/89584709/233848175-c7303a98-28f9-4c9c-bbcb-2da523293c19.png)
![image](https://user-images.githubusercontent.com/89584709/233848200-310e7707-9ac0-46e0-81a0-1eb23e13859b.png)

**Comment by Jenefer-Monroe** [comment]
fix is here
![image](https://user-images.githubusercontent.com/89584709/233848369-fd6e2e13-a6b5-489c-9312-b7f61f71c951.png)

and here
![image](https://user-images.githubusercontent.com/89584709/233848403-b8610da2-2ddd-4152-8326-5d2420dd4797.png)
