### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Component Issue 

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#5314]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

HI,

we are facing an issue in Audit component and would like to reinstall only audit component , can you please help me on this  

### Expected Behavior

Post upgrade also , Flow is still show the old connectors in the flow

The flow is not upgraded and didn't change the connectors

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Post upgrade also , Flow is still show the old connectors in the flow

The flow is not upgraded and didn't change the connectors

### Anything else?

Post upgrade also , Flow is still show the old connectors in the flow

The flow is not upgraded and didn't change the connectors

**Comment by manuelap-msft** [comment]
This typically happens if the flow has unmanaged layers. If you open the CoE Admin Command Center app and navigate to CoE Flows, you can filter by area / search for the flow and it will show you an icon here if the flow has unmanaged layers - you can then click on "Remove solution layers" to remove the layers.
![image](https://user-images.githubusercontent.com/55705669/232719867-ea5ae400-26c8-45bd-8390-ffc737a7ff3b.png)

**Comment by ApoorvaKantale** [comment]
I have removed the unmanaged layer and also upgrade the audit log component. the flows is still showing the old connectors 
![image](https://user-images.githubusercontent.com/78148795/232727788-465899ab-4c3e-409e-9289-eeb2fe7e0453.png)

**Comment by manuelap-msft** [comment]
I'm not sure what you mean by showing old connectors? The screenshot is what the current version of the flow looks like.

**Comment by ApoorvaKantale** [comment]
Actually when we upgrade the Audit log to version 3.3 , the Admin | Sync Audit Logs should look like 

![image](https://user-images.githubusercontent.com/78148795/232742878-0c70498b-f1e8-449d-bd76-c2add1e89fe8.png)

But when I have upgrade the version to 3.3 my flow looks like 

![image](https://user-images.githubusercontent.com/78148795/232743374-75279bf4-e73c-49a4-ba07-70b429b8b681.png)

**Comment by manuelap-msft** [comment]
You're right, I missed that. 

Please share with me what you see when you open the solution layers of this flow
![image](https://user-images.githubusercontent.com/55705669/232744680-5c4fef42-228c-4f75-8de9-a34c4e2278d1.png)

Please share with me what you see when you select the Solutions tab in the environment - you can filter this to only show solutions that start with Center of Excellence but please don't clip it and make sure the screenshot shows us all the Center of Excellence solutions in the environment including the version number
![image](https://user-images.githubusercontent.com/55705669/232744828-020d0c96-aa7a-45cc-8a61-c71e75a2bd63.png)

**Comment by ApoorvaKantale** [comment]
![image](https://user-images.githubusercontent.com/78148795/232747782-1eb090e1-c63f-4c25-8617-9b2badafa3f9.png)


![image](https://user-images.githubusercontent.com/78148795/232748293-166f1c08-25f7-4e29-9e04-fef8454d7665.png)

**Comment by manuelap-msft** [comment]
Hello,

it looks like you raised this with us in the past, and we informed you we were unable to assist any further due to complexity of your issues. Here's the thread https://github.com/microsoft/coe-starter-kit/issues/5191

You will need to hire someone that can sit with you to fix your situation then. Your environment is not in a state that we can assist in debugging remotely.

There are partners that specialize specifically in CoE Starter Kit, so you could reach out to them for assistance. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

As a reminder, although the underlying features and components used to build the kit (such as Dataverse, admin APIs, and connectors) are fully supported, the kit itself represents sample implementations of these features. While we do our best to help people use them as is, the kit itself is not a supported feature.

**Comment by ApoorvaKantale** [comment]
But my question is different,  I will not be able to take help from Appsource.

I just need a one help, is it possible to delete the existing audit component and install new Audit component
