### ISSUE TITLE
[CoE Starter Kit - QUESTION] Error on importing nurturing components

### ISSUE THREAD

**Issue by EmpbPowerAdmin** [microsoft/coe-starter-kit#5361]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Getting following on import - 

![image](https://user-images.githubusercontent.com/129513320/233959904-9fd14ef3-cda1-4946-874d-4d236e1429c8.png)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

February 2022

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
That is a warning message. I'm not familiar with its error but you can typically ignore these warnings. 
Before doing so though, can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by manuelap-msft** [comment]
Could you also let us know what region your CoE environment is in (e.g. Canada, United States, Europe) so we can see if this is a product change impacting some regions? Thank you!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
