### ISSUE TITLE
Dataverse Legacy connector still utilized on CoE workflows

### ISSUE THREAD

**Issue by sdpriebe2568** [microsoft/coe-starter-kit#5390]
Since this connector is due to be completely removed from the connector listing within Power Platform, we just upgraded to the latest CoE build and the workflows are still utilizing this "old" connector.
Are there any plans to update these workflows to the latest Dataverse connector?

**Comment by manuelap-msft** [comment]
Yes, we are tracking this under https://github.com/microsoft/coe-starter-kit/issues/2607

The inventory of certain Power Platform resources is stored in Dataverse tables of the environments they're created from - desktop flows are stored in the Processes table, Chatbots are stored in the Bots table etc etc etc. We use the Dataverse (legacy) connector to loop through all environments in your tenant to get the inventory for those resources. 

The modern/latest Dataverse connector has a few limitations - primarily that you can't connect to environments other than the current environment. 
https://learn.microsoft.com/en-us/power-platform/important-changes-coming#microsoft-dataverse-legacy-connector-for-power-automate-flows-will-be-deprecated-and-replaced-with-another-connector

Due to this limitation we are not yet able to shift to the modern/latest connector yet, but we will once that limitation is resolved in the connector.

Hope this helps,
Manuela

**Comment by sdpriebe2568** [comment]
Thank you for such a quick and thorough response and Thank you for the link to the Issue #2607...I will follow that link for resolution.

On 4/26/2023 12:42:51 PM, Manuela Pichler ***@***.***> wrote:

Yes, we are tracking this under #2607<https://github.com/microsoft/coe-starter-kit/issues/2607>

The inventory of certain Power Platform resources is stored in Dataverse tables of the environments they're created from - desktop flows are stored in the Processes table, Chatbots are stored in the Bots table etc etc etc. We use the Dataverse (legacy) connector to loop through all environments in your tenant to get the inventory for those resources.

The modern/latest Dataverse connector has a few limitations - primarily that you can't connect to environments other than the current environment.
https://learn.microsoft.com/en-us/power-platform/important-changes-coming#microsoft-dataverse-legacy-connector-for-power-automate-flows-will-be-deprecated-and-replaced-with-another-connector

Due to this limitation we are not yet able to shift to the modern/latest connector yet, but we will once that limitation is resolved in the connector.

Hope this helps,
Manuela

**Comment by manuelap-msft** [comment]
From conversations with the Power Automate team, we believe that the way we need to connect environments (using a dynamic variable to specify which environment to connect to vs a static value) will be available at the specified GA time, currently August 2023. Here's the release wave feature to follow for that:
https://learn.microsoft.com/en-us/power-platform/release-plan/2023wave1/power-automate/connect-other-environments-dataverse-connector

It is our top priority to remove dependency on the legacy connector, once all features we need are available in the latest/modern Dataverse connector.

**Comment by manuelap-msft** [comment]
I'll close this question now, but please do let us know if you have further questions related to the CoE kit!
