### ISSUE TITLE
[CoE Starter Kit - Feature]:Add edit history DLP

### ISSUE THREAD

**Issue by StefenRUCKTOOA** [microsoft/coe-starter-kit#5395]
### Is your feature request related to a problem? Please describe.

We cannot find the historic of all edit to any DLP.

### Describe the solution you'd like

Update the audit log child flow to include DLP Logs that are available in the compliance center (pureview)

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/131985461/234895794-ca4fef15-0edc-462f-9181-d1f6459f13a6.png)

### Describe alternatives you've considered

We tried to implement this part as extension of the starter kit, but we would like it to be included in the original version which can benifits also other customers

**Comment by Jenefer-Monroe** [comment]
Hello. 
Thank you so much for sharing your work! 
The audit log connector was a stop gap we had in place awaiting the new BYODL feature. Because of all the problems with the connector (ex missing rows for large sets or after upgrade) we do not plan to invest further in it now that the BYODL feature is available, other than fixing up bugs related to capturing app launches. 
Hope that makes sense. And thank you again!

**Comment by StefenRUCKTOOA** [comment]
ok thank you it's clear.
we'll look to implement the BYODL to get this functionnality.

**Comment by Jenefer-Monroe** [comment]
This functionality doesnt exist in the BYODL version. Only launches are recorded.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
