### ISSUE TITLE
[CoE Starter Kit - ISSUE] Admin | Sync Template v3 flow is failing continuously 

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#5396]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,

Admin | Sync Template v3 flow is failing continuously , 

ERROR:  Action 'Get_Environment' failed . Entity 'admin_environment' With Id = 000xxxxxxxxxxxxxxxxxx Does Not Exist.

But when we check the environment in the power platform admin center the environment is active and it is TEAMS environment 

Please help us to fix this issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please note that failures like this are caught/expected failures. 
We use these calls to see if the object is new to the inventory, and if it is, this call to “get it” will fail. This failure is caught and the “isnew” variable is set to true. 
![image](https://user-images.githubusercontent.com/89584709/225679681-01467de5-1a1c-4c93-bf57-71296f5ea83b.png)
In order to debug you need to find the terminating failure in the flow. Here for example the call to “forced failure” failed, and was not caught, so the flow terminated here. That is the spot you need to find in your failure in order to debug. 
![image](https://user-images.githubusercontent.com/89584709/225681214-a5549790-32e9-482e-b427-0c346aa50684.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
