### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL Apps - missing Apps

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#5400]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
We upgraded to April Release 10 days ago. The Environment and Flow count looks correct. But the App count is only about 5% of our total apps. All the dataflows are refreshing successfully overnight. I have about 30 minute gap between each of them.  
We have a very large tenant. 
We have troubleshooted this our Microsoft Account Team - they said configuration looks OK 

In the March BYODL release we had the correct number of Apps and environments but low Flow count.

Will the May release address this issue ?

### Expected Behavior

Correct number of Apps

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

core components 4.4.1

### What app or flow are you having the issue with?

'CoE BYODL Apps' dataflow 

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
Hello,

we have had another three customers report that they are not getting canvas apps from the Default environment via the Data Export feature. They found that the the canvas.json only contained custom pages but not canvas apps for the default environment. So the issue was with the file provided by the Data Export itself. Could you check if your tenant is impacted by the same?

1. Can you navigate to the storage browser, and to the powerplatform>powerapps>Applications folder, and look at the two Default- .json files. Do they contain all the data you're expecting? Are all apps you are expecting to see listed there? That's the first step in ensuring the source data is correct.
    ![image](https://user-images.githubusercontent.com/55705669/234555282-6dcdf928-abe7-4c2b-bcb2-16d142797f43.png)
2. The other customers with this issue noticed that the file size of the Default-{guid}canvas.json file was very small, and when they opened it could not find any data with subType: ClassicCanvasApps - that's what others have observed.

If you also notice that the Data Export file itself is wrong, can you please raise a support ticket through your regular support channels: https://learn.microsoft.com/en-us/power-platform/admin/get-help-support

The Data Export feature is a product feature and is fully supported by the product team, and the feature has nothing to do with the CoE kit itself so unfortunately we can't help further here. We (the CoE kit) are just consumers of the data provided through this feature, similar to how we're consumers of connectors etc.

We'll follow up internally with the team that owns the Data Export feature as well, but a support ticket will help them track this better.

Thank you,
Manuela

**Comment by jimpreston29** [comment]
Hi
We do not see the Default environment json
![image](https://user-images.githubusercontent.com/78494876/235706555-b8b4564e-3763-499e-9fcd-6d59adf97533.png)
I have opened a ticket with the team

Thanks
Jim

**Comment by Jenefer-Monroe** [comment]
Hello,

We checked internally with the Engineering team that owns the Data Export feature and they confirmed this issue has been fixed and the fix is just rolling out to all customers, according to them you should see the full Default environment file coming through either later today or tomorrow. Fingers crossed!

Thank you

**Comment by jimpreston29** [comment]
Hi - YES - we have the Default Apps back. Thanks !

**Comment by manuelap-msft** [comment]
Wonderful news! I'll close this issue for now, but please do let us know if you have further issues with the BYODL/Data Export integration and we'll look into it.

Thank you
Manuela
