### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is this how I should create a COE testing environment?

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5410]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

A few months ago, I created a new Production environment and installed the COE kit (Dec 2022 release).
A few weeks ago, I upgraded to the April 2023 release of the COE kit.

I now want to extend and customize the CoE Starter Kit components, so I am thinking of creating a separate "COE testing environment" and then copying the original COE environment to this new "COE testing environment".

Will this work?

Note:
I will pretty much only be making customizations to the "inactivity processes" flows in this "COE testing environment", and once I get it right, I will apply the necessary changes in my "COE Production environment".

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
That sounds like a fine approach. I've not done a copy myself but it seems reasonable. 
Be sure to set the **_ProductionEnvironment_** environment variable to no so that you dont send inactivity mails to your tenant from your dev/test envt
![image](https://user-images.githubusercontent.com/89584709/235508813-126d79e5-9123-47ed-af0a-46ed72c63fe8.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
