### ISSUE TITLE
[CoE Starter Kit - BUG]Form of Customized Email Table no longer works in the Admin View App

### ISSUE THREAD

**Issue by pp-panda** [microsoft/coe-starter-kit#5428]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since we installed the **4.3 release**, you can no longer open the form of a table in the admin view. We have integrated the **Customized Email table in the admin view** but now you can't add a new record anymore. See error:
![image](https://user-images.githubusercontent.com/122286024/236127783-13b5a009-fb0c-40ae-a19b-e128ee4b44f3.png)
You can open the form via Dataverse. See image.
I removed the table from the app along with the data via the classic view, then added it again but the error remained. All other CoE tables are not affected.
The Ribbinbar has also changed. See picture.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![Screenshot 2023-05-04 083613](https://user-images.githubusercontent.com/122286024/236128967-fb4def1d-90c9-4c3c-9d8f-4ba3a9b8dacb.png)
![Screenshot 2023-05-04 083740](https://user-images.githubusercontent.com/122286024/236128971-5b5b19b1-4442-416e-af36-4c52d81f4869.png)
![Screenshot 2023-05-04 084121](https://user-images.githubusercontent.com/122286024/236129104-67378b58-4988-4be7-84f3-7a050d372e43.png)

**Comment by manuelap-msft** [comment]
Hello,

none of the screenshots you are sharing are of the Power Platform Admin View in the CoE kit, it looks like you've made your own customizations and extensions here? 

With our UX refresh of the [Admin - Command Center](https://github.com/microsoft/coe-starter-kit/issues/4483) in February, we have moved configuring emails to the CoE Admin Command Center app which works of the regular table view and a custom page.

**View:**
![image](https://user-images.githubusercontent.com/55705669/236153043-bd231038-3c59-4a82-812f-de311dd37410.png)

**Modify email in custom page:**
![image](https://user-images.githubusercontent.com/55705669/236153142-e4a6f448-0341-4511-aa1f-a54637ffcbe9.png)

Because the error is happening with your customization/extension, and not our part of the CoE kit I'm afraid I can't assist any further here. I've checked the view/form of the Customized Email table outside of the CoE Admin Command Center and there was no issue opening it.

**Comment by manuelap-msft** [comment]
We have updated the command bar to remove the + New button as we don't have a documented approach on how to add new emails for your custom extension, but if you were adding new emails to this table for your own custom flows let us know and we can evaluate adding the +New button back in. I've checked and it works directly from the form, the button is just hidden in the view.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
