### ISSUE TITLE
[ALM Accelerator - QUESTION] Activate Flows failing with Environment Variable not set

### ISSUE THREAD

**Issue by sgshameem** [microsoft/coe-starter-kit#5435]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi, 

We have plan to implement ALM setup for our project and so followed the hands on lap document to test with trail CRM instances. However we are encountering a issue at the deploy solution stage with Devops job pipeline failing with below error. 

PowerShell exited with code '1'

The job is failing at the Activate Flows step. Initially when I encountered this failure, I noticed that there is a issue with activating the flows but with just warnings like below

**##[warning]Flow could not be activated. Continuing with flow activation until no more flows can be activated. If this is a result of a child flow not being activated before it's parent consider ordering your flows to avoid this message.**

However in the end the below warning with error is shown.

**##[warning]Errors occurred while activating flows. Please review the log for specific errors and verify your deployment configuration settings.
ScriptHalted
##[error]PowerShell exited with code '1'.
Finishing: Activate Flows**

So I went to CONFIGURE DEPLOYMENT SETTINGS (ALM Accelerator Sample solution) and updated the connection reference with office 365 outlook with the correct account. (admin@***.onmicrosoft.com)

After this I ran Commit and Deploy steps again, but this time it again failed with same error but this time after showing as below 

**FaultException`1 - SetState : Setting Activity State in CRM... workflow |=> Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'cat_DecimalEnvironmentVariable'."}}".**

![Trail1 Fail](https://user-images.githubusercontent.com/47221026/236265097-6f0987b8-166b-4694-bbb3-04a1b9070c80.PNG)
![Setup1](https://user-images.githubusercontent.com/47221026/236265156-e0fefb7f-3ed0-40eb-94bf-75195a0dfff4.PNG)
![Setup2](https://user-images.githubusercontent.com/47221026/236265235-adab0594-a0bc-4f57-b73b-90859e18d0e2.PNG)
![Trail2 Fail](https://user-images.githubusercontent.com/47221026/236265261-b3c29508-7c20-4290-83e7-7ca557544520.PNG)
![ALMSampleVer](https://user-images.githubusercontent.com/47221026/236265725-e77a2b6e-0310-44ee-8a44-24aeec16402c.PNG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.20230503.3

### What app or flow are you having the issue with?

ALM Accelerator for Power Platform

### What method are you using to get inventory and telemetry?

None

**Comment by mikefactorial** [comment]
@sgshameem thanks for reaching out. We are looking into other potential issues surrounding empty environment variables after import that could be a change in the platform or an ALM Accelerator regression. In the meantime does setting the values for the environment variables on the environment variables screen in the deployment settings should stop this error from occurring? i.e. 
![image](https://user-images.githubusercontent.com/42348035/236331648-6947d2f3-0dd4-4563-b5c5-a9054b988979.png)

**Comment by sgshameem** [comment]
Hi Mike,

Sorry for the late reply, but the issue seems to resolved by putting some values in the environment variables. However I did not notice one or two things but I cant remember on top my head right now. I will update once I get chance to go through it to recollect it. In the mean time I am curious to know if there has been any updates to resolve this potential issues? Thanks.

**Comment by RajeevPentyala** [comment]
@sgshameem I would request you to test the scenario with the upcoming (i.e., July month) 'ALM Accelerator' build. 
I have conducted the following test and was able to successfully 'Activate' the flow by referencing an Environment Variable with a blank value.

- Created an Environment Variable(EV) and provided a 'Default Value'.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/477ccbdb-bdc7-4524-a79d-8752dddd81e5)

- Created a flow referring the EV.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/9f6cc9b1-cabd-4603-8a0e-9c1aeea117c2)

- In the 'ALM Accelerator' deployment settings, leave the EV as blank.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/f4255dd5-3603-4e16-94ba-b039e640b173)

- Complete the 'Commit' and 'Deploy' steps. 
- In my case, flow got activated and when I ran the flow on Target environment, if fetched the EV default value which is the expected behavior.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/dbd20ccc-76cb-404b-a136-228ad8ab53fb)

Please feel free to reach out if you have any further queries.
