### ISSUE TITLE
[CoE Starter Kit - BUG] Issue renaming default environment

### ISSUE THREAD

**Issue by krhoadesnh** [microsoft/coe-starter-kit#5442]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We renamed our default environment a few months ago.  Since then, we have had ongoing issues with any of the CoE reports & apps showing incorrect number of flows.  We briefly had the correct number showing after running a full inventory last week but it is now incorrect again.  And I just ran another full inventory but it is still showing only some (numbers below). 
 
 I used the List Flows as Admin connector to query the default environment by GUID it returns 613 flows, which is correct.  The Flows table in the Coe environment, PBI Reports, PP Admin View, etc, show 258 flows.  The missing flows seem to be the ones that were created before the environment rename.

### Expected Behavior

We would expect to see all flows created before and after the environment rename showing in the Flows table and resulting reports.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Unknown, possibly Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run the Admin | Sync Template v3 without the Full Inventory on.

**Comment by Jenefer-Monroe** [comment]
Hello, renaming the default object does have an impact on some of the flows temporarily while the new orgid settles in to all the flows, but its never been something I've seen take months to resolve. 

If you just recently lost a bunch of flows it may have been due to https://github.com/microsoft/coe-starter-kit/issues/5331 for which we released a hotfix. Please upgrade your Core and let me know. You will need to do a full inventory to get them back (which we are making better for May)
[CenterofExcellenceCoreComponents_4_4_2_managed.zip](https://github.com/microsoft/coe-starter-kit/files/11410600/CenterofExcellenceCoreComponents_4_4_2_managed.zip)

**Comment by krhoadesnh** [comment]
@Jenefer-Monroe -  Thanks!  

How many other fixes are included in the 4.4.2 release you linked above?  Is this the only one?

**Comment by Jenefer-Monroe** [comment]
Yes we applied only the one fix between April's original release and the hotfix.

**Comment by krhoadesnh** [comment]
We applied the fix and re-ran the full inventory, then the partial.  The numbers seems to be staying put so far, thanks for the help!

**Comment by Jenefer-Monroe** [comment]
You are quite welcome, closing out as no further action for starter kit team
