### ISSUE TITLE
[CoE Starter Kit - QUESTION] CleanUp Old Objects

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5456]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I rejected app from deletion in Cleanup Old Objects. But after a week the status is showing "No Response". I did rejected two times but the status is still showing "No Response".

![image](https://user-images.githubusercontent.com/126264610/236818527-481f3c6e-480f-4d5e-add5-4df8066996dc.png)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 19th 2023

### What method are you using to get inventory and telemetry?

None

AB#821

**Comment by Jenefer-Monroe** [comment]
First, please make sure all the flows in the solution area are turned on and running with out unmanaged solution layers. 
![image](https://user-images.githubusercontent.com/89584709/236583421-faee052a-2bb8-4a68-9f34-9ba77f36d56a.png)

**Comment by lingutla123** [comment]
All Flows are turned on and running with out unmanaged solution layers.

![image](https://user-images.githubusercontent.com/126264610/236879503-686f3c36-5b4e-46fd-846b-7c1fb4091de6.png)

**Comment by lingutla123** [comment]
I rejected from the app.

![image](https://user-images.githubusercontent.com/126264610/236886624-8053b1a9-dd59-459e-bfa8-a51835d4b40c.png)

**Comment by Jenefer-Monroe** [comment]
I think we might not be cleaning up old requests and if you rejected an old one, then it would get cleaned. 
Now that it reappears, if you reject it, does it come back again with the next run of **_Admin | Inactivity notifications v2 (Start Approval for Apps)_**?

**Comment by lingutla123** [comment]
We rejected every time when ever we received email from COE.  Please see the below warning after importing April release.
![Capture6](https://github.com/microsoft/coe-starter-kit/assets/126264610/a8ed98d7-6121-4d27-b341-18adcb6a8632)

**Comment by Jenefer-Monroe** [comment]
You can ignore those warnings, just use the setup wizard to configure and they will resolve.

**Comment by Jenefer-Monroe** [comment]
Sorry are you saying to reject through the emails now? Above you said you did it through the app. Both? 
I dont repro so you'll have to walk through the flows and debug. Do you need help doing that?

**Comment by lingutla123** [comment]
No. We always reject through the App. Will debug the flows if i need any help will let you know. Thanks for asking.
You and Manuela are doing amazing job.

**Comment by lingutla123** [comment]
Hi,

My issue is same as #3376

**Comment by Jenefer-Monroe** [comment]
oh thats great. So are you resolved then?

**Comment by lingutla123** [comment]
No. I didn't resolve. Flows are working fine. Do i need to look any particular table?

**Comment by Jenefer-Monroe** [comment]
oh I misunderstood. What do you mean that its the same issue then? That issue was that they did not have the flows setup properly.

**Comment by lingutla123** [comment]
My Manager receiving email every week from  CleanUp Old objects even though he rejected Apps  through the Cleanup Old Objects APP. After rejected App few hours later the status is showing No response.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/aa745c9d-4063-4491-9cd1-b7451e3dff02)

**Comment by Jenefer-Monroe** [comment]
Are you sure he rejected through the App and not through the email? Because if he rejected through the email, then another flow which runs on a schedule would migrate his response from the products record of his response to our table which is where we read for this view.

**Comment by lingutla123** [comment]
Yes. He rejected through the App.

**Comment by Jenefer-Monroe** [comment]
Can you repro this yourself?

**Comment by lingutla123** [comment]
Yes. I did my self too. Last week i rejected all Apps through the Cleanup Old Objects APP. My Manager received email yesterday with same apps.

**Comment by lingutla123** [comment]
I followed your steps. Now it is showing Rejected for Delete.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/44f4fda7-87c9-45ca-9c14-8bc7fa24228b)

**Comment by Jenefer-Monroe** [comment]
wonderful. Now if you refresh the app does it still show Rejected for Delete?

**Comment by lingutla123** [comment]
No. After refreshing the app it is showing "No response".
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/eae03407-8749-4eac-9f13-58a31e31b48d)

**Comment by Jenefer-Monroe** [comment]
And can you confirm, they are not receiving an email about this specific app, they just see it listed here. Is that correct?

**Comment by Jenefer-Monroe** [comment]
It looks like the mechanism to clear a date from PowerApps to Dataverse has changed. 
So this app does not currently have an archive request associated with it but the work shown here to clear the date no longer works
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3ae07fd8-d543-4822-83a0-ce5dad978da8)

Quick look online and it seems this needs to happen in flow now. So I'll need to augment one of the inactivity flows to check this and clear.

**Comment by lingutla123** [comment]
From email address is our COE Admin account email and  To email address is our Manager's email.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/7bf26010-9370-4297-9cd5-09024c74a413)

**Comment by Jenefer-Monroe** [comment]
Got it. OK yes the issue then is that the date isnt being cleared anymore. 
Thanks for helping me debug.

**Comment by Jenefer-Monroe** [comment]
actually just pushing with with the FC as this app will likely go away in favor of something better.

**Comment by mdphung** [comment]
When is this going to be fixed in the October release? I get the same issue so is there a fix you can provide in the meantime until you have this resolved in the next release?

**Comment by Jenefer-Monroe** [comment]
Turns out this setting needs to be on in order to have the date clearing work. Who knew?!?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0cfc84cf-c23b-4ade-b3bb-92f0ce4502fd)

Local fixed for March.

**Comment by sasrsc** [comment]
Hi @Jenefer-Monroe... I was about to open a ticket on this and found the existing issue. Our company has just turned on all these flows. I have a question. I turned on the formula-level error management with our current version of the CoE (Feb 24). I am questioning this fix.  

Your patch to archive approvals is assuming the row for that app already appears in the table archive approvals. 

``/update data on backend
Set(CurrentArchiveItem, Patch('Archive Approvals', First(SortByColumns(Filter('Archive Approvals', Name=Text(SelectedFlow.theGUID)), "createdon", SortOrder.Descending)), {'Approval Response': "Approve", 'Approval Comment':VerifySendApprovalInput_1.Text, 'Approval Response Date': Now()}));
UpdateIf(Flows, Flow=SelectedFlow.theGUID, {'Flow Archive Request Ignored Since': Blank()});
UpdateIf(theFlows, theGUID=SelectedFlow.theGUID, {requestsIgnoredSince: Blank()});
Remove('Archive Approvals', Filter('Archive Approvals', 'Archive Approval ' <> CurrentArchiveItem.'Archive Approval ' &&  Name=Text(SelectedFlow.theGUID)));
Refresh('Archive Approvals');

Let me first say - I am a citizen dev - so I'm not criticizing - I am trying to learn - I'm just trying to piece together the puzzle because this issue is widely reported. In that line above will it "insert" a row if it doesn't exist? Well what happens if it doesn't exist in Archive Approvals already? That appears to be what is happening in our case. 

Having said that... when I turned on the formula -level management here's what I find...
1) It is recognizing that stored decision value in Flows/Apps now.
2) But I don't understand how the set statement above works if no row exists already.
3) The UpdateIf for flows DV table - I agree / understand
4) The UpdateIf for theFlows collection - I agree / understand
5) The Remove is deleting any other rows that might exist for that flow in Archive Approval

I have 2 stale flow items I could never get rid of, until I turned on the formula-level, so that's helping. But those 2 flows no longer appear in the gallery of flows at all now and I don't understand why...I rejected one and approved the other. This all reverts back to how an item gets into the archive approval in the first place and if it's not in there (what went wrong) and should the Set statement above accommodate for a row not being in the archive approval table in the first place. 

I'm sorry if this is the wrong place for asking.
