### ISSUE TITLE
[CoE Starter Kit - QUESTION] With Microsoft Dataverse(legacy) connector going to be deprecated after Aug 23, Is it safe now to develop using this connector?

### ISSUE THREAD

**Issue by Antiwa05** [microsoft/coe-starter-kit#5476]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

With Microsoft Dataverse(legacy) connector going to be deprecated after Aug 23, Is it safe now to develop using this connector? as we do not have any alternative to this yet.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid this is really a question for product support and not us. 
I can tell you anecdotally that we do continue to use it for x-envt requirements while we wait for the [modern dataverse connector](https://learn.microsoft.com/connectors/commondataserviceforapps/) to support that scenario. Although we dont invest in it much, unless the scenario is really crucial we have just been delaying, as we are accruing tech debt when we use it since we will need to migrate to the Modern one when the legacy one is deprecated.

**Comment by Antiwa05** [comment]
Thankyou Jenefer for the respone!

**Comment by Jenefer-Monroe** [comment]
You are quite welcome. I'll go ahead and close then but please return if you have other questions!
