### ISSUE TITLE
[CoE Starter Kit - Set Flow Permissions] Change the owner of Flow

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#5515]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

hello,

Please, I have a question about the Set Flow Permissions application, these days an employee left the company and his flow was not orphaned, but I needed to change the Owner of this flow. The problem is that I didn't find this flow in the Set Flow Permissions app, I even noticed that it's not finding all the flows inside the environments here.
My question is if this application should show all the flows or just the orphaned ones, and if I can use this application to change the Ownwe

![Screenshot_1](https://github.com/microsoft/coe-starter-kit/assets/129080740/031107de-2886-4e9f-9b2b-16a81f1c7e24)
![Screenshot_2](https://github.com/microsoft/coe-starter-kit/assets/129080740/c23efc15-70ad-4b62-9599-0be09a34cbd5)
![Screenshot_3](https://github.com/microsoft/coe-starter-kit/assets/129080740/50b15e97-bbb2-497d-a73b-d22b43ed2593)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April 2023 4.4.1

### What app or flow are you having the issue with?

Set Flow Permissions 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We had a bug in 4.4.1 that caused flows to get removed from inventory. You will need to upgrade to the hotfix and run a full inventory to see them come back. 

See the issue here: https://github.com/microsoft/coe-starter-kit/issues/5331

The hotfix build: [CenterofExcellenceCoreComponents_4_4_2_managed.zip](https://github.com/microsoft/coe-starter-kit/files/11410600/CenterofExcellenceCoreComponents_4_4_2_managed.zip)

And how to run a full inventory: https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory

**Comment by minobrega** [comment]
Hello,

Ok, I'll update and test here..
Thank you Jenefer

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
