### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Query connector not available in China cloud

### ISSUE THREAD

**Issue by MeredithOneWorld** [microsoft/coe-starter-kit#5518]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi, I am using China cloud version Power Platform. as I were going through required connector list before deployment, Power Query Dataflow is the only not allowed in China cloud.  What will happen if Power Query dataflow not being used? Can I still deploy it and have everything functional?

### Expected Behavior

Be able to deploy core component in Coe kit.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by MeredithOneWorld** [comment]
Thank you Manuela for detailed explanation. One other question is other than Power Query dataflow, China cloud based Power Platform is also forbidden to use Microsoft Teams connector. What impacts will that bring?

Much appreciated,
Meredith Lou

**Comment by MeredithOneWorld** [comment]
Thank you for detailed explanation. One other question is other than Power Query dataflow, China cloud based Power Platform is also forbidden to use Microsoft Teams connector. What impacts will that bring?

**Comment by manuelap-msft** [comment]
Hello,

we use Teams primarily to send Teams adaptive cards to makers/end users to get input or an action so there's a few processes that would be impacted by the Teams connector not being available:

- **App Catalog** (part of Core components): A process in the app catalog allows end users to request access to the app from the maker, this triggers a teams adaptive card that the maker can approve to grant access. To use the app catalog without this connector, you'd either have to remove the button completely or change the flow to send an email / flow approval instead of a Teams adaptive card.
- **Clean up of orphaned apps and flows (maker has left the organization)** (part of Governance components): Teams is used to post an adaptive card to the manager of the maker who left to inform them of what apps/flows got left behind. You would have to change the entire process to not use Teams, e.g. use Flow Approvals instead - this would likely be a bigger change.
- **Microsoft Teams governance (relevant only for MS Teams environments)**  (part of Governance components): This is a process relevant only if your tenant is using Microsoft Teams environments. If you are, then Teams adaptive cards are used to prompt the environment creator to provide further information about the environment, and to let them know if they're environment will get cleaned-up due to not meeting compliance.
- **Pulse survey** (part of Nurture components): Teams adaptive cards are sent to users to get feedback. This process posts Teams adaptive cards to users for approval. You would have to change the entire process to not use Teams, e.g. use Flow Approvals instead

The overall impact depends on which of these processes you want to use and thus have to change the implementation of. 

Hope this helps,
Manuela

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
