### ISSUE TITLE
[ALM Accelerator - BUG]: App and Workflow Permissions Not Set After Deployment or Import

### ISSUE THREAD

**Issue by jfung85** [microsoft/coe-starter-kit#5519]
### Describe the issue

We have deployed one solution as managed to a TEST environment and also imported the same solution as unmanaged to a different DEV environment. After reviewing the solution at the destinations, the Canvas Apps do not have any permissions shared as was configured in the deployment settings. Also the Power Automate flows do not have the owner or group configured. Only the Service Principal App Registration shows as owner on all apps and flows. 

### Expected Behavior

We expect apps to be shared and flows to have additional owners set from the deployment configuration settings in the solution that has been deployed/imported to the destination environment.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Accelerator Version: 1.0.20230405.2(Managed)

### Steps To Reproduce

1. In ALM Accelerator for Power Platform -> For a solution , configure Deployment Settings -> (Canvas Apps) add a group for each line under Sharing and give Edit permissions (Flows) Add a different account to Owner and Activation User and a group to Team Sharing -> Save and Close
2. Commit the solution
3. Deploy or Import the solution to a target environment
4. Check shared settings on Canvas apps and owner settings on Flows on the target environment

**Comment by mikefactorial** [comment]
@jfung85 Looking at the logs it looks like the values are blank for sharing, owner etc. This leads me to believe that the Deployment Step for the specific environment was configured as a Deployment environment instead of a Development environment. The former would use placeholders in the deployment config while the latter stores the values in the deployment config. There will be a change to this in the May release, where both import and deploy can use placeholders if you configure the step appropriately to do so, but this is my best guess right now as to why the deployment settings aren’t reflected in the imported environment.

**Comment by mikefactorial** [comment]
@jfung85 believe this has been resolved. Closing out.

**Comment by jfung85** [comment]
Hi, I'd like to re-open this issue as we have gone through a few more deployment runs. We have found the Power App co-ownership settings are working as expected but the Power Automate Team Sharing Setting is not getting applied on the deployment. When looking at the Power Automate workflows, the group that we added to Team Sharing is not added as a co-owner.
