### ISSUE TITLE
[ALM Accelerator - QUESTION]Can story board help to complete the Pull requests

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5520]
### What is your question?

We are planning to establish ALM Accelerator tool and would like to understand if Story boards can be used in Azure Devops to complete those Pull requests .

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

February

**Comment by mikefactorial** [comment]
@PPMini I'm not sure I understand the scenario. To be honest I haven't worked with Storyboards in Azure Devops so it may just be my ignorance. Might be a better question for the Azure DevOps team or forums since there's nothing specific about how the ALM Accelerator creates Pull Requests that would effect the behavior of Azure DevOps in question here.

**Comment by mikefactorial** [comment]
Closing this out as there's been no response in > month.
