### ISSUE TITLE
[CoE Starter Kit - Admin | Sync Audit Logs  Flow - The server did not receive a response from an upstream server

### ISSUE THREAD

**Issue by sambhrama28** [microsoft/coe-starter-kit#5522]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Issue while calling the child flow ([Child] Admin | Sync Logs) from 'Admin | Sync Audit Logs Flow'

Error: The server did not receive a response from an upstream server. 
<img width="427" alt="FlowFailureIssue" src="https://github.com/microsoft/coe-starter-kit/assets/114514468/8b0f564a-408b-433f-9335-5835ff1f343e">

### Expected Behavior

I have expected success in flow execution for 'Admin | Sync Audit Logs ' but its failing contineously

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Please check the status of the child flow. Is it running and passing? You can check this in the CoE Admin Command Center, and browse to the child flow to check as needed. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0576597e-6e05-4877-93b7-718ad340a6ae)

The issue is likely that either you have not turned this flow on, or your credential to the custom connector was diabled. 

If the later, here are steps to correct: https://github.com/microsoft/coe-starter-kit/issues/4961

**Comment by sambhrama28** [comment]
Hello Jenefer,

Child flow was running fine without any issue until Friday. I had a problem with parent flow alone.
Initially i have used below configurations.
 
StarTime-Interval: 3 
StarTime-Unit: Day 
TimeInterval-Interval: 5 
TimerInterval-Unit: Minute 
TimeSegments-CountLimit: 1500 

In order to fix parent flow issue i have changed the below configuration, whereas remaining same as above

TimeSegments-CountLimit: 1000 


after changing the 'TimeSegments-CountLimit' getting error in both flows now

Parent Flow error :  The server did not receive a response from an upstream server.

Child flow error :  Start time and end time must both be specified (or both omitted) and must be less than or equal to 24 hours apart, with the start time prior to  end time and start time no more than 7 days in the past

Please help me

**Comment by Jenefer-Monroe** [comment]
I am sure your child flow is failing with that configuration because it cannot look back 3 days. 

We are shipping a new version of the audit logs this week that does not rely on the custom connector any longer and that will also remove this chunking complexity. That is likely your best case to recover here. And it will include a flow to load a backlog so whatever you are missing here can be manually uploaded.

**Comment by Jenefer-Monroe** [comment]
Marking code complete so you will get notified when that version is available.

**Comment by Jenefer-Monroe** [comment]
Release now available.

**Comment by sambhrama28** [comment]
Thank you Jenefer, will take a look in that
