### ISSUE TITLE
[ALM Accelerator - QUESTION] Migrate existing solution automation

### ISSUE THREAD

**Issue by ryanhodgson1** [microsoft/coe-starter-kit#5526]
### What is your question?

Hi

I currently have to migrate around 30+ solutions over to use the ALM process and before i find a way to try and automate this process i was wondering if you have any existing scripts you might have that can automate parts of the process? mainly for these steps:

- Setup of branches and branch policies with build validations and required approvers
- Setup of deployment profiles and deployment steps in ALM admin app

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230308.1

**Comment by mikefactorial** [comment]
Hey @ryanhodgson1 
1. For the setup of the branches and branch policy that will happen automatically the first time the solution is exported to Azure DevOps. We have integration test powershell scripts that you could use to automate the initial export here https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/PowerShell/tests/e2e-pipeline.tests.ps1. These are pester tests but you could take inspiration from them to automate this part. As far as setting required approvers we don't have any automation around that today.
2. We don't currently have anything in place to generate the steps / profiles, but since all of that data is just Dataverse tables it shouldn't be a huge lift to do it. You could even probably use Flow to automate the creation on import of a solution or some other trigger.

**Comment by ryanhodgson1** [comment]
Thanks @mikefactorial 

For the first point are you able to point me to where in the template code it creates the branches and branch policies in the export? or is it only that e2e-pipeline.tests.ps1 file?

For the 2nd one i think just the ability to clone profiles would be best as per this ticket:
https://github.com/microsoft/coe-starter-kit/issues/4321

Was there any progress on that ticket you could share that i could use to populate the dataverse tables?

**Comment by mikefactorial** [comment]
@ryanhodgson1 we've not made any progress on cloning deployment profiles. That issue is slated for July but priorities might change. It's not a common ask although it would benefit others as well as us internally. We recently, in the may release, moved the branch creation and pipeline creation out of the coe-cli and into our pipelines so it's more easily discoverable here https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/PowerShell/update-deployment-settings.ps1

**Comment by ryanhodgson1** [comment]
@mikefactorial i reached out over Teams, not sure if you have seen it

**Comment by ryanhodgson1** [comment]
@mikefactorial i have managed to automate everything on my end now so will close the ticket
