### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#5542]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 
I am not seeing all my Flow in the CoE Admin View that are in the Default environment, on checking the Environment table this is showing with 402 flows, when checking with PowerShell I am getting 7238 flow that are in the default Environment, is there a reason why all the flows are not showing in the Coe?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Flows not showing in Default Env

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
If you just recently lost a bunch of flows it is likely due to https://github.com/microsoft/coe-starter-kit/issues/5331 for which we released a hotfix. 

Please upgrade your Core and let me know. You will need to do a full inventory to get them back (which we are making better for May)
[CenterofExcellenceCoreComponents_4_4_2_managed.zip](https://github.com/microsoft/coe-starter-kit/files/11410600/CenterofExcellenceCoreComponents_4_4_2_managed.zip)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
