### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor V2 - Impact analysis always empty

### ISSUE THREAD

**Issue by Ivanbarbosar** [microsoft/coe-starter-kit#5555]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I try to analyse the impacted apps and flows for a new DLP or DLP change, it never shows any resources. 
Its always shows a empty screen, like below:

Analyzed Apps: 0
Analyzed Flows: 0

### Expected Behavior

The DLP Editor V2 should shows the apps and the flows that will be impacted by the DLP.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

DLP Editor V2

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Create a new DLP with 
2. Open DLP Editor V2 app
3. Apply the DLP to an environments which would have apps and flows impacted by the DLP
4. In the Impact Analysis screen, it not show any impacted app or flow: 
Analyzed Apps: 0
Analyzed Flows: 0

![DLP Editor V2 _ Error](https://github.com/microsoft/coe-starter-kit/assets/104643101/68f87717-807b-4508-bf22-9e08673febb9)

**Comment by Jenefer-Monroe** [comment]
Hello. I dont repro this so it may have something to do with the specific connectors you have in your repro. Can you give more precise repro steps? For example, which connector is the offending connector that shoudl block an app/flow. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4b3ae7a3-fea8-476b-a894-efd71ed701c7)

**Comment by aleksanderaalen** [comment]
We have the same issue, when running the impact analysis it says Analyzed Apps: 0 and Analyzed flows: 0 but the DLP we created is very strict and there should be several flows/apps impacted by the DLP we created.

**Comment by Jenefer-Monroe** [comment]
Hello. Are you saying that in your version of the app you dont see this page when you open the app? 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/aa61785e-372f-4a1b-b61f-1312c3131475)

**Comment by davyderoeck** [comment]
Yes, when I started the app for the first time, it didn't opened on the screen you are showing. Also with another organisation I'm dealing, they had the same situation.

**Comment by Jenefer-Monroe** [comment]
I've never seen this occur. 

Can you please tell me what you mean by this? **_After editing the app (from default env.)_**

**Comment by davyderoeck** [comment]
> I've never seen this occur.
> 
> Can you please tell me what you mean by this? **_After editing the app (from default env.)_**

What I was trying to explain:

- I installed the CoE toolkit (feb 23 edition) in a new environment. 
- All steps (and flows) of the installation wizard are successful executed and completed.
- I opened the DLP Editor V2 in my environment. There are **NO**  DLP-policies defined for the environment nor the tenant.
- It opened the app with the Update Policy Screen (not the main screen)
-I could go through the wizard until the step _impact review_ but nothing appears. (Same as the original screenshot of this post)

I tried to investigate (as I was into contact with a customer who had the same issue) and **I wanted to look inside the app** to understand better what's going on.

- I first tried to edit the app **inside** the Coe-Core solution, but the edit option was disabled because the _managed state of the solution_.
_You cannot directly edit the objects within a managed solution. If the managed properties for solution objects are set to allow customization, you can edit them from another unmanaged solution._
-  I navigated to the **default solution** in the environment, this is always unmanaged.
- I navigated in the default solution to the app's and selected the **DLP Editor V2**
- I clicked on **edit** in the ribbon bar to edit the _DLP Editor V2_ app
- I played the app and noticed that the default screen was _not the main_.
- After playing the app, I checked the formula's and the collections and noticed that their was missing data to make the Wizard work properly. It needs info in the _col_environmentsInPolicy_
- I changed the default screen to Main and replayed. 
- Now I was not able to go to the wizard screen (as expected as I didn't had a DLP policy in my environment.
- When I did the same on an environment (the customer) with DLP-policies, this was working fine for him.
Now he was able to edit and evaluate the DLP policies and the **impact analysis** was showing apps and flows

**Comment by Jenefer-Monroe** [comment]
ok that does seem a separate issue to what the poster is refencing. 
@Ivanbarbosar, I'm afraid I dont see your issue repro. Perhaps you have unmanaged layers on app.

**Comment by Titoleto** [comment]
In my case (last release from May), it does show me that it has analysed applications and flows (although they seem to me to be few) but it shows me nothing.

![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/b04597c0-f2d4-4d67-82c4-19c35f8c48a9)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
