### ISSUE TITLE
[CoE Starter Kit - QUESTION] COE Inactivity approval failure

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5575]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

On May 17, I created a brand new testing environment, and setup the core/inventory components from the May 2023 release of the COE kit.

On May 18, I set up the governance components, and set up the inactivity processes.

I used the Setup Wizard whenever it was possible.

After I turned on the flows for the Inactivity notifications process, my Admin account mailbox received a lot of emails saying:

"
The following object was attempted to go through the Inactivity Notification processes but the creation of the approval failed.
Please see Common errors creating and assigning flow approvals to troubleshoot why this can occur
"

I checked my testing environment and a security group is not associated with my environment.

![COE-Inactivity-Approval-Failure](https://github.com/microsoft/coe-starter-kit/assets/128085471/bfd60be3-9bcd-4449-a7a9-5db980240355)

The link below is helpful, but where can I see the error code that got generated when the "Admin | Inactivity notifications v2 (Start Approval for Apps)" ran?

https://learn.microsoft.com/en-us/troubleshoot/power-platform/power-automate/common-errors-creating-and-assigning-flow-approvals

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
You can see the attempt to create the approval here, that shoudl give you the full error message
Create Archival Request for Each > See if Approved > No branch > See if Rejected > No branch > Create an approval.

To find one of your cases, note its AppID from the mail, then go to the output of this action:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7181fa0b-0b9a-475d-8cb9-d9d9e344577b)

You'll put this output in some kind of JSON parser so that you can get find where it is in the return (ex item 305 of 500) and be sure to note if the parser starts at 0 or 1 so you can have it match flow (which starts at 1)

Then go to that record and see what was returned for Create an approval
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f1c95752-4b84-4c6a-a41c-05a55a62259b)

I hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
