### ISSUE TITLE
[CoE Starter Kit - QUESTION] App Last Launch date and Flow Last Run dates fields are empty after setting up CoE using Data Export Feature

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#5667]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

we are trying to set up CoE starter kit using Data Export feature .

All were configured successfully...
![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/c539578f-3d36-42d7-8044-2244d956b244)
![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/5d23b932-5ca6-4ca5-8d87-bda67b4c7e41)
![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/a753f2ff-4640-4ede-a408-ffd0618da436)

But when I open the tables and verify 
1. The  App last launch date field in Apps Table 
2. Flow last run  date field in Flows table still showing as blank.
3. Also I am seeing the value as Unknown in the Derived Owner field (what is the difference with Blank and Unknown)

Please note, while setting up CoE core solutions I have ran the Set up wizard and it failed to run the flow Admin Sync V3 Connectors flow and it is failed . Is there any dependency with below flow 

![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/3f0be062-2c9a-4777-bd08-578db23b7a47)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May release hot fix

### What app or flow are you having the issue with?

Apps 

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
For the issue with: Admin Sync Flow v3 | Connectors > this flow failed due to a product bug with the Power Apps for Makers connector, this bug was fixed and the fix has rolled out to all stations. If you re-run the flow now, it should work. 

For the launch time issue:
1. Launch history is only available from the moment you configure the CoE kit, can you confirm the apps and flows have launched since you set up the dataflows which looks to be only yesterday? 
2. If they have, open the CoE BYODL Apps Last Launched Date Dataflow - what do you see displayed in the table? Is information showing? Can you share what you're seeing and we can do from there.

**Comment by pamatihyd** [comment]
Yes now I am able to see the app launh event dates and flow is also working fine
