### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Logs - deprecated flow

### ISSUE THREAD

**Issue by johnravas** [microsoft/coe-starter-kit#5684]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am hoping that this isn't a duplicate question.  Searching didn't reveal this question.  I am upgrading my Dev environment to the May edition of the CoE.  As part of this upgrade, I updated the Audit Logs solution.  The Admin | Sync Audit Logs flow shows as deprecated.  I understand that you are moving the solution over to a BYODL.  However, we are not ready to move in that direction yet.  Should I not upgrade the Audit Log solution in production until we are ready for BYODL?  Can I still run the May edition deprecated flow in production?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

May 2023 3.4

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. The Audit Logs solution was not deprecated to push people to BYODL (although we do really suggest you consider BYODL for other reasons :))

The solution was deprecated because we were able to re-create the functionality without a custom connector. So no more upgrade pain etc. 
Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http). 
To use the same app registration as you use for the custom connector you will just need to change the API permissions to Application instead of Delegated.

**Comment by johnravas** [comment]
Will review this documentation.  Thank you for the prompt response @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment]
You are welcome! I'll go ahead and close this out then but please feel free to return with other questions.
