### ISSUE TITLE
[CoE Starter Kit - BUG] Flow Licensing Error, do not have appropriate license to run premium connectors

### ISSUE THREAD

**Issue by ethan-hurst** [microsoft/coe-starter-kit#5688]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When installing core components, some of the flows are presenting with an error advising we do not have the correct license for the connectors when we have assigned those licenses correctly. 

### Expected Behavior

Flows should be turned on and run 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Several

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Install Core Components solution
Open Setup Wizard Model Driven App
Attempt to run through wizzard
When it comes to enable flows, no flows are presented to enable, and notification that some flows could not be turned on is present in toast notifications
Check on flow and find that we are presented with an error that advises we do not have license available to run premium connectors

### Anything else?

![e5641e29-0909-49bd-a2a2-ace64b140cc0](https://github.com/microsoft/coe-starter-kit/assets/23321960/633cb4de-8cb7-4285-ac12-c91a341a8b25)

**Comment by Jenefer-Monroe** [comment]
Hello. Our licensing requirements are shown here. 
[What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

Common issues people face here are : 

- having the license assigned via PIM instead of permanently
- having just received the license and it hadnt propogated yet
- having logged in as the wrong user (themselves instead of their service account for example)

If its not one of those, please do go try to turn the flow on manually and let us know the exact error message you receive.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
