### ISSUE TITLE
[CoE Starter Kit - BUG] Dashboard refresh error

### ISSUE THREAD

**Issue by JawnLegend** [microsoft/coe-starter-kit#5692]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Trying to refresh the dashboard to get the latest data, but am met with an error stating columns are missing in the tables,

![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/fdaafdf0-3e3a-4c82-906a-416e1f7ec827)

### Expected Behavior

Expected dashboard to refresh with latest data. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

CoE Dashboard (suspecting the Admin Sync V3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Refresh data in CoE dashboard
2. Error displayed stating missing columns in tables

**Comment by Jenefer-Monroe** [comment]
Hello. You need to update the report with the new ones shipped with the same release. So each month we ship a new PBIT as well. Usually you can get away with not upgrading it but sometimes (like this) we do some clean up in the Core solution and then the old reports wont work any more.

**Comment by JawnLegend** [comment]
I just published the dashboard, and that fixed the error – thanks! However, I'm still missing data; some of it isn't updated. It seems to be stuck on May 22nd. 


![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/8e81ea60-d403-4021-9953-a21f320778f5)

**Comment by JawnLegend** [comment]
I just published the dashboard, and that fixed the error – thanks! However, I'm still missing data; some of it isn't updated. It seems to be stuck on May 22nd. 


![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/8e81ea60-d403-4021-9953-a21f320778f5)

**Comment by Jenefer-Monroe** [comment]
I presume that is when you upgraded? Note that the old audit log solution has an issue based on it being a custom connector based solution in that the connection to the custom connector needs reset every time you upgrade.  Please see https://github.com/microsoft/coe-starter-kit/issues/1424

Good news is that with May we released a mechanism to gather logs with HTTP connector instead of a custom connector so this should be easier going forward. You need to change the app registration slightly (to application permissions) but otherwise its pretty seamless. Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
