### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs solution

### ISSUE THREAD

**Issue by Sanushattrv** [microsoft/coe-starter-kit#5701]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Not reporting a bug, just have a question for the CoE team, We are using CoE started kit with an older version which still uses the Audit log solutions. However, we came across this article https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog that audit log solution will be removed/deprecated in August 2023. Will this impact our existing deployed solution?
Do we have to upgrade our CoE tool kit before this deadline ?   

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.0.0.6

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
For the audit logs alone, the idea is that if you want to keep using it after we remove it from Core you will just need to copy the custom connector yourself, perhaps put it into the old audit logs solution, as we will not ship it with Core anymore, before you do that upgrade. 

Do note that we still support gathering audit logs via the office 365 API, we were just able to do it with an HTTP call now instead of CC which remove the upgrade pain, the chunking pain, etc. Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http). It requires you change teh app registration slightly. 

As to mandated upgrade, not for this no, but there is a mandated upgrade coming in a few months due to a product change. They are deprecating the way we used to gather inventory via Get Flows as Admin. There is a new action Get Flows as Admin (v2) which is required. Expect communication about that from the product team itself. 

Hope this all helps

**Comment by Sanushattrv** [comment]
Sounds good! Thanks for your quick response and detailed explanation.

**Comment by Jenefer-Monroe** [comment]
happy to help!
