### ISSUE TITLE
[CoE Starter Kit - QUESTION] Upgrade to latest Starter Kit May release 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#5715]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Thank you for your timely responses for all my queries.

we are trying to upgrade to new version of CoE Kit may , 

In our Production tenant , we are currently installed CoE Core components and Audit Log components
1. CenterofExcellenceCoreComponents_4.3_managed
2. Center of Excellence - Audit Logs_3.3_managed

Now I am trying to upgrade CenterofExcellenceCoreComponents_4.3_managed to CenterofExcellenceCoreComponents_4.8_managed 

My question is do we really need upgrade the . Center of Excellence - Audit Logs_3.3_managed along with core components , 
because we recently upgraded the Audit log connector solution , we really dont want to touch unless if it really needed to upgrade along with core components ?

Also , this time we are planning to import governance components into Production tenant, In this components there are components related to makers 

After we import governance components , we dont to trigger any mails to makers or end users. how to make sure this ?
As soon as we import ,we are planning to turn off all the flows to make sure  no mails trigger to  makers.

we are not going to user all the components in the CenterofExcellenceAuditComponents_3.9_managed 

we are planning to go one by one components lets say now we are only planning to enable only Inactive components.

In this case we are planning turn off all the other flows and only enable Inactive components 

Kindly please suggest 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Thanks for reaching out. I've characterized your questions here, please let me know if I missed anything.

1. Do I need to upgrade all solutions when I upgrade Core?
- We always reship the solutions, if no changes were made to it, then the version will not be changed and you can ignore it.
- If the version has changed from what you have installed then yes you need to do the upgrade.

2. (You didnt ask but) upgrading Audit Logs is problematic. Can you please make it easier?
- We have removed the requirement to use the custom connector to gather logs via Office 365 Management API. We now have a HTTP call isntead. This will make upgrade easier as nothing will need redone each month
- To use the HTTP call instead of the custom connector with the same app registration, you will need to make one change to the app registration. 
- Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http) for more information. 

3. How can I turn on Governance features one by one? 
- we ship all these features in Governance off, and then you can pick the featuers to turn on one by one in the CoE Setup and Upgrade Wizard
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2b37fadd-5bf3-42bd-96e6-133611d26aff)

4. How can I turn on Governance features slowly?
- many of the features here (ex inactivity / compliance) have the ability to excuse environments from being considered so that you can start by just running the feature with a target environment
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/623c1903-fb1b-4c89-9406-5f6a5d181851)

5. (You didnt ask but) is May a good build for me to do this all with?
- I suggest you wait for the June release later this week at this point. We made improvements in the setup wizard to make the above easier, including the ability to reliably excuse environments as described above.

**Comment by pamatihyd** [comment]
Thank you sure I will wait and thanks for information on latest release 

I have one more query 

we are planning to import latest  CoE core Components and dont want to import the audil log set up since there are changes from Custom connector to HTTP action . 

we have installed CoE with Data export feature in another environment and we are able to see the app launch events  flow last run without explicitly configuring audit log connector set up 

Going forward we will rely on this new Data export feature only .

In this case shall we go ahead with only core components and leave the audit log connector as it in another env 

will this run or after importing CoE again we need to do any re configure audit log connector

**Comment by Jenefer-Monroe** [comment]
if you decide to switch to data export then you can just turn off the flows in the Audit Log solution, or even delete the audit log solution.

**Comment by pamatihyd** [comment]
I See June release starter kit release today shall we go ahead with this new release ?

**Comment by Jenefer-Monroe** [comment]
Yes please do. I'll go ahead and close this one but please feel free to return with other questions.

**Comment by eileenoceilleachair** [comment]
Hi, 
I'm new to CoE.
I set up CoE and installed Core Components solution and the Audit Components (Governance) solutions in August 2023 following your videos and documentation on Microsoft Learn.

Then in Jan 2024 I upgraded the CoE using the Jan 2024 release - I imported the Core Components solution and I also imported the AuditComponents solution (governance) - see below results of the import.


_**Solution "Center of Excellence - Core Components" imported successfully.**_

**_Solution "Center of Excellence - Governance Components" imported successfully._**

I have two queries - and apologies I'm not quite understanding the above response on this -

First I don't make any changes- I use the solutions as they are out pf the box and don't customise anything.

1)  Do I need to import the Audit Components (Governance) solution each time I update the CoE?

2)  Do I need to import the Power BI CoE and Governance pbit templates every time into Power BI Desktop which I then publish to Power Bi service - Does the power bi pbit templates change?
