### ISSUE TITLE
[CoE Starter Kit - BUG] Legacy Env check fails on Sync Template V3 with Hotfix

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#5726]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting Action 'Get_Environment' failed on checking for legacy environments from Sync Template V3.

![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/a7a9630f-5e75-43e8-a4e8-59c4d9d09d79)

### Expected Behavior

No error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8 with Hotfix

### What app or flow are you having the issue with?

Admin - Sync Template V3

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. That indicates that you can dive into that call to find the terminating failure. You will need to find down deeper where the actual failure occurs.
Most of the time the failure is due to not having all the child flows turned on. You can check that as well. [Turn on child flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
