### ISSUE TITLE
[CoE Starter Kit - Feature]: DLP Editor to contain Desktop flows actions - After update from DLP Editor V2 app, desktop flow actions are disappearing from existing DLP policy

### ISSUE THREAD

**Issue by annsarP** [microsoft/coe-starter-kit#5779]
### Is your feature request related to a problem? Please describe.

In the Power Platform admin center we get ability to turn on dekstop flow actions in DLP:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/bdada5b6-fe42-41fa-88ae-b47aaf0443a3)
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/dbe8c878-b2cb-41ec-98aa-5417399adebe)
After that we are able to see dekstop flow actions in list of connectors during creating / editing DLP Policy.
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/8293086b-652b-465f-b257-8011e7052772)
However, since DLP Editor V2 app collect only connectors it cannot really "find" desktop flow actions.
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/9ee92761-4d21-40f0-875c-65eb8078a4f7)
**!!! After update from DLP Editor V2 app, desktop flow actions will disappear from existing policy.**

### Describe the solution you'd like

I would like DLP Editor V2 to have desktop flow actions on the list as well. Currently admins may delete them by mistake and with no intention from their existing policy by using this app. App should show users list of specific DLP properties - connectorGroups (connectors + desktop flows) not just general list of connectors.

### Describe alternatives you've considered

Alternatives are:

- not using app at all and always creating and updating DLP Policy via admin center to avoid deleting desktop flow actions from policy by accident 
- re-creating an app and instead of listing connectors listing DLP Policy **_connectorGroups_** properties that can be received for example from Power Automate flow via action **Get DLP Policy V2**:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/1cc3c1eb-a3a5-4a73-bcaa-49d3858ed01e)

**Comment by manuelap-msft** [comment]
The Automation Kit offers DLP Impact Analysis for desktop flows
https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/dlp-impact-analysis

The kit specifically targets Desktop Flow / Hyper-Automation scenarios. Due to complexities regarding impact analysis and Desktop Flows (e.g. the CoE kit currently doesn't inventory desktop flow actions at all), we'll have to leave this as separate tools and kits and won't invest here for the CoE kit itself.

Regarding the issue you highlighted in desktop flow actions being removed, we'll have to check if we can persist them during the update, or if we can at least identify that a policy contains desktop flow configuration and then hide the Edit button.

We'll investigate! Thanks for raising this!

**Comment by manuelap-msft** [comment]
We're unable to make these changes today, as the action used in the app does not return the necessary properties. We'll suggest using the DLP Impact Analysis of the Automation Kit instead.
