### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flows and Apps not being added to Dashboard

### ISSUE THREAD

**Issue by JakubZizka** [microsoft/coe-starter-kit#5780]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi guys,
We installed CoE with Data Export as we got 40k flows and 13k apps. It all worked well until 2weeks ago. No new records are picked up. 

**Background**
We added two new columns ('Division', 'Service Account Owner') to "App" and "Flow" Dataverse tables in the environment hosting CoE. We need it to add flow owner's division || owning account's manager's division. This is to enhance reporting. 

Could it be the reason? We have not found any component failing...

**Thank you,
Jakub from DHL**

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core Components  4.4.2

### What app or flow are you having the issue with?

Data Export/Dataflows

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
Hello,

the architecture of how new apps and flows get added to the dashboard is quite complex, so let's try and find the root cause of why this is failing and then go from there:

1. Are you still seeing new files come through in the Storage Account that you set up for Data Export? If you go to the Storage Account, and check the powerplatform/powerapps/Applications and powerplatform/powerautomate/Flows folder - sort by last modified date - do you see any updates happen in the past two weeks? That's just to confirm your Data Export is still working as expected.
2. The data from the Storage Account then gets transformed by a Power BI dataflow - navigate to app.powerbi.com > Your CoE Workspace > check the Refresh History of the Dataflow, do you see it completing daily or do you see any failures there?
   ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/0c04f24b-676c-4af3-8c87-68784d354619)
3. Download the last Refresh from the Dataflow (click the download icon on the top row) and open the refresh report, does anything look unusual there for the Apps/Flows table?
4. Open the Dataflow in Edit Mode and check if you see the latest apps and flows in the dataflow directly. That would be a good indicator on if the dataflow is picking them up. You can do that by selecting the Apps/Flows table and sort descending by last modified or created date
   ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/68b5ef3a-1b89-4faf-ade4-8c96fbe25de2)
6. Lastly, check the Settings of the Dataset that's part of the published Power BI report - under Data Source credentials is everything authorized (no warning about missing connections) and is the scheduled refresh set up correctly to refresh every day? Has a recent refresh of the Power BI dashboard failed? 

I don't think adding new columns should cause any issues, so it's more likely that something between Data Export > Power BI Dataflow > Power BI Dashboard has gone wrong. 

Let me know what you'll find!

**Comment by JakubZizka** [comment]
Hi Jenefer,
I followed your instructions.

Findings:
Dataflow has 1000more items than report displays:
![image](https://github.com/microsoft/coe-starter-kit/assets/22353782/d01b1a79-3dea-4a8d-ac2d-964e2a27fa14)

The newest apps in PowerBi are from 15th May
![image](https://github.com/microsoft/coe-starter-kit/assets/22353782/985ac2aa-aa43-485c-a33c-50c76f7e8155)



Some fails about credentials found
![image](https://github.com/microsoft/coe-starter-kit/assets/22353782/4e86e675-6059-44bd-9b09-8ff25c032d99)

Unable to fix due to:
![image](https://github.com/microsoft/coe-starter-kit/assets/22353782/e8565b10-f145-4cae-8c46-18ccae72d91a)

However, refresh history does not display any error:
![image](https://github.com/microsoft/coe-starter-kit/assets/22353782/3290aa5a-cbd7-45d9-a817-66d1409cccd3)

Refresh log:
![image](https://github.com/microsoft/coe-starter-kit/assets/22353782/78b1570b-7683-4c00-bfaa-fe6b564bd3f2)


Thanks

**Comment by manuelap-msft** [comment]
The refresh/authentication failures here are expected, unfortunately when we ship the Power BI Dataflow file it does "remember" how we (in our development environment) connect to it so you'll have that connection there as stale - but it does not impact the load, so that's looking all good so far!

Can you also check the Power BI refresh itself?

1. Navigate back to app.powerbi.com > Your CoE workspace
2. You should see a Dataset and Report there (as well as the dataflow). Does the dataset show a last refreshed and next refreshed date? Is the last refreshed date today/yesterday?
   ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/989a8ed4-fabc-4d30-b4f9-4ae417d0dc7b)
3. Select the ... next to dataset > Settings and check the Data source credentials there (configured without a warning triangle) and the scheduled refresh (configured to daily)
   ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/a4d52e14-8f58-4151-88a8-54dd9d327eb8)

**Comment by JakubZizka** [comment]
Looks ok:
![image](https://github.com/microsoft/coe-starter-kit/assets/22353782/7093ec65-0b14-48e7-89f3-e7a4ec961b27)

**Comment by Jenefer-Monroe** [comment]
For these new apps. Can you see what value you have in the Name column? Are they filled?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a7f91708-ab9b-4a09-a3ab-f4846c3d9a0c)

**Comment by VictorBcht12** [comment]
Hello, 
I have the same issue with the credentials. When I wanted to check the credentials Dataflow. I tried to re-connect and I had the same error "Selected user account does not exist in tenant "TEST_TEST_POWERCAT_TOOLS".
Do you have any advice ?

**Comment by Jenefer-Monroe** [comment]
This means you did not update the dataflows to your own tenant, either in the DatalakeURL or EnvironmentAPI, you are still poitning to our test tenant

Please see [Configure connections to data sources](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#configure-connections-to-data-sources)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d3a0eb76-fe7c-41e8-a09d-ad64a96f4448)
