### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#5781]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are implementing Power Platform CoE Kit for our environment. 

We need more understanding on Licensing Part . can u please arrange call so we can discuss in details.

Error: Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'List_Ai_Models' of type 'OpenApiConnection' at line '1' and column '3418' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Ai Models) Admin | Sync Template v4 (Apps) Admin | Sync Template v3 (Business Process Flows) Admin | Sync Template v3 (Call Updates) Admin | Sync Template v3 (Connection Identities) Admin | Sync Template v3 (Custom Connectors) Admin | Sync Template v3 (Desktop Flow - Runs) Admin | Sync Template v3 (Desktop flows) Admin | Sync Template v3 (Environment Properties) (optional) Admin | Sync Template v3 (Flow Action Details) Admin | Sync Template v4 (Flows) Admin | Sync Template v3 (Model Driven Apps) Admin | Sync Template v3 (Portals) Admin | Sync Template v3 (PVA) Admin | Sync Template v3 (PVA Usage) Admin | Sync Template v3 (Solutions) Admin | Sync Template v3 (Sync Flow Errors) Admin | Sync Template v3 (Driver) CLEANUP - Admin | Sync Template v3 (Check Deleted) CLEANUP - Admin | Sync Template v3 (Connection Status) CLEANUP - Admin | Sync Template v3 (Delete Bad Data) CLEANUP - Admin | Sync Template v3 (Orphaned Makers) CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) CLEANUP - Admin | Sync Template v3 (PVA Usage)

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with). 

This has been raised multiple times before, so you can look through previous issues for further comments
https://github.com/microsoft/coe-starter-kit/issues?q=InvalidPaginationPolicy

Closing out as duplicate.

**Comment by sunilmhatugade** [comment]
Can u please call me on +91 9975471900 . We need some more understanding on this

**Comment by sunilmhatugade** [comment]
which licences required to full implementation CoE Kit. 

We hvae Office 365 E3 lic. Kindly suggest which licences required to implement Full CoE Kit.
