### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - View-only audit log role still needed with new http method

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#5786]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

With the new audit log connection (http) request through the azure app. Is it necessary for the service account to have permissions to the audit log still? Or since the azure app pulls the info, we can view through the CoE?

Similar to this, with the new set up, do we still need to import the audit log solution? Its not mentioned in the new instructions.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

June 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
`With the new audit log connection (http) request through the azure app. Is it necessary for the service account to have permissions to the audit log still? Or since the azure app pulls the info, we can view through the CoE?`
We do not believe this is needed anymore but have not tested yet to validate. Will be updating the documentaiton once we know for sure its not needed. Please do try it out and let us know your experience!

`Similar to this, with the new set up, do we still need to import the audit log solution? Its not mentioned in the new instructions.`
No you do not need to update that solution. We only marked it deprecated as the last change, and will not be shipping it any longer starting in August.

**Comment by pnoot7** [comment]
Thank you for the reply! I was thinking that would be the case. Currently working to rebuild our CoE, so I will see how it goes.
