### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL - Usage files are not including data from all environments

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#5796]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

It's been few weeks we have observed that Power Automate usage files only include data from 2 environments and the file size has also reduced over time, see screenshot below:

![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/453d5a5c-fdad-4b5a-b2d1-9ed3b5e05d59)

I've checked BYODL PBI report and could confirm that its not including usage from the CoE Starter kit environment. We have upgraded to May 2023 release and have Audit Logs v2 flow running however the report doesn't show latest run date and no. of runs for any of the flows after 23rd May 2023. 
 
This issue has been reported to CSS, however they are not quite able to understand Data Export feature and the case is being transferred between teams. 

Below screenshot shows usage information for some flows that are running from quite some time:
![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/cd4ae6ad-05d0-4f88-9525-f62a39a1845d)

### Expected Behavior

Usage files exported to Azure Data Lake should contain information from all environments where flows are running.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

N/A

**Comment by manuelap-msft** [comment]
Hi Bhavik,

thanks for raising this - can you share with me the support ticket ID so I can forward that to the Product Group? As you know, the Data Export feature is a product feature and the CoE kit is just a consumer of this feature so there's nothing we can do to fix the problem here but I will forward this to the right Engineering team so hopefully the support ticket can be routed to them then.

Thank you
Manuela

**Comment by bhavikj65** [comment]
Hello Manuela,

For your convenience, following is the support ticket number 2306010050001195.

**Comment by manuelap-msft** [comment]
Hello Bhavik,

I followed up with the Data Export PG team and they let me know this issue has been mitigated and the backfill process should have finished 6/27 as well. Are you still seeing issues with usage files now or does everything look up to date now?

Thank you
Manuela

**Comment by bhavikj65** [comment]
Thanks Manuela for the update, I will check the behaviour today and let you
know.

**Comment by bhavikj65** [comment]
@manuelap-msft ,
Although I can now view usage information for some of the flows that weren't available when I first reported this problem, it is still not completely resolved since I can still find numerous flows that lack the last run date and number of executions.  A screenshot is provided below for your use:

![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/be2e7acc-b489-4008-8984-782c70741c4c)

**Comment by manuelap-msft** [comment]
Hello,

thanks for the update!

I believe this is due to how incremental refresh is set up on the Dataflow. By default, it only fetches and loads data from the last 3 days into the Power BI dataset for app and flow usage and builds up data there incrementally every day. If data is missing for a longer period of time, that would cause a gap here. 

I think to resolve this you can try
1. Navigate to app.powerbi.com
2. Open your CoE Power BI Workspace
3. Select Edit on the Dataflow
    ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/0085140b-b139-408e-8dc0-3aa38b9abdfc)
4. Select the Incremental Refresh setting on the FlowUsage table
    ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/ddb18b84-8e5f-4a08-aa76-ba989b5757b7)
5. Change the value where it says "Refresh rows from the past..." - it's set to 3 days to look at the past 3 days worth of value. Try setting it to the past days of how long your data was missing for - e.g. last 20 days or 30 days. And then perform a refresh.
  ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/c3a8682c-0c0e-42d6-b625-e272866c4f43)

The data will get loaded into the dataset and will be stored there for 2 years, so once the missing data has loaded you can set the incremental refresh back to 3 days which should improve performance of this load.

**Comment by bhavikj65** [comment]
Thank you Manuela, this seems to work now.

**Comment by manuelap-msft** [comment]
Great, thank you for confirming!
