### ISSUE TITLE
Admin Sync Template V3 Flow Failing consistently 

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#581]
Hi Team,

We have configured COE in D4T environment and we noticed Admin Sync Template V3 is failing consistently.  In Admin Sync Template v3 Apps (flow), we see a GUID at Filter rows condition on the below action.  We have not modified the flow; I’m not sure what this GUID is referring to.  However, this flow is consistently failing after this action.  Please see attachment and advise, thanks.

[AdminSyncTemplatev3Apps_error.docx](https://github.com/microsoft/coe-starter-kit/files/6610403/AdminSyncTemplatev3Apps_error.docx)

**Comment by JeneferM-MSFT** [comment]
Hello this is a known issue and fixed in the June release. 

Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not removed the unmanaged layers as described there you will not receive updates from us. 

Thank you for using CoE
