### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Log Flows marked deprecated

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#5854]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the new Release of CoE the Audit Log Flows are marked deprecated, but I wasn´t able to find an alternative / new solution. 

What´s the new solution or did I miss something?

![image](https://github.com/microsoft/coe-starter-kit/assets/109345362/7c4dbd3a-bb08-4148-a272-0a0d2ba87c75)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.4

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by DominicMeznik** [comment]
My bad, found the answer in the documentation: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

Seems like I had the old version still cached :)

**Comment by manuelap-msft** [comment]
Hello,

we recently moved from using a custom connector to using an HTTP action - here's the setup instructions
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

There's a few benefits / reasons we did this:
- the customer connector needed re-configuring with every upgrade, which meant it was more efforts for customers doing an upgrade, but also often led to questions/issues for us to triage 
- the custom connector didn't implement pagination and we used environment variables for the "chunking size" which wasn't intuitive to use and error prone. with the HTTP action, we implemented pagination so you no longer need to worry about breaking down calls into chunks
- with how custom connectors and connection references work, we had to ship the custom connector and then the flows using the connector in two separate solution increasing the solutions customers had to import - with the HTTP action, we've moved everything into the Core solution making it easier to maintain and keep up to date

There are some reasons why you may need to continue using the custom connector:
- the App Registration needs to be updated with Application instead of Delegated permission to be used for the HTTP action; if your Azure admin isn't able to grant that you may need to continue using the custom connector
- the HTTP action accepts the client secret in either plain text (not recommended) or via Azure Key Vault (recommended). If you do not have access to Azure Key Vault or aren't able to use that for some reason, you may need to continue using the custom connector and save a copy of it into your own solution before we remove it from the managed solution we ship.

Hope that's some additional helpful details!

**Comment by DominicMeznik** [comment]
Thanks @manuelap-msft , that´s actually really helpful!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by lrarbin** [comment]
@Jenefer-Monroe & @manuelap-msft - Sorry to bother you, are there any instructions on decommissions the deprecated Audit Log solution. Or is it just a case of uninstalling the 'old' Auditing solution (CenterofExcellenceAuditLogs_3.4_managed) and starting to use the new one? Thanks

**Comment by Jenefer-Monroe** [comment]
No problem, happy to help. 

If you use the old Audit Logs solution today here is how to convert
1. Update app registration
- Just need to change the API permissions from type Delegated to type Application
2. Add app registration details to new env variables
- Support plain text or Azure Key Vault
3. Get rid of old solution
- Turn off old flows in the Audit Logs solution
- You can even delete the old Audit Log solution. You won't need anymore
4. Turn on new flow
- Admin | Audit Logs | Sync Audit Logs (V2)

Please let me know if I have resolved for you.

**Comment by lrarbin** [comment]
@Jenefer-Monroe - Thanks, that's all working now. Hopefully no more 'failed sync' messages!
