### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unique Actions empty in Cloud Flow Risk Assessment report

### ISSUE THREAD

**Issue by whorn76** [microsoft/coe-starter-kit#5866]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I've noticed in a couple of recent COE setups with the June release that the Cloud Flow Risk Assessment report.  The "Unique Actions" column wasn't populated.

Is this a known issue is there something that isn't happening to populate that report or does it take some additional time to populate?  I'm assuming its the Admin | Sync Template v3 (Flow Action Details) flow that is populating that column, but not 100% sure.

Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Correct, **_Admin | Sync Template v3 (Flow Action Details)_** is what fills this. By default this will only populate for flow that have been recently modified (in the last week). This is because the flow is very API intensive and so even for small tenants it gets throttled. So over time this will populate for flows.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
