### ISSUE TITLE
[ALM Accelerator - QUESTION] Guidance needed on moving ADO setup to different project

### ISSUE THREAD

**Issue by RebekkaAalbers** [microsoft/coe-starter-kit#5872]
### What is your question?

We have the ALM Accelerator installed and working, but we want to move the Azure DevOps configuration to a different ADO project. Do you have any guidance on the best approach to do that? We want to keep the Power Platform solution as if possible. Can we consider this as an update or should we do a completely new installation?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20230308.1

**Comment by mikefactorial** [comment]
@RebekkaAalbers thanks for the question. It's fairly straightforward to create and initialize a new Azure DevOps project using the project setup wizard and then create new solution deployment profiles to point to the new project. However, that will not move any existing deployment pipelines or repos / history. Cloning the repo to the new project is fairly straight forward using Git but in order to initialize the deployment pipelines you would need to re-export the solutions from maker's environments. The export pipeline will recreate the deployment pipelines.

**Comment by mikefactorial** [comment]
Hey @RebekkaAalbers closing this out for now as there's nothing more for the team to do here. Feel free to open a new issue if you have additional questions or issues.
