### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Deleted

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#5889]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I deleted an environment through the Power Platform Admin Portal on the 23rd May 23 (see below), although it is still showing up in the Power Platform Admin View as **not** being deleted. (see second image below)

<img width="468" alt="CoE1906" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/083fba02-db8a-47b6-8e95-71e79f63346e">

<img width="903" alt="CoE1906_2" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/b30f1945-3763-496e-83a8-6a87da9ffc63">

Should the inventory flows automatically detect that the environment has been deleted? Subsequently also removing the flows \ apps from the inventory table? Or should I have done something after deleting the environment through the Power Platform Admin portal?

thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Are all inventory flows turned on? In particular, is **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** turned on, running, and passing? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/85dedf8b-cc3c-4a3a-b875-94d3a5129108)

**Comment by Jenefer-Monroe** [comment]
All flows in your inventory type need to be on in order to have a reliable inventory, and flows need to be turned on in a particular order in order to be able to be turned on, this for example, has a child flow that is also not turned on. 
It is suggested to use the Setup Wizard when installing / upgrading as this will take care of this complexity for you, else you need to manually turn them on in the correct order

From [Set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components)

1. [Turn on child flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows)
2. [Turn on setup flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-setup-flows)
3. [Turn on inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows)

**Comment by G1982C** [comment]
Thank you Jenefer. This conversation has been valuable as I update the CoE every month and have been following the upgrade steps, but I skim through the content and never saw point 8 - Open the CoE Setup and Upgrade Wizard app. This would explain why some flows are not on, I assumed I just had to import the solution. So thank you, a valuable lesson learnt and one for me to remember.

**Comment by Jenefer-Monroe** [comment]
oh wonderful. I think you'll love the setup wizard! I upgrade a LOT since I own that testing. And its changed my life haha

**Comment by G1982C** [comment]
Just used the setup wizard and what a fantastic tool. Not an issue as the app still worked, but I was getting the error below pop up and it prevented me from interacting with the app screen. If it left it a few minutes the error disappeared and I could interact again wtih the app screen

<img width="613" alt="CoE1906_5" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/53c815c7-9944-4187-9a00-f247ec7b005f">

**Comment by Jenefer-Monroe** [comment]
Unfortunately there is a product regression right now related to hte components we use in our apps, the product team is working on a roll back now. Please see https://github.com/microsoft/coe-starter-kit/issues/5815
