### ISSUE TITLE
[CoE Starter Kit - QUESTION] Check if environment are really deleted

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#5907]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

in a CoE installation there are serveral (teams)-environments, which are marked as deleted but are still there and contain also apps and flows.
Is there a way to update this information (BYODL and cloud flows inventory)?
A full inventory run did not do the trick.

Best regards

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry we will need some more information to assist as this isnt somethign that I repro. Can you please give some more information like the following:

- When you say BYODL and Cloud Flow, what does that mean? Do you have two installs and repro in both? Was it in an upgrade? 
- If you go to the products Admin Center, https://admin.powerplatform.microsoft.com/environments, do you see the envts there?
- Can you please let me know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)
- And also share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by lukas-nC** [comment]
The problem occurred with cloud flow inventory, now it has been changed to BYODL and the environment are still marked as deleted.

The environments and the apps/flows are visible in the Admin Center.

All environments are in Europe


![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/429ef85d-20cf-4bb7-80a7-2e391bc14d64)

**Comment by Jenefer-Monroe** [comment]
ok we will need to investigate these seperately so since we are in BYODL land, you will need to go to the Datalake itself. 

Go to the Data Export Datalake > powerplatform > powerapps > environments > click edit on the file
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/82324001-2a35-4690-bd03-fb2f1acf0599)

Control - F to search for the environment id which you say should be present. Do you see it in the file?

**Comment by lukas-nC** [comment]
I don't know what happend but now, no environment is wrongly marked as delete.
thanks @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment]
Wonderful news. Thanks for letting me know.
