### ISSUE TITLE
[ALM Accelerator - QUESTION] How to resolve - Error running pipeline: CustomAzureDevOps.RunPipeline failed: _scrubbedSensitiveData_

### ISSUE THREAD

**Issue by jfung85** [microsoft/coe-starter-kit#5915]
### What is your question?

We are trying to setup a non Power Platform admin account inside of an AAD group to be able to use the AA4PP app to deploy a solution from Dev to Test. We have gotten to the point of being able to complete the "Configure Deployment Settings" step for Test and clicking on the Commit Solution button. However, after filling out the Commit Solution panel and then clicking on the final Commit Solution button, we get this error: Error running pipeline: CustomAzureDevOps.RunPipeline failed: _scrubbedSensitiveData_. We recently upgraded from May 2023 to June 2023 and did run steps to update the pipeline from the ALM Template. It showed successful but not sure if it still may be related to this error.

We have tried to follow steps at these articles using the ALMAcceleratorForMakers AAD group (ALM Group) in all permission configurations:
https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-app-user-permissions

1. On AA4PP environment -> added ALM Group to a Team with Security Roles ALM Power App Access, ALM Power App Deployment Configuration, Basic User and added ALM Group to Environment Security Group
2. AA4PP app shared with ALM Group
3. CustomAzureDevOps shared with ALM Group
4. In Source Dev and Target Test environments -> added ALM Group with Basic user, Environment Maker, System Customizer roles
5. Azure DevOps -> Added ALM Group to Project Settings -> Teams
6. Azure DevOps -> Added ALM Group to Project Settings -> Service Connections -> User Role (going back it shows Role as Creator with Inherited Access

 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Accelerator Version: 1.0.20230606.1

**Comment by jfung85** [comment]
This doesn't seem to be an ALM Accelerator upgrade issue. Using the admin account, we are still able to complete the Commit Solution step under the upgraded app.

**Comment by mikefactorial** [comment]
Hi @jfung85,
Pardon the delay I was travelling last week. Unfortunately, the _scrubbedSensitiveData_ message is something that seems to have just recently cropped up in the platform and makes it difficult to debug issues like yours since it is masking the actual error. We've notified the product team about this specific problem and have a workaround for it in the July release. In the meantime without the error message is hard to know what specifically is the problem here.

A couple of things to check.
1. I assume that the export pipeline just doesn't start at all in DevOps when you get this error so there's no errors on the DevOps side that would be useful.
2. What happens if you try running a previous export from Azure DevOps with this specific user (i.e. run the export manually from Azure DevOps with the new user). Is the user allowed to run the pipeline? Does the pipeline start or does it throw an error immediately when trying to run?

**Comment by jfung85** [comment]
Hi @mikefactorial, after some additional testing, we noticed that the non-admin account we were using had Stakeholder access to the Azure DevOps Organization. I updated this to Basic User and that looks to have resolved this issue. We will look forward to the update that will allow us to see specific error messages. But I think we are good for this particular issue.
