### ISSUE TITLE
[CoE Starter Kit - BUG]: Sync flow issue

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/coe-starter-kit#592]
**Describe the bug**
Hello, I need help with troubleshooting an issue with a couple of sync flows related to the core components solution.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 2.0.10
 - App or Flow - Admin | Sync Template v3 (Apps) and Admin | Sync Template v3 (RPA)

**To Reproduce**
The starter kit sends a daily notification email advising which sync flows have failed in the last 24 hours.

**Expected behavior**
There should be no sync flows errors reported in the daily email.

**Screenshots**
Refer to the attached screenshots and text files which show the full error message for the two sync flows with an issue:

[Admin - Sync Template v3 (RPA).txt](https://github.com/microsoft/coe-starter-kit/files/6622304/Admin.-.Sync.Template.v3.RPA.txt)
[Admin - Sync Template v3 (Apps).txt](https://github.com/microsoft/coe-starter-kit/files/6622305/Admin.-.Sync.Template.v3.Apps.txt)
![Admin - Sync Template v3 (RPA) screenshot](https://user-images.githubusercontent.com/62425530/121321476-0b35e400-c906-11eb-89af-48a7c91252a4.PNG)
![Admin - Sync Template v3 (Apps) screenshot](https://user-images.githubusercontent.com/62425530/121321487-0c671100-c906-11eb-9022-2f5ace96a584.PNG)

**Comment by JeneferM-MSFT** [comment]
It looks like you are on an old version of Core. 

The second issue (related to CDS Native Connector) is known and fixed in newer versions. 

The first issue (status code form Get profile call) looks like a case where we had missed the configure run after on that switch statement. I have validated that is correctly set in the latest release. Note that this flow has also been renamed so you upgrade you will see it as **_Admin | Sync Template v3 (Desktop flows)_**

Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not removed the unmanaged layers as described there you will not receive updates from us.  

Thanks for using CoE
