### ISSUE TITLE
[CoE Starter Kit - BUG] Issue when turning on the flow "HELPER - CloudFlowOperations"

### ISSUE THREAD

**Issue by VimmiRawat** [microsoft/coe-starter-kit#5928]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I could see this bug is already reported but it was for below flow
"CLEANUP - Admin | Sync Template v3 (Check Deleted)

We are following https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows

While turning "Helper- CloudFlowOpertaions" ; it is failing with below

Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is 'fae19797-0f3b-4151-a24b-992e38b2afd6'. Connection '/providers/Microsoft.PowerApps/apis/shared_office365users/connections/0193337191b24eb196ac44abeb84726f' to 'shared_office365users' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".

When I try to set run-onlu user property as mentioned here https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#set-flow-run-only-users-properties

<img width="271" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/62638075/a97bc2cf-92c9-4944-9ffd-6be86c869502">

Still get error 

Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id '9301f01a-cb40-ec11-8c62-00224829b4c1' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}". Code: 0x80060467 InnerError: '.

### Expected Behavior

It should let us turn on the flow after Run-only user property is set.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

HELPER - CloudFlowOperations

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Production Environment
Go to solutions -> Coe core component 4.2
Go to cloud flows
select :HELPER - CloudFlowOperations" and try to turn on 
Error- Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is 'fae19797-0f3b-4151-a24b-992e38b2afd6'. Connection '/providers/Microsoft.PowerApps/apis/shared_office365users/connections/0193337191b24eb196ac44abeb84726f' to 'shared_office365users' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".

Try to set Run-as only user property , error while doing that ( Microsoft Dataverse as blank and Microsoft Dataverse Legacy as run-only or use this connection but error in both the cases )

Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id '9301f01a-cb40-ec11-8c62-00224829b4c1' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}". Code: 0x80060467 InnerError: '.

<img width="344" alt="error" src="https://github.com/microsoft/coe-starter-kit/assets/62638075/ea6ee0f9-7727-44ec-af6d-6bf053bdde6a">
<img width="304" alt="Run-only" src="https://github.com/microsoft/coe-starter-kit/assets/62638075/97dbe36d-cf18-4e0e-8e39-65c09a1362e4">

**Comment by VimmiRawat** [comment]
I have tried editing Run-Only user properties as mentioned in the article but getting the same error .  What do you mean by Typically if you delete and recreate the Dataverse connection, that resolves.? Can you share details how to fix this ?

**Comment by VimmiRawat** [comment]
I get the error for child flow "Helper- CloudFlowOpertaion" when editing run only users property :

![image](https://github.com/microsoft/coe-starter-kit/assets/62638075/9edfe32f-1065-4309-8d88-4b6a6534a360)

**Comment by Jenefer-Monroe** [comment]
This is a product bug not an issue with the kit. Here are some ways people found work arounds, it seems to have many causes and conditions so we cannot debug with you further if the below does not resolve.
1.	Simply turn on the flow. This fixes it for some folks. 
2.	Some folks fixed by having empty connection on start: https://github.com/microsoft/coe-starter-kit/issues/3820#issuecomment-1286479043

3.	I have fixed myself by fixing or recreating a connection
- Validate the connection shows as green on details page
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5426b478-8d6f-4866-9d5e-edce000f97ea)

- Browse to the connections page as the user shown and filter to dataverse. Validate that its green
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1eff39f9-6b49-4f3a-854a-7de70d94348b)

- Create a new dataverse connection as this user, now you will see two (or more)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc387351-bebf-456c-b133-d04a88292917)

- Go to solutions > Default Solutions > Connection References
Look up the connection reference from above > Edit > Chose the new connection
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598483f6-b5b6-44d1-9cc6-351d3798a34b)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
