### ISSUE TITLE
[CoE Starter Kit - QUESTION] Sync flows turned off

### ISSUE THREAD

**Issue by MichaelRoth42** [microsoft/coe-starter-kit#5945]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What can cause the sync flows to turn off?

I have this phenomenon on different tenants and with different versions. I didn't switch any sync flows off, yet somehow they are switched off (I'm talking about the general "Admin | Sync Template v4" ones, as well as all the others for specific products).

Is there anything like an amount of failed runs, a timeout or something that can cause the flow to turn off? Or can it be caused due to a password change of the owning account? 

I'm all out of ideas right now 😅

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v4

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

flows can become turned off for multiple reasons - if you look at the Flow Details page, do you see a warning/error there? What happens when you manually try and turn it on? Does the flow owner get any emails from Power Automate about this flow?

Here's a few reasons why flows get turned off:
- if they exceed the allowed API limits for a long period of time
- if they continuously fail for a long period of time
- if a DLP policy gets applied to the environment that blocks connectors
- if a new conditional access policy gets rolled out that blocks the user from signing in or that expired the sign in token
- potentially if the account running the flow has the auth token revoked - I'm not sure on the details here but worth checking https://learn.microsoft.com/en-us/troubleshoot/power-platform/power-automate/conditional-access-and-multi-factor-authentication-in-flow
- if the required license gets unassigned from the user, and the flow can no longer be turned on as it's using premium features

**Comment by manuelap-msft** [comment]
I found this as well which contains a list of the limits on how long flows will remain turned on before they expire and get turned off.
https://learn.microsoft.com/en-us/power-automate/limits-and-config#retention-limits

**Comment by MichaelRoth42** [comment]
Ahh, that is interesting to know, thanks a bunch. I am not the owner of the connections behind the flows, therefore I can't test what happens if I switch them on manually.

**Comment by manuelap-msft** [comment]
You know where to find us if you need any further help :) 

I would say the typical two we see are
- DLP violation
- Billing policy violation (license assigned to the user but a service account owns the flow or something like that)

**Comment by MichaelRoth42** [comment]
Right now I think I will just upgrade to  the next version, if I still run into trouble I can't solve myself, I will reach out to you 🙂
