### ISSUE TITLE
[CoE Starter Kit - QUESTION] Error loading control bug in June 2023 version

### ISSUE THREAD

**Issue by jaehwanahn** [microsoft/coe-starter-kit#5946]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

During the June coffee hour session, it was mentioned that there was a bug in the initial setup wizard.

![ErrorLoadingControl](https://github.com/microsoft/coe-starter-kit/assets/22118813/046da6ee-7843-4ba8-91b4-240ff67640b5)

Do you plan to release a hotfix version for June? Can you also please advise whether this is a neglectable bug and won't impact other functionality?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023 (4.9)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
This was due to a product bug which has since been hotfixed.
In order to get their hotfix into your app, here is what you need to do. For any app where you are seeing these types of issues, you will need to republish the MDA for it. I have validated that this does not create an unmanaged layer so you will be good going forward as well.
1. Go to your CoE Environment > Apps
2. Edit the Model Driven App where you see this
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8a9d8808-b0e2-4da4-bfac-82601837c5f5)
3. Once in the MDA hit Publish and wait till publish completes
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2de49f4d-786d-4c3c-9920-7ab70c5c78b9)
4.	Now reopen the Model Driven App and the issue should be resolved.

**Comment by Jenefer-Monroe** [comment]
closing as a duplicate to the product issue for this.
