### ISSUE TITLE
[CoE Starter Kit - BUG] Authorization has been denied for this request.

### ISSUE THREAD

**Issue by joebeyer75** [microsoft/coe-starter-kit#5950]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

[Child] Admin | Sync Logs fails with following message: 

Authorization has been denied for this request.

Fails on the action: Audit Logs Scope > List Audit Log Content 

Status Code: 401

{
  "Message": "Authorization has been denied for this request."
}

{
  "Cache-Control": "no-cache",
  "Pragma": "no-cache",
  "X-AspNet-Version": "4.0.30319",
  "X-Powered-By": "ASP.NET",
  "x-ms-apihub-cached-response": "true",
  "x-ms-apihub-obo": "false",
  "WWW-Authenticate": "Bearer error=\"invalid_token\"",
  "Date": "Fri, 23 Jun 2023 17:42:13 GMT",
  "Content-Length": "61",
  "Content-Type": "application/json; charset=utf-8",
  "Expires": "-1"
}

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. Here are a few things to note. 

Audit logs are collected by a solution separate from Core as the setup for them requires additional permissions. Please see [Set up the audit log connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)

Audit logs begin to collect data from when they are turned on, they do not go back and get historical data.
They are based on a custom connector, and these have issues with upgrade and need to be fixed periodically as described here: https://github.com/microsoft/coe-starter-kit/issues/1424

Please validate that you have installed and setup the [audit log solution](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog) 

Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

A picture like this showing the API permissions are set correctly
![image](https://user-images.githubusercontent.com/89584709/225952426-74897c8e-4190-40e2-a91a-681f66a46d3d.png) 

Make sure you used the secret value as well and not its GUID. Thats something people do farely often
![image](https://user-images.githubusercontent.com/89584709/225953435-8d2d5b8c-1fdd-4e24-92c0-e4618c23f1fa.png)

A picture like this showing if the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png) 

A picture like this showing if the data is populating
![image](https://user-images.githubusercontent.com/89584709/164469099-1cb27bec-a1b8-4a22-8b2c-c9bdb50d7d33.png)

**Comment by joebeyer75** [comment]
When I go through the custom connector set up, I get the Status 400

{
  "error": {
    "code": "AF20024",
    "message": "The subscription is already enabled. No property change."
  }
}

**Comment by Jenefer-Monroe** [comment]
Thats totally fine. 

Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

A picture like this showing the API permissions are set correctly
![image](https://user-images.githubusercontent.com/89584709/225952426-74897c8e-4190-40e2-a91a-681f66a46d3d.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
