### ISSUE TITLE
[CoE Starter Kit - QUESTION] Add new E-Mails to the Customized E-Mails section

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#5980]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Team!

I´m working on a use case where I would like to re-use your concept of custom E-Mails and I was wondering, if there´s a supported way to add new E-Mail templates to the table.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
It is not, we remove mails that haven't been modified recently so that we can remove mails from the solution. 
If you add them, you could add another flow that touched the record each day so that it appears to not be modified recently when that flow gets called. Kind of a hassle but I believe that would work.

**Comment by DominicMeznik** [comment]
Understood! I´ll take a look at it. Thank you! :)
