### ISSUE TITLE
[ALM Accelerator - BUG]: Error in CustomAzureDevOps.

### ISSUE THREAD

**Issue by will-franca** [microsoft/coe-starter-kit#6007]
### Describe the issue

I am not able to create the connection in CustomAzureDevOps. Follow the problem screen.

![image](https://github.com/microsoft/coe-starter-kit/assets/135626493/765442a8-10ac-4bde-94de-ae1d725af30c)

In my scenario I have dynamics in tenant and azure devops is in another tenant. I created app registration in both tenants, I'm putting the client id of the azure devops tenant's app registration in the connection.

### Expected Behavior

connection created successfully

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20221206.2

**Comment by mikefactorial** [comment]
@will-franca unfortunately the cross-tenant scenario is not supported with the ALM Accelerator today due to limitations in how custom connectors work in the platform. We've done some investigation into how to enable this scenario, but don't have a solution for it today. I'm going to close out this issue and refer you to this existing feature request to add your input and vote it up https://github.com/microsoft/coe-starter-kit/issues/3946

**Comment by will-franca** [comment]
> @mikefactorial 

But, before that I could connect using app registration. I did this in version 1.0.20221206.2, what happened? Did you change the connector?

**Comment by mikefactorial** [comment]
@will-franca there hasn't been any change and custom connectors have never worked across tenants. You can absolutely use our pipelines across tenants but the app will not work across tenants.
