### ISSUE TITLE
[CoE Starter Kit - QUESTION] This exceeded the maximum size 'xx' bytes allowed. issue for Connection Identities

### ISSUE THREAD

**Issue by BenGillard1987** [microsoft/coe-starter-kit#6013]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

![image](https://github.com/microsoft/coe-starter-kit/assets/116280908/50f4f1e4-b320-48b5-958a-8eca46b5edd2)

This error occurs twice every day but all other runs are successful. No unmanaged layers.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
The CoE kit is built on top of the product, and as such bound to platform limitations. 
This failure is due to a limitation on the amount of data connectors can bring back, which unfortunately, you have exceeded. 
Note also that deleting individual flows and apps will not delete the connections they use, so they do pile up over time and deleting objects does not 

We cannot fix that, nor can we safely create a script which will reliably connections safely for all tenants that will work over time. 

Here are some things you can do to address:
1. Manually use powershell to [explore](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) unused or errored connections. That technology does not have this same size limitation.
2. Contact [product support](https://learn.microsoft.com/power-platform/admin/get-help-support) to have them help you clean up old connections

Hope that helps, and sorry for the inconvenience.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
