### ISSUE TITLE
[CoE Starter Kit - HOWTO] Maintain custom connector methodology to gather audit logs after deprecation

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#6017]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

If you are unable to use the new [Http methodology to collect audit logs](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http) and instead need to maintain the old [custom connector methodology](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog), you will need to preserve a copy of the custom connector locally in your tenant as it will no longer be released with the Core components. 
This write up is intended to walk you through how to do this. 

### Note Env Var values
Go to the Admin Command Center and get the current values for all these env vars
If they are marked as customized, store them in a notepad as you will make sure to re-enter them later
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8c2d8bd1-17fb-4c2d-9136-e15499ee0ae5)

### Delete old solution
Delete the **_Center of Excellence - Audit Logs_** solution from the environment. Don't worry, the data is stored in a table in Core and so you wont be losing data by deleting it.

### Import the new Custom Connector
Import this solution into your CoE Environment. It contains only a copy of the custom connector.
[NewAuditLogCC_1_0_0_1.zip](https://github.com/microsoft/coe-starter-kit/files/11971475/NewAuditLogCC_1_0_0_1.zip)

### Setup new Custom Connector
Update the security information for the new custom connector, just as you used to for the old one.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cfc6c3dd-9899-4c37-8d1b-d608a08d8d8d)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66ac1914-972c-4f7a-8c77-46ade5ca27f6)

### Create connection to new Custom Connector
Create a connection, if it does not work in this UX sometimes you have to refresh the page or go to the connections page itself and try there.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9c79a294-3bb2-4e52-935d-22d5b69dcfb9)

### Import the rest of the new Audit Logs by CC Solution
[NewAuditLogSolution_1_0_0_3.zip](https://github.com/microsoft/coe-starter-kit/files/11971689/NewAuditLogSolution_1_0_0_3.zip)

### Validate Env vars
Go to the Default Solution and validate or update the values in your env vars from above
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/34802c12-3db4-4dec-8d5f-edabc68c34f4)

### Turn on the flows
Back in the New Audit Log Solution, turn on **_New | [Child] Admin | Sync Logs_**
Next turn on **_New | Admin | Sync Audit Logs_**

### Validate the run
**_New | Admin | Sync Audit Logs_** flow should have run when you turned it on, but if not, please run. It should now run and pass, and you are now safe from us removing the CC later

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

audit logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by bhupendra14** [comment]
**### Validate the run **

** New | Admin | Sync Audit Logs flow should have run when you turned it on, but if not, please run. It should now run and pass, and you are now safe from us removing the CC later.**

Can someone help me to understand which on to remove, as mentioned in above line ( CC ??? ) ??

Thanks in advance.

**Comment by Jenefer-Monroe** [comment]
That was referencing something we would remove not you. The steps above have this step where you delete the old audit logs solution. If you share a screenshot of what you are struggling to decide if you should delete or not I can let you know.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/046ff20c-a61d-4504-bdec-e145c03f16e1)

**Comment by bhupendra14** [comment]
> That was referencing something we would remove not you. The steps above have this step where you delete the old audit logs solution. If you share a screenshot of what you are struggling to decide if you should delete or not I can let you know. ![image](https://user-images.githubusercontent.com/89584709/265989017-046ff20c-a61d-4504-bdec-e145c03f16e1.png)

okay got it now. Thanks for the response.

**Comment by JanetK12** [comment]
Hello!
Could I we the question: 
For now we are unable to use the new Http methodology to collect audit logs and instead we need to maintain the old custom connector methodology, and as we understood we will need to preserve a copy of the custom connector locally in our tenant as it will no longer be released with the Core components.
Because of that we had some questions to understand and confirm the correct sequence of upgrading the solutions. Usually we updated solutions in this sequence:
1. Core components
2. Audit Components
3. **Audit Logs**
4. Nurture Components

Do we need to do it that way (in this sequence) this time as well? So that the Audit Logs solution will be upgraded (as explained in this #6017 writing) only as the third solution.
Or the first thing that needs to be mandatory done is the **maintenance the old custom connector methodology** as you explained in this #6017 writing? And only after we can procced with the Core components, Audit Components and Nurture Components solutions upgrade?
We thought it is imported to confirm this before the actual upgrade, so that we won't ruin anything.
Thank you in advance!
