### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to create a connection for custom connector CustomAzureDevOps.

### ISSUE THREAD

**Issue by Pavan19971** [microsoft/coe-starter-kit#6025]
### Describe the issue

Unable to create a connection for custom connector CustomAzureDevOps.

What was tried:
1. Configure devops connector using this link https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks.
2. Click update connector
3.  Click new connection-> choose my ad profile
4. No connection created and no error whatsoever

### Expected Behavior

The AzureAD login window popups and a connection is created

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20230606.1

### Steps To Reproduce

1. Import CenterofExcellenceALMAccelerator_1.0.20230606.1_managed solution
2. Import CenterofExcellenceALMAccelerator_1.0.20230606.1_managed solution
3.  Create app registration
4.  Change custom connector security

https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks

### Anything else?

There is no error except in the browser console regarding CORS

**Comment by mikefactorial** [comment]
@Pavan19971 not sure I can troubleshoot this on my end without more information. Are you able to create connections for other custom connectors in the same environment? Are you sure the connection wasn't created? If you are creating the connection from the custom connector's test page it will often land you on the connections page and not redirect you back to the test page so you'll have to navigate back.

**Comment by ptdominey** [comment]
Hi
I am having a similar issue.  I notice if I click "Swagger Editor" on the Security page it gives an error message

 "Semantic error at paths./{organization}/{project}/_apis/git/repositories/{repo}/items
Equivalent paths are not allowed."

I don't know if this has any bearing on the issue.  

When I fill in the Client Secret and other information it says it is saving them but the fields do not appear to be populated on the page.

When I go to tesst the connection it pops up a signing-in window but when I click on my account the window just disappears and nothing happens

I suspect this is a Microsoft issue rather than something to do with the ALM Accelerator itself but I just wondered if someone could point me in the right direction to get it fixed

**Comment by ptdominey** [comment]
I tried creating a Logic Apps Custom Connector using the same information and that did not work either.  Then I tried doing it all again in my own AAD tenant in case there were some restrictions in our corporate one and got the same result

**Comment by mikefactorial** [comment]
Closing this out as there hasn't been any response in several months.
