### ISSUE TITLE
[ALM Accelerator - QUESTION] Error Running Pipeline

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#6029]
### What is your question?

Hi Mike,

I am trying  to setup ALM pipeline for already existing DevOps Project. I was able to import ALM Pipeline templates and created profile. But when I "Commit Solution"  it is giving "Error running pipeline" error. Any insight?

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/c9fd2978-1e49-4d1b-8839-3033bb2f30fa)

Here is Our DevOps Project.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/9cb9ab94-24e5-4ece-a11f-f07cf270ff67)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by lingutla123** [comment]
Mike,
 I upgraded to latest ALM Accelerator(July upgrade). As soon as I commit, getting the error. Not giving any option to see the pipeline execution steps and log.

Thank you!

**Comment by mikefactorial** [comment]
@lingutla123 you may want to try running the export pipeline manually from Azure DevOps just to see if there's any specific error with the pipeline itself. Similar to the following. Obviously, this won't likely succeed but it may let us know what the problem is since the app is failing when attempting to run the pipeline which leads me to believe there could be something wrong with the pipeline itself.


![Image](https://github.com/microsoft/coe-starter-kit/assets/42348035/5a9cb22c-8b35-4fa1-a8be-664e39183eec)

**Comment by lingutla123** [comment]
Mike,

For already existing DevOps projects we need add below pipelines,  Service connections and  Variable group.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/5e7a9cfa-6fc0-4a46-bee3-f343e7d33730)

I was able to commit the solution. But in Repo it is showing only feature/branch. It is not showing other solution branch.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/fed4e931-5888-4168-ac99-5fbac29fbafd)

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/d5ba59c5-1b5f-4a25-b01c-f367861d2e43)

**Comment by mikefactorial** [comment]
@lingutla123 in some cases there can be errors in the Update Deployment Settings that create the deployment pipelines that don't necessarily show as errors in the export pipeline execution. Might help to search the logs (specifically Update Deployment Settings step) for error messages. If you want to share the logs we can take a look as well.

**Comment by lingutla123** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/dbb0d3d5-d748-4290-b9d7-121f7c5a6df6)

**Comment by mikefactorial** [comment]
@lingutla123 since this is an existing project you'll need to configure some permissions for the Build Service to access resources it needs to create and update pipelines. The follow has instructions for setting those permissions including giving access to the queues available in the project (#8 and #9 in the list) which is what the error above is telling us. Would recommend verifying all of the permissions listed. https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#update-permissions-for-the-project-build-service

**Comment by lingutla123** [comment]
Hi Mike,

I was able to deploy the solution from Dev to QA to TST. I added Service Connection "Project Collection Build Service" security, Agent Pool security permission, Pipelines security Permission and Repositories security permission.  

Thank You.

**Comment by mikefactorial** [comment]
Great to hear! Thanks for following up and including the steps you took. Will surely help someone else in the future.
