### ISSUE TITLE
[CoE Starter Kit - BUG]: Unable to search by environment in the DLP Editor V2 canvas app

### ISSUE THREAD

**Issue by marcster** [microsoft/coe-starter-kit#605]
**Describe the bug**
On the environments page of the DLP Editor V2 canvas app, you are unable to search by environment name.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 -2.1.70
 - DLP Editor V2

**To Reproduce**
1. Open the DLP Editor V2 app
2. Navigate to the environments page
3. Enter an environment name in the search box on the page
4. The items in the gallery are not filtered

**Expected behavior**
Ability to search for an environment using the search box

**Screenshots**
N/A

**Additional context**
N/A

**Comment by JeneferM-MSFT** [comment]
Can you please share screenshots of what you are seeing? Because this does not repro for me. 
Have you tried with multiple environments? And have you validated that your test case has just 1 or a few DLP policies impacting? 
![image](https://user-images.githubusercontent.com/62659043/121529062-46451f80-c9b9-11eb-91d7-1a35f5c069af.png)
![image](https://user-images.githubusercontent.com/62659043/121529275-7db3cc00-c9b9-11eb-83a9-fdfba4eb6f66.png)

**Comment by albertocaa1317** [comment]
Hi Jenefer,
today I have this same issue. The combo doesn't show any enviroment:

![image](https://user-images.githubusercontent.com/57954993/121650077-8085ee00-ca99-11eb-89f0-287b9d6985d8.png)

And I have two DLPs configured and they isn't showing either
![image](https://user-images.githubusercontent.com/57954993/121650310-ba56f480-ca99-11eb-8e77-276cb7f9e756.png)

In my case, yesterday was working. And the only change that I made was update the core components with the PR 2.1.72 proposed in the issue #603

**Comment by JeneferM-MSFT** [comment]
Albert, your is likely a separate issue as my coutnerpart was working on this app. Apologies, I didnt know she was doing that when I gave you a PR. I'll give you a new PR once she'd done working. I am going to delete your comment as I believe you are seeing a different issue that the original poster. And my counterpart is fixing.

**Comment by JeneferM-MSFT** [comment]
Marc. My counterpart believes you were seeing the envt not work on a different page than the one I showed in my screenshots. Can you confirm and show images going forward to assist us? 
Assigning to her as she is investigating.

**Comment by marcster** [comment]
Thanks @JeneferM-MSFT for the update. My issue is around the page where you can add the environments to the DLP policy. Unable to search by environment name. I think this is due to the fact that the environment name is not part of the collection and so unable to filter on this.


![image](https://user-images.githubusercontent.com/1025102/121698962-6d3d4780-cac6-11eb-8fc0-df44bc80135a.png)

**Comment by manuelap-msft** [comment]
Thanks for confirming! I was able to repo that yesterday, and fixed it - it will be part of our July release.

Thanks for helping make the CoE great by providing this feedback!

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
