### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template V4 (Apps and Flows) looking for child flows that dont exist

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6063]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

What child flow should be here and if you know what might have caused this during the upgrade? 

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/ce67c007-dc6b-4753-84da-cb315abe5162)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/34afa259-41b5-4b4b-8332-f16c35bd90e2)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template V4 (apps) and Admin | Sync Template V4 (flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
It's highly recommended that you use the setup wizard for upgrades as it will make it unnecessary for you to keep track of new flows that need turned on, since the app will turn them on for you. If you cannot use the setup wizard then you need to refer to the documentation when doing upgrades. 

In this case you will find that there are new [child flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows) that need enabled. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/170e3b2a-95f1-4c3f-8bc3-0afa9ac13724)

**Comment by mdphung** [comment]
Thanks, I will go back around with the team and see if they followed like normally would and see if I can get this resolved as I normally would use the wizard afterwards.

 [cid:74f24dab-79a3-4de2-9333-211f46c12f08] [cid:23895ffa-3b36-4cc2-b446-89cba74117e9] <http://www.truetandem.com/>
Corporate Headquarters
[cid:656708b9-198e-45a7-89de-2a0813ec3773]



Mai Phung
Sr. Project Manager

Email: ***@***.******@***.***>
Mobile: (571) 228-9123


“We are a trusted information technology solutions provider, committed to the success of our customers, communities and employees.”  www.truetandem.com<http://www.truetandem.com/>



________________________________

**Comment by mdphung** [comment]
These are for some reason not showing up at all on the list of cloud flows: 
16. Sync Helper | Apps
17. 16. Sync Helper | Cloud Flows

Is there a way to fix this as it almost seems like they did not install  as part of the installation upgrade?

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names. This will help us understand if an error occurred on upgrade.
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)
