### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flows) is failed because "List flows as admin" returns some not existing flows 

### ISSUE THREAD

**Issue by NadinkaRozh** [microsoft/coe-starter-kit#6067]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We noticed that on Default env this flow always fails with 1 the same flow. This fail always appers in action "Get flow as Admin" with error "Flow not found". I've checked everething anf found, that "List flows as Admin" return this flow in a list. However, this flow doen't exist in a Flow table, I've checked this flow using other PA management actions, but they all said that this flow doen't exist. 

![image](https://github.com/microsoft/coe-starter-kit/assets/116064443/3d9b8cf6-395c-4920-a2a2-383981373443)

### Expected Behavior

The "List flows as admin" should return only existing flows in env. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Create flow 
2. Add action "List flows as admin(V2) 
3. Add "Get flow as admin" after that 

But issue with this flows still appears. The account has PP admin role and doen;t have issues with ithers flows.

**Comment by Jenefer-Monroe** [comment]
Hello you have hit a product bug here in which the list flows function is returning a flow that the get flow will not return. 

You will need to [contact support](https://learn.microsoft.com/en-us/power-platform/admin/get-help-support) to have them clean this up in order to have this flow start passing.  
 
Our recommendation is to first get a repro outside of the toolkit before contacting support. You can use the below flow to get a simple repro.  
 
To use: Import the flow, open, select the environment which repros for you, turn on and run. 
It loops the flows, will hit the same failure and then you can go to support with this flow instead of the toolkit, for faster iteration to fix.  
Flow to import: [ProductBugDemo-getflowaftergetflowsfails.zip](https://github.com/microsoft/coe-starter-kit/files/12039511/ProductBugDemo-getflowaftergetflowsfails.zip)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3680adf-ea19-4eb1-aa18-73f5a0590ad4)

To import flows, browse to https://flow.microsoft.com/ > Select environment where you want to import.
My flows > Import > Import Package (Legacy) and walk through the import UX. Let us know if you need help there.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ee84f6c3-ecd6-4e55-9561-e3196267944b)

**Comment by manuelap-msft** [comment]
Closing out as no further action required from CoE team.
