### ISSUE TITLE
[CoE Starter Kit - QUESTION] audit logs broken after upgrade

### ISSUE THREAD

**Issue by SyedSecurian** [microsoft/coe-starter-kit#6085]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The CoE kit Sync Flow for Audit Logs is failing after the June 2023 upgrade. We have followed all the steps as per the documentation and was successfully able to update. But the sync flow keeps failing every day. 

### What solution are you experiencing the issue with?

Audit Log

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please share screenshots of your failure.

**Comment by SyedSecurian** [comment]
> Please share screenshots of your failure.
![2023-07-17_16-33-57](https://github.com/microsoft/coe-starter-kit/assets/139806493/59a7d1a5-c655-4afb-8ef3-d038aeb9cd12)

**Comment by Jenefer-Monroe** [comment]
ok this means the child flow isnt on, likely because the custom connector was not fixed up on upgrade

Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

If that does not resolve, then you likely ended up with a bad connection, perhaps due to the wrong identity provider being selected as in [issue 4808](https://github.com/microsoft/coe-starter-kit/issues/4808)

If that occurs please try the steps outlined in [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

**Comment by Jenefer-Monroe** [comment]
Please note also that we are deprecating the custom connector methodology to collect audit logs due to issues like this. 
It is recommended that you [convert audit logs from custom connector to http format](https://github.com/microsoft/coe-starter-kit/issues/6009)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
