### ISSUE TITLE
Inactivity process also picking up active scheduled flow

### ISSUE THREAD

**Issue by yveskerwyn** [microsoft/coe-starter-kit#6094]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We notice that actively running **scheduled** flows that have been last modified at least  6 months ago are also identified as inactive flows, which doesn't make sense to us. 

Is this by design?

Shouldn't scheduled flows that are actively running not be identified as active flows instead?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

App and Flow Inactivity Notification Clean Up View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

that is by design. Flow Usage data is not available programmatically if you're using cloud flows for inventory and usage information. 

You can exclude environments from the Inactivity process if you have managed production environments where you know flows are running well even if they are not being modified. This is a setting on the environment in the Power Platform Admin View
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#exempt-environments-from-the-inactivity-notifications-process

Flow Usage is available if using Data Export to get inventory and usage, and we do have a backlog item to change the process to take the flow usage date into consideration. This will only work if your inventory source is Data Export.
https://github.com/microsoft/coe-starter-kit/issues/4996
