### ISSUE TITLE
[CoE Starter Kit - QUESTION] Best approach on re-install

### ISSUE THREAD

**Issue by Pyksel** [microsoft/coe-starter-kit#6126]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Due to issues not within our control, the version of our CoE kit is well outdated (June 2022) but still functional. We are aware that we can not upgrade in place so my question is how to best approach this?

Do we spin up a new production environment or is there a way to re-install into the existing environment? 

Any gotcha's we need to be aware of on the new install vs. our previous working version?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2022

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
What all solutions do you use? Do you use more than just Core?
A screenshot with what solutions you have installed in this environment would help us know.
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Pyksel** [comment]
Jenefer, thank you for responding so quickly! I am unable to post screenshots of the environment due to our governance policies. What I can tell you is that we do not have the Creator Kit deployed and while we do share an identical list of Solution names, there are of course, differences in versions. I can certainly list out the versions we have if necessary.

**Comment by Jenefer-Monroe** [comment]
No problem, I mostly just wanted to know if you had Gov/Nurture/Audit Logs installed. It sounds like you do. 

A few things to suggest:
- You will need to install creator kit before you can install the latest version of the kit, I think the dependency started in ~February. 
- Audit Logs solution is being deprecated in favor of a much better method. Please take a look: https://github.com/microsoft/coe-starter-kit/issues/6009
- You can try upgrading as follows, it may work you.
1. August 2022 core
2. August 2022 (rest of the solutions)
3. Oct 2022 core 
4. Oct 2022 (rest of solutions)

-- if you get this far you can probably upgrade then directly to July 2023. We've been testing back further than ususl due to an upcoming mandatory upgrade.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
