### ISSUE TITLE
[BUG]: Problem trying to Activate the sync template flows

### ISSUE THREAD

**Issue by snl-meg** [microsoft/coe-starter-kit#613]
I am attempting to activate the CLEANUP - Admin | Sync Template v3 (Check Deleted) flow. I receive the following error 

![image](https://user-images.githubusercontent.com/85708566/121593747-d9a24300-ca01-11eb-96e6-5e031b979505.png)

 - Solution: Core
 - Version: v1.89]
 - App or Flow:  CLEANUP - Admin | Sync Template v3 (Check Deleted) 

**To Reproduce**
1. make.powerapps.com
2. Click on Solutions
3. Select default solution to manage
4. Select CLEANUP - Admin | Sync Template v3 (Check Deleted) and click on ..., turn on and error appears.

**Expected behavior**
Flow turns on

**Comment by JeneferM-MSFT** [comment]
Hello. All the flows have this pagination policy. It indicates that you are using an insufficient or trial license. 

Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes. 

See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles) 

And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits) 

And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).
