### ISSUE TITLE
[CoE Starter Kit - BUG] Data not pulling through for Desktop flows

### ISSUE THREAD

**Issue by hrsharmafederation** [microsoft/coe-starter-kit#6174]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The COE started kit is installed successfully and pulling data on dashboard for power apps c cloud flow etc. but it is not pulling data for desktop flows. Cloud flows responsible for pulling through the data are running successfully. However, data does not pull through in dashboard on Desktop Flow run details and Desktop Flow errors tab on the production dashboard.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop Flow - Runs) Admin | Sync Template v3 (Desktop flows)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

On power BI dashboard, no data available in Desktop Flow run details and Desktop Flow errors tabs

**Comment by Jenefer-Monroe** [comment]
Hello. There are several limitation in the CoE Starter Kit with gathering Desktop Flows due to some tooling limitations in our architecture, but the good news is that we do have an entire kit and small team devoted to Desktop Flows
The recommendation is to use that tooling and team for deep questions around this feature area. 
https://learn.microsoft.com/power-automate/guidance/automation-kit/overview/introduction

**Comment by Jenefer-Monroe** [comment]
We do have plans to get basic inventory here more sorted but are blocked by a product change. Then you would be able to us for basic inventory and the automation kit for deep dives.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
