### ISSUE TITLE
[CoE Starter Kit - BUG]: Unable to update the CenterofExcellenceAuditLogs_1_41_managed solution from the latest release

### ISSUE THREAD

**Issue by gsknbabu** [microsoft/coe-starter-kit#622]
Unable to update the CenterofExcellenceAuditLogs_1_41_managed solution solution from the latest release

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : CenterofExcellenceAuditLogs_1_41_managed
 - Version 1.41

**To Reproduce**
1. Download the latest CoEStarterKit from https://aka.ms/coestarterkitdownload
2. Unzip the CoEStarterKit zip file
3. Navigate to the Solutions
4. Click on Import
5. Browse and Select CenterofExcellenceAuditLogs_1_41_managed.zip
6. Click on Next
6. Error **There are missing dependencies. Install the following solutions before installing this one: "Active"**.
 

**Expected behavior**
Solution should display the Connection References and proceed to update the selected solution to the environment

**Screenshots**
![image](https://user-images.githubusercontent.com/2226547/121994425-e1c3ff00-cdc2-11eb-99e0-72df9aea206c.png)

**Additional context**
The size of the CenterofExcellenceAuditLogs_1_41_managed.zip file is only 8KB and when try to download the individual component, CenterofExcellenceAuditLogs_1_41_managed.zip file is having the contents of CenterofExcellenceCoreComponentsTeams solution in the metadata.

**Comment by JeneferM-MSFT** [comment]
Hello, in the future you need to get us the details in order to debug these. "Active" is just a placeholder. 

However for this one, I believe you are updating from a very old version and the connecter was moved. Here is what to try

- Upgrade Core first following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.  
- Then update Audit Logs following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). 

If this still does not work, do to the age of your old audit logs solution, you may need to just delete that managed solution and re-install. The data is all stored in Core so you will not lose anything here. 

Thanks for using CoE
