### ISSUE TITLE
[CoE Starter Kit - BUG] Flow fails Audit log Subscription

### ISSUE THREAD

**Issue by MadhanKannathasan** [microsoft/coe-starter-kit#6240]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team, 

When we run the flow with start operation, encountering internal server error in the start subscription. The tracking I'd is xxxxx

### Expected Behavior

The flow needs to run successfully so that  we can configure audit logs

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin Audit logs office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by MadhanKannathasan** [comment]
Plain text

**Comment by Jenefer-Monroe** [comment]
Open the last attempted run for Admin | Audit Logs | Office 365 Management API Subscription
Is the app id correctly ingested here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/97eee119-aae8-4b4e-95f4-2f5e6bd49feb)
Is the secret correctly ingested here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9783b8d9-4ddb-40d7-928f-eeeeb9c1145a)
Does this call fail hence correctly marking the variable as false?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0da62240-6cef-42b5-96fd-6b8bea57cb48)

**Comment by MadhanKannathasan** [comment]
1.Yes secret key correctly Ingested there. 
2. Secret_Azuretype is false also 

But getting internal server error in the start subscription

**Comment by MadhanKannathasan** [comment]
Appid also ingested correctly

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of your App Registrations API Permissions? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d204b547-ed03-441e-a794-d4dd56280c2f)

**Comment by MadhanKannathasan** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/47215546/e97052c4-44e7-4b41-b6c2-54b58d71fc54)

**Comment by Jenefer-Monroe** [comment]
Plesae share a screenshot of the failure so that we can see where in the flow it is failing.

**Comment by MadhanKannathasan** [comment]
Commercial tenant

**Comment by MadhanKannathasan** [comment]
Yes validated

**Comment by Jenefer-Monroe** [comment]
I'm at a loss then. You have checked that: 

- You have the correct app registration
- You have set up the env vars correctly
- The env vars are being ingested correctly
- You are a commercial tenant so nothing special to do there.


There must be something wrong with the configuration that I cannot see since I am not able to debug with you. 
Here are things I've seen before after working through this process with people here:
1. People enter the wrong values when they are working in multiple tenants (ex add app secret from tenant 1 into tenant 2's env var)
2. People enter the secret GUID and not the secret value when they add it to the env var

If that advice does not do it, you may need to seek out some assistance locally from a Power Platform champion in your organization or by hiring out a partner. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

**Comment by MadhanKannathasan** [comment]
After updating latest release of aug month the flow executes successfully

**Comment by Jenefer-Monroe** [comment]
oh wonderful news! I'm so glad to hear that. 
I'll go ahead and close this out then.
