### ISSUE TITLE
[CoE Starter Kit - BUG] Duplicate solutions CoE Core

### ISSUE THREAD

**Issue by mdlister** [microsoft/coe-starter-kit#6264]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When following the upgrade core solution documentation, it detects that we have4.11 installed and prompts to upgrade to 4.13 August release. After the upgrade is complete it creates a new solution. 

![image](https://github.com/microsoft/coe-starter-kit/assets/38280500/2cb5df09-08e1-4cb9-b585-1498540c9231)

We've been upgrading every release and never had this problem before?  

### Expected Behavior

Core Components App gets updated to 4.13 and not a new app created. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.13

### What app or flow are you having the issue with?

Solution

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

following: https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#importing-the-new-solution-version

1. Import the solution
2. Select Upgrade (default setting)

**Comment by mdlister** [comment]
Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 5 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-xxxxxx-xxxxxxxxx, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Deprecated | [Child] Admin | Sync Logs, Id: 751183fc-de4da0c8-bd02-xxxxxx-xxxxxxxxx, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-de4da0c8-bd02-xxxxxx-xxxxxxxxx, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details:

Looks like there is a dependany I need to find and delete.

**Comment by mdlister** [comment]
seems to be linked https://github.com/microsoft/coe-starter-kit/issues/3782 will close this and recreate the environment.

**Comment by federicoruiz** [comment]
Same issue here, we couldn't upgrade to the last version of Core Componentes, and we couldn't delete the old solution too. when Audit Logs components was already deleted.

Solved removing the Connector Reference from Dynamics:
1- Go to the Default Solution and then Change to Classic Mode. 
2- In Components, select Connector References.
3- Try to find the reference that use the Custom Connector and delete.

In classic mode, we couldn't find the dependencies, and the connection reference doesn't appear.

**Comment by mdlister** [comment]
Ditto, we resolved it through a support call with MS doing the same going to dynamics views and removing the reference and trying again.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DataChopsticks** [comment]
Hi, I am going through the same issue.
I have some connection reference somewhere to the Microsoft 365 Management API and because of that the July 4.11 is not getting uninstalled even though 4.13 (Aug) is gets installed.

The error I am getting is this - "{"error":{"code":"CannotDeleteApiDueToExistingConnections","message":"The custom connector admin-5foffice-20365-20management-20api-5fdcc2a89d3e8f5a72 cannot be deleted because there are connections associated with this api."}}"

Audit Log solution has been deleted already from the environement. There are 36 connection references in the default solutions under classic view but I don't know how to figure out which one is the culprit. Any suggestions on how to find that out?
It would be greatly appreciated if anyone can help me!!!

Thanks
Sangeet
