### ISSUE TITLE
[ALM Accelerator - BUG]: Custom Connector Response Type Mismatch

### ISSUE THREAD

**Issue by MKUltraCSA** [microsoft/coe-starter-kit#6271]
### Describe the issue

Downloaded latest version to go through install. Ran into repeatable issue with the custom connector. Connection created fine as did the security entry. Went to test get organizations as described in the tutorial, ran into a schema validation issue. Tried Monday with the version from last months CoE package with the green custom connector icon and it worked just fine. This one was orange and has failed in 2 separate tenants. All tests came back with response 200, in one tenant the response body was empty the other it wasnt, both had a schema validation issue. "Property ""type mismatch, Expected: "object", Actual: "array". Unsure how this will effect performance of Accelerator application, but I assume get orgs is needed for proper app functionality.
![MicrosoftTeams-image (39)](https://github.com/microsoft/coe-starter-kit/assets/141785636/f4cd5e65-5af7-4491-a179-4359102d0d0e)

### Expected Behavior

Get a 200 response and a valid schema

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20230802.1

### Steps To Reproduce

Clean install
Proper App registration with permissions
Insert correct security information
Test 'get organizations' after entering information

**Comment by mikefactorial** [comment]
@MKUltraCSA thanks for reporting this. You can safely ignore the type mismatch for now. We recently updated the apps to use a newer version of the AzDO API that requires memberId to be specified which it gets from the GetCurrentUserProfile operation. The legacy API returned an array instead of an object as you noticed and without the api-version and memberId specified it will revert to the legacy endpoint. If the operation is called with api-version 7.0 and the memberId parameter it returns the properly shaped result.
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/2de777dc-8d4a-4b27-b528-604efdbd283b)
