### ISSUE TITLE
[CoE Starter Kit - QUESTION] Adding custom columns to the Developer Compliance Center 

### ISSUE THREAD

**Issue by JDhdrinc** [microsoft/coe-starter-kit#6277]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We've created a few new columns to the PowerApps App table to collect more information for our compliance process.

I've been able to amend the Governance form, as per attached image,  
![New App Form Section](https://github.com/microsoft/coe-starter-kit/assets/139780772/dfe6fe8e-e208-493e-bd5e-ea85585783ef)

Is there a way I can customise the Developer Compliance Center so that these new columns exist in the 'Support details' form?
![Developer Compliance Center Support Details Form](https://github.com/microsoft/coe-starter-kit/assets/139780772/34a54391-2074-44f8-99f1-dd681fdf7028)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

you would have to modify these custom pages in the Governance components solution to add the fields there as well:
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/8e6a1d51-2664-4a7a-b6f3-30e45e053591)

Note that custom pages don't support merge behaviour, so by modifying them you create a fork to your own version of them. You'll then have to continue maintaining them, and will no longer receive updates from us if we make any changes to these pages. It is likely what you want, just wanted to highlight that!

**Comment by JDhdrinc** [comment]
Thank you for your response Manuela.

Just to clarify then, forms are different to pages?

On the Microsoft Learn page it says form merges are supported (https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components#customize-an-existing-form), so I thought it was a form I was editing, but good to know there is a difference that could have an impact.

If I create my own model driven app version of the Developer Center for our apps within our CoE extension solution rather than editing the existing pages, will that be a sufficient work around for us?

**Comment by manuelap-msft** [comment]
Hello,

In the Power Platform Admin View app, we're using model-driven app features such as views and forms. What you've modified so far is a Form and that supports merging.

The Developer Compliance Center app does not use Forms, but instead surfaces the content using custom pages - those are very similar to canvas apps (allow you pixel perfect control over how to render a page) and they don't support merging. 

Yes, you could create your own Developer Compliance Center app and use Forms/Views instead of modifying the custom pages, that would work as well. You won't get the same look and feel as the Developer Compliance Center has today, but the functionality should work and it would be less development/maintenance effort on your side as well. 

Hope that helps,
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
