### ISSUE TITLE
[ALM Accelerator - BUG]: Save Solution not creating Prod Pipeline

### ISSUE THREAD

**Issue by Aditi3981** [microsoft/coe-starter-kit#6279]
### Describe the issue

The ALM is unable to create the prod pipeline in the folder after saving the Solution in ALM Accelerator app. It creates validation and Test pipeline correctly but does not create Prod. Also, it is adding 'coe-starterkit-azdo' label in front of the solution name.   
![image](https://github.com/microsoft/coe-starter-kit/assets/60483804/f067c805-b463-4796-9beb-805da4062d59)

### Expected Behavior

It should create the Validation, Test and Prod pipelines in the Folder with Solution Name correctly.
![image](https://github.com/microsoft/coe-starter-kit/assets/60483804/fe417f6f-83cd-4677-b2c0-ad81c0105de6)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230629.1

### Steps To Reproduce

1. Create yaml files in main branch in the Solution Name Folder
2. Create a Branch with the Solution Name
3. Click on Save Solution in ALM
4. Should create 3 pipelines (Dev, Test and Prod) in the Solution name folder

**Comment by mikefactorial** [comment]
@Aditi3981 thanks for reporting this. We have noticed recently that errors in the process of creating deployment pipelines are being swallowed and not causing failures in the pipelines. In the short term would recommend searching the Update Deployment Settings log for an error that was logged but didn't fail the pipeline. We have plans to expose these errors more readily going forward. Feel free to report back with any error you find in the Update Deployment Settings step of the export pipeline if you need assistance in troubleshooting. The addition of the repository name is expected and based on feedback related to the same solution existing in multiple repositories in the same project. We're prefixing the repo name now so that they are distinct based on the repo in which the solution is committed.

**Comment by RajeevPentyala** [comment]
@Aditi3981 To troubleshoot the issue, could you share the 'Update Deployment Settings' task logs by following below steps.

- After committing your solution (preferably with fresh solution commit), open the Azdo pipeline by clicking on the highlighted icon below.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/d3a90960-d35e-4af2-92c4-357d3c02b8f1)

- Select the 'Update Deployment Settings' task and click on 'View raw log'. Copy the content and share the log.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/b9326e3c-411d-489f-9e01-b4ffe3a6ab19)

If you can't share the log here, please mail to rajeevpe(at)microsoft(dot)com

**Comment by mikefactorial** [comment]
Closing this out for now since there's been no response.

**Comment by Aditi3981** [comment]
Hello Mike,

We were able to create the pipelines successfully. Thank you for your reply.
