### ISSUE TITLE
[CoE Starter Kit - QUESTION] APP IDEA: Standard Connector App that is part of a new solution, List of all MY Apps, All MY owned Flows with link to environment they are in.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6299]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

APP IDEA: Standard Connector App that is part of a new solution, List of all MY Apps, All MY owned Flows with link to environment they are in.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
We can add this to our backlog, it would have to only use the connectors https://learn.microsoft.com/en-us/connectors/powerappsforadmins/ and https://learn.microsoft.com/en-us/connectors/flowmanagement/ vs Dataverse. 

If this is critical to you, I'd encourage you to look at implementing this yourself. I'm not sure when we'd get to it as our backlog is quite long.

**Comment by jukkan** [comment]
For reference, there's a recently published community solution from Loryan Strant called "My Power Platform" that offers this type of functionality to see the user's own apps and flows: https://www.loryanstrant.com/2023/08/11/my-power-platform-finding-your-flows-and-apps-across-environments/

![image](https://github.com/microsoft/coe-starter-kit/assets/10254155/43c44488-8fdc-4b14-9d57-f27d54f32a25)

One unfortunate limitation with these standard connector solutions is that the Power Apps admin connector does not return model-driven apps (because they have an entirely different tech behind them than canvas apps). So, the list will not be identical to what the CoE Starter Kit inventory says, as that one retrieves model-driven app information from the Dataverse, with a premium connector. Maybe that's not a blocker if the intent is to make the solution available to users without a premium license anyway (and model-driven apps will always require it).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
