### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Dashboard Will Not Install

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#6304]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Every time I try to import the latest CoE Dashboard template I get an error. The CoE is currently up to date with the August release.
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/04279d5c-c07e-4043-9edd-61da41da581a)

Most have the error:
Load was cancelled by an error in loading a previous table.

But for the flows this error is listed:
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/8cb6b826-02ab-4640-aa4b-e4e008466408)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August Release

### What app or flow are you having the issue with?

Power BI Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, we fixed a set of bugs and reshipped the PBI for August release, so if you [download again](https://aka.ms/coestarterkitdownload) you will see this fixed. 

Here are the bugs we fixed in the reship of the PBIT files
[Power BI loading data error - OLE DB or ODBC error on flows table](https://github.com/microsoft/coe-starter-kit/issues/6234)
[Embedded Power BI manage access app error for Flows](https://github.com/microsoft/coe-starter-kit/issues/6246)
[Unable to see any visual in Pulse Dashboard](https://github.com/microsoft/coe-starter-kit/issues/6251)
[Unable to see many visuals for Power Platform Administration Planning Power BI report](https://github.com/microsoft/coe-starter-kit/issues/6253)

**Comment by medicineshow** [comment]
Thanks for the quick response. all sorted.

**Comment by Jenefer-Monroe** [comment]
You are most welcome!
