### ISSUE TITLE
Power BI Dashboard not working behind firewall

### ISSUE THREAD

**Issue by Webritter** [microsoft/coe-starter-kit#632]
I have the situation: 
* CEO Starter Kit is installed in a Teams-Environment - Working properly
* I want to use the power-BI template "Dataverse_CoEDashboard_202106.pbit" to see the Dashboard
* My Computer is behind a firewall blocking Port 1443 
* The Power Bi Template is not working in this case

**Describe the solution you'd like**
I have tried to connect to the Teams-Dataverse.Environment by the Dynamic online - connector by adding "/api/data/v9.2" to the Environment URL. - This is working fine in my situation.

It would be ver helpfull for me to have a ".pbit" file witch connection via the Dynamics Online Connector.

**Describe alternatives you've considered**
Perhaps it is possible to edit all connection in the Query-Editor and save the Dashboard afterwards. I need help to make this changes.

**Additional context**
Firewall is blocking Port 1443 and 5888

**Comment by manuelap-msft** [comment]
There are two different ways to connect to Dataverse from Power BI:

**Dataverse:** This connector is the most recent version and uses the tabular data stream (TDS) protocol.
**Common Data Service (Legacy):** This is the earlier version of the connector.

The CoE Starter Kit provides two Power BI Template files, one using the Dataverse connector and one using the CDS Legacy connector.

Dataverse / TDS endpoint has certain pre-requisites which are listed in [this arcticle](https://docs.microsoft.com/powerapps/maker/data-platform/data-platform-powerbi-connector). We found many organizations have some ports blocked that stop this connector from working, which is why we're providing two dashboards.

Our documentation was updated with this [troubleshooting guide ](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#troubleshooting) and with guide to help you choose[ which version to pick](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use)

**Comment by Webritter** [comment]
Thank you for the information.

I have tried to use the Common Data Service (Legacy) connetor. But this Connector is not working with Dataverse for Teams.
I have seen, that the Dynamics 365 (online) Connector can get data from the Dataverse for Teams.

My need is: A Template using the Dynamics 365 (online) Connector.

**Comment by manuelap-msft** [comment]
That's correct, the Legacy connector does not work for Dataverse for Teams. It's out of the scope of the CoE Starter Kit to provide a third template with a D365 connector, we only provide two with the Common Data Service connector and the Dataverse connector. You may be able to create your own templates, or even use ours as a starting point and modify the Datasource to the D365 connector. But it's not work the CoE team is able to do.

**Comment by Webritter** [comment]
ok. I'll try
