### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Get Security Role Users v4.13

### ISSUE THREAD

**Issue by mpache19** [microsoft/coe-starter-kit#6328]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I'm facing several issues on this Flow. We did the update to the last version and now the errors are growing (about 1.4k per week).

Issue error: The 'inputs.parameters' of workflow operation 'Delete_it' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Check inside [CoE Admin Command Center] Active Sync Flow Errors

**Comment by Jenefer-Monroe** [comment]
Can you please tell how many environments you have? 

Then please do all the following to both **_SYNC HELPER - Get Security Role Users_** and 
**_Admin | Sync Template v3 (Environment Properties)_**.  And return with screenshots of these things. 

1. Turn them both off so that the excess calls can drain. 
2. Check and remove unmanaged layers from them
3. Check to see how often they are running on the analytics usage page
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/18562654-ebd1-4ddb-ad52-62a2d556e251)
4. Check to see how many instances of each you currently have running
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8b81d304-181e-4213-a7af-ce8145e4d611)

**Comment by mpache19** [comment]
Hey Jenefer, how are you?

Thank you for your reply!

We have about 1405 environments until now.

Below you can find the evidences.

Solution layers without unmanaged layers for both:
![image](https://github.com/microsoft/coe-starter-kit/assets/142012800/bff4e588-d8eb-4448-8b2f-9f16586a96a2)
![image](https://github.com/microsoft/coe-starter-kit/assets/142012800/e886336d-12fd-496d-91f0-8b895fb584d5)

Usage for Syn Templates:
![image](https://github.com/microsoft/coe-starter-kit/assets/142012800/50abc69d-ab4c-4de3-8acd-5a91a69276cf)


Usage Syn Helper:
![image](https://github.com/microsoft/coe-starter-kit/assets/142012800/112c795c-cf47-4327-826b-cb6c00d80173)

At this moment we have no running process, but I will check when it starts.

Thank you!

**Comment by Jenefer-Monroe** [comment]
The number of runs of these two flows should nearly match each other as of 4.13. With **_SYNC HELPER - Get Security Role Users_** running slightly less than **_Admin | Sync Template v3 (Environment Properties)_** instead of so much more as before.

**Comment by Jenefer-Monroe** [comment]
wonderful news!
