### ISSUE TITLE
[CoE Starter Kit - QUESTION] Query Power Automate desktop flow contents

### ISSUE THREAD

**Issue by AutoMationTimeNow** [microsoft/coe-starter-kit#6334]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to query the contents of PAD flow?   I have large environment of PAD flows and need to review from time to time if flow uses specific actions: For example:  Launch Edge, Launch Outlook or Invoke web service.  Of course, I could spend hours opening each flow and searching flows, sub flows and take inventory.  However, is there a way to get this information systemically?  
I was exploring COE tool kit and noticed desktop flow information but appears to be limited to run information.

<html>
<body>

Flow Name | Step | Action | Action Details
-- | -- | -- | --
FL1 | 1 | Launch Outlook | Inbox
FL5 | 2 | Launch Outlook | To:

</body>
</html>

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately the kits capabilities for Desktop Flows are quite limited today due to a product limitation (which will hopefully be resolved in a few more months) but there is an entire kit focused on them in the meantime. 
I would suggest you begin by exploring the [Overview of the Automation Kit](https://learn.microsoft.com/power-automate/guidance/automation-kit/overview/introduction)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
