### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION Creator/owner name is blank for Apps and Cloudflows, even after having owners and creators assigned to a service account

### ISSUE THREAD

**Issue by hrsharmafederation** [microsoft/coe-starter-kit#6371]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Why is creator/owner name blank for Apps and Cloudflows in Power BI dashboard results, even after having owners and creators assigned to a service account?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Ownership should be updated. I'm not sure how to proceed in debugging without more details though. 
Where are you seeing the blanks?

**Comment by hrsharmafederation** [comment]
Hi Jenefer,

Thanks for getting back to me.
There are several examples for it in our tenant information, where in Power BI dashboard, the owner names comes as blank in COE dashboard.
Example of one flow is mentioned below, where owner for a particular cloud flow is blank, but when we actually go an check the flow, it has a owner assigned to it which is a service account.

***@***.***

***@***.***

Please do let me know if you need any more information.

Thanks,
Henali Sharma

**Comment by Jenefer-Monroe** [comment]
Can you please share these two screenshots with me? Note that you will need to be logged in to GitHub to share them, responding in email does not share images

### What Solutions installed
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

### All flows on and no unmanaged layers
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by hrsharmafederation** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/140677779/d31a8198-c28a-4c88-999a-25573eafa938)
![image](https://github.com/microsoft/coe-starter-kit/assets/140677779/bdd0ebde-62a3-4fb4-9f80-e67c6b9bdc7e)
Thanks for getting back to me.
There are several examples for it in our tenant information, where in Power BI dashboard, the owner names comes as blank in COE dashboard.
Example of one flow is mentioned below, where owner for a particular cloud flow is blank, but when we actually go an check the flow, it has a owner assigned to it which is a service account.

**Comment by hrsharmafederation** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/140677779/d31a8198-c28a-4c88-999a-25573eafa938)
![image](https://github.com/microsoft/coe-starter-kit/assets/140677779/bdd0ebde-62a3-4fb4-9f80-e67c6b9bdc7e)
Thanks for getting back to me.
There are several examples for it in our tenant information, where in Power BI dashboard, the owner names comes as blank in COE dashboard.
Example of one flow is mentioned below, where owner for a particular cloud flow is blank, but when we actually go an check the flow, it has a owner assigned to it which is a service account.

**Comment by hrsharmafederation** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/140677779/bddb6f13-891b-42b7-99c8-ef21ba3607c6)
![image](https://github.com/microsoft/coe-starter-kit/assets/140677779/e7124d39-6319-4886-9727-854852d75a0c)

Hi Jenefer,

Please find the attached screen-grabs as mentioned above.

**Comment by Jenefer-Monroe** [comment]
I believe this is due to the same underlying issue that caused us to make this update in August release. 
https://github.com/microsoft/coe-starter-kit/issues/6016

After your next upgrade (to August or later) you can force these to be inventoried with the "Inventory Me" flag and then you should see it fixed up. 
Please see https://github.com/microsoft/coe-starter-kit/issues/6419 for how to set that flag

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
