### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to refresh old abandoned setup of the kit.

### ISSUE THREAD

**Issue by AutoMationTimeNow** [microsoft/coe-starter-kit#6372]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The COE toolkit loads successfully in PowerBI, but the data it displays is outdated. Despite my attempts to refresh the data, no changes occur. It appears that the data stopped updating in June 2023. As an example, the 'created on' date of the last Desktop flow is indicated as 6/2023. The individual who initially installed this toolkit is no longer part of our organization. Strikingly, the 'created on' date of the last Desktop flow coincides with the departure date of the person who set up the COE toolkit. I'm eager to reestablish the flow of data into the COE toolkit.

Furthermore, I'd like to determine the version of the Toolkit we're using. The toolkit was installed back in December 2022.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. The kit was likely running in the context of that user and so stopped working when they left the organization, and their license / role was no longer available. 

You'll need to first determine what identity to run the kit with. That could be yours or a shared service account. But here is what it will need for licenses / roles: [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

Then before you decide what to upgrade to, can you please show me what you have installed now all up? Be sure to expand the indicated columns so that we can see full names. This will help me know your current health / state to give the best advice.
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by AutoMationTimeNow** [comment]
Hello Jenefer-Monroe, thank you for the quick response. The license was transferred to me prior to departure. 
How do I determine this?
"You'll need to determine what identity to run the kit with."

![image](https://github.com/microsoft/coe-starter-kit/assets/142052108/d5e59172-e2f8-4ba4-ae86-c3e0c0d66c3a)

**Comment by Jenefer-Monroe** [comment]
This link is intended to help you make that decision by showing you the qualities of the user / service account that will be needed. For example the licenses / roles needed
[What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by Jenefer-Monroe** [comment]
Since you are only using Core, and since it is nearly a year old, you may best be served by [starting from a clean environment](https://learn.microsoft.com/power-platform/guidance/coe/setup#create-your-environments) once you figure out who to use the kit. This way you dont need to worry about configurations the old user made. 

We recommend upgrading at least every 3 months as that is how far back we test.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by AutoMationTimeNow** [comment]
How do I remove the old COE Kit?   I tried to delete the COE Core Component solution and it fails.  Of course, I can install on new lower environment however I need it in production.
