### ISSUE TITLE
[CoE Starter Kit - BUG] Embedded Access This Flow App Not Allowing Access

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#6391]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I use the Power BI dashboard to select a flow and drill down in to a flow that is in the Default Environment, I get a number of errors:
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/8973c392-ac71-4cd2-b5a1-6ca0dccb99fd)
PowerAutomateforAdmins.GetAdminFlowOwnerRole failed: { "error": { "code": "EnvironmentAccessDenied", "message": "You are not permitted to make flows in this '*************************************c'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions." } }

PowerAutomateManagement.AdminGetFlow failed: { "error": { "code": "EnvironmentAccessDenied", "message": "You are not permitted to make flows in this '*************************************'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions." } }

Office365Users.UserProfileV2 failed: The method 'UserProfileV2' has an invalid value for parameter 'id'

Any other environments gets the following:
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/81824e54-ad8e-4a0e-8e6b-0d37cfd4fef8)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin - Access this Flow [works embedded in Power BI only]

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Power BI Dashboard
2. Navigate to Flow Deep Dive
3. Select a flow and right click
4. Select DeepDive

### Anything else?

The account used to connect is s System Administrator in all environments.

**Comment by Jenefer-Monroe** [comment]
Hello, we fixed a set of bugs and reshipped the PBI for August release, so if you [download again](https://aka.ms/coestarterkitdownload) you will see this fixed. 
Here are the bugs we fixed in the reship of the PBIT files
[Power BI loading data error - OLE DB or ODBC error on flows table](https://github.com/microsoft/coe-starter-kit/issues/6234)
[Embedded Power BI manage access app error for Flows](https://github.com/microsoft/coe-starter-kit/issues/6246)
[Unable to see any visual in Pulse Dashboard](https://github.com/microsoft/coe-starter-kit/issues/6251)
[Unable to see many visuals for Power Platform Administration Planning Power BI report](https://github.com/microsoft/coe-starter-kit/issues/6253)

**Comment by Jenefer-Monroe** [comment]
Have you done the "reset to default" on the app? See [Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
