### ISSUE TITLE
[CoE Starter Kit - QUESTION] Collect audit logs using an HTTP action error

### ISSUE THREAD

**Issue by WS6303** [microsoft/coe-starter-kit#6409]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi  Team,

How can I solve the following problems?
<img width="664" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/139745339/bfe35b80-1b39-4d8f-b32e-02e58af0b192">
<img width="623" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/139745339/0ee69897-0ffa-4cb5-8363-f9b70c5da58c">

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, there isnt a problem here to fix unless I'm missing something that you are saying. I've written up what is happening here, hopefully it helps make it clear.

### Why isnt everything running?
We use "configure run after" properties in the flows to run sections of code dependent on state of the previous action. 

### How to see this in the flow
You can see these settings as shown here. 
This "Error Handling" scope only runs if we fail in the "Get Logs" scope
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/012530c6-a267-48c9-ab0a-ca9fd3f87b35)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4605a9a-2847-4dc0-a343-6acf754536f0)

And this scope only runs if "Error Handling" is skipped (aka no failure in Get Logs)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/967ab954-2e75-4bd8-af1b-8e339f177005)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/29265a7a-c716-44f8-b50e-32bf14353321)

### How to see this in the run
As in your case then, a success should skip the Error Handling Scope and therefore run "Update last run as pass ..." 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c4fc5ac7-6ad4-47c0-a974-7bcbe215e536)

### What a failure would look like
Here I've forced a failure and you see that "Error Handling" ran but not the "Update last run as pass..." because "Error Handling" was not skipped.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4425238-9b33-4dd6-9ee9-b9bec8e7f52a)

**Comment by Jenefer-Monroe** [comment]
Closing at as no further action for starter kit team
