### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can I use a D365 Sales Enterprise Edition instead?

### ISSUE THREAD

**Issue by johnrizaldobh** [microsoft/coe-starter-kit#6413]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Instead of Power Apps Per User & Power Automate Per User plan, can I use the D365 Sales Enterprise Edition instead? 

See screenshots below:

![image](https://github.com/microsoft/coe-starter-kit/assets/121220432/32b07bbe-3218-4ff6-a923-c76e47fe82dc)

Licensing guide I've found here: https://learn.microsoft.com/en-us/power-platform/admin/pricing-billing-skus
![image](https://github.com/microsoft/coe-starter-kit/assets/121220432/e39dc81d-cfb5-48a5-afb1-d84932690c3b)
![image](https://github.com/microsoft/coe-starter-kit/assets/121220432/d20d228f-47ac-4167-98c2-d688111d4edc)

Thank you,
John

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We're not licensing experts unfortunately. If your investigation indicate that your current license should work then go ahead and give it a try. You'll know you need to switch to the documentation recommended if you are unable to turn flow on (ex due to pagination issues), unable to run flows (due to insufficient access to premium connectors) or if you receive mails from the product team warning you that your license type is insufficient for some other reason.

**Comment by Jenefer-Monroe** [comment]
Closing at as no further action for starter kit team
