### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

### ISSUE THREAD

**Issue by Ceosc** [microsoft/coe-starter-kit#6416]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello!

We have encountered a problem with the flow: "CLEANUP - Admin | Sync Template v3 (Orphaned Makers)". The problem is as follows:

"The input text for the 'manual' trigger type 'request' did not match its schema definition. Error details: 'Invalid type. Expected string, but received null.'".

We found out that a new user was automatically added in our COE environment without any information (no email address and no name), so the flow fails because there is no display name.

As a quick fix we will adjust the filter option:

![image](https://github.com/microsoft/coe-starter-kit/assets/142991019/5b325990-a6ff-4fc4-80c6-e26c30d24cae)

It would be nice, if you could also adjust the filter option. Thanks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin - Sync Template V3

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello thank you for posting, we did recently change the way we pass in variables to this helper to no longer send in display name and only ID. 
Please see https://github.com/microsoft/coe-starter-kit/issues/6016, fixed in the August 2023 release
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/35de0843-6e4d-4d91-a21f-e9d6363ddc75)

**Comment by Jenefer-Monroe** [comment]
Closing at as no further action for starter kit team
