### ISSUE TITLE
[CoE Starter Kit - BUG]: Core Component Solution issue

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/coe-starter-kit#645]
**Describe the bug**
A number of flows relating to the core components solution are coming up with errors. We've upgraded to the latest version.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 2.1.70
 - App or Flow - Admin | Sync Template v3 (Desktop flows) and CLEANUP - Admin | Sync Template v3 (Connection Status)

**To Reproduce**
The errors occur when the flows runs on it's set schedule.

**Expected behavior**
The flows should run without any errors.

**Screenshots**
I've attached screenshots and text files containing the error for each flow.

![Admin - Sync Template v3 (Desktop Flows) screenshot](https://user-images.githubusercontent.com/62425530/122376032-b0cb0200-cf5b-11eb-9a64-c8e5098bac90.PNG)
[Admin - Sync Template v3 (Connection Status).txt](https://github.com/microsoft/coe-starter-kit/files/6669238/Admin.-.Sync.Template.v3.Connection.Status.txt)
![Admin - Sync Template v3 (Connection Status) screenshot](https://user-images.githubusercontent.com/62425530/122376037-b1fc2f00-cf5b-11eb-9380-e9ef783337a2.PNG)

**Comment by JeneferM-MSFT** [comment]
In the future please post separate issues for your bugs as these are not related. 

For the first issue in (Desktop flows), I believe you have not recieved updates from us as 'content' is not a required property in our schema at that step.  I believe you may have an unmanaged layer on that flow. 
Please install updates following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by JeneferM-MSFT** [comment]
For the second issue:

I believe you have hit a known product bug around caching of deleted PowerApps. You will need to contact support to have them clean this up in order to have this flow start passing. 

Our recommendation is to first get a repro outside of the toolkit before contacting support. You can use the below flow to get this repro. 

To use: Import the flow, open, select the environment which repros for you. 
It loops the apps, will hit the same failure and the you can go to support with this flow instead of the toolkit, for faster iteration to fix.

[ProductBug-GetAppfails-TheresponseisnotinaJSONformat_20210418134636.zip](https://github.com/microsoft/coe-starter-kit/files/6671168/ProductBug-GetAppfails-TheresponseisnotinaJSONformat_20210418134636.zip)

![image](https://user-images.githubusercontent.com/62659043/122421743-d4854c80-cf49-11eb-80c6-d3f27474c665.png)

**Comment by melmgcoe** [comment]
Re the desktop flow issue, I can confirm that we don't have any unmanaged layers for this particular flow. Is there anything else I can look at to resolve the error?

**Comment by JeneferM-MSFT** [comment]
Can you please post a separate issue for that? We can have this one track the product bug you ran in to. 

When you post, please open the flow for edit and capture what is in the schema as shown here and include that
![image](https://user-images.githubusercontent.com/62659043/122427511-67c08100-cf4e-11eb-8afc-a8718696864f.png)
