### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE: Office 365 Management API 

### ISSUE THREAD

**Issue by cooperfl2023** [microsoft/coe-starter-kit#6472]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

My Office 365 Management API custom connector within the Power Platform COE Starter kit is failing to authenticate. Error msg incidates my oauth not authenticating but my azure secret has not expired. Microsoft support and i decided to delete the custom connector and rebuild it but cannot because i cannot authenticate.

### Expected Behavior

This connector connects the child flows in power platform coe starter kit and cannot function without.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. PPCOE environment
2. Solutions-Center of Excellence - Audit Logs-All
3. Select cloud flow: Center of Excellence - Audit Logs
4. Edit
5. Sign-in (Office 365 Management API) SSO
6. Error
7. I go to Custom Connection, Create connection for Office 365 Management API
8. Error: "OAuth2 authorization flow failed for service 'Azure Active Directory'. OAuth 2 sign in failed to exchange code for access token. Client ID and secret sent in form body.. Response status code=Unauthorized. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Inv"

### Anything else?

Issue ongong since May 2023

**Comment by cooperfl2023** [comment]
I deleted and created Office 365 Management API and successfully logged in, however I am getting authentication 401 error. notes incideate bad bearer token, how can that be and how to correct it?

**Comment by Jenefer-Monroe** [comment]
Hello, we have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 
Starting with the August 2023 release, you will no longer be able to upgrade the CoE Starter Kit Core Components until you either [switch to the new http methodology]( https://github.com/microsoft/coe-starter-kit/issues/6009) or [take a local copy of the old custom connector solution]( https://github.com/microsoft/coe-starter-kit/issues/6017) for your personal use.
See [This pinned issue]( https://github.com/microsoft/coe-starter-kit/issues/6018) for more details on how to fix this upgrade issue up.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
