### ISSUE TITLE
[CoE Starter Kit - BUG] Questions/Problems with Connection Reference Identity Table

### ISSUE THREAD

**Issue by javiles1327** [microsoft/coe-starter-kit#6541]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are having an issue with the Connection Reference Identity table in the CoE starter kit.  
We looked at the table to get a better understanding of cross-tenant connectors within power platform.

First, I think our best question is what data is intended to be displayed in this table and for what purpose?
Part of the reason we ask this is that we had a customer who deleted a connection we had a question about, and upon the next update to the table, all historical references to this connecter were gone.

Additionally, individual connection references appear to be logging as though they are creating anew every day.  It's as though each day creates a new reference from the existing connection.  The question we have related to this- is this an error in the reporting, or is this the actual data coming from MS?

Any light that you can shed on this would be greatly appreciated.  Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Connection Reference Identity table

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
First note that we made some fixes to this feature for the September release that just went out this week.

The point of this table is to show what connectors are used by what identities. So you can see that 
- Sam has Dataverse connections in EnvtX
- Sam also has Dataverse connections in EnvtY
- Bob also has Dataverse connections in EnvtX

If Bob deletes all his Dataverse connections from EnvtX then this record should be deleted.
This is because primarily it is used to understand who is accessing what, where. And so in this case Bob is no longer accessing Dataverse from EnvtX.

It does not help you to know about individual connections (ex we use this connection in this flow) as that information is not available to us.

Hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
