### ISSUE TITLE
Service Account Ownership Best Practices

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6554]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Just verifying that we still need to ensure the below for a Service Account to do the install for the CoE:

-No MFA unless the Conditional Access Policies for Lifetime tokens are used and not ' remember multi-factor authentication'
-No password expiry
-Connectors need to be a real user account and cannot use Service Principals (yet)

Just check to make sure nothing has changed.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Correct and also have all roles / licenses permanently assigned and not via PIM

**Comment by PPCan** [comment]
If we can't get the no password expiry requirement, what is the impact?

When the password expires will the flows immediately go offline, or is it similar to MFA 'until revoke', and will keep running?
I'm assuming it's immediate on next call...

**Comment by Jenefer-Monroe** [comment]
I'm really not sure unfortunately I've not tested around this. I would presume that it will stop working at the moment of expiration, but perhaps there are azure features to warn and things like that.
If I couldnt get that allowed I would probably set a reminder on your admin task list to change the password intentionally at a shorter cadence than the tenant expiration policy.

**Comment by PPCan** [comment]
Good idea.

How would you approach this with a large connector base?  I'm assuming each connector would need to have the 'fix connection' addressed individually? There's no CLI?

**Comment by Jenefer-Monroe** [comment]
To my knowledge there is no programmatic way to do this, I believe its an intentional security feature to not allow that. You have to manually create connections as the identity. But there arent that many, a few dozen. The worst part I think is that they wont show as broken straight away so I guess you would want to 

1. wait till a "good time of day"
2. reset the password
3. run a helper flow that calls all the connectors which should cause them all to then show as broken
4. fix them. 

lame but thats all I can think to do.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
