### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION about upgrade to latest version

### ISSUE THREAD

**Issue by miroslav-harlas** [microsoft/coe-starter-kit#6580]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,
I have several questions, for which I have tried to get answer in official documentation, but I was not able to find the details, or I may misunderstood it. Thank you very much in advance for getting this clarified:

1. We are running old version of the Starter Kit - December 2022 - just the Core components and without Audit logs, and we are planning for upgrade. I'm aware that you are recommending to upgrade starter kit frequently, but we failed due to various organizational reasons on our side. Can we go directly from Dec 2022 to Sept. 2023 or should we apply some kind of upgrade path and download and install also some other versions in-between as a part of the upgrade process?
2. We are also keen about using Data Lake export as a source of the inventory and usage data. We have already enabled it in our tenant and we have our Data Lake full of data from past months. After the upgrade of the CoE starter Kit to the latest version, is there any option to switch from Cloud Flows to Data Export, test it, and then switch back? If yes, then please, could you share what are the steps to switch between these two methods? I haven't find these details anywhere in the documentation.
3. Are there anywhere the recordings of the CoE Starter Kit Office Hours available for listening? 

Thank you very much in advance for answers.
Best Regards
Miroslav Harlas

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

n/a

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. 

1. Upgrade Dec 2022 -> Sept 2023: We happen to be testing back further than usual at this time due to an upcoming mandatory upgrade of the kit for a connector deprecation, so you are fine to upgrade directly from Dec at this time. 

2. Switch to Data Export: Yes you can convert. After upgrade boot the **CoE Setup and Upgrade Wizard** and it will walk you through the conversion. Shown below is the screen in that app that you can use to switch between them after which the steps will show you how to complete that setup. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d7901e1e-4c2a-442a-ba27-dfbeb62332bb)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cc55d947-11ef-4b24-a4a6-72fbb3f40fa6)

3. Office Hours Recordings: Unfortunately not, we are not staffed at this time to do the work to make these available.

**Comment by miroslav-harlas** [comment]
Hello @Jenefer-Monroe ,
thank you very much for the reply and for all the details.

Add 2.
Is there anywhere documented, what configuration actions are performed by the Wizard? Can be the switch from Cloud Flows to Data Export done manually without Wizard, is that supported from your side?

Thank you in advance for clarification of this last point.

**Comment by miroslav-harlas** [comment]
Hello @Jenefer-Monroe 
Thank you very much for clarification of all the details and for so prompt responding.
You are doing tremendous job to support us, Power Platform Admins ;)
This question can be closed.
Best Regards
Miroslav Harlas

**Comment by miroslav-harlas** [comment]
closing...
