### ISSUE TITLE
[CoE Starter Kit - BUG] Issue with custom connector methodology to collect audit logs

### ISSUE THREAD

**Issue by KezHalls** [microsoft/coe-starter-kit#6600]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am not seeing any new data for field  admin_applastlaunchedon table has no new data.  Same issue as #6159 but fix does not work.

the flow is running successfully and only takes about 1 minute.  It has run successfully in the past. 
I did have to change from using the azure secret value as this is also broken as I cannot update the variable (have logged this with MS)

### Expected Behavior

Last launched gets populated after audit flow runs

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run the flow

**Comment by Jenefer-Monroe** [comment]
Hello, we have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. Likely that is what hit you here is that your connection to the custom connector broke.

Starting with the August 2023 release, you will no longer be able to upgrade the CoE Starter Kit Core Components until you either [switch to the new http methodology]( https://github.com/microsoft/coe-starter-kit/issues/6009) or [take a local copy of the old custom connector solution]( https://github.com/microsoft/coe-starter-kit/issues/6017) for your personal use.
See [This pinned issue]( https://github.com/microsoft/coe-starter-kit/issues/6018) for more details on how to fix this upgrade issue up. 

Its recommended that you prepare for the switch to the new http methodology. 
In the meantime, I will paste next the old debugging tips for the old custom connector methodology

**Comment by Jenefer-Monroe** [comment]
**_UPGRADE of old deprecated custom connector methodology_**
Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issI will beues/1424) for how to esolve 
If that does not resolve, then you likely ended up with a bad connection, perhaps due to the wrong identity provider being selected as in [issue 4808](https//github.com/microsoft/coe-starter-kit/issues/4808)

If that occurs please try the steps outlined in [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)
The default Identity Providor for the custom connector changed to Generic Oauth 2, so likely what happened is that you authenticated to a bad connection. Unfortunately this isnt obvious and clean up isnt that easy. 
![image](https://user-images.githubusercontent.com/89584709/225247140-70c99bb5-5770-428c-b45a-60c3f45e01dd.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
