### ISSUE TITLE
[ALM Accelerator - QUESTION] Error: remote unpack failed: error VS403702: The push was rejected because one or more commits contain author email

### ISSUE THREAD

**Issue by ashishbhatt-afk** [microsoft/coe-starter-kit#6652]
### What is your question?

While running the script "https://github.com/microsoft/coe-alm-accelerator-templates/blob/CenterofExcellenceALMAccelerator-August2022/PowerShell/update-deployment-settings.ps1" I am getting error "error: remote unpack failed: error VS403702: The push was rejected because one or more commits contain author email '' which does not match the policy-specified patterns. " This error is expected when the commit is coming from an email address that is not added in the repository policies. But in this script there is no git commit.. so why do I see this error?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

latest

**Comment by ashishbhatt-afk** [comment]
Hello,

May I please know how can I unblock my self? I don't want to disable the
Author email validation policy.

Regards,

**Comment by mikefactorial** [comment]
@ashishbhatt-afk the email is set based on the user who initiated the commit. Can you add the user to the policy or use another user that is included in the policy?

**Comment by ashishbhatt-afk** [comment]
@mikefactorial
 It is good to know that the issue will be fixed in October. 

Also, Unfortunately, I did not understand how to implement the suggestion you provided "update the commit ref being passed to the API with the author / committer". Can you please elaborate a bit on it? It would be helpful. 😊

**Comment by mikefactorial** [comment]
@ashishbhatt-afk [the permalink in the ALM Accelerator template repo](https://github.com/microsoft/coe-alm-accelerator-templates/blob/c01411106245ef1c9dd65a073b4b6a1ab635b042/PowerShell/brach-pipeline-policy.ps1#L169) is where the commit object is created that gets passed in the body of the post to the API that does the push. As you can see it doesn't include the user's information, which is what the error message is stating "The push was rejected because one or more commits contain author email ''". 

```
                    # Create a new commit object with the changes array
                    $commit = @(
                        @{
                            comment = "Add DevOps Pipeline"
                            changes = $commitChanges
                        }
                    )
```

You would need to modify the powershell to [add author to that object per the API documentation](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pushes/create?view=azure-devops-rest-7.0&tabs=HTTP#gitcommitref) to get around the error.

Example (not tested)
```
                    $author = @(
                        @{
                            email = "foo@test.com"
                            name = "foo"
                        }
                    )
                    $commit = @(
                        @{
                            comment = "Add DevOps Pipeline"
                            changes = $commitChanges
                            author = $author
                        }
                    )
```

**Comment by mikefactorial** [comment]
Closing this out as it's been resolved in the October release.
