### ISSUE TITLE
[CoE Starter Kit - BUG] Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding.

### ISSUE THREAD

**Issue by eduxrd89** [microsoft/coe-starter-kit#6698]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, I have problems updating "Center of Excellence - Core Components" from version 4.4.2 to 4.15, I get the following error:

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 3 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-bd68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

![WhatsApp Image 2023-09-22 at 7 45 44 PM](https://github.com/microsoft/coe-starter-kit/assets/43019998/54743a3d-3696-4539-a49b-a7a251d033ec)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Center of Excellence - Core Components - Apply update 4.15

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Download CoE starter kit Sep 2023 version
2. Import Solution - "Center of Excellence - Core Components"
3. Apply update 4.15 - Does not complete and shows error

**Comment by Jenefer-Monroe** [comment]
Hello, this is a known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018

We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 

Starting with the August 2023 release, you are no longer be able to upgrade the CoE Starter Kit Core Components until you either [switch to the new http methodology]( https://github.com/microsoft/coe-starter-kit/issues/6009) or [take a local copy of the old custom connector solution]( https://github.com/microsoft/coe-starter-kit/issues/6017) for your personal use.
See [This pinned issue]( https://github.com/microsoft/coe-starter-kit/issues/6018) for more details on how to fix this upgrade issue up.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
