### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION 

### ISSUE THREAD

**Issue by MeredithOneWorld** [microsoft/coe-starter-kit#6700]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Wehn creating the three groups (Admin, maker and users), can the source of Mail enabled security groups to be Windows AD (synced from the on-prem) instead of cloud? 
When installing the CoE starter kit using the service account, can individual admin variable's email address different from service account using my other email address(non-admin)? If service account had MFA enabled and password will be changed after fixed period of time, does all the flow connection have to be updated manually in order to have them running properly?  What is some best practice when setting up MFA?
 
![image](https://github.com/microsoft/coe-starter-kit/assets/95392006/225aaf98-4391-497c-9e2f-bb74ecf7b1f8)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Sept 2023

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. 

### When creating the three groups (Admin, maker and users), can the source of Mail enabled security groups to be Windows AD (synced from the on-prem) instead of cloud?

I think it should work but its not something we've tested, nor have I heard about other people doing it.

### When installing the CoE starter kit using the service account, can individual admin variable's email address different from service account using my other email address(non-admin)? 

Yes. That is used to send communication for things like approvals for orphaned objects. 

### If service account had MFA enabled and password will be changed after fixed period of time, does all the flow connection have to be updated manually in order to have them running properly? 

Yes as far as I know that is true. There is no programmatic mechanism to refresh connections by design to my understanding, for security reasons, and so if you are forced to do this you would need to go ahead of the expected change date, change the password and then fix all the connection references manually. 

### What is some best practice when setting up MFA?

Here are the [recommendations for conditional access and multi-factor authentication in Microsoft Flow](https://learn.microsoft.com/troubleshoot/power-platform/power-automate/conditional-access-and-multi-factor-authentication-in-flow)
