### ISSUE TITLE
[CoE Starter Kit - BUG] Install CoE Core Component failed

### ISSUE THREAD

**Issue by kinwong7** [microsoft/coe-starter-kit#6710]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Tried to upgrade the Core component from v4.4.2 to 4.15, the import was successful, but the uninstall of the older version failed.

Also tried the apply upgrade feature in both modern and classic view, same result.

It complains the dependencies and says to remove all dependencies, but those are in managed solution, can't be deleted.

![image](https://github.com/microsoft/coe-starter-kit/assets/29238122/ce023d69-51bb-4eb0-81b1-f11102948dd5)

### Expected Behavior

Solution should be installed without error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

n/a

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, this is a known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018

We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 

Starting with the August 2023 release, you are no longer be able to upgrade the CoE Starter Kit Core Components until you either [switch to the new http methodology]( https://github.com/microsoft/coe-starter-kit/issues/6009) or [take a local copy of the old custom connector solution]( https://github.com/microsoft/coe-starter-kit/issues/6017) for your personal use.
See [This pinned issue]( https://github.com/microsoft/coe-starter-kit/issues/6018) for more details on how to fix this upgrade issue up.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
