### ISSUE TITLE
[CoE Starter Kit - BUG] Power Apps were set to deleted though they are active

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#6726]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi @manalimaura,

There are many number of flows that were set to deleted in Personal productivity environment. 

Below is one example which shows these apps are active in the environment.

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/d15d1ba2-a1f5-449e-8904-fad980851818)

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/27b8634b-f5e4-4d88-8721-39abde06c4c7)

Could you please let me know what could be the cause of this issue?

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.1.5

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Canvas Apps)

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
### Typical Cause
This is typically due to the identity running the flow not having the PPAdmin Role permanently assigned. 
Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

### If you dont think thats it:
Please go to the run of this flow on 9/22 (according to the screen you shared there) for this envt. You can add the envt name by hitting edit columns.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bbe81690-ad24-44cb-ad44-b7b9b1578032)

Once you find it click the time stamp to open, find this call and see if the app of interest was in the output
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1d38983e-ed1c-4970-b546-6b613da7b035)

**Comment by devvelegandla** [comment]
We are using BYODL, as per condition the cleanup flow (Canvas apps) is not running.

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/42f9e7dc-2bfc-426b-aabd-a2755d37ccd0)

All the BYODL flows are running as expected.

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/3d09d351-add5-416c-b06d-0869078b7add)

**Comment by devvelegandla** [comment]
I also logged another issue which i found with Dataflows.

[https://github.com/microsoft/coe-starter-kit/issues/6742](url)

**Comment by Jenefer-Monroe** [comment]
Sorry about that, I didnt notice you were Data Export. Let me try that again :) I'll hide original to avoid confusion in the bug

### Typical Cause
This is typically due to the identity running the flow not having the PPAdmin Role permanently assigned. 
Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

### If you dont think thats it:
Please go to the run of this flow on 9/22 (according to the screen you shared there) for this envt. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0476067a-4973-4f60-9225-3cae374dbc88)

Once you find it click the time stamp to open, find this call and see if the app of interest was in the output
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ac463886-edc3-4e87-b05d-ca5c02b19026)

**Comment by devvelegandla** [comment]
Thanks, @Jenefer-Monroe. 

Issue is fixed after updating the dataflows.

**Comment by Jenefer-Monroe** [comment]
oh that is WONDERFUL news. Thank you so much for following back up with us on this.
