### ISSUE TITLE
[CoE Starter Kit - QUESTION] Data Export Inventory data - dataflows not connecting to datalake

### ISSUE THREAD

**Issue by WouterKessener** [microsoft/coe-starter-kit#6730]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Got the data export running.

Data is stored in: https://xxx.blob.core.windows.net/powerplatform

Example of environment storage: https://xxx.blob.core.windows.net/powerplatform/powerapps/environments/environments.json

-	Imported the Dataflows in the PowerBI service – Premium workspace
-	Changed DatalakeURL from https://pctoolscoedevdataexport.dfs.core.windows.net/powerplatform to https://xxx.blob.core.windows.net/powerplatform
- 
The dataflow cannot connect to the datasource. I think the problem lies in the DFS vs BLOB in the connection string. 

Did we make a mistake when setting up the data export?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Spet 2023

### What app or flow are you having the issue with?

PowerBI Dataflows

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
Hello,

when you fetch the URL:

1. Navigate to [portal.azure.com](https://portal.azure.com/).
1. Search for or select the storage account configured to receive [Data Export data](https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics#set-up-the-data-export-process-for-your-tenant).
1. Select Endpoints.
1. Copy the Data Lake Storage URL to notepad. Copy Data Lake Storage URL from Storage Account endpoints.
1. Append /powerplatform to the URL.

![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/8c0e5772-7f92-4d31-ad10-a008cddfcc2c)

I believe you copied the blob endpoint which is why it's not working. You need to copy the Data Lake Storage URL. Is that not available for your storage account?

**Comment by WouterKessener** [comment]
Thanks so much. Sorry, tried to configure without using the wizard. Lesson learnt. Always use the wizard it clearly states to use the Data Lake Storage.
