### ISSUE TITLE
[ CoE - Bug ] Power BI Report throws connection error

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#674]
Hello,

I have been in discussion with Microsoft support team for the error we are facing in the Power BI report, however they have suggested to raise a ticket with Github.

This is regarding Power BI Report available with CoE Starter Kit latest version ( 2.1.7)  downloaded on 06/17/2021.

It's a Power BI report "Legacy_CoEDashboard_yyyyMM.pbit" that throws connection error as follows as Power Platform Administrator:

![image](https://user-images.githubusercontent.com/13658386/122934329-6f609b00-d33d-11eb-84d0-93aa33963cf7.png)

I have tried all work arounds listed [here](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard), However the above error is not listed.

Could you please help?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
There are two different ways to connect to Dataverse from Power BI: 
- **Dataverse**: This connector is the most recent version and uses the tabular data stream (TDS) protocol. 
- **Common Data Service (Legacy)**: This is the earlier version of the connector. 

The CoE Starter Kit provides two Power BI Template files, one using the Dataverse connector and one using the CDS Legacy connector.  

Dataverse / TDS endpoint has certain pre-requisites which are listed [in this arcticle](https://docs.microsoft.com/powerapps/maker/data-platform/data-platform-powerbi-connector). We found many organizations have some ports blocked that stop this connector from working, which is why we're providing two dashboards.

Our documentation was updated with this [troubleshooting guide](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#troubleshooting) and with guide to help you choose [which version to pick](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use)

**Comment by DiptiC-InsightRun** [comment]
Hi Jenefer,

Thanks for the response, I see now that it could be due to port issues, however Our work station/VM (local machine) does not have direct access to Internet - all the traffic has to be sent through the proxy, Given that the provided telnet commands will not work . is there a way to use proxy for these connections?
 
We have raised this issue with Power BI support, however they have mentioned that it's an issue with CoE Report therefore checking it out here, kindly help!

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
I'm afraid we cannot assist here. The starter kit needs configuration and work for some organizations beyond what we can do. I suggest hiring a PP partner to assist.
