### ISSUE TITLE
[CoE Starter Kit - Feature]: AI Builder credit consumption report

### ISSUE THREAD

**Issue by IrvineHA** [microsoft/coe-starter-kit#6740]
### Is your feature request related to a problem? Please describe.

AI Builder credit consumption report (PP admin center capacity reports) sub optimal as it only shows a static snapshot of information.  We are quickly burning through credits without dynamically seeing how much is being burned and by whom. We need to get this information for better governance of AI Builder. We need to get the situation under control.

### Describe the solution you'd like

We know that each environment has an AI Event table that contains this information, but we would like to see the COE gather it in one spot and if possible display it in a user friendly and dynamic report in both the COE Admin Center and in the COE Power BI report.

### Describe alternatives you've considered

We are working on a Power BI report to display this data, but we can only do it for a few select high use environments,  Unfortunately we have hundreds making it difficult to bring it all together in one spot.

### Additional context?

We are operating in GCC.

**Comment by manuelap-msft** [comment]
This is already on our backlog: https://github.com/microsoft/coe-starter-kit/issues/6100

Unfortunately we have not yet been able to prioritize working on this, due to some product changes that meant we had to prioritize work on just keeping the kit going (connector action changes and deprecations, data export file format changes etc). Please follow #6100 for status updates on when we'll be able to fit this in!

I'll close this item out as a duplicate, but feel free to add your scenarios to #6100
