### ISSUE TITLE
[CoE Starter Kit - BUG] Dashboard information is incorrect

### ISSUE THREAD

**Issue by apulidoo21** [microsoft/coe-starter-kit#6745]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Reviewing the dashboards, we have noticed that the information displayed is incongruent with the data I can retrieve, for example, using PowerShell or the Microsoft API. 

We have also observed that after renaming the "Default" environment, both environments appear simultaneously in the reports instead of updating the inventory with the new environment name. 

Checking the synchronization flows and the CoE error panel, there is nothing related to this. Additionally, it seems that the Power BI dashboards are updating correctly as well.

### Expected Behavior

We expect to see that the information in the dashboards is reliable and that when compared to other inventory methods, the data is accurate.
Furthermore, changing the name of the default environment should not pose more problems for the dashboards than changing the environment's name in the inventories themselves.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

CoE Dashboards

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Check Governance Dashboard > Details on external connections
Check Power Automate Dashboard

**Comment by Jenefer-Monroe** [comment]
Renaming environments should equalize over time. There is a process to clean up things like that which runs periodically (~every 2 weeks)

**Comment by Jenefer-Monroe** [comment]
For other issues of things not being the same across backends please see [Inventory and telemetry differences between PowerShell, Power Platform Admin Center, and CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/limitations#inventory-and-telemetry-differences-between-powershell-power-platform-admin-center-and-coe-starter-kit)
If after review you still think you have a bug for the kit please return with a specific case and we can explore.

**Comment by apulidoo21** [comment]
Hello Jenefer, the environment renaming was like 2 months ago and I still seeing the old name and the new one.
And I'm comparing the Flows inventory through PowerShell and are not the same (PS flows: 4477; CoE Cloud flows: 5811)

**Comment by Jenefer-Monroe** [comment]
For future reference, its very difficult to track multiple issues in one bug so please post separately. 

Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

And also please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

Lastly, go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by apulidoo21** [comment]
Here is the installed solutions on the CoE Environments:
![image](https://github.com/microsoft/coe-starter-kit/assets/146342025/883c9074-d501-4b6f-ba31-cfcbdab27eaa)

The CoE Environment is a Production type environment hosted on Europe.

All the flows we want to enable are turned on and the runs are successfull. We don't have any unmanaged layers.

**Comment by Jenefer-Monroe** [comment]
Yes your install failed as can be seen here so you are in an unknown state until this is resolved. You likely got a failure message when you did the install. 
The failure was likely due to the Audit Logs solution remaining. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/94cd1cea-9f5d-4557-80f6-5a0023088ed0)

There is a known upgrade failure due to audit logs: https://github.com/microsoft/coe-starter-kit/issues/6018

We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 

Starting with the August 2023 release, you are no longer be able to upgrade the CoE Starter Kit Core Components until you either [switch to the new http methodology]( https://github.com/microsoft/coe-starter-kit/issues/6009) or [take a local copy of the old custom connector solution]( https://github.com/microsoft/coe-starter-kit/issues/6017) for your personal use.
See [This pinned issue]( https://github.com/microsoft/coe-starter-kit/issues/6018) for more details on how to fix this upgrade issue up.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by apulidoo21** [comment]
Hello Jenefer,
We actually updated the CoE to the Newest version successfully but still having the same problems with the old/new default environment.
