### ISSUE TITLE
[ALM Accelerator - BUG]: 

### ISSUE THREAD

**Issue by JM-SHA** [microsoft/coe-starter-kit#6748]
### Describe the issue

The YAML pipeline template “update-deployment-settings.yml” passes the agentOS parameter at position 15 when the associated PS function is called.
![image](https://github.com/microsoft/coe-starter-kit/assets/120573109/7d43590b-eb15-4299-a18d-9ddca8219cae)
![image](https://github.com/microsoft/coe-starter-kit/assets/120573109/00cfbf5e-a316-4ac1-ae47-f8e3e06058c5)
With the August 2023 release, this parameter has now been moved to the last position in the calling PS script.
![image](https://github.com/microsoft/coe-starter-kit/assets/120573109/15880e06-5b27-46e5-a8cf-2f17998829a2)
This means that the value of this parameter is now assigned to the “$usePlaceholders” parameter.
As a result, this parameter is supplied with incorrect values and always runs into the “is not false” condition. However, we use ALM with the configuration “false” for this parameter.

### Expected Behavior

Assigning the value of this parameter OT to the “$usePlaceholders” parameter but to the correct one.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

CenterofExcellenceALMAccelerator_1.0.20230802.1_managed.zip

### Steps To Reproduce

See description

**Comment by mikefactorial** [comment]
@JM-SHA thanks for reporting this and for the detailed description. This was discovered internally during the October release and fixed in the release that went out today https://github.com/microsoft/coe-alm-accelerator-templates/releases/tag/CenterofExcellenceALMAccelerator-October2023. Going to close this out for now but feel free to open a new issue if you run across any other problems. Thanks again!
