### ISSUE TITLE
[CoE Starter Kit - BUG] Solution Upgrade Failed - 8004f01D 

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#6764]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are trying to upgrade the Coe Starter Kit - Core Components from 4.8 to 4.15 but it seems there is an issue when uninstalling the previous update.

![image](https://github.com/microsoft/coe-starter-kit/assets/119695189/26595c79-b5ec-4956-83f7-f4035d79bfa6)
![image](https://github.com/microsoft/coe-starter-kit/assets/119695189/8547fa53-efed-4640-b44a-a66371001514)
![image](https://github.com/microsoft/coe-starter-kit/assets/119695189/ea9a0c67-e937-45c6-b1d7-3837cddcc6cb)

Solution dependencies exist, cannot uninstall. DependencyCount : 3 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Deprecated | [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: 8715a22c-49cc-465c-87cf-3efbb60c5274, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: 3f57123f-83c5-4f98-a319-ed1650901618, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

### Expected Behavior

Upgrade Completes without issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponents

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Import Solution **CenterofExcellenceCoreComponents_4.15_managed**.
3. Set to **Upgrade** and **Enable Plugin Steps and flows included in the solution**.
4. Click on **Next**.

**Comment by manuelap-msft** [comment]
Hello, this is a known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018

We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 

Starting with the August 2023 release, you are no longer be able to upgrade the CoE Starter Kit Core Components until you either [switch to the new http methodology]( https://github.com/microsoft/coe-starter-kit/issues/6009) or [take a local copy of the old custom connector solution]( https://github.com/microsoft/coe-starter-kit/issues/6017) for your personal use.
See [This pinned issue]( https://github.com/microsoft/coe-starter-kit/issues/6018) for more details on how to fix this upgrade issue up.
