### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE Received error when importing center of excellence core components

### ISSUE THREAD

**Issue by snl-meg** [microsoft/coe-starter-kit#6768]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Received error when importing center of excellence core components. Not able to uninstall previous version.
[Center of Excellence - Core Components_import.log](https://github.com/microsoft/coe-starter-kit/files/12784156/Center.of.Excellence.-.Core.Components_import.log)

Attached log. May need to change extension to xml to view it properly.

Also this is the test environment and some of the environment variable may not have been setup. Please advise if I should continue with updating the rest of the solutions.

### Expected Behavior

Updating core components from v4.9 to v4.15. Received an error importing. However still shows that update is a success.

![image](https://github.com/microsoft/coe-starter-kit/assets/85708566/be6056a0-d7af-4a1b-aadb-94d142ab82eb)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

v4.15

### What app or flow are you having the issue with?

solution

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello, this is a known and expected issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018

We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 

Starting with the August 2023 release, you are no longer be able to upgrade the CoE Starter Kit Core Components until you either [switch to the new http methodology]( https://github.com/microsoft/coe-starter-kit/issues/6009) or [take a local copy of the old custom connector solution]( https://github.com/microsoft/coe-starter-kit/issues/6017) for your personal use.
See [This pinned issue]( https://github.com/microsoft/coe-starter-kit/issues/6018) for more details on how to fix this upgrade issue up.

**Comment by snl-meg** [comment]
I did the suggested but when I tried to run the update again, it failed with the same error. I went back and found another suggestion to delete the custom connection outside the solution and I get this error:

![image](https://github.com/microsoft/coe-starter-kit/assets/85708566/a817d9cb-a368-4773-9e89-b14f12611506)

I keep on click delete and the correlation id keeps changing. Not sure what to do next.

**Comment by snl-meg** [comment]
I am also not able to delete by going to connection references

![image](https://github.com/microsoft/coe-starter-kit/assets/85708566/43c76674-98ef-4f4b-b0fd-f26bb57a8973)

**Comment by snl-meg** [comment]
I'm also trying to delete the connection from the flow but I don't see an option. If its deprecated can I just delete the flow entirely?

![image](https://github.com/microsoft/coe-starter-kit/assets/85708566/1a126f5f-d09e-4d4e-9359-7f82aaa0f617)

**Comment by snl-meg** [comment]
Hi Manuela,

Thanks for your responding. I delete the audit log solutions, went to the default solution and removed the custom connector. Then imported the solution. The solution has been importing for about an hour now. It has an end time but it still says “currently importing solution”.
Is that normal for this update? Going from v4.9 to v4.15.

***@***.***

Maria

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
