### ISSUE TITLE
[CoE Starter Kit - BUG]: issue title

### ISSUE THREAD

**Issue by poppynka** [microsoft/coe-starter-kit#677]
Hi,

we have turned on the Admin | Archive and Clean Up v2 (Start Approval for Flows) and Admin | Archive and Clean Up v2 (Start Approval for Apps) flows and we get like 90 e-mails with following error:

![image](https://user-images.githubusercontent.com/6829792/123075398-7dcfb500-d418-11eb-944d-501745c65e35.png)

Basic users don't have access to the CoE Environment, we have set up a security group for CoE Admins and only they have the access. Is this the correct setup?

Thanks

**Comment by manuelap-msft** [comment]
Hello,

no, that's not the correct setup, see: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#security-groups-and-approvals

`We recommend against using security groups to control access to the CoE environment, because it's likely that users who don't have access to this environment will be participating in approvals. If you choose to use a security group to control access, users will have to be a part of that group to work with the archival solutions.`

Thank you for using the CoE,
Manuela

**Comment by JeneferM-MSFT** [comment]
I've added a link to this limitation page from the setup documentation so its easier to find.

**Comment by poppynka** [comment]
Thank you Manuela and Jenefer,

We have been setting CoE up almost a year ago and I think there was no recommendation about not using security groups :) or maybe it was even other way round and it was recommended, I don't remember anymore. 
But anyway, we have missed that we should change our setup, so thanks again for the info and sorry for asking dumb questions :D

**Comment by JeneferM-MSFT** [comment]
Thank you for using CoE!
