### ISSUE TITLE
[CoE Starter Kit - BUG]App Launches for Model Driven Apps not available

### ISSUE THREAD

**Issue by amila-nawarathna** [microsoft/coe-starter-kit#6771]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Dear Team,

I'm pleased to inform you that we have successfully executed the Flow "Admin | Sync Template v3," which has led to the Model Driven Apps being visible in the Power Apps List. Additionally, we have taken the necessary step of enabling Audit Logs. Despite these efforts, we have encountered an issue where we are unable to access the "Last Launched Date" for these Model Driven Apps.

We kindly request your guidance on any further actions or potential solutions to resolve this matter.

Thank you for your assistance.
Best regards,
Amila 

![image](https://github.com/microsoft/coe-starter-kit/assets/80649500/b410f6de-ff7c-4dd3-b27f-7d99ebc60971)

We can see data for Canvas App
![image](https://github.com/microsoft/coe-starter-kit/assets/80649500/b2a09800-94ab-4d9b-b474-8b92ca8be499)

Audit logs enabled Compliance
![image](https://github.com/microsoft/coe-starter-kit/assets/80649500/8fb0e009-173a-4540-afa9-ae36dc37cb57)

Solution Details
![image](https://github.com/microsoft/coe-starter-kit/assets/80649500/1d0f9551-552f-4755-94e4-eaaba077e9bc)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Center of Excellence - Audit Logs

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
That's a known limitation. App launches of model driven apps are not recorded in the Audit Log, and thus not available to the CoE kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by dhingra34** [comment]
The audit log primarily focuses on capturing SDK updates. You can find more information about this in the following documentation: [Dataverse Auditing](https://learn.microsoft.com/en-us/power-platform/admin/manage-dataverse-auditing).

However, it's important to note that this information is available in Power Apps logs as well. You can refer to the details in the following documentation: [Logging Power Apps](https://learn.microsoft.com/en-us/power-platform/admin/logging-powerapps#what-events-are-audited).

Given that the information is readily available in Power Apps logs, it may be more efficient for the Center of Excellence to retrieve this data from Power Apps logs rather than the Audit Logs.

Would you like to consider this as a feature request to streamline the process of accessing this information from Power Apps logs instead of Audit Logs?

**Comment by manuelap-msft** [comment]
Hello,

I'm not sure what you mean - the documentation you pointed to (https://learn.microsoft.com/en-us/power-platform/admin/logging-powerapps#what-events-are-audited) is where we are pulling the Audit Log data from - it's the Microsoft Purview Audit Log. There's no separate Power Apps Log. And this information does not include model driven app launches.

**Comment by xinn-wang** [comment]
Hi I have the following question regarding to the "Last Launched Date" for these Model Driven Apps. 

We can find the report for last opened, created , and last modified date from App Inventory from Power Apps analytics. This report contains both canvas apps and model driven apps, why in the CoE starter kit those data are missing? You can find the report based on following steps: 

- Open Power platform admin center https://admin.powerplatform.microsoft.com/ 
- Click Power Apps under Analytics 
- Click Overview  
- Then click App Inventory 
- Adjust the filter then report is ready 

 


 

Who can view these report: 
- Power Platform admin 
- Microsoft 365 Global admin 
- Delegated admin
