### ISSUE TITLE
[CoE Starter Kit - BUG] Help with DLP Editor

### ISSUE THREAD

**Issue by Tonycpb** [microsoft/coe-starter-kit#6790]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When using the DLP Editor app we have an environment that we know for certain contains flows that are in violation of the proposed DLP policy, but the impact screen does not identify the flows. In fact, the impact screen displays it has only analyzed 5 apps and no flows and nothing is impacted.

### Expected Behavior

we expect the impact screen to identify all apps and flows that are in violation of the DLP policy if implemented.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

September COE version

### What app or flow are you having the issue with?

DLP Editor

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

please use the DLP Impact Analysis app going forward, as we're deprecating the DLP Editor. 

When did you set up the CoE kit? Has the inventory completed running? The DLP app does not pull the inventory data straight from the environment but instead from the Dataverse tables that are populated as part of the CoE kit's inventory processes. It's possible your inventory hasn't finished yet and that's why you don't see all the apps and flows listed. If you open the Power Platform Admin View, do you see everything there?

Manuela

**Comment by Tonycpb** [comment]
I used the DLP Impact Analysis App. I verified the flows that I know will suspend are in the dataverse Flow table. The impact screen does show some flows that will suspend but not all.

**Comment by Jenefer-Monroe** [comment]
If you export the list to csv do you see all the expected flows?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a3893a3f-1395-4c54-a307-65942eb9808c)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
