### ISSUE TITLE
[CoE Starter Kit - QUESTION] Info about flows with a specified trigger

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#6853]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,
Does exist in CoESK Inventory information to list al flows that uses a specified trigger:, for example "When a HTTP request is received"?
Thanks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Yes there is, but unfortunately it requires that you run the flow action details flow to get that information. And many tenants dont run this due to it being so high in API usage.

However if you now what trigger you are interested in, you can go have that flow run for the subset of flows. 

We're adding how to do this to documentation but in the near term its here
https://github.com/microsoft/coe-starter-kit/issues/6603#issuecomment-1739641640

**Comment by albertocastro365** [comment]
Hi Jennefer,
I have seen that my CoE flow to retrieve Flow Actions is enabled but I have incomplete data. I mean: I find some flows with the trigger that I looking for, but  I know that there are more.

In my Flow table I can see this column with 3 values: Yes, No or Empty (No by default)
To confirm: If I want to refresh all data un Flow Connection column of Flow data, Have to mark with Yes in column InventoryMyFLowActionsDetails in All Rows?

**Comment by Jenefer-Monroe** [comment]
Yes that would do it, and the next inventory run will clear this flag after it inventories them. If you have a large tenant though this will be a very long running.

**Comment by albertocastro365** [comment]
OK, I tried this and works fine. Thanks Jennefer.
