### ISSUE TITLE
[ALM Accelerator - BUG]: deploy and build pipelines empty after running "export solution to git"

### ISSUE THREAD

**Issue by groypk** [microsoft/coe-starter-kit#6860]
### Describe the issue

After upgrading to Oct version and using the templates, when I run the 
export-solution-to-git pipeline for my solutions it creates the folders for the pipelines to test and prod but the yml files are empty 

![image](https://github.com/microsoft/coe-starter-kit/assets/5492973/783d90f7-fdd7-4645-852f-beef6c1d8de1)

### Expected Behavior

The yml pipelines are empty for build and deploy to test and prod.

Previous versions of the tool worked, noticed this after the October upgrade, especially after the Upgrading the pipeline templates

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231012.1

### Steps To Reproduce

![image](https://github.com/microsoft/coe-starter-kit/assets/5492973/b1985898-9cb1-4972-ba5f-06d256f28162)

```[tasklist]
### Tasks
```

AB#186

**Comment by RajeevPentyala** [comment]
@groypk Could you share the log of "Update Deployment Settings" task of 'export-solution-to-git' pipeline?

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/fa0e0bc4-31cc-469c-b81a-0265628b81fc)

**Comment by groypk** [comment]
> @groypk Could you share the log of "Update Deployment Settings" task of 'export-solution-to-git' pipeline?
> 
> ![image](https://user-images.githubusercontent.com/104883923/274868242-fa0e0bc4-31cc-469c-b81a-0265628b81fc.png)

@RajeevPentyala looks like I was able to make it work by removing the space from the name of the Deployment step, it was initially "Name Test" and couldn't find the YML file in the Update Deployment settings step, its creating the pipelines know , so assuming the space was the one causing the issues

![image](https://github.com/microsoft/coe-starter-kit/assets/5492973/f61f8913-cbcd-4a28-b581-3c4c46f59048)

**Comment by mikefactorial** [comment]
@groypk thanks for reporting back the solution you found. Out of the box the ALM Accelerator only supports Validation,Test, Prod steps. You can customize the steps by adding new build templates to your repo or specifying the Build Template Path on the step to point to an existing build template (e.g. /Pipelines/build-deploy-test-SampleSolution.yml). Closing this out as expected behavior. See https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/customize-deployment-pipelines for more details on brin your own templates.
