### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL Upgrade Cleared Tables? - please update after-setup instructions

### ISSUE THREAD

**Issue by nwmb** [microsoft/coe-starter-kit#6897]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We upgraded the COE Toolkit with the BYODL, and honestly, its been quite painful because of the lack of clear documentation - predominantly regarding the dataflows.

During the last upgrade, I got the updates installed.  Removed and reinstalled the Power BI dataflow via the Power BI workspace (didn't seem there was a method to update using the .json file?) and was feeling pretty proud.  I forgot, however, about the dataflows that exist in the COE environment and couldn't find documentation to reference on the upgrade process when BYODL in place.  

Fast forward to today, it appears that the connection information in the dataflows within the Power Platform environment was reset during the upgrade and the dataflows have been failing.  This is a relatively easy fix and I've been working through getting those updated to run again - however, the more painful piece, is that it **appears the failing workflows may have wiped out the environments, apps, flows, etc. tables within the COE**.

Unfortunately, the environment records had been assigned descriptions and use cases and other metadata that went away with the deletion of these records.  I'm not sure if something else is at play here, but looking for advice and wanting to raise this in case it happens to others!

Also, if there is a good document that outlines how to upgrade the COE with BYODL on - please share!

### Expected Behavior

1. Better documentation on BYODL upgrades on the COE upgrade page (https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup)
2. Dataflow failures keep data instead of removing data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

BYODL Dataflows

### What method are you using to get inventory and telemetry?

Data Export

AB#263

**Comment by Jenefer-Monroe** [comment]
Hello I'm so sorry you lost your metadata. 
Unfortunately a record being missing from a refresh in the only way we know that an object (envt etc) has been deleted. We look for that (for envts) here CoE BYODL - When Environment dataflow refresh is complete: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c97de57d-543a-4b12-9035-2cf6d10872be)

When we detect these cases we do not delete them though we only mark them deleted. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/417e7acd-cdec-40cb-aa51-f27af04d4381)

The delete itself happens in this flow CLEANUP - Admin | Sync Template v3 (Check Deleted) dependent upon an envt variable. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ddb7c75b-2a05-4995-9bef-a0dc33536ba6)

So the way to avoid this happening, so that you can restore these records, is to use that env variable, set it to No, and then while we will still mark these objects deleted, you could fix up the dataflow issue and then they would be restored with their metadata. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c6bca59f-af7e-40d5-b817-6f0754658e94)

We dont have that env var set to no by default to avoid capacity overage. So its recommended if you do this, to have a periodic flow on your own side that will delete these after some time when you feel they are safe to remove (perhaps after 6 months of being marked deleted or something like that)

**Comment by Jenefer-Monroe** [comment]
Regarding the instructions being improved, it does seem that the [after setup](https://learn.microsoft.com/power-platform/guidance/coe/after-setup) article could use updated to refer to the setup and upgrade wizard. 

In short the recommendation is now much simpler, which is to install the core ugprade, then boot the setup wizard and use it to walk you through the steps.

**Comment by nwmb** [comment]
Thank you for the fabulous information and the assistance Jenefer!  Switching over to the BYODL side has been a massive improvement for us gaining much broader visibility into usage (flow runs, model driven apps) than was available before.  I really appreciate all the hard work y'all continue to put into the CoE!

**Comment by nwmb** [comment]
Do you think it's worthwhile to provide steps to replace the "PowerPlatformAdminAnalytics-DF.json" somewhere?  The setup wizard brings you to information on how to install the data flow [https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#import-power-bi-dataflows](url) but doesn't seem to cover how to update it?  

I ended up deleting and re-importing it from scratch.

**Comment by Jenefer-Monroe** [comment]
We can look through that documentation as part of this bug too yes.

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
