### ISSUE TITLE
[CoE Starter Kit - BUG] New PowerApps Canvas Apps and SharePoint Form App not tracked in Power Platform Admin View

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#6903]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

New Canvas Apps and SharePoint Form Apps created in the tenant are not getting tracked in the Power Platform Admin View Model -Driven app. The last App Created on date was 7/19/2023.

### Expected Behavior

All Power Apps created in the tenant should be displayed in the Power Platform Admin View Model - Driven App.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Power Platform Admin View Model - Drive App

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Log into CoE environment and launch the Power Platform Admin View Model-Driven App
2. In the Left Navigation, click on PowerApps Apps
3. In the View Selector, choose Canvas list view
4. Sort App created On from newer to older

AB#269

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

And also please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

Lastly, please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by dcurt1977** [comment]
Here's a screenshot of the solutions.
![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/6bffc836-b697-463c-9309-b478dfe8ee1a)

Here's a screenshot of the region where the environment is in.
![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/b12b0db2-19de-445f-b4c5-df45a9beaa39)

The flow named Admin | Add Maker to Group was turned off, it is now turned all. I attempted to turn on the flow Admin | Sync Template v3 (Environment Properties) but getting the below error message.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/9480ca8e-aa6b-499b-8394-2cae8a9ddd70)

**Comment by Jenefer-Monroe** [comment]
That error message indicates that there are other flows not yet turned on. Can you please go to the Core solution > Cloud Flows > search for the string **_sync help_**

You should see 3 flows and they all need to be turned on. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f21ddb0f-0d09-4bda-a2a7-3b6ac1c2ed27)

**Comment by dcurt1977** [comment]
All the above mentioned CoE Flows are turned on.

**Comment by Jenefer-Monroe** [comment]
Great were the app/flow ones off? How about these 2 flows? Are they on? And have they been running?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/464b9e0b-e19d-4816-be7d-0d8e9a451b98)

**Comment by dcurt1977** [comment]
The two above mentioned flows now turned on. The flows are not running as yet.

**Comment by Jenefer-Monroe** [comment]
No they will kick off with the next run of the driver flow. Is it turned on and running? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fd976e44-936e-470a-97df-e3e542630834)

**Comment by dcurt1977** [comment]
Yes, the above-mentioned flow is turned on and running.

**Comment by Jenefer-Monroe** [comment]
great then please check tomorrow to see if you are seeing new objects now that all the flows are on.

**Comment by dcurt1977** [comment]
New objects are now updated in the Power Platform Admin View Model-driven app.
