### ISSUE TITLE
[CoE Starter Kit - QUESTION] Changing environment URL breaks everything, how fix?

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#6922]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I changed the URL for the environment that hosts CoE and now everything has broken :-(
Is there a way to fix it?
I was expecting the original URL to continue to work along side the new one.
e.g. the flows either won't run (triggers are broken) or they run with errors, the Power BI report is still using the old URL and won't refresh the data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

all of them

### What method are you using to get inventory and telemetry?

Cloud flows

AB#293

**Comment by Jenefer-Monroe** [comment]
Hello, you've hit an issue with the product itself here but I can hopefully get you back to working. 
- The original link will no longer work once you change, so you will need to republish your PBI to point to the new url
- Triggers should still work although sometimes the product caches urls so you may need to turn off and back on all the flows that you are not seeing work. 

Please let me know if that gets you unblocked!

**Comment by MartinWGT** [comment]
Thanks Jenefer. I created a new Power BI report so that was fine. But I'm really struggling with the flows, mainly "Admin | Sync Template v3 (Driver)" to kick things off. It was running but never ending (20hrs+ instead of 30 mins). 
So, I decided to rename the environment URL back to what it was originally. This partly helped. I deleting and recreating some connections to Dataverse and it ran ok , but it created a solution layer and removing the layer turned off the flow and wouldn't let me turn it on due to permissions with the connector.
It's tempting to start all over again and deploy from scratch but that takes a lot of time. But what I am trying now is an environment restore. I've not done that before so will see if it works. I'll report back when it completes.

**Comment by MartinWGT** [comment]
The restore didn't take long and is now complete, but I have the same error trying to turn on the flow. Do you know how I can fix it without creating a layer? 

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/83bcdf6a-ad13-498c-b2ea-58d8d4220237)

**Comment by Jenefer-Monroe** [comment]
First do note that the driver flow has a built in delay, so it can take quiet a while to run. Here is some information about that

**Delay Inventory**
The delay is expected, and will delay a randomized length of time before continuing and kicking off inventory each day. 
This is done to prevent all the organizations that use the CoE from beginning their sync flows at the same time as they use a lot of Dataverse API calls.
Why? To protects the Dataverse service on the Microsoft side - the CoE Starter Kit is installed in thousands of tenants, and as you can image performs quite a lot of Dataverse read/write actions during an inventory run. The way scheduled flows work, unfortunately, is that when they are shipped in a managed solution they run at the very same time independent of the customer timezone - so they may run at 7am PST, 3pm GMT etc etc. This meant that we saw many many millions (or more) of Dataverse calls at the very same time each day, which meant that with an increase in installations of the CoE kit it may have caused a service disruption. That's the last thing we want! In order to balance out these Dataverse calls we had to make sure customers run the inventory at different times during the day - our ideal solution would have been to provide a parameter to the Schedule trigger, unfortunately that's not possible in Power Automate today (the Schedule trigger doesn't work with Environment Variables etc) so the only solution we could think of is introducing a random delay after the flow kicks off. We know and appreciate that's not ideal but it's the only thing we could think of to protect the service on our side.

**Comment by MartinWGT** [comment]
Thanks Jenefer, I was just replying at the same time. The delay action hasn't been slowing things down, it had moved onto to later scopes.

However,  I've found the answer regarding broken connections, from an old community post...

Go to Solutions -> find "Default Solution" -> Find your connection reference and edit it's properties from here.

The flow now turns on. I'll check all the other flows; hopefully it will be all working again. 

I'm wondering if changing the environment URL just needed a new connection and to update the connection reference in the default solution.

**Comment by Jenefer-Monroe** [comment]
Make sure also when you did your restore that the CoE environment did not land in admin mode. That happens sometimes with environment operations.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7e5ad26d-c27f-4e6c-9cba-d63203b2df3e)

**Comment by MartinWGT** [comment]
Thanks for that. It was in admin mode (I'll google what that actually means!).
Going back to the delay, I have set the environment variable to stop the delay in my dev environment. When it's working again I'll enable the delay.

**Comment by Jenefer-Monroe** [comment]
Regarding that broken connection. 
Go see if it shows broken on the connections page, and if so fix it there and see if that resolves things for you. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ee11c315-355e-44bb-9507-13ca9d145cca)

If not then delete the Legacy Dataverse connector there and recreate
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/81927f9b-c401-437a-afb6-7df1282c3c90)

Then go to the Default Solution > Connection References > Fix up the Connection Reference to point to this new connection. 
While you are there you may as well make sure all your connection references are pointed correctly too. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e2ff0d7a-0e13-428d-9592-1edeb3cf19e6)

**Comment by Jenefer-Monroe** [comment]
Looks like you were ahead of me all the way here haha :)
Please do let me know if this resolved things for you.

**Comment by MartinWGT** [comment]
Hi Jenefer,
It's all looking good now. I've even changed the environment URL to what I wanted.
Thanks for your quick replies.

**Comment by MartinWGT** [comment]
I was afraid this might happen. I am trying to update to the latest Core solution but I'm getting an error. When I restored my environment, it changed all the app Ids. Would this prevent the solution from updating? This is the error I get...

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/c362fc00-2547-47ee-a485-7f9160a5ee39)
