### ISSUE TITLE
[CoE Starter Kit - QUESTION] How/When to Install Audit Logs After CoE Update

### ISSUE THREAD

**Issue by BB-BITS** [microsoft/coe-starter-kit#6925]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am updating to the October release of CoE from version 4.3 (Feb or March).  I am following the Microsoft documentation, https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup.  It does not specifically say anything about installing the Audit Log solution, although I see CenterofExcellenceAuditComponents_3.13_managed in the download zip file.

When I ran the CoE Setup and Upgrade Wizard, there are several features listed with the error "Missing prerequisite:  ImportCenterOf ExcellenceAuditComponents before configuring this feature".

Should I now import the CenterofExcellenceAuditComponents_3.13 solution?
Is there anything else I should set up first?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

October 2023

### What method are you using to get inventory and telemetry?

None

AB#296

**Comment by Jenefer-Monroe** [comment]
Hello the audit log solution has been deprecated. It used to be in a separate solution due to the custom connector present, and the issues custom connectors have with import. 

We now support an http methodology instead of custom connector for this work and so no longer require a separate solution, all the flows and things you need are already in Core, and you can follow these steps for setup
[Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by frcelaya** [comment]
Thanks Jenefer,
We are using the method you described and it's been working fine, our only issue is that the only type of event captured is "LaunchPowerApp". We would like to have more types of events captured, for example, when Power Apps are deleted, Power Automate flows created, etc.

Is there any guide or official instructions on how to do this?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
