### ISSUE TITLE
[CoE Starter Kit - BUG]: Legacy connectors and RDS

### ISSUE THREAD

**Issue by samadane** [microsoft/coe-starter-kit#694]
**Describe the bug**
I see that some of the flows have the old legacy dataverse / cds connector.  Are these going to be removed before RDS deprecation?

**Component (please tell us which flow or app you are experiencing issues with):**
Admin | Sync Template v3 (PVA) Flow
![image](https://user-images.githubusercontent.com/43175066/123318781-98c82500-d4fd-11eb-9614-0358ee77f3e4.png)

Admin | Sync Template v3 (Model Driven Apps)
Admin | Sync Template v3 (Desktop flows)
Admin | Sync Template v3 (Desktop flow runs)

CLEANUP flows as well

**Comment by JeneferM-MSFT** [comment]
The new Dataverse connector does not yet support us going outside of the Current environment. And some objects (Model Driven Apps, Desktop Flows, Power Virtual Agents) require that we fetch the data about them through the dataverse tables in each environment in order to gather the inventory. 

So that is what we are waiting for before we can migrate the last of these connectors to the modern connector. 

Thanks for using CoE

**Comment by samadane** [comment]
Will this work after June 30th then?

**Comment by JeneferM-MSFT** [comment]
Can you share where you see a June 30th deadline for that connector?

**Comment by JeneferM-MSFT** [comment]
Chatted offline with Sam and we are covered here. 
Thanks for checking in!
