### ISSUE TITLE
[CoE Starter Kit - QUESTION] Haven't updated since March release

### ISSUE THREAD

**Issue by FredrickLucerne** [microsoft/coe-starter-kit#6957]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Should I install updates month by month i.e March -> April then the May, June July updates separately?  Or will I be ok to update to the latest release?

Just concerned since I have not updated the CoE kit in so long.

Thank you!

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The general advice is to upgrade every 3 months as we dont test back past that. 
We happen to be testing further back right now (to Feb release) for an upcoming mandatory upgrade. 
So this time you should be fine (see caveat below) but typically do upgrade more frequently. 

There is one known upgrade blocker due to the deprecation of the audit log solution. If you have that solution installed please look at this issue before attempting to upgrade https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
