### ISSUE TITLE
CoE Maker Command Center - Environment Creation Requests not working

### ISSUE THREAD

**Issue by jcgds** [microsoft/coe-starter-kit#6967]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, I'm trying to create a request for a new environment through the CoE Maker Command Center as shown in the image, however, after selecting the components I need and clicking OK it doesn't advance to the next screen. Please, is there any additional procedure that should be carried out or is it in fact a bug? If it's a bug, is there any forecast for fixing? Thank you! 

![1 3ErrorClickMakerEnvironmentCreationRequests](https://github.com/microsoft/coe-starter-kit/assets/147111987/04d43e83-95fe-4ee9-97b9-ea08e8dce64f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

CoE Maker Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#441

**Comment by manuelap-msft** [comment]
Hello,

this is a known issue, we unfortunately missed a configuration on the panel here. It is fixed for the November release due to be released next week. We're tracking this issue here https://github.com/microsoft/coe-starter-kit/issues/6815

I'll close this out as a duplicate as we're already tracking this bug.
