### ISSUE TITLE
[AA4AM]: Check no current value is present for environment variables on release

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#698]
Shipping a solution with current values in the environment variables can lead to issues as customers import the solution (e.g. they are not prompted to provide their values, flows are working off our test values).

Even though we can follow best practices in development, current values may sneak in and if the release pipeline could check for current values and fail, this would ensure a higher quality of release.

**Comment by mikefactorial** [comment]
The solution here is that on export the pipelines will look for a pipeline variable called DoNotExportEnvironmentVariableValues (Optional). If  the value of that variable is true then an error will be thrown in the export pipeline notifying the maker that they have included environment variable values in their export. If the variable is set to false or the variable does not exist then the check will not happen

**Comment by mikefactorial** [comment]
The reason we are checking these on export rather than as part of the release pipeline is to ensure that the values don't end up in source control which will be the ultimate source of truth. As of right now these are all or nothing but we could allow only certain environment variables in the future to contain current values when exported

**Comment by mikefactorial** [comment]
@manuelap-msft This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.
