### ISSUE TITLE
[CoE Starter Kit - QUESTION]  Upgarde to latest version is failed 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#6983]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

While upgrading to latest version of CoE toolkit 

I have tried to upgrade CoE Core  solutions 

I could see latest version of CoE 4.16 solution is installed but older CoE Core Solution 4.9 is still exists and I found below error 

Exception message
Solution dependencies exist, cannot uninstall. DependencyCount : 3 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: 4df5e00d-871c-4a1d-816a-84ae2e225ee5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: 978e2c60-1d8c-4557-8675-ab275ff2b187, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

Could you please help me in understanding the issue ? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

Cloud flows

AB#589

**Comment by Jenefer-Monroe** [comment]
When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 
These will never converge or repair on their own, you will need to take action to resolve. 
If you go to history you can find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)

For your case it is sounds like its due to this known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018 
We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. Issue https://github.com/microsoft/coe-starter-kit/issues/6018 will walk you through how to address.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
