### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrading Core Components 4.11 to 4.13 fails. Cannot start another [Uninstall] because there is a previous [Uninstall] running at this moment. Use Solution History for more details. -- The solution installation or removal failed due to the installation or removal of another solution at the same time. Please try again later.

### ISSUE THREAD

**Issue by da1davis** [microsoft/coe-starter-kit#6987]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am upgrading the Core Components of the CoE Kit from v.4.11 to v.413 and getting the exception message in the Subject line.
I doubled checked there is no dependencies on the Audit Log from the Default solution lingering around. 
I tried deleting both and applying the upgrade on v.411 and still nothing works. 

![image](https://github.com/microsoft/coe-starter-kit/assets/126509323/5aeb7ab1-b69e-4db3-b1e9-9113d27ffeb5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Manage Solution

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Typically this happens when there are connection references to the old custom connector still in the system that you just cast see from the UX. 

Please see the following from https://github.com/microsoft/coe-starter-kit/issues/6018:

And some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use  powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest)  these remaining connections to the old connector.

**Comment by da1davis** [comment]
@Jenefer-Monroe .
Thanks for your help. However, there are no Audit Logs references under the Default Solution > Connection References as outlined in the provided link. And the original error message I am seeing when trying to delete the Core Components solution doesn't mention any dependencies as in the provided link. My error message is as mentioned on the Subject of this issue. Anything else we can do?

**Comment by Jenefer-Monroe** [comment]
oh I see sorry I got distracted by your reference to the audit log. 
Your error in the subject line is just a temporal one. It implies that something else was currently installing when you tried to install. 
This can happen without you knowing as the product itself does install solutions as well. 

It looks like now you have a a core and a core_upgrade 
So please deleted the _upgrade and try to upgrade again. Then see what error message, if any, you get.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
