### ISSUE TITLE
[CoE Starter Kit - QUESTION]  Older environments are not showing any "Desktop Flows".

### ISSUE THREAD

**Issue by gp-empire** [microsoft/coe-starter-kit#6988]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have deployed the October BOYDL version and am not getting RPA data from most of my environments.

I'm only getting RPA's from an environment that was created within the last 60 days.  Older environments are not showing any "Desktop Flows".
Older environments are not showing the Environment Maker because that user is no longer an active user in our tenant.  Is this related?   Shouldn't the "Environment Maker" be the Owner, not the Creator?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023

### What app or flow are you having the issue with?

Flows Dataflow

### What method are you using to get inventory and telemetry?

Data Export

AB#592

**Comment by Jenefer-Monroe** [comment]
Hello. It sounds like we have two issues here, lets use this one to track the Desktop Flows being missing, can you please post a second issue for he envt maker field? Our processes require we try to have single issue bugs.

**Comment by Jenefer-Monroe** [comment]
First note that we have many issues with the way we inventory Desktop Flows in existing versions of the kit due to some issues with the legacy Dataverse connector. We are happy to say that with the Nov release we have finally been unblocked from moving the Desktop Flow inventory to the modern connector! This is tracked by https://github.com/microsoft/coe-starter-kit/issues/6946

So it might be that the issue you are having is known from the old connector, but lets make sure. 

Please find an environment that that desktop flows that hasnt been inventoried
Go to the recent runs of Admin | Sync Template v3 (Desktop flows)
Add the display name to the columns shown, hit all runs if needed, and find the most recent run of your target envt. Open that run
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5fce519d-0fd8-43ba-8a82-bcbeda24f33e)

Do the desktop flows show up in the download of this step?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3c7ea8ca-280d-462e-84b0-7041400b4cf0)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
