### ISSUE TITLE
[CoE Starter Kit - BUG] Child flow in Admin | Sync Template v4 (Apps) is failing

### ISSUE THREAD

**Issue by henryed07** [microsoft/coe-starter-kit#6989]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The following error is happening when running the above flow - calling the Apps Sync Template
{
  "error": {
    "code": "TriggerInputSchemaMismatch",
    "message": "The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Required properties are missing from object: boolean.'."
  }
}

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.16

### What app or flow are you having the issue with?

 Admin | Sync Template v4 (Apps)

### What method are you using to get inventory and telemetry?

None

AB#593

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
