### ISSUE TITLE
[CoE Starter Kit - BUG] PBI: data source error: The 'admin_userprinciplenamewithoutspecialchars' column does not exist in the rowset

### ISSUE THREAD

**Issue by RosThom** [microsoft/coe-starter-kit#6992]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have just upgraded from version 4.11 to 4.16 and I am using the BYODL_CoEDashboard_October2023.pbit.
I published the report successfully but it is getting the error below when refreshing.
Please can you advise how to fix.

Data source error: The 'admin_userprinciplenamewithoutspecialchars' column does not exist in the rowset. Table: Maker.
Cluster URI: WABI-NORTH-EUROPE-J-PRIMARY-redirect.analysis.windows.net
Activity ID: 8ad243ec-c89c-4479-9ea3-6ffb46efdd0a
Request ID: b7b61ad1-a44d-55de-ae1f-e4062c3eb4f1
Time: 2023-11-03 15:17:19Z

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

PBI refresh

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Follow instructions to set up PBI dashboard from here.
https://learn.microsoft.com/en-gb/power-platform/guidance/coe/setup-powerbi

Published successfully as pbix, but pbix is not refreshing

AB#600

**Comment by RosThom** [comment]
For info, Dataflow refreshed successfully

**Comment by Jenefer-Monroe** [comment]
Each time you download a new version of the kit https://aka.ms/coestarterkitdownload, you will find new PBIT files. 
It’s recommended that you update these each time. While sometimes you can get away without doing that, other times you will fail to instantiate because (as in this case) a field has been removed.

**Comment by RosThom** [comment]
I did use the new PBIT file BYODL_CoEDashboard_October2023.pbit.

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by RosThom** [comment]
Hi,  I rebuilt the Power BI report and managed to get rid of this particular error, but the PBI report still won't refresh on a scheduled refresh.  I can refresh from desktop, but when I try a scheduled refresh we get the error below.

Data source error[ValidateMarkupTags][ccon]Expression.Error: The key didn't match any rows in the table.. Key = [ccon][workspaceId = "491c443e-e218-41dd-b695-82e56f840d72"][/ccon]. Table = [ccon]#table({"workspaceId", "workspaceType", "Data", "workspaceName", "Tags", "ItemKind", "ItemName", "IsLeaf"}, {})[/ccon]. [/ccon];[ccon]The key didn't match any rows in the table.[/ccon]. The exception was raised by the IDbCommand interface. Table: App Connection Reference.

The same error sometimes occurs with table Flow Connection Reference.  I searched for this bug and can see this has happened before but there was no resolution offered.

Refresh BYODL PBI in web failure: Expression.Error: The key didn't match any rows in the table. #4740

**Comment by RosThom** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/148232935/49923ead-6942-46a4-8974-fb8b6ac19908)

**Comment by Jenefer-Monroe** [comment]
This sounds like an issue with the data in your tenant. 
Can you please make sure this flow is turned on, running, and passing? CLEANUP - Admin | Sync Template v3 (Delete Bad Data)

**Comment by Jenefer-Monroe** [comment]
Regarding this issue
### This exceeded the maximum size '209715200' bytes allowed. issue for Connection Identities
The CoE kit is built on top of the product, and as such bound to platform limitations. 
This failure is due to a limitation on the amount of data connectors can bring back, which unfortunately, you have exceeded. 
Note also that deleting individual flows and apps will not delete the connections they use, so they do pile up over time and deleting objects does not 

We cannot fix that, nor can we safely create a script which will reliably connections safely for all tenants that will work over time. 

Here are some things you can do to address:
1. Manually use powershell to [explore](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) unused or errored connections. That technology does not have this same size limitation.
2. Contact [product support](https://learn.microsoft.com/power-platform/admin/get-help-support) to have them help you clean up old connections

Hope that helps, and sorry for the inconvenience.

**Comment by RosThom** [comment]
Morning
The App Connection Query looks fine as far as I can see.
For info, the workspace that the error says is missing is the one I add to the parameters i.e. the workspace where the data flow is stored.
Is there anywhere else you think I should check?

Thanks

Data source error[ValidateMarkupTags][ccon]Expression.Error: The key didn't match any rows in the table.. Key = [ccon][workspaceId = "491c443e-e218-41dd-b695-82e56f840d72"][/ccon]. Table = [ccon]#table({"workspaceId", "workspaceType", "Data", "workspaceName", "Tags", "ItemKind", "ItemName", "IsLeaf"}, {})[/ccon]. [/ccon];[ccon]The key didn't match any rows in the table.[/ccon]. The exception was raised by the IDbCommand interface. Table: App Connection Reference.

**Comment by RosThom** [comment]
Also, the refresh is successful in the Desktop app, just the scheduled refresh is getting the error.

**Comment by Jenefer-Monroe** [comment]
Oh perhaps its the permission in PBI.Com then. I usually have to fix that up every few months for some reason.

It sounds like the issue would be in the report itself
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b7bcb39b-1534-4126-8773-a385c591b6cf)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6234f0f5-9145-481f-b0aa-86197a4243de)


But please check the Dataflow while there
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f87b20ec-44ed-4a4e-9ad4-67d3ca568630)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e2c46307-e69c-47fd-a41b-7aacfb0113b0)

**Comment by RosThom** [comment]
You were right - it was a permissions error.  Thanks very much for your help

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
