### ISSUE TITLE
App Registration Used in CoE Power Automate Flow Unable to Connect to Microsoft Graph

### ISSUE THREAD

**Issue by mattahearn** [microsoft/coe-starter-kit#6993]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

We are trying to stand up the PP CoE Kit on a DOD tenant and running into a 401 unauthorized error in the Power Automate Flow called "_Admin | Audit Logs | Sync Audit Logs (V2_)" when it tries to access Graph audit logs during the "**_ListAuditLogContent_**" step.  Our Azure App Registration is using the prescribed "ServiceMessage.Read.All" permission as detailed here --> https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-an-azure-ad-app-registration-to-connect-to-microsoft-graph 

Any advice would be appreciated.

![Admin_Audit_Logs_Sync_Audit_Logs_V2](https://github.com/microsoft/coe-starter-kit/assets/59938342/53662dfb-50cd-4ec8-a8dc-fb12710f0873)

Matt Ahearn
Sr. Consultant - Fed Civ Biz Apps

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

CenterofExcellenceCoreComponents_4.15_managed

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#601

**Comment by Jenefer-Monroe** [comment]
These audit log flows require a separate set of setup instructions. Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

Note that since the flow is already on, if the flow still fails after you run all the setup instructions, please be sure to turn it off and back on as sometimes flow cache env vars and you wont have the correct values since you are DoD (non-default)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
