### ISSUE TITLE
Orphaned Flows not showing in admin flow app

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6995]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

There seems to be some orphaned flows not showing.  We get some, and some others don't show. 

This is a problem as we monitor the flows to ensure that we don't have flows in production that stop.

We are aware that users shouldn't own prod items, and we are cleaning it up, but it's a problem at the moment.

Also, is there automated warnings from the tenant?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Admin Flow App

### What method are you using to get inventory and telemetry?

Cloud flows

AB#603

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not following you here. 
What do you mean here? `There seems to be some orphaned flows not showing. We get some, and some others don't show.`
Do you mean have there are some flows missing from your inventory?

**Comment by PPCan** [comment]
Correct.  There are flows that are owned by users that have left, and thier AD accounts are gone,  effectively orphaning the flows.

Some of these flows are showing in the CoE, and others are not.  We don't know why, and this is a very important feature!

**Comment by Jenefer-Monroe** [comment]
OK since this isn't a general problem, you will need to find a specific case to repro so that we can debug.
Find a flow that you expect to see in the inventory but do not and note its display name and the name of the environment it is in
For my example I'm looking for a flow called **_test flow_** in my default envt
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8d2d766f-888e-49dd-b467-616cebfd8c12)

Go to the details page of **_Admin | Sync Template v4 (Flows)_**
Edit the columns to show display name and go to all runs if needed to find the envt with your  missing flow. Click the timestamp to open the run
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/404d87fb-0744-4bd3-972c-69b1606c47c4)

See if the flow showed up in the output of this action
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d16182cb-640f-492d-867d-13928e0e2de6)

Next see if the flow still shows up in the out of this action
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b0f3b6d8-2c38-4555-a88a-fa79c7aaedce)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
