### ISSUE TITLE
[CoE Starter Kit - BUG] Custom connector Office 365 Management API not getting updated

### ISSUE THREAD

**Issue by Saj-H** [microsoft/coe-starter-kit#6997]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have a custom connector for Office 365 Management API which was created 1 year ago. The certificate has expired and we have renewed the certificate on 27th September 2023. However when we try to edit and put the new values for client secret ID, it is throwing the below error in the final Test stage. 

Error: Operation failed (401), see response below Headers: { "cache-control": "no-cache", "content-length": "61", "content-type": "application/json; charset=utf-8", "date": "Thu, 28 Sep 2023 12:17:00 GMT", "expires": "-1", "pragma": "no-cache", "www-authenticate": "Bearer error=\"invalid_token\"", "x-aspnet-version": "4.0.30319", "x-ms-apihub-cached-response": "true", "x-ms-apihub-obo": "false", "x-powered-by": "ASP.NET" } Body: { "Message": "Authorization has been denied for this request." } 

Please note that we have updated the connector with the latest Azure App registration certificate information. Hence could you please let us know how to fix this error with the custom connector.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### What method are you using to get inventory and telemetry?

Cloud flows

AB#608

**Comment by Jenefer-Monroe** [comment]
We have deprecated the Custom Connector mechanism for collecting audit logs due to issues like this. It's highly recommended that you switch to the new HTTP methodology [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

My guess is that you ended up with a bad connection, perhaps due to the wrong identity provider being selected as in [issue 4808](https://github.com/microsoft/coe-starter-kit/issues/4808)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
