### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to share DCC with Makers

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#7000]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I've enabled pay as you go for the Developer Compliance Center app and am trying to share it with makers.
I'm following this https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#share-apps-with-makers that says to assign the 'Power Platform Maker SR' security role, but this role is not available to select (it does exist though).

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/9e622091-a810-42a6-b44c-8c1245722831)

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/13ff8197-7788-4e86-ad39-55c3eaa2746d)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023

### What app or flow are you having the issue with?

DCC

### What method are you using to get inventory and telemetry?

Cloud flows

AB#611

**Comment by Jenefer-Monroe** [comment]
Hello. In order to share a MDA with users you first need to share the app as a whole with the desired security roles
Share the app as a whole with the Security Role
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3d532a9-92f5-4765-aeef-a9e171f19a46)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5377d117-c406-4293-bd3b-1c966f1569a8)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c9d7d6a-5e3e-4dab-b8d9-9749fcadaa15)
Now those SRs can be applied to users you share the app with.
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f8976c2-b594-43da-b56c-fa4932fd7400)

**Comment by MartinWGT** [comment]
Brilliant, that got it working. Thank you!

**Comment by Jenefer-Monroe** [comment]
Thank you for letting me know!
