### ISSUE TITLE
[CoE Starter Kit - BUG]: DLP App Analysis Impact Email not sent to correct owner

### ISSUE THREAD

**Issue by tchinnin** [microsoft/coe-starter-kit#703]
**Describe the bug**
On the DLP Editor V2 App, on impact analysis, when sending an email to a Flow (or app) owner because a DLP rule is going to be violated, the email is not sent to the correct owner.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - 2.1.70
 - App DLP Editor V2

**To Reproduce**
1. Go to app DLP Editor V2
2. Create a new DLP policy
3. Block connector
4. Go to impact analysis screen
5. Select a first flow
6. Select a second flow
7. Send Email to the owner
8. See Email not sent to the correct owner

**Expected behavior**
Email sent to the selected Flow owner

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Thank you for reporting. We seem to always send to the selected app owner, even when the flows are what you are working with. 
But in your notes you say you repro this for apps as well. Can you please confirm? I would expect this to work for apps and not flows today looking at the logic.

**Comment by JeneferM-MSFT** [comment]
Fixed assuming the above is true (that this was only broken for flows, and working for apps per my testing). Please let me know if I'm off and you are seeing something else. 

Also fixed to using "Derived Owner" for the flow since that is our tracking mechanism for the person charged with managing a flow in the CoE

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
