### ISSUE TITLE
[CoE Starter Kit - BUG]: DLP Editor V2 - Analysis impact - wrong modified date

### ISSUE THREAD

**Issue by tchinnin** [microsoft/coe-starter-kit#704]
**Describe the bug**
When viewing detail on Impact analysis screen of DLP Editor V2 app, the Modified date is incorrect

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - 2.1.70
 - App DLP Editor V2

**To Reproduce**
1. Open DLP Editor App
2. Update a DLP to see impact analysis
3. choose a Flow impacted. 
4. See modified date is not correct

**Expected behavior**
Flow Modified date should be displayed instead of default dataverse modified date

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
I presume you mean this spot yes? For apps and flows. 
![image](https://user-images.githubusercontent.com/62659043/123816669-bbb75800-d8b4-11eb-8271-49c4a338ca13.png)

Thanks for spotting! Local fixed for July

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
