### ISSUE TITLE
[ALM Accelerator - BUG]: Ordering flow activation no longer possible

### ISSUE THREAD

**Issue by BeekvanV** [microsoft/coe-starter-kit#7047]
### Describe the issue

I have added multiple flows to my solution but it is no longer possible for me to activate them in the correct order using the deployment setting.
![image](https://github.com/microsoft/coe-starter-kit/assets/86412280/623ea8ea-480a-42a7-8b10-5b50c184df2e)

Was this change made by design or do I need to do something to re-activate it?

### Expected Behavior

Possibilty to order the activation of flows with deployment settings.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231012.1

### Steps To Reproduce

1. Create solution with multiple flows
2. Open ALM Accelerator canvas app
3. Select Configure deployment settings for given solution
4. Navigate to flows tab

AB#756

**Comment by mikefactorial** [comment]
@BeekvanV thanks for the question. Late last year we introduced retry logic into the activation process in the pipelines that made the ordering of the flows obsolete. We left the functionality in place for a while as a fallback measure if the retry wasn't sufficient but decided to remove it recently since it should no longer be necessary.

**Comment by BeekvanV** [comment]
> @BeekvanV thanks for the question. Late last year we introduced retry logic into the activation process in the pipelines that made the ordering of the flows obsolete. We left the functionality in place for a while as a fallback measure if the retry wasn't sufficient but decided to remove it recently since it should no longer be necessary.

Hi Mike, thanks for the reply. So if I understand you correctly, the flows will all try to turn themselves on and then those that weren't able to, retry until requirements have been met (e.g. dependend flows have been turned on) and they turn on?

**Comment by mikefactorial** [comment]
@BeekvanV yeah that's the retry logic. Effectively, if a flow cannot be turned on due to an error, the pipelines will continue to the next flow and continue trying to turn on flows not already turned on until no more flows can be turned on. 

Closing this out for now, but feel free to respond if there are any other questions.
