### ISSUE TITLE
[CoE Starter Kit - QUESTION] - orphan flows auto assigned?

### ISSUE THREAD

**Issue by IonB1977** [microsoft/coe-starter-kit#7051]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi There,
Hope you can help us with a issue we had for the last 2 months.

We are using the CoE for the last 18 months and we installed updates in June:
- Core Components (v4.8)
- Nurture Components (v3.6)
- Audit Logs (v3.4)
- Governance Components (3.9)

Everything looks good. 
But at end of August we had one person leaving the company. This person had some flows running in a different Environment.

And now the account we use for CoE (coeadmin account) was added **Automatically** as owner to those flows (orphan flows)
Please see attached the email received in the mailbox for the "coeadmin".
 
Hope it makes sense. We are trying to figure out how to disable this option for the future.

Could you please let us know where we should look - is there a flow that automatically assigns ownership to orphan flows? 
Or a setting we activated by mistake?

Is this possible, or we are looking on the wrong side?
Please let me know if any more info to provide.

Thank you
Ion

![Capture7](https://github.com/microsoft/coe-starter-kit/assets/110121301/657f433f-7d3d-4de1-9584-52a86d5d02a8)
![Capture8](https://github.com/microsoft/coe-starter-kit/assets/110121301/c0497eda-fc59-4b3c-857e-f30189453f7f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

AB#765

**Comment by Jenefer-Monroe** [comment]
We auto assign only in one case which is the **_Admin | Sync Template v3 (Flow Action Details)_** flow for those flows which contain information you cannot get as an admin (specialty connectors) like http. 

The good news is that the product team is adding this information to Get Flow as Admin soon (rather than just Get Flow) and so we will be able to remove this. But we are still waiting for that to hit all regions and then we can fund.

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e61de496-6fc8-4acb-9739-8cf54dc874ed)

**Comment by IonB1977** [comment]
Thank you Jenefer for the quick answer.

That's exactly what we're looking for.

For now I turned off the flow (as I see it optional) and will monitor manually.

Thanks again,
Ion

**Comment by Jenefer-Monroe** [comment]
you are quite welcome! I'll go ahead and close this out then but please do return with new issues as you have them
