### ISSUE TITLE
[ALM Accelerator - BUG]: Error at the build-deploy "pack msapp files" step

### ISSUE THREAD

**Issue by mehakvij** [microsoft/coe-starter-kit#706]
**Describe the bug**

When running the build-deploy pipeline, we are getting the below error at the "pack msapp files" step.

"C:\Program Files\PowerShell\7\pwsh.exe"
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/73190679/123823260-047a0b80-d8cb-11eb-8de5-461831d9bd98.png)
[ERror.txt](https://github.com/microsoft/coe-starter-kit/files/6734482/ERror.txt)
 -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'c:\adows\_temp\a151099d-37b1-4543-bce3-17e3d16e074a.ps1'"

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

at temp_canvas_packager.Program.Main(String[] args)

##[error]PowerShell exited with code '1'.
**Component (please tell us which part you are experiencing issues with):**

- Version [e.g. 1.29]
- Component: ALM Accelerator Pipelines

**To Reproduce**

1. Go to build-deploy pipelines
2. Run the pipeline
3. scroll to pack msapp files

**Comment by devkeydet** [comment]
We're moving away from temp-canvas-packager in favor of using pac cli now that it's in public preview:
https://powerapps.microsoft.com/en-us/blog/canvas-source-code-tool-integrated-with-power-platform-cli/

This will be part of our next release.  Unfortunately, that release is delayed because we ran into an issue with the new pac cli:
https://github.com/microsoft/PowerApps-Language-Tooling/issues/248

Once the new pac cli is released, we will start using that.  Can you try to pack with the new pac cli on your local machine and see if you get the same error?

**Comment by mehakvij** [comment]
I think we tried that and got this error: "the current manifest version is 0.20 and now tool only supports 0.23 and above"

**Comment by devkeydet** [comment]
Sounds like the version you have unpacked in source control was unpacked with an older version.  Can you unpack using the newer version before trying to pack again?  Unfortunately, since we took a dependency on the canvas unpack/pack in early preview, it means that as the format changes, you need to update your source code before you can pack with a new version.  This will not be the case once canvas unpack/pack comes out of preview.

**Comment by devkeydet** [comment]
There's a similar discussion going on here:
https://github.com/microsoft/PowerApps-Language-Tooling/issues/260

**Comment by mehakvij** [comment]
@devkeydet we tried implementing this and got this error below:
[ERror.txt](https://github.com/microsoft/coe-starter-kit/files/6809488/ERror.txt)
![Test](https://user-images.githubusercontent.com/73190679/125467532-98f5f799-680e-4ac5-aa1f-33115bd6400b.jpg)

**Comment by mehakvij** [comment]
I just found out that it only happens with one of the solution packages we have installed, not all of them. Would you happen to know why/what's been experienced in the past with certain solution packages?

**Comment by mikefactorial** [comment]
Looks like this will be fixed when we move to PAC CLI in the next release. https://github.com/microsoft/PowerApps-Language-Tooling/releases/tag/0.3.7-preview. @mehakvij will follow up with you when we've pushed the release.
