### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to share Developer Compliance Center with Makers?

### ISSUE THREAD

**Issue by JHFPT** [microsoft/coe-starter-kit#7099]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I tried searching for an answer to this, but couldn't find an answer so my apologies if it has already been answered.  For the COE Compliance Center, when the app sends an email to Makers who need to provide details on their app for compliance purposes, are those makers automatically added to the COE Compliance Center and necessary tables so they can provide their updates?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

None

AB#849

**Comment by Jenefer-Monroe** [comment]
No we do not auto share the apps with people, you need to share the apps with the Makers separately.

**Comment by JHFPT** [comment]
If we have 1000+ makers across different Power Platform environments, we need to manually add them to the Compliance center one by one in order to gain compliance details on their respective apps?  Is there an automation we could set-up to automatically add people to an app if they are a maker?

**Comment by shrikant-singh31** [comment]
In order to share a MDA with users you first need to share the app as a whole with the desired security roles
Share the app as a whole with the Security Role
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3d532a9-92f5-4765-aeef-a9e171f19a46)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5377d117-c406-4293-bd3b-1c966f1569a8)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c9d7d6a-5e3e-4dab-b8d9-9749fcadaa15)
Now that SR can be applied to users you share the app with.
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f8976c2-b594-43da-b56c-fa4932fd7400)

**Comment by shrikant-singh31** [comment]
Instead of sharing to each individual Maker you can share the app with the Maker group as all the Makers are added to a Maker Security Group by **Admin | Add Maker to Group** cloud flow and then you can share the app to the Maker group by searching in the People search box and assign the Maker Security Role to the Maker Group
<img width="960" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149066866/a00f4eb1-bff6-4534-9e0a-7b4e284b3553">

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by santiareh** [comment]
Very useful stuff! If I want to use the CoE Setup app to share all the apps with Admins and Makers, does this also send out the sharing notifications or do I have the option to choose if I want them to go out or not?
![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/3f40350c-6089-47e1-96a7-8299c2f86ed0)

**Comment by MaxDuca** [comment]
As the App "**Devleoper Compliance Center**" is Premium:
![image](https://github.com/microsoft/coe-starter-kit/assets/17979332/f50c4736-716b-4dad-841c-2ece04ece156)

Can you confirm that all maker need a power apps premium license? Can we have another license solution?

Thanks in advance,

**Comment by AAKP95** [comment]
Hello,

One more question on this.

If we are giving Power platform maker SR role to the makers team and share the CoE apps with them, won't it give access to  makers to the environment?

Will they be able to create resources in CoE environment or to edit existing resources?
