### ISSUE TITLE
COE starter kit - center of excellence setup wizard failure

### ISSUE THREAD

**Issue by SomarajuA** [microsoft/coe-starter-kit#7103]
Hi Jenefer, we are trying follow the steps provided in the ticket : [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6851).

When we are executing the center of excellence setup wizard, we are not able to turn on the below Run inventory flows and getting the below error. Please suggest.

Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_PowerPlatformMakeSecurityGroup'."}}".

![MicrosoftTeams-image (5)](https://github.com/microsoft/coe-starter-kit/assets/147693435/47f227e4-8c42-41de-a01b-a975a8d6d4b7)

![MicrosoftTeams-image (6)](https://github.com/microsoft/coe-starter-kit/assets/147693435/399b26b8-2943-49a7-b265-6b4cd547a7a8)

Please suggest on where can I find this value **admin_PowerPlatformMakeSecurityGroup**

AB#859

**Comment by Jenefer-Monroe** [comment]
There was a step in the setup wizard for you to add this field
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bffd5790-b345-4a8f-93a7-792610f76477)

Now that you are past that you can also this you can also update this, and all environment variables, in the CoE Admin Command Center, which is one of the apps installed with Core
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/14e29004-f8a4-4344-b745-d45ea755a65b)

**Comment by Jenefer-Monroe** [comment]
I've added @v-bjaiswal to assist you with other issues as you get setup. Please feel free to use this issue to get yourself setup.

**Comment by SomarajuA** [comment]
Hi Jenefer,

We have setup the COE starter kit, however we got flow failure notification for the below two flows and the run history shows that the flow is running successful afterwards. I am attaching the flow name, error, and the run history. Please suggest if we have to check anything.


Flow name; Admin | Sync Template v3 (Flow Action Details)
![MicrosoftTeams-image (8)](https://github.com/microsoft/coe-starter-kit/assets/147693435/ce1de31a-821a-4410-b2f2-43d8cdfbe437)
![MicrosoftTeams-image (9)](https://github.com/microsoft/coe-starter-kit/assets/147693435/d6955225-d057-4fec-83f7-1bfc2331076d)

Flow name: Admin | Sync Template v3 (Connection Identities)

![MicrosoftTeams-image (10)](https://github.com/microsoft/coe-starter-kit/assets/147693435/ea9a438d-c924-4c1d-99e7-c8697924f34e)
![MicrosoftTeams-image (11)](https://github.com/microsoft/coe-starter-kit/assets/147693435/59921557-7aad-4594-9487-3d75dc12dc34)

**Comment by Jenefer-Monroe** [comment]
### Connection Identities
The CoE kit is built on top of the product, and as such bound to platform limitations. 
This failure is due to a limitation on the amount of data connectors can bring back, which unfortunately, you have exceeded. 
Note also that deleting individual flows and apps will not delete the connections they use, so they do pile up over time and deleting objects does not 

We cannot fix that, nor can we safely create a script which will reliably connections safely for all tenants that will work over time. 

Here are some things you can do to address:
1. Manually use powershell to [explore](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) unused or errored connections. That technology does not have this same size limitation.
2. Contact [product support](https://learn.microsoft.com/power-platform/admin/get-help-support) to have them help you clean up old connections

Hope that helps, and sorry for the inconvenience.

**Comment by Jenefer-Monroe** [comment]
### Flow Action Details
Can you please clarify the version of the kit you are using?
You can see this on the solutions screen
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f6089bdb-4264-4e63-a133-7e31f47f6767)

**Comment by SomarajuA** [comment]
Hi Jenefer,
It's 4.16

![image](https://github.com/microsoft/coe-starter-kit/assets/147693435/2d6e7645-93c5-4416-b7fa-f367c23e250d)

**Comment by Jenefer-Monroe** [comment]
ok thank you. Unfortunately then this is a current limitaiton of the kit. 
We do have this on the backlog to investigate with https://github.com/microsoft/coe-starter-kit/issues/6819
However it would mean losign some of the API reduction work that we do. You casn keep an eye on that issue though to see if we are able to find a way to solve.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
