### ISSUE TITLE
[CoE Starter Kit - QUESTION] Exclude CoE apps and flows from CoE kit inventory

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7115]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

is there a way to exclude coe apps and flows so that we don't get dinged by coe as if those apps/flows are still used every once in a while?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#868

**Comment by shrikant-singh31** [comment]
If we want to exclude all coe flows and apps so that we do not get inactivity notification for these apps and flows then we can exempt that environment from the inactivity process in which COE is installed using COE Setup and Upgrade Wizard app.
Steps:

1. Open COE Setup and Upgrade Wizard app.   We have an option to exempt the inactivity process
2. Go to More Features and select Inactivity notification process.
<img width="959" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149066866/e2da0d66-4b4c-47df-b05c-177e9dd42b12">
3. Follow the steps and turn on the toggle for the environment in which coe kit solutions are installed to exempt it from inactivity process.
<img width="960" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149066866/7cf24eda-7923-4957-8fa3-d9401f9797d6">

This can also be done from the Power Platform Admin View app. By navigating to the particular environment record in which coe is installed and setting Excuse from Inactivity Flows columns to Yes under Settings tab.
<img width="958" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149066866/4fcc2a4a-c8da-48a7-8711-8b10b2496f92">

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
