### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#7178]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

The PBI template is throwing an issues
<img width="934" alt="pbi template error" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/552af823-b7a9-43b3-81be-a09b5420f10d">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Production_CoEDashboard_October2023.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

I have followed this step in url - Note that for this dashboard it need to have the prefix (htttp..) and the ending /
Bad data flow is working fine.

AB#1508

**Comment by RahulBojji** [comment]
@Rajatchopra3 Can you please confirm if you have used https:// instead of http:// as per [this](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-the-production-and-governance-power-bi-dashboard)

<img width="714" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/61c0335b-7371-473e-a9c9-8df769e1d59b">

**Comment by Rajatchopra3** [comment]
Yes, I have used https

**Comment by Rajatchopra3** [comment]
Yes, I have used https

**Comment by RahulBojji** [comment]
@Rajatchopra3 Can you please give us the full error. You can copy entire text by scrolling down.

**Comment by Rajatchopra3** [comment]
Hi, I think that was some intermittent issue. you may close the ticket, thanks
