### ISSUE TITLE
[CoE Starter Kit - QUESTION] If an App/Flow is created AND deleted prior to the next refresh, will it still show up in the reporting?

### ISSUE THREAD

**Issue by abhijkumar-msft** [microsoft/coe-starter-kit#7206]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

P&G recently asked for additional visibility into Apps and Flows that are created and deleted within a 24 hour period. The supposition is as follows:

“Our COE Starter Kit reporting refreshes every 24 hours. So what happens if someone creates an app or flow that’s malicious, and then subsequently deletes it within the 24 hour windows? We’ll never catch it in any of our reporting.”

Do the reports in the CoE Starter Kit pickup apps or flows created in the past 24 hours -- even if they were subsequently deleted? If so, where would we find this activity?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.7 (June Version)

### What method are you using to get inventory and telemetry?

Data Export

AB#1620

**Comment by Jenefer-Monroe** [comment]
The Data Export only happens once a day so if the app is created and removed in that time period then I do not believe it will be in the Data Export. It might be occasionally just due to random timing but you would not be able to rely on that. 

This is the same for the sync flow architecture except that you could set that to refresh more frequently. Still the same limitation would be there. If you set the sync flow to run hourly, and the person created and then deleted the malicious object in that timeframe it would not be found. 

I think your best answer here is to use the DLP policies for things which are concerning.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
