### ISSUE TITLE
Admin | Sync Template V3 flow fails - Get flow fails in loop after Get Flows

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#722]
Hi Team

The flow "Admin | Sync Template v3 flow “In the CoE starter kit is failing with error message “admin_flow With Id = XXXXXXXXXXXXXXXXXXX Does Not Exist”.

After some research I found that flow is failing for the flows which are in solution and no problem with the flows which are in my flows.

Let’s say we have 10 flows in the Environment and 4 are inside the solution and remaining 6 flows are in my flows.

Now flow fails 4 times with error flow id XXXXX Doesn’t exist.

Any tips?

**Comment by JeneferM-MSFT** [comment]
Can you please share a screenshot (you'll need to do this in GitHub not email) of where in the flow it is failing? There are places we expect this to fail and catch, so wanting to make sure we have the correct failure message. 

Can you also please find if these flows / solutions were created / imported by a service principle?

**Comment by Jodarcy1** [comment]
[Coe Flw Errors.docx](https://github.com/microsoft/coe-starter-kit/files/6754880/Coe.Flw.Errors.docx)

No, we are not using service principal; we are using a service account for all connections in the flow.  Thanks.

**Comment by JeneferM-MSFT** [comment]
Hello, few possibilities here:

1) Timing issue 1
Your connections are broken, may have broken mid-run. Ask same as # 2 below. 

2) Timing issue 2
It's possible, though not likely, that the flow was deleted after the flow started to run. 
**ASK:** Can you confirm this was not the case by fixing your connections and resubmitting? 

3) Service Principle
When I asked about the service principle, I did not mean the identity running the CoE, I meant the identity that created the flow its failing to find. 
**ASK:** Please go manually see if the flow still exists, and who its owner is. You can do this with the Set Flow Permissions app, or Power Shell. 

4) It's also possible that you have hit a product bug we have seen before in which the **Get Flows** call is returning previously deleted flows. And the call to **Get Flow** correctly says it no longer exists. 
**ASK** If this is the case, you will need to contact support to have them clean this up in order to have this flow start passing.  
Please try the below flow to get a repro outside of the toolkit before contacting support. You can use the below flow to get this repro.  
To use: Import the flow, open, select the environment which repros for you.  
It loops the flows, will hit the same failure and the you can go to support with this flow instead of the toolkit, for faster iteration to fix. 

[ProductBugDemo-getflowaftergetflowsfails_20210702144440.zip](https://github.com/microsoft/coe-starter-kit/files/6755313/ProductBugDemo-getflowaftergetflowsfails_20210702144440.zip)

![image](https://user-images.githubusercontent.com/62659043/124291999-64162800-db12-11eb-92a6-55b4ffe1ecee.png)

**Comment by JeneferM-MSFT** [comment]
closing out as no further work for CoE team
