### ISSUE TITLE
[CoE Starter Kit - QUESTION]  Adding makers to Makers table

### ISSUE THREAD

**Issue by GithMen** [microsoft/coe-starter-kit#7234]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,
I am trying to track down  which flow is triggering the adding of maker in the Makers table when a user create a new flow. 
I have created a could flow to test this process. 
Which inventory flow i have to run manually to get my maker added to the Makers table ?

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1692

**Comment by RahulBojji** [comment]
@GithMen 
Whenever a maker record gets created in the maker table, a flow "**Admin | Add Maker to Group**" kicks in and add the maker to the maker security group.

**Comment by GithMen** [comment]
Hi,
My question is not about processes that trigger when user get added to Makers table. My question is more about  inventory flow that trigger adding maker toi Makers table and how i can test this process manually.

**Comment by GithMen** [comment]
So the flow Admin | Sync Template v3 (Driver) is the parent flow of all the others flows. I have runned it manually since 3 hours but themaker of my test flow is not added to Makers table.

**Comment by Jenefer-Monroe** [comment]
Yes there is a delay in the Driver flow and the delay is expected, and will delay a randomized length of time before continuing and kicking off inventory each day. 

This is done to prevent all the organizations that use the CoE from beginning their sync flows at the same time as they use a lot of Dataverse API calls.

Why? To protects the Dataverse service on the Microsoft side - the CoE Starter Kit is installed in thousands of tenants, and as you can image performs quite a lot of Dataverse read/write actions during an inventory run. The way scheduled flows work, unfortunately, is that when they are shipped in a managed solution they run at the very same time independent of the customer timezone - so they may run at 7am PST, 3pm GMT etc etc. This meant that we saw many many millions (or more) of Dataverse calls at the very same time each day, which meant that with an increase in installations of the CoE kit it may have caused a service disruption. That's the last thing we want! In order to balance out these Dataverse calls we had to make sure customers run the inventory at different times during the day - our ideal solution would have been to provide a parameter to the Schedule trigger, unfortunately that's not possible in Power Automate today (the Schedule trigger doesn't work with Environment Variables etc) so the only solution we could think of is introducing a random delay after the flow kicks off. We know and appreciate that's not ideal but it's the only thing we could think of to protect the service on our side.

**Comment by Jenefer-Monroe** [comment]
You can go view that flow to see when it completes, and then your test case should be resolved.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
