### ISSUE TITLE
[CoE Starter Kit - QUESTION] Desktop flows created in default environment are not displaying in CoE Desktop Flows tables 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#7272]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

we have many desktop flows created in our default environment in Power Platform . 

I could see the desktop flows that are created in another enviornment  but unable to see the flows were created in default enviornment. 

could you please help me if something needed to be checked or configure ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Desktop Floes

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1756

**Comment by Jenefer-Monroe** [comment]
Likely it failed due to size. This is something we've fixed in the v4 version of the flows which use the modern connector which allows for column select. 
To validate you can go to the Command Center and look at your sync flow failures
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cfd8daef-fe32-4ca6-abe0-afdb1cfa55ec)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
