### ISSUE TITLE
Admin | Sync Template v3 (Driver)

### ISSUE THREAD

**Issue by bocESMI** [microsoft/coe-starter-kit#7308]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 
I am installing the COE solution on one of our dev tenants and an issue when setting up the compliance processes at this step https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#set-up-the-developer-compliance--components-using-the-setup-wizard
Missing prerequisite message appears to return to the set up wizard when the Admin | Sync Template v3 (Driver) flow - see below. When I check on the flow, it is stuck in the Delay Inventory condition which is set to 900 minutes.

Please advise as this is my first time installing the COE solution. Thank you in advance.

Missing prerequisite
It looks like some inventory flows required to set up the Compliance process haven't finished running yet. Please check the CoE flows page of the Admin - Command Center app, and return to this setup wizard when the Admin | Sync Template v3 (Driver) flow has finished running.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

CenterofExcellenceCoreComponents_4.17

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1799

**Comment by Jenefer-Monroe** [comment]
The delay is expected, and will delay a randomized length of time before continuing and kicking off inventory each day. 
This is done to prevent all the organizations that use the CoE from beginning their sync flows at the same time as they use a lot of Dataverse API calls.
Why? To protects the Dataverse service on the Microsoft side - the CoE Starter Kit is installed in thousands of tenants, and as you can image performs quite a lot of Dataverse read/write actions during an inventory run. The way scheduled flows work, unfortunately, is that when they are shipped in a managed solution they run at the very same time independent of the customer timezone - so they may run at 7am PST, 3pm GMT etc etc. This meant that we saw many many millions (or more) of Dataverse calls at the very same time each day, which meant that with an increase in installations of the CoE kit it may have caused a service disruption. That's the last thing we want! In order to balance out these Dataverse calls we had to make sure customers run the inventory at different times during the day - our ideal solution would have been to provide a parameter to the Schedule trigger, unfortunately that's not possible in Power Automate today (the Schedule trigger doesn't work with Environment Variables etc) so the only solution we could think of is introducing a random delay after the flow kicks off. We know and appreciate that's not ideal but it's the only thing we could think of to protect the service on our side.

**Comment by bocESMI** [comment]
Thank you Jennefer, makes sense. Just to confirm, the flow will eventually run, once the run is finished, I can continue with the installation?

**Comment by Jenefer-Monroe** [comment]
yes thats correct. Sorry I should have clarified that part per your question :)

**Comment by bocESMI** [comment]
Perfect, much appreciated.

**Comment by Jenefer-Monroe** [comment]
You are so welcome! I'll go ahead and close this out then. Thanks for using CoE
