### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Add Maker to Group Error

### ISSUE THREAD

**Issue by bleno123** [microsoft/coe-starter-kit#7352]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When I turn on the flow "Admin | Add Maker to Group" I get the error below. I've turned on several other flows without any problem. How do I fix this? My main goal here is inventory/tracking what people are doing so if I can't fix this step, how crucial is it?

![image](https://github.com/microsoft/coe-starter-kit/assets/154913304/ec0b8e26-8643-4343-9196-444d303b9a53)

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Admin | Add Maker to Group

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1901

**Comment by Jenefer-Monroe** [comment]
Hello. The flows in the kit have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites]( https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with).

**Comment by bleno123** [comment]
Thanks I saw that from earlier posts but was confused because many of my flows did work. Either way I think I got it figured out. Thanks for your help.
