### ISSUE TITLE
[CoE Starter Kit - BUG] Configure embedded apps in the CoE dashboard - wrong page name

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#7399]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We updated the page name but forgot to update the documentation. 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2a17acb9-d05b-406b-9bb1-7c3e8e32fc1d)

### Expected Behavior

Manage App Access
Manage Flow Access
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1088e1ca-8a3e-4583-ad43-f514752dbb73)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

documentation

### What method are you using to get inventory and telemetry?

None

AB#1966

**Comment by LucX4** [comment]
Hi @Jenefer-Monroe, hope you are well!
Adding a few comments here that might be helpful:
Sometimes, the Environment name isn't visible due to a warning message, similar to the one shown in the image below.

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/b65cc7e8-8c56-4b77-9db5-9dd7f1e3f2c7)

To select the correct Environment from the dropdown, we must first close it:

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/d8380c6b-b3c8-4247-aded-82ed3c561d06)

Wish you a great week.
