### ISSUE TITLE
[CoE Starter Kit - Feature]: Report on makers SR in all envts

### ISSUE THREAD

**Issue by ddebela22** [microsoft/coe-starter-kit#7402]
### Is your feature request related to a problem? Please describe.

Is the CoE Starter Kit generate reports of a roll for the users in each to environment ?

### Describe the solution you'd like

Needs a report which shows users roll in the environment. (Lists of users with there roll in specific enviroment)

AB#1969

**Comment by Jenefer-Monroe** [comment]
Hello. I presume you mean the Security Role for the environment yes? 

We have this for the System Admin SR and it was done in a way to allow you to expand to more SRs if you'd like. But unfortunately its just too API and space intensive for us to do for all SR's and BUs. 
Please see this report in the Power Platform Admin View app
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6dbc07f3-1511-4f81-b4b5-3ba36b60bc12)

Which uses this flow: **_SYNC HELPER - Get Security Role Users_**
The flow takes in the Environment, Security Role, and Business Unit so that it can be expanded upon by you for other SRs / BUs
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/82b1fabe-27f1-46b8-9485-e1f6c78bd222)

The product team is aware of this requirement though. I suggest you post about it on the https://powerusers.microsoft.com/ site to help get traction for it as a feature.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
