### ISSUE TITLE
[ALM Accelerator - QUESTION] Connection references not resolving?

### ISSUE THREAD

**Issue by jberu622Neudesic** [microsoft/coe-starter-kit#7407]
### What is your question?

I'm not sure if this is the expected behavior but when the person who created the connection references navigates to the configure deployment settings the connection references resolve for him. Howerver when I go to the same screen for the same project the connection references show unknown and where the user display name shows i see the guid. 

<img width="860" alt="Screenshot 2024-01-08 093731" src="https://github.com/microsoft/coe-starter-kit/assets/59027173/6ad7734a-96c9-4326-bcb3-d382041813b2">
<img width="686" alt="Screenshot 2024-01-08 111010" src="https://github.com/microsoft/coe-starter-kit/assets/59027173/770799a5-f68d-4434-b0ff-41b34128b0f9">

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231109.3

AB#1973

**Comment by v-bjaiswal** [comment]
Hi @jberu622Neudesic , thank you for logging this bug. We are investigating into this.

**Comment by mikefactorial** [comment]
@jberu622Neudesic this is the expected behavior for the same reason you can't see another users connection in the maker portal when logged in as yourself. The ALM Accelerator stores the id of the connection that the other person created but it can't and won't show you the details of that connection because you don't have permission to see it. Hence it will be listed as an unknown connection.

**Comment by jberu622Neudesic** [comment]
@mikefactorial It makes sense, thanks for the update.
