### ISSUE TITLE
CoE import - User is not authorized to read secrets from keyvault

### ISSUE THREAD

**Issue by KezHalls** [microsoft/coe-starter-kit#7411]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have logged this as a bug previously (eg #6473) and ended up getting MS to help me.  
It has now returned and I cannot do an upgrade.
Error:
User is not authorized to read secrets from  [keyvaut secret]

### Expected Behavior

1. import CoE
2. CoE imports successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

core components import

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

follow steps from : https://learn.microsoft.com/en-gb/power-platform/guidance/coe/after-setup#installing-upgrades

1. remove unmanaged layers
2.  import CoE

AB#1978

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately it sounds like you hit a product limitation in the integration between Power Platform and Azure Key Vault. We are not able to make this better ourselves and you would need to have support assist again. Hopefully the support > product team feedback loop can help make this better.

**Comment by Jenefer-Monroe** [comment]
Reviewing my notes and we have seen this before when people try to enter secrets in the env variables while importing. 
Please see [Set up the Inventory components using the Setup Wizard](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-using-the-setup-wizard)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c42c5166-4aac-4ba8-a273-1762e1512475)

I've not seen this impact upgrade in the past but I know the product team recently changed their import behaivor for env vars so that might be worth a try.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
