### ISSUE TITLE
[CoE Starter Kit - BUG] COE Governance and COE BYODL PBI Dashboards capacity limit error

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#7422]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We had identified the COE Power BI reports are taking longer to refresh, and facing the below error message. is there a way to optimize it?

<img width="566" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/76d57f4a-b629-4a3e-b78b-5b1f820bafb9">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

PowerBI

### What method are you using to get inventory and telemetry?

Data Export

AB#1996

**Comment by ALSPowerPlatform** [comment]
Team- could you please assist us on this.

**Comment by Jenefer-Monroe** [comment]
The Data Export product feature that the CoE kit depends on for the BYODL implementation continues to be in public preview which means we've seen very slow adoption of the integration and customers understandably are not taking a dependency on this feature due the preview nature. 

In order to better utilize resources in our team and make sure we invest in the right features, we are pausing investments related to the BYODL architecture and will re-focus our investment here once this feature is GA. We may continue to make small fixes if they are well understood.

In the meantime, you can continue to use the BYODL architecture as-released and make your modifications and extensions to it, or switch to the sync flow architecture. We've recently made big improvements to the sync flow architecture as well, so this is less impacted by throttling and has a much lower API call volume.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
