### ISSUE TITLE
[ALM Accelerator - BUG]: Environments not showing when creating a new project via wizard

### ISSUE THREAD

**Issue by tobiasneunercs** [microsoft/coe-starter-kit#7423]
### Describe the issue

Hi everyone,
we started our journey with the ALM accelerator. Preparing everything, installing the app and so on worked like a charm. But we hit a first block, when we wanted to create a new project using the provided "project wizard".
In the step "Service Conections" we need to select the environments for which we want to create connections. Unfortunately this list is quite long and the dropdown stops the listing somewhere in the letter "P". We did not find a way to refresh the list or enter the environment manually.

### Expected Behavior

Expected behavior would be that either the tool automatically continues loading until all environments are loaded, does so whenever the end of the dropdown is reached or there is somewhere a manual button to start the refresh.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

CenterofExcellenceALMAccelerator_1.0.20240104.1_managed.zip

### Steps To Reproduce

To reproduce you would need to create many environments. (Don't know the exact number)

AB#1997

**Comment by v-bjaiswal** [comment]
Hi @tobiasneunercs , thank you for logging this bug. We are investigating into this.

**Comment by v-bjaiswal** [comment]
Hi @tobiasneunercs , 
We are not actually able to replicate it in our system. We have tested it with 500 environments list, and it didn't cause any issue.
we were able to see all the environment list. So, for further testing can you tell us the exact count of environment list in your end.
And for a workaround as of now please try to write the environment name directly into the text box which you want to select instead of selecting it from the dropdown.

**Comment by v-bjaiswal** [comment]
Marking this as close. Please create another ticket if you are still facing issue. Thank you.
