### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - How to use ByoDL DataFlow to get all Flow Usage Data

### ISSUE THREAD

**Issue by shoffma1** [microsoft/coe-starter-kit#7450]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

With January release, the ByoDL data flow is not allowing downstream usage.  When trying to import the Flow Usage table to another report it is only pulling in recent data, not all data shown when opening the dataflow itself.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

January 2024

### What app or flow are you having the issue with?

Power BI DataFlow

### What method are you using to get inventory and telemetry?

Data Export

AB#2028

**Comment by Jenefer-Monroe** [comment]
That's correct. This is a feature we implemented to allow large orgs to not hit Dataflow limits. 
Please see https://github.com/microsoft/coe-starter-kit/issues/6969

In order to have a "full inventory" you would need to clear out the records in the DataflowRefreshHistory table. 
Note that we are, with https://github.com/microsoft/coe-starter-kit/issues/7412, making this easier by offering a "delete all history" option in the Command Center

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
