### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - Licenses required for makers and users to use the tool

### ISSUE THREAD

**Issue by Yusuke-Itazu** [microsoft/coe-starter-kit#7453]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I understand that the installation of the "CoE Starter Kit" requires a premium license.
For example, if an maker requests to create an environment, he or she will use the "CoE Maker Command Center" app to submit the application, but since this app is a model-driven app, it requires a premium license.
Do makers and users need a premium license to use the CoE Starter Kit?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2032

**Comment by Jenefer-Monroe** [comment]
That's correct. Anyone using the apps in the kit needs a premium license. This was true before the transition to Model Driven Apps as well as they are (for the most part) built off data stored in Dataverse which is also a premium feature.

There are a few expectations to this. 
For example the [inactivity processes](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components) in the governance solution use the products **_Approvals_** flow and so the interaction with the user is via the products approvals UX in email instead of in an app. 

Hope that helps provide clarity.
