### ISSUE TITLE
[CoE Starter Kit - BUG] Error Upgrading CoE Start Kit

### ISSUE THREAD

**Issue by comcare123** [microsoft/coe-starter-kit#7459]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have **CenterofExcellenceCoreComponents(Ver 3.3.1)** solution. When we are trying to upgrade the environment with **CenterofExcellenceCoreComponents(Ver 4.1.7)** solution we are getting the folowing error.

**ErrorCode**: [80050123]
**Exception Message**: Import of app module(s) failed: The app is already associated with component library 'Power Platform Admin View'. The app already has a component library Name: 'admin_admin_PowerPlatformAdminView_canvasappid_admin_powerplatformadminviewdefaultcommandlibrary_4db75'. In Solution Import, please remove library either from Source or Target and try again.

How can we fix this?

### Expected Behavior

We are expecting the solution import to be successful.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.3.1

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Log into CoE environment with System Admin role.
2. Download CoE Starter Kit.
3. Extract the zip file.
4. Try to import CenterofExcellenceCoreComponents_4.17_managed.zip solution.
5. It throws error mentioned above after 20 minutes.

<img width="770" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/156623952/685b7f1c-753b-4c46-9d49-2960995da5dd">

AB#2039

**Comment by Jenefer-Monroe** [comment]
Hello. We’ve seen a few people hit this in the past. Unfortunately it’s a product bug due to something in your tenant/environment and not something we can resolve for you. 

Another CoE user did find a solution and posted this as they way he resolved. Please see https://github.com/microsoft/coe-starter-kit/issues/4375#issuecomment-1345554161 

It points to this power users thread: [Managed solution import - Component library issue](https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Managed-solution-import-Component-library-issue/td-p/1785842)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
