### ISSUE TITLE
[CoE Starter Kit - QUESTION] No data in App Usage page of CoE Power BI Dashboard

### ISSUE THREAD

**Issue by isabellewong** [microsoft/coe-starter-kit#7466]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are unable to get any data to load up in the App Usage page of the dashboard and date range doesn't extend past 2 Oct 2020.
Table also not filled in App Shares page. Need some assistance on understanding what could be missing. 

![appshares-coe-issue](https://github.com/microsoft/coe-starter-kit/assets/72850507/d0fe57f4-5142-4570-8981-b627295169ee)
![appusage-coe-issue](https://github.com/microsoft/coe-starter-kit/assets/72850507/9189ad94-471d-43dc-8f16-d7f6497b7548)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023 4.9

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

AB#2046

**Comment by Jenefer-Monroe** [comment]
You are on an old version of the kit and we have redesigned the PBI since then so I don't have those exact pages anymore. But I can tell you how those are populated and we can see if the data is in the tables. 

### AUDIT LOGS
**See if in tables**
Please go to the Power Platform Admin View model driven app. 
For audit logs, you can look at the table itself. Do you see the data there?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f171a504-4867-42df-a9c5-a1fa9011f5fe)

**Check flows**
Back in June I believe the audit logs were a separate solution still. Can you please go validate that those flows are turned on and running? I dont have a screenshot as we've deprecated that solution but here were the setup instructions in case that helps you find them. [Collect audit logs using a custom connector (deprecated)](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)
Do note that these flows are deprecated and when you upgrade next you will need to remove this solution as described here: https://github.com/microsoft/coe-starter-kit/issues/6018

### APP SHARED
**See if in tables**
Please go to the Power Platform Admin View model driven app. 
Select a canvas app you know is shared and view its usage
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9d3822d3-efdf-4f49-8fe9-043579ee0ebf)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f48b2d18-eecb-4df7-bd6f-2c620e9dd540)

**Check flows**
If the data is not there, please be sure these flows are turned on and running. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f4a4c1cd-2968-4d74-9494-7769b601f081)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by diltont** [comment]
@Jenefer-Monroe Ihave the same issue mentioned here . I cannot see the app usage data in CoE toolkit.
1)I checked the audit log in the Power Platfrom Admin View. There is no data shown
![image](https://github.com/microsoft/coe-starter-kit/assets/47943660/7dcc14b0-55f0-429c-850c-72accacfb3b2)
2)We have upgraded to new CoE toolkit and we got no errors.
3)There are multiple cloud flows which are turned off . Which one should I make it on. An overview is shown below
![image](https://github.com/microsoft/coe-starter-kit/assets/47943660/855823d5-fb7a-401f-9f85-e98cae5dc4de)

Support is highly appreciated.
Thanks
