### ISSUE TITLE
[CoE Starter Kit - Governance Components] Add summary email of deleted Teams environments to Admins

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#748]
Currently the Weekly Clean Up of Teams environments only sends a notification to the Team owner about the deletion of their environment. 
We should add a weekly summary of deleted environments after deletion to the Admin as well, so they get enough notice to restore environments (which is possible for 7 days as the flow does a soft-delete).

**Comment by manuelap-msft** [comment]
Added information about deleted environments to Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments. Ready for August release.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
