### ISSUE TITLE
[CoE Starter Kit - BUG] failed to import: Solution Upgrade action faile

### ISSUE THREAD

**Issue by ramu1977** [microsoft/coe-starter-kit#7489]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 3 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: e5b0781f-537d-4e18-8ff5-7d335756b130, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: df9d2eb2-be65-434d-80dc-923c1f692e22, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

### Expected Behavior

Update without any error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Full solution

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In this environment,

### Anything else?

No

AB#2076

**Comment by Jenefer-Monroe** [comment]
Hello, this is a known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018
We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 
If you have tried those steps and still see this error, note that some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use  powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest)  these remaining connections to the old connector.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
