### ISSUE TITLE
[CoE Starter Kit - BUG] Install wizard not loading pre requisite 

### ISSUE THREAD

**Issue by augermathieu** [microsoft/coe-starter-kit#7491]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When using a service account, the install wizard is not loading the pre requisite and we get this error message : 

Office365Users.MyProfileV2 failed: { "error": { "code": "-2147024891, System.UnauthorizedAccessException", "message": "Attempted to perform an unauthorized operation.", "innerError": { "date": "2024-01-18T15:47:11", "request-id": "5d9186a9-ff86-4e72-b225-672313a40c53", "client-request-id": "5d9186a9-ff86-4e72-b225-672313a40c53" } } }

![image](https://github.com/microsoft/coe-starter-kit/assets/157041031/9f8e9a4c-8549-4a66-949f-c8c93947c166)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Create new environment.
Authorize connectors in the default DLP policy 
Install the creator kit
Install the core components
Run the wizard with the service account
Error happening  

AB#2078

**Comment by Jenefer-Monroe** [comment]
This usually indicates that the startup flows were not turned on. 

The following flows are supposed to ship turned on, please go try to turn each on manually and see what error you get when you try to turn them on. 

- SetupWizard>CreateGroup
- SetupWizard>GetCurrentEnvironment
- SetupWizard>GetTenantID
- SetupWizard>GetUserDetails
 
In particular this failure is usually due to this flow not being on: **_SetupWizard>GetUserDetails_**
This usually happens when the **_HTTP with Microsoft Entra ID (preauthorized)_** connection is broken or misconfigured.
Please go to connections and make sure the connection for these is as follows (or your tenant equivalent if you are not a commercial tenant: https://graph.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a31b22b8-bc81-4d81-a5b7-80dc740f2b82)

Sometimes the product creates one of these connected to the envt and this will not work.

**Comment by augermathieu** [comment]
Hi Jenefer, as you are suggested, the connector is correctly configured so issue is not tied to that
