### ISSUE TITLE
[CoE Starter Kit BYODL - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#7499]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Still seing the mashup error for flows dataflow. old case  #6736

![image](https://github.com/microsoft/coe-starter-kit/assets/87489417/f89bd635-1638-48d5-afdf-8207c2c78c84)

### Expected Behavior

Suppose to sync the data flow for power automate

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

COE BYODL FLows

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Sync dataflow from PowerApps dataflows

AB#2089

**Comment by Jenefer-Monroe** [comment]
Thats unfortunate. It is working for most people who are investigating the Data Export feature. We can put on the backlog to investigate. 

However, as the Data Export product feature that the CoE kit depends on for the BYODL implementation continues to be in public preview which means we've seen very slow adoption of the integration and customers understandably are not taking a dependency on this feature due the preview nature. 

In order to better utilize resources in our team and make sure we invest in the right features, we are pausing investments related to the BYODL architecture and will re-focus our investment here once this feature is GA. We may continue to make small fixes if they are well understood.

In the meantime, you can continue to use the BYODL architecture as-released and make your modifications and extensions to it, or switch to the sync flow architecture. We've recently made big improvements to the sync flow architecture as well, so this is less impacted by throttling and has a much lower API call volume.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
