### ISSUE TITLE
[CoE Starter Kit  BYODL- QUESTION] How update BYODL PBI to point to new Dataflow

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#7500]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How can we upgrade powerBI dataflow in COE BYODL Solution. Each version will have new Dataflow. But in PowerBI how can we upgrade? I can see only option to rename old and import new one.is that correct method? if its correct the problem is the new dataflow will pull only the information from when it is imported. Upgrade documentation is not explaining the process to upgrade the powerBI dataflow.

![image](https://github.com/microsoft/coe-starter-kit/assets/87489417/be6027d6-fbfe-4770-b661-4e536b22dba3)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

PowerPlatformAdminAnalytics-DF

### What method are you using to get inventory and telemetry?

None

AB#2090

**Comment by Jenefer-Monroe** [comment]
Thanks for reaching out. 
You will use the PBI Template file in the Jan 2024 kit download, and use the new DF id for the parameter. 
Let me know if that is unclear.

**Comment by jayakumarkgds** [comment]
> Thanks for reaching out. You will use the PBI Template file in the Jan 2024 kit download, and use the new DF id for the parameter. Let me know if that is unclear.

PBIT Templte i am clear .My questions is every time new dataflow is relase how the upgrade process working ?as there is no upgrade process available for dataflow.only replace old one or rename old one.but in that case new dataflow wont pickup the data which was laready synced by old dataflow.like the flow usage informartion.all auditlogs informations are not pulled again when you replace the old dataflow with new on.you cant merge that as well

**Comment by Jenefer-Monroe** [comment]
We do not anticipate shipping another one for quite a while, this is our first rev since our initial Dataflow. 
But I do hear you that we need to think through the process if we release a new one again.

**Comment by jayakumarkgds** [comment]
> We do not anticipate shipping another one for quite a while, this is our first rev since our initial Dataflow. But I do hear you that we need to think through the process if we release a new one again.

I remeber there was an interim fix last month and we have updated the dataflow.If there is a change in Jan month we need to upgrade this as well.But unfortunately we dont see any process for powerBI dataflow upgarde for COE solution.if i replace i will loose old usage data like Audit information.

**Comment by Jenefer-Monroe** [comment]
I'm not sure that you would lose the audit information, the dataflows fetch from the source. But I could be wrong. 
Regardless unfortunately we do not have another solution here today. We are bound by the limitations of Dataflows and as the Data Export product feature that the CoE kit depends on for the BYODL implementation continues to be in public preview which means we've seen very slow adoption of the integration and customers understandably are not taking a dependency on this feature due the preview nature. 
In order to better utilize resources in our team and make sure we invest in the right features, we are pausing investments related to the BYODL architecture and will re-focus our investment here once this feature is GA. We may continue to make small fixes if they are well understood.
In the meantime, you can continue to use the BYODL architecture as-released and make your modifications and extensions to it, or switch to the sync flow architecture. We've recently made big improvements to the sync flow architecture as well, so this is less impacted by throttling and has a much lower API call volume.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
