### ISSUE TITLE
[CoE Starter Kit - BUG] Picture doesn't load in Outlook - admin_eMailBodyStart

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7532]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,
I'm currently working on updating the 'admin_eMailBodyStart' Environment Variable to incorporate a new image stored in our SharePoint folder. Strangely, while the image appears correctly when viewed in Outlook's web version, I encounter the following error when accessing it through the desktop app:

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/1ced7d81-d6e7-41b1-8c4f-c3bcd0555d9c)

I have verified that all permissions for our SharePoint library are in order.

Curiously, images from other locations display without any issues.

Has anyone experienced a similar issue before?

Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

January 2024

### What app or flow are you having the issue with?

All Flows that send emails 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2126

**Comment by Jenefer-Monroe** [comment]
Hello. We've seen issues like this where the mail will display differently in OWA v Outlook. Unfortunately this is likely an issue for the integration between SharePoint and Outlook rather than something we could resolve in the kit. I know SP has issues sharing images in different locations. 
Happy to hear if others have ideas on ways we could get around this.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for the starter kit team
