### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Kargadong-Putik** [microsoft/coe-starter-kit#7534]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have received an email with the title "CoE Starter Kit - Orphaned Objects: Manager did not respond" but we have already replaced the owner of the flow. Is there anyway to check why we are still receiving this emails?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.11

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2129

**Comment by RahulBojji** [comment]
@Kargadong-Putik Can you please let us know how you updated the owners of the orphaned flows ??

**Comment by Kargadong-Putik** [comment]
> @Kargadong-Putik Can you please let us know how you updated the owners of the orphaned flows ??

Some of the flows were updated by the new owner via "PowerAutomate" site via owners section of the flow, while other flows updated the ownership by Admins using COE App "Power Platform Admin View" via "Manage Permissions" assign owner.

**Comment by RahulBojji** [comment]
we have not yet updated the kit to use the information from changing the owner in the product but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see [#3052](https://github.com/microsoft/coe-starter-kit/issues/3052)
In the meantime you likely want to set it in both places. In the product so that its correct from the product pov (the most important piece) and then in the kit so that the processes can see it

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
