### ISSUE TITLE
[CoE Starter Kit - Feature]: Data Export to Azure Storage

### ISSUE THREAD

**Issue by AleckTK** [microsoft/coe-starter-kit#7539]
### Is your feature request related to a problem? Please describe.

At current when using Data Export, if an environment is deleted the JSON file is not deleted or removed from the Storage account and the data will continue to sync and notifications will continue to be sent out to Makers. 

I believe the JSON has environment state of being deleted

### Describe the solution you'd like

Maybe has something in the solution to highlight a Environment has been deleted and stop data exports/inactivity from running on that specific environment. 
Possibly alert the Admin as well that the environment has been deleted so we can clean up. 

### Describe alternatives you've considered

I have only thought about manually cleaning up the JSON files but maybe a flow might help 

### Additional context?

![image](https://github.com/microsoft/coe-starter-kit/assets/153608822/5f868d31-f205-43b0-84f6-285b4024c684)

AB#2136

**Comment by Jenefer-Monroe** [comment]
Thank you for posting this is an interesting idea. 

The Data Export product feature that the CoE kit depends on for the BYODL implementation continues to be in public preview which means we've seen very slow adoption of the integration and customers understandably are not taking a dependency on this feature due the preview nature. 

In order to better utilize resources in our team and make sure we invest in the right features, we are pausing investments related to the BYODL architecture and will re-focus our investment here once this feature is GA. We may continue to make small fixes if they are well understood.

In the meantime, you can continue to use the BYODL architecture as-released and make your modifications and extensions to it, or switch to the sync flow architecture. We've recently made big improvements to the sync flow architecture as well, so this is less impacted by throttling and has a much lower API call volume.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
