### ISSUE TITLE
[CoE Starter Kit - Feature]: Data Export BYOD Flows

### ISSUE THREAD

**Issue by tkudya** [microsoft/coe-starter-kit#7540]
### Is your feature request related to a problem? Please describe.

Some Environment are not always updated in time for inactivity flows/ other flows to run in the Storage account .json file. meaning Makers are being sent outdated information when something has changed

### Describe the solution you'd like

Something to paus ore not run the inactivity flows and any other compliance flows if the information has not been updated for a certain period to prevent

AB#2137

**Comment by Jenefer-Monroe** [comment]
Thank you for posting this is an interesting idea. 

The Data Export product feature that the CoE kit depends on for the BYODL implementation continues to be in public preview which means we've seen very slow adoption of the integration and customers understandably are not taking a dependency on this feature due the preview nature. 

In order to better utilize resources in our team and make sure we invest in the right features, we are pausing investments related to the BYODL architecture and will re-focus our investment here once this feature is GA. We may continue to make small fixes if they are well understood.

In the meantime, you can continue to use the BYODL architecture as-released and make your modifications and extensions to it, or switch to the sync flow architecture. We've recently made big improvements to the sync flow architecture as well, so this is less impacted by throttling and has a much lower API call volume.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
