### ISSUE TITLE
[CoE Starter Kit - BUG] Power App Launches showing up 3 times for each launch.

### ISSUE THREAD

**Issue by cant682** [microsoft/coe-starter-kit#7542]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Audit Logs are showing app launches 3x for each app launch, they all appear at the same time so it looks to be duplicates.

### Expected Behavior

Single entry to app launches listed in audit log.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/123032850/4c5744d2-07b6-4706-9415-b2752ed575ce)

AB#2139

**Comment by Jenefer-Monroe** [comment]
I've seen this happen sometimes. Unfortunately it maps directly to multiple records in the data source which you can see by browsing to the Audit Logs directly. So this is a bug in the product writing to the audit logs, rather than in our reading them. 
https://compliance.microsoft.com/auditlogsearch?viewid=Async%20Search
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f395d718-20d1-416c-a2c7-847908290492)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
