### ISSUE TITLE
[CoE Starter Kit - BUG] App isn't compliant with the latest data loss prevention policies

### ISSUE THREAD

**Issue by chiragknzariya** [microsoft/coe-starter-kit#7551]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

When I open a flow record and click on "Turn Flow Off" or "Turn Flow On". I got below error:

It looks like this app isn't compliant with the latest data loss prevention policies.
Policy Name: xxx
Connector action: SearchUser within connector:shared_office365users
Connector action: UserPhotoV2 within connector:shared_office365users

I have checked and verified with one of the Microsoft engineer: Priya Elangovan that above policy has all the connectors and it's actions are enabled for the environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2150

**Comment by pre-alt** [comment]
Hi Team , please note that Turn off and on button exists only when the Coe kit is installed . When tried to access the buttons getting error as mentioned above. please look into this if this is a bug or a known issue and help us with some workaround or a mitigation steps in need at the earliest.

Providing the error message which display on accessing the button :
When I open a Flow record and click on "Turn Flow Off", I got below error:

{"error":{"code":"ApiPolicyViolated","message":"It looks like this app isn't compliant with the latest data loss prevention policies.","details":[{"code":"MultipleViolations","message":"Policy name: CoE - Dev\r\nConnector action: SearchUser within connector: shared_office365users cannot be used since it is blocked by your company's admin.\r\nConnector action: UserPhotoV2 within connector: shared_office365users cannot be used since it is blocked by your company's admin.\r\n"}]}}
UciError: {"error":{"code":"ApiPolicyViolated","message":"It looks like this app isn't compliant with the latest data loss prevention policies.","details":[{"code":"MultipleViolations","message":"Policy name: CoE - Dev\r\nConnector action: SearchUser within connector: shared_office365users cannot be used since it is blocked by your company's admin.\r\nConnector action: UserPhotoV2 within connector: shared_office365users cannot be used since it is blocked by your company's admin.\r\n"}]}} at s (https://content.powerapps.com/resource/uci-infra/scripts/app.86f18c81fe5e5b157dd865f33752650d.js:33:932262) at https://content.powerapps.com/resource/uci-infra/scripts/custompage.9a66a0c445414f6a9486bdfca39a0498.js:4:221315

**Comment by RahulBojji** [comment]
Please check in the policies, looks like the connectors might be added in Blocked or Business group. Because of this you might be experiencing the above issue

**Comment by Jenefer-Monroe** [comment]
Hello, please note that the Turn off and on buttons in the kit only refer to the product connector which has Turn on and Turn off actions. 
If you go to the flow directly and attempt to turn it on manually you should get the same error.

**Comment by chiragknzariya** [comment]
Hi @Jenefer-Monroe I am able to Turn On and Off the flow directly. Thanks!

**Comment by Jenefer-Monroe** [comment]
That button calls this flow which in turn only calls this product flow. So there is nothing unique about the kit here. Perhaps the flow recalled a cached answer for DLP at the time. 
If you try to run this helper with your flow information now (off and on again). What do you see? 
Command Center App > Set CoE Flows State


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a4d776c8-1bd2-46a6-85b3-a2f6fc829eb5)

**Comment by chiragknzariya** [comment]
Hi @Jenefer-Monroe I am able to turn on and off one flow using Command Center App > Set CoE Flows State. Thanks!
I would like you or anyone from your team to schedule a call and check the issue as I need to resolve this on priority. cc: @pre-alt

**Comment by RahulBojji** [comment]
Please note that, we do best effort to assist our GitHub customers, but we are not funded to meet with them outside of the context of communicating here.
Thanks

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not sure what is left to resolve?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by pre-alt** [comment]
Hi Jenefer,

Greetings!

I am the support engineer from Power automate team. If this is not related to CoE kit may I confirm why the Turn off and On button is getting displayed or installed once the Started kit is been installed. Because we got inputs from customer Chirag that these Turn off and On buttons are installed when the starter kit is in place but if it is not installed those buttons are not visible .

Please clarify the above detail on priority so that it can help us to check it at our end on priority .

Regards
Priya Elangovan

________________________________

**Comment by chiragknzariya** [comment]
Hello @Jenefer-Monroe,
Can you please help resolve the issue, as from UI still it shows DLP error mentioned as above? Thanks

**Comment by manuelap-msft** [comment]
Hello @chiragknzariya, when you say "the UI shows the DLP Error" - can you please share a screenshot of what UI you are talking about here? Can you also explain what is blocking you from proceeding as you said above that you were able to turn on/off the flows?

**Comment by Jenefer-Monroe** [comment]
Hello please note that we cannot hold issues open indefinitely so please do let us know if there is anything you need help with here.

**Comment by pre2024** [comment]
Sharing the screenshot on behalf of customer :

![image](https://github.com/microsoft/coe-starter-kit/assets/158031268/00d4a013-cab9-4512-8b94-51f426807936)

**Comment by Jenefer-Monroe** [comment]
ok yes this references an app that we use to say "are you sure" 
it has connectors in the app and so those connectors need to be supported by the DLP policies for the envt
In this case it looks like its saying you've blocked O365 Users connector, which I didnt even know was possible but that is the issue.

**Comment by chiragknzariya** [comment]
@Jenefer-Monroe O365 Users connector is enabled and environment is added in the policy. Thanks!

**Comment by Jenefer-Monroe** [comment]
I'm sorry this is a product error about DLP. That is a product error saying you do not have the correct DLPs applied. If that is untrue it is a product issue with DLP. Wouldnt you agree?

**Comment by chiragknzariya** [comment]
> I'm sorry this is a product error about DLP. That is a product error saying you do not have the correct DLPs applied. If that is untrue it is a product issue with DLP. Wouldnt you agree?

I have told exactly the same @Jenefer-Monroe , when I have been asked to raise it here. Thanks!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for the starter kit team
