### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - ERROR

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#7589]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Getting error in Core Component's flows -

"Admin | Sync Template v3 (Desktop flows)" : Http request failed as there is an error: 'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'.

"Admin | Sync Template v3 (Solutions)" : Looks like your flow's operation is hitting an action limit designed to protect the connector service being called.

Can anyone suggest any way to get rid of this.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

None

AB#2197

**Comment by RahulBojji** [comment]
For "**Admin | Sync Template v3 (Desktop flows)**" There was a issue reported on the same and it was fixed in the January Release. Please have a look at [this](https://github.com/microsoft/coe-starter-kit/issues/7220), But for large organizations there are some limitations. Please have a look at this [comment ](https://github.com/microsoft/coe-starter-kit/issues/5633#issuecomment-1569483263)  and also [this](https://github.com/microsoft/coe-starter-kit/issues/4557#issuecomment-1377169762)

For "**Admin | Sync Template v3 (Solutions)**". Can you please check if there are any unmanaged layers on the flow. If not, please share the screenshots of the flow exactly where it's failing.

**Comment by bhupendra14** [comment]
@RahulBojji there is no unmanaged layer on the flow, It's failing on the first action, FYI Screenshot with error.

![Screenshot CoE](https://github.com/microsoft/coe-starter-kit/assets/35683189/e613e2c9-f5e9-4e7f-a982-71baed56bd30)

**Comment by bhupendra14** [comment]
![Screenshot 2024-02-05 161736](https://github.com/microsoft/coe-starter-kit/assets/35683189/c38bb2a5-06dc-4a75-a314-8fea5ad5de5a)

**Comment by RahulBojji** [comment]
As per the screenshot, it's not failing at the first step. It Executed the false block of the if condition. Since there are no actions in the false block, it might have executed next actions after if condition. Can you please share those screenshots?

**Comment by bhupendra14** [comment]
> As per the screenshot, it's not failing at the first step. It Executed the false block of the if condition. Since there are no actions in the false block, it might have executed next actions after if condition. Can you please share those screenshots?

I have checked, it stopped here only there is no step been executed after if condition.

**Comment by Jenefer-Monroe** [comment]
Can you please take a larger screenshot? It must continue below as there are no failures in what you have shown

**Comment by bhupendra14** [comment]
Hi @Jenefer-Monroe , please see the below snapshot, it's not showing anything in the false condition.

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/49a26dec-68f7-4e53-9462-5e6663e32933)
