### ISSUE TITLE
[CoE Starter Kit - BUG] - Number of Apps and Number of Flows are equal to 0 in the Dataverse Table : "Environment"

### ISSUE THREAD

**Issue by JulietteMahe1** [microsoft/coe-starter-kit#7592]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 
I have an issue about the Environment Table : My columns Number of Apps and Number of Flows are equals to 0, when in fact this is not the case.
I don'k know how these columns are filled, all the flows are running very well... I need help...
![CoE_Issue](https://github.com/microsoft/coe-starter-kit/assets/159022938/68ee0f6d-9fb1-4707-90b6-6985d0b443f3)

However, the Power Apps App and Flow table, we have the apps and flows associated with their environment.

Thanks to you !

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Environment Table

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2200

**Comment by Jenefer-Monroe** [comment]
These fields are roll up fields and so for a new install they take a while to update. It’s typically a 12 hour wait after the inventory completes before you can expect to see these populate but the product itself is what determines how frequently and when to update these roll up fields.

You can force these to calculate. Please see the tip in this product team article on [Rollup columns](https://learn.microsoft.com/power-apps/developer/data-platform/calculated-rollup-attributes#rollup-columns)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d374b7dc-82e2-499d-8855-be81a70bdb98)

If its been a while since install and you still see zeros, it could be that the rollups broke or got deactivated somehow. Please [View Rollup Jobs](https://learn.microsoft.com/power-apps/maker/data-platform/define-rollup-fields#view-rollup-jobs) and see their state.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/50ca6f07-dc57-4188-8db6-47198478608b)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
