### ISSUE TITLE
[CoE Starter Kit - BUG] The removed Power Automate flows and Canvas apps are still showing in the Power Platform Admin View app.

### ISSUE THREAD

**Issue by MgNa-H2O** [microsoft/coe-starter-kit#7622]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When the user removes the Power Automate flow or Canvas app from an environment, the specific flow or app will still show up in the CoE Power Platform Admin View as active for one week to three weeks.

### Expected Behavior

The active Power Automate flow and Canvas app in the environment should be the same as the flow or app show up in the CoE Power Platform Admin View.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

AB#2246

**Comment by Jenefer-Monroe** [comment]
Objects are removed from inventory by the Check Deleted cleanup flow and its helpers. 
Because its long running it is set to only run once every 2 weeks. Good news is that we were able to reduce the time and api hit of the flow with a refactor that you can see in **_CLEANUP - Admin | Sync Template v4 (Check Deleted)_** which is set to run weekly as of the Feb release.

**Comment by MeinaHe** [comment]
Sounds good, i will keep monitoring it, thank you so much for your help.

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
