### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can we add retry policy for all the Sync flows

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#7636]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

We are getting the throttle limits issues on the flows. Can we add retry policy for all sync flows?

The specific flow below is having issues on "Get Apps as Admin" action.

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/14978a56-2937-4174-8fcc-7290efdab398)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v4 (BYODL App Properties)

### What method are you using to get inventory and telemetry?

Data Export

AB#2264

**Comment by Jenefer-Monroe** [comment]
We do have retry in most places ut it looks like we missed it here.

**Comment by devvelegandla** [comment]
@Jenefer-Monroe 
Yes its working but the issue is these flows runs forever. can you update the settings with Min and Max intervals?

**Comment by Jenefer-Monroe** [comment]
This is not a common problem we have heard about so I would rather not make a change like that right now as we dont do it elsewhere in the kit and so I'm not sure the consequence.

Please note that the Data Export product feature that the CoE kit depends on for the BYODL implementation continues to be in public preview which means we've seen very slow adoption of the integration and customers understandably are not taking a dependency on this feature due the preview nature. 
In order to better utilize resources in our team and make sure we invest in the right features, we are pausing investments related to the BYODL architecture and will re-focus our investment here once this feature is GA. We may continue to make small fixes if they are well understood.

In the meantime, you can continue to use the BYODL architecture as-released and make your modifications and extensions to it, or switch to the sync flow architecture. If you make this suggested change locally and run for a while and find it does not have negative ramifications please do let me know and we can reconsider

**Comment by Jenefer-Monroe** [comment]
Actually I think this issue you described will be resolved by these two changes:
One fixed in Feb: https://github.com/microsoft/coe-starter-kit/issues/7504
The other fixed in March:  https://github.com/microsoft/coe-starter-kit/issues/7525

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
