### ISSUE TITLE
[CoE Starter Kit - BUG] 80048539 - Updating COE error / two solutions now present

### ISSUE THREAD

**Issue by RandomDept** [microsoft/coe-starter-kit#7680]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Looked through the old bugs and while I see this reported, I didn't manage to see a solution.
![help](https://github.com/microsoft/coe-starter-kit/assets/151495228/607caea7-f011-46b1-8e0f-bcfb9b726664)

It looks like the import of 4.23 worked on 19/2 but then the uninstall / upgrade failed. This would have been due to Audit logs being set up the old way. I rectified this and tried again but now I get 80048539

Solution manifest import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade already exists.

I assume this is because we see CentreofExcellenceCoreComponents 4.23 showing as success on 19/2 @ 9:15 before the original upgrade failure @ 9:22.

Can I safely delete the CentreofExcellenceCoreComponents 4.23 Solution and reimport to upgrade?
When I open command centre app it is still telling me I am using an old version of the COE and to update.

Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

COE upgrade

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Import new solution - upgrade

AB#2316

**Comment by Jenefer-Monroe** [comment]
When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 
These will never converge or repair on their own, you will need to take action to resolve. 
You must first delete the _Upgrade before you can try to upgrade again. If this was due to the old audit log solution, here are some steps to help you out: https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by RandomDept** [comment]
Win, thank you.
