### ISSUE TITLE
[CoE Starter Kit - QUESTION] About the owner of the application and flow

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#7682]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have a flow where the owner does not match for the owner displayed in Power Platform Admin Veiw, is there a way to reacquire them all?
Management center and application information did not match.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2327

**Comment by asuka1103131** [comment]
@RahulBojji 
Below is a screenshot.
The owner in the CoE is ”高木飛鳥”, but in the management center, the owner is ”長井涼”.

・Information acquisition in CoE
![image](https://github.com/microsoft/coe-starter-kit/assets/156406138/db9bfee1-6fd5-487c-a781-45c492671ff1)

・Obtaining information at the management center
![image](https://github.com/microsoft/coe-starter-kit/assets/156406138/d578e280-f63d-496e-8e87-dcf9c0ab2b0b)

**Comment by RahulBojji** [comment]
can you please confirm if the owner of the flow is modified in the power automate portal after creating it ??

**Comment by asuka1103131** [comment]
@RahulBojji 
Where is the Power Automate Portal located?
The Power Automate flow was created for testing.

**Comment by RahulBojji** [comment]
Here is the [Power Automate](https://make.powerautomate.com/) Portal. If the owner of the flow is changed from here, the updated owner is not available programmatically via any connector.

we have not yet updated the kit to use the information from changing the owner in the product but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see https://github.com/microsoft/coe-starter-kit/issues/3052
In the meantime you likely want to set it in both places. In the product so that its correct from the product pov (the most important piece) and then in the kit so that the processes can see it
