### ISSUE TITLE
Admin | Sync Template v3 (PVA) - The length of substring can't be longer than '6' which is the length of the source

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#7690]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, the Admin | sync template v3 (PVA) is still in error for 2 of my environments with the error Action ‘Check_if_Orphan_-_Edit’ failed. Looking at the update bot action, I have this message The length of substring can’t be longer than ‘6’ which is the length of the source.

Could this be due to an action in the bot?

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/3705e603-26b1-4962-8580-1a6f57d6fea0)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA) 

### What method are you using to get inventory and telemetry?

None

AB#2335

**Comment by Jenefer-Monroe** [comment]
We fixed this bug in the past by looking at component state instead of component state label but it looks like we forgot to apply the fix to the Edit side, you can see it correct on the new side
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f48407c1-c051-4b72-bbbf-3e21082aee8a)


Good news is that this is resolved already in the v4 version of the flow which is available to you now to use instead, and is the only option starting in the March release.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2c413e45-3e57-4283-90df-8c5753577fda)

**Comment by tocri** [comment]
Wow. Thank you for the quick reply. I'm looking forward for the next release then. ❤️

**Comment by Jenefer-Monroe** [comment]
YEAH! I'll go ahead and close then, the March build shoudl ship March 6th, you can track this issue to be notified when it ships. https://github.com/microsoft/coe-starter-kit/issues/7535
