### ISSUE TITLE
BYODL PowerApps, too many & mostly w/o name or environment

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#7698]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

There should be about 12,000, but the table has almost 22,000 rows. 3/4 have no name or environment. 1/4 don't even have AppIDStrings. The Dataflows and BYODL cloud Flows are running without errors. Here's an export from the CoE Apps. Other tables all look good.

### Expected Behavior

Should be about 12,000, with names, environments, etc.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

PowerApps table in CoE

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Run the Maker Dataflow and then look at the PowerApps table.

### Anything else?

[All Apps 2-20-2024 4-59-04 PM.xlsx](https://github.com/microsoft/coe-starter-kit/files/14351743/All.Apps.2-20-2024.4-59-04.PM.xlsx)

AB#2344

**Comment by Jenefer-Monroe** [comment]
We have had a bunch of changes to the export files and are iterating fixes this month. You will need to upgrade to the March release to get these changes when its available in a few weeks.

**Comment by RickKush** [comment]
Should/could I downgrade to 2.23?

**Comment by Jenefer-Monroe** [comment]
No its due to a change in the Data Export files not a change in our code. We discovered them yesterday and so I was scrambling yesterday to fix for March. 
So the issues will appear for everyone using the Data Export feature regardless of build. 

Please note this is the reason we suggest people not depend on it yet as the Data Export feature is still in preview and so changes like this can result in the inventory being wrong while we adjust our toolkit to match those schema changes.

[What data source should I use for my Power Platform inventory?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/36a988c7-e9b4-46cf-9783-b9adaba3a6ca)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
