### ISSUE TITLE
[CoE Starter Kit - BUG] PowerPlatformGovernance_CoEDashboard_Feb2024 - Cross tenant report issue

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#7706]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am refereeing here my previous two ticket which is in close state - "issues/6387", "6692"

Now the situation is worse in cross tenant report

User which belongs to my tenant (st.com) also reported as cross connection
Item count in report drastically grown up to 15.74k
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/aeb10d90-8dc0-4a84-9b86-5b539a5da7af)

Admin | Sync Template v4 (Connection Identities): this flow running successfully, however its seems that there is issue during appending the URL 

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/0b4aec64-b60c-403e-9d8b-00aecfdcc74e)

### Expected Behavior

Cross connection count should be correct and should not report our domain in cross connection report.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23 

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Connection Identities)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2354

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not following. 
What do you have configured for your Host Domains env var? And note that we do not go back and fix existing records when you change that env var. This is due to the extreme API hit of it. 

Please see [How to change what is considered "local" for the Cross Tenant Connection References report](https://github.com/microsoft/coe-starter-kit/issues/7164#issuecomment-1819454712) and 
[How to update existing data to respect the configured local tenants](https://github.com/microsoft/coe-starter-kit/issues/7164#issuecomment-1819498144)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
