### ISSUE TITLE
Is it possible to isolate the inactivity components to just look for apps rather than flows? 

### ISSUE THREAD

**Issue by melbare** [microsoft/coe-starter-kit#7711]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

Is it possible to isolate the inactivity components to just look for apps rather than flows? Would this possibly be done by turning off the Flow Approvals flow within the Inactivity Components?

Thank you

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.15

### What app or flow are you having the issue with?

Inactivity Processes

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2360

**Comment by melbare** [comment]
Want to know any side effects also, like whether already sent out approvals for flows will somehow mark them for deletion or email the Maker forever.

**Comment by Jenefer-Monroe** [comment]
I have not tested this myself but yes I think you are correct. Turning the flow off should mean they dont get bothered anymore but to be certain, here is what you can do

- Turn off **_Admin | Inactivity notifications v2 (Start Approval for Flows)_**
- Delete the records in the **_Archive Approval_** table
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1a7af514-8866-4a72-bb35-5fe4fd41eb5d)
- Clear the Flow Archive Request Ignored Since flag in the Flow table (I would use export to excel for this)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c337c37c-52e2-4b09-bf38-48743166bbe4)

**Comment by melbare** [comment]
Closing issue
