### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cleanup Old Objects App 

### ISSUE THREAD

**Issue by sasrsc** [microsoft/coe-starter-kit#7718]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Note: we're using the Jan 24 version of the CoE.
I was looking at the admin_archiveapproval table directly in Power BI and comparing the information in there versus what the user sees in the Cleanup Old Objects App. The counts are different. 
1) I assume the app uses the admin_archiveapproval table for the data. True/False. If False what table does the app use.
2) Are there any filters on the data used in the app that could account for the differences. My Power BI was showing more items that they didn't see in the app. 
3) In the app, some users have complained that they will approve or reject something and add comments yet when they come back to the app the status is not reflected. I've witnessed that myself and had multiple people express a similar message. They can update most rows. Someone wondered if it's related to something that is shared. I didn't think so as I share virtually all my apps/flows.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Jan 2024

### What app or flow are you having the issue with?

Cleanup Old Objects App

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2366

**Comment by Jenefer-Monroe** [comment]
Hello please note that this feature area of inactivity is up for reimagining and this app will not survive that change as it does not match the modern look / feel / patterns for us. So improvements / changes to this app for small improvements are not likely. 

The data shown here is based off the objects. Here you can see how the apps are collected:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a1a6adb7-0bac-43ea-baed-7b40af1d49aa)

Regarding not updating, this is tracked by https://github.com/microsoft/coe-starter-kit/issues/5456
Thanks for pressing on it. I did a little more investigation so I wouldn't have to punt again and found that you need to have a particular setting on the app done which wasn't on. So that should be fixed for March now.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
