### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View - Sum of number of apps and flows per environment shows zero but data are populated

### ISSUE THREAD

**Issue by MaxImumOccupancy** [microsoft/coe-starter-kit#7726]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

in the [Power Platform Admin View], in the "active environment" chart, the Sum of number of apps and flows per environment shows zero but data are populated. Checking the "PowerApps Apps" and "Flows" entries I can see apps and flows with the environment field correctly populated. If I click on the environment lookup, it opens the related record and checking the "Resources" Tab it shows all the Apps and Flows for that environment. COE core component install completed Friday 23rd Feb, one flow was not turned on "Admin | Sync Template v3 (Environment Properties)", turned on on Feb 26th at 9.40. Not sure if it is related.

### Expected Behavior

The chart "active environment" should show the correct number of Apps and Flows for each environment

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2380

**Comment by Jenefer-Monroe** [comment]
These fields are roll up fields and so for a new install they take a while to update. It’s typically a 12 hour wait after the inventory completes before you can expect to see these populate but the product itself is what determines how frequently and when to update these roll up fields.
You can force these to calculate. Please see the tip in this product team article on [Rollup columns](https://learn.microsoft.com/power-apps/developer/data-platform/calculated-rollup-attributes#rollup-columns)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d374b7dc-82e2-499d-8855-be81a70bdb98)
If its been a while since install and you still see zeros, it could be that the rollups broke or got deactivated somehow. Please [View Rollup Jobs](https://learn.microsoft.com/power-apps/maker/data-platform/define-rollup-fields#view-rollup-jobs) and see their state.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/50ca6f07-dc57-4188-8db6-47198478608b)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
