### ISSUE TITLE
[ALM Accelerator - QUESTION] Environment Management and Access Issues in AA4PP

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#7779]
### What is your question?

Hello,

I'm dealing with some confusion regarding the management of environments in AA4PP. I have a user who, as an "Environment Maker" security role holder , is supposed to have access only to the "Env A" and "Env B" environments. However, when he opens AA4PP,  he can see more environments than he should. If he try to access these environments, an error message appears, stating they do not have access. This situation is very disturbing for the user.

I've attempted to fix this issue by reloading the app in incognito mode, but it didn't make any difference.

Additionally, I'm facing the reverse issue: some users with the "Environment Maker" role on a specific environment are unable to see it in the app.

Could you please help me with these issues?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20240104.1

AB#2476

**Comment by mikefactorial** [comment]
@tocri this is a known issue. The app uses the PowerAppsForMakers.GetEnvironments() connector function to get a list of environments available to the user. Unfortunately, the inner workings of that connector are a bit of a mystery. It may be returning all environments the user has a role in or possibly any environment that the user exists in or even any environment in which the user has access to some component (e.g. an app). I'm not sure how we could filter that down further, but I wouldn't expect an environment to be returned that isn't an environment that shows in the maker portal as well. We do filter out non-Dataverse environments but not sure we have information in the data returned by the connector to filter it down further. We can't really check to see if the user has a role in the environment, for instance, if the user doesn't have permission to view roles since the user's context would be the one querying that information.

**Comment by tocri** [comment]
Sorry for the delay. I understand and i have now some explications that i can give to my users.
