### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flows containing broken connections

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#7788]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi I have been looking in the Admin | Sync Template v3 (Flow Action Details) to see where Flow Contains Broken Connections is updated and I am not able to see this, is there another flow this updates in?
When looking at the admin view app within the orphaned flows view,  all of the Flow Contains Broken connections is set to no, should this not be set to yes as the flow is orphaned and there is no connection?
I am just trying to fully understand how the CoE starter kit fully works :)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.15

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details) 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2486

**Comment by Alyson95170** [comment]
Also the "flow last run ON" is also not updating this is showing blank for active and orphaned flows

**Comment by Jenefer-Monroe** [comment]
Hello. Happy to help. 

**_flow last run ON_** - this field is only filled when using the Data Export architecture. there is a feature from the product team that is shipping in a few months that will unblock us from doing this work if we find an efficient way to do so. 

**_Flow Contains Broken Connection_** - I think this is just poorly named, I hadnt thought of it the way you did but now I cant unsee it. So this just means that the inventory isnt complete because the flow uses a connection not yet in inventory .

So imagine a case where you've made a custom connector and added a flow. 
The flow gets inventoried before the custom connector. In this case we flag the flow has "has broken connection" 
This will cause the flow to go through inventory again the next day at which point the CC will be in the inventory and we can clear this flag.

**Comment by Alyson95170** [comment]
Thanks for the update Jenefer that makes sense
