### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor v2 defects

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#780]
### Describe the issue

1. The selector of enviroments in  "DLP Editor v2" doesn't show results.
2. Doesn't show the DLPs that we haved created in the tenant.

### Expected Behavior

1. The expected behaviour wil be to can select a Enviroment to try a DLP.
2. To can to select a DLP existing to edit it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

Simply opening this app.

### Anything else?

![image](https://user-images.githubusercontent.com/57954993/124880092-33c90080-dfce-11eb-8990-2515aee49dc8.png)

![image](https://user-images.githubusercontent.com/57954993/124880146-44797680-dfce-11eb-99ba-55e399d5e2a4.png)

In the first issue, if I go to "+ New Tenant Policy" and go back to the initial screen, the enviroments are showed in the selector:
![image](https://user-images.githubusercontent.com/57954993/124884762-e1d6a980-dfd2-11eb-9c43-7b1ac8301af9.png)

**Comment by manuelap-msft** [comment]
Hello,

I don't repo this in my install - it also looks like you may have not received the latest upgrades. Due to a product limitation, we had to remove the + New Tenant Policy button and I still see that in your UI.

Here's what the new version should look like:
![image](https://user-images.githubusercontent.com/55705669/124893341-8c9a9800-dfd2-11eb-9963-a081663e9810.png)

You may have had an unmanaged layer on the app before upgrade which means you didn't receive the latest version? Can you check for solution layers: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

Thank you
Manuela

**Comment by albertocaa1317** [comment]
Hi @manuelap-msft 
you are in the correct, I had a unmanaged layer in this app created after investigate a issue with this app in the June version. After remove it the app runs OK. Sorry.

Let me one question: then, now with this app can't we create a new DLP and review the impact in the enviroments? Now the way to do this wil be, firstly I create a DLP in PPAC, and after I edit it from DLP Editor V2 and analyse the impact, is it correct?

**Comment by manuelap-msft** [comment]
No worries! Thanks for confirming it works now!

Yes - we had to remove the "Create Policy" action due to an issue with the [Create Policy action](https://docs.microsoft.com/en-us/connectors/powerplatformforadmins/#create-dlp-policy-v2) we're using of the Power Platform for Admins connector where this wasn't working properly - we're investigating this!

Yes, the best way is to create a DLP Policy in the Power Platform Admin Center and not assign it to any environments there (so as to not cause an impact) and then open the DLP Editor v2 and edit the policy, select the environments you want to apply it to and analyse the impact from there. Updating the policy from the DLP Editor works, it was just creating it that caused issues.

I'm going to close this issue now, but please let me know if you experience further problems with this app!

Thank you
Manuela
