### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard for Compliance gets stuck

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#7806]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Within the set up wizard, when selecting the Compliance Process module, a message pops up saying "Missing prerequisite - return to this setup wizard when the Admin | Sync Template v3 (Driver) flow has finished running". It looks like 'Admin | Sync Template v3 (Driver)' no longer exists and is stopping progress.

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/88755a7c-5f17-4e2e-9de9-c3048fbfa4a1)

### Expected Behavior

When selecting the Compliance Process module, the Next button can be clicked.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run the wizard app
Click on More features
Click on 'Compliance process' - configure this feature
The pop up appears.

AB#2512

**Comment by tocri** [comment]
i have the same issue and it s the same issue for **inactivity notification process**

**Comment by Jenefer-Monroe** [comment]
Looks like we forgot to update that when we updated the Driver to V4. 
Easy fix for April.

**Comment by Jenefer-Monroe** [comment]
- [x] compliance
- [x] inactivity
- [x] Teams evnts

**Comment by MartinWGT** [comment]
Is there another way to select the Environments that are excluded from governance?

**Comment by madhavjaya** [comment]
It looks like some inventory flows required to set up the Compliance process haven't finished running yet. Please check the CoE flows page of the Admin - Command Center app, and return to this setup wizard when the Admin | Sync Template v3 (Driver) flow has finished running.  I get this error as well. Is there any chance we can fix this early as I'm working with a customer to deploy this tool and we cannot make it work with the March Version.

**Comment by Jenefer-Monroe** [comment]
Hi folks. Sorry for the delay in response just saw your notes when I came to mark the fix test complete. Here are some workarounds

### Trick the Setup Wizard
If you want to use the setup wizard still you can fake it here by adding a records to the **_CoE Solution Metadata_** table
Go to that table, set it to show the records shown and filter to Object Name = **_Admin | Sync Template v4 (Driver)_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b52b0231-7cd7-427b-a239-5d726a3ac610)

Create a new record that is the same except has **_Admin | Sync Template v3 (Driver)_** for the name
And set it to have LastRunPassed = yes and LastRun = tomorrow
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/da07f236-e940-4c70-af32-35471478b774)

### Manual setup
You can also manually setup instead of using the wizard. 
The excuse from Governance flags are on the envt and you can edit that from the table view as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b38b654c-ebee-4a60-ab09-32ebf91eeac0)

And then turn the flows on manually as descried in the documentation: 

- [Set up inactivity processes](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components)
- [Set up Developer Compliance components](https://learn.microsoft.com/power-platform/guidance/coe/setup-governance-components)

**Comment by MartinWGT** [comment]
@Jenefer-Monroe Thanks for details!

**Comment by Jenefer-Monroe** [comment]
Yes this fix is ready for the April release.
