### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flow Action Details) Failed

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#7825]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello we noticed that one flow run was failed because of Get Flow action. I'm wondering whether the Get Flow as Admin action should be used here?

<img width="835" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/54030753/0d75d4b8-9a63-4145-974e-3234ba28cc68">

Error Message:

{"statusCode":403,"headers":{"Cache-Control":"no-store, no-cache","Strict-Transport-Security":"max-age=31536000; includeSubDomains","x-ms-islandgateway":"GA00000IL","x-ms-request-id":"westeurope:90d4a4e5-ad56-4b6d-aab4-93dfdcd7844d","x-ms-correlation-request-id":"90d4a4e5-ad56-4b6d-aab4-93dfdcd7844d","x-ms-flow-mobile-ios-version":"3.0.421","x-ms-flow-routing-request-id":"WESTEUROPE:20240313T052654Z:90d4a4e5-ad56-4b6d-aab4-93dfdcd7844d","Server-Timing":"x-ms-igw-upstream-headers;dur=342.5,x-ms-igw-req-overhead;dur=0.6","X-Content-Type-Options":"nosniff","x-ms-service-request-id":"ab516555-ba12-4cf4-b146-bdabec577d05","x-ms-correlation-id":"cb633de1-389a-4129-ab13-ec91cbc53531","x-ms-activity-vector":"IN.08.00","Timing-Allow-Origin":"*","x-ms-apihub-cached-response":"true","x-ms-apihub-obo":"false","Date":"Wed, 13 Mar 2024 05:26:53 GMT","Content-Length":"557","Content-Type":"application/json"},"body":{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '737db107-5c3a-X-X-X'. Connection '507ec42e-8e32-X-9553-X' to 'shared_logicflows' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}}

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2541

**Comment by Jenefer-Monroe** [comment]
This call has to be Get Flow, not Get Flow as Admin because the Get Flow as Admin call does not have the needed information for these specialty connections. For example what is the host called in an http request. 
The error reads like one of your connections is broken. 

Please log in as the user who’s identity installs and runs the kit and do the following:
### Fix connections. 
Browse to the connections in the envt. If there are any broken connections please repair them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2198fb17-1107-4851-a744-f3b34e89d11d)
### Fix Connection References
Go to the Default Solution > Connection References
Make sure they are all pointed to the correct identity which is intended to run the flows by doing the below for all connection references.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f630670f-9bf5-4c56-bf18-9693e0eeea01)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4a34cc4-5d46-494e-9a7d-e9d570489159)

**Comment by fim34** [comment]
Hi i have same issue ( core 4.29), all connection are made with a service account.
Connected to this account, there no connection to fix in connection tab and i not find one with name "shared_logicflows" or id.
All connection reference are good.
Where i can check to resolve this issue ?
