### ISSUE TITLE
COE starter kit Core components Solution Upgrade Issue

### ISSUE THREAD

**Issue by hereisavinash** [microsoft/coe-starter-kit#7855]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Even though the core components solution got updated to the latest version 4.23 the old version of core components 4.9 version is not getting deleted automatically.

Ideally the old version should get deleted automatically.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2573

**Comment by RahulBojji** [comment]
ust wanted to understand the state in which your environment is on. Can you please share screenshot of the list of solutions you have installed in your environment just like below. Please make sure you are expanding the highlighted columns.

![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/520221c4-a3cf-4184-b64f-02cb18c581b2)

**Comment by hereisavinash** [comment]
Hi Team,

Please find the attached screenshot. I have highlighted the old version in blue of core components 4.9 version which is not getting deleted automatically.

![COE Core Components](https://github.com/microsoft/coe-starter-kit/assets/159412164/3154f653-d6ca-4985-9a03-74bce35bf561)

Please assist on the same.

Regards.
Avinash.

**Comment by RahulBojji** [comment]
@hereisavinash When upgrade fails the product often leaves an _Upgrade and an original solution sitting there.
These will never converge or repair on their own, you will need to take action to resolve.
You must first delete the _Upgrade before you can try to upgrade again.

**Comment by hereisavinash** [comment]
@RahulBojji As this is COE starter kit product issue appreciate if you can share the exact solution for this with detailed steps. After deleting the _Upgrade what are the next steps.

**Comment by RahulBojji** [comment]
This is not a COE kit issue, that is D365 product behavior. As sometimes users face these import issues which might be because of timeout.  Once deletion of _upgrade solution successfully, you can try to import the version you are trying to install. 

In case if you face issues regarding the Office 365 management API custom connector which we have deprecated. Please follow [this](https://github.com/microsoft/coe-starter-kit/issues/6018) as we have documented the issue. We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors.
If you have tried those steps and still see this error, note that some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) these remaining connections to the old connector.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
