### ISSUE TITLE
[CoE Starter Kit - QUESTION] Question about the flows with similar names but different versions 

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#7905]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!
I had some questions regarding the flows with similar names but different versions.
For example these flows:

CLEANUP HELPER - Check Deleted (Solutions)
CLEANUP HELPER - Check Deleted v4 (Solutions)

CLEANUP HELPER - Check Deleted (PVA)
CLEANUP HELPER - Check Deleted v4 (PVA)

CLEANUP HELPER - Check Deleted (Canvas Apps)
CLEANUP HELPER - Check Deleted v4 (Canvas Apps)

CLEANUP HELPER - Check Deleted (Model Driven Apps)
CLEANUP HELPER - Check Deleted v4 (Model Driven Apps)

CLEANUP HELPER - Check Deleted (Cloud Flows)
CLEANUP HELPER - Check Deleted v4 (Cloud Flows)

CLEANUP HELPER - Check Deleted (Business Process Flows)
CLEANUP HELPER - Check Deleted v4 (Business Process Flows)

CLEANUP HELPER - Check Deleted (Ai Models)
CLEANUP HELPER - Check Deleted v4 (Ai Models)

Admin | Sync Template v3 (Solutions)
Admin | Sync Template v4 (Solutions)

Admin | Sync Template v3 (PVA)
Admin | Sync Template v4 (PVA)

Admin | Sync Template v3 (Portals)
Admin | Sync Template v4 (Portals)

Admin | Sync Template v3 (Model Driven Apps)
Admin | Sync Template v4 (Model Driven Apps)

Admin | Sync Template v3 (Desktop flows)
Admin | Sync Template v4 (Desktop flows)

Admin | Sync Template v3 (Business Process Flows)
Admin | Sync Template v4 (Business Process Flows)

Admin | Sync Template v3 (Ai Models)
Admin | Sync Template v4 (Ai Models)

Admin | Audit Logs | Update Data (V2)

Could I clarify, these versions (v3 and v4) mean something as "some new features added", but they are completely the same flows as the v3 flows? Or there is big difference between the v3 and v4 flows?

Also, some of these v4 flows have descriptions and some no; or have it really short. 
My question - is it possible to find somewhere the description of each new flow that doesn't have any deception (or even have really short description)? 

And, just to notify, I noticed that most of the new flows have one and the same deception. Does it need to be like that?
For example, these flows have this description:

CLEANUP HELPER - Check Deleted v4 (Solutions)
CLEANUP HELPER - Check Deleted v4 (PVA)
CLEANUP HELPER - Check Deleted v4 (Portals)
CLEANUP HELPER - Check Deleted v4 (Model Driven Apps)
CLEANUP HELPER - Check Deleted v4 (Desktop flows)
CLEANUP HELPER - Check Deleted v4 (Business Process Flows)
CLEANUP HELPER - Check Deleted v4 (Ai Models)

Description
"Does the check deleted work for a given environment for model driven apps"

and these flows have this description:
CLEANUP HELPER - Check Deleted v4 (Cloud Flows)
CLEANUP HELPER - Check Deleted v4 (Canvas Apps)

Description
"Does the check deleted work for a given environment for canvas apps"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What method are you using to get inventory and telemetry?

None

AB#2630

**Comment by bhupendra14** [comment]
@JanetK12 in the latest March release they removed most of the duplicates (same name with diff version) flows.
You might need to upgrade the Kit. 😊

**Comment by RahulBojji** [comment]
@JanetK12 Both V3 and V4 flows does the same thing. The only difference is in v3 version of the flows we were using Dataverse legacy connector, which is now deprecated, and the product has released a Modern Dataverse connectors. So, all the new V4 flows you are seeing they all use Modern Dataverse connectors instead of legacy connector. For example, please see [this](https://github.com/microsoft/coe-starter-kit/issues/6946) for more information on the work we did in replacing the old connector.

If you want to opt in to use V4 flows you can just toggle the flag in setup wizard. Please check [this](https://github.com/microsoft/coe-starter-kit/issues/7146) for more information. In the latest release, we have removed most of the v3 version flows. Hope this gives answers your question

**Comment by Jenefer-Monroe** [comment]
One last note, we left the v3 in there for two months with the V4. But the setup wizard turned on v4 and off v3. 
This was due to the large change, so we wanted to have a fall back mechanism in the event the v4's had some catastrophic issue we missed. 
All was well so from March forward the deprecated v3's are removed. 
And the product team is now starting the process of deprecating the connector upon which they relied.

**Comment by JanetK12** [comment]
@Jenefer-Monroe , could I clarify?
So, am I right to assume that if we decide to turn on the v4 flows, then at the same time we need to turn off all the v3 flows? As they are the same flows, so for both v3 and v4 to be turned on is not a good idea, right?

**Comment by Jenefer-Monroe** [comment]
Thats correct you want one or the other. I suggest you use the V4s as they are the only ones remaining going forward in the system. 
If you use the Setup Wizard this should be configured for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
