### ISSUE TITLE
Governance Stats - What tables store connector info

### ISSUE THREAD

**Issue by sasrsc** [microsoft/coe-starter-kit#7915]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am a citizen developer working in conjunction w/IT on our gov model for the PP. 
I want to do more than what is in the standard COE Power BI reports. Can you point me in the right direction rather than me guessing.
What **DV tables do I need** to answer these questions:
(I'll build the report in Power BI with whatever filtering I need)
I need to know specifically who is using a certain connector - that can be done in the COE but that's the easy question. 
I then want to know what solutions / apps / flows are using the on-prem gateway?
I then want to know what specific connectors are being with the on-prem gateway?
I would like to know who is using premium connectors?
I assume the answers will be found in a couple of tables. Which ones ... 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

March 2024

### What app or flow are you having the issue with?

n/a

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2640

**Comment by Jenefer-Monroe** [comment]
Hello. It sounds like you would benefit from coming to our office hours which are held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
We talk about new features and answer questions. Hope to see you there! 
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/OfficeHours/OFFICEHOURS.md

### On-Prem
Unfortunately we don't have any information tracking on-prem gateways. 

### Connectors / Connections
For the question of who is using what connectors, we have a table called **_Connection Reference Identity_** which tracks what I think you are looking for there. 
So it will tell you if Adele has an O365 Users connection in Default envt for example. And then in upcoming April release this is exposed in the Manage Permissions apps so that you casn see the individual connections within that. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f4ba55df-7625-4105-b7ed-59679702950d)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/564f8cd0-35a6-4303-a307-7971440a77fa)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
