### ISSUE TITLE
What security roles are need for a user to run the Developer Compliance Center app?

### ISSUE THREAD

**Issue by MshulerIWT** [microsoft/coe-starter-kit#7920]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

What security roles are need for a user to run the Developer Compliance Center app?
The user currently has the "Power Platform Maker SR" role, and is getting this when they try to run the app, "An error has occurred: You cannot complete this operation because you are missing "prvReadSolution" privileges."

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

January 2024

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

None

AB#2647

**Comment by Jenefer-Monroe** [comment]
That is the correct SR. Can you please validate that you've shared the MDA with that SR? The below uses a different app and SR to showcase but the system is the same.

### How to share a MDA
In order to share a MDA with users you first need to share the app as a whole with the desired security roles
Share the app as a whole with the Security Role
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3d532a9-92f5-4765-aeef-a9e171f19a46)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5377d117-c406-4293-bd3b-1c966f1569a8)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c9d7d6a-5e3e-4dab-b8d9-9749fcadaa15)
Now that SR can be applied to users you share the app with.
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f8976c2-b594-43da-b56c-fa4932fd7400)

**Comment by MshulerIWT** [comment]
Hi Jenefer,

Thank you for the reply.
I have confirmed these settings are in place with the role "Power Platform Maker SR".

But the user is still getting "An error has occurred: You cannot complete this operation because you are missing "prvReadSolution" privileges"

**Comment by Jenefer-Monroe** [comment]
Looks like we missed this permission on the SR. Strange as I can open it in my tenant but not see the data. 
This is fixed for April release. You can local fix if you'd like:

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/15fb1714-9384-44fe-9f3c-139e62433107)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f668d3e6-6633-4e8f-b03c-7e624064fce3)

**Comment by Jenefer-Monroe** [comment]
Thanks for posting!

**Comment by MshulerIWT** [comment]
Thats great, thank you Jenefer!
😊
