### ISSUE TITLE
[CoE Starter Kit - QUESTION] Descriptions  App

### ISSUE THREAD

**Issue by Fadel1949** [microsoft/coe-starter-kit#7923]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, I have a question and can't find an explanation in the Document. Can you explain these apps? What is it and what does it do?

1. Admin - Access this App
2. Admin - Access this Flow
3. CoE Admin Environment Request (Preview)
4. CoE Maker Command Center
5. CoE Setup and Upgrade Wizard
6. DLP Impact Analysis
7. Manage Permission 
8. Setup Wizard - ARM Features
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/701c933f-edd6-45c9-bf0f-26f932f37551)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2650

**Comment by Jenefer-Monroe** [comment]
Hello. We are a very small team and struggle to keep the documentation up to date. You may be best served just booting these objects and getting to know them. But here are a few things to get you started.

These two are for updating permissions directly from the PBI reports: [Configure the Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard)
Admin - Access this App
Admin - Access this Flow

Here's an overview of these: [Environment and DLP Policy management](https://learn.microsoft.com/power-platform/guidance/coe/env-mgmt)
CoE Admin Environment Request (Preview)
CoE Maker Command Center

You should use this every upgrade. It walks you through the steps to ensure all flows/env vars/etc are setup correctly.
CoE Setup and Upgrade Wizard

Same but for Audit logs. Had to be separate due to connector availability in some Gov clouds.
Setup Wizard - ARM Features

For finding if changes to DLP will impact canvas apps and cloud flows in your tenant.
DLP Impact Analysis

New app for managing things like connection references, security roles, and app/flow permissions. 
Manage Permission

**Comment by Fadel1949** [comment]
@Jenefer-Monroe    Thank you very much.
Do you happen to have a manual for each app? How to use each app, and how to get started?"

**Comment by Jenefer-Monroe** [comment]
Unfortunately no, we just are not able to staff up such documentation. 

Please take a look, try out the apps, and then if you have specific questions you can return here with them, or you can show up to our office hours where we answer questions like these from the community.

### Office hours
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)

**Comment by girishuppal** [comment]
Hello @Fadel1949 - Please find the community videos for centre of excellence starter kit here https://www.youtube.com/playlist?list=PL5xdZrvu1OhXfL52jgQEObfb6Lqx2CzNq

**Comment by Fadel1949** [comment]
Thank you very much!

**Comment by Fadel1949** [comment]
@Jenefer-Monroe  

Can you please explain this app? Please help me, I don't understand what this is for. I opened it and there is only one security role.

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/a912bb60-ec03-4aca-96a9-51265817c6b7)

I don't understand the next page either. What track is it and what is it used for?
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/bc34edc9-1023-49a1-a3ce-1084a450f169)

**Comment by Jenefer-Monroe** [comment]
Please run this flow and you will see the other SR's to select: Admin | Gather Tenant SRs
We added a link to this when it hasnt yet populated for April so people wont see a blank page there going forward:  https://github.com/microsoft/coe-starter-kit/issues/7862

**Comment by Fadel1949** [comment]
OK, now the information in Configure SRs is here. Do you have an explanation for this page? What does it do?
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/94e6475c-b247-40bf-a546-9b2541ea13cc)
But for the Manage SRs page, there is still nothing to show.
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/75cf6675-9593-4ee6-b66b-986aa7e316ae)



![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/b263330f-dba4-4386-a4b8-8bd61bdf3c68)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
