### ISSUE TITLE
[CoE Starter Kit - QUESTION]  We are planning to use BYOD for COE but noticed that the App/Flow usage files generated in Azure show very less data

### ISSUE THREAD

**Issue by goroy1** [microsoft/coe-starter-kit#7939]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are planning to use BYOD for COE but noticed that the App/Flow usage files generated in Azure show very less data, as low as 3 Bytes, is this a known issue with the data collection ? has anyone faced issues where the Azure Blob storage shows no data for a day? 
![image](https://github.com/microsoft/coe-starter-kit/assets/125452130/bd0fc7d9-44b4-43a5-8f1a-71657c101ade)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2670

**Comment by Jenefer-Monroe** [comment]
I have not heard of this particular issue with the preview feature, no. But thanks for sharing here so I and others can be aware. 

I'm afraid you'll need to [contact product support](https://docs.microsoft.com/en-us/power-platform/admin/support-overview) with this information so that they can iterate on it to resolve.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
