### ISSUE TITLE
Cleanup Old Objects Apps - PowerApps License

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#7952]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello CoE Team,

Maker has a PowerApps License and able to launch the "Cleanup Old Objects Apps". if the manager needs to check it, does he/she need to license it as well to launch this apps?
![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/8ddc6579-834e-4b54-b4f2-44dde09c93c8)

### Expected Behavior

Managers who have no power apps license should be able to launch and send email reminders.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Cleanup Old Objects Apps

### What method are you using to get inventory and telemetry?

None

### Anything else?

N/A

**Comment by Jenefer-Monroe** [comment]
Hello. Yes the app itself requires premium license in order to view and use as it relies on the Dataverse connector. Please see [About licensing and license management](https://learn.microsoft.com/power-platform/admin/wp-license-management) which explains the ways in which connectors impact license requirements.

**Comment by RyanCloud8888** [comment]
Thank you Jenefer as always.

**Comment by Jenefer-Monroe** [comment]
Happy to help!
