### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to provide value for Environment Variable "admin_CoESystemUserID"

### ISSUE THREAD

**Issue by julakantisaiabhinav** [microsoft/coe-starter-kit#7976]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have seen in the backlog there is similar bug while upgrading the COE Starter kit, but I am on the Initial Setup using manual setup using cloud flows instead of Data Export. So Please help me in providing the value for above Environment Variable. There is a flow named "SYNC HELPER - Apps" is _not turning on_ throwing the following error
"Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_CoESystemUserID'."}}"."

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2722

**Comment by RahulBojji** [comment]
@julakantisaiabhinav 

I think the issue is that you do not have the environment variable filled for SYSTEM user. Its highly recommended that you use the CoE Setup and Upgrade Wizard to install or upgrade the kit. It allows you to not worry about the order of turning flows on / new environment variables etc.

![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/fcf4b678-b437-43bf-8dc4-e1f610865f37)

In this case this env variable is used to identify who the SYSTEM user is in the envt.
Can you confirm, did you use the setup wizard?

**Comment by julakantisaiabhinav** [comment]
I am not using the Setup Wizard because I am doing initial setup using Manual setup method instead of Data Export method.

**Comment by Jenefer-Monroe** [comment]
The setup wizard works for both Data Export and Cloud Flow architectures. 
It's highly recommended that you use the Setup Wizard as, due to the very small size of our team, the documentation has drifted pretty out of date. 
Please launch the setup wizard, it will setup this env var for you and turn on the correct flows.

**Comment by julakantisaiabhinav** [comment]
Thank you @Jenefer-Monroe , as per your recommendation went ahead and ran the setup wizard app, it helped me alot in setting up things. I would highly recommend to use this app after every component solution import. This helps in minimizing of manual work. I would request you to provide documentation as early as possible on this in utilizing it.
