### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Center access 

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#7980]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello team, 

For the COE Compliance Center, when the email notification is sent to Makers who need to provide details on their app for compliance purposes, they can't seem to access it.
I tried searching for an answer to this, I found some bit here and there in our forum but I would like to clarify. 

**Error when they try to access.**
            
![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/858e7500-1f5e-4cc9-b501-5672e0bb9e94)

1. Do They need a premium license to access ?
2. I shared "*Developer Compliance Center*" (Free Power Automate License) to the "System Administrator" role by sharing this app only - can he access the apps, access other modules, and change our CoE production setting and variable, correct?
3.  I see someone in our forum suggested to have "Nurture Component" help.  I currently do not have a "Nurture Component" in our production.  Should I install it?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Development Compliant Center

### What method are you using to get inventory and telemetry?

None

AB#2727

**Comment by Jenefer-Monroe** [comment]
Hello. 

### Do They need a premium license to access ?
Yes as the app uses Dataverse which is a premium connector, users will need a premium license to access. 

### I see someone in our forum suggested to have "Nurture Component" help. I currently do not have a "Nurture Component" in our production. Should I install it?
No that should not be related

### I shared "Developer Compliance Center" (Free Power Automate License) to the "System Administrator" role by sharing this app only - can he access the apps, access other modules, and change our CoE production setting and variable, correct?
The System Administrator role is like the Database Administrator role for SQL. So they can do anything they want to the environment. We created lesser custom security roles you can use. 
For your makers you would want to grant them the Power Platform Maker SR which we ship with Core. 
Then you will want to share the app with that SR. I've pasted below how to do that. Note the screenshots are for the Nurture SR but its the same idea for the one in Core

**_How to share a MDA_**
In order to share a MDA with users you first need to share the app as a whole with the desired security roles
Share the app as a whole with the Security Role
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3d532a9-92f5-4765-aeef-a9e171f19a46)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5377d117-c406-4293-bd3b-1c966f1569a8)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c9d7d6a-5e3e-4dab-b8d9-9749fcadaa15)
Now that SR can be applied to users you share the app with.
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f8976c2-b594-43da-b56c-fa4932fd7400)

**Comment by RyanCloud8888** [comment]
Thanks Jenefer.
so, "Clean Up Apps" share the same way - should do it too then?

**Comment by RyanCloud8888** [comment]
Thanks Jenefer.

**Comment by RyanCloud8888** [comment]
Thanks Jenefer. 
I added user then user access - no problem, it works as intended but when I add user to a M365 group, then add that group and share the same way, it's not working.  Is there anyway that we can add all makers?

**Comment by RyanCloud8888** [comment]
Thanks Jenefer.
