### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by JanParnahaj** [microsoft/coe-starter-kit#8005]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I am getting the following error when trying to upgrade/import CenterofExcellenceCoreComponents version 4.29.

Solution manifest import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade exists. Cannot update solution.

The current version is 4.24, installed a few weeks ago (upgraded from v4.23).
I suspect something might have gone wrong with the last installation, as version 4.23 is still available under solutions, and it wasn't uninstalled.

I tried both the Update and Upgrade options but got the same error.

Is there some config setting that would allow the upgrade to proceed?

Thanks,
Jan

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

None

AB#2782

**Comment by Jenefer-Monroe** [comment]
Hello. When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 
These will never converge or repair on their own, you will need to take action to resolve as a result. And until you do, you are in an unknown state.
If you go to history you may find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)
And if you don’t, then you should delete the _upgrade. And try to upgrade again to see either if it succeeds this time, or if you see the error message this time.

If you share a screenshot like this so we can see what solutions you have installed in this environment, I might be able to help with what the issue is.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by JanParnahaj** [comment]
Thanks for the prompt response, I do see the _Upgrade version after expanding the column width.

I will delete it and try to re-import and will provide the update ..

***@***.***

Thanks,
Jan

**Comment by JanParnahaj** [comment]
Providing update in order to close the loop.

After deleting the "_Upgrade", I was able to successfully install version 4.29.

Thanks again

From: Jan Parnahaj
Sent: April 5, 2024 5:06 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] QUESTION (Issue #8005)

Thanks for the prompt response, I do see the _Upgrade version after expanding the column width.

I will delete it and try to re-import and will provide the update ..

***@***.***

Thanks,
Jan

**Comment by Jenefer-Monroe** [comment]
thank you for letting me know!
