### ISSUE TITLE
[CoE Starter Kit - QUESTION]  Betwork error when using patch function and Run Setup Flows not running

### ISSUE THREAD

**Issue by omalss** [microsoft/coe-starter-kit#8019]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I installed the CoE solution (new intall), configured connectors etc and started the CoE Srtup and upgrade wizard.

I received a few errors in the first few steps of the setup wizard.

"SetupWizard>GetTenantID.Run failed: {"error":"Code":"0x80048d0b","Message":"Failed to install the flow"}} (I was able to tur this flow on and run it successfully and the error went away when I went through the wizard again)

"Network error when using Patch function: The requested operation is invalid" (This error appears when loading "Configure inventory data source")

I chose Cloud Flows and then "Run Setup Flows" does nothing. It doesn't show any data after clicking refresh and doesn't allow me to move to the next stage. 
Admin | Sync Template v3 Configure Emails is turned on but hasn't run
Admin | Sync Template v3 (Connectors) is turned on but hasn't run.
"Setup Wizard" Flows:  getuserdetails, getcurrentenvironment, creategroup are turned on. Getcurrentenvironment has ran, the rest have not.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Multiple

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2846

**Comment by Jenefer-Monroe** [comment]
We had another person just hit this, and it was some intermittent issue. Please do the following:

### Flows turned on
In the CoE Envt, go to the Core solution > Flows. See approximately how many flows are turned on. 
Then in particular validate that the Admin | Sync Template v3 CoE Solution Metadata is turned on
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/093039e7-7569-42c1-838f-47529657a8d1)

### Flows returned from connector
1. Create a new flow and have it call the **_List Flows as Admin (V2)_** action. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/93bc9445-c00e-4c77-b3fd-00a33301480a)

2. Select your CoE Envt and set pagination so that it will return solution aware flows too

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/86baa740-c23a-4c34-bde4-c5f8ea3883fb)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1f42e2f9-0d8a-4d36-bd10-3efbd4c5b6d2)

3. Save and run the flow then see if the our target flow (Admin | Sync Template v3 CoE Solution Metadata ) is in the output.

### Process Table
Go to the system's Process table 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9b5b8c62-7c28-40ef-84e2-455d74de0c72)
And filter the Process Name to our target flow
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/feca070c-ad9e-418b-94b8-4abdc4e86c76)

**Comment by omalss** [comment]
Thanks - I had to update the tenant ID env variable, manually run the flow (Admin | Sync Template v3 CoE Solution Metadata ) and everthing seemed to fall into place then.
