### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Archive Scores

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#8022]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The highest score listed in the official Microsoft documentation may be exceeded under certain conditions, but is the highest archive score correct?
Also, is application isolation a situation where there is no co-owner?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2849

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern

Do you exceed the highest value listed here?
![image](https://github.com/microsoft/coe-starter-kit/assets/156406138/82adb148-8c15-4d82-a4f8-8c5cba4d275d)

Does the condition "Is the app orphaned" mean that there is no co-owner?

**Comment by Jenefer-Monroe** [comment]
Yes looks like that documentation just made a mistake there and counted the rows rather than summing the max values. 

We do not take co-owners into account in the kit today. So in order to not be counted as orphaned an app needs a new owner assigned.

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
Is it correct that the highest flow score is 10 and the highest app score is 12?

Do the flow conditions "Is the flow orphaned?" and "Does the flow have an owner?" add score if there is no owner?
![image](https://github.com/microsoft/coe-starter-kit/assets/156406138/f2f45feb-ce84-4cf7-8ed5-bde1fd967cbc)

**Comment by Jenefer-Monroe** [comment]
That is correct.

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
"2(Orphaned Apps)/0(Non-Orphaned Apps) with a score of 1. Is this a problem?


![MicrosoftTeams-image](https://github.com/microsoft/coe-starter-kit/assets/156406138/ce5463b0-317d-450a-9878-739ca257bd73)

**Comment by Jenefer-Monroe** [comment]
Its a relative scale so while its not "correct", I dont really think its a problem. 
We can explore making this feature nicer and I can put it on the backlog but due to competing priorities I dont expect to see it funded in the next few quarters. 
If you explore and find a solution and let me know we may be able to ship what you find.
Please let me know your thoughts.

**Comment by Jenefer-Monroe** [comment]
Hello we are not likely to make changes in this space due to competing priorities and its low usage, so you can assume that the numbers are a relative score. And while yes the 1 there should probably be a 2, all apps will behave this way. 
You should be fine to proceed and then we can put this on the backlog but we are unlikely to fund soon due to competing priorities

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
