### ISSUE TITLE
[CoE Starter Kit - BUG] Older version of Core Components not uninstalling after installing newer one (Part of Upgrade kit)

### ISSUE THREAD

**Issue by VenugopalDakoji** [microsoft/coe-starter-kit#8041]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I tried to upgrade my CoE starter kit. After installing the newer version of core components solution package, the older version was not uninstalling.

### Expected Behavior

CoE Starter kir was installed in a dedicated environment. We have seen an error that older version of Core Components not uninstalling after installing newer one (Part of Upgrade kit). We have reached out to Microsoft support, and they suggested us to reach out GitHub team. We are unsure, what was the exact root cause for this issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.30

### What app or flow are you having the issue with?

CoreComponentsSolution

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

<img width="903" alt="Starter kit issue" src="https://github.com/microsoft/coe-starter-kit/assets/166607688/7c080604-23bf-408c-a2bb-43a7b4586bf9">

AB#2873

**Comment by Jenefer-Monroe** [comment]
Hello, this is a known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018
We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 
You will need to follow the steps outlined in https://github.com/microsoft/coe-starter-kit/issues/6018 in order to proceed. 
In short:
1.	Delete _upgrade
2.	Delete Audit Logs solution and any other dependencies
3.	Try your upgrade of Core again
4.	Setup new Audit Logs collection technique
These are explained more deeply in the referenced bug.

**Comment by VenugopalDakoji** [comment]
Thanks for your quick response. Issue has been resolved. Now I have updated CoE starter kit with newer version.

**Comment by Jenefer-Monroe** [comment]
wonderful news! I'll go ahead and close then but please do return with new issues as needed in the future
