### ISSUE TITLE
[CoE Starter Kit - QUESTION] Questions after installing the CoE:

### ISSUE THREAD

**Issue by Fadel1949** [microsoft/coe-starter-kit#8055]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

1. Is there a feature that can delete apps that filter specifically for "No owner" all at once, many apps at once without having to delete each app individually?
2. What does "Flows Pending Suspension" mean in the Governance Dashboard?
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/5455f296-6590-4e49-adc5-4c53624bbe89)

3. What does "Action count" mean in the Flow Dashboard?
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/9d7f11b7-1e9e-4434-b1dd-859c5af2d515)

4. Is there an overview of the architecture of all flows, showing which flows are for pulling data from PowerApps daily, Flows daily?
5. Is there a description for flows, possibly grouped, such as these flows are for pulling various data?
6. ** How to maintain after installation?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2889

**Comment by Jenefer-Monroe** [comment]
Hello, in the future please post questions separately. It becomes very difficult to go back and forth with folks when there are multiple issues being addressed.

Also, please consider attending our monthly office hours. We talk about new features, upcoming changes, and spend most of the time answering your questions. 

More information:
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)

### What does "Flows Pending Suspension" mean in the Governance Dashboard?
Like most of the kit, this record is just exposing a product concept to you so that you know you have some action to take. The underlying feature of flows pending suspension is one from the product team. It basically means that some flow is no longer meeting the requirements to run, typically meaning at its license level. 
More can learn more about it here: [When premium flows are subject to license enforcement](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/when-flows-are-turned-off)

### What does "Action count" mean in the Flow Dashboard?
This is the number of actions in the flow, its filled by the following flow: **_Admin | Sync Template v3 (Flow Action Details)_**

### Is there an overview of the architecture of all flows, showing which flows are for pulling data from PowerApps daily, Flows daily?
There is not in any current, we are a very small team and are not able to keep documentation like that up to date very well. 
We do have this documentation but it is stale.
Note this one is for Core but you will find in this general documentation information about the other solutions as well. https://learn.microsoft.com/power-platform/guidance/coe/core-components#flows

### Is there a description for flows, possibly grouped, such as these flows are for pulling various data?
Same answer as above

### How to maintain after installation?
Please see [Updating the Center of Excellence (CoE) Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/after-setup)

**Comment by Fadel1949** [comment]
@Jenefer-Monroe 

Ok, thank you very much for your response.

Question 1: Do you have a method if we look at the Dashboard and see many apps without an Owner? If we want to delete all apps or select multiple apps to delete at once, can we do that in the CoE function?

**Comment by Jenefer-Monroe** [comment]
Q1 : Please see the new Manage Permission app, note this is new to the April 2024 release. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/941dc6aa-7724-4569-82aa-f843b66e3070)

Q7: Sorry I dont understand what you mean here by full.

**Comment by Fadel1949** [comment]
@Jenefer-Monroe 
Q7:I mean, after we have installed the CoE, there will continuously be data coming in the future. Is there a chance that it will become full, or will there be a flow for deleting old data that is no longer used? How do we maintain the data?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
