### ISSUE TITLE
RBAC on CoE Dashboard

### ISSUE THREAD

**Issue by JO20232425** [microsoft/coe-starter-kit#8068]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I need expert advice on how to provide role based access control (RBAC) to the system administrators on the CoE Starter kit dashboard for the Power Platform . How can we define Row Level Security on CoE Dashboard.
Requirement: The system admin of an environment should be able to see only their own environment data in CoE Dashboard. Has anyone implemented same? 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Dashboard

### What method are you using to get inventory and telemetry?

None

AB#2905

**Comment by Jenefer-Monroe** [comment]
We do not have a write up for this, and we can’t really offer it more than some starter links due to the size of our team and the per-tenant requirements and complexity of the features. 

Many customers are using Power BI row level security rules to achieve what you're after, rules are then set up based on values in the tables - e.g. Member Firm A sees Environments A/B/C etc.
https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls

Or you could implement it with the Row Level Security features of Dataverse using Modern Business Units. 
If you arent familiar with the Security Model features of Dataverse, its a bit of a learning curve but amazing once you get past that. 
Here are some starter links
https://learn.microsoft.com/power-platform/admin/wp-security-cds
https://learn.microsoft.com/power-platform/admin/control-user-access

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
