### ISSUE TITLE
[CoE Starter Kit - BUG] Core for Teams tables are not up to date with Core

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#807]
Dataverse PBI Dashboard is expecting a different schema than the Dataverse for Teams solution updated my Dataverse for Teams environment to have.
![image](https://user-images.githubusercontent.com/55705669/125066911-744a7c00-e0ab-11eb-94bb-de5cf5464e23.png)

- [x] We added new fields in Core tables (esp Environment) that have not yet been ported to Core for Teams
- [x] Those fields are not used in the Power BI Dashboard so could be removed from the schema which should make the dashboard then work

**Comment by manuelap-msft** [comment]
Done for August release!

**Comment by manuelap-msft** [comment]
This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
