### ISSUE TITLE
[CoE Starter Kit - BUG] Issue with the Admin | Audit Logs | Sync Audit Logs (V2) - Your flow is running too many actions

### ISSUE THREAD

**Issue by DataChopsticks** [microsoft/coe-starter-kit#8086]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We recently upgraded the COE Toolkit to Jan 2024 Release (Core Component Version 4.22) and from around that time we started getting this warning 

Your flow is running too many actions
Your flow has exceeded its Power Platform Requests (https://aka.ms/pa-ppr) limit in the past 24 hours. If this high usage persists, your flow actions may get throttled and slowed down. Power Platform Requests used: 213144, Power Platform Requests transition limit: 200000.

Flow name: **Admin | Audit Logs | Sync Audit Logs (V2)**

We have turned off this flow in our Dev and QA environments for now, but this flow is very important for us to continue using COE Toolkit in prod as we use the audit logs quite a bit.

Does anyone face the same issue or know anything about it?

Please let me know if you need any additional information.

Thanks
Sangeet

### Expected Behavior

The flow should be running fine without the warning of it using too many power platform request cycles.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2924

**Comment by Jenefer-Monroe** [comment]
Unfortunately we are not able to streamline this flow further that we have today. I believe it was the Feb release that we made the last known improvement but it was not a tremendous one. 
The nature of the workaround we have here just does not lend itself to large organizations. 
For large organizations unfortunately you will need to rely on the products native features for inventory. We are about to work into a new FC for this as they make a big schema change so until then Im afraid you will need to either live without this data or purchose a per-flow license for this one.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by JulesCam** [comment]
Hello, I appreciate this has been closed but I am facing the same behaviour and we will most likely seek to purchase a per-flow license for this flow, however, I wanted to check something. I have installed the COE for four of our partners who each have their own tenant. We are only seeing this for one partner and not the others. Is this due to the volume of Database and Log used within the partner Power Platform, i.e., the partner impacted has 822.10 GBs of Database data and 437.62 GBs of Log data, whereby the others are below 200 GB for Database and 100 GB for Log - is this a key contributor? Are there other contributors like the number of Makers, Users? Is it the number of flows and apps? Your clarification would be much appreciated.
