### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI: Overview - Apps, Automate, Bots Top 20 environment count is incorrect

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#810]
Top 20 Environments by App / Flow / Chatbot count is incorrect, and tied to the numberofapps calculated field on all three pages. This means the count a) always reflects highest number of apps (vs number of flows and chatbots) and b) is a day out of date based on calculated field.

**Comment by manuelap-msft** [comment]
Update to adjust the Top 20 count on the dashboard.

**Comment by manuelap-msft** [comment]
Hello,

fixed this issue and the new version of the Dashboard is now available either via the main download aka.ms/coestarterkitdownload or directly here: https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/CDSLegacy_CoEDashboard_202107_v2.pbit

Thank you
Manuela

**Comment by manuelap-msft** [comment]
This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
