### ISSUE TITLE
CoE Starter Kit - Missing "Center of Excellence Audit Logs" zip folder

### ISSUE THREAD

**Issue by llbeste** [microsoft/coe-starter-kit#8106]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This is a request for information. I'm trying to set up a PBi to analyze the data within the CoE starter kit. One issue I'm running into is around getting my usage data; right now it is blank. I need the "Center of Excellence Audit Logs" zip folder but can't seem to find it. Inside this folder there should be two cloud flows below: "[child] Admin I Sync Logs" & "Admin I Sync Audit Logs". Can you help me get this zip folder? 

### Expected Behavior

We expected that this folder would be included in the CoEStarterKit zip folder

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Center of Excellence Audit Logs

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

N/A

### Anything else?

This is a request for the zip folder Center of Excellence Audit Logs

AB#2944

**Comment by Jenefer-Monroe** [comment]
Hello, We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors.  

Our recommendation is to switch to the new HTTP methodology to gather however if you cannot we did capture the old custom connector for you to install and maintain on your own. 
Please see steps 4a (http) and 4b (captured cc) in the write up here: https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
