### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot Import Audit Component 1.70.20210708.1_managed

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#813]
### Describe the issue

Missing Dependency while importing. 
 solution.xml file shows all the missing dependency 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.70.20210708.1

### What app or flow are you having the issue with?

Solution Import

**Comment by manuelap-msft** [comment]
Hello,

we will need a bit more information here - can you share the error log of what dependency is missing? Did you upgrade Core to the latest version as well? Can you try performing an **Update** instead of an Upgrade on Import? (On Import, you will have to select "Advanced settings" and select Update).

Thank you
Manuela

**Comment by aakashpatel660** [comment]
it resolve the issue after installing core component
