### ISSUE TITLE
[CoE Starter Kit - Customized Emails] News Body Emails

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#8132]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello everyone, everything good?

I would like to ask you a question, I want to create a new email body, I am creating a customization when the environment exceeds the approved capacity, send a personalized email to the owner.

However, looking at what already exists, I saw that the message ID is not a variable, but a fixed value, is that right? How do you make it work between environments, I don't understand

can you help me?

![image](https://github.com/microsoft/coe-starter-kit/assets/94450591/8675dccf-699c-4179-998f-3da337d36b8a)

![image](https://github.com/microsoft/coe-starter-kit/assets/94450591/fd30fc9f-c360-4f19-80b1-a69528381599)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Capacity Alerts

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2972

**Comment by DominicMeznik** [comment]
Hi! 
The ID related to the E-Mail Id. It makes sense it´s fixed, since the Flows are sending specific E-mails only. 

You can actually add the ID field in the Admin Command Center like this:

![image](https://github.com/microsoft/coe-starter-kit/assets/109345362/2a5616c3-6ec6-42a8-959f-a0833e395678)


The value you see in the Flow is the "Based On" field from the E-Mail templates.

Hope this helps!

**Comment by ClaudioRWS** [comment]
@DominicMeznik 

Thanks for the help, I'll use this field!
