### ISSUE TITLE
[CoE Starter Kit - BUG] - Connection Status flow failing due to deleted apps

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#816]
### Describe the issue

![image](https://user-images.githubusercontent.com/62659043/125107014-8a514000-e09d-11eb-8aae-6726da33bb4b.png)

### Expected Behavior

Condition is delete eq false, but should be delete ne true as some data never got this set to false. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Connection Status)

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
