### ISSUE TITLE
[CoE Starter Kit - BUG] cannot remove dependencies with error code: 8004F01D

### ISSUE THREAD

**Issue by Jonson1501** [microsoft/coe-starter-kit#8165]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

We have been working with MS Support team under support ID request: 2404110030000299 and been advised to raise a ticket to Github team. 

Failed to upgrade COE Starter Kit from V4.11 to V4.29 with error Code: 8004F01D.

We want to uninstall V4.11 COE Solution. System asking to delete 3 of the dependencies, however we cannot remove dependencies to uninstall it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

AB#3042

**Comment by Jenefer-Monroe** [comment]
Hello. Can you please provide some more information :

1. The specific error message so we can know what objects are at issue.

1. Can you please share what build you were upgrade from and to? 

1. A screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Jonson1501** [comment]
++Kristen.

Hi Team,

Please find the following info:

  1.  The specific error message so we can know what objects are at issue.
     *   Please find attached error message
  2.  Can you please share what build you were upgrade from and to?
     *   We are trying to Upgrade from 4.11 to 4.29
  3.  A screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names

  *   ***@***.***


Regards,

***@***.***

Jonson Pan
Service Automation Analyst/Power Platform Center of Excellent, BOQ Group
BOQ | L5, 100 Skyring Terrace Newstead QLD
e: ***@***.******@***.***> | boq.com.au<http://www.boq.com.au/>

**Comment by Jenefer-Monroe** [comment]
Hello images do not come through when you respond in email, you need to log in to GitHub to share them. 
However the error message have pointed me to the issue. 

This is a known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018
We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 
You will need to follow the steps outlined in https://github.com/microsoft/coe-starter-kit/issues/6018 in order to proceed. 
In short:
1.	Delete _upgrade
2.	Delete Audit Logs solution and any other dependencies
3.	Try your upgrade of Core again
4.	Setup new Audit Logs collection technique
These are explained more deeply in the referenced bug.

**Comment by Jonson1501** [comment]
++Kristen


Regards,

***@***.***

Jonson Pan
Service Automation Analyst/Power Platform Center of Excellent, BOQ Group
BOQ | L5, 100 Skyring Terrace Newstead QLD
e: ***@***.******@***.***> | boq.com.au<http://www.boq.com.au/>

**Comment by Jonson1501** [comment]
Hi Jenefer,

Thanks for providing the fixing solution. I have now able to install the new COE solution.

Feel free close the ticket.

Cheers. 😊


Regards,

***@***.***

Jonson Pan
Service Automation Analyst/Power Platform Center of Excellent, BOQ Group
BOQ | L5, 100 Skyring Terrace Newstead QLD
e: ***@***.******@***.***> | boq.com.au<http://www.boq.com.au/>

**Comment by Jenefer-Monroe** [comment]
Thanks for letting me know!

**Comment by Jonson1501** [comment]
Hi Jenefer,

One additional question regarding to this solution guide.

Do we still need to re-install CenterofExcellenceAuditComponents solution back after the COE Core is installed successfully? The documentation did not mention this.

Cheers. 😊


Regards,

***@***.***

Jonson Pan
Service Automation Analyst/Power Platform Center of Excellent, BOQ Group
BOQ | L5, 100 Skyring Terrace Newstead QLD
e: ***@***.******@***.***> | boq.com.au<http://www.boq.com.au/>
