### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Connection Identities)

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8182]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '210550412' bytes. This exceeded the maximum size '209715200' bytes allowed.

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/457ebc87-a03a-498d-9217-df2898058985)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/4757b9c5-4708-49a6-8597-d605d0c09b04)

### Expected Behavior

it should work and paginate. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Sync Template v4 (Connection Identities)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3087

**Comment by Jenefer-Monroe** [comment]
The CoE kit is built on top of the product, and as such bound to platform limitations. 
This failure is due to a limitation on the amount of data connectors can bring back, which unfortunately, you have exceeded. 
Note also that deleting individual flows and apps will not delete the connections they use, so they do pile up over time and deleting objects does not 

We cannot fix that, nor can we safely create a script which will reliably connections safely for all tenants that will work over time. 

Here are some things you can do to address:
1. Manually use powershell to [explore](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) unused or errored connections. That technology does not have this same size limitation.
2. Contact [product support](https://learn.microsoft.com/power-platform/admin/get-help-support) to have them help you clean up old connections

Hope that helps, and sorry for the inconvenience.

**Comment by nasilvae** [comment]
> The CoE kit is built on top of the product, and as such bound to platform limitations. This failure is due to a limitation on the amount of data connectors can bring back, which unfortunately, you have exceeded. Note also that deleting individual flows and apps will not delete the connections they use, so they do pile up over time and deleting objects does not
> 
> We cannot fix that, nor can we safely create a script which will reliably connections safely for all tenants that will work over time.
> 
> Here are some things you can do to address:
> 
> 1. Manually use powershell to [explore](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) unused or errored connections. That technology does not have this same size limitation.
> 2. Contact [product support](https://learn.microsoft.com/power-platform/admin/get-help-support) to have them help you clean up old connections
> 
> Hope that helps, and sorry for the inconvenience.

I understand, I'm opening a ticket with PG if they can dig in further.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by nasilvae** [comment]
> closing out as no further action for starter kit team

Have we considered using the http connector since this has more flexibility with the pagination limits?
