### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Model Driven Apps) Failed

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#819]
### Describe the issue

Model-Driven Flow does not find the CRM organization with a unique name. 

![image](https://user-images.githubusercontent.com/59940632/125142247-497d1980-e0e5-11eb-91bc-ba2dd57a4d9e.png)

![image](https://user-images.githubusercontent.com/59940632/125142197-2a7e8780-e0e5-11eb-93d1-dadf2d59d6fe.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Model Driven Apps)

**Comment by JeneferM-MSFT** [comment]
We have seen this error repro intermittently. 
Ask 1 is to please just see if this repros again on rerun. 

If so, please look at the trigger for this flow and scroll down under Outputs to 
 "admin_displayname": "Github-ABC",
  "admin_environmentcdsinstanceurl": "https://githubabcxysyasdf.dynamics.com/"

![image](https://user-images.githubusercontent.com/55705669/110352967-6e298d80-802e-11eb-918b-f02cc5831a35.png)

And then can you
1. Go to the Environment URL and see if that exists?
2. Go to PPAC > Environments and see if you can find the Environment Name there? If you can find it there, can you check if the Instance URL there matches what's in the CoE starter kit (with .crm4.dynamics.com) at the end.
3. Go to https://admin.powerplatform.microsoft.com/environments/deleted to see if the environment is listed here under Deleted environments

**Comment by aakashpatel660** [comment]
Hi @JeneferM-MSFT 

I found that environment and is a trial environment and this environment is created by System. The environment is in the inactive stage. I have deleted that environment.

**Comment by JeneferM-MSFT** [comment]
thank you for these details!

**Comment by VansNogueira** [comment]
Hello guys,

Was this flow failing cause the environment was a trial? Asking this because I'm having the same issue and it happens to different types of environments (production/sandbox/default) and I compared the values of the display name and URL (from Outputs) with the environments and they all seem the same and the user running the flow is a power platform admin, has all the permissions but even though the flow is failing. I assume it's a problem with the legacy action/connection?

Any help appreciated.

![image](https://user-images.githubusercontent.com/49518442/134938629-dcee60da-590b-455a-8e59-2427fc713d0b.png)
