### ISSUE TITLE
[CoE Starter Kit - BUG] Issue when updating with March update and beyond (8004F01F)

### ISSUE THREAD

**Issue by Descent098** [microsoft/coe-starter-kit#8190]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am currently updating our CoE from the February release to March/April, in both cases I am getting the same error code: `8004F01F`

All other solutions are updated to latest, it's just the core solution that's having an issue. The error message reads that there is an uninstall failure with the workflow:

```
Workflow uninstall: FAILURE, workflow id <REMOVED ID> category ModernFlow name CLEANUP HELPER - Check Deleted (Solutions)
```

### Expected Behavior

Be able to update to the latest release

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Solutions)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Login to our CoE production environment as an admin
2. Attempt to import the latest core components solution
3. **Get error after it tries to import the solution**

### Anything else?

I checked through and found what appears to be a potentially related issue (#8165 ), the resolution from that ticket ( #6018 ) however is not possible because I don't see a `_upgrade` solution.

The only other potentially relevant information is that we do not use the nurture components, so I'm unsure if they are required going forward for the core components to work

AB#3095

**Comment by Jenefer-Monroe** [comment]
Hello, this flow was deleted and the product's upgrade code is failing to recognize this and delete the flow. 
This is being tracked with https://github.com/microsoft/coe-starter-kit/issues/8130
Someone is contacting product support. Hopefully we can get this resolved. 
Update does work in the meantime as a workaround, as it does not delete removed components. 

Please follow along on https://github.com/microsoft/coe-starter-kit/issues/8130 so that we can keep all our notes in one place.
I;ll go ahead and close as a dupe.
