### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flows) Failed

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#820]
### Describe the issue

Flow get failed because flow does not exist. My question is that if the flow does not exist then why is it looking for that flow? Where is it getting that data, if the data does not exist in the Flow table?

  "error": {
    "code": "0x80040217",
    "message": "admin_flow With Id = 0ea49d00-5553-4933-9b19-c6d4dd6852f3 Does Not Exist",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_flow With Id = 0ea49d00-5553-4933-9b19-c6d4dd6852f3 Does Not Exist"

![Screenshot 2021-07-09 184719](https://user-images.githubusercontent.com/59940632/125142600-1edf9080-e0e6-11eb-9cec-61b3f65aa3b6.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by JeneferM-MSFT** [comment]
I believe you have hit a known product bug around caching of deleted flows. You will need to contact support to have them clean this up in order to have this flow start passing.  

Our recommendation is to first get a repro outside of the toolkit before contacting support. You can use the below flow to get this repro.  

To use: Import the flow, open, select the environment which repros for you.  
It loops the flows, will hit the same failure and the you can go to support with this flow instead of the toolkit, for faster iteration to fix. 
[ProductBugDemo-getflowaftergetflowsfails_20210702144440.zip](https://github.com/microsoft/coe-starter-kit/files/6755313/ProductBugDemo-getflowaftergetflowsfails_20210702144440.zip) 
![image](https://user-images.githubusercontent.com/62659043/124291999-64162800-db12-11eb-92a6-55b4ffe1ecee.png)

**Comment by aakashpatel660** [comment]
Hi @JeneferM-MSFT 

I did get an error but it is for a different flow, not the same flow. 

![image](https://user-images.githubusercontent.com/59940632/125148865-43963100-e103-11eb-852c-4128989c9408.png)

**Comment by JeneferM-MSFT** [comment]
is this the same issue as #818 and this failure was caught? please share a picture of the failure in a larger context.

**Comment by aakashpatel660** [comment]
![image](https://user-images.githubusercontent.com/59940632/125284821-f0310800-e2e7-11eb-8402-dc0309ee68cd.png)

![image](https://user-images.githubusercontent.com/59940632/125285031-30908600-e2e8-11eb-8d2d-9f20c50c6c7e.png)

Error message on the Get New Flow as Admin. 

"statusCode": 404,
"body": {
"error": {
"code": "XrmWorkflowNotFound",
"message": "The XRM workflow table row could not be found."

**Comment by JeneferM-MSFT** [comment]
I have validated that this call works for new flows in default (see below). So I dont know what is wrong for you. Did you validate
1) that it still fails when you rerun it? 
1) that you have all the pre-reqs needed per [our documentation](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites)?
In particular, do you have the Power Platform Admin role? 
Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf) 


![image](https://user-images.githubusercontent.com/62659043/125322834-68ed8f80-e2fb-11eb-802b-245884f161ea.png)

**Comment by aakashpatel660** [comment]
Hi @JeneferM-MSFT 

Yes, it still fails. 
All of the prereqs have been completed. 
I do have an admin role.

**Comment by JeneferM-MSFT** [comment]
Please go see if that flow exists using admin tooling like the admin UX and powershell.

**Comment by aakashpatel660** [comment]
Hi @JeneferM-MSFT 

I got a 404 error.

![image](https://user-images.githubusercontent.com/59940632/125517951-ba112e32-ba08-4b36-a875-2d9b6bf12c50.png)

**Comment by JeneferM-MSFT** [comment]
Yes it looks like the app doesnt exist and we are back to the original suggestion. 
Re-pasting here for ease of access
Thanks for using CoE 


I believe you have hit a known product bug around caching of deleted flows. You will need to contact support to have them clean this up in order to have this flow start passing.  

Our recommendation is to first get a repro outside of the toolkit before contacting support. You can use the below flow to get this repro.  

To use: Import the flow, open, select the environment which repros for you.  
It loops the flows, will hit the same failure and the you can go to support with this flow instead of the toolkit, for faster iteration to fix. 
[ProductBugDemo-getflowaftergetflowsfails_20210702144440.zip](https://github.com/microsoft/coe-starter-kit/files/6755313/ProductBugDemo-getflowaftergetflowsfails_20210702144440.zip) 
![image](https://user-images.githubusercontent.com/62659043/124291999-64162800-db12-11eb-92a6-55b4ffe1ecee.png)
