### ISSUE TITLE
[CoE Starter Kit - BUG] Flows use/ run everyday still get mark as old object to clean up

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#8201]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Why do flows used/ run every day _(these flows do not need to be modified because it is running fine and does not make any modifications)_ still get marked as old objects to clean up?  Is there anywhere that we can check and adjust that? how can we avoid the annoyance to users?  Users can't go to every single flow to save it again, some of them have 100s and they are not happy about it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CLEANUP - Admin

### What method are you using to get inventory and telemetry?

None

**Comment by RyanCloud8888** [comment]
Thanks Jenefer, if I want to stop flow trigger, and only for Apps. 

How can I do that just for apps Only?

**Comment by Jenefer-Monroe** [comment]
Sorry I should have specified. 

In the Governance Components cloud flows you will see these two flows
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9fa96c3e-803c-4774-9209-3ff26072362e)

Turn off **_Admin | Inactivity notifications v2 (Start Approval for Flows)_**
And leave **_Admin | Inactivity notifications v2 (Start Approval for Apps)_** turned on. 

This way you will only run the systems for canvas apps.

**Comment by RyanCloud8888** [comment]
Thank you, Jenefer.

**Comment by dbraben** [comment]
I hope it's okay to branch off a "little" bit from Ryan's discussion, but I have a question related to the "Admin | Inactivity notifications v2 (Start Approval for Flows)" and "Admin | Inactivity notifications v2 (Start Approval for Apps)" flows within the Center of Excellence (CoE). How can I remove the "Use this app: Clean Upp App" link from the notification emails? I've explored all the customisable email options in the CoE Admin Command Center but haven't found where this link is included. I suspect it might be embedded via a Helper flow using an Environment variable for the URL? Since my users do not have PowerApp Licences, I'd like to modify this to use only the workflows. Any guidance would be greatly appreciated!
