### ISSUE TITLE
[CoE Starter Kit - BUG] Failed to upgrade to CenterofExcellenceCoreComponents_4.31_managed solution - Workflow uninstall CLEANUP HELPER - Check Deleted

### ISSUE THREAD

**Issue by hbazerbashi** [microsoft/coe-starter-kit#8250]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I'm starting to upgrade our CoE environments from version 4.23 to 4.31. As I'm starting with Dev, we're getting the following error that I see in the Solution history:
Workflow uninstall: FAILURE, workflow id 04b5f2be-08f7-ec11-bb3d-000d3a10bc1d category ModernFlow name CLEANUP HELPER - Check Deleted (Solutions)
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/45d53b53-1b89-4fb9-952e-7935d1648c5f)

I checked the Flow in the command center, and I don't see any extra layers to delete
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/ea889782-ba3a-4377-9d14-8457f4879ff4)

How can I resolve this?

Thanks,
Hasan.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3220

**Comment by Jenefer-Monroe** [comment]
Hello. Please see https://github.com/microsoft/coe-starter-kit/issues/8130

There is a product bug around deleting a parent and child flow at the same time which is hitting some envts. 
This is due to us cleaning up all the old v3 inventory flows. 

A workaround has been tested and is described here: https://github.com/microsoft/coe-starter-kit/issues/8130#issuecomment-2101226902

Will go ahead and close out as a dupe so that all communication is in that one tracking issue.
