### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE Title: Core component upgrade failing

### ISSUE THREAD

**Issue by a8kw** [microsoft/coe-starter-kit#8253]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Solution manifest import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade already exists. 4.22 is already there. Trying 4.29.

There is another older version 4.11 where "Apply Upgrade" is failing and also unable to delete it as there is a dpeendency on Custom Connector. Need help here.

### Expected Behavior

Successful upgrade from core solution 4.22 to 4.29

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Importing the solution

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In the environment, Import solution, select "Upgrade"

AB#3224

**Comment by Jenefer-Monroe** [comment]
When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 

These will never converge or repair on their own, you will need to take action to resolve as a result. And until you do, you are in an unknown state.

If you go to history you may find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)

And if you don’t, then you should delete the _upgrade. And try to upgrade again to see either if it succeeds this time, or if you see the error message this time.

For your case it is likely that your failure was due to this known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018

We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 

You will need to follow the steps outlined in https://github.com/microsoft/coe-starter-kit/issues/6018 in order to proceed. 
In short:
1.	Delete _upgrade
2.	Delete Audit Logs solution and any other dependencies
3.	Try your upgrade of Core again
4.	Setup new Audit Logs collection technique

These are explained more deeply in the referenced bug.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
