### ISSUE TITLE
[CoE Starter Kit - BUG] Wrong file shipped for Maker Assessment Starter Data

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#826]
### Describe the issue

After creating a connection it throws the below error message.

![image](https://user-images.githubusercontent.com/59940632/125300025-a7814b00-e2f7-11eb-9756-dbff8b1bbdea.png)

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

1.60.20210708.1

### What app or flow are you having the issue with?

Maker Assessment Starter Dataflow

**Comment by JeneferM-MSFT** [comment]
Did you see this error as called out in the instructions? And if so did you run it again as suggested? The alternate keys sometimes take a while to propagate and so it fails the first itme. 
![image](https://user-images.githubusercontent.com/62659043/125323379-f335f380-e2fb-11eb-8896-05ed96836c50.png)

**Comment by aakashpatel660** [comment]
Hi @JeneferM-MSFT 

I did do the refresh and still does not work. getting the same error message.

**Comment by JeneferM-MSFT** [comment]
can you show the excel workbook you used for the data in SP?

**Comment by aakashpatel660** [comment]
I am not sure if I understand your question correctly. 
Below is the screenshot of the Advance Editor for Power Query

Assessment Categories table
![image](https://user-images.githubusercontent.com/59940632/125516961-fc7e0202-23f7-4ccb-88a7-00fe1ca98eff.png)

Assessments Table
![image](https://user-images.githubusercontent.com/59940632/125516990-56050495-b9a9-4f3d-8531-ff7a29b6e1d2.png)

Answer Option table
![image](https://user-images.githubusercontent.com/59940632/125517115-72c77d01-83d5-4a25-8c96-5676db8a7263.png)

**Comment by JeneferM-MSFT** [comment]
It looks like you changed the formulas to point to 3 different files. And that is probably because the new single file didn't get put into the delivery folder. 

Here is the file with the data, we switched to a single file this time for technical reasons. And this is the one you should upload into SP and use.
[MakerAssessmentStarterData.xlsx](https://github.com/microsoft/coe-starter-kit/files/6811991/MakerAssessmentStarterData.xlsx)

We'll hold this bug to see what tooling in the background grabbed the wrong file.

**Comment by manuelap-msft** [comment]
We updated the release today! Thank you for letting us know!
