### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflow errors in the Latest Release (April)

### ISSUE THREAD

**Issue by abhijkumar-msft** [microsoft/coe-starter-kit#8267]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team,

We're seeing the following data flow errors occur after having the client upgrade to the latest release of the CoE Starter Kit:

**Flows Data Flow:**
![image](https://github.com/microsoft/coe-starter-kit/assets/146243200/c6140143-3c1b-443e-882b-de80ed1dad16)

**Makers Data Flow:**
![image](https://github.com/microsoft/coe-starter-kit/assets/146243200/f997c7d1-d624-41ad-82e0-d906ca43cd57)

**Latest Errors:**
![image](https://github.com/microsoft/coe-starter-kit/assets/146243200/1f6191c6-d172-49ee-abfd-0799e89f9461)

**Quick FAQ / Debugging Steps:**
The "next refresh" is only set for makers. _Yes; verified with the client that the "next refresh" is set only for Makers._
What information is given about the failures for flow. _The detailed errors are provided in the initial snapshots in the ticket description (Flows Data Flow and Makers Data Flow).

### Expected Behavior

The data flows should run as expected and not error out randomly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April Release

### What app or flow are you having the issue with?

Sync Data Flows

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Install the latest version of the CoE Starter Kit and allow it to run during it's pre-scheduled times.

AB#3239

**Comment by Jenefer-Monroe** [comment]
Hello. The flow one failed because the Maker one failed and it cannot find Makers that were to be inserted by it. 
So you will need to back up and delete refresh history to before these failures once resolved.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b2263ccc-4416-447e-9514-9e24e6ebe5cf)

It sounds like the dataflow could not access the AAD table. 
This could be because they missed a spot they needed to create a connection, or it could be something wrong with your environment. 
Please open the Maker dataflow and click each query, waiting for it to resolve all the way to the bottom, to see where the failure occurs.
For example click Makers, then wait till it resolves all the way to the last action (change)
Then click App Makers and wait, etc
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f5f13d82-07a8-42cf-995f-aa3169d0cd2c)

**Comment by abhijkumar-msft** [comment]
Thanks @Jenefer-Monroe ! I've relayed your items back to the client for further troubleshooting. I'll post their outcomes here, along with any additional items that may need our attention. Cheers!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
