### ISSUE TITLE
[CoE Starter Kit - [CoE Starter Kit - Need help to update the COE kit in power platform

### ISSUE THREAD

**Issue by akhileshmishraadmin** [microsoft/coe-starter-kit#8286]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

 Need help to update the COE kit in power platform

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2023

### What method are you using to get inventory and telemetry?

None

AB#3260

**Comment by Jenefer-Monroe** [comment]
Hello Sorry we are unable to have calls with our GitHub users. If you can please let us know specific questions we are happy to assist. 

Or if you can please tell me, what version of Core do you have now? 
You can also share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by akhileshmishraadmin** [comment]
Hi Jenefer,Thank you for your response, can you please confirm are these detail only visible to user who created this solution as for me its not visible

**Comment by Jenefer-Monroe** [comment]
What do you see when you go here? No solutions at all? 

Solutions should be visible to you if you are a system customizer or system admin in the environment I believe. 
If you are going to be doing the upgrades and management its suggested you be a System Admin in the envt.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
