### ISSUE TITLE
[CoE Starter Kit - BUG]  Admin | Sync Template v4 (Security Roles) - User Not Found error

### ISSUE THREAD

**Issue by julian0723** [microsoft/coe-starter-kit#8294]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow is failing, when the user is found deleted in Entra ID.

The action "Users Modified Name" is throwing an error

![image](https://github.com/microsoft/coe-starter-kit/assets/54391303/d4281eb8-423c-4f59-95fa-a6677156b351)

### Expected Behavior

The flow should still continue even though the deleted user is not found.

Expected no error received from the COE notification flow failure.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Security Roles)

### What method are you using to get inventory and telemetry?

None

AB#3267

**Comment by Jenefer-Monroe** [comment]
The failure to find in Entra is expected and caught. It looks like there is something wrong with teh expression here. 

What is returned in the call above that? For Users Name
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6d8a9b37-23be-4a68-87d6-648e7089ac14)

**Comment by julian0723** [comment]
The "Users Name" variable is empty, Click to Download -> shows empty.

![image](https://github.com/microsoft/coe-starter-kit/assets/54391303/c9907099-ab11-4286-9667-21fc4802e934)

The one above it "Find this unknown users name" -> Also shows as empty.

![image](https://github.com/microsoft/coe-starter-kit/assets/54391303/02f0ec46-dc88-44bc-a2f3-877e85561709)

I think, the "Configure Run After" -> Failure must also be set for the variables

**Comment by Jenefer-Monroe** [comment]
Names are required for processing so we don't want to catch and ignore this failures. And its also a primary field. So it appears this data got into your table due to some error in the past. Hopefully from an early version of this feature before we added this work to parse and identify user type. 

Please go find and delete cases where User Name is blank from the table. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6a89a832-75bb-4e3c-bd02-82f606e05dd2)

Then let me know if they return, from my testing they do not

**Comment by julian0723** [comment]
We check one of the deleted users run in the table and not see the UserName field as empty. UserName filter by "Does Not Contain Data"
![image](https://github.com/microsoft/coe-starter-kit/assets/54391303/cf54e27e-1452-4363-b84a-78e5938eb7fe)

There is an empty field but it is "User Identity Provider".
![image](https://github.com/microsoft/coe-starter-kit/assets/54391303/01f41106-2f4f-4875-a0e5-eee68de16db0)

Also our flow is getting throttled. Is there a way to have COE working in Enterprise tenant?
![image](https://github.com/microsoft/coe-starter-kit/assets/54391303/68915768-1fc1-427c-94f7-af15e1ebaed8)

We would like to check that entry again but throttling issue is there.

**Comment by Jenefer-Monroe** [comment]
### Regarding the throttling
This is a high API usage flow, but it has also been reviewed to be as streamlined as we can make it. 
Please go see what SR's you've selected to be monitored and if you've chosen to track also the BU's.
This is in the Manage Permissions app as shown below. 
If you don't have SRs or BU's you can remove and still meet your organizations needs then you can consider a per flow license for this flow. Or it could be that they were just long running for their initial population. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6751f8f2-4a7d-48f1-998f-1a812b341dad)

### Regarding this issue
Looks like you may have an overrun issue due to the flow being long running as the filters here are nearly identical except one iterates through the other. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/85303928-6dea-40ff-b4b7-7aaa6484df3f)

### For both issues
I wonder if both issues are due to the table being initially populated. 
I suggest you turn the flow off, wait till all the runs complete (this will allow the API calls to drain)
Then turn the flow back on to see if you continue to see these issues.
