### ISSUE TITLE
[CoE Starter Kit - QUESTION FLOW ] I changed ownership, but the inventory is still out of date

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#8297]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hey guys,

I have a problem, we are changing the owner of some flows manually, but the inventory remains with the old one, which flow should I analyze?

I didn't find anything in these
![image](https://github.com/microsoft/coe-starter-kit/assets/94450591/69aaea0d-6733-4ffb-b9e7-f5c023f997ab)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Released May

### What app or flow are you having the issue with?

Inventory flow

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3270

**Comment by Jenefer-Monroe** [comment]
Hello, we have not yet updated the kit to use the information from changing the owner in the product but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see [[#3052](https://github.com/microsoft/coe-starter-kit/issues/3052)]( https://github.com/microsoft/coe-starter-kit/issues/3052)
In the meantime you likely want to set it in both places. In the product so that its correct from the product pov (the most important piece) and then in the kit so that the processes can see it.

**Comment by petepuu** [comment]
Have you updated the connection references to use the new account? You need to do that in default solution

Not sure will this help but I created PowerShell script which changes the owner of flows, canvas apps, connection references and environment variables. It requires these PS modules to work
https://www.powershellgallery.com/packages/Microsoft.PowerApps.Administration.PowerShell https://www.powershellgallery.com/packages/MSAL.PS

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
