### ISSUE TITLE
[AA4AM] Conditionally using a connector from a canvas app

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#832]
**Is your feature request related to a problem? Please describe.**
Currently, connectors are all or nothing when using an App. We would like to give the user a choice to connect or not and have Canvas Apps / Flows be intelligent enough to know what connectors are being used and make decisions based on what the user has enabled.

**Describe the solution you'd like**
Would be useful to be able to have conditionally required connectors. Specifically, this would enable AA4AM to use either GitHub or Azure Devops in the future if this was enabled in the platform.

Please upvote this if you have use cases that would benefit from enabling this feature in the platform.

**Comment by devkeydet** [comment]
I still agree this feature would be useful as a general platform feature.  For others context, we are *not* a part of any of the teams that build and deliver code to the service.  There are some exceptions where we have contributed, but overall we are faced with the same challenges as all of you.  Namely, solving problems using publicly documented and available platform features.

We have other challenges in achieving our broader goal of supporting both GitHub and Azure DevOps.  See:
https://github.com/microsoft/coe-starter-kit/issues/47

To have a canvas app that looks the same and behaves the same but uses either Azure DevOps or GitHub APIs would also mean that we have a canvas code base that is noisy due to conditionally calling different APIs.  That kind of codebase introduces complexity and technical debt that would be hard to maintain.  I am concerned that the end result would be more technical debt and difficult maintenance.  In turn, which means focusing less on new capabilities in our backlog and customer feedback. 
 
I am gravitating towards the opinion that the use case we have may be better served by an approach where we have two custom connectors with a consistent set of actions and response schema, then use canvas code copying to build two apps that have the same code but use different custom connectors actual custom connectors but with identical interface/schema.  I have a little spike / POC experimenting with the idea here:
https://github.com/devkeydet/TwoAppsTwoConnectorsSameInterface/

The downside is we would not be able to then achieve this longer-term goal.
https://github.com/microsoft/coe-starter-kit/issues/696

This is because the Azure DevOps & GitHub connectors have different actions / schema.  This makes sense for the common use cases.  Our use case is that we need to build an experience over both.  While this may not be unique to us, it is a narrower scoped use case than the common one.

@mikefactorial / @jenschristianschroder / @alvarezskinner / @Grant-Archibald-MS / I have had some healthy internal debate on this topic.  Every solution has pros/cons.  As we try to design more in the open and gather more feedback from the community, I'd like to test out welcoming others to share thoughts.

**Comment by devkeydet** [comment]
Moved to a discussion so we don't make the backlog item noisy:
https://github.com/microsoft/coe-starter-kit/discussions/1811

**Comment by mikefactorial** [comment]
Closing this issue since we're no longer tracking this as an option for adding GitHub support and it's not directly related to ALM or the ALM Accelerator.
