### ISSUE TITLE
[CoE Starter Kit - BUG] Remove dependency on CoE Settings Table

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#833]
### Describe the issue

Before environment variables we used the CoE Settings table to setup some properties for reading in to the objects in the CoE. Now that we have env variables, and as things like DfT has made using the table harder, we want to streamline to using just env vars. 

### Expected Behavior

just use env vars for input values. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

CoE Settings Table

**Comment by JeneferM-MSFT** [comment]
removing vnext marker until code complete. 
Core done. Todo: Nurture, Gov

**Comment by JeneferM-MSFT** [comment]
done in core, nurture and gov. Documentation updated as well.

**Comment by manuelap-msft** [comment]
This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
