### ISSUE TITLE
How to Verify Manually that user has the Power Platform Admin role

### ISSUE THREAD

**Issue by eileenoceilleachair** [microsoft/coe-starter-kit#8354]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the centre of excellence upgrade wizard it is asking me to verify manually that the user is a power platform service admin - how do I do this?  The user has the Power Platform Administrator role assigned to it and is a member of the security administrators  in the centre of excellence environment itself.  See screen shot attached for the error.
![coe issue](https://github.com/microsoft/coe-starter-kit/assets/156800138/cb62231a-e37a-4305-8ab0-324427567dd9)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2024 4.31 Core Components and 3.21 Governance Components

### What app or flow are you having the issue with?

Centre of Excellence Upgrade Wizard Confirm Prerequisites

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3365

**Comment by eileenoceilleachair** [comment]
Hi Jenefer,

I don’t see the permanent option or the Direct assignment either.

This is what I see for the user. – it is different to the screen shot you sent – I don’t have the options eligible, active or expired assignments like you have on the screen shot you sent.


***@***.***

**Comment by Jenefer-Monroe** [comment]
Hello screenshots do not come through if you respond in email, you need to log in to GitHub directly in order to share images. 

I'm not a PIM expert so there may be other ways to accomplish, but here is how I get the correct settings for the role: 

1. Add assignment
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5eba34a2-4aeb-48ad-8e26-636c82f1e02a)

2. Select the role, this is assigned to the user directly here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/46e9477e-b954-402b-8e78-c4c7c22edb71)

3. Set active and permanent, add note as needed
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3f13cfa3-07b2-4d0c-bcae-0ce4bb47613a)

**Comment by eileenoceilleachair** [comment]
Hi,
Thanks for your assistance. 
See attached two screen shots.
We don't have a P2 license to make the assignment permanent - I think you are using a P2 license and that is why your screen shots are different to mine and you see active, permanent and expired. [
![P1 license](https://github.com/microsoft/coe-starter-kit/assets/156800138/a3f94fb5-62af-46e8-bc30-2b360c11b6e7)
![P2 license](https://github.com/microsoft/coe-starter-kit/assets/156800138/3f3e772d-cb90-413c-9db0-572e60f37075)
](url)
How do I assign the Power Platform Administrator role as permanent and never expires without the P2 license?

  We have a P1 license.

**Comment by Jenefer-Monroe** [comment]
Sorry I'm just not sure the answer there. You may need to contact product support and see if there is a way to do it through Power Shell or something similar. I'm just using the product as it exists and so don't have control over these limitations.

**Comment by eileenoceilleachair** [comment]
Thanks, I'll try figure it out and check with support if I'm not having any luck.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
