### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Ramazancz** [microsoft/coe-starter-kit#8367]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to setup Wizzard and the setup flows are not showing in the app and because of that I cannot continue in the app. for info the flows that are supposed to run finished successfully. I need help or advice how to continue.
![image](https://github.com/microsoft/coe-starter-kit/assets/137779034/44f19dcd-dcac-468c-b091-3d96df596373)

### Expected Behavior

the flows should be seen in the app so I can continue in the setup

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

admin_CoESetupWizardPreview

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Import solution
Setup env variables
open admin_CoESetupWizardPreview

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/137779034/82b9b794-9333-4f6b-9eac-b4420a2a8960)

AB#3389

**Comment by Ramazancz** [comment]
Sorry for not responding

**Comment by Jenefer-Monroe** [comment]
Are you saying that this flow: **_Admin | Sync Template v3 CoE Solution Metadata_**
Did not end up in the table? 

That was the transient product issue others saw too. Basically the flow connector did not return them for whatever reason. 
For the other users, this issue was transient and went away when they tried later / next day. 
Can you please rerun the **_Admin | Sync Template v3 CoE Solution Metadata_** flow today and see if it shows up in the table this time?

**Comment by Ramazancz** [comment]
I had to reimport the solution yesterday so I tried today and nothing happened
