### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture Apps - Admin "Create teams event" not working

### ISSUE THREAD

**Issue by lsavard** [microsoft/coe-starter-kit#8373]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When clicking button "Create Teams event", the following message appears at the top of the popup window : Office365Outlook.CalendarGetItems failed: The function 'CalendarGetItems' has an invalid value for parameter 'table' - a blank value was passed to it where it was not expected. Please make sure that a valid argument is passed to the function.

When clicking button "Create Teams meeting for this event", another error message appears. See sceenshots for details.

I do not know if it is linked, but when users click on "Register" button in the "Nurture Apps - Makers", nothing happens.

Thanks !

![screen1](https://github.com/microsoft/coe-starter-kit/assets/51333566/ff86bdca-53cb-43c4-b19d-ea0dc303f789)
![screen2](https://github.com/microsoft/coe-starter-kit/assets/51333566/474628e7-1da4-4fda-8ded-4440d28ab3a9)

### Expected Behavior

No error messages when creating teams meetings

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.17

### What app or flow are you having the issue with?

Nurture Apps - Admin

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3396

**Comment by Jenefer-Monroe** [comment]
I dont see that UX in the new MDA version of the admin app, are you using the deprecated one? 

I do believe the makers button to register not working is this issue: https://github.com/microsoft/coe-starter-kit/issues/8350
Basically all buttons and panels in the kit are broken right now due to a product change that impacted the creator kit. 
We're getting a new drop of the creator kit this week and will update this app before we ship June to have a fix out there.

**Comment by Jenefer-Monroe** [comment]
Got it, thank you for those steps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team. issue is local fixed for June release with https://github.com/microsoft/coe-starter-kit/issues/8350
