### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Request Next button not working

### ISSUE THREAD

**Issue by alanmWDC** [microsoft/coe-starter-kit#8374]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the CoE Maker Command Center Environment Request page, after selecting New, the dialog shows to select connectors but after selection the Next button doesn't to anything when clicked.

### Expected Behavior

After selecting connectors, click the Next button to get to the security page.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CoE Maker Command Center Environment Request

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run the CoE Maker Command Center as a Maker or Admin
2. Select New
3. Select a connector and add to request
4. Click Next button

### Anything else?

I think this was an issue in the past with the formula that detects the button selection not being correct.

AB#3397

**Comment by alanmWDC** [comment]
Additional note is that the Next button works in the editor in play mode or with the Alt key but not if opened directly

**Comment by Jenefer-Monroe** [comment]
Hello, all dialogs and panels are broken in the kit today due to a product change that broke the creator kit components that we use. 

Here are the issues tracking this on the Creator Kit side: 
https://github.com/microsoft/powercat-creator-kit/issues/464
https://github.com/microsoft/powercat-creator-kit/issues/463

And the issue tracking on the CoE side
https://github.com/microsoft/coe-starter-kit/issues/8350

We will be getting a new drop of Creator Kit this week and then will update the apps in the kit before the June release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
