### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by JessicaFromBusPatrol** [microsoft/coe-starter-kit#8389]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I'm unable to update any environment variables needed for my sandbox update process.

### Expected Behavior

after I paste the sandbox environment ID, then select Save, the side window should go away and the new ID should update.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

after I removed the dataflows from production, I copied over my CoE Production to overwrite my sandbox environment. After verifying sandbox was in admin mode, I went to CoE admin center tried to modify "admin_ProductionEnvironment" to "No" tried to select Save and then nothing happens. 

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/160529204/8ebd4b75-f042-499a-9764-6ee0bcb33e31)

AB#3413

**Comment by Jenefer-Monroe** [comment]
Hello, all dialogs and panels are broken in the kit today due to a product change that broke the creator kit components that we use. 

Here are the issues tracking this on the Creator Kit side: 
https://github.com/microsoft/powercat-creator-kit/issues/464
https://github.com/microsoft/powercat-creator-kit/issues/463

And the issue tracking on the CoE side
https://github.com/microsoft/coe-starter-kit/issues/8350

We have a new drop of Creator Kit now and I am updating the apps in the kit before the June release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
