### ISSUE TITLE
[CoE Starter Kit - BUG] Delay Inventory  - variable cannot be switched to no 

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#8400]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When installing COE toolkit core components - May release, delay inventory variable cannot be switched to No in the GUI 

### Expected Behavior

user should be able to switch variable to no, save button does not commit change

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2024

### What app or flow are you having the issue with?

Governance Application COE toolkit

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

in this environment, install coe toolkit core, access management application, attempt to set variable top no.  save does not work 

AB#3426

**Comment by Jenefer-Monroe** [comment]
Hello, all dialogs and panels are broken in the kit today due to a product change that broke the creator kit components that we use. 

Here are the issues tracking this on the Creator Kit side: 
https://github.com/microsoft/powercat-creator-kit/issues/464
https://github.com/microsoft/powercat-creator-kit/issues/463

And the issue tracking on the CoE side
https://github.com/microsoft/coe-starter-kit/issues/8350

We have a new drop of Creator Kit now and I am updating the apps in the kit before the June release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
