### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flow Action Details) fails

### ISSUE THREAD

**Issue by Grant-R** [microsoft/coe-starter-kit#8421]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v3 (Flow Action Details) fails on the same entry each run. 
Unable to determine where the inaccurate data/info is coming from. 

![image](https://github.com/microsoft/coe-starter-kit/assets/60246683/cccd4817-da40-42e6-b6c4-6348e26e45f5)

![image](https://github.com/microsoft/coe-starter-kit/assets/60246683/bf86134c-fe9d-4a0e-84da-27737196f484)

![image](https://github.com/microsoft/coe-starter-kit/assets/60246683/f5f10f49-c14c-4e14-bd4a-749cb3c84986)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

 4.29

### What app or flow are you having the issue with?

Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

As per above screenshots

AB#3484

**Comment by Jenefer-Monroe** [comment]
Are you saying it returns and fails for this record id on rerun? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9dcf4e03-b304-41da-a340-0407e40732e5)

We see this failure from time to time but has always been due to overlapping runs. So I would not expect it to fail for this same id next run as it would not be returned. 
Can you please rerun this failure and check to see if it fails again and if so, if its the same id?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
