### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by iSK101** [microsoft/coe-starter-kit#8424]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

While creating an Environment creation request, nothing happens when I am clicking on the "Next" button after adding the connectors. Can anybody help me with this? Am I missing something?

Note : I am using the latest version of the CoE Starter kit.

![336778215-1ac4c155-375e-4885-bbfa-ee1f3066aaa9](https://github.com/microsoft/coe-starter-kit/assets/171793932/882839fd-3252-40d0-bdd8-9e0529456e04)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CoE Maker Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3487

**Comment by Jenefer-Monroe** [comment]
Hello, all dialogs and panels are broken in the kit today due to a product change that broke the creator kit components that we use. 

Here are the issues tracking this on the Creator Kit side: 
https://github.com/microsoft/powercat-creator-kit/issues/464
https://github.com/microsoft/powercat-creator-kit/issues/463

And the issue tracking on the CoE side
https://github.com/microsoft/coe-starter-kit/issues/8350

We have a new drop of Creator Kit now and I am updating the apps in the kit before the June release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
