### ISSUE TITLE
[CoE Starter Kit - QUESTION] PBI with environments with PCF/code components 

### ISSUE THREAD

**Issue by silvafr1** [microsoft/coe-starter-kit#8430]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,
In CoE Power Platform Admin View App we can get all Environments with PCF/code components feacture activated!
Do you have an idea when it will be in PBI report?

And to finish, does CoE Starter Kit collect which "PCF Components" are being used on each environment?
For security purposes, this option would be awesome!
Thank you!

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 2024

### What method are you using to get inventory and telemetry?

None

AB#3501

**Comment by Jenefer-Monroe** [comment]
Hello, to my knowledge there isn't a way for us to gather these PCF controls across the tenant but we have heard this request more than once, so if anyone in the community knows how to gather these, please do let me know. I'd love to get this done for you all. 

Regarding another report, we do have this on the backlog but I'm not quite sure when it will be done due to competing priorities, I would suggest you through something together yourself in the meantime as I just am not sure when we will get it done. Apologies.

**Comment by silvafr1** [comment]
Than you! :)

Best regards

**Comment by Jenefer-Monroe** [comment]
You bet, sorry we couldnt be more help in the near term on this one
closing out as no further action for starter kit team
