### ISSUE TITLE
[Data Export] Governance Dashboard doesn't shows correct Apps Last launched data

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#8472]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In Governance Dashboard PBI I have a blank in the "Apps launched this month" visualization.
I see that uses the data from Power Apps table:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/0f38322b-e0ef-4427-b528-35f7d56dba70)

But in the CoEDashboard PBI I can see the correct data with the last launches from apps.
In this case, the data used is in Power Apps Launches table
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/4308515e-7bfa-4229-880f-b762d2483501)

### Expected Behavior

Governance Dashboard must be have the updated data for Last launches of apps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2024

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard_June2024.pbit

### What method are you using to get inventory and telemetry?

Data Export

AB#3577

**Comment by Jenefer-Monroe** [comment]
Hello

I think the data in your Power Apps table may be wrong due to a flow not being turned on. 

We moved the updating of the Power Apps table to its own flow for performance reasons and it looks like you may not have turned it on. Please validate that both these turned on:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5447542a-72d7-448b-9556-c6ef0c5e0cf8)

That will fix the issue going forward, but I have also created a one-off flow to run which will go back and fix up app information for the ones you missed while the flow was off. 

### Import and Turn On the flow into CoE Environment
Go to https://make.powerautomate.com/ > select your CoE Environment > My flows > Import > Import Package (Legacy)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e2a7c2e7-1e63-4786-a097-b96c481ec51b)

Upload the following flow: 
[Fixupmissedauditlogentries_20240514131140.zip](https://github.com/microsoft/coe-starter-kit/files/15308849/Fixupmissedauditlogentries_20240514131140.zip)

Create the connection and Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/918baa95-1023-431e-a789-757ba832bd11)

When done click Open Flow to view and then back to see details and turn on.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f73573f1-e52b-496e-bdd4-acad4fce7df7)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a2acd671-7c52-4722-882e-9d8a23a52043)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed3f47f0-8c87-4b98-9713-1bfed6a4272b)

### Run the flow
Click Run enter the number of days back you need to go
For example if you missed 3 months of data you would put in 90 (for 90 days)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/74c77b1b-70aa-4f8f-8dcd-a6fdbb4bc4c9)

Flow will turn off your audit logs temporarily while it does this processing. Get everything fixed, and then turn them back on.

**Comment by albertocastro365** [comment]
Hi Jennefer,
I have turned off these flows because I use BYODL version.

**Comment by Jenefer-Monroe** [comment]
oh sorry I missed that you were Data Export. Let me take a look

**Comment by Jenefer-Monroe** [comment]
ok yes it looks like this wasnt made to work with Data Export. Will put as a feature for that work when we get the new schema update.

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
