### ISSUE TITLE
[CoE Starter Kit - QUESTION] Release Wave Notes Update

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#8483]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello CoE Team,

I hope you are well. 

For the apps "CoE Admin Command Center" and "CoE Maker Command Center" on the "Release Waves Notes" in the navigation pane, when I click on it, I don't see any notes for 2024. which is [available](https://learn.microsoft.com/en-us/power-platform/release-plan/2024wave1/).

Is there a Flow I need to run to populate this with 2024 data? I couldn't see a Flow name that corresponded with this task.

Thanks very much,

Garry

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3599

**Comment by Jenefer-Monroe** [comment]
I did just manually update all these for the June release via https://github.com/microsoft/coe-starter-kit/issues/8326
Until that bug was posted I did just assume there was a flow behind this but there is not, its all hard coded. 
So its updated for for now, and will need manually updated again for Wave 2. I dont know of a feed which these can be read rom.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
