### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unable to Save in the Developer Compliance App - Support form

### ISSUE THREAD

**Issue by Chitusnair** [microsoft/coe-starter-kit#8496]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Dear team,

We use the CoE kit February release. The Save button in the Compliance centre app in the Production environment is not responding when the user tries to save.

I have shared the app with the user through the M365 maker group with the role, Power Platform maker SR. Am I missing something?

Thanks,
CN

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3613

**Comment by Jenefer-Monroe** [comment]
Hello, 

All dialogs and panels were broken in the kit due to a product change that broke the creator kit components that we use. 
This has been resolved with the latest version of the creator kit: https://aka.ms/creatorkitdownload
- Creator Kit Core 1.0.20240529.1

Then this new version of creator kit has been adopted and used to fix in the June 2024 release of the kit: https://aka.ms/coestarterkitdownload
- Core 4.32
- Gov 3.24
- Nurture 3.18 

You will need to upgrade to the June release to see this fix across the kit.

**Comment by Chitusnair** [comment]
Hi Jenefer,

I don't understand by 'all dialogs and panels '. Do you mean the February version is completely unusable? Can you please be more specific? What are the components/apps/flows which are broken in the February version. Where can I find these information? 

We have CoE in the **test environment which is working fine**, both test and prod are the same version. I don't have issues with any other components, apps, flows etc that I notice other than the issue I mentioned above.

Thanks,

**Comment by Jenefer-Monroe** [comment]
Yes most apps have issues due to this. I did happen to make a list while I was fixing them, you can see it here: 
https://github.com/microsoft/coe-starter-kit/issues/8350

I don't know why you are still seeing this work in some envt, as I said this was a product change that broke the creator kit, and we are just consumers of that. 

So I would have to ask you to post questions in the creator kit forum if you need more specifics about the issue itself.

**Comment by Chitusnair** [comment]
Hi Jenefer,

Thanks for the update. I will upgrade the kit to the June version. Btw, I
would like to double check if nothing else is impacted, for e.g: Tables and
Inventory flows that populate them.

Thanks,
Chitra

**Comment by Jenefer-Monroe** [comment]
Do you mean impacted by the referenced bug? If so, no that bug just impacted canvas component in the kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
