### ISSUE TITLE
[CoE Starter Kit - BUG] Custom Connectors tab is not working as usual

### ISSUE THREAD

**Issue by patrickpooon02** [microsoft/coe-starter-kit#850]
### Describe the issue

The Connector drop down list is showing all connectors, even the standard connector that is available without customization.

### Expected Behavior

The drop down list should only contains the "Custom Connector", which is based on REST API and setup separately.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors)

### Steps To Reproduce

On Power BI Dashboard, switch to "Custom Connectors" tab. Then you can check the "Flow connector" and "App Connector" drop down list.

### Anything else?

![Custom Connector filteting](https://user-images.githubusercontent.com/82566841/125724122-1b92867a-de31-472b-a185-20c72605b2cb.png)

**Comment by manuelap-msft** [comment]
Hello,

thanks for the feedback - it looks like one of the filters to only show custom APIs has fallen out of that page. If you want to fix this yourself, you can select the drop down visual and add a filter on this visual to set "admin_iscustomapi" to true. This has to be from the Flow Connection References table for the Flow drop down and App Connection References for the App dropdown.
![image](https://user-images.githubusercontent.com/55705669/125755931-589b2456-2910-4b74-97c1-67f8adbde4e9.png)

However, we are also going to release a new version of the dashboard due to some other issues later today so you may want to hold off making the changes. I will update you here when the new dashboard is uploaded, just doing some final testing!

Thank you
Manuela

**Comment by patrickpooon02** [comment]
Hi Manuela,

Thanks for your quick response! Just want to note if you can also check the
filter of "App Connector" if it is running properly. It is because there
are not much custom App Connector in my tenant, so I cannot tell.

Best Regards,
Patrick

Manuela Pichler ***@***.***> 於 2021年7月15日週四 下午4:32寫道：

**Comment by manuelap-msft** [comment]
Hello,

fixed this issue and the new version of the Dashboard is now available either via the main download aka.ms/coestarterkitdownload or directly here: https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/CDSLegacy_CoEDashboard_202107_v2.pbit

Thank you
Manuela
