### ISSUE TITLE
[CoE Starter Kit - QUESTION] Upgrade path

### ISSUE THREAD

**Issue by tiagosazevedo** [microsoft/coe-starter-kit#8501]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,
what's the upgrade path for Center of Excellence - Core Components  between the version 4.9  and the latest version?

Should I upgrade step by step (version by version) or  can I jump to the latest?

What's the best practice? 
Clone the CoE environment to another and test the upgrade? I already tried this but got a duplicated component error. 

Or make a backup and try to upgrade in place?

Thanks in advance!

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3619

**Comment by Jenefer-Monroe** [comment]
Hello, here is our documentation on how to upgrade [Updating the Center of Excellence (CoE) Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/after-setup)

There are several issues you may run in to in an upgrade that old, including these ones:
Due to audit log deprecation: https://github.com/microsoft/coe-starter-kit/issues/6018
Due to delete of parent and child flows: https://github.com/microsoft/coe-starter-kit/issues/8130
Due to deprecation of legacy Dataverse connector: https://github.com/microsoft/coe-starter-kit/issues/8466

Generally we ask people to upgrade at least quarterly as thats the only way we are likely able to assist with issues. 
Regarding the the other questions, some people do have test environments that they upgrade first, if you have one of those please do. Otherwise you'll just need to upgrade your production envt.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
