### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE Setup Wizard -  Environment Request management - Enable cost tracking  - error loading control

### ISSUE THREAD

**Issue by KimberleyBrian** [microsoft/coe-starter-kit#8540]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the Center of Excellence Setup Wizard (in preview) - Environment Request management step,  for the 'configure mandatory values the questoin 'env request - enable cost tracking' shows an 'error loading control'.
![image](https://github.com/microsoft/coe-starter-kit/assets/25760206/902659c7-3d64-48be-9fbe-6bf98101290f)

### Expected Behavior

I assume a toggle yes/no control is meant to load

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Center of Excellence Setup Wizard - Environment Reuqest Management

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. open the setup wizard
2. click on 'environment request management'
3. click on 'next' twice to get to the 3rd step of 'configure mandatory values'
4. can see the error loading control on the right

AB#3671

**Comment by Jenefer-Monroe** [comment]
I don't repro this. Can you please reload the page and see if you still repro? Sometimes controls fail to load a first time. 

If you still repro after reload of the page, them please do the following: 

### What Solutions installed
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)
And also please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
