### ISSUE TITLE
[CoE Starter Kit - BUG] Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception

### ISSUE THREAD

**Issue by wangyon-git** [microsoft/coe-starter-kit#8548]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I upgrade the core component version (4.22 to 4.32), I got the following error message:
Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :The connectionreference(e9987570-96e0-48f5-b1ab-fe8e1f3c3e01) component cannot be deleted because it is referenced by 17 other components. For a list of referenced components, use the RetrieveDependenciesForDeleteRequest.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponents_4_32_2_managed.zip

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Import the solution : CenterofExcellenceCoreComponents_4_32_2_managed.zip

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/158856634/35df1a22-da50-43d5-b3f4-98975237e349)

AB#3684

**Comment by Jenefer-Monroe** [comment]
Unfortunately it looks like you've hit a product bug around upgrade. A few other people have hit this too. Please see https://github.com/microsoft/coe-starter-kit/issues/8466. 
### The connection
This is likely the legacy Dataverse connection that is at play, why it wont tell you the name I don’t know. 
But this is a connection that we have removed from the kit and that is causing issues in the product’s upgrade code.
### The likely issue
The issue is around dependency ordering. 
Flow X uses Connection Y
Both Flow X and Connection Y are deleted as part of the upgrade
The product is attempting to delete Connection Y before Flow X, which is cannot do. 
### Find impacted flows
Please go to the default solution > connection references > look at the dependencies for both of these connection references
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3bdbd49-f77b-42bb-be7f-fb665db85734)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c8186341-cf26-4710-aa3c-8b3e3bb9f2ea)
### How to work around the bug
As a result, in order to upgrade you will break the dependencies. 
You will need to:
1. Delete the _Upgrade solution (if one was left behind)
2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again
### Step 2 example
Example of how to do the workaround for one of the flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5044cf53-6776-411c-bc70-d0205227755c)
### Thats just awful!
Yes I apologize for the hassle.
The product team is aware of this issue but the fix has not yet come out.
And another user has succeeded with this workaround. See https://github.com/microsoft/coe-starter-kit/issues/8466

**Comment by wangyon-git** [comment]
Hi,

 

Hello, I tried the workaround and there are still some flows in the
dependencies that I cannot edit to remove. 

 



 

Here is an example with error:



 

This one is always Saving:

 



 

Thanks!

 

.:.

Yong WANG (il/lui, he/him)

Gestionnaire de produits ( ***@***.***>
Intégration solutions infonuagiques)

X-200, pavillon Roger-Gaudry

(514) 343-6111 x2732

@
<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.mic
rosoft.com%2Fl%2Fchat%2F0%2F0%3Fusers%3Dyong.wang%40umontreal.ca&data=05%7C0
1%7Cyong.wang%40umontreal.ca%7C972533cc2d7543e42ff108db7bf6b61f%7Cd27eefec2a
474be7981e0f8977fa31d8%7C1%7C0%7C638240071761973977%7CUnknown%7CTWFpbGZsb3d8
eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C
%7C%7C&sdata=v8TEwLMK7fJX5BLiUvSXIfFkRHdR0yPSe7lBq7I9vN8%3D&reserved=0>
Microsoft Teams

 

Technologies de linformation

Université de Montréal et du monde.

**Comment by wangyon-git** [comment]
Hello, I tried the workaround and there are still some flows in the dependencies that I cannot edit to remove. 
![image](https://github.com/microsoft/coe-starter-kit/assets/158856634/0e731123-b2fb-49f9-804f-760c2bd6b70a)

Here is an example with error:
![image](https://github.com/microsoft/coe-starter-kit/assets/158856634/7d560a47-f51b-410e-94db-a2f0a0517218)

This one is always Saving:
![image](https://github.com/microsoft/coe-starter-kit/assets/158856634/447e70fd-8f7b-4071-88ab-42853d8b35a0)

Thanks!

**Comment by Jenefer-Monroe** [comment]
Sorry that is a product issue that I cannot assist with. I would suggest perhaps just deleting other parts of the flow and saving after each thing you remove. 
Sorry for the pain.

**Comment by wangyon-git** [comment]
Finally, keeping Initialize variable step allowed Flow to be saved.
CoE Starter Kit has successfully completed its upgrade once the dependency issue is resolved.

Thanks again!
