### ISSUE TITLE
[CoE Starter Kit - BUG] EDITING ENVIRONMENT VARIABLES IN COE ADMIN COMMAND CENTER DOES NOT WORK

### ISSUE THREAD

**Issue by MatiasJulianDK** [microsoft/coe-starter-kit#8551]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When trying to use the CoE Admin Command Center to edit the Environment Variables when customized, the page does not respond while clicking save and does not save the values in the Environment Values table in the solution. It looks like the value is catched in the text field when pressing the "Edit" button but is not saved as a value when pressing "Save". This includes alle values that has been customized and also values which has not been customized. 

The values can be edited directly in the dataverse tables through forms. 

### Expected Behavior

That when pressing the edit button and pressing save, the value would be saved as the new value and the old value in the field would be overwritten to enforce the change. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Go to CoE Environment where solution is installed
2. Go to "CoE Admin Command Center" Model Driven app 
3. Go to the "Environment Variables" custom page under "CoE Configuration" 
4. Choose "AdminEmail" and press "edit"
5. Edit the value 
6. Press the "Save" button
7. Check that the value is not saved

AB#3687

**Comment by Jenefer-Monroe** [comment]
Hello, 

All dialogs and panels were broken in the kit due to a product change that broke the creator kit components that we use. 
This has been resolved with the latest version of the creator kit: https://aka.ms/creatorkitdownload
- Creator Kit Core 1.0.20240529.1

Then this new version of creator kit has been adopted and used to fix in the June 2024 release of the kit: https://aka.ms/coestarterkitdownload
- Core 4.32
- Gov 3.24
- Nurture 3.18 

You will need to upgrade to at least the builds above to see this fix across the kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
