### ISSUE TITLE
[CoE Starter Kit - BUG] Assign Role Child Flow failed 

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#857]
### Describe the issue

While I created a new Project using ALM Accelerator for Maker's child flow Assign Role got failed at Get Token Action. Below is the screenshot of the error message. 

![image](https://user-images.githubusercontent.com/75992078/125818168-b62d2207-baeb-41ed-8830-cfbb6881c5ee.png)

{
  "error": "invalid_grant",
  "error_description": "AADSTS50126: Error validating credentials due to invalid username or password.
  "error_codes": [
    50126
  ],
  "error_uri": "https://login.microsoftonline.com/error?code=50126"
}

I selected as a Core component because there is no option to select ALM Accelerator for Makers. 
Solution Name - ALM Accelerator for Makers 
Version - 1.0.20210521.1

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.20210521.1

### What app or flow are you having the issue with?

AssignRole

**Comment by mikefactorial** [comment]
@AkashPatel136 double check user/password specified in the Admin app. If they are correct double check the app registration setup. A similar issue was reported yesterday here https://github.com/microsoft/coe-starter-kit/discussions/849

The fix was related to step 11 in the setup doc. 'Under Advanced Settings > Allow public client flows, turn on the Enable the following mobile and desktop flows toggle.'

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator#create-an-azure-ad-app-registration

**Comment by AkashPatel136** [comment]
Hi @mikefactorial 

I have done that and that is correct based on the documentation. you can see the below image. 

The only 1 thing I want to point is that I did not create the app registration using the account which I have provided in the ALM for Makers app. Also, that user does not have some permission so it cannot change anything on the App registration. 

![image](https://user-images.githubusercontent.com/75992078/125820660-6d380ea4-79e4-491b-bdac-b55fb39ff898.png)

**Comment by mikefactorial** [comment]
@AkashPatel136 one thought. Is the user you have in the Admin settings using MFA? For AA4M you need a user that doesn't require MFA.

**Comment by mikefactorial** [comment]
I just had dejavu... :) https://github.com/microsoft/powerapps-tools/issues/649

**Comment by AkashPatel136** [comment]
MFA is disabled.

**Comment by mikefactorial** [comment]
Another possibility? Is the user you have in the Admin settings a Federated account (e.g. an account in on-prem Active Directory that is synced with AAD)? If so, try using an account that was created in AAD as an alternative...based on this article I found https://docs.microsoft.com/en-us/answers/questions/38035/aadsts50126-invalid-grant-error-validating-credent.html

**Comment by AkashPatel136** [comment]
Hi @mikefactorial 

if I understand correctly. When I try to log in it will show me the Microsoft login page and once I enter the user name it will take me to our SSO page for the login. 

![image](https://user-images.githubusercontent.com/75992078/125826053-4182654e-caf7-4efb-8462-4e591b484109.png)

![image](https://user-images.githubusercontent.com/75992078/125826070-565b5b98-81e0-46bf-9fa6-9612e01c78f9.png)

**Comment by mikefactorial** [comment]
Yeah that would be ADFS. Looks like there's only a couple of options in this case to be able to use this type of auth flow with your app registration. This article does a good job of describing the options. https://docs.microsoft.com/en-us/answers/questions/399347/invalid-grant34-34error-description34-34aadsts5012.html

1. Create a cloud only user (i.e. a user created in Azure Active Directory) to use as the service account.
2. Enable  Password Hash Sync (PHS) in ADFS.

Neither may be ideal for your org though.

The overarching issue here is that AAD has no idea what the user's password is since it is stored in, presumably, your on-prem Active Directory so AAD can't directly authenticate the user/password supplied and there appears to not be a flow from AAD to AD that would allow the app registration to handle this scenario. This is an unfortunate side effect of using a service account instead of a Service Principal in AA4M.

From the Microsoft Docs: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc

**Comment by AkashPatel136** [comment]
HI @mikefactorial 

Any idea when the service principal will be available in AA4M?

**Comment by mikefactorial** [comment]
We don't have a timeline for using service principal in AA4M. Any additional work on AA4M would be done after we release AA4AM and would involve porting our AA4AM pipelines to work with GitHub workflows #47 which isn't planned right now, but will be a priority once our AzDO pipelines are stable and complete.

**Comment by AkashPatel136** [comment]
Hi @mikefactorial 

once the account is created does that account need any additional setup like admin role, environment role, license?

**Comment by mikefactorial** [comment]
The User will need a license. Once they have a license it will take a little while for the user to sync to Dataverse but that will happen automatically. You'll need to assign the new user a Dataverse role in the environments they should have access to.

**Comment by AkashPatel136** [comment]
ok thanks, Mike, I will try this and update you. 

The user does not need the Power Platform Admin role, am I correct?

**Comment by mikefactorial** [comment]
It probably will in order to provision and read environments, but might make sense to start with least privileges and add-on from there.

**Comment by mikefactorial** [comment]
@AkashPatel136 closing this issue as there is nothing more for us to work on here.
