### ISSUE TITLE
What SRs are needed to edit environment variables in an environment? 

### ISSUE THREAD

**Issue by Tracharr** [microsoft/coe-starter-kit#8575]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

my developers have environment maker security role in an environment - until recently they could see all environment variables and edit them. Recently this changed and they can only see and edit the environment variables that they created. I have multiple developers working on the same apps and they need to be able to see them - is there something that has changed or  I have changed that would effect this - I have made no changes to the security roles?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

All V3 flows

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
It sounds like this is a general question about the products system of SRs and env variables, outside the context of the kit. 
Unfortunately we are not staffed to assist with product questions like this. 

To my knowledge no change has occurred there. 
Happy to hold open a few days to see if others in the community have ideas. Otherwise you should perhaps post in the power platform community: https://powerusers.microsoft.com

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
