### ISSUE TITLE
[CoE Starter Kit - QUESTION]How this column InventoryMyFlowActionsDetails in Flow table will get updated with values No and Yes 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#8581]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 

Thank you so much for your continuous support on our queries. 

we got a case in our organization to get flow action details for their flows, when we turn on the admin sync flows action details , we are unable to get the details because of no performance and throttling actions issue. 

error : 
Your flow was turned off on 6/22/2024 6:01:51 PM (1 week ago) because it was running more actions than expected

so we decide to customize the flow as a instant flow by copying it and and we input the environments and then we are able to run the flow and capture the flow action details in the Flow action Details table 

Replaced the flow retrival condition 

From 
admin_flowdeleted ne true and admin_inventorymyflowactiondetails eq true and _admin_flowenvironment_value eq envName and admin_flowispublished ne false

To admin_flowdeleted ne true and _admin_flowenvironment_value eq  envName

Could you please let me know if this is okay to implement and fetch the action details based on demand. 

Do you see any potential challenges here ?
Also , How this column InventoryMyFlowActionsDetails in Flow table will get updated with values No and Yes  ?

Thanks in advance 

![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/7d94950c-5e5f-4089-a45f-d4a02a0caef9)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4,31

### What app or flow are you having the issue with?

Admin-Sync V3 Template 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I'm afraid I can't comment much on the flow working in your customized proposal. I think it should work although you would need to either replace the set logic with something else, or update it to apply to a single flow. Please do let us know if you get this working, I've had other people ask for this and so the community would enjoy seeing how to get this done! 

Regarding how that flag is set to true programmatically, its done in the **_SYNC HELPER - Cloud Flows_** flow during inventory of a flow. It's at this point that we know the flow is being inventoried for some reason (its been modified, is new, etc)
And so we also set it to have its actions inventoried.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/149d6254-f128-4ba3-bbfa-85571068bfa1)

**Comment by pamatihyd** [comment]
Hi what do you mean by set logic could you please show screenshot or explain.

We are running this flow in an environment with 589 flows. It has been in progress for 18 hours and is still running, but no details have been captured in Flow Action Details.

**Comment by Jenefer-Monroe** [comment]
Regarding it running for 18 hours. It is likely throttled. Unfortunately this is just a product limitation around API limits. You will just need to wait while it drains. 

Regarding set logic. We do this all over the kit, I've used a more simple example here to show you: 
From Admin | Sync Template v4 (Flows), where we look for new flows
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5a180384-9219-47e1-b26c-0f0f4a3b4e9e)

Basically we build two sets which we will compare. New objects are the simplest to understand which is why I'm using them to explain. 
We build up a set (a list) of all flows according to inventory using their GUID and then another set (list) showing all flows according to the tenant using their GUID
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1dc879b8-98ce-4ebe-a12d-9698c82bac57)

Then we do the set logic, meaning we compare these two sets to identify the flow GUIDs from the actual (tenant) set to find those not already in the inventory set, and we add those to the "flowsToInventory" array
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fa03af6d-9b54-45bb-90ed-0adde0dfe07a)

**Comment by pamatihyd** [comment]
Thank you so much Jenefer-Monroe)

**Comment by pamatihyd** [comment]
Hi Jenefer-Monroe, 

It was a great explanation I understand it very clearly, I have a last query 

In the flow Admin | Sync Template v3 (Flow Action Details) 
I understand the set logic clearly but when we see Scope  Get Specialty Action Details 

why do we need this scope  for capturing flow action details 
![image](https://github.com/user-attachments/assets/ea2f13fd-a85c-4a13-bfe3-6f89fc71a538)

what is the impact if we remove this scope just the logic goes like this 
For an environment----Fetch all flows 
Set Logic get GetCurrentInventory and GetActualInventory
Load the newly added actions into the FlowAction details  table 
Remove the non existing actions from the FlowAction details table. 
*************************************************************************************
because I could see sometimes even if the flow have 20 flows also getting stuck for 18 to 20 hours of that scope , 

It would be great if you guide me here, Thanks alot for your excellent support and sorry for opening ticket again.
