### ISSUE TITLE
[CoE Starter Kit - QUESTION] Security Roles do not affect access to applications

### ISSUE THREAD

**Issue by Dutycalling** [microsoft/coe-starter-kit#8582]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When attempting to share apps with my makers (e.g. Developer Compliance or Maker Command), adding any of the Power Platform Security roles does not allow a user to access any of the applications. Users run into attached Error Message.

Using the same methodology of sharing but adding a system administrator or customizer role (not what we want) does allow users to open the app.

![Error Message](https://github.com/microsoft/coe-starter-kit/assets/174716186/3f7bae4a-2329-4f3f-82ba-7410f57e47c5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2024

### What app or flow are you having the issue with?

Maker Command (or any other core component app)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I just tested to validate this is working for the Maker Command Center. 

Can you confirm, did you share the MDA with the SR? See below for some helper instructions for how to do that. 

### How to share a MDA
In order to share a MDA with users you first need to share the app as a whole with the desired security roles
Share the app as a whole with the Security Role
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3d532a9-92f5-4765-aeef-a9e171f19a46)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5377d117-c406-4293-bd3b-1c966f1569a8)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c9d7d6a-5e3e-4dab-b8d9-9749fcadaa15)
Now that SR can be applied to users you share the app with.
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f8976c2-b594-43da-b56c-fa4932fd7400)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
