### ISSUE TITLE
[CoE Starter Kit - QUESTION] Makers Group

### ISSUE THREAD

**Issue by Zkemp26** [microsoft/coe-starter-kit#8670]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When setting up the compliance components we noticed that users cannot access the Dev Compliance center, while having the appropriate SRs for that group (power platform Maker SR) the COE environment contains no security groups and is open and the makers group was the recommended created M365 group. I can see the group itself when i look at the admin center under teams, however the users in that group are not fully populated  (1100 group members, only around 7 are showing). I believe this is because they have yet to navigate to the COE environment, but i was under the assumption that users would be able to do so during the compliance emails that get sent to makers. 

How should the COE access be set for makers so that they can reach the applications they need to?(DCC was already shared with the group with the appropriate SR and the app itself has the SR selected) 
![Screenshot 2024-07-18 at 10 28 36 AM](https://github.com/user-attachments/assets/4b4d1eff-f12d-4d44-a2dc-65ac3251bac8)
![Screenshot 2024-07-18 at 10 28 51 AM](https://github.com/user-attachments/assets/81103ad9-6ed2-4a4b-82fd-80bbd7178959)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 4.32.2 Gov3.24

### What app or flow are you having the issue with?

Dev Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3836

**Comment by Jenefer-Monroe** [comment]
Hello. I just tested in the July release and it does appear to work, and I dont think that its due to the build number, so likely just something in your setup. 

Here is a little write up we have on how to share a Model Driven App. Can you see if that does it? Perhaps you missed that last step? (Share the SR with the user)

### How to share a MDA
In order to share a MDA with users you first need to share the app as a whole with the desired security roles
Share the app as a whole with the Security Role
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3d532a9-92f5-4765-aeef-a9e171f19a46)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5377d117-c406-4293-bd3b-1c966f1569a8)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c9d7d6a-5e3e-4dab-b8d9-9749fcadaa15)
Now that SR can be applied to users you share the app with.
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f8976c2-b594-43da-b56c-fa4932fd7400)

**Comment by Zkemp26** [comment]
Hello! Would the app still need to be shared with each individual user if the team they are a part of has already had this shared and has the appropriate SR? 

We would be sharing to well over a thousand makers. And if sharing with the makers individually  in the tenant, is there less painful way than assigning a power platform Maker SR to each maker dynamically?

**Comment by Jenefer-Monroe** [comment]
You should be able to share with a group here, I didnt see you had shared that SR with the group sorry. 

This is really a product behavior, not something with the kit. But I did find some helper links to get you going:

[Use Microsoft Entra groups to manage access](https://learn.microsoft.com/power-apps/maker/model-driven-apps/share-model-driven-app#use-microsoft-entra-groups-to-manage-access) from [Share a model-driven app](https://learn.microsoft.com/power-apps/maker/model-driven-apps/share-model-driven-app)

[Microsoft Dataverse teams management](https://learn.microsoft.com/power-platform/admin/manage-teams#about-group-teams)

I know I've done this before too so please take a look at these documents and see if they expose what you are missing there.

**Comment by Zkemp26** [comment]
Thanks Jenefer! It looks like the problem came down to licensing as makers did not have the appropriate ones to access the DCC.

**Comment by Jenefer-Monroe** [comment]
wonderful news! I'll go ahead and close this out then. feel free to return with new issues!
