### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Environment Properties)

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8677]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Invalid Schema with Admin | Sync Template v3 (Environment Properties)
![image](https://github.com/user-attachments/assets/f8d84274-5da1-4ec3-a157-a7cb9aa381b9)
![image](https://github.com/user-attachments/assets/80ed460b-b6c3-4a81-9e9c-471e4bf5dadf)
![image](https://github.com/user-attachments/assets/504d32ba-f0ce-4d42-ba45-0174d2f4337b)

### Expected Behavior

Schema should match. This is a GCC tenant. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Environment Properties)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3850

**Comment by JamesClapper** [comment]
Following as we our GCC instance is affected by this bug as well.

**Comment by Jenefer-Monroe** [comment]
Hello. That flow was deprecated in the March 2024 release of the kit. The actions in it were incorporated into CLEANUP - Admin | Sync Template v4 (Other Objects)

I'm not sure why you are still seeing it. Perhaps you did an "update" instead of an "upgrade". 
If you do an upgrade it will remove flows that have been removed from the solution. 

Or perhaps you have a failed upgrade with two versions of Core sitting in your solution file.

**Comment by Jenefer-Monroe** [comment]
great, thanks for confirming! 
@JamesClapper please let me know for your case as well.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
