### ISSUE TITLE
[CoE Starter Kit - Documentation] Audit logs unclear how to respond to the "you need smaller chunks" mail

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#868]
### Describe the issue

point people to documentation but its not to a specific place in setup
give example of 30 minutes

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.50

### What app or flow are you having the issue with?

parent flow

**Comment by JeneferM-MSFT** [comment]
Fixed documentation to show the expected values are singular by giving examples
And gave product documentation feedback on their typo

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
