### ISSUE TITLE
[CoE Starter Kit - BUG] Make link to Cleanup Old Objects App optional in the driving flow

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#869]
### Describe the issue

can make the env var optional in the flow and then not have the "click here" in the mail.  

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin | Email Managers Ignored Approvals Admin | Setup | Ignored Archival Requests

**Comment by JeneferM-MSFT** [comment]
fixed for August release

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
