### ISSUE TITLE
How can we categorise an App in the App Catalog as Sales or Finance etc...

### ISSUE THREAD

**Issue by gghaleb** [microsoft/coe-starter-kit#8691]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How can we categorise an App in the App Catalog as Sales or Finance etc...

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3874

**Comment by Jenefer-Monroe** [comment]
Hello. Thanks for posting. You got me to see that we missed a fix here. A product change required we shift the way we use search bars. So that is fixed for August now thanks to you posting: https://github.com/microsoft/coe-starter-kit/issues/8692

Workaround till you upgrade is to enter a character into that search bar. 

Anyway, to answer your question, this is filled in the Power Platform Admin View app as shown here: 
![image](https://github.com/user-attachments/assets/9813b62f-ed71-4eb9-aa43-6efab7e8131e)
![image](https://github.com/user-attachments/assets/cbe1d251-4137-4998-95ef-13cc207aab53)

**Comment by gghaleb** [comment]
Thanks a lot
