### ISSUE TITLE
[CoE Starter Kit - Test Case] Add Object ID as string to the views and Set Permissions apps for cloud flows, canvas apps, and MDAs

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#870]
### Describe the issue

So many tools show the user the object id and not object envt and name. its a pain. Lets add the object id to the MDA main view to make this eaiser for folks. 

### Expected Behavior

add id to the views in the MDA for the objects

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

MDA

**Comment by JeneferM-MSFT** [comment]
For whatever reason the GUIDs aren't offered to be in the views. But I did see they can use advanced find so I will send that to the user that was asking for this and then return to decide if we can do something else.

**Comment by JeneferM-MSFT** [comment]
I did a brute force thing where this will be present for cloud flows, canvas apps, and MDAs. 

To benefit from this you will require a full inventory run. See [incomplete inventory](https://docs.microsoft.com/power-platform/guidance/coe/limitations#incomplete-inventory)

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
