### ISSUE TITLE
[CoE Starter Kit - QUESTION] governance flows - import as disabled 

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#8711]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

hi all, I imported the governance components of the COE toolkit. But the flows were enabled on import and sent a large number of contacts out to users before I was ready . Is there a method to ensure the flows are disabled on import so they they dont start processing until i am ready.

is it a default behaviour for the flows to import in an enabled state

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Jul 24

### What method are you using to get inventory and telemetry?

None

AB#3904

**Comment by crowdedLeopard** [comment]
Hi @Jenefer-Monroe , did we manage to do  a pass to correct the governance flow enablement state. Many thanks

**Comment by derekmalag** [comment]
Hi @Jenefer-Monroe, many thanks for the update. Another one here that have suffered the impact of this and sent a large amount of emails to users. May I ask if June version is fine from this bug? I would rather import June version if it is free from this bug. Otherwise assuming that the process below will prevent compliance emails to be triggered to users: 

1. Update temporary 'ProductionEnvironment’ to 'No' in PROD
2. Import Governance Components and Manually turn off compliance workflows
3. Update back 'ProductionEnvironment’ to 'Yes'  in PROD

Thank you to you and the team for your effort to fix this.

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
