### ISSUE TITLE
Environment Capacity Differences Between the CoE Starter Kit and PPAC

### ISSUE THREAD

**Issue by VA-smcvey** [microsoft/coe-starter-kit#8731]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In building reports for the Business Customers from the CoE Starter Kit to determine storage capacity.  We are noticing discrepancies between the database consumption table in the CoE Starter Kit compared to the same environments in the capacity view in PPAC.  An example is included below.

We are being asked to explain the difference from our Power Platform CoE Management.

Thanks in advance for your help.
![image](https://github.com/user-attachments/assets/f32583dd-9b29-448b-826f-1d212650120e)

![image](https://github.com/user-attachments/assets/20ca4c85-3cc1-485d-a4a0-567219e3cc43)

### Expected Behavior

The database, file, and log capacities would be the same whether viewed in the CoE Starter Kit App or from PPAC.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31 (May 2024)

### What app or flow are you having the issue with?

CLEANUP HELPER - Environment Capacity

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We get these numbers directly from the product's connector as shown here:
![image](https://github.com/user-attachments/assets/ea6a83b4-fd71-48f4-adfb-7718bc5ab46a)


So any differences between what is shown in the Product's UX and the Product's Connector would either be due to when these processes run, or some difference in the way the product collects it for display in ux v api. 
Unfortunately I would not be able to explain the differences in what is returned and you would need to contact product support.
However the numbers seem pretty close to me so I presume its just the time of when the collection runs. 
In the kit that number is gathered weekly.

Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
