### ISSUE TITLE
D4T envt cleanup and bots

### ISSUE THREAD

**Issue by renrous** [microsoft/coe-starter-kit#8739]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

An environment of the dataverser for team type was removed from us, in line with this, what we identified is that the bot had activities in the last few days according to the definition of activities in the product documentation https://learn.microsoft.com/es-es/power-platform/admin/inactive-teams-environment#definition-of-user-activity but these activities were from bots and this is not contemplated in the flow logic.

![image](https://github.com/user-attachments/assets/fc2e71dc-4910-4282-9010-e40ead78f9ed)

therefore although interactions with a bot are considered an activity based on the documentation but the flow does not evaluate them, the bot is deleted, I think this should be taken as an issue and the flow should be modified to evaluate this type of activities and avoid the deletion of dataverse for teams type environments that are productive and active

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately what you have pointed to is the product feature for inactive D4T environments:
Product feature: https://learn.microsoft.com/power-platform/admin/inactive-teams-environment#definition-of-user-activity

While this flow is part of the starter kit and is documented here:
[Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#microsoft-teams-admin--weekly-clean-up-of-microsoft-teams-environments)
![image](https://github.com/user-attachments/assets/fcd7a89c-3cd2-4e7e-8d0a-430fafbbf150)

If you can use the product feature instead of the kit, that would be advised as the starter kit is just a set of sample implementations while the product itself is, of course, a robust platform with first class support.

Sorry for the confusion, and hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
