### ISSUE TITLE
[CoE Starter Kit - QUESTION] Clarify how Power Platform Users table works

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#8765]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'd like to use this question as a placeholder to clarify how the Power Platform Users table works as there's not too much information available about it.

**Q1**: How do rows get created in the Power Platform Users table?
**Q2:** Are Power Platform User rows removed if a Power Platform User has no apps shared with them (shared apps and power platform user roles are empty due to revoked share)?

Closest reference:
https://github.com/microsoft/coe-starter-kit/issues/6449

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.32.2

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Hope the below helps!

Q1: How do rows get created in the Power Platform Users table?
They get added in a few ways but they all are around apps/flows being shared with people as viewers. 
So if someone has an app shared with them as a viewer (for example) then they will appear in the Power Platform Users table.

Q2: Are Power Platform User rows removed if a Power Platform User has no apps shared with them (shared apps and power platform user roles are empty due to revoked share)?
No, we do not do any clean up of this table, nor the Maker table.

**Comment by anttipajunen** [comment]
Perfect, thanks Jenefer. This helps!

For the archives:
Admin | Sync Template v3 (Call Updates) runs weekly and calls both CLEANUP - Admin | Sync Template v3 (Orphaned Users) and CLEANUP - Admin | Sync Template v3 (Orphaned Makers).

**Comment by Jenefer-Monroe** [comment]
So glad it helped! And thats correct, as well as a few other flows we run periodically as shown here
![image](https://github.com/user-attachments/assets/fc8c102d-428d-4481-9eb8-aa2f0fd2d56a)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team

**Comment by anttipajunen** [comment]
@Jenefer-Monroe I'm coming back to this. Can you clarify when a maker is marked orphaned in the maker table?
