### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI CDSLegacy July 2021 v2 defects

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#880]
### Describe the issue
1. The option "Drill through" to "Cloud flow detail" is not available.
2. In Enviroments tab, all the enviroments shows the same number of Desktop flows and Chatbots
3. In Apps tab, the graphic "Top Env's by % of Apps" shows a incorrect data. In my case we have the most apps in Default enviroment, and this enviroment isn't showed in this chart.
4. A weeks ago I changed the name of our Default enviroment. In apps tab, I can see apps in the old name and the new name enviroment. In the PBI Dasboard of June I could see this data OK.
5. In Custom Connectors tab, the chart shows incorrect data. Every months shows new custom connectors created but there is no real. If I select any month always shows 4 custom creator. Also we have more custom created. This data of the custom conectors is different in any tabs of the pbi dashboard.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

PowerBI CDSLegacy July 2021 v2

### What app or flow are you having the issue with?

PowerBI CDSLegacy July 2021 v2

### Anything else?
![image](https://user-images.githubusercontent.com/57954993/126397396-81236c0e-bbab-475c-b546-6a287bdafb91.png)

2.
![image](https://user-images.githubusercontent.com/57954993/126222388-b4c10a40-b78d-432a-9217-6966bb45386a.png)

3.
![image](https://user-images.githubusercontent.com/57954993/126222651-901d42ec-1f3a-48f3-a265-67817cde8e95.png)

4.
![image](https://user-images.githubusercontent.com/57954993/126226478-378e073a-8d46-418c-ac51-97a0923b81b3.png)

5.
![image](https://user-images.githubusercontent.com/57954993/126227771-809152ca-3734-49f5-8199-4726d74132b8.png)

![image](https://user-images.githubusercontent.com/57954993/126227880-d5243a68-7130-46f6-8a73-9c69c1796720.png)

![image](https://user-images.githubusercontent.com/57954993/126227914-78d398f4-8c9b-4572-95f9-f1230c2519b8.png)
Enviroments:
![image](https://user-images.githubusercontent.com/57954993/126227951-014ef775-2bc1-4214-a3c8-1ee45ceb7186.png)

**Comment by manuelap-msft** [comment]
Hello,

regarding renaming the Default environment:
- by default, the sync flows (Admin | Sync Template v3 ...) only update apps, flows that have been updated since the last run
- renaming the environment will not mark an app or flow in the environment as modified
- what happens during the Sync Flow is that new or modified apps, flows etc will get stored in the Dataverse tables with the new environment name
- existing apps and flows that have not been modified will remain with the old name
- some of the visuals in the Power BI dashboard use the Environment Name field stored in the App table to display information, and not from the Environment table. Hence this info is out of date on some screens. 

The easiest way may be to bulk update your apps and flows, e.g. through Editing the data in Excel and updating the Environment Display Name field to reflect the new name. 

I will have a look at the other issues this week as well - have been on leave for the past week so just catching up now :)

Thank you
Manuela

**Comment by manuelap-msft** [comment]
1. Fixed for August by adding the Flow ID to the table
![image](https://user-images.githubusercontent.com/55705669/128337657-f8a8d934-e736-45c4-86c1-72ae9bb1052f.png)
2. Addressed for August release
3. Fixed, the filter was incorrectly set to First 5 Apps instead of Count Apps 
![image](https://user-images.githubusercontent.com/55705669/128337588-cc210e09-a191-45be-a303-66569be33fdb.png)
4. As explained above
5. Fixed. On the Custom Connector page, the filter to only show Custom Connectors was missing 
![image](https://user-images.githubusercontent.com/55705669/128338220-aba79b26-21df-4afe-8023-04cba45a7fc4.png)
I do not repo showing different custom connector counts on different pages, for me it always shows the same number.

The August release will go out early next week, likely Tuesday and these issues will be fixed then. 

Thank you for testing this so thoroughly and making the CoE Starter Kit great,
Manuela

**Comment by albertocaa1317** [comment]
Thanks to you @manuelap-msft

**Comment by albertocaa1317** [comment]
Hi,
all issues fixed except the point 1. I will open a new issue about this.

**Comment by mikefactorial** [comment]
@albertocaa1317 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
