### ISSUE TITLE
[CoE Starter Kit - QUESTION] Your flow is running too many actions

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#8800]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have been receiving this email for all Core CoE Flows.

Could you please let us know if this is related to larger tenants having more resources, which is causing Flow usage to reach 80%? Are the regular Flows facing any issues?

Do we anticipate a further spike in usage going forward?

Is there a way to handle these scenarios?

![image](https://github.com/user-attachments/assets/144ef0f2-aa53-4699-9f32-21bed5452d4f)

![image](https://github.com/user-attachments/assets/cb5ae90b-ac80-4cab-b17a-c300be9d7309)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately in a general manner there are just product limitations on the number of API calls that can be made. 

For Audit Logs, luckily another API has become available and we do have it integrated into the August release. 
Please see https://github.com/microsoft/coe-starter-kit/issues/8482#issuecomment-2211797168 to understand how to integrate that one once [August release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024) is available.

For AI events, unfortunately there isnt anything we can do for that one at this time. The good news is that the product team is working on providing this data natively with a new version of Data Export at which time you would be able to get this data natively rather than through the sync flows. 

Please feel free to come to the office hours to hear more information about these. 

### Office Hours
Please consider attending our monthly office hours. We talk about new features, upcoming changes, and spend most of the time answering your questions. 
More information:
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)

**Comment by Jenefer-Monroe** [comment]
The AI credits one was raised by product team to us as well and we found an issue in the flow which is resolved now for August relesae. 
Please see the issue: https://github.com/microsoft/coe-starter-kit/issues/8814
And the fix is available here: https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
