### ISSUE TITLE
DLP Editor V2 - Idea ::: Export list of apps or flows impacted by a DLP

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#881]
Hi,
in the power app DLP Editor V2, it would be helpfull to can export a list of the apps or flows impacted to a DLP to be analyse offline
Thanks.

**Comment by mikefactorial** [comment]
@albertocaa1317 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by mikefactorial** [comment]
@albertocaa1317 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by albertocaa1317** [comment]
Hi @mikefactorial,
How can I export this list of apps/flow impated with a DLP? I don't see the option. (I haven't unmanaged layers in DLP Editor app)

**Comment by manuelap-msft** [comment]
Hey, sorry about that - this was incorrectly closed as we had marked it as part of the December milestone, as we had planned on delivering it then but we didn't finish the work yet. I'm opening it up again now so we will continue tracking this!

**Comment by albertocaa1317** [comment]
Not worries. It's 2nd failed attempt of release 😅
I trust in the 3rd.

**Comment by manuelap-msft** [comment]
@albertocaa1317 I'm working on it right now and it's looking good! Got the CSV almost ready - quick question for you; generating the CSV can take quite some time to run (it's done in a flow), in my small demo tenant it's 30 seconds so too long to keep the app in a state of waiting. So my idea was to run that in the background and send the CSV to the user of the app once it's ready. Would that work for you?

**Comment by albertocaa1317** [comment]
It's perfect @manuelap-msft !!! I don't see problem in receive the list in a mail later and the same to receive different files for apps and flows.
The sense to this would be after to see the components affected by the DLP, contact with the owner to advise them.
Thanks, thanks and thanks!!!

**Comment by manuelap-msft** [comment]
Great, thanks for confirming! The button in the app will show a notification to say you'll receive an email and that it might take a bit depending on the size of the tenant. All good for January (finally), thank you for your patience and looking forward to your feedback as you try out the feature!

**Comment by manuelap-msft** [comment]
Here's what the email looks like:
![image](https://user-images.githubusercontent.com/55705669/147746155-8ab98a28-cc82-40d2-ad74-5085b31ba43c.png)

And the two files:
**Impacted Flows** contains Flow Name, Flow Maker Name, Flow Maker eMail, Environment, Connections used in the Flow, Flow ID and Environment ID
![image](https://user-images.githubusercontent.com/55705669/147746168-0627b445-af8a-4a1b-aa5f-dc58325490af.png)

**Impacted Apps** contains App Name, App Owner Name, App Owner eMail, Environment, Connections used in the App, App ID and Environment ID
![image](https://user-images.githubusercontent.com/55705669/147746183-51bff8de-5735-482b-8818-03c2c6190200.png)

The flow is called **DLP Editor>Parse impacted resources into CSV**

**Comment by mikefactorial** [comment]
@albertocaa1317 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
