### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Cloud Flows is failing

### ISSUE THREAD

**Issue by devipriyanka414** [microsoft/coe-starter-kit#8819]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

SYNC HELPER - Cloud Flows is failing for Dynamics 365 customer service or Dynamics 365 customer service related flows
![Sync Helper - Cloud Flows 4](https://github.com/user-attachments/assets/784ff2f3-937b-45dc-9d64-c2de9cf6779e)
![Sync Helper - Cloud Flows 3](https://github.com/user-attachments/assets/c752a3b0-1502-4201-aadd-5d695568effb)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. 

This is an expected and caught failure when the user running the flow does not have permission to the environment it is querying.
![image](https://github.com/user-attachments/assets/787a3f68-6fa7-473a-bef2-a54a4079222e)

You have likely have been impacted by new product behavior that shipped recently around the way the product treats privileged roles (ex Power Platform Admin role, Global Admin role) as that would lead you to not have the correct permissions.

### The product change
Here is information about the product feature: [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)

### How to check if this is the case
1. Validate the user running the flow has direct and permanent assignment to the Power Platform Admin role.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

2. Take one of the target environments in your repro, one of the environments which is failing, and make sure the user running the flow has System Admin security role in that target environment.

### How to address
There is a system to [escalate a user to system admin](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles#self-elevate-to-the-system-administrator-role) in an environment provided by the product team.
Please upgrade to the August 2024 release which has this workaround integrated.

**Comment by Jenefer-Monroe** [comment]
Oh sorry it seems like you changed the bug to a different issue. 
That said, the issue you first posted will prevent you from successfully using the kit so please do explore the above

**Comment by devipriyanka414** [comment]
We are running the flows with the account that has the Power Platform Amin role permanently enabled

**Comment by Jenefer-Monroe** [comment]
Power Platform Admin Role no longer automatically escalates users in environments. This is due to a product change.

### The product change
Here is information about the product feature: [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)

### How to check if this is the case

Take one of the target environments in your repro, one of the environments which is failing, and make sure the user running the flow has System Admin security role in that target environment.

### How to address
There is a system to [escalate a user to system admin](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles#self-elevate-to-the-system-administrator-role) in an environment provided by the product team.
Please upgrade to the August 2024 release which has this workaround integrated.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
