### ISSUE TITLE
[CoE Starter Kit - BUG] New Flows & Apps missing from last 2 weeks

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#8825]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the CoE Admin view new apps and flows are not longer getting loaded into the tables.

### Expected Behavior

I should see new apps & flows practically every day. I have verified with the old style CoE and also with PowerBI against the Admin Analytics export in the Data Lake that there are many new flows and apps in the last 2 weeks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

I verify that the DataFlows are running every day without error, but no new rows appear in the Flows or Apps.

**Comment by Jenefer-Monroe** [comment]
Hello. Have your dataflows in the Core Solution been running and passing?

**Comment by RickKush** [comment]
Yes

From: Jenefer Monroe ***@***.***>
Sent: Monday, August 19, 2024 5:30 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] New Flows & Apps missing from last 2 weeks (Issue #8825)

Hello. Have your dataflows in the Core Solution been running and passing? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <microsoft/coe-starter-kit/issues/8825/2297490422@ github. com>


Hello. Have your dataflows in the Core Solution been running and passing?

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of the dataflows so we can see both their next refresh as well as their last refresh?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b510a94a-4570-4cbd-91c7-4cf3a5274467)

And also a screenshot showing your storage account via the Storage browser. 
Go to apps and sort descending on Last Modified, when was the most recent update to the data here?
![image](https://github.com/user-attachments/assets/e5ea3ce7-8afc-4423-8a73-01177dec690f)

**Comment by RickKush** [comment]
***@***.***

From: Jenefer Monroe ***@***.***>
Sent: Monday, August 19, 2024 9:54 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] New Flows & Apps missing from last 2 weeks (Issue #8825)

Can you please share a screenshot of the dataflows so we can see both their next refresh as well as their last refresh? image. png (view on web) And also a screenshot showing your storage account via the Storage browser. Go to apps and sort descending


Can you please share a screenshot of the dataflows so we can see both their next refresh as well as their last refresh?
image.png (view on web)<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/assets/89584709/b510a94a-4570-4cbd-91c7-4cf3a5274467__;!!May37g!MTKmm4eIHebxCwbY1vg9_3RvfSg9YBaheQDQG8UrJatcaqQWnrRIue9lZJl60cdRqZM3f5ZleHtAYzFXzBhqmRk_7w$>

And also a screenshot showing your storage account via the Storage browser.
Go to apps and sort descending on Last Modified, when was the most recent update to the data here?
image.png (view on web)<https://urldefense.com/v3/__https:/github.com/user-attachments/assets/e5ea3ce7-8afc-4423-8a73-01177dec690f__;!!May37g!MTKmm4eIHebxCwbY1vg9_3RvfSg9YBaheQDQG8UrJatcaqQWnrRIue9lZJl60cdRqZM3f5ZleHtAYzFXzBhRGHBlnA$>

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry screenshots do not come through when you respond in email you must log in to GitHub to share them.

**Comment by RickKush** [comment]
![image](https://github.com/user-attachments/assets/2b507e18-5e74-4583-bc04-7dda226f34cd)

**Comment by RickKush** [comment]
![image](https://github.com/user-attachments/assets/a94a98a2-8613-483f-82d6-3513e1a15c5c)

**Comment by RickKush** [comment]
![image](https://github.com/user-attachments/assets/d250a79e-2960-4491-b86c-0df4dfd22c5f)

**Comment by Jenefer-Monroe** [comment]
You can try to delete the Dataflow run history back a few weeks for all the Dataflows. You can do this in the Command Center
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8316fd00-6ade-4ab9-8381-6b158be58fa2)

And see if that fixes. But if not, unfortunately, we are not currently investing in the BYODL architecture. 

### BYODL sorry
The Data Export product feature that the CoE kit depends on for the BYODL implementation continues to be in public preview which means we've seen very slow adoption of the integration and customers understandably are not taking a dependency on this feature due the preview nature. 

In order to better utilize resources in our team and make sure we invest in the right features, we are pausing investments related to the BYODL architecture and will re-focus our investment here once this feature is GA. We may continue to make small fixes if they are well understood.

In the meantime, you can continue to use the BYODL architecture as-released and make your modifications and extensions to it, or switch to the sync flow architecture. We've recently made big improvements to the sync flow architecture as well, so this is less impacted by throttling and has a much lower API call volume.

**Comment by Jenefer-Monroe** [comment]
Yes you should be able to migrate that data. You can also switch your BYODL CoE into sync flow just by runing the setup wizard and chosing the other option.

Also, as a heads up, Data Export V2 is in progress and we hope to have something available this fall.

**Comment by RickKush** [comment]
But the byodl data is incomplete. Is there any assistance to update from 4.11 to 4.13. 4.11 can't be deleted because it has depencencies.

**Comment by RickKush** [comment]
This same dependency occurrs 13 times with the same ObjectName and different Id's:

![image](https://github.com/user-attachments/assets/b63682f3-6513-4e03-8b0d-21add7b909b9)

**Comment by Jenefer-Monroe** [comment]
You are on the July 2023 version of the kit from before we deprecated the custom connector we used to use for Audit Logs. 

Please see https://github.com/microsoft/coe-starter-kit/issues/6018

We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 
You will need to follow the steps outlined in https://github.com/microsoft/coe-starter-kit/issues/6018 in order to proceed. 
In short:
1.	Delete _upgrade
2.	Delete Audit Logs solution and any other dependencies
3.	Try your upgrade of Core again
4.	Setup new Audit Logs collection technique
These are explained more deeply in the referenced bug.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
