### ISSUE TITLE
[CoE Starter Kit - BUG] Error updating core version

### ISSUE THREAD

**Issue by renrous** [microsoft/coe-starter-kit#8848]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When trying to upgrade from version 4.33 to 4.37 I receive the following error Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Cannot delete attribute: admin_customizedemailid from Entity: admin_CustomizedEmail since the attribute is not a custom fields

![image](https://github.com/user-attachments/assets/5575a4f6-1626-4fbe-b752-65a7fae77b67)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Upgrade

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
This is the second issue like this. People are getting an error on upgrade about a field that still exists.
See https://github.com/microsoft/coe-starter-kit/issues/8831

Unfortunately I cannot assist as this is a product issue. It would be great if you could create a support ticket. 
In the meantime you can update instead of upgrade and you should be fine.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by shmcarth** [comment]
There was a regression in the solution framework that is fixed. It will be completed rollout worldwide by this weekend. Please retry.
