### ISSUE TITLE
[CoE Starter Kit - BUG] Environments missing from the "Power Platform Admin View" app

### ISSUE THREAD

**Issue by nrd2015** [microsoft/coe-starter-kit#8853]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The "Power Platform Admin View" app does not list all the environments in the tenant. It is missing few sandbox and production environments.

### Expected Behavior

All the tenant environments should be shown in the "Power Platform Admin View" app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

No error in flows

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello likely you have been impacted by new product behavior that shipped recently around the way the product treats privileged roles (ex Power Platform Admin role, Global Admin role)

## The product change
Here is information about the product feature: [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)
In short, the privileged roles no longer grant you permissions to individual environments.

## How to check if this is the case
1. Validate the user running the flow has direct and permanent assignment to the Power Platform Admin role.
Note that this is still required in order to perform the workaround, but is no longer sufficient.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

2. Take one of the target environments in your repro, one of the environments which is failing, and make sure the user running the flow has System Admin security role in that target environment.

## How to address
There is a system to [escalate a user to system admin](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles#self-elevate-to-the-system-administrator-role) in an environment provided by the product team.
Please upgrade to the August 2024 (4.37) release or greater which has this workaround integrated.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
