### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Report doesn´t show Custom Connector Usage in Apps or Flows

### ISSUE THREAD

**Issue by VolkerSteltenkamp** [microsoft/coe-starter-kit#8855]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Neither in the Production-COEDashboard_August2024 nor in the BYDOL_CoE_Dashboard August 2024 (we´re using the BYODL audit log and in addition the AuditLog V3 Solution) there is information about the Usage in Apps or Flows:
![image](https://github.com/user-attachments/assets/3a231d53-9ddc-437d-afca-1d51bede4a04)

### Expected Behavior

There should be a list which shows where the Custom connector is used, either in an App or a Flow or both

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Power BI Report

### What method are you using to get inventory and telemetry?

Data Export

### Anything else?

Seems that we don´t have any information on any Connector usage:
![image](https://github.com/user-attachments/assets/c55ae130-1ac8-4ddf-9eac-9e16bef436e3)

**Comment by Jenefer-Monroe** [comment]
I dont repro this. Please look to see if you have the report filtered accidently, and refresh the data source.
![image](https://github.com/user-attachments/assets/e2b132f4-a02d-41e9-81b1-537bb7ddecb6)

So this is likely an issue specific to the BYODL architecture. 
Note that we are no longer making fixes in the BYODL side of the kit as the new Data Export system we are preparing to ship this autumn with the product team does not use the datalake any longer. So that is where all our Data Export efforts are focused.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
