### ISSUE TITLE
[CoE Starter Kit - QUESTION] Need guidance on removing CoE entirely so we can start from scratch

### ISSUE THREAD

**Issue by utmikestanley** [microsoft/coe-starter-kit#8859]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

A previous employee installed many components of the CoE into a separate environment within our Power Platform tenant at the University of Tennessee. We have no documentation on the choices he made and would like to completely remove the CoE from that environment, possibly delete the environment if that will not cause any issues with our many other environments, then setup a new environment for the CoE and install a component of it at a time, test and configure it, and keep going until we have it setup to meet our needs.

I realize Microsoft may not support the using the kit, but what we're seeking is core Power Platform guidance on the best way to remove the currently installed CoE. I am ok with downloading and installing it fresh myself, although if you can point me to a best practice document to follow, I'd appreciate it.

Thanks for your time!

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
If you can start a brand new environment without much issue, that would be great. 
Are you in a sovereign cloud? Or are you commercial? 

## If you are Sovereign
If you are sovereign, then you will need to install the May version of the kit while we await a connector to be resolved.
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2024
And that will mean manually adding your user to environments as sys admin due to https://github.com/microsoft/coe-starter-kit/issues/8016
August release has this resolved by via a connect that should be fixed in sovereign clouds soon. 

Alternatively you can monitor this bug and wait for it to be resolved before doing the setup, and setting up with August release where this is resolved. 
Issue blocking sovereign cloud: https://github.com/microsoft/coe-starter-kit/issues/8835

**Comment by utmikestanley** [comment]
We're US higher education, so definitely not sovereign.  I can create a brand new environment no problem. If I do that, would you recommend deleting the current environment in which the CoE is installed, or should I wait until after I've installed the latest version into the new environment?

Appreciate your help!

**Comment by utmikestanley** [comment]
Thanks so much @Jenefer!
