### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Admin Command Center - Flows Page

### ISSUE THREAD

**Issue by LucasCXavier** [microsoft/coe-starter-kit#8871]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer, hope you are doing well!

We'd like to implement something similar to what we have in the 'CoE Flows' tab of the Command Center:

![image](https://github.com/user-attachments/assets/2217204b-5517-48a6-a9cf-61cce145f6a5)

The goal is to monitor the cloud flows in one of our Production environments.

I would really appreciate any advice you could offer.

Thanks in advance,
Lucas 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2024

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I duplicated this for another project for myself as well. 

Basically this uses the metadata table that you see here: **_CoE Solution Metadata_**
Which we fill on release by this flow: **_Admin | Sync Template v3 CoE Solution Metadata_**
Not shipped to you is how we get the json to fill this flow's json objects 
![image](https://github.com/user-attachments/assets/45b3dc63-8c0a-4588-b80b-460d2a1409b4)

Basically we have a spreadsheet called solution metadata that we store the tabular view of all the objects in the kit, unfortunately this is filled manually. 
![image](https://github.com/user-attachments/assets/9a1ce20c-dbff-408a-b67e-ba193fe5c403)

Then we have a flow that reads that and creates json in the format needed for the table
![image](https://github.com/user-attachments/assets/d9caacea-5127-42e5-8a55-6a58478460df)

In the app itself, the CoE version is slow to load because we have to worry about unpublished flows but you could remove that complexity since you aren't trying to simulate and ISV style delivery. That will make the page much faster to load. 

I hope that helps!

**Comment by LucasCXavier** [comment]
Thanks so much Jenefer.
