### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned Flows not syncing with the CoE report

### ISSUE THREAD

**Issue by PPTechy** [microsoft/coe-starter-kit#8878]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

I have fixed the orphaned flow user using the manage permissions CoE tool, but still I am getting the email about the Orphaned flow. Orphaned flows how often it synced with the CoE orphaned flow report? Which flow is responsible to sync the orphaned flow? 

Hi @Jenefer-Monroe - Could you please help me on this. I had mixed this question with my deleted flows post, but separating it from there for more focused discussion.

Thank you!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Orphaned Flow Sync

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I think we'll have to take a single instance to debug.

What mail are you getting? That will help us deduce where in the flow you are being pinged.

1. Find one of the flows you do not expect to see getting to you from the orphan flow because you re-assigned it, and find it in 
the Power Platform Admin View
- Is it shown as deleted?
- Is it shown as orphan? 
- Is the correct person shown as derived owner? 

2. Find one of the flows you do not expect to see getting to you from the orphan flow because you deleted it, and find it in the Power Platform Admin View
- Is it shown as deleted?

**Comment by PPTechy** [comment]
Hi @Jenefer-Monroe, Thank you so much. Please keep this thread open for the next couple of days, will update you the behavior. then we can close this.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
