### ISSUE TITLE
Developer Compliance Center - Unable to share the App to Everyone

### ISSUE THREAD

**Issue by Harishkumargilead** [microsoft/coe-starter-kit#8912]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Center of Excellence - Governance Components

I am unable to share the Developer Compliance Center app with everyone in the organization. For some people, even if the app is shared, it is stuck on loading and they are unable to update their information in the compliance app.

The CoE Toolkit version installed is 4.17.

### Expected Behavior

Our Existing On-boarding customized app was a canvas app and we are able to share the app to everyone 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Environment - Center of Excellence_Development and Center of Excellence-Production

In both environments, we are trying to share the Developer Compliance Center.

Select any one environment -> go to Solutions -> Center of Excellence - Governance Components -> Apps -> Developer Compliance Center App. I am unable to see everyone in the organization here, whereas, in the same solution, I can see them in the Cleanup Old Objects app.

As an alternative, I tried adding a security group that includes everyone in the organization (30,000 members). However, even after adding the group, many users are still unable to access the app.

I provided the Power Platform User SR Role and tried both the User SR and System Customizer roles, but the issue persists; users are still unable to update the information.

**Comment by Jenefer-Monroe** [comment]
Yes I think that "everyone" concept is a concept only for Canvas type apps. To my knowledge Model Driven Apps do not have such a capability.  

Here is a product write up on how to [Share MDAs](https://learn.microsoft.com/power-apps/maker/model-driven-apps/share-model-driven-app)

And here is a write up we did as well

## How to share a MDA
In order to share a MDA with users you first need to share the app as a whole with the desired security roles
Share the app as a whole with the Security Role
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3d532a9-92f5-4765-aeef-a9e171f19a46)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5377d117-c406-4293-bd3b-1c966f1569a8)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c9d7d6a-5e3e-4dab-b8d9-9749fcadaa15)
Now that SR can be applied to users you share the app with.
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f8976c2-b594-43da-b56c-fa4932fd7400)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
