### ISSUE TITLE
[CoE Starter Kit - QUESTION] Where are Flow details page links stored?

### ISSUE THREAD

**Issue by LucasCXavier** [microsoft/coe-starter-kit#8917]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer, hope you are doing well!

I was checking enhancement (#6793) and wanted to ask which table the Flow links are being stored in.

Also, I've noticed that the default environment flows are not being displayed due to a missing 'Default-' prefix in the URL. Could you please advise on the best way to correct this?

Thank you in advance for your assistance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2024

### What app or flow are you having the issue with?

CoE Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello we do not store this its generated in the transform layer of the PBI itself as shown here. 
Thanks for posting this issue, the issue is at the spot highlighted. I'll need to add the name in and put it there. 
I'll fix this up in an upcoming release. 

![image](https://github.com/user-attachments/assets/e5850383-e89a-4ad5-aea0-aa2a665db779)

**Comment by LucasCXavier** [comment]
Got it. Thank you :)

**Comment by Jenefer-Monroe** [comment]
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2024
