### ISSUE TITLE
Admin | Audit Logs | Sync Audit Logs (V2) > Get Logs > Get Azure Secret

### ISSUE THREAD

**Issue by Graya17** [microsoft/coe-starter-kit#8923]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to run the **Admin | Audit Logs | Sync Audit Logs (V2)** flow in the CoE but it fails at step **_Get Logs > Get Azure Secret_**.
We are not using the key vault and according to the documentation (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables) this should be left blank if you're storing your client ID in plain text in the **_Audit Logs - Client Secret_** environment variable, which we are.

All help would be much appreciated.

![image](https://github.com/user-attachments/assets/1978ae8c-b585-49a7-bfeb-271c756c5c0d)

**Error:** 
{
  "error": {
    "code": "0x80040216",
    "message": "Error occured while reading secret: Value cannot be null.\r\nParameter name: input"
  }
}

### Expected Behavior

As we have the client Id and secret already in the related flows we would expect this flow to run successfully assuming all steps have been taken correctly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Got to CoE environment, 2. Find flow Admin | Audit Logs | Sync Audit Logs (V2) 3. Run Flow

### Anything else?

N/A

**Comment by Jenefer-Monroe** [comment]
Hello this is a caught failure indicating you have stored your secret as plain text and thus setting the variable here to indicate that. 
![image](https://github.com/user-attachments/assets/0a0f62c7-5209-4a73-9898-19b980403282)

You will need to find the terminating (uncaught) failure below. 
Below is some text we wrote up to help with this idea.

## Find terminating failure
Please note that failures like this are caught/expected failures. 
We use these calls to see if the object is new to the inventory, and if it is, this call to “get it” will fail. This failure is caught and the “isnew” variable is set to true. 
![image](https://user-images.githubusercontent.com/89584709/225679681-01467de5-1a1c-4c93-bf57-71296f5ea83b.png)
In order to debug you need to find the terminating failure in the flow. Here for example the call to “forced failure” failed, and was not caught, so the flow terminated here. That is the spot you need to find in your failure in order to debug. 
![image](https://user-images.githubusercontent.com/89584709/225681214-a5549790-32e9-482e-b427-0c346aa50684.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
