### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflows remain Off after using setupwizard

### ISSUE THREAD

**Issue by TammoJ-S** [microsoft/coe-starter-kit#8927]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Using the CoE SetupWizard step 7 (Configure dataflows (Data export)), "Configure connections to your datasources in dataflows", i can succesfully configure every CoE BYODL dataflow. I can succesfully configure the daily refresh of CoE BYODL Makers dataflow.
However, only the daily CoE BYODL Makers dataflow appears to update, all other dataflows do not update.
![image](https://github.com/user-attachments/assets/c7966bf7-505d-4795-af1d-65a48095fe5a)

Looking at the dataflows, they are not modified and are turned off.
![dataflows_censored](https://github.com/user-attachments/assets/cca4c319-92e4-4042-9bff-4fb7f860d4d0)

How can i start these dataflows succesfully?

### Expected Behavior

I expect all dataflows to be turned on.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

All dataflows

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Create a new environment,
2. Setup CoE Core components,
3. Run Setupwizard,
4. Configure dataflows

**Comment by Jenefer-Monroe** [comment]
Hello the BYODL architecture for Data Export is no longer the plan of record for Data Export. We are actively working with the product team on the new architecture that will rely on Fabric instead of the Data Lake and hope to preview it to the community in fall of 2024.

As a result we are no longer suggesting new users attempt to setup BYODL as the pain of configuration is not something that will benefit you when the new version comes out, and issues that remain in BYODL are not being addressed. 

That said, I can share with you the stored write ups we have for when people saw issues like the above in the past, but again it is not something that we recommend you pursue at this point.

**Comment by TammoJ-S** [comment]
I understand the move to fabric and the move away from dataflows and data lake, which, for me, results in a status quo where i don't have any solution. I don't mind waiting for the fabric solution but i would like to see the dataflows refresh so i can start working on designing security and dlp policies and alike. Could you share the info you have with me so i can try to get it up and running? I'll not be deploying other CoE solution until the fabric solution is released.

**Comment by Jenefer-Monroe** [comment]
Below is what was usually the issue with the triggers not working

### For this trigger issue:
Triggers for dataflows use some strange string for their "Group" that gets set up wrong sometimes and has even changed for me in the past. 
If you open one of the recent runs for the **_on complete flows_** you can see what its using for "Current Environment" environment variable
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bee54b30-88e5-4811-907a-a79d4e61e925)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/80e8311f-614e-4dda-9aa9-de031c0a50a0)
If it looks like a GUID, its wrong. And if it looks correct, it still might be wrong due to it changing. Please do the below to resolve.
### Get the correct value for Group
Open the following flow in edit mode and expand the trigger, select your coe envt and the Maker Dataflow. 
Save, close and turn it on
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/388da23c-e8fe-4aac-b0d5-df4abd6b6beb)
Run the Maker dataflow and when its done, this flow should run. You can see what the string should be now by looking at the run history. Remember also to turn this helper flow off now as you don’t need it anymore.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c34607d8-6e08-439d-a076-2e822a5e0d00)
This flow is supposed to update the env var but sometimes it fails. 
### Update Env Var
To ensure the env var is updated please go to the command center and update the env var to that group string that was used. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cb03f056-4b00-460c-9fa7-f5675351e7f1)
Then turn all the "on complete" flows for the dataflows off and back on to ensure the new env var is used
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f2acd229-76d6-444f-bf19-b41def19b04c)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
