### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to remove Core Components previous version

### ISSUE THREAD

**Issue by Ace0751** [microsoft/coe-starter-kit#8947]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Our team has updated to the July CoE a few weeks back but we are having trouble trying to remove the previous version of the CoE core components.  When were trying to remove the core components manually, we receive an error message saying it failed as there is a dependency.  The dependency is the PowerApps App(total shared) and when digging into the solution layers, there are no unmanaged layers just the centerofexcellencecorecomponents solution.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Solution

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
This is a field that was removed from the kit and replaced with another. It sounds like you may have taken a local dependency on it. 

Go to the default solution > Tables > PowerApps App > columns > Find the total shared colunn > look at its dependencies. 
Here is how to do that for another field since I dont hvae total shared anymore

![image](https://github.com/user-attachments/assets/4bfb9628-f5e7-4fed-bfef-7a54eb4b0a22)

**Comment by Ace0751** [comment]
Thanks, we will evaluate this in the morning and see if we can get the older solution removed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
