### ISSUE TITLE
[CoE Starter Kit - BUG] App Shared w/ Guest Users not populating; Shared Users & Shared Tenant have bad data

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#8957]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am looking at PowerApps Apps in the Admin View, filtered for App Shared with Tenant. Our tenant has over 55,000 user accounts including 20,000 external guests. I checked a couple and they were not actually shared with Tenant. The App Shared Users counts were all under 100. And the App Shared Guests were all empty. These same fields in the BYODL version were all accurate.

### Expected Behavior

Accurate info.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Look at PowerApps Apps in the Admin View, filter for App Shared with Tenant, verify data.

### Anything else?

![image](https://github.com/user-attachments/assets/2ad34442-0aac-4598-9407-f4ec2088f38a)
This one is not shared with Tenant.

**Comment by RickKush** [comment]
This is from the BYODL. Note the App Shared Users counts:
![image](https://github.com/user-attachments/assets/f7168c7c-293e-49e3-b24d-7bd33bb4ff00)

**Comment by RickKush** [comment]
![image](https://github.com/user-attachments/assets/5662805e-c91c-4e57-b88f-88cd359839e1)

![image](https://github.com/user-attachments/assets/bebf358f-aa3c-409d-b7ee-1a69554c399e)

**Comment by Jenefer-Monroe** [comment]
Sorry having a little trouble following. Note that BYODL and Cloud Flows both use the same system for this. 

The flow that fills this are the following. Please make sure you dont have unmanaged layers and then run the parent flow. Since it only runs every two weeks due to API impact, it may be stale. 

- CLEANUP - Admin | Sync Template v3 (App Shared With)
- CLEANUP HELPER - Power Apps User Shared With

Then if you still have repros plese return with them either one at at time or labeled so that I can tell which is which (ie this is the "shared with tenant repro")

**Comment by RickKush** [comment]
The HELPER wasn't even turned on. It ran for under 4 hours and everything looks good now. Thanx!!!

**Comment by RickKush** [comment]
The HELPER wasn't even turned on. It ran for under 4 hours and everything looks good now. Thanx!!!
