### ISSUE TITLE
[CoE Starter Kit - BUG] Disabled flows wrongly marked as deleted 

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/coe-starter-kit#8963]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I was surprised to see a dramatic reduction in flows after I upgraded to core 4.37 and ran the inventory flows. It turned out to be the filters in the Power Platform view that did not display flows wrongly marked as deleted. Seems like the inventory is marking disabled flows as deleted.

For one environment when I check PPAC we have 4 enabled flows made by us and 3 disabled ones installed by Microsoft (flows like 'Integrated Search API trigger flow'). In the default Active flows view we only see the 4 enabled ones as the three others have 'Flow deleted' set to 'Yes'. In the old CoE version all 7 flows have Flow deleted = 'No' 

PPAC:
![image](https://github.com/user-attachments/assets/7afd290a-8489-4a66-b2d7-b7daad336cea)

CoE Admin view app
![image](https://github.com/user-attachments/assets/ce4cc142-d3a2-4dd5-bf07-5e5445017410)

### Expected Behavior

Disabled/Not started flows should be marked as Flow Deleted = No

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Install core 4.37, setup inventory flows, run full inventory, check delete status of disabled flows

**Comment by Jenefer-Monroe** [comment]
The kit does not collect disabled flows. Meaning flows installed in solutions but never turned on. I call these "unpublished" flows in the kit. 

The kit **_does_** inventory flows that are turned off but which were previously on. 

Please let me know which situation you are referencing. Flows that are "unpublished" or just any flow that is turned off. I'll presume you mean unpublished for now. 

If so, then this is by design, please see [our limitations](https://learn.microsoft.com/power-platform/guidance/coe/limitations#flows-that-dont-get-activated). There was one build which shipped (I don't remember which build) that accidently inventoried these. And later builds will clean them up. 

The reason we cannot inventory them is that the GUID is fluid and so any metadata you put on that record will get lost.

**Comment by HenningStrand** [comment]
Thanks for quick reply. So what you are saying is that if we had the old version that actually inventoried these flows that have never been published, then the new version will not find them and mark them as deleted?

**Comment by HenningStrand** [comment]
Thx. I tried a clean install of 4.37 in a new env. There I indeed got no flows marked deleted = yes and the same total number of flows as in the upgrade was marked deleted = no. Thanks for the explanation. Can close this one

**Comment by Jenefer-Monroe** [comment]
You are welcome, thanks for using CoE!
