### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to enable inventoring new environments created after CoE installation

### ISSUE THREAD

**Issue by malaker** [microsoft/coe-starter-kit#8999]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

1. New environments were created outside of the built in environment creation process in CoE.
2. I can't find out why new environments created after CoE is installed are not inventoried. I checked Admin Sync flows but majority of them relying on add or modify event of admin_environment record. 
3. What flow syncs environments ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin - Sync Template

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello likely you have been impacted by new product behavior that shipped recently around the way the product treats privileged roles (ex Power Platform Admin role, Global Admin role)

## The product change
Here is information about the product feature: [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)
In short, the privileged roles no longer grant you permissions to individual environments.

## How to check if this is the case
1. Validate the user running the flow has direct and permanent assignment to the Power Platform Admin role.
Note that this is still required in order to perform the workaround, but is no longer sufficient.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

2. Take one of the target environments in your repro, one of the environments which is failing, and make sure the user running the flow has System Admin security role in that target environment.

## How to address
There is a system to [escalate a user to system admin](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles#self-elevate-to-the-system-administrator-role) in an environment provided by the product team.
Please upgrade to the August 2024 (4.37) release or greater which has this workaround integrated.

**Comment by Jenefer-Monroe** [comment]
It appears you are already on August so please do the following:

Share a screenshot like this so we can see what solutions you have installed in this environment? 
Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

Then go to the Admin Command Center > CoE Flows > Inventory. 
Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

Then see if there are any sync flow errors to investigate. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d43b50b3-84d1-4894-a9a3-04d5d95fe8dc)

**Comment by malaker** [comment]
Thanks, indeed the running flows user has to be Power Platform Admin. After assigning this role, in next day all other environments were added.
