### ISSUE TITLE
[CoE Starter Kit - what was alternate flow created for CLEANUP - Admin | Sync Template v3 (Connection Status) in latest versions

### ISSUE THREAD

**Issue by Vignes29** [microsoft/coe-starter-kit#9008]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I would like to know which flow does the CLEANUP - Admin | Sync Template v3 (Connection Status) job as this flow is not available in latest version. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Connection Status)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid I don't remember a flow with that name. Can you please let me know what it did? And I'll let you know what we have.

**Comment by Vignes29** [comment]
"This flow runs weekly, and checks if any apps or flows have unresolved connections" this is the description I found in that flow. Mark the tables Flows and PowerApps Apps column **Reinventory App Contains Broken Connections** as Yes or No

**Comment by Jenefer-Monroe** [comment]
That field holds when an app or flow's connection is not found in inventory. This happens when the following occurs for example

1. New connector **Get-X-Stuff** released (not in inventory as we only collect connectors weekly)
2. Someone uses it in an app **My-App**
3. The next day **My-App** is inventoried but **Get-X-Stuff** is not found yet so the app is marked as needing to be re-inventoried till that is resolved
4. Later that week the connector flow runs and **Get-X-Stuff** connector is now in CoE inventory
5. **My-App** is seen as needing inventoried due to the Reinventory App Contains Broken Connections being Yes
6. Finally all is resolved. 

So this happens inline in the regular sync flows for apps and flows.

**Comment by Vignes29** [comment]
Got it, So I can remove this flow from my solution and there won't be any impact in tables or any flows in core components.
And do we have any flows that does this job as this flow is not part of the latest versions

**Comment by Jenefer-Monroe** [comment]
That flow does not exist for me so its not needed for the kit to run OOB.

This action is done inline in the sync flows: 
- Admin | Sync Template v4 (Flows)
- Admin | Sync Template v4 (Apps)

I would suggest you please validate that you have all the inventory flows turned on just to be sure you are current. You can do this by booting and running the setup wizard, and then looking in the command center to validate. 
Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)
