### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Starter Kit - Inactivity Notifications: Set interval beetween two dates in the past

### ISSUE THREAD

**Issue by lucasubieta** [microsoft/coe-starter-kit#9026]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi there, I’m trying to set the "admin | Inactivity notification v2 (Start Approval for Apps)" and "admin | Inactivity notification v2 (Start Approval for Flows)" interval to only cover the year 2023, so between January 1, 2023, and December 31, 2023.

I cannot find a way to do this since the environment variable only allows setting the time from now to the past.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

July 2024

### What app or flow are you having the issue with?

Admin | Inactivity notification v2 (Start Approval for X)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Yes we don't have that functionality built in. You would have to update the env var between runs to do this, or try one of the other local changes to your flow below. If you update the env var, be sure to restart these flows so that they do not use a cached value. 

If you only care about nothing this year you could do something like this, it would get 2022,2023,...
![image](https://github.com/user-attachments/assets/1e03c96b-b1b2-4c2c-9422-d3d30f930c86)

If you really want 2023 only I think you'll need to add a filter:
![image](https://github.com/user-attachments/assets/5267af30-a1aa-4fd5-800d-316c1d3db706)

I hope that helps!
