### ISSUE TITLE
Accidentally deleting the spatial services connector in Delete Bad Data flow

### ISSUE THREAD

**Issue by PiZe0** [microsoft/coe-starter-kit#9043]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am System Administrator and Power Platform Administrator, and I’m encountering an issue with an app that uses the "Spatial Services" connector. This is causing an error in the Sync-HELPER - Apps Flow within the CoE Toolkit. The flow fails at the step where it inventories all connection references of the specific App. Specifically, the "Spatial Services" connector does not have an associated "App ID".

I have manually searched for the corresponding row in the relevant table but was unable to locate it—the row appears not to exist.

![image](https://github.com/user-attachments/assets/50e845e8-e320-49e6-967d-1a8659a17dcd)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by PiZe0** [comment]
Additionally - i cannot find the "microsoft spatial services" connector in the table "admin_connector" in the CoE toolkit. Maybe that's why there is no "connector id".  Attached you can see, the "office 365 users" connector has an "admin_connector_value", while the spatial services does not.

![image](https://github.com/user-attachments/assets/39b7c4c5-f367-42f5-b824-79b8dbb941bb)

**Comment by PiZe0** [comment]
I have to clarify this :-).

The flow "SYNC HELPER - Apps" which is within CoE Toolkit is throwing an error when it is trying to inventory an App. More specific, when it is trying to inventory the connection references of the App. And the connection reference of the "spatial services" connector which is used inside this app does not have an connector id. And i can't find this connector inside the CoE toolkit or the related "Connector" tables inside CoE.

**Comment by PiZe0** [comment]
Maybe could you check if you have "Microsofr Spatial Services" connector in the connector table?

**Comment by Jenefer-Monroe** [comment]
Got it. OK yes we did fix a bug with this connector recently so an upgrade should fix it for you. 

You can check locally before hand though. I can't find the issue but I'll just paste the solution here. 
If you open the following flow: Admin | Sync Template v3 (Connectors)
You shoudl see this section "Specialty Connectors" and Spatial Services is in there. I dont recall where the bug was but I think it was with the name somewhere. Here are the actions can you please compare? 

![image](https://github.com/user-attachments/assets/94aa36a5-1c7a-4190-b32e-94a5f86cbf83)
![image](https://github.com/user-attachments/assets/66a2566b-c08c-413c-91c4-8e1b1219a476)
![image](https://github.com/user-attachments/assets/2a480853-fe7c-4ed3-9063-f4d5e1443649)
![image](https://github.com/user-attachments/assets/6cf46ce9-3932-4b92-9496-8206c72250af)

**Comment by PiZe0** [comment]
I checked the flow and the action "Add MicrosoftSpatialServices" was marked as succeeded - but it didn't add the connector. I turned off the flow and turned it on again -> it worked ! I have a wild guess, because we renamed the environment URL where the CoE toolkit is installed a few weeks ago. Maybe that's why :-)!

**Comment by Jenefer-Monroe** [comment]
Aww yes thats what it is. Sometimes flows cache env urls and flows need to be reset for them to work properly. 
So glad we got this resolved!

**Comment by PiZe0** [comment]
Unfortunately ... we got the error back. I looked at the audit history.. and it got deleted again. I wonder if any CoE flow does this?

![image](https://github.com/user-attachments/assets/78a46564-53b6-4b8c-8150-eb509b056804)

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
