### ISSUE TITLE
[CoE Starter Kit - QUESTION] One year without updating CoE Starter Kit, what is the best aproach?

### ISSUE THREAD

**Issue by ivannribeiro** [microsoft/coe-starter-kit#9047]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Have been one year that I dont update de CoE Starter KIt. I'm in the CoreComponent version 4.16.  
Should I try to update to the latest version? 
Or maybe try to update some intermedian versions first, before going to the September 24?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.16

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately I dont know if I have good advice for you here. You can certainly try a direct upgrade. If it fails it would leave an _upgrade that you can delete. Below is some information about that. 
The real issue is that I don't remember the state of the kit then so I can't advise about what you might see. 

## Two Solutions!
When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 
These will never converge or repair on their own, you will need to take action to resolve as a result. And until you do, you are in an unknown state.
If you go to history you may find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)
And if you don’t, then you should delete the _upgrade. And try to upgrade again to see either if it succeeds this time, or if you see the error message this time.

**Comment by djtrustgod** [comment]
Hi.   In the last few weeks we went from September 2023 (4.15) to August 2024 (4.15) skipping tow releases at a time.  We are only running core at this time and are using Flows, not Data Lake.  Before we could go beyond Feb 2024 (4.23)  this was our biggest issue:  [https://github.com/microsoft/coe-starter-kit/issues/8466](https://github.com/microsoft/coe-starter-kit/issues/8466).  Hope this helps, but it is possible.

**Comment by Jenefer-Monroe** [comment]
Thanks for sharing your experience @djtrustgod
