### ISSUE TITLE
ChildFlowNeverPublished error when turning on 'Admin | Sync Template v4 (Driver)' Flow

### ISSUE THREAD

**Issue by harsh-mehra-db** [microsoft/coe-starter-kit#9075]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are getting the below error when trying to turn on the 'Admin | Sync Template v4 (Driver)'  flow due to which the sync flows are also not working. Can you please help on this.

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id '[GUID]' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello likely this is due to the following child flow: **_HELPER - Driver Escalation Check_**
Please go turn that on and then Driver should be able to be turned on. 

Also note that if you boot the setup wizard after each upgrade then new flows like this should be enabled for you. 
Please let me know if the Driver flow was off for very long as you may need to go patch up the inventory if it was.

**Comment by harsh-mehra-db** [comment]
Yep, even I found the same just now. It's turned on now. 

Thanks for the response.
