### ISSUE TITLE
[CoE Starter Kit - Feature]: CoE to run only using Service Principle instead of service account

### ISSUE THREAD

**Issue by McBaz** [microsoft/coe-starter-kit#9102]
### Is your feature request related to a problem? Please describe.

Hi, due to security reason. Recently my org is pushing to remove power platform admin right from the service account running CoE.

### Describe the solution you'd like

I think the only alternative is to allow CoE to run on and only on custom connectors using service principle.
Hope this can be considered, this should have other orgs to greatly enhance their system from a security stand point.

**Comment by Jenefer-Monroe** [comment]
Hello. We cannot use Service Principles to run the kit yes as not all the connectors we use can rely on it. And we are just not staffed to shift the whole kit over to using CC unfortunately. 

I believe the product team is working to make Dataverse work via Service Principle and at that point the kit should work for them. 

Sorry I dont have better news for you.

**Comment by McBaz** [comment]
Hi @Jenefer-Monroe  thanks for the quick response.
Are you able to advise if there can be other alternative that does not require power platform admin right allocated to the service account?

**Comment by McBaz** [comment]
How about giving the service account system admin right to every environment and take away the power platform admin privilege? Will the CoE continue to run?

**Comment by Jenefer-Monroe** [comment]
Unfortunately not. 

Some objects (ex Canvas Apps, Cloud Flows) have connectors that we use to gather inventory. These therefore require the Power Platform Admin Role as that is what is checked when you call the connector

Other objects (ex Model Driven Apps, Desktop Flows) do not have a connector and hence need to dip into the product tables in each environment in order to gather inventory. 

Further as new environments appear in your tenant, the Power Platform Admin Role (or higher) is required to successfully grant yourself System Admin permissions in those environments.
