### ISSUE TITLE
[CoE Starter Kit - BUG] Cleanup flow running too many actions

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#9106]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I'm getting the following message for the CLEANUP HELPER - Cloud Flow User Shared With flow in the COE production environment:

"Your flow is executing an excessive number of actions per day and reached 80% of the Power Platform request limit. If the usage grows, further actions may be throttled or slowed down."

I've never seen this message in production before; how can I resolve this issue?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CLEANUP HELPER - Cloud Flow User Shared With

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. This flow will be long running as it touches every flow in the tenant. Its already been streamlined as much as possible according to all the reviews we have one (open to feedback though if you have ideas). The first run will be longest as it is filling all the entries for the first time and future runs will be less, though still api intensive

So here are your options
1. Turn off the parent flow **_(CLEANUP - Admin | Sync Template v3 (Flow Shared With))_** and wait till all these children complete, then turn parent back on to see if it runs with few enough calls next time
2. Change the cadence of the flow to run less often. Change **_CLEANUP - Admin | Sync Template v3 (Flow Shared With)_** recurrence trigger to be monthly instead of every two weeks
![Image](https://github.com/user-attachments/assets/7e2d73c2-96c8-4c06-b474-5aece4c27cd1)
3. Turn off completely and just not collect information about who a flow is shared with
4. Add a [process license](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/deep-dive-on-specific-license#power-automate-process-license) so that the flow has its own larger pool of API calls to pull from.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
