### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin|Add Maker to Group - Insuff. Privileges

### ISSUE THREAD

**Issue by lucasubieta** [microsoft/coe-starter-kit#9126]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi there!,

I’m seeking a bit of help with a flow. It seems that my user doesn’t have the necessary privileges to add a new team member. I initially thought these permissions were granted when I registered the Microsoft 365 app in Azure.

Could this issue be related to my user's permissions, or does it seem more like a tenant-level restriction?
Should I check the user privileges in Entra ID ?

Thanks a lot i really appreciate the support you provide.

![Image](https://github.com/user-attachments/assets/71126e23-5992-4b0d-a251-48c86ed844b6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 24

### What app or flow are you having the issue with?

Admin | Add Maker to Group

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. No problem this is a common issue so easy to assist. 
The identity running the flow needs to be an owner of the group in order to add users to it. 
Please see [How to communicate with your admins, makers, and users](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-to-communicate-with-your-admins-makers-and-users)
![Image](https://github.com/user-attachments/assets/6dab878d-9a01-43cc-9d9b-401b5f260e8a)
