### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cross-tenant connections showing incorrect values

### ISSUE THREAD

**Issue by zellos13** [microsoft/coe-starter-kit#9135]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi,

In CoE there is an environment variable called "Host Domains". I've configured it so it should update Cross-tenant connections for our tenant.

![Image](https://github.com/user-attachments/assets/4855c270-20ee-413e-9f6e-b62fcd3b54dc)

![Image](https://github.com/user-attachments/assets/5e91bd08-5558-48e2-b85e-93e82cd7f382)

Unfortunately, this report marks all connections as cross-tenant. Could you please help me investigate what must be configured for this report to show correct data?

I've checked: [#6216](https://github.com/microsoft/coe-starter-kit/issues/6216) and [#3506](https://github.com/microsoft/coe-starter-kit/issues/3506) issues and I still don't know what I did wrong.

Cheers!

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Core Components 4.31

### What method are you using to get inventory and telemetry?

None

**Comment by Harry-AU** [comment]
Hi @Jenefer-Monroe  To update the old data for Cross-tenant connections for our tenant after changing the variable, 
Can we directly edit the Dataverse table by going to Connection Reference Identity table in solutions instead of doing this excel add in thing?
I was able to do it but not sure its the right thing to do
We have 4.47.1 COE toolkit version installed 
Thanks,
Harry.
