### ISSUE TITLE
[CoE Starter Kit - BUG] Data Policy Impact analysis app crashes on start (AppMetadataFetchFailed)

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/coe-starter-kit#9141]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Trying to open the app for the first time after upgrading to 4.37. 

Error
Something has gone wrong. Check technical details for more details.
Error Code: AppMetadataFetchFailed
Multiple errors occurred: 'InternalServerError,InternalServerError,InternalServerError,InternalServerError,InternalServerError,InternalServerError,InternalServerError,InternalServerError'. Please see details.
UciError: Multiple errors occurred: 'InternalServerError,InternalServerError,InternalServerError,InternalServerError,InternalServerError,InternalServerError,InternalServerError,InternalServerError'. Please see details. at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.fd3fb478dbf7cd68db6b78dbb1a203bb.js:33:961647) at https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.3db6d13f2dd48983e7cec0e34c1ca719.js:4:23208

### Expected Behavior

App opens without errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Data Policy Impact Analysis

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Start the app...

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)
And also please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by HenningStrand** [comment]
Can close this issue as I do not have the same situation today. Now I can open the app without errors. Yesterday I saw the same error message in two different tenants (test/prod), today I don't. Both were in the European region.
