### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by nrayner73** [microsoft/coe-starter-kit#9157]
### Does this bug already exist in our backlog?

- [x] #9158

### Describe the issue

The Power Platform Admin View does not display all Power App applications in each environment, which causes issues with the results from the admin flow. For example, there are more than five applications, but the Power Platform Admin View only shows five. When I created a flow to review all applications shared with users, the flow produced the wrong result.
![Image](https://github.com/user-attachments/assets/299a5194-446a-4394-9d41-ae0e8bdd5ead)
![Image](https://github.com/user-attachments/assets/97f622de-ac50-4859-b51f-d01ff6c9057c)

### Expected Behavior

The Power Platform data syncs properly with the CoE inventory. The admin view should display a list of applications that reflects the actual number of applications in each environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Go to [[admi](https://make.preview.powerapps.com/environments/9c8bec4b-a60d-e2d4-b92f-9831e3530af5/apps)](https://make.preview.powerapps.com/environments/9c8bec4b-a60d-e2d4-b92f-9831e3530af5/apps)
2. Run Power Platform Admin View
3. Select Environment and pick an environment
4. Select the Resource menu, then review the list of applications in that environment and compare it to the actual list of applications from the Power Platform Admin Centre.

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

Then see if there are any sync flow errors to investigate. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d43b50b3-84d1-4894-a9a3-04d5d95fe8dc)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
