### ISSUE TITLE
[CoE Starter Kit - BUG] Flow does not turn on: Admin | Audit Logs | Sync Audit Logs (V2)

### ISSUE THREAD

**Issue by chris-nguyen-MSFT** [microsoft/coe-starter-kit#9171]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Setting up audit log components and wizard does not turn on `Admin | Audit Logs | Sync Audit Logs (V2) flows. `
Manual attempt to turn flow on returns below error:

`Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'ListDefns-AppID' of type 'OpenApiConnection' at line '1' and column '3672' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".`

JSON from flow:

```
  "runtimeConfiguration": {
    "paginationPolicy": {
      "minimumItemCount": 100000
    }
```

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run through audit logs wizard
2. Reach start flows page
3. start sync v2 flow (error returned)
4. attempt to turn flow on manually in Power Automate
5. Encounter error

**Comment by Jenefer-Monroe** [comment]
Hello. All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites]( https://learn.microsoft.com/power-platform/guidance/coe/setup#which-identity-should-i-use-to-install-the-coe-starter-kit).

**Comment by chris-nguyen-MSFT** [comment]
Thank you for the note, I double checked and the issue did occur 3 days after my trial had expired. 
I will close this item.
