### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot turn on flow | Admin | Compliance detail request v3

### ISSUE THREAD

**Issue by chris-nguyen-MSFT** [microsoft/coe-starter-kit#9175]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Similar to #9171 

`
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'List_Environments_not_excused_from_compliance' of type 'OpenApiConnection' at line '1' and column '6288' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".`

Code view of affected action:

```
"runtimeConfiguration": {
    "paginationPolicy": {
      "minimumItemCount": 100000
    }
```

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. use governance setup wizard
2. get to turn on flows step
3. turn on Admin | Compliance detail request v3, error says to manually turn on in Power Automate
4. turn on in Power Automate generates error

**Comment by Jenefer-Monroe** [comment]
Hello. All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites]( https://learn.microsoft.com/power-platform/guidance/coe/setup#which-identity-should-i-use-to-install-the-coe-starter-kit).

**Comment by chris-nguyen-MSFT** [comment]
Thank you for the note, I double checked and the issue did occur 3 days after my trial had expired. 
I will close this item.
