### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot turn on flow | Admin | Quarantine non-compliant apps

### ISSUE THREAD

**Issue by chris-nguyen-MSFT** [microsoft/coe-starter-kit#9176]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Similar to issues #9175 #9171 

`Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'List_apps_for_quarantine' of type 'OpenApiConnection' at line '1' and column '1901' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".`

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25

### What app or flow are you having the issue with?

Admin | Quarantine non-compliant apps

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

same repro steps as #9175

**Comment by Jenefer-Monroe** [comment]
Hello. All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites]( https://learn.microsoft.com/power-platform/guidance/coe/setup#which-identity-should-i-use-to-install-the-coe-starter-kit).

**Comment by chris-nguyen-MSFT** [comment]
Thank you for the note, I double checked and the issue did occur 3 days after my trial had expired. 
I will close this item.
