### ISSUE TITLE
Unable to get the Usage data in Power BI

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#9179]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

We are trying to load the App usage information filter in a custom Power BI which is using the dataflow. The data got stuck up to May 22, 2024. We are unable to get the data in Power BI after May 22, 2024.

Verified the storage account and we have usage info for all the months from May to October until now.

Thanks,
Devendra

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Dataflow

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Connect to the dataflow from Power BI
Load the App usage launch time to the Power BI.

**Comment by Jenefer-Monroe** [comment]
Hello the BYODL architecture for Data Export is no longer the plan of record for Data Export. We are actively working with the product team on the new architecture that will rely on Fabric instead of the Data Lake and hope to preview it to the community in fall of 2024.

As a result we are no longer suggesting users attempt to use BYODL as the pain of configuration is not something that will benefit you when the new version comes out, and issues that remain in BYODL are not being addressed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
