### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Get Security Role Users - RowID not found

### ISSUE THREAD

**Issue by PiZe0** [microsoft/coe-starter-kit#9187]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

The "SYNC HELPER - Get Security Role Users" flow repeatedly encounters isolated errors with the message: "Action 'Delete_it' failed: Entity 'admin_EnvironmentSecurityRolePermission' With Id = 8f6b1896-7392-ef11-8a69-7c1e525e270f Does Not Exist," where the Id varies, of course.

We have a total of 15 environments and no BYODL flows activated. The flow runs very often, as we have activated multiple security roles to be fetched in the "Tenant Security roles" table. But that doesn’t make sense why the flow can’t find the row (as seen in my last screenshot). Maybe it its deleting the rows somewhere else at the same time?

![Image](https://github.com/user-attachments/assets/eaebdf5b-b0d2-4510-b4cb-cba553046603)
![Image](https://github.com/user-attachments/assets/83df6ae8-7e7e-4f39-aeff-e36631f07de5)
![Image](https://github.com/user-attachments/assets/fd15b139-71e7-44c0-b4cd-210d690fe135)
![Image](https://github.com/user-attachments/assets/96097713-8aff-475d-98e3-7dfda94cfa2c)

### Expected Behavior

There should not be missing rows?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Are the records still in the table? 

My initial guess was the same as yours, that the flow is long running and so you end up with multiple instances running and one succeeds while the other fails because the records was already deleted. However that error message indicates it may be something else. 

Can you try to update the retry policy and see if that addresses? 

![Image](https://github.com/user-attachments/assets/602ab644-ab77-471c-a298-cd59b4e79928)
![Image](https://github.com/user-attachments/assets/66ad0c2a-d831-4e44-98fb-10ef897c9034)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
