### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#9191]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

The StarterKit Install wizard appears to get stuck on "Admin | Sync Template v3 (Connectors)"

![Image](https://github.com/user-attachments/assets/34bc07d8-b510-4528-844e-9c18d8b8bb86)

When I look at the flows despite the log reporting 2 successful runs when I look at the runs there are errors:

![Image](https://github.com/user-attachments/assets/8c7f133f-31a2-45f5-ac68-fc9dc4570385)

![Image](https://github.com/user-attachments/assets/79ee8a09-5b10-4d71-8749-f5bdf6ab5f6e)

![Image](https://github.com/user-attachments/assets/4c2599c5-4527-4595-9334-9245a2417510)

Is this expected behaviour and is there a way to get the flow to run successfully in the Setup Wizard?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43 Sept 2024

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Looks like you ended up with two records in the CoE Metadata table for the Connectors flow. 

Please go to the CoE Solution Metadata table, add columns so that you see Last Run and Last Run Passed. Filter to ObjectName = Admin | Sync Template v3 (Connectors) and delete the record that does not have Last Run data

![Image](https://github.com/user-attachments/assets/3c42b7c1-a6a2-4a1c-a60a-c9ad7713d028)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
