### ISSUE TITLE
[CoE Starter Kit - BUG] Flow Action Details is Exceeding Array Limits

### ISSUE THREAD

**Issue by michael-wright-pwc** [microsoft/coe-starter-kit#9198]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

We just upgraded our CoE core components and are noticing the Flow Action Details flow is now blowing up & failing in the exact same manner as ticket 8610 with exceeding array limits. And this is in our dev tenant where there are 1/1000 the flows in our prod tenant.

Currently "Admin | Sync Template v3 (Flow Action Details)" is scoped to the environment level (i.e. 1 run of this flow handles updating all flows in 1 env). Is it possible to scope it to the flow level instead? (so 1 run of this flow handles updating flow action details for 1 flow only). It seems like that would take care of these array issues in massive envs with many flows. For example, instead of triggering when an env record is updated, it could trigger when a flow record is updated.

### Expected Behavior

Arrays don't max out.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello I do have this local fixed in the V2 version of the kit. See https://github.com/microsoft/coe-starter-kit/issues/6819
Unfortunately we are not ready to release that due to some delays on the Data Export V2 work from the product team. 

Basically the strategy was to switch these to being per-flow. 

If we are not able to release the V2 version in Dec time frame then I will try and convince folks to allow me to shift that work back to V1 for a Dec release of V1.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
