### ISSUE TITLE
[CoE Starter Kit - BUG] Flows getting failed with insufficient priveleges to fetch data from certain Environments

### ISSUE THREAD

**Issue by Vaishu-Tennet** [microsoft/coe-starter-kit#9203]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

We have setup Core Components solution of 4.43 version, ![Image](https://github.com/user-attachments/assets/1f3dd4cf-5315-48fb-bfe0-dd4b90f86b7a)
Few Flows getting failed with below errors:
RetrievePrivilegeForUser: The user with id 91d30686-8190-ef11-8a6a-000d3ab4fe11 has not been assigned any roles. They need a role with the prvReadWorkflow privilege.
RetrievePrivilegeForUser: The user with id e04db5ea-1796-ef11-8a69-7c1e526121ce has not been assigned any roles. They need a role with the prvReadbot privilege.
RetrievePrivilegeForUser: The user with id ca19e388-743f-ef11-8409-002248878b1d has not been assigned any roles. They need a role with the prvReadAppModule privilege.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Business Process Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
This is likely due to the recent changes to PIM in the product. However, the build you are should have the workaround implemented. 

Can you please validate the following

1. Confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently? 
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

2. Validate that you ran the **_CoE Setup and Upgrade Wizard_** app after you installed/upgraded to 4.43

3. Share a screenshot like this so we can see what solutions you have installed in this environment. Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

4. Go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
Especially for these two flows: **_Admin | Sync Template v4 (Driver)_**, **_HELPER - Driver Escalation Check_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

5. See if there are any sync flow errors to investigate. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d43b50b3-84d1-4894-a9a3-04d5d95fe8dc)

**Comment by Vaishu-Tennet** [comment]
1. Yes Power Platform Admin Role is direct and Permanent.
![Image](https://github.com/user-attachments/assets/60649199-ebe2-48c0-97cb-1aa6942e4e29)
2. Run CoE Setup and Upgrade Wizard app - this is done while upgrading and setup.
3. ![Image](https://github.com/user-attachments/assets/16135adc-faa6-4bc0-af93-e4246449bb60)
4. Mandatory flows mentioned are turned on with no managed layers, except 2 which are attached
![Image](https://github.com/user-attachments/assets/8c611004-ab2d-4fb9-a58e-26388acee992)
![Image](https://github.com/user-attachments/assets/98a15aa3-7b4e-4926-9f9f-0f270049e8de)
![Image](https://github.com/user-attachments/assets/009025c2-fd46-4568-bf21-4a4a34d43191)
![Image](https://github.com/user-attachments/assets/c606902e-39f5-4ca6-b6f0-a8a0bc4b135f)
![Image](https://github.com/user-attachments/assets/f14a8f42-b513-4919-b0c1-1f3ae3c328ce)
 2 inventory failed flows
![Image](https://github.com/user-attachments/assets/6e1f6d89-92ee-4e25-ad07-00e87fc1c8ee)
 turnedd off flows
![Image](https://github.com/user-attachments/assets/e7ba85ee-8752-4529-9c23-a4b34cfb3190)

5. ![Image](https://github.com/user-attachments/assets/e87c5b9a-9525-4d9a-ba95-33ddede064ae)
![Image](https://github.com/user-attachments/assets/bb12c253-99e3-4f18-bc78-b299d1fe8d7c)
![Image](https://github.com/user-attachments/assets/1da24c8f-0862-4c40-87d4-c0efd5d1bb9f)

kindly help me with what is blocking

**Comment by Jenefer-Monroe** [comment]
Oh I see, you are not on Core version 4.43, but on Core version 4.22 which does not have the fix to the feature change I was referencing. 
![Image](https://github.com/user-attachments/assets/e9ba2d9d-f490-4492-9521-e903fa49f506)

I'll paste more information about the feature below. In short, **_you will need to upgrade to the latest version of the kit to see this fixed_**. 

## The product change
Here is information about the product feature: [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)
In short, the privileged roles no longer grant you permissions to individual environments.

## How to check if this is the case
1. Validate the user running the flow has direct and permanent assignment to the Power Platform Admin role.
Note that this is still required in order to perform the workaround, but is no longer sufficient.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

2. Take one of the target environments in your repro, one of the environments which is failing, and make sure the user running the flow has System Admin security role in that target environment.

## How to address
There is a system to [escalate a user to system admin](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles#self-elevate-to-the-system-administrator-role) in an environment provided by the product team.
Please upgrade to the August 2024 (4.37) release or greater which has this workaround integrated.

**Comment by Vaishu-Tennet** [comment]
![Image](https://github.com/user-attachments/assets/2f3da9a7-2455-4d40-9cf5-81a01b54bc44)
we are on 4.43 version only i have reposted same pic highlighting the version for you.
![Image](https://github.com/user-attachments/assets/ba62122f-a652-4983-ac76-23a63de77a30)
I am posting solution history as well for reference.

1. we already have Power Platform Admin Role assigned permanently to the service account which is used for setting up COE toolkit.
2. I've checked for the failed flows environment role, System Admin Role is already assigned, I've re submitted and flow ran successfully then.

Not sure on what basis they got failed initially. Is there anything else to be checked?

**Comment by Jenefer-Monroe** [comment]
Sorry about that, I dont know where I saw that other Core install build number. Let me think this through a little bit.

**Comment by Jenefer-Monroe** [comment]
I did not see the Driver flow and the Driver helper in your list, do you see them? 
![Image](https://github.com/user-attachments/assets/2a2cc427-fc03-4328-af55-23b5bbeb8169)

**Comment by Vaishu-Tennet** [comment]
![Image](https://github.com/user-attachments/assets/a38dcf58-af57-4ae2-bbae-dd8aa9bf7b1b)

**Comment by Jenefer-Monroe** [comment]
ok everything should be working then. 
Please find a repro of your issue, meaning an environment where you see this issue. 
Go find the user in PPAC UX and be sure it has the System Administrator Security Role. 

### How check to see a users environment permissions 
Browse to https://admin.powerplatform.microsoft.com/environments/ > find your environment > Settings > Users + permissions > Users
![image](https://github.com/user-attachments/assets/0ee1dadd-9dc5-487a-8b7a-a1cce0843094)
![image](https://github.com/user-attachments/assets/35aa7aae-8162-43cd-8101-6678b3792b7a)
![image](https://github.com/user-attachments/assets/425bf786-31b9-462e-9c92-650584f41f56)
Find your user > Click to see their settings > are they enabled? What role do they have?
![image](https://github.com/user-attachments/assets/a8e17a78-1ee7-416e-b974-6d21fbc298f3)
![image](https://github.com/user-attachments/assets/ea312158-6170-461b-b814-54da4bac6f85)
