### ISSUE TITLE
[CoE Starter Kit - BUG] Cross-tenant Isolation connection references still not working

### ISSUE THREAD

**Issue by zellos13** [microsoft/coe-starter-kit#9207]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

We've updated the CoE Starter Kit. We are now working on a June version. Everything is working fine except the cross-tenant isolation report.

We've set up the environment variable, and it's configured:

![Image](https://github.com/user-attachments/assets/b6ebfa18-4aac-44c1-8c2e-8df85aa525f9)

In our CoE Starter Kit - all new connection references are marked as cross-tenant:

![Image](https://github.com/user-attachments/assets/53ada17d-6c19-40df-8721-37dc9d76f1fb)

In the screenshot, I've hidden the names, but these are our - internal domains included in the environment variable but they are still marked as cross-tenant. Can you tell me why?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core 4.31

### What app or flow are you having the issue with?

Cross-tenant isolation report

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, 

We do not update the existing data set when you change the host domain, due to the API impact of having to check this every time the flows run. However new data collected going forward will respect the change.
To go back and change the existing data please see: https://github.com/microsoft/coe-starter-kit/issues/7164#issuecomment-1819498144

New new rows, these should be getting marked correctly. 
Please go to the most recent run of **_Admin | Sync Template v4 (Connection Identities)_**

Do you see the string you entered in the Host Domains env var here? 
![Image](https://github.com/user-attachments/assets/643098ac-fb61-4014-814a-9639a98200d2)

Then here you should see the host domain list you put in that env var plus the host of the identity running the flow. Do you see that? 
![Image](https://github.com/user-attachments/assets/ab99232e-c92e-4ad3-b33a-8b337ccdca3b)

If the domain you are concerned about one not in this list?

**Comment by zellos13** [comment]
Hi,

As for the old con-ref, yes, I know that you don't update them. I am referring only to the newly created ones.

And yes - this flow runs every day successfully and yes I can see the domains in the list there and yes - the second action contains the domains list with the one from the trigger.

![Image](https://github.com/user-attachments/assets/2def593d-09b2-4997-b493-3da0ddc9b76a)

![Image](https://github.com/user-attachments/assets/aa9f7cb6-a526-478b-9fd0-fbf70ce32564)

But I don't now what should be the outcome of this.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
