### ISSUE TITLE
[CoE Starter Kit - BUG] Helper Driver Escalation Check doesn't start - Clean Install

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#9210]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi Power CAT Team,

We recently decided to carry out a completely fresh install of the Power Platform CoE Starter Kit and have experienced the below issue:

When Installing the Core Components solution and running the Setup Wizard we saw that the Helper Driver Escalation Check and Admin Sync Template v4 (Driver) were not starting.

![Image](https://github.com/user-attachments/assets/de0cb4e3-d2f1-499a-a94b-662337f6a250)
 
![Image](https://github.com/user-attachments/assets/b2d49f16-4088-40c8-bdd4-b5f47f2d28df)

![Image](https://github.com/user-attachments/assets/51d15860-da6d-4734-9fba-7a2e786c2f82)

If we try starting the flow nothing happens...

There seems to be some serious issues with this flow?

### Expected Behavior

Expect the flows to start

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Helper Driver Escalation Check

### What method are you using to get inventory and telemetry?

None

**Comment by myatix** [comment]
Just an update...

I have now tried this 3 times by starting with a new environment every time and get the same issue reported above each time....

**Comment by Jenefer-Monroe** [comment]
What error message do you get when you try to turn the flow on from the Product UX?

**Comment by Jenefer-Monroe** [comment]
Please share the following screenshots: (note that you will need to be logged in to GitHub to share images)

1. Flow list
Via https://flow.microsoft.com/ please browse to the Core solution flows in your CoE Environment, and filter to flows with the word "Driver"
![Image](https://github.com/user-attachments/assets/1b304abf-9095-4254-bb84-70e5fb23b877)

2. Target flow
If you see **_HELPER - Driver Escalation Check_** in the list, click on it and share a picture of what you see
![Image](https://github.com/user-attachments/assets/4c984028-79d9-435d-8c29-57b34b094963)

3. Error when turn on
If you are able to load this flow please try to turn it on and show what error message you see
![Image](https://github.com/user-attachments/assets/44fbc25b-6d5e-4209-9e1f-aecac2a2923e)

4. Solutions installed
A screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Jenefer-Monroe** [comment]
Ok looks like this is something beyond my ability to assist. You will need to contact product support for this.
