### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Cloud Flows -Could not find flow Admin | Audit Logs | Sync Audit Logs (V2)

### ISSUE THREAD

**Issue by rajamanickamg2** [microsoft/coe-starter-kit#9229]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

My CoE Flows (SYNC HELPER - Cloud Flows) throws error recently Action 'Get_Flow_Owner_Role_as_Admin' failed and Could not find flow 'f3f31dea-4999-531c-ea8e-f593c15052d5'.

I have did some analysis and the flow Admin | Audit Logs | Sync Audit Logs (V2) is missing in the active flows view in the inventry table and I can see this flow in Deleted Flows. This is CoE flow and we didn't delete  this manually but this marked as deleted. I think thats the reason throws error But My question how come it is marked as Deleted.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, sorry having a little trouble following. 

I think you are saying that a flow is marked as deleted in the coe inventory table when it is not actually deleted from the tenant. 

However you are also saying that this call in **_SYNC HELPER - Cloud Flows_** also fails with saying that it could not find the same flow. 
![Image](https://github.com/user-attachments/assets/826bd54f-dedd-482b-906d-ce99105f52fb)

## Correct?
Is that accurate? 
If so it sounds like the product itself is not finding the flow sometimes when the flows are running. 
This typically happens when you have access issues. 

## PIM
Please confirm that the user identity installing and running the kit has the Power Platform Admin Role assigned both directly and permanently.
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

## Connections
Make sure the connections for the **_SYNC HELPER - Cloud Flows_** flow are the user that sets up and runs the flow, and that the connections are all green.
![Image](https://github.com/user-attachments/assets/c136b643-7875-4298-9ac9-b39b62a0b2e5)

**Comment by rajamanickamg2** [comment]
Is that accurate? Yes...

the workflow is running under Power Platform Admin service account.. we got to know this error from this sync flow throws error like unable to find this flow"**Admin | Audit Logs | Sync Audit Logs `(V2)**" This is marked as deleted in inventory table. My question is why it is marked as deleted.

**Comment by Jenefer-Monroe** [comment]
I'm trying to help deduce that. Please let me know:

## PIM
Please confirm that the user identity installing and running the kit has the Power Platform Admin Role assigned both directly and permanently.
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

## Connections on the SYNC HELPER - Cloud Flows flow
Make sure the connections for the **_SYNC HELPER - Cloud Flows_** flow are the user that sets up and runs the flow, and that the connections are all green.
![Image](https://github.com/user-attachments/assets/c136b643-7875-4298-9ac9-b39b62a0b2e5)

**Comment by rajamanickamg2** [comment]
Yes. I have verified that it looks same as your screenshot

**Comment by Jenefer-Monroe** [comment]
ok do you have a specific item that is marked deleted that should not be?

**Comment by rajamanickamg2** [comment]
Yes. Thats what I have mentioned earlier this workflow name"Admin | Audit Logs | Sync Audit Logs `(V2)" mentioned deleted in the inventory table .![Image](https://github.com/user-attachments/assets/97a3513a-4dab-4896-8125-edb7536bf268)

**Comment by Jenefer-Monroe** [comment]
Does this coincide with a running of  **_CLEANUP - Admin | Sync Template v4 (Check Deleted)_**

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
