### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log Sync V2 not capturing logs

### ISSUE THREAD

**Issue by DarkestOfNights** [microsoft/coe-starter-kit#9251]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

After the November 2024 update, the Audit Log Sync V2 Flow is not capturing any LaunchPowerApp log events when using the Graph connector. In reviewing flow runs, Events are returned from the query, but are filtered out prior to processing due to all being of RecordType 45 rather than 256. Any 256-type records in our tenant are only ApiEndpointCallEvent actions. This could just be an issue with GCC tenants.

### Expected Behavior

Audit logs are ingested

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Oh no. We were responding to this change https://admin.cloud.microsoft/?ref=MessageCenter/:/messages/MC912045
It did not occur to me that they might not make this change everywhere. 

I've reached out to the amazing internal GCC team to see if they know what's going on. 
And in the meantime I think the only workaround would be to import the old flow to run while we sort out what to do. 

Here is the old flow in a new solution so that it can be imported outside of Core. Please import and turn this one one, and the real one in Core off for now. 
[auditlogsbackupwithoutpurview_1_0_0_1_managed.zip](https://github.com/user-attachments/files/17722348/auditlogsbackupwithoutpurview_1_0_0_1_managed.zip)

Let me know how it goes.

**Comment by DarkestOfNights** [comment]
We have that same alert under a different message number: MC912042, the change just hasn't made it to our logs quite yet. I'll import this and let you know in just a few minutes. Thanks!

**Comment by DarkestOfNights** [comment]
@Jenefer-Monroe That worked, thank you. I'll be keeping an eye on our logging solution to determine when 256 messages include anything other than just ApiEndPointCallEvent actions so that I can move back over to the original flow. I am watching those messages for other governance purposes, and this may explain why I am not getting all of the messages I am expecting otherwise.

I will keep you updated when the logs switch over properly for GCC.

**Comment by osbornecc** [comment]
@Jenefer-Monroe, we're glad we found this as well.  The old flow in that new solution is what we needed to deploy to get the app launch data from the audit logs working again.  Thank you for providing it.

**Comment by Jenefer-Monroe** [comment]
I could never leave you all in the dust, here to help :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by adamx9035** [comment]
@Jenefer-Monroe We are in GCC tenant here. I could not find the MC912045 in the Message Center of O365 admin center. Is this because that change has not rolled out to our GCC tenant? Could you help provide the details about that change?

Reading the discussions above, it sounds like going forward the Admin | Audit Logs | Sync Audit Logs (V2) flow will continue to filter for RecordType of 256. But the audit logs it pulls down from the O365 side is still using RecordType of 45 which is documented at https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#auditlogrecordtype. I'm not seeing RecordType of 256 in this document. Do you have a reference about it? Thanks!
