### ISSUE TITLE
[CoE Starter Kit - BUG] The Office 365 Management API custom connector missing

### ISSUE THREAD

**Issue by brigidaanne94** [microsoft/coe-starter-kit#9256]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Imported the November 2024 solution, set up the API app in Azure, turned on the required flows and ran them, and I am still missing The Office 365 Management API custom connector that should have been imported from the solution. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

The Office 365 Management API custom connector

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, we deprecated the custom connector technique to gather Audit Logs back in ~July of 2023 due to several issues like lack of pagination and upgrade issues with custom connectors. The new technique is an HTTP action and requires an app registration. 

Please see https://github.com/microsoft/coe-starter-kit/issues/6018 for a write up on this issue and steps on how to proceed

**Comment by brigidaanne94** [comment]
Hello,
  I was reading this, but I didn't do an upgrade. I did a fresh install.

**Comment by Jenefer-Monroe** [comment]
Yes the custom connector is not be included any longer due to its support and maintenance costs. 

Going forward you will need to use the HTTP methodology to gather this data. There are two API's you can chose from. 
Please see the following for setup instructions

- [Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)
- [Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
