### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot turn on "HELPER - Driver escalation check" and "Admin| Sync Template V4 ( Driver)"

### ISSUE THREAD

**Issue by Service-WebDevPowerP** [microsoft/coe-starter-kit#9260]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I cannot enable the flows "HELPER - Driver escalation check" and "Admin| Sync Template V4 ( Driver)" they wont turn on via the set up and upgrade wizard ( screenshot 1) and I cant enable them directly via the flows themselves either ( Screenshot 2)

Is this expected ?

![Image](https://github.com/user-attachments/assets/73a11004-4746-45cf-bbf2-d93bbab6e9d8)

![Image](https://github.com/user-attachments/assets/5fbfacd6-32b7-4adc-9816-3b4393d3a1e0)

### Expected Behavior

N/a

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

"HELPER - Driver escalation check" and "Admin| Sync Template V4 ( Driver)"

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. It looks like the DLP policy that governs the environment was not updated to allow the new connector. 
Please update that policy to comply with the list shown here: [Validate data loss prevention (DLP) policies](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies)

**Comment by Service-WebDevPowerP** [comment]
Hi

I have double checked the list in the DLP policy and it matches that list. Power Platform for Admins v2 seems to be the new one and it is there. 

There is also another flow that is turned off. Is this expected?:

![Image](https://github.com/user-attachments/assets/d4457b32-391a-4a71-b691-4df1830ecdb7)

**Comment by Jenefer-Monroe** [comment]
That other flow is used in the setup wizard, you should be able to turn that one on manually. 

Let's focus on your DLP issue here, its hard for me to track multiple issues in a single ticket due to the number I interact with.

Unfortunately if the DLP policy is not applying correctly that is a product issue and not something I can help resolve. 

Usually though the issue is that either
1. You have recently updated the DLP and it has not yet propagated - note this can take up to 12 hours though it usually does not.
2. You have another DLP policies impacting the environment you were unaware of. We do have a column with this information in the kit. 
![Image](https://github.com/user-attachments/assets/757203ec-873c-47d5-9b99-00ece259b18e)

**Comment by Service-WebDevPowerP** [comment]
The setup Wizard is working now ( i mentioned it thinking maybe it was related) the other 2 flows though still wont turn on. I will look into the DLP Policy and get back to you
