### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by alikalik9** [microsoft/coe-starter-kit#9281]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I am using the Power BI dashboards from the CoE. However, I have customized one of the dashboards in Power BI Desktop by adding a custom measure, new pages, visuals, etc. With each CoE release, a new version of the dashboard is published, which is recommended to use.

This raises the question: Does it even make sense to make customizations if I’ll need to switch to a new version of the dashboard in about three months anyway? How can I manage or preserve my customizations effectively when upgrading to the latest version?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, yes you've run into the issue where the kit can either be used, used as an inspiration, or used and customized. 

Unfortunately we do not have a way to merge PBI changes between you folks and us, so you will just need to decide each time if updating the PBI is worth it to you. We do try to be fully transparent in the bug list each cycle so that you will know what you are missing if you do use our PBIT file from wherever you forked it.

Here for example you can see all the changes form the Nov release
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024
![Image](https://github.com/user-attachments/assets/b48bfc31-04e1-496e-b3fc-11d21b3bb9f1)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
