### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow / Apps Table - different IDs WorkflowEntityId

### ISSUE THREAD

**Issue by PiZe0** [microsoft/coe-starter-kit#9324]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

In the CoE Flow Table, all flows are listed. There are 4 columns: "Record GUID as String," "WorkflowEntityId," "FlowIDString," and "Flow."
These represent two distinct values across four different columns. The "Record GUID as String," "FlowIDString," and "Flow" values are identical, but the "WorkflowEntityId" value is different. The value in the "WorkflowEntityId" column can be found directly in the flow itself, either in the URL or via "GetFlowIdentifier."

When I search for a flow using the "Get Flow as Admin" action, I can find it using either the WorkflowEntityId (which I can get directly from the flow) or the other IDs (Record GUID, etc.).

Additionally, I’ve noticed that some flows in the Flow Table have no "WorkflowEntityId."

Then, I also looked into the PowerApps Table. There, I found "Record GUID as String," "AppIDString," and "App." For some apps, the values in these three columns are identical, while for others, they differ.

**Questions:
Why does the WorkflowEntityId exist, and why is it different from the other IDs?
Why do some flows in the Flow Table lack a WorkflowEntityId?
Why are there some apps in the App Table where the IDs are identical and others where they are not?**

![Image](https://github.com/user-attachments/assets/158252c0-d3a2-40f1-ad35-2ac21c49f181)

**Get Flow as Admin Action with Flow ID**
![Image](https://github.com/user-attachments/assets/9ce73651-885c-4cf1-a693-10ac3f0a94be)

**Get Flow as Admin Action with WorkflowIdentity**
![Image](https://github.com/user-attachments/assets/43988b02-7d00-40d6-b350-b940d171ac3f)

**Flow Table**
![Image](https://github.com/user-attachments/assets/0dc15f51-d406-4e00-b003-1686c247d6e5)

**Power Apps Table:**
![Image](https://github.com/user-attachments/assets/36f93eee-3ffc-44f5-a9b3-37613e917e37)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Questions:
## Record GUID as String
Across the kit you will find a string field in most tables that is identical to the records GUID. 
This is so that we could make an alternate key for the table. 

## Flow GUIDS
Why does the WorkflowEntityId exist, and why is it different from the other IDs?
Why do some flows in the Flow Table lack a WorkflowEntityId?

Flow GUIDs are rather complex. The short answer is that WorkflowEntityId represents a flow in a solution. 
So records without a WorkflowEntityId are flows that exist outside the context of a solution. 
I don't know why the product keeps both but I do know that they are used in different contexts. Ex you need one to get a URL and another to look up a row with the dataverse connector etc.

## Model Driven vs Canvas style apps
Why are there some apps in the App Table where the IDs are identical and others where they are not?

Our PowerApps Apps table stores both MDA and Canvas style apps when in reality these are different objects gathered and administered in different ways by the product. 
So MDA's (historically) did not have a unique GUID in each envt. So "Solutions Hub" had the same GUID in default and in other envts as well. So we had to generate a unique GUID to store them together in one table. 
This has changed recently and so the V2 version of CoE (etc coming Jan 2025) will not have this particular complexity.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
