### ISSUE TITLE
[CoE Starter Kit - BUG] Power Apps Apps table not updating

### ISSUE THREAD

**Issue by MaxTheMarshall-UK** [microsoft/coe-starter-kit#9335]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Since our update of the CoE Toolkit a couple of weeks ago, new Apps aren't appearing in the 'Power Apps App' table in the CoE environment.

It looks like it should be trigger by 
Admin | Sync Template v4 (Apps)
or
SYNC HELPER - Apps

But since the update it's not working. I've checked all other flows, and run the Wizard but all related flows seem to be turned on?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
## Upgrade success check
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

## Driver flow
Is the driver flow turned on? Has it been running? **_Admin | Sync Template v4 (Driver)_**

## Permissions check
Please confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
