### ISSUE TITLE
Help with Upgrade

### ISSUE THREAD

**Issue by KarumanchiVenkat** [microsoft/coe-starter-kit#9348]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

we need to update the CoE toolkit for latest reports to download

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.15

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. If you are on Core 3.15 that is ~March 2024 so upgrade may not work as we only test back 3 months. However you can give it a try and let me know when you hit issues. 

Upgrade is much like Install, you will install the solutions and then boot the setup wizard to ensure all new flows are on. 

Here is some more information that I can think of since then:
## DLP
New connectors to consider for your DLP: [Validate data loss prevention (DLP) policies](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies)

## Permissions
Confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently.
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

## General
For more information see [General upgrade help](https://learn.microsoft.com/power-platform/guidance/coe/after-setup)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
