### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by bleaeib** [microsoft/coe-starter-kit#9357]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi, 
The below feature was scheduled to be included in the Starter Kit.
https://github.com/microsoft/coe-starter-kit/issues/5541 
I was wondering how do we enable it. 
As we would like to see the audit event on DLP change, update or create from the audit log in the started kit.

Thanks

Pac

### What solution are you experiencing the issue with?

Audit Log

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately we have not been able to fund this work due to staffing limitations. You can use the existing audit logs patterns as an inspiration to create your own flows to do this work, but we are not staffed to assist with those customizations. 

Sorry we cannot help more in the near term.

**Comment by bleaeib** [comment]
Thanks for the quick update.

**Comment by Jenefer-Monroe** [comment]
Happy to be of service as best I can :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
