### ISSUE TITLE
[CoE Starter Kit - BUG]  COE Dashboard, Number of App ,Number of App makers not updating

### ISSUE THREAD

**Issue by vishnuguptapowerappsCOE** [microsoft/coe-starter-kit#9372]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

On COE Dashboard, Number of App ,Number of App makers not updating after 2nd Dec.
Deployed Nov 2024 kit in around 20th nov.
kindly suggest what to check

### Expected Behavior

Should show correct Apps and maker data after daily scheduled refresh

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
## solutions installed
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

## region / type
And also please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

## flows turned on
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

## driver flow running
Please validate that the driver flow is running and passing: Admin | Sync Template v4 (Driver)
![Image](https://github.com/user-attachments/assets/3db35a8e-ffe3-4fb5-8cb2-b6217ce69739)

## errors
Then see if there are any sync flow errors to investigate. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d43b50b3-84d1-4894-a9a3-04d5d95fe8dc)

**Comment by vishnuguptapowerappsCOE** [comment]
Hi Jenefer/Team
Attached below is Solutions screenshot.
Region in United States.


***@***.***

Below Error coming fot Turning on Sync Template v4 (Driver) flow.

***@***.***

In Syn Flow error. One flow is coming failure. CLEANUP - Admin | Sync Template v4 (Other Objects)

***@***.***
__

Vishnu Gupta
IT Chapter Lead - Senior Manager

***@***.***

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately images and attachments do not come through when you respond in email, you will need to log in to GitHub to share.

**Comment by vishnuguptapowerappsCOE** [comment]
[![Image](https://github.com/user-attachments/assets/1205ae24-b560-4bb4-a38b-0e9a60582c6e)
![Image](https://github.com/user-attachments/assets/a1549bd5-4a37-42a3-a7c6-67291d73143c)
![Image](https://github.com/user-attachments/assets/1891955d-b308-46b8-8a12-8aeed54947bf)
![Image](https://github.com/user-attachments/assets/57edbe5a-b671-4683-9912-c8f7947f5fce)
![Image](https://github.com/user-attachments/assets/8127781f-14e7-4724-90b5-b4ff602e80e6)
![Image](https://github.com/user-attachments/assets/8b686ad7-116e-47d6-9789-c150d3f6bd48)
![Image](https://github.com/user-attachments/assets/f3f3a7c0-1125-48da-94c6-2f7f07d36236)
![Image](https://github.com/user-attachments/assets/d7e4ba1a-e2d8-4958-beee-bbba7d582a25)
![Image](https://github.com/user-attachments/assets/4fcfb1ef-194d-4f90-be36-ead8fe26e49f)
](url)

**Comment by vishnuguptapowerappsCOE** [comment]
Can you see all attached screenshots

**Comment by vishnuguptapowerappsCOE** [comment]
Driver flow is showing some error due to dependency

**Comment by vishnuguptapowerappsCOE** [comment]
last app update on environment was done on 2nd December and driver flow ran on 26th Sep so i don't think App count has dependency on Driver flow

**Comment by vishnuguptapowerappsCOE** [comment]
@Jenefer-Monroe Screenshots attached

**Comment by Jenefer-Monroe** [comment]
The driver flow drives the entire inventory so if its not running then you wont get new inventory for any of your objects.
If you expand this column, does it show _upgrade? And is there a second instance of core in your list? 
![Image](https://github.com/user-attachments/assets/e0010473-abb5-4b58-8e65-0616224eff27)

Basically trying to see if your upgrade failed.

**Comment by vishnuguptapowerappsCOE** [comment]
@Jenefer-Monroe  What i need to check further. Also data was updating till 2nd Dec so KIt installation was Ok

**Comment by vishnuguptapowerappsCOE** [comment]
Also suggest whats use of flow **Admin | Sync Template v4 (Apps)**.
I can see its getting canceled after starting so if this one is culprit?

**Comment by vishnuguptapowerappsCOE** [comment]
![Image](https://github.com/user-attachments/assets/72abe9d2-3aa3-4b27-aa31-37d1e6f80969)

**Comment by Jenefer-Monroe** [comment]
We need to track one mystery at a time here. Let's focus on the Driver flow as without it nothing will work. 
Please answer this question, a screenshot would be ideal

Expand this column, does it show _upgrade? And is there a second instance of core in your list? 
![Image](https://github.com/user-attachments/assets/e0010473-abb5-4b58-8e65-0616224eff27)

**Comment by vishnuguptapowerappsCOE** [comment]
No second instance running![Image](https://github.com/user-attachments/assets/f07b1b44-2f2d-4b2b-923d-35de90b93523)

**Comment by vishnuguptapowerappsCOE** [comment]
no say _upgrade

**Comment by vishnuguptapowerappsCOE** [comment]
Turned this helper flow and now driver is working

**Comment by Jenefer-Monroe** [comment]
Good news. Thanks for letting me know!

Did you use the setup wizard? That should have turned this flow on for you.

**Comment by vishnuguptapowerappsCOE** [comment]
I did it manually.
Now data is coming as Driver flow started running.

__

Vishnu Gupta
IT Chapter Lead - Senior Manager

***@***.***

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
