### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow running too many actions

### ISSUE THREAD

**Issue by zellos13** [microsoft/coe-starter-kit#9380]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi,

One of our CoE Starter Kit flows is running too many actions, and we receive those messages daily:

![Image](https://github.com/user-attachments/assets/b82c1693-7e65-40af-ba61-1890c9c8b1c2)

Can you tell us if there is any way to optimize this or eliminate this problem? We would be grateful.

Cheers,
Daniel

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2024

### What app or flow are you having the issue with?

Admin | Sync Template v4 (PVA)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately that flow has already been optimized to the current known level. 

The good news is that copilots are in progress now for the upcoming new Data Export features from the product team and so future iterations of the kit will be able to access that information. 

In the meantime, you would need to add a [process license](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/deep-dive-on-specific-license#power-automate-process-license) so that the flow has its own larger pool of API calls to pull from.

**Comment by zellos13** [comment]
Hi,

Thank you for your answer. Do you know in which month the updated version that does not cause these problems will be available?

**Comment by zellos13** [comment]
Thanks for the information!
