### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by raj835** [microsoft/coe-starter-kit#949]
### Describe the issue

I am using CenterofExcellenceCoreComponentsTeams_1_998_managed solution .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.998

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

While turning ON this flow ,getting error .I have excluded the Teams environment ( which got automatically created after adding Power App ) from DLP policy .

Even after excluding the environment I am getting error .
![CoETeams1](https://user-images.githubusercontent.com/66004078/127952645-64e457e7-25a0-4dc7-8003-61179eb3f71e.PNG)

**Comment by JeneferM-MSFT** [comment]
I'm afraid I cannot help here. If you really dont have any DLP policies that are at issue, then you have hit a product issue. 
We have seen caching issues in the past where changes to DLP don't take right away. You may have to contact support.

**Comment by raj835** [comment]
We have only 1 DLP policy applied in our Tenant ,and we have excluded this environment from that DLP policy .

**Comment by JeneferM-MSFT** [comment]
I believe what you are saying is that there are no DLP policies impacting this environment. If that is the case, then you should not see any DLP errors when using any object in the environment. I'm afraid this issue is beyond how I can help as you are hitting product issues and not toolkit issues. 

Did you just exclude it recently? You may have hit a caching issue. 

You will need to contact support, the issue you are facing is with the product incorrectly identifying DLP issues.

**Comment by raj835** [comment]
I have excluded it from DLP one week before .

**Comment by JeneferM-MSFT** [comment]
ok im afraid you will need to create a support ticket then. 
closing out as nothing we can do to help from the toolkit pov
