### ISSUE TITLE
[CoE Starter Kit - Docs] Setup Documentation

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#967]
Better pre-requisites - pull together all the groups / teams / etc that will be needed, all the roles that are required, what access/permission is needed for various connectors and resources.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
