### ISSUE TITLE
[CoE Starter Kit - ENHANCEMENT] Add ability to monitor portals in the CoE inventory

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#973]
### Describe the issue

sync flow for gathering the the portals across the tenant
portal table to hold this
the portal one-pager in the PBI

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Portals)

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
