### ISSUE TITLE
[CoE Starter Kit - BUG] Warrington is back in the USA

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#977]
### Describe the issue

Hi 

In the Makers page of the PowerBI dashboard Warrington has moved back to the USA.
![thumbnail_WarringtonbackintheUSA](https://user-images.githubusercontent.com/8484048/128733370-83251fcf-fb4d-4734-ab19-12da7b162f7e.jpg)

### Expected Behavior

Warrington should be in the UK

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

PowerBI dashboard

### Steps To Reproduce

Display Makers page of the PowerBI dashboard

**Comment by manuelap-msft** [comment]
Fixed this for the September release.

You can update this yourself by using the "Country, City" field in the Maker table (it's currently just using the City field):
![image](https://user-images.githubusercontent.com/55705669/131492107-c5a77d29-9386-4a10-a27e-287fa2cdf31d.png)

**Comment by NPrice99** [comment]
Thanks Manuela

**Comment by mikefactorial** [comment]
@NPrice99 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
