### ISSUE TITLE
[CoE Starter Kit] Cleanup - Admin | Sync Template v3 (Check Deleted) hitting content throughput thresholds

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#991]
The Cleanup - Admin | Sync Template v3 (Check Deleted) is hitting the content throughput limit of 50 GB for large customers: https://docs.microsoft.com/en-us/power-automate/limits-and-config#content-throughput-limits 

Need to check if there's potential for optimization in reducing the fields selected and brought back into the flow. Make sure all Dataverse queries only bring back fields needed. Potentially split the flow into separate flows per resource - e.g. one for apps, one for flows, one for chatbots.

@JeneferM-MSFT would you be able to look at this for September? Thank you!

**Comment by JeneferM-MSFT** [comment]
its only my favorite flow to fix (kidding not kidding)

**Comment by JeneferM-MSFT** [comment]
code complete and locally tested. In the hands of two customers for large tenant testing now.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
