### ISSUE TITLE
[CoE Starter Kit - Backlog] Power BI Dashboard - App Detail - add date filter for launches / sessions on this page

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#997]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/987

<div type='discussions-op-text'>

<sup>Originally posted by **patrickpooon02** August 10, 2021</sup>
Anyone can advise the top left 2 fields' definition? The "launches" and "users of this app" is calculated based on what elements?

![image](https://user-images.githubusercontent.com/82566841/128828469-4287cafe-46d8-478c-8a99-f5e74d34c71b.png)

</div>

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
